export interface HelmPresetFile {
  settings?: Record<string, number>;
}

export const HELM_PARAMETER_ORDER = [
  'amp_attack',
  'amp_decay',
  'amp_release',
  'amp_sustain',
  'arp_frequency',
  'arp_gate',
  'arp_octaves',
  'arp_on',
  'arp_pattern',
  'arp_sync',
  'arp_tempo',
  'beats_per_minute',
  'cross_modulation',
  'cutoff',
  'delay_dry_wet',
  'delay_feedback',
  'delay_frequency',
  'delay_on',
  'delay_sync',
  'delay_tempo',
  'distortion_on',
  'distortion_type',
  'distortion_drive',
  'distortion_mix',
  'fil_attack',
  'fil_decay',
  'fil_env_depth',
  'fil_release',
  'fil_sustain',
  'filter_saturation',
  'filter_drive',
  'filter_blend',
  'filter_type',
  'filter_style',
  'filter_shelf',
  'filter_on',
  'formant_on',
  'formant_x',
  'formant_y',
  'keytrack',
  'legato',
  'mod_attack',
  'mod_decay',
  'mod_release',
  'mod_sustain',
  'mono_lfo_1_amplitude',
  'mono_lfo_1_frequency',
  'mono_lfo_1_retrigger',
  'mono_lfo_1_sync',
  'mono_lfo_1_tempo',
  'mono_lfo_1_waveform',
  'mono_lfo_2_amplitude',
  'mono_lfo_2_frequency',
  'mono_lfo_2_retrigger',
  'mono_lfo_2_sync',
  'mono_lfo_2_tempo',
  'mono_lfo_2_waveform',
  'noise_volume',
  'num_steps',
  'osc_1_transpose',
  'osc_1_tune',
  'osc_1_unison_detune',
  'osc_1_unison_voices',
  'osc_1_volume',
  'osc_1_waveform',
  'osc_2_transpose',
  'osc_2_tune',
  'osc_2_unison_detune',
  'osc_2_unison_voices',
  'osc_2_volume',
  'osc_2_waveform',
  'osc_feedback_amount',
  'osc_feedback_transpose',
  'osc_feedback_tune',
  'osc_mix',
  'pitch_bend_range',
  'poly_lfo_amplitude',
  'poly_lfo_frequency',
  'poly_lfo_sync',
  'poly_lfo_tempo',
  'poly_lfo_waveform',
  'polyphony',
  'portamento',
  'portamento_type',
  'resonance',
  'reverb_damping',
  'reverb_dry_wet',
  'reverb_feedback',
  'reverb_on',
  'step_frequency',
  'step_seq_00',
  'step_seq_01',
  'step_seq_02',
  'step_seq_03',
  'step_seq_04',
  'step_seq_05',
  'step_seq_06',
  'step_seq_07',
  'step_seq_08',
  'step_seq_09',
  'step_seq_10',
  'step_seq_11',
  'step_seq_12',
  'step_seq_13',
  'step_seq_14',
  'step_seq_15',
  'step_seq_16',
  'step_seq_17',
  'step_seq_18',
  'step_seq_19',
  'step_seq_20',
  'step_seq_21',
  'step_seq_22',
  'step_seq_23',
  'step_seq_24',
  'step_seq_25',
  'step_seq_26',
  'step_seq_27',
  'step_seq_28',
  'step_seq_29',
  'step_seq_30',
  'step_seq_31',
  'step_sequencer_retrigger',
  'step_sequencer_sync',
  'step_sequencer_tempo',
  'step_smoothing',
  'stutter_frequency',
  'stutter_sync',
  'stutter_tempo',
  'stutter_on',
  'stutter_resample_frequency',
  'stutter_resample_sync',
  'stutter_resample_tempo',
  'stutter_softness',
  'sub_shuffle',
  'sub_octave',
  'sub_volume',
  'sub_waveform',
  'unison_1_harmonize',
  'unison_2_harmonize',
  'velocity_track',
  'volume',
] as const;

const HELM_PARAMETER_INDEX = new Map<string, number>(
  HELM_PARAMETER_ORDER.map((parameterName, parameterIndex) => [parameterName, parameterIndex]),
);

export interface HelmParameterUpdate {
  paramId: number;
  value: number;
}

export function buildHelmParameterUpdates(preset: HelmPresetFile): HelmParameterUpdate[] {
  if (!preset.settings) {
    return [];
  }

  const updates: HelmParameterUpdate[] = [];
  for (const [parameterName, value] of Object.entries(preset.settings)) {
    const paramId = HELM_PARAMETER_INDEX.get(parameterName);
    if (paramId === undefined || typeof value !== 'number' || !Number.isFinite(value)) {
      continue;
    }
    updates.push({ paramId, value });
  }

  return updates;
}
