/* ====================================================================
 * Auto-generated by asm68k-to-c transpiler
 * Source: Core Design.asm
 *
 * This file was mechanically translated from Motorola 68000 assembly.
 * Original ASM instructions appear as inline comments.
 * ==================================================================== */

#include "paula_soft.h"
#include <stdint.h>

/* -- 68k Register File ------------------------------------------------
 * Data registers D0-D7:  general-purpose 32-bit registers.
 * Address registers A0-A6: pointer registers (32-bit).
 * SP (A7): stack pointer.  PC: program counter (unused in transpiled code).
 * Flags: Z (zero), N (negative), C (carry), V (overflow), X (extend).
 * -------------------------------------------------------------------- */
static uint32_t d0,d1,d2,d3,d4,d5,d6,d7;
static uint32_t a0,a1,a2,a3,a4,a5,a6,sp,pc;
#define a7 sp  /* A7 is the stack pointer */
static int flag_z=0, flag_n=0, flag_c=0, flag_v=0, flag_x=0;
static uint16_t ccr = 0;  /* condition code register (for MOVE SR/CCR) */
static uint16_t sr = 0;   /* status register (interrupt mask bits etc.) */

/* -- Sub-register Accessors -------------------------------------------
 * W(d0) -- access the low 16 bits of d0 (read/write).
 * B(d0) -- access the low 8 bits of d0 (read/write).
 * Example: W(d0) = 0x1234;  // sets d0.w, leaves upper 16 bits unchanged
 * -------------------------------------------------------------------- */
#define W(r)  (*((uint16_t*)&(r)))
#define B(r)  (*((uint8_t*)&(r)))

/* -- Memory Access (Big-Endian) ---------------------------------------
 * The 68k is big-endian; these macros byte-swap on little-endian hosts.
 * Uses memcpy for alignment-safe access (68k allows unaligned word/long).
 *
 * READ8(addr)       -- read  byte from address
 * READ16(addr)      -- read  big-endian word from address
 * READ32(addr)      -- read  big-endian longword from address
 * WRITE8(addr,v)    -- write byte to address
 * WRITE16(addr,v)   -- write big-endian word to address
 * WRITE32(addr,v)   -- write big-endian longword to address
 * READ16_POST(reg)  -- read word, then reg += 2  (simulates (An)+ mode)
 * WRITE16_PRE(reg,v)-- reg -= 2, then write word (simulates -(An) mode)
 * -------------------------------------------------------------------- */
#include <string.h>
#define READ8(addr)   (*((const uint8_t*)(uintptr_t)(addr)))
#define WRITE8(addr,v)  (*((uint8_t*)(uintptr_t)(addr)) = (uint8_t)(v))
static inline uint16_t _rd16(uintptr_t a) { uint16_t v; memcpy(&v,(void*)a,2); return v; }
static inline uint32_t _rd32(uintptr_t a) { uint32_t v; memcpy(&v,(void*)a,4); return v; }
static inline void _wr16(uintptr_t a,uint16_t v) { memcpy((void*)a,&v,2); }
static inline void _wr32(uintptr_t a,uint32_t v) { memcpy((void*)a,&v,4); }
#if defined(__BYTE_ORDER__) && __BYTE_ORDER__ == __ORDER_BIG_ENDIAN__
#define READ16(addr)  _rd16((uintptr_t)(addr))
#define READ32(addr)  _rd32((uintptr_t)(addr))
#define WRITE16(addr,v) _wr16((uintptr_t)(addr),(uint16_t)(v))
#define WRITE32(addr,v) _wr32((uintptr_t)(addr),(uint32_t)(v))
#else
#define READ16(addr)  __builtin_bswap16(_rd16((uintptr_t)(addr)))
#define READ32(addr)  __builtin_bswap32(_rd32((uintptr_t)(addr)))
#define WRITE16(addr,v) _wr16((uintptr_t)(addr),__builtin_bswap16((uint16_t)(v)))
#define WRITE32(addr,v) _wr32((uintptr_t)(addr),__builtin_bswap32((uint32_t)(v)))
#endif
#define READ8_POST(r)   ({ uint32_t _r=(r); (r)+=1; READ8(_r); })
#define READ16_POST(r)  ({ uint32_t _r=(r); (r)+=2; READ16(_r); })
#define READ32_POST(r)  ({ uint32_t _r=(r); (r)+=4; READ32(_r); })
#define READ8_PRE(r)    ({ (r)-=1; READ8(r); })
#define READ16_PRE(r)   ({ (r)-=2; READ16(r); })
#define READ32_PRE(r)   ({ (r)-=4; READ32(r); })
#define WRITE8_POST(r,v)  ({ WRITE8(r,v);  (r)+=1; })
#define WRITE16_POST(r,v) ({ WRITE16(r,v); (r)+=2; })
#define WRITE32_POST(r,v) ({ WRITE32(r,v); (r)+=4; })
#define WRITE8_PRE(r,v)   ({ (r)-=1; WRITE8(r,v); })
#define WRITE16_PRE(r,v)  ({ (r)-=2; WRITE16(r,v); })
#define WRITE32_PRE(r,v)  ({ (r)-=4; WRITE32(r,v); })

/* -- Rotation Helpers -------------------------------------------------
 * ROL32(v,n) -- rotate 32-bit value left by n bits
 * ROR32(v,n) -- rotate 32-bit value right by n bits
 * -------------------------------------------------------------------- */
#define ROL32(v,n)  (((v)<<(n))|((v)>>(32-(n))))
#define ROR32(v,n)  (((v)>>(n))|((v)<<(32-(n))))

/* -- Hardware Write Interception --------------------------------------
 * Many 68k replayers load $DFF000 into a register and then write to
 * channel offsets (e.g. MOVE.W d0,$A8(a0) for volume on channel 0).
 * These runtime checks intercept writes to the Paula/DMACON address
 * range and route them to the paula_soft API instead of memory.
 * -------------------------------------------------------------------- */
static inline void hw_write8(uint32_t addr, uint8_t val) {
  if (addr >= 0xDFF000 && addr < 0xE00000) return; /* ignore byte writes to custom chips */
  WRITE8(addr, val);
}
static inline void hw_write16(uint32_t addr, uint16_t val) {
  if (addr >= 0xDFF0A0 && addr <= 0xDFF0DF) {
    int ch = (addr - 0xDFF0A0) >> 4;
    int reg = (addr & 0x0F);
    switch (reg) {
      case 0x06: paula_set_period(ch, val); return;
      case 0x08: paula_set_volume(ch, (uint8_t)val); return;
      case 0x04: paula_set_length(ch, val); return;
      default: return; /* AUDxDAT or unknown */
    }
  }
  if (addr == 0xDFF096) { paula_dma_write(val); return; }
  if (addr >= 0xDFF000 && addr < 0xE00000) return; /* other custom chip writes */
  if (addr >= 0xBF0000 && addr < 0xC00000) return; /* CIA writes */
  WRITE16(addr, val);
}
static inline void hw_write32(uint32_t addr, uint32_t val) {
  if (addr >= 0xDFF0A0 && addr <= 0xDFF0DF) {
    int ch = (addr - 0xDFF0A0) >> 4;
    int reg = (addr & 0x0F);
    if (reg == 0x00) { paula_set_sample_ptr(ch, (const int8_t*)(uintptr_t)val); return; }
  }
  if (addr >= 0xDFF000 && addr < 0xE00000) {
    /* Fallback: treat as two word writes (big-endian high word first) */
    hw_write16(addr, (uint16_t)(val >> 16));
    hw_write16(addr + 2, (uint16_t)val);
    return;
  }
  if (addr >= 0xBF0000 && addr < 0xC00000) return; /* CIA writes */
  WRITE32(addr, val);
}

/* -- EQU Constants ------------------------------------------------- */
#define SubSongs 4
#define LoadSize 12
#define SongSize 20
#define SamplesSize 28
#define Samples 36
#define CalcSize 44
#define SpecialInfo 52
#define AuthorName 60
#define SongName 68

/* -- Unresolved Symbols -------------------------------------------- */
/* These symbols come from include files not available to the transpiler. */
/* DTP_* */
#ifndef DTP_PlayerVersion
#define DTP_PlayerVersion 0
#endif
#ifndef DTP_RequestDTVersion
#define DTP_RequestDTVersion 0
#endif
#ifndef DTP_PlayerName
#define DTP_PlayerName 0
#endif
#ifndef DTP_Creator
#define DTP_Creator 0
#endif
#ifndef DTP_DeliBase
#define DTP_DeliBase 0
#endif
#ifndef DTP_Check1
#define DTP_Check1 0
#endif
#ifndef DTP_Interrupt
#define DTP_Interrupt 0
#endif
#ifndef DTP_SubSongRange
#define DTP_SubSongRange 0
#endif
#ifndef DTP_InitPlayer
#define DTP_InitPlayer 0
#endif
#ifndef DTP_EndPlayer
#define DTP_EndPlayer 0
#endif
#ifndef DTP_InitSound
#define DTP_InitSound 0
#endif
#ifndef DTP_EndSound
#define DTP_EndSound 0
#endif
#ifndef DTP_Volume
#define DTP_Volume 0
#endif
#ifndef DTP_Balance
#define DTP_Balance 0
#endif
/* EP_* */
#ifndef EP_PlayerVersion
#define EP_PlayerVersion 0
#endif
#ifndef EP_Check3
#define EP_Check3 0
#endif
#ifndef EP_Get_ModuleInfo
#define EP_Get_ModuleInfo 0
#endif
#ifndef EP_SampleInit
#define EP_SampleInit 0
#endif
#ifndef EP_ModuleChange
#define EP_ModuleChange 0
#endif
#ifndef EP_Voices
#define EP_Voices 0
#endif
#ifndef EP_StructInit
#define EP_StructInit 0
#endif
#ifndef EP_Flags
#define EP_Flags 0
#endif
/* _other* */
#ifndef WT
#define WT 0
#endif
#ifndef EQU
#define EQU 0
#endif
#ifndef setzen
#define setzen 0
#endif
#ifndef _LVOSetIntVector
#define _LVOSetIntVector 0
#endif
#ifndef _LVOLoadSeg
#define _LVOLoadSeg 0
#endif
#ifndef _LVOUnLoadSeg
#define _LVOUnLoadSeg 0
#endif
/* EPB_* */
#ifndef EPB_Volume
#define EPB_Volume 0
#endif
#ifndef EPB_Balance
#define EPB_Balance 0
#endif
#ifndef EPB_ModuleInfo
#define EPB_ModuleInfo 0
#endif
#ifndef EPB_Voices
#define EPB_Voices 0
#endif
#ifndef EPB_SampleInfo
#define EPB_SampleInfo 0
#endif
#ifndef EPB_Songend
#define EPB_Songend 0
#endif
#ifndef EPB_Analyzer
#define EPB_Analyzer 0
#endif
#ifndef EPB_NextSong
#define EPB_NextSong 0
#endif
#ifndef EPB_PrevSong
#define EPB_PrevSong 0
#endif
#ifndef EPB_Restart
#define EPB_Restart 0
#endif
#ifndef TAG_DONE
#define TAG_DONE 0
#endif
/* UPS_* */
#ifndef UPS_SizeOF
#define UPS_SizeOF 0
#endif
#ifndef UPS_Voice1Vol
#define UPS_Voice1Vol 0
#endif
#ifndef UPS_Voice2Vol
#define UPS_Voice2Vol 0
#endif
#ifndef UPS_Voice3Vol
#define UPS_Voice3Vol 0
#endif
#ifndef UPS_Voice4Vol
#define UPS_Voice4Vol 0
#endif
#ifndef UPS_Voice1Adr
#define UPS_Voice1Adr 0
#endif
#ifndef UPS_Voice2Adr
#define UPS_Voice2Adr 0
#endif
#ifndef UPS_Voice3Adr
#define UPS_Voice3Adr 0
#endif
#ifndef UPS_Voice4Adr
#define UPS_Voice4Adr 0
#endif
#ifndef UPS_Voice1Len
#define UPS_Voice1Len 0
#endif
#ifndef UPS_Voice1Per
#define UPS_Voice1Per 0
#endif
#ifndef UPS_Voice2Per
#define UPS_Voice2Per 0
#endif
#ifndef UPS_Voice3Per
#define UPS_Voice3Per 0
#endif
#ifndef UPS_Voice4Per
#define UPS_Voice4Per 0
#endif
#ifndef UPS_DMACon
#define UPS_DMACon 0
#endif
#ifndef UPS_Enabled
#define UPS_Enabled 0
#endif
#ifndef UPS_Flags
#define UPS_Flags 0
#endif
/* EPG_* */
#ifndef EPG_ARG1
#define EPG_ARG1 0
#endif
#ifndef EPG_ARG3
#define EPG_ARG3 0
#endif
#ifndef EPG_ARG2
#define EPG_ARG2 0
#endif
#ifndef EPG_ARG5
#define EPG_ARG5 0
#endif
#ifndef EPG_ARG4
#define EPG_ARG4 0
#endif
#ifndef EPG_ARGN
#define EPG_ARGN 0
#endif
#ifndef EPG_ModuleChange
#define EPG_ModuleChange 0
#endif
#ifndef EPG_SampleInfoStructure
#define EPG_SampleInfoStructure 0
#endif
/* dtg_* */
#ifndef dtg_SndLBal
#define dtg_SndLBal 0
#endif
#ifndef dtg_SndVol
#define dtg_SndVol 0
#endif
#ifndef dtg_SndRBal
#define dtg_SndRBal 0
#endif
#ifndef dtg_ChkData
#define dtg_ChkData 0
#endif
#ifndef dtg_SongEnd
#define dtg_SongEnd 0
#endif
#ifndef dtg_DOSBase
#define dtg_DOSBase 0
#endif
#ifndef dtg_PathArrayPtr
#define dtg_PathArrayPtr 0
#endif
#ifndef dtg_AudioAlloc
#define dtg_AudioAlloc 0
#endif
#ifndef dtg_SndNum
#define dtg_SndNum 0
#endif
#ifndef EPR_NotEnoughMem
#define EPR_NotEnoughMem 0
#endif
#ifndef ENPP_AllocSampleStruct
#define ENPP_AllocSampleStruct 0
#endif
/* EPS_* */
#ifndef EPS_Adr
#define EPS_Adr 0
#endif
#ifndef EPS_Length
#define EPS_Length 0
#endif
#ifndef EPS_Volume
#define EPS_Volume 0
#endif
#ifndef EPS_Type
#define EPS_Type 0
#endif
#ifndef EPS_Flags
#define EPS_Flags 0
#endif
#ifndef USITY_RAW
#define USITY_RAW 0
#endif
/* USIB_* */
#ifndef USIB_Playable
#define USIB_Playable 0
#endif
#ifndef USIB_Saveable
#define USIB_Saveable 0
#endif
#ifndef USIB_8BIT
#define USIB_8BIT 0
#endif
/* MI_* */
#ifndef MI_SubSongs
#define MI_SubSongs 0
#endif
#ifndef MI_LoadSize
#define MI_LoadSize 0
#endif
#ifndef MI_Songsize
#define MI_Songsize 0
#endif
#ifndef MI_SamplesSize
#define MI_SamplesSize 0
#endif
#ifndef MI_Samples
#define MI_Samples 0
#endif
#ifndef MI_Calcsize
#define MI_Calcsize 0
#endif
#ifndef MI_SpecialInfo
#define MI_SpecialInfo 0
#endif
#ifndef MI_AuthorName
#define MI_AuthorName 0
#endif
#ifndef MI_SongName
#define MI_SongName 0
#endif
#ifndef MI_Prefix
#define MI_Prefix 0
#endif
/* UPSB_* */
#ifndef UPSB_Adr
#define UPSB_Adr 0
#endif
#ifndef UPSB_Len
#define UPSB_Len 0
#endif
#ifndef UPSB_Per
#define UPSB_Per 0
#endif
#ifndef UPSB_Vol
#define UPSB_Vol 0
#endif
/* INTB_* */
#ifndef INTB_AUD0
#define INTB_AUD0 0
#endif
#ifndef INTB_AUD1
#define INTB_AUD1 0
#endif
#ifndef INTB_AUD2
#define INTB_AUD2 0
#endif
#ifndef INTB_AUD3
#define INTB_AUD3 0
#endif

/* -- Packed Data Section -------------------------------------------- */
/* All data labels packed into a single contiguous byte array matching
 * 68k memory layout. Accessor macros provide typed pointer access. */
uint8_t _ds[940] = {
  0x24,0x56,0x45,0x52,0x3a,0x20,0x43,0x6f,0x72,0x65,0x20,0x44,0x65,0x73,0x69,0x67,
  0x6e,0x20,0x70,0x6c,0x61,0x79,0x65,0x72,0x20,0x6d,0x6f,0x64,0x75,0x6c,0x65,0x20,
  0x56,0x31,0x2e,0x30,0x20,0x28,0x31,0x37,0x20,0x46,0x65,0x62,0x20,0x32,0x30,0x30,
  0x34,0x29,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x01,0x00,0x00,0x00,0x00, /* Tags@52 */
  0x00,0x00,0x00,0x09,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,
  0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,
  0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,
  0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,
  0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,
  0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,
  0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,
  0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,
  0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,
  0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,
  0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,
  0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,
  0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x43,0x6f,0x72,0x65, /* PlayerName@268 */
  0x20,0x44,0x65,0x73,0x69,0x67,0x6e,0x00,0x28,0x63,0x29,0x20,0x31,0x39,0x38,0x39, /* Creator@280 */
  0x2d,0x39,0x30,0x20,0x62,0x79,0x20,0x47,0x72,0x65,0x6d,0x6c,0x69,0x6e,0x20,0x47,
  0x72,0x61,0x70,0x68,0x69,0x63,0x73,0x2c,0x0a,0x61,0x64,0x61,0x70,0x74,0x65,0x64,
  0x20,0x62,0x79,0x20,0x57,0x61,0x6e,0x74,0x65,0x64,0x20,0x54,0x65,0x61,0x6d,0x00,
  0x43,0x4f,0x52,0x45,0x2e,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00, /* Prefix@336, DeliBase@342, ModulePtr@346, PlayPtr@350 */
  0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00, /* AudioPtr@354, InitSongPtr@358, EndSongPtr@362, SampleInfoPtr@366 */
  0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00, /* EndSampleInfoPtr@370, EagleBase@374, Change@378, ChangeLen@380 */
  0x00,0x00,0x00,0x40,0x00,0x40,0x00,0x01,0x00,0x01,0x00,0x01,0x00,0x01,0x00,0x00, /* SongEndFlag@384, RightVolume@386, LeftVolume@388, Voice1@390, Voice2@392, Voice3@394, Voice4@396, OldVoice1@398 */
  0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00, /* OldVoice2@400, OldVoice3@402, OldVoice4@404, StructAdr@406, InfoBuffer@408 */
  0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,
  0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,
  0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,
  0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,
  0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00, /* Channel0@492 */
  0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00, /* Channel1@496, Channel2@500, Channel3@504, StructInt@508 */
  0x00,0x00,0x00,0x00,0x02,0x05,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00, /* IntAddress@526 */
  0x00,0x00,0x43,0x6f,0x72,0x65,0x20,0x44,0x65,0x73,0x69,0x67,0x6e,0x20,0x41,0x75, /* IntName@530 */
  0x64,0x69,0x6f,0x20,0x49,0x6e,0x74,0x65,0x72,0x72,0x75,0x70,0x74,0x00,0x00,0x00,
  0x43,0x6f,0x64,0x65,0x30,0x2d,0x50,0x61,0x74,0x63,0x68,0x54,0x61,0x62,0x6c,0x65, /* PatchTable@560 */
  0x28,0x43,0x6f,0x64,0x65,0x30,0x45,0x6e,0x64,0x2d,0x43,0x6f,0x64,0x65,0x30,0x29,
  0x00,0x02,0xff,0xff,0x50,0x61,0x74,0x63,0x68,0x30,0x2d,0x50,0x61,0x74,0x63,0x68,
  0x54,0x61,0x62,0x6c,0x65,0x00,0x43,0x6f,0x64,0x65,0x31,0x2d,0x50,0x61,0x74,0x63,
  0x68,0x54,0x61,0x62,0x6c,0x65,0x28,0x43,0x6f,0x64,0x65,0x31,0x45,0x6e,0x64,0x2d,
  0x43,0x6f,0x64,0x65,0x31,0x29,0x00,0x02,0xff,0xff,0x50,0x61,0x74,0x63,0x68,0x31,
  0x2d,0x50,0x61,0x74,0x63,0x68,0x54,0x61,0x62,0x6c,0x65,0x00,0x43,0x6f,0x64,0x65,
  0x32,0x2d,0x50,0x61,0x74,0x63,0x68,0x54,0x61,0x62,0x6c,0x65,0x28,0x43,0x6f,0x64,
  0x65,0x32,0x45,0x6e,0x64,0x2d,0x43,0x6f,0x64,0x65,0x32,0x29,0x00,0x02,0xff,0xff,
  0x50,0x61,0x74,0x63,0x68,0x32,0x2d,0x50,0x61,0x74,0x63,0x68,0x54,0x61,0x62,0x6c,
  0x65,0x00,0x43,0x6f,0x64,0x65,0x33,0x2d,0x50,0x61,0x74,0x63,0x68,0x54,0x61,0x62,
  0x6c,0x65,0x28,0x43,0x6f,0x64,0x65,0x33,0x45,0x6e,0x64,0x2d,0x43,0x6f,0x64,0x65,
  0x33,0x29,0x00,0x02,0xff,0xff,0x50,0x61,0x74,0x63,0x68,0x33,0x2d,0x50,0x61,0x74,
  0x63,0x68,0x54,0x61,0x62,0x6c,0x65,0x00,0x43,0x6f,0x64,0x65,0x34,0x2d,0x50,0x61,
  0x74,0x63,0x68,0x54,0x61,0x62,0x6c,0x65,0x28,0x43,0x6f,0x64,0x65,0x34,0x45,0x6e,
  0x64,0x2d,0x43,0x6f,0x64,0x65,0x34,0x29,0x00,0x02,0xff,0xff,0x50,0x61,0x74,0x63,
  0x68,0x34,0x2d,0x50,0x61,0x74,0x63,0x68,0x54,0x61,0x62,0x6c,0x65,0x00,0x43,0x6f,
  0x64,0x65,0x35,0x2d,0x50,0x61,0x74,0x63,0x68,0x54,0x61,0x62,0x6c,0x65,0x28,0x43,
  0x6f,0x64,0x65,0x35,0x45,0x6e,0x64,0x2d,0x43,0x6f,0x64,0x65,0x35,0x29,0x00,0x02,
  0xff,0xff,0x50,0x61,0x74,0x63,0x68,0x35,0x2d,0x50,0x61,0x74,0x63,0x68,0x54,0x61,
  0x62,0x6c,0x65,0x00,0x43,0x6f,0x64,0x65,0x36,0x2d,0x50,0x61,0x74,0x63,0x68,0x54,
  0x61,0x62,0x6c,0x65,0x28,0x43,0x6f,0x64,0x65,0x36,0x45,0x6e,0x64,0x2d,0x43,0x6f,
  0x64,0x65,0x36,0x29,0x00,0x02,0xff,0xff,0x50,0x61,0x74,0x63,0x68,0x36,0x2d,0x50,
  0x61,0x74,0x63,0x68,0x54,0x61,0x62,0x6c,0x65,0x00,0x00,0x00,
};
#define Tags ((uint32_t*)(_ds + 52))
#define PlayerName ((uint8_t*)(_ds + 268))
#define Creator ((uint8_t*)(_ds + 280))
#define Prefix ((uint8_t*)(_ds + 336))
#define DeliBase ((uint32_t*)(_ds + 342))
#define ModulePtr ((uint32_t*)(_ds + 346))
#define PlayPtr ((uint32_t*)(_ds + 350))
#define AudioPtr ((uint32_t*)(_ds + 354))
#define InitSongPtr ((uint32_t*)(_ds + 358))
#define EndSongPtr ((uint32_t*)(_ds + 362))
#define SampleInfoPtr ((uint32_t*)(_ds + 366))
#define EndSampleInfoPtr ((uint32_t*)(_ds + 370))
#define EagleBase ((uint32_t*)(_ds + 374))
#define Change ((uint16_t*)(_ds + 378))
#define ChangeLen ((uint32_t*)(_ds + 380))
#define SongEndFlag ((uint16_t*)(_ds + 384))
#define RightVolume ((uint16_t*)(_ds + 386))
#define LeftVolume ((uint16_t*)(_ds + 388))
#define Voice1 ((uint16_t*)(_ds + 390))
#define Voice2 ((uint16_t*)(_ds + 392))
#define Voice3 ((uint16_t*)(_ds + 394))
#define Voice4 ((uint16_t*)(_ds + 396))
#define OldVoice1 ((uint16_t*)(_ds + 398))
#define OldVoice2 ((uint16_t*)(_ds + 400))
#define OldVoice3 ((uint16_t*)(_ds + 402))
#define OldVoice4 ((uint16_t*)(_ds + 404))
#define StructAdr ((uint8_t*)(_ds + 406))
#define InfoBuffer ((uint32_t*)(_ds + 408))
#define Channel0 ((uint32_t*)(_ds + 492))
#define Channel1 ((uint32_t*)(_ds + 496))
#define Channel2 ((uint32_t*)(_ds + 500))
#define Channel3 ((uint32_t*)(_ds + 504))
#define StructInt ((uint32_t*)(_ds + 508))
#define IntAddress ((uint32_t*)(_ds + 526))
#define IntName ((uint8_t*)(_ds + 530))
#define PatchTable ((uint16_t*)(_ds + 560))

/* -- External Data Placeholders (INCBIN / external data) ------------- */
/* Host must set these pointers to actual module data before playback. */
static uint8_t* NoChange = NULL;
static uint8_t* SetNew = NULL;
static uint8_t* NoVoice1 = NULL;
static uint8_t* Voice1On = NULL;
static uint8_t* SetIt = NULL;
static uint8_t* NoVoice2 = NULL;
static uint8_t* Voice2On = NULL;
static uint8_t* NoVoice3 = NULL;
static uint8_t* Voice3On = NULL;
static uint8_t* Voice4On = NULL;
static uint8_t* _SetVoice = NULL;
static uint8_t* No_Voice1 = NULL;
static uint8_t* No_Voice2 = NULL;
static uint8_t* No_Voice3 = NULL;
static uint8_t* No_Voice4 = NULL;
static uint8_t* _return = NULL;
static uint8_t* hop = NULL;
static uint8_t* Note = NULL;
static uint8_t* NoRTE = NULL;
static uint8_t* More = NULL;
static uint8_t* NoSR = NULL;
static uint8_t* ClearUPS = NULL;
static uint8_t* NoEnd = NULL;

/* -- Forward Declarations -------------------------------------------- */
static void ChangeVolume(void);
static void ModuleChange(void);
static void ClearAudioVector(void);
static void SongEnd(void);
static void SetAll(void);
static void SetVol(void);
static void SetPer(void);
void Interrupt(void);
static void SubSongRange(void);
static void Code0(void);
static void SetVolume(void);
static void SetVoices(void);
static void StructInit(void);
static void SampleInit(void);
static void Check1(void);
static void fail(void);
static void GetInfos(void);
static void SetAudioVector(void);
void InitPlayer(void);
static void InitFail(void);
static void EndPlayer(void);
void EndSound(void);
static void Code1(void);
static void Code2(void);
static void Code3(void);
static void Code4(void);
static void Code5(void);
static void Code6(void);
static void Check3(void);
void InitSound(void);
static void SetBalance(void);


/* ====================================================================
 * Code Section -- Transpiled Functions
 * ==================================================================== */
/* ***************************************************** */
/* ***     Core Design replayer for EaglePlayer,    **** */
/* ***         all adaptions by Wanted Team	  **** */
/* ***     DeliTracker 2.32 compatible version	  **** */
/* ***************************************************** */

static void _anon0(void) {
  /* UNIMPLEMENTED: INCDIR */  /* INCDIR	dh2:include/ */
}


/* -- SECTION Player ------------------------------------------ */

static void _anon1(void) {
  /* UNIMPLEMENTED: PLAYERHEADER */  /* PLAYERHEADER	Tags */
}

/* ************************************************************************** */
/* *************************** EP_ModuleChange ****************************** */
/* ************************************************************************** */

/* --- ModuleChange --- */
static void ModuleChange(void) {
  {  /* MOVE.W	Change(PC),D0 */
      uint16_t _mv = (uint16_t)(READ16((uintptr_t)Change));
      W(d0) = (uint16_t)_mv;
      flag_z = ((int16_t)(_mv) == 0);
      flag_n = ((int16_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  if (!flag_z) goto NoChange;  /* not equal / nonzero */  /* BNE.S	NoChange */
  {  /* MOVE.L	EndSongPtr(PC),EPG_ARG1(A5) */
      uint32_t _mv = (uint32_t)(READ32((uintptr_t)EndSongPtr));
      hw_write32(a5 + (intptr_t)EPG_ARG1, _mv);
      flag_z = ((int32_t)(_mv) == 0);
      flag_n = ((int32_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  a1 = (uint32_t)(uintptr_t)PatchTable;  /* LEA	PatchTable(PC),A1 */
  {  /* MOVE.L	A1,EPG_ARG3(A5) */
      uint32_t _mv = (uint32_t)(a1);
      hw_write32(a5 + (intptr_t)EPG_ARG3, _mv);
      flag_z = ((int32_t)(_mv) == 0);
      flag_n = ((int32_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  {  /* MOVE.L	ChangeLen(PC),D1 */
      uint32_t _mv = (uint32_t)(READ32((uintptr_t)ChangeLen));
      d1 = _mv;
      flag_z = ((int32_t)(_mv) == 0);
      flag_n = ((int32_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  {  /* MOVE.L	D1,EPG_ARG2(A5) */
      uint32_t _mv = (uint32_t)(d1);
      hw_write32(a5 + (intptr_t)EPG_ARG2, _mv);
      flag_z = ((int32_t)(_mv) == 0);
      flag_n = ((int32_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  d0 = (uint32_t)(int32_t)(int8_t)(-2);  /* MOVEQ	#-2,D0 */
  {  /* MOVE.L	D0,EPG_ARG5(A5) */
      uint32_t _mv = (uint32_t)(d0);
      hw_write32(a5 + (intptr_t)EPG_ARG5, _mv);
      flag_z = ((int32_t)(_mv) == 0);
      flag_n = ((int32_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  d0 = (uint32_t)(int32_t)(int8_t)(1);  /* MOVEQ	#1,D0 */
  {  /* MOVE.L	D0,EPG_ARG4(A5) */
      uint32_t _mv = (uint32_t)(d0);
      hw_write32(a5 + (intptr_t)EPG_ARG4, _mv);
      flag_z = ((int32_t)(_mv) == 0);
      flag_n = ((int32_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  d0 = (uint32_t)(int32_t)(int8_t)(5);  /* MOVEQ	#5,D0 */
  {  /* MOVE.L	D0,EPG_ARGN(A5) */
      uint32_t _mv = (uint32_t)(d0);
      hw_write32(a5 + (intptr_t)EPG_ARGN, _mv);
      flag_z = ((int32_t)(_mv) == 0);
      flag_n = ((int32_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  {  /* MOVE.L	EPG_ModuleChange(A5),A0 */
      uint32_t _mv = (uint32_t)(READ32(a5 + (intptr_t)EPG_ModuleChange));
      a0 = _mv;
      flag_z = ((int32_t)(_mv) == 0);
      flag_n = ((int32_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  { uintptr_t _jt=(uintptr_t)(a0); if(_jt) ((void(*)(void))_jt)(); }  /* JSR	(A0) */
NoChange:
  {  /* MOVE.W	#1,Change */
      uint16_t _mv = (uint16_t)(1);
      WRITE16((uintptr_t)Change, _mv);
      flag_z = ((int16_t)(_mv) == 0);
      flag_n = ((int16_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  d0 = (uint32_t)(int32_t)(int8_t)(0);  /* MOVEQ	#0,D0 */
  return;  /* RTS */
}

/* ************************************************************************** */
/* ************************ DTP_Volume, DTP_Balance ************************* */
/* ************************************************************************** */
/* Copy Volume and Balance Data to internal buffer */

/* --- SetVolume --- */
static void SetVolume(void) {
SetBalance:
  {  /* MOVE.W	dtg_SndLBal(A5),D0 */
      uint16_t _mv = (uint16_t)(READ16(a5 + (intptr_t)dtg_SndLBal));
      W(d0) = (uint16_t)_mv;
      flag_z = ((int16_t)(_mv) == 0);
      flag_n = ((int16_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  d0 = (uint32_t)((uint16_t)(READ16(a5 + (intptr_t)dtg_SndVol)) * (uint16_t)W(d0));  /* MULU.W	dtg_SndVol(A5),D0 */
  W(d0) = (uint16_t)((uint32_t)(W(d0)) >> 6);  /* LSR.W	#6,D0 */
  {  /* MOVE.W	D0,LeftVolume */
      uint16_t _mv = (uint16_t)(W(d0));
      WRITE16((uintptr_t)LeftVolume, _mv);
      flag_z = ((int16_t)(_mv) == 0);
      flag_n = ((int16_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  {  /* MOVE.W	dtg_SndRBal(A5),D0 */
      uint16_t _mv = (uint16_t)(READ16(a5 + (intptr_t)dtg_SndRBal));
      W(d0) = (uint16_t)_mv;
      flag_z = ((int16_t)(_mv) == 0);
      flag_n = ((int16_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  d0 = (uint32_t)((uint16_t)(READ16(a5 + (intptr_t)dtg_SndVol)) * (uint16_t)W(d0));  /* MULU.W	dtg_SndVol(A5),D0 */
  W(d0) = (uint16_t)((uint32_t)(W(d0)) >> 6);  /* LSR.W	#6,D0 */
  {  /* MOVE.W	D0,RightVolume */
      uint16_t _mv = (uint16_t)(W(d0));
      WRITE16((uintptr_t)RightVolume, _mv);
      flag_z = ((int16_t)(_mv) == 0);
      flag_n = ((int16_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  a1 = (uint32_t)(uintptr_t)OldVoice1;  /* LEA	OldVoice1(PC),A1 */
  d0 = (uint32_t)(int32_t)(int8_t)(3);  /* MOVEQ	#3,D0 */
  a4 = (uint32_t)0xDFF000;  /* LEA	$DFF000,A4 */
SetNew:
  {  /* MOVE.W	(A1)+,D0 */
      uint16_t _mv = (uint16_t)(READ16_POST(a1));
      W(d0) = (uint16_t)_mv;
      flag_z = ((int16_t)(_mv) == 0);
      flag_n = ((int16_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  ChangeVolume();  /* BSR.B	ChangeVolume */
  a4 = (uint32_t)(a4 + 16);  /* LEA	16(A4),A4 */
  if ((int16_t)(--d0) >= 0) goto SetNew;  /* DBF	D0,SetNew */
  return;  /* RTS */
}


/* --- ChangeVolume --- */
static void ChangeVolume(void) {
  {  /* CMPA.L	#$DFF000,A4 */
      int32_t _lhs = (int32_t)(a4);
      int32_t _rhs = (int32_t)(0xDFF000);
      int32_t _cmp = _lhs - _rhs;
      flag_z = (_cmp == 0);
      flag_n = (_cmp < 0);
      flag_c = ((uint32_t)_lhs < (uint32_t)_rhs);
    }
  if (!flag_z) goto NoVoice1;  /* not equal / nonzero */  /* BNE.B	NoVoice1 */
  {  /* MOVE.W	D0,OldVoice1 */
      uint16_t _mv = (uint16_t)(W(d0));
      WRITE16((uintptr_t)OldVoice1, _mv);
      flag_z = ((int16_t)(_mv) == 0);
      flag_n = ((int16_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  {  /* TST.W	Voice1 */
      uint16_t _tst = (uint16_t)(READ16((uintptr_t)Voice1));
      flag_z = (_tst == 0);
      flag_n = ((int16_t)(_tst) < 0);
      flag_c = 0; flag_v = 0;
    }
  if (!flag_z) goto Voice1On;  /* not equal / nonzero */  /* BNE.B	Voice1On */
  d0 = (uint32_t)(int32_t)(int8_t)(0);  /* MOVEQ	#0,D0 */
Voice1On:
  d0 = (uint32_t)((uint16_t)(READ16((uintptr_t)LeftVolume)) * (uint16_t)W(d0));  /* MULU.W	LeftVolume(PC),D0 */
  goto SetIt;  /* BRA.B	SetIt */
NoVoice1:
  {  /* CMPA.L	#$DFF010,A4 */
      int32_t _lhs = (int32_t)(a4);
      int32_t _rhs = (int32_t)(0xDFF010);
      int32_t _cmp = _lhs - _rhs;
      flag_z = (_cmp == 0);
      flag_n = (_cmp < 0);
      flag_c = ((uint32_t)_lhs < (uint32_t)_rhs);
    }
  if (!flag_z) goto NoVoice2;  /* not equal / nonzero */  /* BNE.B	NoVoice2 */
  {  /* MOVE.W	D0,OldVoice2 */
      uint16_t _mv = (uint16_t)(W(d0));
      WRITE16((uintptr_t)OldVoice2, _mv);
      flag_z = ((int16_t)(_mv) == 0);
      flag_n = ((int16_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  {  /* TST.W	Voice2 */
      uint16_t _tst = (uint16_t)(READ16((uintptr_t)Voice2));
      flag_z = (_tst == 0);
      flag_n = ((int16_t)(_tst) < 0);
      flag_c = 0; flag_v = 0;
    }
  if (!flag_z) goto Voice2On;  /* not equal / nonzero */  /* BNE.B	Voice2On */
  d0 = (uint32_t)(int32_t)(int8_t)(0);  /* MOVEQ	#0,D0 */
Voice2On:
  d0 = (uint32_t)((uint16_t)(READ16((uintptr_t)RightVolume)) * (uint16_t)W(d0));  /* MULU.W	RightVolume(PC),D0 */
  goto SetIt;  /* BRA.B	SetIt */
NoVoice2:
  {  /* CMPA.L	#$DFF020,A4 */
      int32_t _lhs = (int32_t)(a4);
      int32_t _rhs = (int32_t)(0xDFF020);
      int32_t _cmp = _lhs - _rhs;
      flag_z = (_cmp == 0);
      flag_n = (_cmp < 0);
      flag_c = ((uint32_t)_lhs < (uint32_t)_rhs);
    }
  if (!flag_z) goto NoVoice3;  /* not equal / nonzero */  /* BNE.B	NoVoice3 */
  {  /* MOVE.W	D0,OldVoice3 */
      uint16_t _mv = (uint16_t)(W(d0));
      WRITE16((uintptr_t)OldVoice3, _mv);
      flag_z = ((int16_t)(_mv) == 0);
      flag_n = ((int16_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  {  /* TST.W	Voice3 */
      uint16_t _tst = (uint16_t)(READ16((uintptr_t)Voice3));
      flag_z = (_tst == 0);
      flag_n = ((int16_t)(_tst) < 0);
      flag_c = 0; flag_v = 0;
    }
  if (!flag_z) goto Voice3On;  /* not equal / nonzero */  /* BNE.B	Voice3On */
  d0 = (uint32_t)(int32_t)(int8_t)(0);  /* MOVEQ	#0,D0 */
Voice3On:
  d0 = (uint32_t)((uint16_t)(READ16((uintptr_t)RightVolume)) * (uint16_t)W(d0));  /* MULU.W	RightVolume(PC),D0 */
  goto SetIt;  /* BRA.B	SetIt */
NoVoice3:
  {  /* MOVE.W	D0,OldVoice4 */
      uint16_t _mv = (uint16_t)(W(d0));
      WRITE16((uintptr_t)OldVoice4, _mv);
      flag_z = ((int16_t)(_mv) == 0);
      flag_n = ((int16_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  {  /* TST.W	Voice4 */
      uint16_t _tst = (uint16_t)(READ16((uintptr_t)Voice4));
      flag_z = (_tst == 0);
      flag_n = ((int16_t)(_tst) < 0);
      flag_c = 0; flag_v = 0;
    }
  if (!flag_z) goto Voice4On;  /* not equal / nonzero */  /* BNE.B	Voice4On */
  d0 = (uint32_t)(int32_t)(int8_t)(0);  /* MOVEQ	#0,D0 */
Voice4On:
  d0 = (uint32_t)((uint16_t)(READ16((uintptr_t)LeftVolume)) * (uint16_t)W(d0));  /* MULU.W	LeftVolume(PC),D0 */
SetIt:
  W(d0) = (uint16_t)((uint32_t)(W(d0)) >> 6);  /* LSR.W	#6,D0 */
  {  /* MOVE.W	D0,168(A4) */
      uint16_t _mv = (uint16_t)(W(d0));
      hw_write16(a4 + 168, _mv);
      flag_z = ((int16_t)(_mv) == 0);
      flag_n = ((int16_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  return;  /* RTS */
}

/* ------------------------------- Set Vol -------------------------------* */

/* --- SetVol --- */
static void SetVol(void) {
  {  /* MOVE.L	A0,-(A7) */
      uint32_t _mv = (uint32_t)(a0);
      WRITE32_PRE(a7, _mv);
      flag_z = ((int32_t)(_mv) == 0);
      flag_n = ((int32_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  a0 = (uint32_t)(uintptr_t)StructAdr+UPS_Voice1Vol;  /* LEA	StructAdr+UPS_Voice1Vol(PC),A0 */
  {  /* CMP.L	#$DFF000,A4 */
      int32_t _lhs = (int32_t)(a4);
      int32_t _rhs = (int32_t)(0xDFF000);
      int32_t _cmp = _lhs - _rhs;
      flag_z = (_cmp == 0);
      flag_n = (_cmp < 0);
      flag_c = ((uint32_t)_lhs < (uint32_t)_rhs);
    }
  if (flag_z) goto _SetVoice;  /* equal / zero */  /* BEQ.S	.SetVoice */
  a0 = (uint32_t)(uintptr_t)StructAdr+UPS_Voice2Vol;  /* LEA	StructAdr+UPS_Voice2Vol(PC),A0 */
  {  /* CMP.L	#$DFF010,A4 */
      int32_t _lhs = (int32_t)(a4);
      int32_t _rhs = (int32_t)(0xDFF010);
      int32_t _cmp = _lhs - _rhs;
      flag_z = (_cmp == 0);
      flag_n = (_cmp < 0);
      flag_c = ((uint32_t)_lhs < (uint32_t)_rhs);
    }
  if (flag_z) goto _SetVoice;  /* equal / zero */  /* BEQ.S	.SetVoice */
  a0 = (uint32_t)(uintptr_t)StructAdr+UPS_Voice3Vol;  /* LEA	StructAdr+UPS_Voice3Vol(PC),A0 */
  {  /* CMP.L	#$DFF020,A4 */
      int32_t _lhs = (int32_t)(a4);
      int32_t _rhs = (int32_t)(0xDFF020);
      int32_t _cmp = _lhs - _rhs;
      flag_z = (_cmp == 0);
      flag_n = (_cmp < 0);
      flag_c = ((uint32_t)_lhs < (uint32_t)_rhs);
    }
  if (flag_z) goto _SetVoice;  /* equal / zero */  /* BEQ.S	.SetVoice */
  a0 = (uint32_t)(uintptr_t)StructAdr+UPS_Voice4Vol;  /* LEA	StructAdr+UPS_Voice4Vol(PC),A0 */
_SetVoice:
  {  /* MOVE.W	D0,(A0) */
      uint16_t _mv = (uint16_t)(W(d0));
      hw_write16(a0, _mv);
      flag_z = ((int16_t)(_mv) == 0);
      flag_n = ((int16_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  {  /* MOVE.L	(A7)+,A0 */
      uint32_t _mv = (uint32_t)(READ32_POST(a7));
      a0 = _mv;
      flag_z = ((int32_t)(_mv) == 0);
      flag_n = ((int32_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  return;  /* RTS */
}

/* ------------------------------- Set All -------------------------------* */

/* --- SetAll --- */
static void SetAll(void) {
  {  /* MOVE.L	A0,-(A7) */
      uint32_t _mv = (uint32_t)(a0);
      WRITE32_PRE(a7, _mv);
      flag_z = ((int32_t)(_mv) == 0);
      flag_n = ((int32_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  a0 = (uint32_t)(uintptr_t)StructAdr+UPS_Voice1Adr;  /* LEA	StructAdr+UPS_Voice1Adr(PC),A0 */
  {  /* CMP.L	#$DFF000,A4 */
      int32_t _lhs = (int32_t)(a4);
      int32_t _rhs = (int32_t)(0xDFF000);
      int32_t _cmp = _lhs - _rhs;
      flag_z = (_cmp == 0);
      flag_n = (_cmp < 0);
      flag_c = ((uint32_t)_lhs < (uint32_t)_rhs);
    }
  if (flag_z) goto _SetVoice;  /* equal / zero */  /* BEQ.S	.SetVoice */
  a0 = (uint32_t)(uintptr_t)StructAdr+UPS_Voice2Adr;  /* LEA	StructAdr+UPS_Voice2Adr(PC),A0 */
  {  /* CMP.L	#$DFF010,A4 */
      int32_t _lhs = (int32_t)(a4);
      int32_t _rhs = (int32_t)(0xDFF010);
      int32_t _cmp = _lhs - _rhs;
      flag_z = (_cmp == 0);
      flag_n = (_cmp < 0);
      flag_c = ((uint32_t)_lhs < (uint32_t)_rhs);
    }
  if (flag_z) goto _SetVoice;  /* equal / zero */  /* BEQ.S	.SetVoice */
  a0 = (uint32_t)(uintptr_t)StructAdr+UPS_Voice3Adr;  /* LEA	StructAdr+UPS_Voice3Adr(PC),A0 */
  {  /* CMP.L	#$DFF020,A4 */
      int32_t _lhs = (int32_t)(a4);
      int32_t _rhs = (int32_t)(0xDFF020);
      int32_t _cmp = _lhs - _rhs;
      flag_z = (_cmp == 0);
      flag_n = (_cmp < 0);
      flag_c = ((uint32_t)_lhs < (uint32_t)_rhs);
    }
  if (flag_z) goto _SetVoice;  /* equal / zero */  /* BEQ.S	.SetVoice */
  a0 = (uint32_t)(uintptr_t)StructAdr+UPS_Voice4Adr;  /* LEA	StructAdr+UPS_Voice4Adr(PC),A0 */
_SetVoice:
  {  /* MOVE.L	14(A6),(A0) */
      uint32_t _mv = (uint32_t)(READ32(a6 + 14));
      hw_write32(a0, _mv);
      flag_z = ((int32_t)(_mv) == 0);
      flag_n = ((int32_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  {  /* MOVE.W	18(A6),UPS_Voice1Len(A0) */
      uint16_t _mv = (uint16_t)(READ16(a6 + 18));
      hw_write16(a0 + (intptr_t)UPS_Voice1Len, _mv);
      flag_z = ((int16_t)(_mv) == 0);
      flag_n = ((int16_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  {  /* MOVE.W	8(A6),UPS_Voice1Per(A0) */
      uint16_t _mv = (uint16_t)(READ16(a6 + 8));
      hw_write16(a0 + (intptr_t)UPS_Voice1Per, _mv);
      flag_z = ((int16_t)(_mv) == 0);
      flag_n = ((int16_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  {  /* MOVE.L	(A7)+,A0 */
      uint32_t _mv = (uint32_t)(READ32_POST(a7));
      a0 = _mv;
      flag_z = ((int32_t)(_mv) == 0);
      flag_n = ((int32_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  return;  /* RTS */
}

/* ------------------------------- Set Per -------------------------------* */

/* --- SetPer --- */
static void SetPer(void) {
  {  /* MOVE.L	A0,-(A7) */
      uint32_t _mv = (uint32_t)(a0);
      WRITE32_PRE(a7, _mv);
      flag_z = ((int32_t)(_mv) == 0);
      flag_n = ((int32_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  a0 = (uint32_t)(uintptr_t)StructAdr+UPS_Voice1Per;  /* LEA	StructAdr+UPS_Voice1Per(PC),A0 */
  {  /* CMP.L	#$DFF000,A4 */
      int32_t _lhs = (int32_t)(a4);
      int32_t _rhs = (int32_t)(0xDFF000);
      int32_t _cmp = _lhs - _rhs;
      flag_z = (_cmp == 0);
      flag_n = (_cmp < 0);
      flag_c = ((uint32_t)_lhs < (uint32_t)_rhs);
    }
  if (flag_z) goto _SetVoice;  /* equal / zero */  /* BEQ.S	.SetVoice */
  a0 = (uint32_t)(uintptr_t)StructAdr+UPS_Voice2Per;  /* LEA	StructAdr+UPS_Voice2Per(PC),A0 */
  {  /* CMP.L	#$DFF010,A4 */
      int32_t _lhs = (int32_t)(a4);
      int32_t _rhs = (int32_t)(0xDFF010);
      int32_t _cmp = _lhs - _rhs;
      flag_z = (_cmp == 0);
      flag_n = (_cmp < 0);
      flag_c = ((uint32_t)_lhs < (uint32_t)_rhs);
    }
  if (flag_z) goto _SetVoice;  /* equal / zero */  /* BEQ.S	.SetVoice */
  a0 = (uint32_t)(uintptr_t)StructAdr+UPS_Voice3Per;  /* LEA	StructAdr+UPS_Voice3Per(PC),A0 */
  {  /* CMP.L	#$DFF020,A4 */
      int32_t _lhs = (int32_t)(a4);
      int32_t _rhs = (int32_t)(0xDFF020);
      int32_t _cmp = _lhs - _rhs;
      flag_z = (_cmp == 0);
      flag_n = (_cmp < 0);
      flag_c = ((uint32_t)_lhs < (uint32_t)_rhs);
    }
  if (flag_z) goto _SetVoice;  /* equal / zero */  /* BEQ.S	.SetVoice */
  a0 = (uint32_t)(uintptr_t)StructAdr+UPS_Voice4Per;  /* LEA	StructAdr+UPS_Voice4Per(PC),A0 */
_SetVoice:
  {  /* MOVE.W	8(A6),(A0) */
      uint16_t _mv = (uint16_t)(READ16(a6 + 8));
      hw_write16(a0, _mv);
      flag_z = ((int16_t)(_mv) == 0);
      flag_n = ((int16_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  {  /* MOVE.L	(A7)+,A0 */
      uint32_t _mv = (uint32_t)(READ32_POST(a7));
      a0 = _mv;
      flag_z = ((int32_t)(_mv) == 0);
      flag_n = ((int32_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  return;  /* RTS */
}

/* ************************************************************************** */
/* ***************************** EP_Voices ********************************** */
/* ************************************************************************** */
/* d0 Bit 0-3 = Set Voices Bit=1 Voice on */

/* --- SetVoices --- */
static void SetVoices(void) {
  a0 = (uint32_t)(uintptr_t)Voice1;  /* LEA	Voice1(PC),A0 */
  a1 = (uint32_t)(uintptr_t)StructAdr;  /* LEA	StructAdr(PC),A1 */
  d1 = (uint32_t)(int32_t)(int8_t)(1);  /* MOVEQ	#1,D1 */
  {  /* MOVE.W	D1,(A0)+,Voice1,EQU,#0,setzen */
      uint16_t _mv = (uint16_t)(W(d1));
      WRITE16_POST(a0, _mv);
      flag_z = ((int16_t)(_mv) == 0);
      flag_n = ((int16_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  flag_z = ((d0 & (1u << (0 & 31))) == 0);  /* BTST	#0,D0 */
  if (!flag_z) goto No_Voice1;  /* not equal / nonzero */  /* BNE.B	No_Voice1 */
  hw_write16(a0 + -2, 0);  /* CLR.W	-2(A0) */
  paula_set_volume(0, (uint8_t)(0));  /* CLR.W	$DFF0A8 */
  hw_write16(a1 + (intptr_t)UPS_Voice1Vol, 0);  /* CLR.W	UPS_Voice1Vol(A1) */
No_Voice1:
  {  /* MOVE.W	D1,(A0)+,Voice2,EQU,#0,setzen */
      uint16_t _mv = (uint16_t)(W(d1));
      WRITE16_POST(a0, _mv);
      flag_z = ((int16_t)(_mv) == 0);
      flag_n = ((int16_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  flag_z = ((d0 & (1u << (1 & 31))) == 0);  /* BTST	#1,D0 */
  if (!flag_z) goto No_Voice2;  /* not equal / nonzero */  /* BNE.B	No_Voice2 */
  hw_write16(a0 + -2, 0);  /* CLR.W	-2(A0) */
  paula_set_volume(1, (uint8_t)(0));  /* CLR.W	$DFF0B8 */
  hw_write16(a1 + (intptr_t)UPS_Voice2Vol, 0);  /* CLR.W	UPS_Voice2Vol(A1) */
No_Voice2:
  {  /* MOVE.W	D1,(A0)+,Voice3,EQU,#0,setzen */
      uint16_t _mv = (uint16_t)(W(d1));
      WRITE16_POST(a0, _mv);
      flag_z = ((int16_t)(_mv) == 0);
      flag_n = ((int16_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  flag_z = ((d0 & (1u << (2 & 31))) == 0);  /* BTST	#2,D0 */
  if (!flag_z) goto No_Voice3;  /* not equal / nonzero */  /* BNE.B	No_Voice3 */
  hw_write16(a0 + -2, 0);  /* CLR.W	-2(A0) */
  paula_set_volume(2, (uint8_t)(0));  /* CLR.W	$DFF0C8 */
  hw_write16(a1 + (intptr_t)UPS_Voice3Vol, 0);  /* CLR.W	UPS_Voice3Vol(A1) */
No_Voice3:
  {  /* MOVE.W	D1,(A0)+,Voice4,EQU,#0,setzen */
      uint16_t _mv = (uint16_t)(W(d1));
      WRITE16_POST(a0, _mv);
      flag_z = ((int16_t)(_mv) == 0);
      flag_n = ((int16_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  flag_z = ((d0 & (1u << (3 & 31))) == 0);  /* BTST	#3,D0 */
  if (!flag_z) goto No_Voice4;  /* not equal / nonzero */  /* BNE.B	No_Voice4 */
  hw_write16(a0 + -2, 0);  /* CLR.W	-2(A0) */
  paula_set_volume(3, (uint8_t)(0));  /* CLR.W	$DFF0D8 */
  hw_write16(a1 + (intptr_t)UPS_Voice4Vol, 0);  /* CLR.W	UPS_Voice4Vol(A1) */
No_Voice4:
  {  /* MOVE.W	D0,UPS_DMACon(A1) */
      uint16_t _mv = (uint16_t)(W(d0));
      hw_write16(a1 + (intptr_t)UPS_DMACon, _mv);
      flag_z = ((int16_t)(_mv) == 0);
      flag_n = ((int16_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  /* Bit 0 = Kanal 1 usw. */
  d0 = (uint32_t)(int32_t)(int8_t)(0);  /* MOVEQ	#0,D0 */
  return;  /* RTS */
}

/* ************************************************************************** */
/* ****************************** EP_StructInit ***************************** */
/* ************************************************************************** */

/* --- StructInit --- */
static void StructInit(void) {
  a0 = (uint32_t)(uintptr_t)StructAdr;  /* LEA	StructAdr(PC),A0 */
  return;  /* RTS */
}

/* ************************************************************************** */
/* ****************************** EP_SampleInit ***************************** */
/* ************************************************************************** */

/* --- SampleInit --- */
static void SampleInit(void) {
  d7 = (uint32_t)(int32_t)(int8_t)(EPR_NotEnoughMem);  /* MOVEQ	#EPR_NotEnoughMem,D7 */
  a3 = (uint32_t)(a5 + (intptr_t)EPG_SampleInfoStructure);  /* LEA	EPG_SampleInfoStructure(A5),A3 */
  {  /* MOVE.L	SampleInfoPtr(PC),D0 */
      uint32_t _mv = (uint32_t)(READ32((uintptr_t)SampleInfoPtr));
      d0 = _mv;
      flag_z = ((int32_t)(_mv) == 0);
      flag_n = ((int32_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  if (flag_z) goto _return;  /* equal / zero */  /* BEQ.B	return */
  {  /* MOVE.L	D0,A0 */
      uint32_t _mv = (uint32_t)(d0);
      a0 = _mv;
      flag_z = ((int32_t)(_mv) == 0);
      flag_n = ((int32_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  {  /* MOVE.L	InfoBuffer+Samples(PC),D5 */
      uint32_t _mv = (uint32_t)(READ32((uintptr_t)InfoBuffer+Samples));
      d5 = _mv;
      flag_z = ((int32_t)(_mv) == 0);
      flag_n = ((int32_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  if (flag_z) goto _return;  /* equal / zero */  /* BEQ.B	return */
  {  /* SUBQ.L	#1,D5 */
      uint32_t _sr = (uint32_t)(d5 - 1);
      d5 = (uint32_t)_sr;
      flag_z = ((int32_t)(_sr) == 0);
      flag_n = ((int32_t)(_sr) < 0);
    }
hop:
  { uintptr_t _jt=(uintptr_t)(READ32(a5 + (intptr_t)ENPP_AllocSampleStruct)); if(_jt) ((void(*)(void))_jt)(); }  /* JSR	ENPP_AllocSampleStruct(A5) */
  {  /* MOVE.L	D0,(A3) */
      uint32_t _mv = (uint32_t)(d0);
      hw_write32(a3, _mv);
      flag_z = ((int32_t)(_mv) == 0);
      flag_n = ((int32_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  if (flag_z) goto _return;  /* equal / zero */  /* BEQ.B	return */
  {  /* MOVE.L	D0,A3 */
      uint32_t _mv = (uint32_t)(d0);
      a3 = _mv;
      flag_z = ((int32_t)(_mv) == 0);
      flag_n = ((int32_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  {  /* MOVE.L	6(A0),A1 */
      uint32_t _mv = (uint32_t)(READ32(a0 + 6));
      a1 = _mv;
      flag_z = ((int32_t)(_mv) == 0);
      flag_n = ((int32_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  d0 = (uint32_t)(int32_t)(int8_t)(0);  /* MOVEQ	#0,D0 */
  {  /* MOVE.W	(A1)+,D0 */
      uint16_t _mv = (uint16_t)(READ16_POST(a1));
      W(d0) = (uint16_t)_mv;
      flag_z = ((int16_t)(_mv) == 0);
      flag_n = ((int16_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  d0 = d0 << 1;  /* LSL.L	#1,D0 */
  {  /* MOVE.L	A1,EPS_Adr(A3) */
      uint32_t _mv = (uint32_t)(a1);
      hw_write32(a3 + (intptr_t)EPS_Adr, _mv);
      flag_z = ((int32_t)(_mv) == 0);
      flag_n = ((int32_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  {  /* MOVE.L	D0,EPS_Length(A3) */
      uint32_t _mv = (uint32_t)(d0);
      hw_write32(a3 + (intptr_t)EPS_Length, _mv);
      flag_z = ((int32_t)(_mv) == 0);
      flag_n = ((int32_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  {  /* MOVE.L	#64,EPS_Volume(A3) */
      uint32_t _mv = (uint32_t)(64);
      hw_write32(a3 + (intptr_t)EPS_Volume, _mv);
      flag_z = ((int32_t)(_mv) == 0);
      flag_n = ((int32_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  {  /* MOVE.W	#USITY_RAW,EPS_Type(A3) */
      uint16_t _mv = (uint16_t)(USITY_RAW);
      hw_write16(a3 + (intptr_t)EPS_Type, _mv);
      flag_z = ((int16_t)(_mv) == 0);
      flag_n = ((int16_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  {  /* MOVE.W	#USIB_Playable,USIB_Saveable,USIB_8BIT,EPS_Flags(A3) */
      uint16_t _mv = (uint16_t)(USIB_Playable);
      WRITE16((uintptr_t)USIB_Saveable, _mv);
      flag_z = ((int16_t)(_mv) == 0);
      flag_n = ((int16_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
SkipInfo:
  a0 = (uint32_t)(a0 + 14);  /* LEA	14(A0),A0 */
  if ((int16_t)(--d5) >= 0) goto hop;  /* DBF	D5,hop */
  d7 = (uint32_t)(int32_t)(int8_t)(0);  /* MOVEQ	#0,D7 */
_return:
  {  /* MOVE.L	D7,D0 */
      uint32_t _mv = (uint32_t)(d7);
      d0 = _mv;
      flag_z = ((int32_t)(_mv) == 0);
      flag_n = ((int32_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  return;  /* RTS */
}

/* ************************************************************************** */
/* ******************************* DTP_Check1 ******************************* */
/* ************************************************************************** */

/* --- Check1 --- */
static void Check1(void) {
  {  /* MOVE.L	DeliBase(PC),D0 */
      uint32_t _mv = (uint32_t)(READ32((uintptr_t)DeliBase));
      d0 = _mv;
      flag_z = ((int32_t)(_mv) == 0);
      flag_n = ((int32_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  if (flag_z) { fail(); return; }  /* equal / zero */  /* BEQ.B	fail */
}

/* ************************************************************************** */
/* ****************************** EP_Check3 ********************************* */
/* ************************************************************************** */

/* --- Check3 --- */
static void Check3(void) {
  a0 = READ32(a5 + (intptr_t)dtg_ChkData);  /* MOVEA.L	dtg_ChkData(A5),A0 */
  {  /* CMP.L	#$000003F3,(A0) */
      int32_t _lhs = (int32_t)(READ32(a0));
      int32_t _rhs = (int32_t)(0x000003F3);
      int32_t _cmp = _lhs - _rhs;
      flag_z = (_cmp == 0);
      flag_n = (_cmp < 0);
      flag_c = ((uint32_t)_lhs < (uint32_t)_rhs);
    }
  if (!flag_z) { fail(); return; }  /* not equal / nonzero */  /* BNE.B	fail */
  {  /* TST.B	20(A0) */
      uint8_t _tst = (uint8_t)(READ8(a0 + 20));
      flag_z = (_tst == 0);
      flag_n = ((int8_t)(_tst) < 0);
      flag_c = 0; flag_v = 0;
    }
  if (flag_z) { fail(); return; }  /* equal / zero */  /* BEQ.B	fail */
  a0 = (uint32_t)(a0 + 32);  /* LEA	32(A0),A0 */
  {  /* CMP.L	#$70FF4E75,(A0)+ */
      int32_t _lhs = (int32_t)(READ32_POST(a0));
      int32_t _rhs = (int32_t)(0x70FF4E75);
      int32_t _cmp = _lhs - _rhs;
      flag_z = (_cmp == 0);
      flag_n = (_cmp < 0);
      flag_c = ((uint32_t)_lhs < (uint32_t)_rhs);
    }
  if (!flag_z) { fail(); return; }  /* not equal / nonzero */  /* BNE.B	fail */
  {  /* CMP.L	#$532e5048,(A0)+ */
      int32_t _lhs = (int32_t)(READ32_POST(a0));
      int32_t _rhs = (int32_t)(0x532e5048);
      int32_t _cmp = _lhs - _rhs;
      flag_z = (_cmp == 0);
      flag_n = (_cmp < 0);
      flag_c = ((uint32_t)_lhs < (uint32_t)_rhs);
    }
  if (!flag_z) { fail(); return; }  /* not equal / nonzero */  /* BNE.B	fail */
  {  /* CMP.L	#$49505053,(A0)+ */
      int32_t _lhs = (int32_t)(READ32_POST(a0));
      int32_t _rhs = (int32_t)(0x49505053);
      int32_t _cmp = _lhs - _rhs;
      flag_z = (_cmp == 0);
      flag_n = (_cmp < 0);
      flag_c = ((uint32_t)_lhs < (uint32_t)_rhs);
    }
  if (!flag_z) { fail(); return; }  /* not equal / nonzero */  /* BNE.B	fail */
  {  /* TST.L	(A0)+ */
      uint32_t _tst = (uint32_t)(READ32_POST(a0));
      flag_z = (_tst == 0);
      flag_n = ((int32_t)(_tst) < 0);
      flag_c = 0; flag_v = 0;
    }
  if (flag_z) { fail(); return; }  /* equal / zero */  /* BEQ.B	fail */
  {  /* TST.L	(A0)+ */
      uint32_t _tst = (uint32_t)(READ32_POST(a0));
      flag_z = (_tst == 0);
      flag_n = ((int32_t)(_tst) < 0);
      flag_c = 0; flag_v = 0;
    }
  if (flag_z) { fail(); return; }  /* equal / zero */  /* BEQ.B	fail */
  {  /* TST.L	(A0)+ */
      uint32_t _tst = (uint32_t)(READ32_POST(a0));
      flag_z = (_tst == 0);
      flag_n = ((int32_t)(_tst) < 0);
      flag_c = 0; flag_v = 0;
    }
  if (flag_z) { fail(); return; }  /* equal / zero */  /* BEQ.B	fail */
  {  /* TST.L	(A0)+ */
      uint32_t _tst = (uint32_t)(READ32_POST(a0));
      flag_z = (_tst == 0);
      flag_n = ((int32_t)(_tst) < 0);
      flag_c = 0; flag_v = 0;
    }
  if (flag_z) { fail(); return; }  /* equal / zero */  /* BEQ.B	fail */
  {  /* TST.L	(A0) */
      uint32_t _tst = (uint32_t)(READ32(a0));
      flag_z = (_tst == 0);
      flag_n = ((int32_t)(_tst) < 0);
      flag_c = 0; flag_v = 0;
    }
  if (flag_z) { fail(); return; }  /* equal / zero */  /* BEQ.B	fail */
  d0 = (uint32_t)(int32_t)(int8_t)(0);  /* MOVEQ	#0,D0 */
  return;  /* RTS */
}


/* --- fail ---  (cross-function goto target) */
static void fail(void) {
  d0 = (uint32_t)(int32_t)(int8_t)(-1);  /* MOVEQ	#-1,D0 */
  return;  /* RTS */
}

/* ************************************************************************** */
/* **************************** EP_Get_ModuleInfo *************************** */
/* ************************************************************************** */

/* --- GetInfos --- */
static void GetInfos(void) {
  a0 = (uint32_t)(uintptr_t)InfoBuffer;  /* LEA	InfoBuffer(PC),A0 */
  return;  /* RTS */
}

/* ************************************************************************** */
/* **************************** DTP_Intterrupt ****************************** */
/* ************************************************************************** */

/* --- Interrupt --- */
void Interrupt(void) {
  WRITE32_PRE(sp, a6);  /* MOVEM.L	D1,D2,D3,D4,D5,D6,D7,A0,A1,A2,A3,A4,A5,A6,-(SP) */
    WRITE32_PRE(sp, a5);
    WRITE32_PRE(sp, a4);
    WRITE32_PRE(sp, a3);
    WRITE32_PRE(sp, a2);
    WRITE32_PRE(sp, a1);
    WRITE32_PRE(sp, a0);
    WRITE32_PRE(sp, d7);
    WRITE32_PRE(sp, d6);
    WRITE32_PRE(sp, d5);
    WRITE32_PRE(sp, d4);
    WRITE32_PRE(sp, d3);
    WRITE32_PRE(sp, d2);
    WRITE32_PRE(sp, d1);
  a0 = (uint32_t)(uintptr_t)StructAdr;  /* LEA	StructAdr(PC),A0 */
  hw_write8(a0 + (intptr_t)UPS_Enabled, 0xFF);  /* ST	UPS_Enabled(A0) */
  hw_write16(a0 + (intptr_t)UPS_Voice1Per, 0);  /* CLR.W	UPS_Voice1Per(A0) */
  hw_write16(a0 + (intptr_t)UPS_Voice2Per, 0);  /* CLR.W	UPS_Voice2Per(A0) */
  hw_write16(a0 + (intptr_t)UPS_Voice3Per, 0);  /* CLR.W	UPS_Voice3Per(A0) */
  hw_write16(a0 + (intptr_t)UPS_Voice4Per, 0);  /* CLR.W	UPS_Voice4Per(A0) */
  {  /* MOVE.W	#UPSB_Adr,UPSB_Len,UPSB_Per,UPSB_Vol,UPS_Flags(A0) */
      uint16_t _mv = (uint16_t)(UPSB_Adr);
      WRITE16((uintptr_t)UPSB_Len, _mv);
      flag_z = ((int16_t)(_mv) == 0);
      flag_n = ((int16_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  {  /* MOVE.L	PlayPtr(PC),A0 */
      uint32_t _mv = (uint32_t)(READ32((uintptr_t)PlayPtr));
      a0 = _mv;
      flag_z = ((int32_t)(_mv) == 0);
      flag_n = ((int32_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  { uintptr_t _jt=(uintptr_t)(a0); if(_jt) ((void(*)(void))_jt)(); }  /* JSR	(A0) */
  a0 = (uint32_t)(uintptr_t)StructAdr;  /* LEA	StructAdr(PC),A0 */
  hw_write16(a0 + (intptr_t)UPS_Enabled, 0);  /* CLR.W	UPS_Enabled(A0) */
  d1 = READ32_POST(sp);  /* MOVEM.L	(SP)+,D1,D2,D3,D4,D5,D6,D7,A0,A1,A2,A3,A4,A5,A6 */
    d2 = READ32_POST(sp);
    d3 = READ32_POST(sp);
    d4 = READ32_POST(sp);
    d5 = READ32_POST(sp);
    d6 = READ32_POST(sp);
    d7 = READ32_POST(sp);
    a0 = READ32_POST(sp);
    a1 = READ32_POST(sp);
    a2 = READ32_POST(sp);
    a3 = READ32_POST(sp);
    a4 = READ32_POST(sp);
    a5 = READ32_POST(sp);
    a6 = READ32_POST(sp);
  d0 = (uint32_t)(int32_t)(int8_t)(0);  /* MOVEQ	#0,D0 */
  return;  /* RTS */
}


/* --- SongEnd --- */
static void SongEnd(void) {
  WRITE32_PRE(sp, a5);  /* MOVEM.L	A1,A5,-(A7) */
    WRITE32_PRE(sp, a1);
  {  /* MOVE.L	EagleBase(PC),A5 */
      uint32_t _mv = (uint32_t)(READ32((uintptr_t)EagleBase));
      a5 = _mv;
      flag_z = ((int32_t)(_mv) == 0);
      flag_n = ((int32_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  {  /* MOVE.L	dtg_SongEnd(A5),A1 */
      uint32_t _mv = (uint32_t)(READ32(a5 + (intptr_t)dtg_SongEnd));
      a1 = _mv;
      flag_z = ((int32_t)(_mv) == 0);
      flag_n = ((int32_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  { uintptr_t _jt=(uintptr_t)(a1); if(_jt) ((void(*)(void))_jt)(); }  /* JSR	(A1) */
  a1 = READ32_POST(sp);  /* MOVEM.L	(A7)+,A1,A5 */
    a5 = READ32_POST(sp);
  return;  /* RTS */
}


/* --- SetAudioVector ---  (cross-function goto target) */
static void SetAudioVector(void) {
  WRITE32_PRE(sp, a6);  /* MOVEM.L	D0,A1,A6,-(A7) */
    WRITE32_PRE(sp, a1);
    WRITE32_PRE(sp, d0);
  a6 = 4;  /* MOVEA.L	#4,A6 */
  a1 = (uint32_t)(uintptr_t)StructInt;  /* LEA	StructInt(PC),A1 */
  d0 = (uint32_t)(int32_t)(int8_t)(INTB_AUD0);  /* MOVEQ	#INTB_AUD0,D0 */
  { uintptr_t _jt=(uintptr_t)(READ32(a6 + (intptr_t)_LVOSetIntVector)); if(_jt) ((void(*)(void))_jt)(); }  /* JSR	_LVOSetIntVector(A6) */
  {  /* MOVE.L	D0,Channel0 */
      uint32_t _mv = (uint32_t)(d0);
      WRITE32((uintptr_t)Channel0, _mv);
      flag_z = ((int32_t)(_mv) == 0);
      flag_n = ((int32_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  a1 = (uint32_t)(uintptr_t)StructInt;  /* LEA	StructInt(PC),A1 */
  d0 = (uint32_t)(int32_t)(int8_t)(INTB_AUD1);  /* MOVEQ	#INTB_AUD1,D0 */
  { uintptr_t _jt=(uintptr_t)(READ32(a6 + (intptr_t)_LVOSetIntVector)); if(_jt) ((void(*)(void))_jt)(); }  /* JSR	_LVOSetIntVector(A6) */
  {  /* MOVE.L	D0,Channel1 */
      uint32_t _mv = (uint32_t)(d0);
      WRITE32((uintptr_t)Channel1, _mv);
      flag_z = ((int32_t)(_mv) == 0);
      flag_n = ((int32_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  a1 = (uint32_t)(uintptr_t)StructInt;  /* LEA	StructInt(PC),A1 */
  d0 = (uint32_t)(int32_t)(int8_t)(INTB_AUD2);  /* MOVEQ	#INTB_AUD2,D0 */
  { uintptr_t _jt=(uintptr_t)(READ32(a6 + (intptr_t)_LVOSetIntVector)); if(_jt) ((void(*)(void))_jt)(); }  /* JSR	_LVOSetIntVector(A6) */
  {  /* MOVE.L	D0,Channel2 */
      uint32_t _mv = (uint32_t)(d0);
      WRITE32((uintptr_t)Channel2, _mv);
      flag_z = ((int32_t)(_mv) == 0);
      flag_n = ((int32_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  a1 = (uint32_t)(uintptr_t)StructInt;  /* LEA	StructInt(PC),A1 */
  d0 = (uint32_t)(int32_t)(int8_t)(INTB_AUD3);  /* MOVEQ	#INTB_AUD3,D0 */
  { uintptr_t _jt=(uintptr_t)(READ32(a6 + (intptr_t)_LVOSetIntVector)); if(_jt) ((void(*)(void))_jt)(); }  /* JSR	_LVOSetIntVector(A6) */
  {  /* MOVE.L	D0,Channel3 */
      uint32_t _mv = (uint32_t)(d0);
      WRITE32((uintptr_t)Channel3, _mv);
      flag_z = ((int32_t)(_mv) == 0);
      flag_n = ((int32_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  d0 = READ32_POST(sp);  /* MOVEM.L	(A7)+,D0,A1,A6 */
    a1 = READ32_POST(sp);
    a6 = READ32_POST(sp);
  return;  /* RTS */
}


/* --- ClearAudioVector --- */
static void ClearAudioVector(void) {
  a6 = 4;  /* MOVEA.L	#4,A6 */
  a1 = READ32((uintptr_t)Channel0);  /* MOVEA.L	Channel0(PC),A1 */
  d0 = (uint32_t)(int32_t)(int8_t)(INTB_AUD0);  /* MOVEQ	#INTB_AUD0,D0 */
  { uintptr_t _jt=(uintptr_t)(READ32(a6 + (intptr_t)_LVOSetIntVector)); if(_jt) ((void(*)(void))_jt)(); }  /* JSR	_LVOSetIntVector(A6) */
  a1 = READ32((uintptr_t)Channel1);  /* MOVEA.L	Channel1(PC),A1 */
  d0 = (uint32_t)(int32_t)(int8_t)(INTB_AUD1);  /* MOVEQ	#INTB_AUD1,D0 */
  { uintptr_t _jt=(uintptr_t)(READ32(a6 + (intptr_t)_LVOSetIntVector)); if(_jt) ((void(*)(void))_jt)(); }  /* JSR	_LVOSetIntVector(A6) */
  a1 = READ32((uintptr_t)Channel2);  /* MOVEA.L	Channel2(PC),A1 */
  d0 = (uint32_t)(int32_t)(int8_t)(INTB_AUD2);  /* MOVEQ	#INTB_AUD2,D0 */
  { uintptr_t _jt=(uintptr_t)(READ32(a6 + (intptr_t)_LVOSetIntVector)); if(_jt) ((void(*)(void))_jt)(); }  /* JSR	_LVOSetIntVector(A6) */
  a1 = READ32((uintptr_t)Channel3);  /* MOVEA.L	Channel3(PC),A1 */
  d0 = (uint32_t)(int32_t)(int8_t)(INTB_AUD3);  /* MOVEQ	#INTB_AUD3,D0 */
  ((void(*)(void))(uintptr_t)(a6 + (intptr_t)_LVOSetIntVector))(); return;  /* JMP	_LVOSetIntVector(A6) */
}

/* ************************************************************************** */
/* **************************** DTP_SubSongRange **************************** */
/* ************************************************************************** */

/* --- SubSongRange --- */
static void SubSongRange(void) {
  d0 = (uint32_t)(int32_t)(int8_t)(0);  /* MOVEQ	#0,D0 */
  {  /* MOVE.L	InfoBuffer+SubSongs(PC),D1 */
      uint32_t _mv = (uint32_t)(READ32((uintptr_t)InfoBuffer+SubSongs));
      d1 = _mv;
      flag_z = ((int32_t)(_mv) == 0);
      flag_n = ((int32_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  {  /* SUBQ.L	#1,D1 */
      uint32_t _sr = (uint32_t)(d1 - 1);
      d1 = (uint32_t)_sr;
      flag_z = ((int32_t)(_sr) == 0);
      flag_n = ((int32_t)(_sr) < 0);
    }
  return;  /* RTS */
}

/* ************************************************************************** */
/* **************************** DTP_InitPlayer ****************************** */
/* ************************************************************************** */

/* --- InitPlayer --- */
void InitPlayer(void) {
  {  /* MOVE.L	dtg_DOSBase(A5),A6 */
      uint32_t _mv = (uint32_t)(READ32(a5 + (intptr_t)dtg_DOSBase));
      a6 = _mv;
      flag_z = ((int32_t)(_mv) == 0);
      flag_n = ((int32_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  {  /* MOVE.L	dtg_PathArrayPtr(A5),D1 */
      uint32_t _mv = (uint32_t)(READ32(a5 + (intptr_t)dtg_PathArrayPtr));
      d1 = _mv;
      flag_z = ((int32_t)(_mv) == 0);
      flag_n = ((int32_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  { uintptr_t _jt=(uintptr_t)(READ32(a6 + (intptr_t)_LVOLoadSeg)); if(_jt) ((void(*)(void))_jt)(); }  /* JSR	_LVOLoadSeg(A6) */
  d0 = d0 << 2;  /* LSL.L	#2,D0 */
  if (flag_z) { InitFail(); return; }  /* equal / zero */  /* BEQ.W	InitFail */
  {  /* ADDQ.L	#4,D0 */
      uint32_t _ar = (uint32_t)(d0 + 4);
      d0 = (uint32_t)_ar;
      flag_z = ((int32_t)(_ar) == 0);
      flag_n = ((int32_t)(_ar) < 0);
    }
  {  /* MOVE.L	D0,A0 */
      uint32_t _mv = (uint32_t)(d0);
      a0 = _mv;
      flag_z = ((int32_t)(_mv) == 0);
      flag_n = ((int32_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  a2 = (uint32_t)(uintptr_t)InfoBuffer;  /* LEA	InfoBuffer(PC),A2 */
  a1 = (uint32_t)(uintptr_t)ModulePtr;  /* LEA	ModulePtr(PC),A1 */
  {  /* MOVE.L	D0,(A1)+ */
      uint32_t _mv = (uint32_t)(d0);
      WRITE32_POST(a1, _mv);
      flag_z = ((int32_t)(_mv) == 0);
      flag_n = ((int32_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  a0 = (uint32_t)((int32_t)a0 + (int32_t)(int16_t)(8));  /* ADDQ.L	#8,A0 */
  a0 = (uint32_t)((int32_t)a0 + (int32_t)(int16_t)(4));  /* ADDQ.L	#4,A0 */
  {  /* MOVE.L	(A0)+,(A1)+ */
      uint32_t _mv = (uint32_t)(READ32_POST(a0));
      WRITE32_POST(a1, _mv);
      flag_z = ((int32_t)(_mv) == 0);
      flag_n = ((int32_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  {  /* MOVE.L	(A0)+,(A1)+ */
      uint32_t _mv = (uint32_t)(READ32_POST(a0));
      WRITE32_POST(a1, _mv);
      flag_z = ((int32_t)(_mv) == 0);
      flag_n = ((int32_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  {  /* MOVE.L	(A0)+,(A1)+ */
      uint32_t _mv = (uint32_t)(READ32_POST(a0));
      WRITE32_POST(a1, _mv);
      flag_z = ((int32_t)(_mv) == 0);
      flag_n = ((int32_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  {  /* MOVE.L	(A0)+,(A1)+ */
      uint32_t _mv = (uint32_t)(READ32_POST(a0));
      WRITE32_POST(a1, _mv);
      flag_z = ((int32_t)(_mv) == 0);
      flag_n = ((int32_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  {  /* MOVE.L	(A0)+,SubSongs(A2) */
      uint32_t _mv = (uint32_t)(READ32_POST(a0));
      hw_write32(a2 + (intptr_t)SubSongs, _mv);
      flag_z = ((int32_t)(_mv) == 0);
      flag_n = ((int32_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  {  /* MOVE.L	(A0)+,(A1)+ */
      uint32_t _mv = (uint32_t)(READ32_POST(a0));
      WRITE32_POST(a1, _mv);
      flag_z = ((int32_t)(_mv) == 0);
      flag_n = ((int32_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  {  /* MOVE.L	(A0)+,(A1)+ */
      uint32_t _mv = (uint32_t)(READ32_POST(a0));
      WRITE32_POST(a1, _mv);
      flag_z = ((int32_t)(_mv) == 0);
      flag_n = ((int32_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  {  /* MOVE.L	(A0)+,SongName(A2) */
      uint32_t _mv = (uint32_t)(READ32_POST(a0));
      hw_write32(a2 + (intptr_t)SongName, _mv);
      flag_z = ((int32_t)(_mv) == 0);
      flag_n = ((int32_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  {  /* MOVE.L	(A0)+,AuthorName(A2) */
      uint32_t _mv = (uint32_t)(READ32_POST(a0));
      hw_write32(a2 + (intptr_t)AuthorName, _mv);
      flag_z = ((int32_t)(_mv) == 0);
      flag_n = ((int32_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  {  /* MOVE.L	(A0)+,SpecialInfo(A2) */
      uint32_t _mv = (uint32_t)(READ32_POST(a0));
      hw_write32(a2 + (intptr_t)SpecialInfo, _mv);
      flag_z = ((int32_t)(_mv) == 0);
      flag_n = ((int32_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  {  /* MOVE.L	(A0)+,LoadSize(A2) */
      uint32_t _mv = (uint32_t)(READ32_POST(a0));
      hw_write32(a2 + (intptr_t)LoadSize, _mv);
      flag_z = ((int32_t)(_mv) == 0);
      flag_n = ((int32_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  {  /* MOVE.L	(A0)+,CalcSize(A2) */
      uint32_t _mv = (uint32_t)(READ32_POST(a0));
      hw_write32(a2 + (intptr_t)CalcSize, _mv);
      flag_z = ((int32_t)(_mv) == 0);
      flag_n = ((int32_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  {  /* MOVE.L	(A0)+,SamplesSize(A2) */
      uint32_t _mv = (uint32_t)(READ32_POST(a0));
      hw_write32(a2 + (intptr_t)SamplesSize, _mv);
      flag_z = ((int32_t)(_mv) == 0);
      flag_n = ((int32_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  {  /* MOVE.L	(A0)+,SongSize(A2) */
      uint32_t _mv = (uint32_t)(READ32_POST(a0));
      hw_write32(a2 + (intptr_t)SongSize, _mv);
      flag_z = ((int32_t)(_mv) == 0);
      flag_n = ((int32_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  {  /* MOVE.L	EndSampleInfoPtr(PC),D1 */
      uint32_t _mv = (uint32_t)(READ32((uintptr_t)EndSampleInfoPtr));
      d1 = _mv;
      flag_z = ((int32_t)(_mv) == 0);
      flag_n = ((int32_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  {  /* SUB.L	SampleInfoPtr(PC),D1 */
      uint32_t _sr = (uint32_t)(d1 - READ32((uintptr_t)SampleInfoPtr));
      d1 = (uint32_t)_sr;
      flag_z = ((int32_t)(_sr) == 0);
      flag_n = ((int32_t)(_sr) < 0);
    }
  {  /* DIVU.W	#14,D1 */
      uint16_t q = (uint16_t)((uint32_t)d1 / (uint16_t)14);
      uint16_t r = (uint16_t)((uint32_t)d1 % (uint16_t)14);
      d1 = ((uint32_t)r << 16) | q;
    }
  {  /* MOVE.L	D1,Samples(A2) */
      uint32_t _mv = (uint32_t)(d1);
      hw_write32(a2 + (intptr_t)Samples, _mv);
      flag_z = ((int32_t)(_mv) == 0);
      flag_n = ((int32_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  {  /* MOVE.L	A5,(A1)+ */
      uint32_t _mv = (uint32_t)(a5);
      WRITE32_POST(a1, _mv);
      flag_z = ((int32_t)(_mv) == 0);
      flag_n = ((int32_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  WRITE16_POST(a1, 0);  /* CLR.W	(A1)+ */
  {  /* MOVE.L	EndSongPtr(PC),A2 */
      uint32_t _mv = (uint32_t)(READ32((uintptr_t)EndSongPtr));
      a2 = _mv;
      flag_z = ((int32_t)(_mv) == 0);
      flag_n = ((int32_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  {  /* MOVE.L	A2,A0 */
      uint32_t _mv = (uint32_t)(a2);
      a0 = _mv;
      flag_z = ((int32_t)(_mv) == 0);
      flag_n = ((int32_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
More:
  {  /* CMP.L	#$3BC03865,(A2) */
      int32_t _lhs = (int32_t)(READ32(a2));
      int32_t _rhs = (int32_t)(0x3BC03865);
      int32_t _cmp = _lhs - _rhs;
      flag_z = (_cmp == 0);
      flag_n = (_cmp < 0);
      flag_c = ((uint32_t)_lhs < (uint32_t)_rhs);
    }
  if (flag_z) goto Note;  /* equal / zero */  /* BEQ.B	Note */
  {  /* CMP.W	#$4E73,(A2) */
      int32_t _lhs = (int32_t)(READ16(a2));
      int32_t _rhs = (int32_t)(0x4E73);
      int32_t _cmp = _lhs - _rhs;
      flag_z = (_cmp == 0);
      flag_n = (_cmp < 0);
      flag_c = ((uint32_t)_lhs < (uint32_t)_rhs);
    }
  if (!flag_z) goto NoRTE;  /* not equal / nonzero */  /* BNE.B	NoRTE */
  {  /* ADDQ.W	#2,(A2)+ */
      uint16_t _ar = (uint16_t)(READ16_POST(a2) + 2);
      WRITE16_POST(a2, (uint16_t)_ar);
      flag_z = ((int16_t)(_ar) == 0);
      flag_n = ((int16_t)(_ar) < 0);
    }
  goto More;  /* BRA.B	More */
NoRTE:
  {  /* CMP.W	#$46DF,(A2) */
      int32_t _lhs = (int32_t)(READ16(a2));
      int32_t _rhs = (int32_t)(0x46DF);
      int32_t _cmp = _lhs - _rhs;
      flag_z = (_cmp == 0);
      flag_n = (_cmp < 0);
      flag_c = ((uint32_t)_lhs < (uint32_t)_rhs);
    }
  if (!flag_z) goto NoSR;  /* not equal / nonzero */  /* BNE.B	NoSR */
  {  /* MOVE.W	#$4E71,(A2) */
      uint16_t _mv = (uint16_t)(0x4E71);
      hw_write16(a2, _mv);
      flag_z = ((int16_t)(_mv) == 0);
      flag_n = ((int16_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
NoSR:
  a2 = (uint32_t)((int32_t)a2 + (int32_t)(int16_t)(2));  /* ADDQ.L	#2,A2 */
  goto More;  /* BRA.B	More */
Note:
  a2 = (uint32_t)((int32_t)a2 - (int32_t)(int16_t)(a0));  /* SUB.L	A0,A2 */
  {  /* MOVE.L	A2,(A1) */
      uint32_t _mv = (uint32_t)(a2);
      hw_write32(a1, _mv);
      flag_z = ((int32_t)(_mv) == 0);
      flag_n = ((int32_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  {  /* MOVE.L	AudioPtr(PC),A0 */
      uint32_t _mv = (uint32_t)(READ32((uintptr_t)AudioPtr));
      a0 = _mv;
      flag_z = ((int32_t)(_mv) == 0);
      flag_n = ((int32_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  a2 = (uint32_t)(uintptr_t)IntAddress;  /* LEA	IntAddress(PC),A2 */
  {  /* MOVE.L	A0,(A2) */
      uint32_t _mv = (uint32_t)(a0);
      hw_write32(a2, _mv);
      flag_z = ((int32_t)(_mv) == 0);
      flag_n = ((int32_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  ModuleChange();  /* BSR.W	ModuleChange */
  a0 = READ32(a5 + (intptr_t)dtg_AudioAlloc);  /* MOVEA.L	dtg_AudioAlloc(A5),A0 */
  ((void(*)(void))(uintptr_t)a0)(); return;  /* JMP	(A0) */
}


/* --- InitFail ---  (cross-function goto target) */
static void InitFail(void) {
  d0 = (uint32_t)(int32_t)(int8_t)(EPR_NotEnoughMem);  /* MOVEQ	#EPR_NotEnoughMem,D0 */
  return;  /* RTS */
}

/* ************************************************************************** */
/* **************************** DTP_EndPlayer ******************************* */
/* ************************************************************************** */

/* --- EndPlayer --- */
static void EndPlayer(void) {
  {  /* MOVE.L	dtg_DOSBase(A5),A6 */
      uint32_t _mv = (uint32_t)(READ32(a5 + (intptr_t)dtg_DOSBase));
      a6 = _mv;
      flag_z = ((int32_t)(_mv) == 0);
      flag_n = ((int32_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  {  /* MOVE.L	ModulePtr(PC),D1 */
      uint32_t _mv = (uint32_t)(READ32((uintptr_t)ModulePtr));
      d1 = _mv;
      flag_z = ((int32_t)(_mv) == 0);
      flag_n = ((int32_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  {  /* SUBQ.L	#4,D1 */
      uint32_t _sr = (uint32_t)(d1 - 4);
      d1 = (uint32_t)_sr;
      flag_z = ((int32_t)(_sr) == 0);
      flag_n = ((int32_t)(_sr) < 0);
    }
  d1 >>= 2;  /* LSR.L	#2,D1 */
  ((void(*)(void))(uintptr_t)(a6 + (intptr_t)_LVOUnLoadSeg))(); return;  /* JMP	_LVOUnLoadSeg(A6) */
}

/* ************************************************************************** */
/* **************************** DTP_InitSound ******************************* */
/* ************************************************************************** */

/* --- InitSound --- */
void InitSound(void) {
  a0 = (uint32_t)(uintptr_t)StructAdr;  /* LEA	StructAdr(PC),A0 */
  a1 = (uint32_t)(a0 + (intptr_t)UPS_SizeOF);  /* LEA	UPS_SizeOF(A0),A1 */
ClearUPS:
  WRITE16_POST(a0, 0);  /* CLR.W	(A0)+ */
  {  /* CMP.L	A0,A1 */
      int32_t _lhs = (int32_t)(a1);
      int32_t _rhs = (int32_t)(a0);
      int32_t _cmp = _lhs - _rhs;
      flag_z = (_cmp == 0);
      flag_n = (_cmp < 0);
      flag_c = ((uint32_t)_lhs < (uint32_t)_rhs);
    }
  if (!flag_z) goto ClearUPS;  /* not equal / nonzero */  /* BNE.B	ClearUPS */
  a0 = (uint32_t)(uintptr_t)OldVoice1;  /* LEA	OldVoice1(PC),A0 */
  WRITE32_POST(a0, 0);  /* CLR.L	(A0)+ */
  hw_write32(a0, 0);  /* CLR.L	(A0) */
  d1 = (uint32_t)(int32_t)(int8_t)(1);  /* MOVEQ	#1,D1 */
  {  /* MOVE.W	dtg_SndNum(A5),D0 */
      uint16_t _mv = (uint16_t)(READ16(a5 + (intptr_t)dtg_SndNum));
      W(d0) = (uint16_t)_mv;
      flag_z = ((int16_t)(_mv) == 0);
      flag_n = ((int16_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  a1 = (uint32_t)(uintptr_t)SongEndFlag;  /* LEA	SongEndFlag(PC),A1 */
  hw_write8(a1, 0xFF);  /* ST	(A1) */
  {  /* MOVE.L	InitSongPtr(PC),A0 */
      uint32_t _mv = (uint32_t)(READ32((uintptr_t)InitSongPtr));
      a0 = _mv;
      flag_z = ((int32_t)(_mv) == 0);
      flag_n = ((int32_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  { uintptr_t _jt=(uintptr_t)(a0); if(_jt) ((void(*)(void))_jt)(); }  /* JSR	(A0) */
  a1 = (uint32_t)(uintptr_t)SongEndFlag;  /* LEA	SongEndFlag(PC),A1 */
  hw_write16(a1, 0);  /* CLR.W	(A1) */
  SetAudioVector(); return;  /* BRA.W	SetAudioVector */
}

/* ************************************************************************** */
/* **************************** DTP_EndSound ******************************** */
/* ************************************************************************** */

/* --- EndSound --- */
void EndSound(void) {
  ClearAudioVector();  /* BSR.W	ClearAudioVector */
  {  /* MOVE.L	EndSongPtr(PC),A0 */
      uint32_t _mv = (uint32_t)(READ32((uintptr_t)EndSongPtr));
      a0 = _mv;
      flag_z = ((int32_t)(_mv) == 0);
      flag_n = ((int32_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  { uintptr_t _jt=(uintptr_t)(a0); if(_jt) ((void(*)(void))_jt)(); }  /* JSR	(A0) */
  a0 = (uint32_t)0xDFF000;  /* LEA	$DFF000,A0 */
  {  /* MOVE.W	#15,150(A0) */
      uint16_t _mv = (uint16_t)(15);
      hw_write16(a0 + 150, _mv);
      flag_z = ((int16_t)(_mv) == 0);
      flag_n = ((int16_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  d0 = (uint32_t)(int32_t)(int8_t)(0);  /* MOVEQ	#0,D0 */
  {  /* MOVE.W	D0,168(A0) */
      uint16_t _mv = (uint16_t)(W(d0));
      hw_write16(a0 + 168, _mv);
      flag_z = ((int16_t)(_mv) == 0);
      flag_n = ((int16_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  {  /* MOVE.W	D0,184(A0) */
      uint16_t _mv = (uint16_t)(W(d0));
      hw_write16(a0 + 184, _mv);
      flag_z = ((int16_t)(_mv) == 0);
      flag_n = ((int16_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  {  /* MOVE.W	D0,200(A0) */
      uint16_t _mv = (uint16_t)(W(d0));
      hw_write16(a0 + 200, _mv);
      flag_z = ((int16_t)(_mv) == 0);
      flag_n = ((int16_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  {  /* MOVE.W	D0,216(A0) */
      uint16_t _mv = (uint16_t)(W(d0));
      hw_write16(a0 + 216, _mv);
      flag_z = ((int16_t)(_mv) == 0);
      flag_n = ((int16_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  return;  /* RTS */
}

/* ----------------- PatchTable for Core Design -------------------* */
/* Audio Interrupt patch for Core Design modules */

/* --- Code0 --- */
static void Code0(void) {
  {  /* MOVE.W	D0,$DFF09C */
      uint16_t _mv = (uint16_t)(W(d0));
      /* hw $DFF09C */ (void)(_mv);
      flag_z = ((int16_t)(_mv) == 0);
      flag_n = ((int16_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
Code0End:
Patch0:
  {  /* MOVE.W	D0,$DFF09A */
      uint16_t _mv = (uint16_t)(W(d0));
      /* hw $DFF09A */ (void)(_mv);
      flag_z = ((int16_t)(_mv) == 0);
      flag_n = ((int16_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  {  /* MOVE.W	D0,$DFF09C */
      uint16_t _mv = (uint16_t)(W(d0));
      /* hw $DFF09C */ (void)(_mv);
      flag_z = ((int16_t)(_mv) == 0);
      flag_n = ((int16_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  return;  /* RTS */
}

/* Audio Interrupt patch for Core Design modules */

/* --- Code1 --- */
static void Code1(void) {
  {  /* MOVE.W	D2,$DFF09C */
      uint16_t _mv = (uint16_t)(W(d2));
      /* hw $DFF09C */ (void)(_mv);
      flag_z = ((int16_t)(_mv) == 0);
      flag_n = ((int16_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
Code1End:
Patch1:
  {  /* MOVE.W	D2,$DFF09A */
      uint16_t _mv = (uint16_t)(W(d2));
      /* hw $DFF09A */ (void)(_mv);
      flag_z = ((int16_t)(_mv) == 0);
      flag_n = ((int16_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  {  /* MOVE.W	D2,$DFF09C */
      uint16_t _mv = (uint16_t)(W(d2));
      /* hw $DFF09C */ (void)(_mv);
      flag_z = ((int16_t)(_mv) == 0);
      flag_n = ((int16_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  return;  /* RTS */
}

/* SR patch for Core Design modules */

/* --- Code2 --- */
static void Code2(void) {
  {  /* MOVE.W	SR,-(SP) */
      uint16_t _mv = (uint16_t)(W(sr));
      WRITE16_PRE(sp, _mv);
      flag_z = ((int16_t)(_mv) == 0);
      flag_n = ((int16_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  W(sr) |= (uint16_t)(0x700);  /* ORI.W	#$700,SR */
Code2End:
Patch2:
  return;  /* RTS */
}

/* SongEnd patch for Core Design modules */

/* --- Code3 --- */
static void Code3(void) {
  d2 = (uint32_t)(int32_t)(int8_t)(0);  /* MOVEQ	#0,D2 */
  {  /* MOVE.B	D0,D2 */
      uint8_t _mv = (uint8_t)(B(d0));
      B(d2) = (uint8_t)_mv;
      flag_z = ((int8_t)(_mv) == 0);
      flag_n = ((int8_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  W(d2) = (uint16_t)(W(d2) << 3);  /* ASL.W	#3,D2 */
Code3End:
Patch3:
  d2 = (uint32_t)(int32_t)(int8_t)(0);  /* MOVEQ	#0,D2 */
  {  /* MOVE.B	D0,D2 */
      uint8_t _mv = (uint8_t)(B(d0));
      B(d2) = (uint8_t)_mv;
      flag_z = ((int8_t)(_mv) == 0);
      flag_n = ((int8_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  W(d2) = (uint16_t)(W(d2) << 3);  /* ASL.W	#3,D2 */
  {  /* TST.W	SongEndFlag */
      uint16_t _tst = (uint16_t)(READ16((uintptr_t)SongEndFlag));
      flag_z = (_tst == 0);
      flag_n = ((int16_t)(_tst) < 0);
      flag_c = 0; flag_v = 0;
    }
  if (!flag_z) goto NoEnd;  /* not equal / nonzero */  /* BNE.B	NoEnd */
  SongEnd();  /* BSR.W	SongEnd */
NoEnd:
  return;  /* RTS */
}

/* Period/length/address patch for Core Design modules */

/* --- Code4 --- */
static void Code4(void) {
  {  /* MOVE.W	(A0)+,18(A6) */
      uint16_t _mv = (uint16_t)(READ16_POST(a0));
      hw_write16(a6 + 18, _mv);
      flag_z = ((int16_t)(_mv) == 0);
      flag_n = ((int16_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  {  /* MOVE.L	A0,14(A6) */
      uint32_t _mv = (uint32_t)(a0);
      hw_write32(a6 + 14, _mv);
      flag_z = ((int32_t)(_mv) == 0);
      flag_n = ((int32_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
Code4End:
Patch4:
  {  /* MOVE.W	(A0)+,18(A6) */
      uint16_t _mv = (uint16_t)(READ16_POST(a0));
      hw_write16(a6 + 18, _mv);
      flag_z = ((int16_t)(_mv) == 0);
      flag_n = ((int16_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  {  /* MOVE.L	A0,14(A6) */
      uint32_t _mv = (uint32_t)(a0);
      hw_write32(a6 + 14, _mv);
      flag_z = ((int32_t)(_mv) == 0);
      flag_n = ((int32_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  SetAll();  /* BSR.W	SetAll */
  return;  /* RTS */
}

/* Volume patch for Core Design modules */

/* --- Code5 --- */
static void Code5(void) {
  W(d0) = (uint16_t)((uint32_t)(W(d0)) >> 1);  /* LSR.W	#1,D0 */
  {  /* MOVE.W	D0,168(A4) */
      uint16_t _mv = (uint16_t)(W(d0));
      hw_write16(a4 + 168, _mv);
      flag_z = ((int16_t)(_mv) == 0);
      flag_n = ((int16_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
Code5End:
Patch5:
  W(d0) = (uint16_t)((uint32_t)(W(d0)) >> 1);  /* LSR.W	#1,D0 */
  ChangeVolume();  /* BSR.W	ChangeVolume */
  SetVol();  /* BSR.W	SetVol */
  return;  /* RTS */
}

/* Period/length/address patch for Core Design modules */

/* --- Code6 --- */
static void Code6(void) {
  {  /* MOVE.W	0(A0),8(A6) */
      uint16_t _mv = (uint16_t)(READ16(a0 + 0 + (int16_t)W(d0)));
      hw_write16(a6 + 8, _mv);
      flag_z = ((int16_t)(_mv) == 0);
      flag_n = ((int16_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
Code6End:
Patch6:
  {  /* MOVE.W	0(A0),8(A6) */
      uint16_t _mv = (uint16_t)(READ16(a0 + 0 + (int16_t)W(d0)));
      hw_write16(a6 + 8, _mv);
      flag_z = ((int16_t)(_mv) == 0);
      flag_n = ((int16_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  SetPer();  /* BSR.W	SetPer */
  return;  /* RTS */
}

/* Patch DC.L label references with runtime addresses */
static void _ds_init(void) {
  WRITE32((uintptr_t)(_ds + 80), (uint32_t)(uintptr_t)PlayerName);
  WRITE32((uintptr_t)(_ds + 88), (uint32_t)(uintptr_t)Creator);
  WRITE32((uintptr_t)(_ds + 96), (uint32_t)(uintptr_t)DeliBase);
  WRITE32((uintptr_t)(_ds + 104), (uint32_t)(uintptr_t)Check1);
  WRITE32((uintptr_t)(_ds + 120), (uint32_t)(uintptr_t)Interrupt);
  WRITE32((uintptr_t)(_ds + 128), (uint32_t)(uintptr_t)SubSongRange);
  WRITE32((uintptr_t)(_ds + 136), (uint32_t)(uintptr_t)InitPlayer);
  WRITE32((uintptr_t)(_ds + 144), (uint32_t)(uintptr_t)EndPlayer);
  WRITE32((uintptr_t)(_ds + 160), (uint32_t)(uintptr_t)EndSound);
  WRITE32((uintptr_t)(_ds + 168), (uint32_t)(uintptr_t)GetInfos);
  WRITE32((uintptr_t)(_ds + 176), (uint32_t)(uintptr_t)SampleInit);
  WRITE32((uintptr_t)(_ds + 184), (uint32_t)(uintptr_t)ModuleChange);
  WRITE32((uintptr_t)(_ds + 192), (uint32_t)(uintptr_t)SetVolume);
  WRITE32((uintptr_t)(_ds + 208), (uint32_t)(uintptr_t)SetVoices);
  WRITE32((uintptr_t)(_ds + 216), (uint32_t)(uintptr_t)StructInit);
  WRITE32((uintptr_t)(_ds + 484), (uint32_t)(uintptr_t)Prefix);
  WRITE32((uintptr_t)(_ds + 518), (uint32_t)(uintptr_t)IntName);
}


/* TRANSPILER WARNINGS:
 * Line 142: Custom chip write $DFF000 — emitted as no-op
 * Line 630: Custom chip write $DFF000 — emitted as no-op
 * Line 655: Custom chip write $DFF09C — emitted as no-op
 * Line 658: Custom chip write $DFF09A — emitted as no-op
 * Line 659: Custom chip write $DFF09C — emitted as no-op
 * Line 665: Custom chip write $DFF09C — emitted as no-op
 * Line 668: Custom chip write $DFF09A — emitted as no-op
 * Line 669: Custom chip write $DFF09C — emitted as no-op
 */