import type { SynthPreset } from './types';

export const FM_SYNTH_PRESETS: SynthPreset[] = [
  {
    id: 'fm-electric-piano',
    name: 'Electric Piano',
    description: 'Classic DX7-style electric piano',
    category: 'key',
    config: {
      oscillator: { type: 'sine' },
      modulationIndex: 3.5,
      harmonicity: 2,
      envelope: { attack: 0.001, decay: 1.2, sustain: 0.1, release: 0.8 },
      modulationEnvelope: { attack: 0.001, decay: 0.5, sustain: 0.2, release: 0.5 },
    },
  },
  {
    id: 'fm-bass',
    name: 'FM Bass',
    description: 'Punchy FM synthesis bass',
    category: 'bass',
    config: {
      oscillator: { type: 'sine' },
      modulationIndex: 8,
      harmonicity: 1,
      envelope: { attack: 0.005, decay: 0.3, sustain: 0.4, release: 0.15 },
      modulationEnvelope: { attack: 0.001, decay: 0.15, sustain: 0.0, release: 0.1 },
    },
  },
  {
    id: 'fm-bell',
    name: 'Crystal Bell',
    description: 'Shimmering bell tone',
    category: 'key',
    config: {
      oscillator: { type: 'sine' },
      modulationIndex: 12,
      harmonicity: 3.5,
      envelope: { attack: 0.001, decay: 2.5, sustain: 0.0, release: 1.5 },
      modulationEnvelope: { attack: 0.001, decay: 1.8, sustain: 0.0, release: 1.0 },
    },
  },
  {
    id: 'fm-metallic-lead',
    name: 'Metallic Lead',
    description: 'Harsh metallic FM lead',
    category: 'lead',
    config: {
      oscillator: { type: 'square' },
      modulationIndex: 15,
      harmonicity: 2.5,
      envelope: { attack: 0.005, decay: 0.2, sustain: 0.7, release: 0.2 },
      modulationEnvelope: { attack: 0.01, decay: 0.4, sustain: 0.5, release: 0.3 },
    },
  },
  {
    id: 'fm-pluck',
    name: 'FM Pluck',
    description: 'Short percussive FM pluck',
    category: 'key',
    config: {
      oscillator: { type: 'sine' },
      modulationIndex: 6,
      harmonicity: 4,
      envelope: { attack: 0.001, decay: 0.2, sustain: 0.0, release: 0.1 },
      modulationEnvelope: { attack: 0.001, decay: 0.1, sustain: 0.0, release: 0.05 },
    },
  },
  {
    id: 'fm-organ',
    name: 'FM Organ',
    description: 'Warm organ-like FM tone',
    category: 'key',
    config: {
      oscillator: { type: 'sine' },
      modulationIndex: 2,
      harmonicity: 1,
      envelope: { attack: 0.01, decay: 0.1, sustain: 0.9, release: 0.3 },
      modulationEnvelope: { attack: 0.01, decay: 0.1, sustain: 0.8, release: 0.3 },
    },
  },
  {
    id: 'fm-wobble',
    name: 'FM Wobble',
    description: 'Unstable vibrating FM texture',
    category: 'fx',
    config: {
      oscillator: { type: 'sine' },
      modulationIndex: 20,
      harmonicity: 1.414,
      envelope: { attack: 0.05, decay: 0.8, sustain: 0.5, release: 0.4 },
      modulationEnvelope: { attack: 0.1, decay: 1.0, sustain: 0.6, release: 0.5 },
    },
  },
  {
    id: 'fm-glass',
    name: 'Glass Marimba',
    description: 'Bright glassy percussive tone',
    category: 'key',
    config: {
      oscillator: { type: 'sine' },
      modulationIndex: 5,
      harmonicity: 5.07,
      envelope: { attack: 0.001, decay: 1.0, sustain: 0.0, release: 0.6 },
      modulationEnvelope: { attack: 0.001, decay: 0.4, sustain: 0.0, release: 0.3 },
    },
  },
  {
    id: 'fm-snarl-bass',
    name: 'Snarl Bass',
    description: 'Aggressive growling FM bass',
    category: 'bass',
    config: {
      oscillator: { type: 'triangle' },
      modulationIndex: 10,
      harmonicity: 0.5,
      envelope: { attack: 0.005, decay: 0.25, sustain: 0.5, release: 0.1 },
      modulationEnvelope: { attack: 0.001, decay: 0.2, sustain: 0.3, release: 0.1 },
    },
  },
  {
    id: 'fm-ethereal-pad',
    name: 'Ethereal Pad',
    description: 'Slow evolving FM pad',
    category: 'pad',
    config: {
      oscillator: { type: 'sine' },
      modulationIndex: 4,
      harmonicity: 3,
      envelope: { attack: 0.8, decay: 1.5, sustain: 0.6, release: 2.0 },
      modulationEnvelope: { attack: 1.0, decay: 2.0, sustain: 0.4, release: 1.5 },
    },
  },
];
