import type { SynthPreset } from './types';
import type { FormantSynthConfig } from '../../types/instrument';

export const FORMANT_SYNTH_PRESETS: SynthPreset[] = [
  {
    id: 'formant-a',
    name: 'Vowel A',
    description: '"Ahhh" sound',
    category: 'pad',
    config: {
      vowel: 'A',
      vowelMorph: { target: 'A', amount: 0, rate: 1, mode: 'manual' },
      oscillator: { type: 'sawtooth' },
      formants: { f1: 800, f2: 1200, f3: 2500, bandwidth: 100 },
      envelope: { attack: 100, decay: 800, sustain: 0, release: 300 },
      brightness: 70,
    } as Partial<FormantSynthConfig>,
  },
  {
    id: 'formant-e',
    name: 'Vowel E',
    description: '"Ehh" sound',
    category: 'pad',
    config: {
      vowel: 'E',
      vowelMorph: { target: 'E', amount: 0, rate: 1, mode: 'manual' },
      oscillator: { type: 'sawtooth' },
      formants: { f1: 400, f2: 2000, f3: 2600, bandwidth: 100 },
      envelope: { attack: 100, decay: 800, sustain: 0, release: 300 },
      brightness: 70,
    } as Partial<FormantSynthConfig>,
  },
  {
    id: 'formant-i',
    name: 'Vowel I',
    description: '"Eee" sound',
    category: 'lead',
    config: {
      vowel: 'I',
      vowelMorph: { target: 'I', amount: 0, rate: 1, mode: 'manual' },
      oscillator: { type: 'sawtooth' },
      formants: { f1: 300, f2: 2300, f3: 3000, bandwidth: 100 },
      envelope: { attack: 50, decay: 600, sustain: 0, release: 200 },
      brightness: 80,
    } as Partial<FormantSynthConfig>,
  },
  {
    id: 'formant-o',
    name: 'Vowel O',
    description: '"Ohh" sound',
    category: 'pad',
    config: {
      vowel: 'O',
      vowelMorph: { target: 'O', amount: 0, rate: 1, mode: 'manual' },
      oscillator: { type: 'sawtooth' },
      formants: { f1: 500, f2: 800, f3: 2500, bandwidth: 100 },
      envelope: { attack: 150, decay: 900, sustain: 0, release: 400 },
      brightness: 60,
    } as Partial<FormantSynthConfig>,
  },
  {
    id: 'formant-u',
    name: 'Vowel U',
    description: '"Ooo" sound',
    category: 'pad',
    config: {
      vowel: 'U',
      vowelMorph: { target: 'U', amount: 0, rate: 1, mode: 'manual' },
      oscillator: { type: 'sawtooth' },
      formants: { f1: 350, f2: 600, f3: 2400, bandwidth: 100 },
      envelope: { attack: 200, decay: 1000, sustain: 0, release: 500 },
      brightness: 50,
    } as Partial<FormantSynthConfig>,
  },
  {
    id: 'formant-ae',
    name: 'A to E Morph',
    description: 'Morphing between vowels',
    category: 'pad',
    config: {
      vowel: 'A',
      vowelMorph: { target: 'E', amount: 50, rate: 1, mode: 'lfo' },
      oscillator: { type: 'sawtooth' },
      envelope: { attack: 200, decay: 1000, sustain: 50, release: 500 },
      brightness: 70,
    } as Partial<FormantSynthConfig>,
  },
  {
    id: 'formant-choir',
    name: 'Choir',
    description: 'Evolving choir pad',
    category: 'pad',
    config: {
      vowel: 'A',
      vowelMorph: { target: 'O', amount: 60, rate: 0.5, mode: 'lfo' },
      oscillator: { type: 'sawtooth' },
      envelope: { attack: 400, decay: 1500, sustain: 60, release: 800 },
      brightness: 65,
    } as Partial<FormantSynthConfig>,
  },
  {
    id: 'formant-robot',
    name: 'Robot',
    description: 'Robotic voice',
    category: 'fx',
    config: {
      vowel: 'E',
      vowelMorph: { target: 'I', amount: 40, rate: 8, mode: 'lfo' },
      oscillator: { type: 'square' },
      envelope: { attack: 5, decay: 400, sustain: 0, release: 100 },
      brightness: 90,
    } as Partial<FormantSynthConfig>,
  },
  {
    id: 'formant-talk',
    name: 'Talking',
    description: 'Speech-like sound',
    category: 'lead',
    config: {
      vowel: 'A',
      vowelMorph: { target: 'I', amount: 70, rate: 2, mode: 'envelope' },
      oscillator: { type: 'sawtooth' },
      envelope: { attack: 50, decay: 500, sustain: 0, release: 200 },
      brightness: 75,
    } as Partial<FormantSynthConfig>,
  },
  {
    id: 'formant-whisper',
    name: 'Whisper',
    description: 'Breathy whisper',
    category: 'pad',
    config: {
      vowel: 'O',
      vowelMorph: { target: 'U', amount: 30, rate: 0.3, mode: 'lfo' },
      oscillator: { type: 'sawtooth' },
      formants: { f1: 500, f2: 800, f3: 2500, bandwidth: 200 },
      envelope: { attack: 300, decay: 1200, sustain: 40, release: 600 },
      brightness: 40,
    } as Partial<FormantSynthConfig>,
  },
  {
    id: 'formant-square',
    name: 'Square Vocal',
    description: 'Square wave formant',
    category: 'lead',
    config: {
      vowel: 'A',
      vowelMorph: { target: 'E', amount: 0, rate: 1, mode: 'manual' },
      oscillator: { type: 'square' },
      envelope: { attack: 20, decay: 500, sustain: 0, release: 150 },
      brightness: 80,
    } as Partial<FormantSynthConfig>,
  },
  {
    id: 'formant-bass',
    name: 'Vocal Bass',
    description: 'Deep vocal bass',
    category: 'bass',
    config: {
      vowel: 'O',
      vowelMorph: { target: 'U', amount: 20, rate: 0.5, mode: 'lfo' },
      oscillator: { type: 'sawtooth' },
      formants: { f1: 400, f2: 700, f3: 2000, bandwidth: 80 },
      envelope: { attack: 10, decay: 400, sustain: 0, release: 100 },
      brightness: 40,
    } as Partial<FormantSynthConfig>,
  },
  {
    id: 'formant-lead',
    name: 'Vocal Lead',
    description: 'Singing lead sound',
    category: 'lead',
    config: {
      vowel: 'I',
      vowelMorph: { target: 'A', amount: 30, rate: 3, mode: 'envelope' },
      oscillator: { type: 'sawtooth' },
      envelope: { attack: 30, decay: 600, sustain: 0, release: 200 },
      brightness: 85,
    } as Partial<FormantSynthConfig>,
  },
  {
    id: 'formant-alien',
    name: 'Alien',
    description: 'Strange alien voice',
    category: 'fx',
    config: {
      vowel: 'E',
      vowelMorph: { target: 'U', amount: 80, rate: 5, mode: 'lfo' },
      oscillator: { type: 'triangle' },
      formants: { f1: 250, f2: 3000, f3: 4000, bandwidth: 50 },
      envelope: { attack: 100, decay: 800, sustain: 30, release: 400 },
      brightness: 60,
    } as Partial<FormantSynthConfig>,
  },
  {
    id: 'formant-angel',
    name: 'Angelic',
    description: 'Heavenly choir',
    category: 'pad',
    config: {
      vowel: 'A',
      vowelMorph: { target: 'O', amount: 40, rate: 0.2, mode: 'lfo' },
      oscillator: { type: 'sawtooth' },
      envelope: { attack: 600, decay: 2000, sustain: 50, release: 1000 },
      brightness: 55,
    } as Partial<FormantSynthConfig>,
  },
  {
    id: 'formant-opera',
    name: 'Opera',
    description: 'Operatic voice',
    category: 'pad',
    config: {
      vowel: 'A',
      vowelMorph: { target: 'O', amount: 50, rate: 1.5, mode: 'lfo' },
      oscillator: { type: 'sawtooth' },
      formants: { f1: 900, f2: 1300, f3: 2700, bandwidth: 120 },
      envelope: { attack: 300, decay: 1200, sustain: 60, release: 700 },
      brightness: 75,
    } as Partial<FormantSynthConfig>,
  },
  {
    id: 'formant-wide',
    name: 'Wide Vowel',
    description: 'Wide bandwidth formant',
    category: 'pad',
    config: {
      vowel: 'A',
      vowelMorph: { target: 'E', amount: 0, rate: 1, mode: 'manual' },
      oscillator: { type: 'sawtooth' },
      formants: { f1: 800, f2: 1200, f3: 2500, bandwidth: 200 },
      envelope: { attack: 150, decay: 800, sustain: 0, release: 400 },
      brightness: 60,
    } as Partial<FormantSynthConfig>,
  },
  {
    id: 'formant-narrow',
    name: 'Narrow Vowel',
    description: 'Tight resonant formant',
    category: 'lead',
    config: {
      vowel: 'I',
      vowelMorph: { target: 'E', amount: 0, rate: 1, mode: 'manual' },
      oscillator: { type: 'sawtooth' },
      formants: { f1: 300, f2: 2300, f3: 3000, bandwidth: 50 },
      envelope: { attack: 20, decay: 500, sustain: 0, release: 150 },
      brightness: 90,
    } as Partial<FormantSynthConfig>,
  },
  {
    id: 'formant-sweep',
    name: 'Vowel Sweep',
    description: 'Full vowel sweep',
    category: 'fx',
    config: {
      vowel: 'A',
      vowelMorph: { target: 'U', amount: 100, rate: 0.1, mode: 'lfo' },
      oscillator: { type: 'sawtooth' },
      envelope: { attack: 200, decay: 2000, sustain: 70, release: 800 },
      brightness: 65,
    } as Partial<FormantSynthConfig>,
  },
  {
    id: 'formant-pluck',
    name: 'Vocal Pluck',
    description: 'Short vocal pluck',
    category: 'pluck',
    config: {
      vowel: 'E',
      vowelMorph: { target: 'A', amount: 60, rate: 1, mode: 'envelope' },
      oscillator: { type: 'sawtooth' },
      envelope: { attack: 5, decay: 150, sustain: 0, release: 50 },
      brightness: 80,
    } as Partial<FormantSynthConfig>,
  },
];

// ============================================
// DUB SIREN PRESETS
// ============================================

