import type { SynthPreset } from './types';
import type { PolySynthConfig } from '../../types/instrument';

export const POLYSYNTH_PRESETS: SynthPreset[] = [
  {
    id: 'poly-warm',
    name: 'Warm Poly',
    description: 'Classic warm poly sound',
    category: 'pad',
    config: {
      voiceCount: 8,
      voiceType: 'Synth',
      stealMode: 'oldest',
      oscillator: { type: 'sawtooth', detune: 5, octave: 0 },
      envelope: { attack: 100, decay: 800, sustain: 0, release: 400 },
      portamento: 0,
    } as Partial<PolySynthConfig>,
  },
  {
    id: 'poly-brass',
    name: 'Poly Brass',
    description: 'Brass-like poly',
    category: 'pad',
    config: {
      voiceCount: 6,
      voiceType: 'Synth',
      stealMode: 'oldest',
      oscillator: { type: 'sawtooth', detune: 10, octave: 0 },
      envelope: { attack: 50, decay: 600, sustain: 0, release: 300 },
      portamento: 0,
    } as Partial<PolySynthConfig>,
  },
  {
    id: 'poly-strings',
    name: 'Poly Strings',
    description: 'String ensemble',
    category: 'string',
    config: {
      voiceCount: 8,
      voiceType: 'Synth',
      stealMode: 'oldest',
      oscillator: { type: 'sawtooth', detune: 15, octave: 0 },
      envelope: { attack: 300, decay: 1500, sustain: 70, release: 800 },
      portamento: 0,
    } as Partial<PolySynthConfig>,
  },
  {
    id: 'poly-organ',
    name: 'Poly Organ',
    description: 'Organ-like poly',
    category: 'key',
    config: {
      voiceCount: 8,
      voiceType: 'Synth',
      stealMode: 'oldest',
      oscillator: { type: 'square', detune: 0, octave: 0 },
      envelope: { attack: 5, decay: 100, sustain: 100, release: 100 },
      portamento: 0,
    } as Partial<PolySynthConfig>,
  },
  {
    id: 'poly-fm-bell',
    name: 'FM Bell',
    description: 'Bell-like FM poly',
    category: 'key',
    config: {
      voiceCount: 8,
      voiceType: 'FMSynth',
      stealMode: 'oldest',
      oscillator: { type: 'sine', detune: 0, octave: 0 },
      envelope: { attack: 5, decay: 1500, sustain: 0, release: 500 },
      portamento: 0,
    } as Partial<PolySynthConfig>,
  },
  {
    id: 'poly-fm-ep',
    name: 'FM E.Piano',
    description: 'FM electric piano',
    category: 'key',
    config: {
      voiceCount: 8,
      voiceType: 'FMSynth',
      stealMode: 'oldest',
      oscillator: { type: 'sine', detune: 0, octave: 0 },
      envelope: { attack: 10, decay: 800, sustain: 0, release: 300 },
      portamento: 0,
    } as Partial<PolySynthConfig>,
  },
  {
    id: 'poly-am',
    name: 'AM Poly',
    description: 'Amplitude modulation poly',
    category: 'lead',
    config: {
      voiceCount: 6,
      voiceType: 'ToneAM',
      stealMode: 'oldest',
      oscillator: { type: 'sawtooth', detune: 5, octave: 0 },
      envelope: { attack: 20, decay: 600, sustain: 0, release: 200 },
      portamento: 0,
    } as Partial<PolySynthConfig>,
  },
  {
    id: 'poly-pluck',
    name: 'Poly Pluck',
    description: 'Short plucky poly',
    category: 'pluck',
    config: {
      voiceCount: 8,
      voiceType: 'Synth',
      stealMode: 'oldest',
      oscillator: { type: 'triangle', detune: 0, octave: 0 },
      envelope: { attack: 3, decay: 200, sustain: 0, release: 80 },
      portamento: 0,
    } as Partial<PolySynthConfig>,
  },
  {
    id: 'poly-glide',
    name: 'Glide Poly',
    description: 'Portamento poly',
    category: 'lead',
    config: {
      voiceCount: 4,
      voiceType: 'Synth',
      stealMode: 'lowest',
      oscillator: { type: 'sawtooth', detune: 8, octave: 0 },
      envelope: { attack: 50, decay: 700, sustain: 0, release: 300 },
      portamento: 100,
    } as Partial<PolySynthConfig>,
  },
  {
    id: 'poly-square',
    name: 'Square Poly',
    description: 'Hollow square wave poly',
    category: 'pad',
    config: {
      voiceCount: 8,
      voiceType: 'Synth',
      stealMode: 'oldest',
      oscillator: { type: 'square', detune: 7, octave: 0 },
      envelope: { attack: 80, decay: 900, sustain: 0, release: 400 },
      portamento: 0,
    } as Partial<PolySynthConfig>,
  },
  {
    id: 'poly-sine',
    name: 'Pure Sine',
    description: 'Clean sine wave poly',
    category: 'pad',
    config: {
      voiceCount: 8,
      voiceType: 'Synth',
      stealMode: 'oldest',
      oscillator: { type: 'sine', detune: 0, octave: 0 },
      envelope: { attack: 100, decay: 1000, sustain: 50, release: 500 },
      portamento: 0,
    } as Partial<PolySynthConfig>,
  },
  {
    id: 'poly-tri',
    name: 'Triangle Poly',
    description: 'Soft triangle wave',
    category: 'pad',
    config: {
      voiceCount: 8,
      voiceType: 'Synth',
      stealMode: 'oldest',
      oscillator: { type: 'triangle', detune: 5, octave: 0 },
      envelope: { attack: 150, decay: 1000, sustain: 40, release: 600 },
      portamento: 0,
    } as Partial<PolySynthConfig>,
  },
  {
    id: 'poly-thick',
    name: 'Thick Poly',
    description: 'Heavy detuned poly',
    category: 'pad',
    config: {
      voiceCount: 4,
      voiceType: 'Synth',
      stealMode: 'oldest',
      oscillator: { type: 'sawtooth', detune: 30, octave: 0 },
      envelope: { attack: 80, decay: 700, sustain: 0, release: 350 },
      portamento: 0,
    } as Partial<PolySynthConfig>,
  },
  {
    id: 'poly-thin',
    name: 'Thin Poly',
    description: 'Light clean poly',
    category: 'lead',
    config: {
      voiceCount: 8,
      voiceType: 'Synth',
      stealMode: 'oldest',
      oscillator: { type: 'triangle', detune: 0, octave: 1 },
      envelope: { attack: 10, decay: 400, sustain: 0, release: 150 },
      portamento: 0,
    } as Partial<PolySynthConfig>,
  },
  {
    id: 'poly-sub',
    name: 'Sub Poly',
    description: 'Deep sub bass poly',
    category: 'bass',
    config: {
      voiceCount: 4,
      voiceType: 'Synth',
      stealMode: 'oldest',
      oscillator: { type: 'sine', detune: 0, octave: -1 },
      envelope: { attack: 20, decay: 600, sustain: 0, release: 200 },
      portamento: 0,
    } as Partial<PolySynthConfig>,
  },
  {
    id: 'poly-bright',
    name: 'Bright Poly',
    description: 'Bright cutting poly',
    category: 'lead',
    config: {
      voiceCount: 6,
      voiceType: 'Synth',
      stealMode: 'oldest',
      oscillator: { type: 'sawtooth', detune: 5, octave: 1 },
      envelope: { attack: 10, decay: 500, sustain: 0, release: 200 },
      portamento: 0,
    } as Partial<PolySynthConfig>,
  },
  {
    id: 'poly-dark',
    name: 'Dark Poly',
    description: 'Muffled dark poly',
    category: 'pad',
    config: {
      voiceCount: 8,
      voiceType: 'Synth',
      stealMode: 'oldest',
      oscillator: { type: 'sawtooth', detune: 10, octave: -1 },
      envelope: { attack: 200, decay: 1200, sustain: 40, release: 600 },
      portamento: 0,
    } as Partial<PolySynthConfig>,
  },
  {
    id: 'poly-stab',
    name: 'Stab',
    description: 'Short chord stab',
    category: 'key',
    config: {
      voiceCount: 8,
      voiceType: 'Synth',
      stealMode: 'oldest',
      oscillator: { type: 'sawtooth', detune: 12, octave: 0 },
      envelope: { attack: 5, decay: 150, sustain: 0, release: 50 },
      portamento: 0,
    } as Partial<PolySynthConfig>,
  },
  {
    id: 'poly-swirl',
    name: 'Swirl',
    description: 'Evolving detune pad',
    category: 'pad',
    config: {
      voiceCount: 6,
      voiceType: 'Synth',
      stealMode: 'oldest',
      oscillator: { type: 'sawtooth', detune: 25, octave: 0 },
      envelope: { attack: 500, decay: 2000, sustain: 60, release: 1000 },
      portamento: 50,
    } as Partial<PolySynthConfig>,
  },
  {
    id: 'poly-vintage',
    name: 'Vintage',
    description: 'Classic polysynth',
    category: 'pad',
    config: {
      voiceCount: 6,
      voiceType: 'Synth',
      stealMode: 'oldest',
      oscillator: { type: 'sawtooth', detune: 8, octave: 0 },
      envelope: { attack: 60, decay: 600, sustain: 30, release: 300 },
      portamento: 0,
    } as Partial<PolySynthConfig>,
  },
];

// ============================================
// Get presets by synth type
// ============================================

