import type { SynthPreset } from './types';
import type { PWMSynthConfig } from '../../types/instrument';

export const PWM_SYNTH_PRESETS: SynthPreset[] = [
  {
    id: 'pwm-classic',
    name: 'Classic PWM',
    description: 'Warm analog-style PWM',
    category: 'pad',
    config: {
      pulseWidth: 50,
      pwmDepth: 40,
      pwmRate: 1.5,
      pwmWaveform: 'sine',
      oscillators: 2,
      detune: 8,
      envelope: { attack: 100, decay: 800, sustain: 0, release: 300 },
      filter: { type: 'lowpass', cutoff: 5000, resonance: 20, envelopeAmount: 30, keyTracking: 50 },
    } as Partial<PWMSynthConfig>,
  },
  {
    id: 'pwm-strings',
    name: 'PWM Strings',
    description: 'String ensemble emulation',
    category: 'string',
    config: {
      pulseWidth: 50,
      pwmDepth: 50,
      pwmRate: 3,
      pwmWaveform: 'triangle',
      oscillators: 3,
      detune: 15,
      envelope: { attack: 200, decay: 1000, sustain: 70, release: 500 },
      filter: { type: 'lowpass', cutoff: 6000, resonance: 10, envelopeAmount: 20, keyTracking: 60 },
    } as Partial<PWMSynthConfig>,
  },
  {
    id: 'pwm-bass',
    name: 'PWM Bass',
    description: 'Fat PWM bass',
    category: 'bass',
    config: {
      pulseWidth: 40,
      pwmDepth: 20,
      pwmRate: 2,
      pwmWaveform: 'sine',
      oscillators: 2,
      detune: 5,
      envelope: { attack: 5, decay: 400, sustain: 0, release: 100 },
      filter: { type: 'lowpass', cutoff: 2000, resonance: 40, envelopeAmount: 50, keyTracking: 30 },
    } as Partial<PWMSynthConfig>,
  },
  {
    id: 'pwm-lead',
    name: 'PWM Lead',
    description: 'Cutting PWM lead',
    category: 'lead',
    config: {
      pulseWidth: 30,
      pwmDepth: 30,
      pwmRate: 4,
      pwmWaveform: 'sawtooth',
      oscillators: 2,
      detune: 10,
      envelope: { attack: 10, decay: 500, sustain: 0, release: 150 },
      filter: { type: 'lowpass', cutoff: 8000, resonance: 25, envelopeAmount: 40, keyTracking: 70 },
    } as Partial<PWMSynthConfig>,
  },
  {
    id: 'pwm-pad',
    name: 'Lush Pad',
    description: 'Evolving pad sound',
    category: 'pad',
    config: {
      pulseWidth: 50,
      pwmDepth: 60,
      pwmRate: 0.5,
      pwmWaveform: 'sine',
      oscillators: 3,
      detune: 20,
      envelope: { attack: 500, decay: 2000, sustain: 60, release: 1000 },
      filter: { type: 'lowpass', cutoff: 4000, resonance: 15, envelopeAmount: -20, keyTracking: 40 },
    } as Partial<PWMSynthConfig>,
  },
  {
    id: 'pwm-pluck',
    name: 'PWM Pluck',
    description: 'Short plucky sound',
    category: 'pluck',
    config: {
      pulseWidth: 25,
      pwmDepth: 10,
      pwmRate: 8,
      pwmWaveform: 'sine',
      oscillators: 1,
      detune: 0,
      envelope: { attack: 2, decay: 150, sustain: 0, release: 50 },
      filter: { type: 'lowpass', cutoff: 6000, resonance: 30, envelopeAmount: 60, keyTracking: 80 },
    } as Partial<PWMSynthConfig>,
  },
  {
    id: 'pwm-hollow',
    name: 'Hollow',
    description: 'Thin hollow sound',
    category: 'lead',
    config: {
      pulseWidth: 10,
      pwmDepth: 80,
      pwmRate: 2,
      pwmWaveform: 'triangle',
      oscillators: 2,
      detune: 12,
      envelope: { attack: 50, decay: 600, sustain: 0, release: 200 },
      filter: { type: 'bandpass', cutoff: 3000, resonance: 40, envelopeAmount: 30, keyTracking: 60 },
    } as Partial<PWMSynthConfig>,
  },
  {
    id: 'pwm-wide',
    name: 'Wide PWM',
    description: 'Stereo detuned PWM',
    category: 'pad',
    config: {
      pulseWidth: 50,
      pwmDepth: 45,
      pwmRate: 1,
      pwmWaveform: 'sine',
      oscillators: 3,
      detune: 30,
      envelope: { attack: 150, decay: 1000, sustain: 50, release: 400 },
      filter: { type: 'lowpass', cutoff: 5500, resonance: 18, envelopeAmount: 25, keyTracking: 50 },
    } as Partial<PWMSynthConfig>,
  },
  {
    id: 'pwm-slow',
    name: 'Slow Mod',
    description: 'Very slow PWM movement',
    category: 'pad',
    config: {
      pulseWidth: 50,
      pwmDepth: 70,
      pwmRate: 0.2,
      pwmWaveform: 'sine',
      oscillators: 2,
      detune: 10,
      envelope: { attack: 300, decay: 1500, sustain: 40, release: 600 },
      filter: { type: 'lowpass', cutoff: 4500, resonance: 12, envelopeAmount: -15, keyTracking: 45 },
    } as Partial<PWMSynthConfig>,
  },
  {
    id: 'pwm-fast',
    name: 'Fast Mod',
    description: 'Rapid PWM modulation',
    category: 'lead',
    config: {
      pulseWidth: 50,
      pwmDepth: 50,
      pwmRate: 10,
      pwmWaveform: 'sine',
      oscillators: 1,
      detune: 0,
      envelope: { attack: 10, decay: 400, sustain: 0, release: 100 },
      filter: { type: 'lowpass', cutoff: 7000, resonance: 20, envelopeAmount: 35, keyTracking: 60 },
    } as Partial<PWMSynthConfig>,
  },
  {
    id: 'pwm-bright',
    name: 'Bright PWM',
    description: 'Unfiltered bright tone',
    category: 'lead',
    config: {
      pulseWidth: 25,
      pwmDepth: 35,
      pwmRate: 3,
      pwmWaveform: 'triangle',
      oscillators: 2,
      detune: 8,
      envelope: { attack: 5, decay: 500, sustain: 0, release: 120 },
      filter: { type: 'lowpass', cutoff: 15000, resonance: 5, envelopeAmount: 0, keyTracking: 50 },
    } as Partial<PWMSynthConfig>,
  },
  {
    id: 'pwm-dark',
    name: 'Dark PWM',
    description: 'Muffled dark tone',
    category: 'bass',
    config: {
      pulseWidth: 60,
      pwmDepth: 25,
      pwmRate: 1,
      pwmWaveform: 'sine',
      oscillators: 2,
      detune: 6,
      envelope: { attack: 20, decay: 600, sustain: 0, release: 150 },
      filter: { type: 'lowpass', cutoff: 1500, resonance: 35, envelopeAmount: 40, keyTracking: 20 },
    } as Partial<PWMSynthConfig>,
  },
  {
    id: 'pwm-resonant',
    name: 'Resonant PWM',
    description: 'High resonance sweep',
    category: 'lead',
    config: {
      pulseWidth: 40,
      pwmDepth: 40,
      pwmRate: 2,
      pwmWaveform: 'sine',
      oscillators: 2,
      detune: 10,
      envelope: { attack: 10, decay: 450, sustain: 0, release: 120 },
      filter: { type: 'lowpass', cutoff: 3000, resonance: 70, envelopeAmount: 60, keyTracking: 70 },
    } as Partial<PWMSynthConfig>,
  },
  {
    id: 'pwm-sync',
    name: 'Sync-ish',
    description: 'Hard sync-like character',
    category: 'lead',
    config: {
      pulseWidth: 20,
      pwmDepth: 60,
      pwmRate: 6,
      pwmWaveform: 'sawtooth',
      oscillators: 2,
      detune: 25,
      envelope: { attack: 5, decay: 350, sustain: 0, release: 80 },
      filter: { type: 'lowpass', cutoff: 4500, resonance: 45, envelopeAmount: 55, keyTracking: 65 },
    } as Partial<PWMSynthConfig>,
  },
  {
    id: 'pwm-choir',
    name: 'Choir',
    description: 'Voice-like pad',
    category: 'pad',
    config: {
      pulseWidth: 50,
      pwmDepth: 55,
      pwmRate: 1.2,
      pwmWaveform: 'sine',
      oscillators: 3,
      detune: 18,
      envelope: { attack: 400, decay: 1500, sustain: 55, release: 700 },
      filter: { type: 'bandpass', cutoff: 2000, resonance: 25, envelopeAmount: 15, keyTracking: 55 },
    } as Partial<PWMSynthConfig>,
  },
  {
    id: 'pwm-vintage',
    name: 'Vintage',
    description: 'Prophet-5 style',
    category: 'pad',
    config: {
      pulseWidth: 45,
      pwmDepth: 35,
      pwmRate: 2.5,
      pwmWaveform: 'triangle',
      oscillators: 2,
      detune: 7,
      envelope: { attack: 80, decay: 700, sustain: 30, release: 300 },
      filter: { type: 'lowpass', cutoff: 4800, resonance: 22, envelopeAmount: 35, keyTracking: 55 },
    } as Partial<PWMSynthConfig>,
  },
  {
    id: 'pwm-mono',
    name: 'Mono PWM',
    description: 'Single osc mono',
    category: 'lead',
    config: {
      pulseWidth: 50,
      pwmDepth: 40,
      pwmRate: 3,
      pwmWaveform: 'sine',
      oscillators: 1,
      detune: 0,
      envelope: { attack: 5, decay: 400, sustain: 0, release: 100 },
      filter: { type: 'lowpass', cutoff: 6000, resonance: 30, envelopeAmount: 45, keyTracking: 60 },
    } as Partial<PWMSynthConfig>,
  },
  {
    id: 'pwm-thick',
    name: 'Thick',
    description: 'Three oscillator thick',
    category: 'bass',
    config: {
      pulseWidth: 50,
      pwmDepth: 30,
      pwmRate: 1.8,
      pwmWaveform: 'sine',
      oscillators: 3,
      detune: 12,
      envelope: { attack: 10, decay: 500, sustain: 0, release: 120 },
      filter: { type: 'lowpass', cutoff: 2500, resonance: 35, envelopeAmount: 45, keyTracking: 40 },
    } as Partial<PWMSynthConfig>,
  },
  {
    id: 'pwm-ethereal',
    name: 'Ethereal',
    description: 'Dreamy slow pad',
    category: 'pad',
    config: {
      pulseWidth: 50,
      pwmDepth: 65,
      pwmRate: 0.3,
      pwmWaveform: 'sine',
      oscillators: 3,
      detune: 25,
      envelope: { attack: 800, decay: 3000, sustain: 50, release: 1500 },
      filter: { type: 'lowpass', cutoff: 3500, resonance: 10, envelopeAmount: -25, keyTracking: 35 },
    } as Partial<PWMSynthConfig>,
  },
  {
    id: 'pwm-key',
    name: 'PWM Keys',
    description: 'Electric piano-ish',
    category: 'key',
    config: {
      pulseWidth: 35,
      pwmDepth: 15,
      pwmRate: 5,
      pwmWaveform: 'sine',
      oscillators: 2,
      detune: 5,
      envelope: { attack: 5, decay: 300, sustain: 20, release: 200 },
      filter: { type: 'lowpass', cutoff: 5000, resonance: 20, envelopeAmount: 50, keyTracking: 80 },
    } as Partial<PWMSynthConfig>,
  },
];

// ============================================
// STRING MACHINE PRESETS
// ============================================

