import type { SynthPreset } from './types';
import type { StringMachineConfig } from '../../types/instrument';

export const STRING_MACHINE_PRESETS: SynthPreset[] = [
  {
    id: 'string-full',
    name: 'Full Orchestra',
    description: 'All sections balanced',
    category: 'string',
    config: {
      sections: { violin: 100, viola: 80, cello: 70, bass: 60 },
      ensemble: { depth: 60, rate: 3, voices: 4 },
      attack: 200,
      release: 1000,
      brightness: 60,
    } as Partial<StringMachineConfig>,
  },
  {
    id: 'string-violin',
    name: 'Violin Solo',
    description: 'High strings only',
    category: 'string',
    config: {
      sections: { violin: 100, viola: 30, cello: 0, bass: 0 },
      ensemble: { depth: 40, rate: 4, voices: 3 },
      attack: 100,
      release: 800,
      brightness: 80,
    } as Partial<StringMachineConfig>,
  },
  {
    id: 'string-cello',
    name: 'Cello Section',
    description: 'Rich cello tone',
    category: 'string',
    config: {
      sections: { violin: 0, viola: 40, cello: 100, bass: 50 },
      ensemble: { depth: 50, rate: 2.5, voices: 4 },
      attack: 250,
      release: 1200,
      brightness: 50,
    } as Partial<StringMachineConfig>,
  },
  {
    id: 'string-bass',
    name: 'Bass Section',
    description: 'Deep string bass',
    category: 'bass',
    config: {
      sections: { violin: 0, viola: 0, cello: 30, bass: 100 },
      ensemble: { depth: 30, rate: 2, voices: 3 },
      attack: 300,
      release: 1500,
      brightness: 30,
    } as Partial<StringMachineConfig>,
  },
  {
    id: 'string-chamber',
    name: 'Chamber Strings',
    description: 'Small ensemble',
    category: 'string',
    config: {
      sections: { violin: 80, viola: 70, cello: 60, bass: 40 },
      ensemble: { depth: 35, rate: 3.5, voices: 2 },
      attack: 150,
      release: 900,
      brightness: 65,
    } as Partial<StringMachineConfig>,
  },
  {
    id: 'string-solina',
    name: 'Solina Strings',
    description: 'Classic ensemble machine',
    category: 'string',
    config: {
      sections: { violin: 100, viola: 80, cello: 60, bass: 40 },
      ensemble: { depth: 70, rate: 6, voices: 6 },
      attack: 80,
      release: 600,
      brightness: 70,
    } as Partial<StringMachineConfig>,
  },
  {
    id: 'string-warm',
    name: 'Warm Strings',
    description: 'Dark warm pad',
    category: 'pad',
    config: {
      sections: { violin: 60, viola: 80, cello: 100, bass: 80 },
      ensemble: { depth: 50, rate: 2, voices: 4 },
      attack: 400,
      release: 1500,
      brightness: 35,
    } as Partial<StringMachineConfig>,
  },
  {
    id: 'string-bright',
    name: 'Bright Strings',
    description: 'Cutting bright strings',
    category: 'string',
    config: {
      sections: { violin: 100, viola: 70, cello: 50, bass: 30 },
      ensemble: { depth: 55, rate: 4, voices: 4 },
      attack: 100,
      release: 700,
      brightness: 90,
    } as Partial<StringMachineConfig>,
  },
  {
    id: 'string-slow',
    name: 'Slow Strings',
    description: 'Gentle slow attack',
    category: 'pad',
    config: {
      sections: { violin: 90, viola: 80, cello: 70, bass: 60 },
      ensemble: { depth: 45, rate: 2, voices: 4 },
      attack: 800,
      release: 2000,
      brightness: 50,
    } as Partial<StringMachineConfig>,
  },
  {
    id: 'string-fast',
    name: 'Fast Strings',
    description: 'Quick attack strings',
    category: 'string',
    config: {
      sections: { violin: 100, viola: 80, cello: 60, bass: 40 },
      ensemble: { depth: 50, rate: 5, voices: 4 },
      attack: 30,
      release: 400,
      brightness: 70,
    } as Partial<StringMachineConfig>,
  },
  {
    id: 'string-lush',
    name: 'Lush Ensemble',
    description: 'Maximum chorus depth',
    category: 'pad',
    config: {
      sections: { violin: 100, viola: 100, cello: 100, bass: 100 },
      ensemble: { depth: 100, rate: 3, voices: 6 },
      attack: 300,
      release: 1200,
      brightness: 55,
    } as Partial<StringMachineConfig>,
  },
  {
    id: 'string-dry',
    name: 'Dry Strings',
    description: 'Minimal chorus',
    category: 'string',
    config: {
      sections: { violin: 100, viola: 80, cello: 70, bass: 50 },
      ensemble: { depth: 15, rate: 3, voices: 2 },
      attack: 150,
      release: 800,
      brightness: 60,
    } as Partial<StringMachineConfig>,
  },
  {
    id: 'string-80s',
    name: '80s Strings',
    description: 'Retro synth strings',
    category: 'string',
    config: {
      sections: { violin: 100, viola: 60, cello: 40, bass: 20 },
      ensemble: { depth: 80, rate: 5.5, voices: 6 },
      attack: 50,
      release: 500,
      brightness: 75,
    } as Partial<StringMachineConfig>,
  },
  {
    id: 'string-movie',
    name: 'Movie Score',
    description: 'Cinematic strings',
    category: 'string',
    config: {
      sections: { violin: 80, viola: 90, cello: 100, bass: 70 },
      ensemble: { depth: 40, rate: 2.5, voices: 4 },
      attack: 350,
      release: 1400,
      brightness: 55,
    } as Partial<StringMachineConfig>,
  },
  {
    id: 'string-pizz',
    name: 'Pizzicato',
    description: 'Short plucked strings',
    category: 'pluck',
    config: {
      sections: { violin: 100, viola: 80, cello: 60, bass: 40 },
      ensemble: { depth: 20, rate: 3, voices: 2 },
      attack: 5,
      release: 200,
      brightness: 80,
    } as Partial<StringMachineConfig>,
  },
  {
    id: 'string-tremolo',
    name: 'Tremolo',
    description: 'Fast tremolo strings',
    category: 'string',
    config: {
      sections: { violin: 100, viola: 80, cello: 60, bass: 40 },
      ensemble: { depth: 100, rate: 6, voices: 6 },
      attack: 20,
      release: 300,
      brightness: 70,
    } as Partial<StringMachineConfig>,
  },
  {
    id: 'string-spooky',
    name: 'Spooky',
    description: 'Eerie horror strings',
    category: 'fx',
    config: {
      sections: { violin: 70, viola: 90, cello: 100, bass: 100 },
      ensemble: { depth: 70, rate: 0.5, voices: 4 },
      attack: 600,
      release: 2500,
      brightness: 25,
    } as Partial<StringMachineConfig>,
  },
  {
    id: 'string-epic',
    name: 'Epic',
    description: 'Big dramatic strings',
    category: 'string',
    config: {
      sections: { violin: 100, viola: 100, cello: 100, bass: 100 },
      ensemble: { depth: 60, rate: 3, voices: 4 },
      attack: 200,
      release: 1000,
      brightness: 70,
    } as Partial<StringMachineConfig>,
  },
  {
    id: 'string-gentle',
    name: 'Gentle',
    description: 'Soft delicate strings',
    category: 'pad',
    config: {
      sections: { violin: 60, viola: 70, cello: 50, bass: 30 },
      ensemble: { depth: 35, rate: 2, voices: 3 },
      attack: 500,
      release: 1500,
      brightness: 40,
    } as Partial<StringMachineConfig>,
  },
  {
    id: 'string-synth',
    name: 'Synth Strings',
    description: 'Very synthetic sound',
    category: 'pad',
    config: {
      sections: { violin: 100, viola: 50, cello: 30, bass: 20 },
      ensemble: { depth: 90, rate: 5, voices: 6 },
      attack: 30,
      release: 400,
      brightness: 85,
    } as Partial<StringMachineConfig>,
  },
];

// ============================================
// FORMANT SYNTH PRESETS
// ============================================

