import type { SynthPreset } from './types';
import type { SuperSawConfig } from '../../types/instrument';

export const SUPERSAW_PRESETS: SynthPreset[] = [
  {
    id: 'supersaw-classic',
    name: 'Classic Supersaw',
    description: 'JP-8000 style trance supersaw',
    category: 'lead',
    config: {
      voices: 7,
      detune: 30,
      mix: 50,
      stereoSpread: 80,
      envelope: { attack: 10, decay: 600, sustain: 0, release: 150 },
      filter: { type: 'lowpass', cutoff: 8000, resonance: 20, envelopeAmount: 0 },
    } as Partial<SuperSawConfig>,
  },
  {
    id: 'supersaw-anthem',
    name: 'Anthem Lead',
    description: 'Massive anthem-style lead',
    category: 'lead',
    config: {
      voices: 9,
      detune: 40,
      mix: 60,
      stereoSpread: 100,
      envelope: { attack: 20, decay: 800, sustain: 0, release: 200 },
      filter: { type: 'lowpass', cutoff: 10000, resonance: 15, envelopeAmount: 20 },
    } as Partial<SuperSawConfig>,
  },
  {
    id: 'supersaw-bass',
    name: 'Supersaw Bass',
    description: 'Thick detuned bass',
    category: 'bass',
    config: {
      voices: 5,
      detune: 15,
      mix: 70,
      stereoSpread: 30,
      envelope: { attack: 5, decay: 400, sustain: 0, release: 80 },
      filter: { type: 'lowpass', cutoff: 2000, resonance: 30, envelopeAmount: 40 },
    } as Partial<SuperSawConfig>,
  },
  {
    id: 'supersaw-pad',
    name: 'Supersaw Pad',
    description: 'Lush evolving pad',
    category: 'pad',
    config: {
      voices: 7,
      detune: 25,
      mix: 50,
      stereoSpread: 90,
      envelope: { attack: 500, decay: 2000, sustain: 60, release: 1000 },
      filter: { type: 'lowpass', cutoff: 6000, resonance: 10, envelopeAmount: -30 },
    } as Partial<SuperSawConfig>,
  },
  {
    id: 'supersaw-stab',
    name: 'Stab',
    description: 'Short punchy stab',
    category: 'lead',
    config: {
      voices: 7,
      detune: 35,
      mix: 55,
      stereoSpread: 70,
      envelope: { attack: 5, decay: 200, sustain: 0, release: 50 },
      filter: { type: 'lowpass', cutoff: 12000, resonance: 10, envelopeAmount: 0 },
    } as Partial<SuperSawConfig>,
  },
  {
    id: 'supersaw-minimal',
    name: 'Minimal Saw',
    description: 'Less voices, tighter sound',
    category: 'lead',
    config: {
      voices: 3,
      detune: 10,
      mix: 50,
      stereoSpread: 40,
      envelope: { attack: 10, decay: 400, sustain: 0, release: 100 },
      filter: { type: 'lowpass', cutoff: 5000, resonance: 25, envelopeAmount: 30 },
    } as Partial<SuperSawConfig>,
  },
  {
    id: 'supersaw-wide',
    name: 'Ultra Wide',
    description: 'Maximum stereo spread',
    category: 'lead',
    config: {
      voices: 9,
      detune: 50,
      mix: 45,
      stereoSpread: 100,
      envelope: { attack: 15, decay: 700, sustain: 0, release: 180 },
      filter: { type: 'lowpass', cutoff: 9000, resonance: 15, envelopeAmount: 10 },
    } as Partial<SuperSawConfig>,
  },
  {
    id: 'supersaw-dark',
    name: 'Dark Supersaw',
    description: 'Filtered dark trance',
    category: 'lead',
    config: {
      voices: 7,
      detune: 30,
      mix: 55,
      stereoSpread: 75,
      envelope: { attack: 10, decay: 500, sustain: 0, release: 120 },
      filter: { type: 'lowpass', cutoff: 3500, resonance: 35, envelopeAmount: 50 },
    } as Partial<SuperSawConfig>,
  },
  {
    id: 'supersaw-bright',
    name: 'Bright Saw',
    description: 'Cutting bright lead',
    category: 'lead',
    config: {
      voices: 7,
      detune: 28,
      mix: 50,
      stereoSpread: 80,
      envelope: { attack: 8, decay: 550, sustain: 0, release: 130 },
      filter: { type: 'highpass', cutoff: 200, resonance: 10, envelopeAmount: 0 },
    } as Partial<SuperSawConfig>,
  },
  {
    id: 'supersaw-pluck',
    name: 'Saw Pluck',
    description: 'Short plucky supersaw',
    category: 'pluck',
    config: {
      voices: 5,
      detune: 20,
      mix: 50,
      stereoSpread: 60,
      envelope: { attack: 3, decay: 150, sustain: 0, release: 40 },
      filter: { type: 'lowpass', cutoff: 8000, resonance: 20, envelopeAmount: 60 },
    } as Partial<SuperSawConfig>,
  },
  {
    id: 'supersaw-uplifting',
    name: 'Uplifting',
    description: 'Epic uplifting trance',
    category: 'lead',
    config: {
      voices: 7,
      detune: 32,
      mix: 52,
      stereoSpread: 85,
      envelope: { attack: 12, decay: 650, sustain: 0, release: 160 },
      filter: { type: 'lowpass', cutoff: 7500, resonance: 18, envelopeAmount: 25 },
    } as Partial<SuperSawConfig>,
  },
  {
    id: 'supersaw-progressive',
    name: 'Progressive',
    description: 'Prog house supersaw',
    category: 'lead',
    config: {
      voices: 5,
      detune: 22,
      mix: 60,
      stereoSpread: 65,
      envelope: { attack: 15, decay: 500, sustain: 0, release: 120 },
      filter: { type: 'lowpass', cutoff: 6000, resonance: 22, envelopeAmount: 35 },
    } as Partial<SuperSawConfig>,
  },
  {
    id: 'supersaw-hard',
    name: 'Hardstyle',
    description: 'Hard-hitting hardstyle',
    category: 'lead',
    config: {
      voices: 7,
      detune: 38,
      mix: 50,
      stereoSpread: 75,
      envelope: { attack: 5, decay: 350, sustain: 0, release: 80 },
      filter: { type: 'lowpass', cutoff: 5500, resonance: 30, envelopeAmount: 45 },
    } as Partial<SuperSawConfig>,
  },
  {
    id: 'supersaw-euphoric',
    name: 'Euphoric',
    description: 'Euphoric hardstyle',
    category: 'lead',
    config: {
      voices: 9,
      detune: 35,
      mix: 48,
      stereoSpread: 90,
      envelope: { attack: 10, decay: 600, sustain: 0, release: 150 },
      filter: { type: 'lowpass', cutoff: 8500, resonance: 12, envelopeAmount: 15 },
    } as Partial<SuperSawConfig>,
  },
  {
    id: 'supersaw-layer',
    name: 'Layer Saw',
    description: 'Good for layering',
    category: 'lead',
    config: {
      voices: 5,
      detune: 18,
      mix: 55,
      stereoSpread: 50,
      envelope: { attack: 8, decay: 450, sustain: 0, release: 100 },
      filter: { type: 'bandpass', cutoff: 4000, resonance: 15, envelopeAmount: 0 },
    } as Partial<SuperSawConfig>,
  },
  {
    id: 'supersaw-vocal',
    name: 'Vocal Saw',
    description: 'Voice-like quality',
    category: 'lead',
    config: {
      voices: 7,
      detune: 25,
      mix: 50,
      stereoSpread: 70,
      envelope: { attack: 50, decay: 800, sustain: 0, release: 200 },
      filter: { type: 'bandpass', cutoff: 2500, resonance: 30, envelopeAmount: 20 },
    } as Partial<SuperSawConfig>,
  },
  {
    id: 'supersaw-mono',
    name: 'Mono Lead',
    description: 'Center-focused lead',
    category: 'lead',
    config: {
      voices: 7,
      detune: 30,
      mix: 70,
      stereoSpread: 0,
      envelope: { attack: 5, decay: 500, sustain: 0, release: 100 },
      filter: { type: 'lowpass', cutoff: 7000, resonance: 20, envelopeAmount: 30 },
    } as Partial<SuperSawConfig>,
  },
  {
    id: 'supersaw-acid',
    name: 'Acid Saw',
    description: 'Resonant filter sweep',
    category: 'lead',
    config: {
      voices: 5,
      detune: 20,
      mix: 50,
      stereoSpread: 60,
      envelope: { attack: 5, decay: 400, sustain: 0, release: 80 },
      filter: { type: 'lowpass', cutoff: 2000, resonance: 60, envelopeAmount: 70 },
    } as Partial<SuperSawConfig>,
  },
  {
    id: 'supersaw-dreamy',
    name: 'Dreamy',
    description: 'Ethereal dream trance',
    category: 'pad',
    config: {
      voices: 9,
      detune: 35,
      mix: 45,
      stereoSpread: 95,
      envelope: { attack: 300, decay: 1500, sustain: 40, release: 800 },
      filter: { type: 'lowpass', cutoff: 5000, resonance: 15, envelopeAmount: -20 },
    } as Partial<SuperSawConfig>,
  },
  {
    id: 'supersaw-gritty',
    name: 'Gritty Saw',
    description: 'Aggressive and raw',
    category: 'lead',
    config: {
      voices: 7,
      detune: 45,
      mix: 55,
      stereoSpread: 70,
      envelope: { attack: 3, decay: 350, sustain: 0, release: 60 },
      filter: { type: 'lowpass', cutoff: 4500, resonance: 40, envelopeAmount: 50 },
    } as Partial<SuperSawConfig>,
  },
];

// ============================================
// ORGAN PRESETS (Hammond B3 Style)
// ============================================

