import type { SynthPreset } from './types';
import type { SynareConfig } from '../../types/instrument';

export const SYNARE_PRESETS: SynthPreset[] = [
  {
    id: 'synare-deep-kick',
    name: 'Deep Kick',
    description: 'Boomy sub-heavy kick drum',
    category: 'drum',
    config: {
      oscillator: { type: 'square', tune: 60, fine: 0 },
      oscillator2: { enabled: false, detune: 0, mix: 0 },
      noise: { enabled: false, type: 'white', mix: 0, color: 20 },
      filter: { cutoff: 200, resonance: 30, envMod: 40, decay: 200 },
      lfo: { enabled: false, rate: 1, depth: 0, target: 'pitch' },
      envelope: { decay: 400, sustain: 0 },
      sweep: { enabled: true, amount: 36, time: 50 },
    } as Partial<SynareConfig>,
  },
  {
    id: 'synare-punchy-kick',
    name: 'Punchy Kick',
    description: 'Tight punchy kick with click',
    category: 'drum',
    config: {
      oscillator: { type: 'square', tune: 80, fine: 0 },
      oscillator2: { enabled: false, detune: 0, mix: 0 },
      noise: { enabled: true, type: 'white', mix: 0.15, color: 30 },
      filter: { cutoff: 300, resonance: 20, envMod: 50, decay: 100 },
      lfo: { enabled: false, rate: 1, depth: 0, target: 'pitch' },
      envelope: { decay: 250, sustain: 0 },
      sweep: { enabled: true, amount: 24, time: 30 },
    } as Partial<SynareConfig>,
  },
  {
    id: 'synare-snappy-snare',
    name: 'Snappy Snare',
    description: 'Tight snare with noise crack',
    category: 'drum',
    config: {
      oscillator: { type: 'square', tune: 180, fine: 0 },
      oscillator2: { enabled: true, detune: 7, mix: 0.4 },
      noise: { enabled: true, type: 'white', mix: 0.6, color: 60 },
      filter: { cutoff: 4000, resonance: 15, envMod: 30, decay: 150 },
      lfo: { enabled: false, rate: 1, depth: 0, target: 'pitch' },
      envelope: { decay: 200, sustain: 0 },
      sweep: { enabled: true, amount: 12, time: 20 },
    } as Partial<SynareConfig>,
  },
  {
    id: 'synare-fat-snare',
    name: 'Fat Snare',
    description: 'Thick layered analog snare',
    category: 'drum',
    config: {
      oscillator: { type: 'square', tune: 150, fine: 0 },
      oscillator2: { enabled: true, detune: 5, mix: 0.5 },
      noise: { enabled: true, type: 'pink', mix: 0.5, color: 50 },
      filter: { cutoff: 3000, resonance: 25, envMod: 40, decay: 200 },
      lfo: { enabled: false, rate: 1, depth: 0, target: 'pitch' },
      envelope: { decay: 350, sustain: 0 },
      sweep: { enabled: true, amount: 8, time: 25 },
    } as Partial<SynareConfig>,
  },
  {
    id: 'synare-hihat',
    name: 'Hi-Hat',
    description: 'Metallic closed hi-hat',
    category: 'drum',
    config: {
      oscillator: { type: 'square', tune: 800, fine: 30 },
      oscillator2: { enabled: true, detune: 11, mix: 0.7 },
      noise: { enabled: true, type: 'white', mix: 0.8, color: 80 },
      filter: { cutoff: 8000, resonance: 20, envMod: 10, decay: 60 },
      lfo: { enabled: false, rate: 1, depth: 0, target: 'pitch' },
      envelope: { decay: 80, sustain: 0 },
      sweep: { enabled: false, amount: 0, time: 10 },
    } as Partial<SynareConfig>,
  },
  {
    id: 'synare-tom',
    name: 'Analog Tom',
    description: 'Classic analog drum tom',
    category: 'drum',
    config: {
      oscillator: { type: 'square', tune: 120, fine: 0 },
      oscillator2: { enabled: false, detune: 0, mix: 0 },
      noise: { enabled: true, type: 'white', mix: 0.1, color: 30 },
      filter: { cutoff: 1500, resonance: 35, envMod: 50, decay: 300 },
      lfo: { enabled: false, rate: 1, depth: 0, target: 'pitch' },
      envelope: { decay: 500, sustain: 0 },
      sweep: { enabled: true, amount: 18, time: 80 },
    } as Partial<SynareConfig>,
  },
  {
    id: 'synare-laser-tom',
    name: 'Laser Tom',
    description: 'Sci-fi laser tom with long sweep',
    category: 'drum',
    config: {
      oscillator: { type: 'square', tune: 400, fine: 0 },
      oscillator2: { enabled: false, detune: 0, mix: 0 },
      noise: { enabled: false, type: 'white', mix: 0, color: 20 },
      filter: { cutoff: 5000, resonance: 50, envMod: 70, decay: 400 },
      lfo: { enabled: false, rate: 1, depth: 0, target: 'pitch' },
      envelope: { decay: 600, sustain: 0 },
      sweep: { enabled: true, amount: 48, time: 200 },
    } as Partial<SynareConfig>,
  },
  {
    id: 'synare-metallic-hit',
    name: 'Metallic Hit',
    description: 'Harsh metallic percussion hit',
    category: 'drum',
    config: {
      oscillator: { type: 'pulse', tune: 500, fine: 50 },
      oscillator2: { enabled: true, detune: 13, mix: 0.8 },
      noise: { enabled: true, type: 'white', mix: 0.3, color: 70 },
      filter: { cutoff: 6000, resonance: 60, envMod: 50, decay: 100 },
      lfo: { enabled: false, rate: 1, depth: 0, target: 'pitch' },
      envelope: { decay: 150, sustain: 0 },
      sweep: { enabled: true, amount: 6, time: 15 },
    } as Partial<SynareConfig>,
  },
  {
    id: 'synare-zap',
    name: 'Zap',
    description: 'Quick pitch-sweep zap percussion',
    category: 'drum',
    config: {
      oscillator: { type: 'square', tune: 600, fine: 0 },
      oscillator2: { enabled: false, detune: 0, mix: 0 },
      noise: { enabled: false, type: 'white', mix: 0, color: 20 },
      filter: { cutoff: 10000, resonance: 40, envMod: 80, decay: 50 },
      lfo: { enabled: false, rate: 1, depth: 0, target: 'pitch' },
      envelope: { decay: 100, sustain: 0 },
      sweep: { enabled: true, amount: 36, time: 30 },
    } as Partial<SynareConfig>,
  },
  {
    id: 'synare-wobble-drum',
    name: 'Wobble Drum',
    description: 'LFO-modulated tribal drum',
    category: 'drum',
    config: {
      oscillator: { type: 'square', tune: 100, fine: 0 },
      oscillator2: { enabled: true, detune: 3, mix: 0.3 },
      noise: { enabled: true, type: 'pink', mix: 0.15, color: 40 },
      filter: { cutoff: 1000, resonance: 45, envMod: 60, decay: 500 },
      lfo: { enabled: true, rate: 8, depth: 40, target: 'pitch' },
      envelope: { decay: 700, sustain: 0 },
      sweep: { enabled: true, amount: 12, time: 100 },
    } as Partial<SynareConfig>,
  },
];
