import type { SynthPreset } from './types';
import type { V2Config } from '../../types/instrument';

export const V2_PRESETS: SynthPreset[] = [
  {
    id: 'v2-moog-bass',
    name: 'Moog Bass',
    description: 'Classic Moog-style resonant bass',
    category: 'bass',
    config: {
      osc1: { mode: 1, transpose: 64, detune: 64, color: 0, level: 120 },
      osc2: { mode: 1, ringMod: false, transpose: 52, detune: 66, color: 10, level: 100 },
      osc3: { mode: 0, ringMod: false, transpose: 64, detune: 64, color: 0, level: 0 },
      filter1: { mode: 6, cutoff: 50, resonance: 80 },
      filter2: { mode: 0, cutoff: 64, resonance: 0 },
      routing: { mode: 0, balance: 64 },
      envelope: { attack: 2, decay: 50, sustain: 60, release: 20 },
      envelope2: { attack: 0, decay: 40, sustain: 0, release: 15 },
      lfo1: { rate: 30, depth: 0 },
    } as Partial<V2Config>,
  },
  {
    id: 'v2-screaming-lead',
    name: 'Screaming Lead',
    description: 'High-resonance aggressive lead',
    category: 'lead',
    config: {
      osc1: { mode: 1, transpose: 64, detune: 64, color: 30, level: 127 },
      osc2: { mode: 2, ringMod: false, transpose: 76, detune: 67, color: 50, level: 90 },
      osc3: { mode: 0, ringMod: false, transpose: 64, detune: 64, color: 0, level: 0 },
      filter1: { mode: 6, cutoff: 40, resonance: 110 },
      filter2: { mode: 0, cutoff: 64, resonance: 0 },
      routing: { mode: 0, balance: 64 },
      envelope: { attack: 3, decay: 30, sustain: 90, release: 15 },
      envelope2: { attack: 0, decay: 50, sustain: 20, release: 30 },
      lfo1: { rate: 50, depth: 15 },
    } as Partial<V2Config>,
  },
  {
    id: 'v2-lush-pad',
    name: 'Lush Pad',
    description: 'Warm detuned pad with slow attack',
    category: 'pad',
    config: {
      osc1: { mode: 1, transpose: 64, detune: 60, color: 20, level: 100 },
      osc2: { mode: 1, ringMod: false, transpose: 64, detune: 68, color: 25, level: 100 },
      osc3: { mode: 3, ringMod: false, transpose: 76, detune: 64, color: 0, level: 50 },
      filter1: { mode: 1, cutoff: 70, resonance: 20 },
      filter2: { mode: 0, cutoff: 64, resonance: 0 },
      routing: { mode: 0, balance: 64 },
      envelope: { attack: 80, decay: 70, sustain: 90, release: 80 },
      envelope2: { attack: 90, decay: 60, sustain: 80, release: 70 },
      lfo1: { rate: 25, depth: 10 },
    } as Partial<V2Config>,
  },
  {
    id: 'v2-digital-keys',
    name: 'Digital Keys',
    description: 'Clean digital keyboard sound',
    category: 'key',
    config: {
      osc1: { mode: 2, transpose: 64, detune: 64, color: 64, level: 110 },
      osc2: { mode: 3, ringMod: false, transpose: 76, detune: 64, color: 0, level: 70 },
      osc3: { mode: 0, ringMod: false, transpose: 64, detune: 64, color: 0, level: 0 },
      filter1: { mode: 1, cutoff: 80, resonance: 15 },
      filter2: { mode: 0, cutoff: 64, resonance: 0 },
      routing: { mode: 0, balance: 64 },
      envelope: { attack: 1, decay: 60, sustain: 40, release: 40 },
      envelope2: { attack: 0, decay: 50, sustain: 30, release: 35 },
      lfo1: { rate: 40, depth: 5 },
    } as Partial<V2Config>,
  },
  {
    id: 'v2-acid-squelch',
    name: 'Acid Squelch',
    description: 'Resonant filter sweep acid line',
    category: 'bass',
    config: {
      osc1: { mode: 1, transpose: 64, detune: 64, color: 0, level: 127 },
      osc2: { mode: 0, ringMod: false, transpose: 64, detune: 64, color: 0, level: 0 },
      osc3: { mode: 0, ringMod: false, transpose: 64, detune: 64, color: 0, level: 0 },
      filter1: { mode: 6, cutoff: 30, resonance: 100 },
      filter2: { mode: 0, cutoff: 64, resonance: 0 },
      routing: { mode: 0, balance: 64 },
      envelope: { attack: 1, decay: 35, sustain: 40, release: 10 },
      envelope2: { attack: 0, decay: 25, sustain: 0, release: 10 },
      lfo1: { rate: 30, depth: 0 },
    } as Partial<V2Config>,
  },
  {
    id: 'v2-noise-sweep',
    name: 'Noise Sweep',
    description: 'Filtered noise riser/sweep',
    category: 'fx',
    config: {
      osc1: { mode: 4, transpose: 64, detune: 64, color: 64, level: 127 },
      osc2: { mode: 0, ringMod: false, transpose: 64, detune: 64, color: 0, level: 0 },
      osc3: { mode: 0, ringMod: false, transpose: 64, detune: 64, color: 0, level: 0 },
      filter1: { mode: 2, cutoff: 60, resonance: 70 },
      filter2: { mode: 0, cutoff: 64, resonance: 0 },
      routing: { mode: 0, balance: 64 },
      envelope: { attack: 70, decay: 80, sustain: 50, release: 60 },
      envelope2: { attack: 80, decay: 90, sustain: 40, release: 50 },
      lfo1: { rate: 20, depth: 40 },
    } as Partial<V2Config>,
  },
  {
    id: 'v2-dual-filter',
    name: 'Dual Filter',
    description: 'Serial low+high filter combo',
    category: 'lead',
    config: {
      osc1: { mode: 1, transpose: 64, detune: 62, color: 15, level: 120 },
      osc2: { mode: 2, ringMod: false, transpose: 64, detune: 66, color: 40, level: 100 },
      osc3: { mode: 0, ringMod: false, transpose: 64, detune: 64, color: 0, level: 0 },
      filter1: { mode: 1, cutoff: 55, resonance: 50 },
      filter2: { mode: 3, cutoff: 30, resonance: 40 },
      routing: { mode: 1, balance: 64 },
      envelope: { attack: 5, decay: 40, sustain: 70, release: 25 },
      envelope2: { attack: 0, decay: 30, sustain: 50, release: 20 },
      lfo1: { rate: 35, depth: 20 },
    } as Partial<V2Config>,
  },
  {
    id: 'v2-ring-mod-bell',
    name: 'Ring Mod Bell',
    description: 'Inharmonic ring modulation bell',
    category: 'key',
    config: {
      osc1: { mode: 3, transpose: 64, detune: 64, color: 0, level: 110 },
      osc2: { mode: 3, ringMod: true, transpose: 71, detune: 64, color: 0, level: 90 },
      osc3: { mode: 0, ringMod: false, transpose: 64, detune: 64, color: 0, level: 0 },
      filter1: { mode: 1, cutoff: 90, resonance: 10 },
      filter2: { mode: 0, cutoff: 64, resonance: 0 },
      routing: { mode: 0, balance: 64 },
      envelope: { attack: 1, decay: 90, sustain: 0, release: 60 },
      envelope2: { attack: 0, decay: 70, sustain: 0, release: 50 },
      lfo1: { rate: 30, depth: 5 },
    } as Partial<V2Config>,
  },
  {
    id: 'v2-sub-bass',
    name: 'V2 Sub',
    description: 'Deep sine sub bass',
    category: 'bass',
    config: {
      osc1: { mode: 3, transpose: 52, detune: 64, color: 0, level: 127 },
      osc2: { mode: 0, ringMod: false, transpose: 64, detune: 64, color: 0, level: 0 },
      osc3: { mode: 0, ringMod: false, transpose: 64, detune: 64, color: 0, level: 0 },
      filter1: { mode: 6, cutoff: 40, resonance: 30 },
      filter2: { mode: 0, cutoff: 64, resonance: 0 },
      routing: { mode: 0, balance: 64 },
      envelope: { attack: 2, decay: 40, sustain: 100, release: 25 },
      envelope2: { attack: 0, decay: 30, sustain: 80, release: 20 },
      lfo1: { rate: 30, depth: 0 },
    } as Partial<V2Config>,
  },
  {
    id: 'v2-harsh-industrial',
    name: 'Industrial',
    description: 'Harsh noisy industrial texture',
    category: 'lead',
    config: {
      osc1: { mode: 2, transpose: 64, detune: 64, color: 20, level: 120 },
      osc2: { mode: 4, ringMod: true, transpose: 64, detune: 64, color: 80, level: 80 },
      osc3: { mode: 1, ringMod: false, transpose: 76, detune: 70, color: 40, level: 60 },
      filter1: { mode: 2, cutoff: 50, resonance: 60 },
      filter2: { mode: 3, cutoff: 70, resonance: 40 },
      routing: { mode: 2, balance: 50 },
      envelope: { attack: 1, decay: 45, sustain: 80, release: 15 },
      envelope2: { attack: 0, decay: 35, sustain: 60, release: 10 },
      lfo1: { rate: 60, depth: 25 },
    } as Partial<V2Config>,
  },
];
