import type { SynthPreset } from './types';
import type { WavetableConfig } from '../../types/instrument';

export const WAVETABLE_PRESETS: SynthPreset[] = [
  {
    id: 'wt-evolving-pad',
    name: 'Evolving Pad',
    description: 'Slowly morphing wavetable pad',
    category: 'pad',
    config: {
      wavetableId: 'basic',
      morphPosition: 30,
      morphModSource: 'lfo',
      morphModAmount: 60,
      morphLFORate: 0.3,
      unison: { voices: 4, detune: 25, stereoSpread: 80 },
      envelope: { attack: 800, decay: 1500, sustain: 70, release: 1200 },
      filter: { type: 'lowpass', cutoff: 5000, resonance: 15, envelopeAmount: -20 },
      filterEnvelope: { attack: 600, decay: 1200, sustain: 60, release: 1000 },
    } as Partial<WavetableConfig>,
  },
  {
    id: 'wt-digital-lead',
    name: 'Digital Lead',
    description: 'Sharp digital wavetable lead',
    category: 'lead',
    config: {
      wavetableId: 'basic',
      morphPosition: 50,
      morphModSource: 'envelope',
      morphModAmount: 40,
      morphLFORate: 1,
      unison: { voices: 2, detune: 10, stereoSpread: 40 },
      envelope: { attack: 10, decay: 300, sustain: 60, release: 150 },
      filter: { type: 'lowpass', cutoff: 8000, resonance: 25, envelopeAmount: 30 },
      filterEnvelope: { attack: 5, decay: 250, sustain: 40, release: 120 },
    } as Partial<WavetableConfig>,
  },
  {
    id: 'wt-pluck',
    name: 'WT Pluck',
    description: 'Short percussive wavetable pluck',
    category: 'pluck',
    config: {
      wavetableId: 'basic',
      morphPosition: 70,
      morphModSource: 'envelope',
      morphModAmount: 80,
      morphLFORate: 1,
      unison: { voices: 3, detune: 15, stereoSpread: 50 },
      envelope: { attack: 2, decay: 200, sustain: 0, release: 80 },
      filter: { type: 'lowpass', cutoff: 10000, resonance: 20, envelopeAmount: 50 },
      filterEnvelope: { attack: 1, decay: 150, sustain: 0, release: 60 },
    } as Partial<WavetableConfig>,
  },
  {
    id: 'wt-warm-keys',
    name: 'WT Keys',
    description: 'Warm wavetable keyboard sound',
    category: 'key',
    config: {
      wavetableId: 'basic',
      morphPosition: 20,
      morphModSource: 'none',
      morphModAmount: 0,
      morphLFORate: 1,
      unison: { voices: 2, detune: 8, stereoSpread: 30 },
      envelope: { attack: 10, decay: 600, sustain: 40, release: 300 },
      filter: { type: 'lowpass', cutoff: 4000, resonance: 10, envelopeAmount: 20 },
      filterEnvelope: { attack: 5, decay: 400, sustain: 30, release: 250 },
    } as Partial<WavetableConfig>,
  },
  {
    id: 'wt-glass-shimmer',
    name: 'Glass Shimmer',
    description: 'Bright shimmering texture',
    category: 'pad',
    config: {
      wavetableId: 'basic',
      morphPosition: 80,
      morphModSource: 'lfo',
      morphModAmount: 30,
      morphLFORate: 1.5,
      unison: { voices: 6, detune: 30, stereoSpread: 90 },
      envelope: { attack: 400, decay: 1000, sustain: 50, release: 1500 },
      filter: { type: 'highpass', cutoff: 800, resonance: 12, envelopeAmount: -15 },
      filterEnvelope: { attack: 300, decay: 800, sustain: 40, release: 1200 },
    } as Partial<WavetableConfig>,
  },
  {
    id: 'wt-thick-bass',
    name: 'WT Bass',
    description: 'Thick wavetable bass',
    category: 'bass',
    config: {
      wavetableId: 'basic',
      morphPosition: 10,
      morphModSource: 'envelope',
      morphModAmount: 50,
      morphLFORate: 1,
      unison: { voices: 3, detune: 12, stereoSpread: 20 },
      envelope: { attack: 5, decay: 300, sustain: 50, release: 100 },
      filter: { type: 'lowpass', cutoff: 1500, resonance: 40, envelopeAmount: 60 },
      filterEnvelope: { attack: 2, decay: 200, sustain: 20, release: 80 },
    } as Partial<WavetableConfig>,
  },
  {
    id: 'wt-stereo-sweep',
    name: 'Stereo Sweep',
    description: 'Wide morphing stereo texture',
    category: 'pad',
    config: {
      wavetableId: 'basic',
      morphPosition: 0,
      morphModSource: 'lfo',
      morphModAmount: 100,
      morphLFORate: 0.15,
      unison: { voices: 8, detune: 40, stereoSpread: 100 },
      envelope: { attack: 1000, decay: 2000, sustain: 80, release: 2000 },
      filter: { type: 'lowpass', cutoff: 7000, resonance: 8, envelopeAmount: -10 },
      filterEnvelope: { attack: 800, decay: 1500, sustain: 70, release: 1800 },
    } as Partial<WavetableConfig>,
  },
  {
    id: 'wt-aggressive-lead',
    name: 'Aggressive Lead',
    description: 'In-your-face digital lead',
    category: 'lead',
    config: {
      wavetableId: 'basic',
      morphPosition: 60,
      morphModSource: 'envelope',
      morphModAmount: 70,
      morphLFORate: 1,
      unison: { voices: 4, detune: 20, stereoSpread: 60 },
      envelope: { attack: 3, decay: 200, sustain: 70, release: 100 },
      filter: { type: 'lowpass', cutoff: 6000, resonance: 35, envelopeAmount: 40 },
      filterEnvelope: { attack: 2, decay: 150, sustain: 50, release: 80 },
    } as Partial<WavetableConfig>,
  },
];
