/* ====================================================================
 * Auto-generated by asm68k-to-c transpiler
 * Source: Cinter4.S
 *
 * This file was mechanically translated from Motorola 68000 assembly.
 * Original ASM instructions appear as inline comments.
 * ==================================================================== */

#include "paula_soft.h"
#include <stdint.h>

/* -- 68k Register File ------------------------------------------------
 * Data registers D0-D7:  general-purpose 32-bit registers.
 * Address registers A0-A6: pointer registers (32-bit).
 * SP (A7): stack pointer.  PC: program counter (unused in transpiled code).
 * Flags: Z (zero), N (negative), C (carry), V (overflow), X (extend).
 * -------------------------------------------------------------------- */
static uint32_t d0,d1,d2,d3,d4,d5,d6,d7;
uint32_t a0,a1,a2,a3,a4,a5,a6,sp,pc;
#define a7 sp  /* A7 is the stack pointer */
static int flag_z=0, flag_n=0, flag_c=0, flag_v=0, flag_x=0;
static uint16_t ccr = 0;  /* condition code register (for MOVE SR/CCR) */
static uint16_t sr = 0;   /* status register (interrupt mask bits etc.) */

/* -- Sub-register Accessors -------------------------------------------
 * W(d0) -- access the low 16 bits of d0 (read/write).
 * B(d0) -- access the low 8 bits of d0 (read/write).
 * Example: W(d0) = 0x1234;  // sets d0.w, leaves upper 16 bits unchanged
 * -------------------------------------------------------------------- */
#define W(r)  (*((uint16_t*)&(r)))
#define B(r)  (*((uint8_t*)&(r)))

/* -- Memory Access (Big-Endian) ---------------------------------------
 * The 68k is big-endian; these macros byte-swap on little-endian hosts.
 * Uses memcpy for alignment-safe access (68k allows unaligned word/long).
 *
 * READ8(addr)       -- read  byte from address
 * READ16(addr)      -- read  big-endian word from address
 * READ32(addr)      -- read  big-endian longword from address
 * WRITE8(addr,v)    -- write byte to address
 * WRITE16(addr,v)   -- write big-endian word to address
 * WRITE32(addr,v)   -- write big-endian longword to address
 * READ16_POST(reg)  -- read word, then reg += 2  (simulates (An)+ mode)
 * WRITE16_PRE(reg,v)-- reg -= 2, then write word (simulates -(An) mode)
 * -------------------------------------------------------------------- */
#include <string.h>
#define READ8(addr)   (*((const uint8_t*)(uintptr_t)(addr)))
#define WRITE8(addr,v)  (*((uint8_t*)(uintptr_t)(addr)) = (uint8_t)(v))
static inline uint16_t _rd16(uintptr_t a) { uint16_t v; memcpy(&v,(void*)a,2); return v; }
static inline uint32_t _rd32(uintptr_t a) { uint32_t v; memcpy(&v,(void*)a,4); return v; }
static inline void _wr16(uintptr_t a,uint16_t v) { memcpy((void*)a,&v,2); }
static inline void _wr32(uintptr_t a,uint32_t v) { memcpy((void*)a,&v,4); }
#if defined(__BYTE_ORDER__) && __BYTE_ORDER__ == __ORDER_BIG_ENDIAN__
#define READ16(addr)  _rd16((uintptr_t)(addr))
#define READ32(addr)  _rd32((uintptr_t)(addr))
#define WRITE16(addr,v) _wr16((uintptr_t)(addr),(uint16_t)(v))
#define WRITE32(addr,v) _wr32((uintptr_t)(addr),(uint32_t)(v))
#else
#define READ16(addr)  __builtin_bswap16(_rd16((uintptr_t)(addr)))
#define READ32(addr)  __builtin_bswap32(_rd32((uintptr_t)(addr)))
#define WRITE16(addr,v) _wr16((uintptr_t)(addr),__builtin_bswap16((uint16_t)(v)))
#define WRITE32(addr,v) _wr32((uintptr_t)(addr),__builtin_bswap32((uint32_t)(v)))
#endif
#define READ8_POST(r)   ({ uint32_t _r=(r); (r)+=1; READ8(_r); })
#define READ16_POST(r)  ({ uint32_t _r=(r); (r)+=2; READ16(_r); })
#define READ32_POST(r)  ({ uint32_t _r=(r); (r)+=4; READ32(_r); })
#define READ8_PRE(r)    ({ (r)-=1; READ8(r); })
#define READ16_PRE(r)   ({ (r)-=2; READ16(r); })
#define READ32_PRE(r)   ({ (r)-=4; READ32(r); })
#define WRITE8_POST(r,v)  ({ WRITE8(r,v);  (r)+=1; })
#define WRITE16_POST(r,v) ({ WRITE16(r,v); (r)+=2; })
#define WRITE32_POST(r,v) ({ WRITE32(r,v); (r)+=4; })
#define WRITE8_PRE(r,v)   ({ (r)-=1; WRITE8(r,v); })
#define WRITE16_PRE(r,v)  ({ (r)-=2; WRITE16(r,v); })
#define WRITE32_PRE(r,v)  ({ (r)-=4; WRITE32(r,v); })

/* -- Rotation Helpers -------------------------------------------------
 * ROL32(v,n) -- rotate 32-bit value left by n bits
 * ROR32(v,n) -- rotate 32-bit value right by n bits
 * -------------------------------------------------------------------- */
#define ROL32(v,n)  (((v)<<(n))|((v)>>(32-(n))))
#define ROR32(v,n)  (((v)>>(n))|((v)<<(32-(n))))
/* 16-bit rotate: ROL32 loses the wrap-around bits when applied to a uint16 value */
#define ROL16(v,n)  ((uint16_t)(((uint32_t)(uint16_t)(v)<<(n))|((uint32_t)(uint16_t)(v)>>(16-(n)))))

/* -- Hardware Write Interception --------------------------------------
 * Many 68k replayers load $DFF000 into a register and then write to
 * channel offsets (e.g. MOVE.W d0,$A8(a0) for volume on channel 0).
 * These runtime checks intercept writes to the Paula/DMACON address
 * range and route them to the paula_soft API instead of memory.
 * -------------------------------------------------------------------- */
static inline void hw_write8(uint32_t addr, uint8_t val) {
  if (addr >= 0xDFF000 && addr < 0xE00000) return; /* ignore byte writes to custom chips */
  WRITE8(addr, val);
}
static inline void hw_write16(uint32_t addr, uint16_t val) {
  if (addr >= 0xDFF0A0 && addr <= 0xDFF0DF) {
    int ch = (addr - 0xDFF0A0) >> 4;
    int reg = (addr & 0x0F);
    switch (reg) {
      case 0x06: paula_set_period(ch, val); return;
      case 0x08: paula_set_volume(ch, (uint8_t)val); return;
      case 0x04: paula_set_length(ch, val); return;
      default: return; /* AUDxDAT or unknown */
    }
  }
  if (addr == 0xDFF096) { paula_dma_write(val); return; }
  if (addr >= 0xDFF000 && addr < 0xE00000) return; /* other custom chip writes */
  if (addr >= 0xBF0000 && addr < 0xC00000) return; /* CIA writes */
  WRITE16(addr, val);
}
static inline void hw_write32(uint32_t addr, uint32_t val) {
  if (addr >= 0xDFF0A0 && addr <= 0xDFF0DF) {
    int ch = (addr - 0xDFF0A0) >> 4;
    int reg = (addr & 0x0F);
    if (reg == 0x00) { paula_set_sample_ptr(ch, (const int8_t*)(uintptr_t)val); return; }
  }
  if (addr >= 0xDFF000 && addr < 0xE00000) {
    /* Fallback: treat as two word writes (big-endian high word first) */
    hw_write16(addr, (uint16_t)(val >> 16));
    hw_write16(addr + 2, (uint16_t)val);
    return;
  }
  if (addr >= 0xBF0000 && addr < 0xC00000) return; /* CIA writes */
  WRITE32(addr, val);
}

/* -- EQU Constants ------------------------------------------------- */
#define CINTER_DEGREES 16384
/* c_* */
#define c_SampleState 0
#define c_PeriodTable 12
#define c_TrackSize 86
#define c_InstPointer 88
#define c_MusicPointer 92
#define c_MusicEnd 96
#define c_MusicLoop 100
#define c_MusicState 104
#define c_dma 152
#define c_waitline 154
#define c_Instruments 156
#define c_Sinus 412
#define c_SIZE 412

/* -- External Data Placeholders (INCBIN / external data) ------------- */
/* Host must set these pointers to actual module data before playback. */
static uint8_t* _loop = NULL;
static uint8_t* _instrumentloop = NULL;
static uint8_t* _rawloop = NULL;
static uint8_t* _mdist = NULL;
static uint8_t* _bdist = NULL;
static uint8_t* _vpower = NULL;
static uint8_t* _fdist_in = NULL;
static uint8_t* _fdist = NULL;
static uint8_t* _notover = NULL;
static uint8_t* _nottop = NULL;
static uint8_t* _notzero = NULL;
static uint8_t* _pc_off_01a0 = NULL;
static uint8_t* _pc_off_01bc = NULL;
static uint8_t* _pc_off_01d8 = NULL;
static uint8_t* _sampleloop = NULL;
static uint8_t* _loop1 = NULL;
static uint8_t* _notend = NULL;
static uint8_t* _trigger = NULL;
static uint8_t* _slide = NULL;
static uint8_t* _write = NULL;
static uint8_t* _sameinst = NULL;
static uint8_t* _noteloop = NULL;
static uint8_t* _norepeat = NULL;
static uint8_t* _channelloop = NULL;
static uint8_t* _nodma = NULL;
static uint8_t* _dmawait = NULL;

/* -- Forward Declarations -------------------------------------------- */
void CinterInit(void);
void CinterPlay1(void);
void CinterPlay2(void);


/* ====================================================================
 * Code Section -- Transpiled Functions
 * ==================================================================== */
/* T         T               T */

/* --- CinterInit ---  (PUBLIC) */
void CinterInit(void) {
_top: ;
  /* A2 = Music data */
  /* A4 = Instrument space */
  /* A6 = Cinter working memory */
  /* Raw instrument data must be copied to the start of the */
  /* instrument space before or after CinterInit is called. */
CinterMakeSinus:
  a0 = (uint32_t)(a6 + (intptr_t)c_Sinus);  /* LEA	c_Sinus(A6),A0 */
  a0 = (uint32_t)((int32_t)a0 + (int32_t)(int16_t)(2));  /* ADDQ.L	#2,A0 */
  a1 = (uint32_t)(a0 + 16382);  /* LEA.L	16382(A0),A1 */
  d7 = (uint32_t)(int32_t)(int8_t)(1);  /* MOVEQ.L	#1,D7 */
do {
  {  /* MOVE.W	D7,D1 */
      uint16_t _mv = (uint16_t)(W(d7));
      W(d1) = (uint16_t)_mv;
      flag_z = ((int16_t)(_mv) == 0);
      flag_n = ((int16_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  d1 = (uint32_t)((uint16_t)(W(d7)) * (uint16_t)W(d1));  /* MULU.W	D7,D1 */
  d1 >>= 8;  /* LSR.L	#8,D1 */
  {  /* MOVE.W	#2373,D0 */
      uint16_t _mv = (uint16_t)(2373);
      W(d0) = (uint16_t)_mv;
      flag_z = ((int16_t)(_mv) == 0);
      flag_n = ((int16_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  d0 = (uint32_t)((uint16_t)(W(d1)) * (uint16_t)W(d0));  /* MULU.W	D1,D0 */
  d0 = (d0 >> 16) | (d0 << 16);  /* SWAP.W	D0 */
  W(d0) = (uint16_t)(-(int16_t)W(d0));  /* NEG.W	D0 */
  {  /* ADD.W	#21073,D0 */
      uint16_t _ar = (uint16_t)(W(d0) + 21073);
      W(d0) = (uint16_t)((uint16_t)_ar);
      flag_z = ((int16_t)(_ar) == 0);
      flag_n = ((int16_t)(_ar) < 0);
    }
  d0 = (uint32_t)((uint16_t)(W(d1)) * (uint16_t)W(d0));  /* MULU.W	D1,D0 */
  d0 = (d0 >> 16) | (d0 << 16);  /* SWAP.W	D0 */
  W(d0) = (uint16_t)(-(int16_t)W(d0));  /* NEG.W	D0 */
  {  /* ADD.W	#51469,D0 */
      uint16_t _ar = (uint16_t)(W(d0) + 51469);
      W(d0) = (uint16_t)((uint16_t)_ar);
      flag_z = ((int16_t)(_ar) == 0);
      flag_n = ((int16_t)(_ar) < 0);
    }
  d0 = (uint32_t)((uint16_t)(W(d7)) * (uint16_t)W(d0));  /* MULU.W	D7,D0 */
  d0 >>= 8;  /* LSR.L	#8,D0 */
  d0 >>= 5;  /* LSR.L	#5,D0 */
  {  /* MOVE.W	D0,(A0)+ */
      uint16_t _mv = (uint16_t)(W(d0));
      WRITE16_POST(a0, _mv);
      flag_z = ((int16_t)(_mv) == 0);
      flag_n = ((int16_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  {  /* MOVE.W	D0,-(A1) */
      uint16_t _mv = (uint16_t)(W(d0));
      WRITE16_PRE(a1, _mv);
      flag_z = ((int16_t)(_mv) == 0);
      flag_n = ((int16_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  W(d0) = (uint16_t)(-(int16_t)W(d0));  /* NEG.W	D0 */
  {  /* MOVE.W	D0,16384(A1) */
      uint16_t _mv = (uint16_t)(W(d0));
      hw_write16(a1 + 16384, _mv);
      flag_z = ((int16_t)(_mv) == 0);
      flag_n = ((int16_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  {  /* MOVE.W	D0,16382(A0) */
      uint16_t _mv = (uint16_t)(W(d0));
      hw_write16(a0 + 16382, _mv);
      flag_z = ((int16_t)(_mv) == 0);
      flag_n = ((int16_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  {  /* ADDQ.W	#1,D7 */
      uint16_t _ar = (uint16_t)(W(d7) + 1);
      W(d7) = (uint16_t)((uint16_t)_ar);
      flag_z = ((int16_t)(_ar) == 0);
      flag_n = ((int16_t)(_ar) < 0);
    }
  {  /* CMP.W	#(CINTER_DEGREES/4),D7 — must set V for the following BLT (flag_n!=flag_v) */
      int32_t _lhs = (int32_t)(W(d7));
      int32_t _rhs = (int32_t)((CINTER_DEGREES/4));
      int32_t _cmp = _lhs - _rhs;
      uint16_t _va=(uint16_t)W(d7), _vb=(uint16_t)((CINTER_DEGREES/4)&0xffff), _vr=(uint16_t)(_va-_vb);
      flag_v = ((((_va ^ _vb) & (_va ^ _vr)) >> 15) & 1);
      flag_z = (_cmp == 0);
      flag_n = (_cmp < 0);
      flag_c = ((uint32_t)_lhs < (uint32_t)_rhs);
    }
} while (flag_n!=flag_v);
  W(d0) = (uint16_t)(-(int16_t)W(d0));  /* NEG.W	D0 */
  {  /* MOVE.W	D0,-(A1) */
      uint16_t _mv = (uint16_t)(W(d0));
      WRITE16_PRE(a1, _mv);
      flag_z = ((int16_t)(_mv) == 0);
      flag_n = ((int16_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  W(d0) = (uint16_t)(-(int16_t)W(d0));  /* NEG.W	D0 */
  {  /* MOVE.W	D0,16384(A1) */
      uint16_t _mv = (uint16_t)(W(d0));
      hw_write16(a1 + 16384, _mv);
      flag_z = ((int16_t)(_mv) == 0);
      flag_n = ((int16_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  /* Sample parameters: */
  /* short length, replength */
  /* short mpitch, mod, bpitch */
  /* short attack, distortions, decay */
  /* short mpitchdecay, moddecay, bpitchdecay */
  /* Sample state: */
  /* long mpitch, mod, bpitch */
  /* short ampdelta,amp */
CinterMakeInstruments:
  a0 = (uint32_t)(a6 + (intptr_t)c_Sinus);  /* LEA	c_Sinus(A6),A0 */
  a5 = (uint32_t)(a6 + (intptr_t)c_Instruments);  /* LEA	c_Instruments(A6),A5 */
  /* Loop through instruments */
  {  /* MOVE.W	(A2)+,D7 */
      uint16_t _mv = (uint16_t)(READ16_POST(a2));
      W(d7) = (uint16_t)_mv;
      flag_z = ((int16_t)(_mv) == 0);
      flag_n = ((int16_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  if (flag_n) {
  W(d7) = (uint16_t)(~W(d7));  /* NOT.W	D7 */
  /* Raw instruments */
do {
  /* Read length */
  d5 = 0;  /* CLR.L	D5 */
  {  /* MOVE.W	(A2),D5 */
      uint16_t _mv = (uint16_t)(READ16(a2));
      W(d5) = (uint16_t)_mv;
      flag_z = ((int16_t)(_mv) == 0);
      flag_n = ((int16_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  {  /* MOVE.L	(A2)+,(A5)+ */
      uint32_t _mv = (uint32_t)(READ32_POST(a2));
      WRITE32_POST(a5, _mv);
      flag_z = ((int32_t)(_mv) == 0);
      flag_n = ((int32_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  {  /* MOVE.L	A4,(A5)+ */
      uint32_t _mv = (uint32_t)(a4);
      WRITE32_POST(a5, _mv);
      flag_z = ((int32_t)(_mv) == 0);
      flag_n = ((int32_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  {  /* ADD.L	D5,D5 */
      uint32_t _ar = (uint32_t)(d5 + d5);
      d5 = (uint32_t)_ar;
      flag_z = ((int32_t)(_ar) == 0);
      flag_n = ((int32_t)(_ar) < 0);
    }
  a4 = (uint32_t)((int32_t)a4 + (int32_t)(d5));  /* ADD.L	D5,A4 (full 32-bit; transpiler wrongly truncated D5 to .W) */
} while ((int16_t)(--d7) >= 0);
  {  /* MOVE.W	(A2)+,D7 */
      uint16_t _mv = (uint16_t)(READ16_POST(a2));
      W(d7) = (uint16_t)_mv;
      flag_z = ((int16_t)(_mv) == 0);
      flag_n = ((int16_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  /* Generated instruments (NOTE: a4 advance fixed below to full 32-bit ADD.L) */
  }
_instrumentloop:
  /* Read length */
  d5 = 0;  /* CLR.L	D5 */
  {  /* MOVE.W	(A2),D5 */
      uint16_t _mv = (uint16_t)(READ16(a2));
      W(d5) = (uint16_t)_mv;
      flag_z = ((int16_t)(_mv) == 0);
      flag_n = ((int16_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  {  /* MOVE.L	(A2)+,(A5)+ */
      uint32_t _mv = (uint32_t)(READ32_POST(a2));
      WRITE32_POST(a5, _mv);
      flag_z = ((int32_t)(_mv) == 0);
      flag_n = ((int32_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  {  /* MOVE.L	A4,(A5)+ */
      uint32_t _mv = (uint32_t)(a4);
      WRITE32_POST(a5, _mv);
      flag_z = ((int32_t)(_mv) == 0);
      flag_n = ((int32_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  {  /* ADD.L	D5,D5 */
      uint32_t _ar = (uint32_t)(d5 + d5);
      d5 = (uint32_t)_ar;
      flag_z = ((int32_t)(_ar) == 0);
      flag_n = ((int32_t)(_ar) < 0);
    }
  /* Init state */
  {  /* MOVE.L	A6,A1 */
      uint32_t _mv = (uint32_t)(a6);
      a1 = _mv;
      flag_z = ((int32_t)(_mv) == 0);
      flag_n = ((int32_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  {  /* MOVE.W	(A2)+,(A1)+ */
      uint16_t _mv = (uint16_t)(READ16_POST(a2));
      WRITE16_POST(a1, _mv);
      flag_z = ((int16_t)(_mv) == 0);
      flag_n = ((int16_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  WRITE16_POST(a1, 0);  /* CLR.W	(A1)+ */
  {  /* MOVE.W	(A2)+,(A1)+ */
      uint16_t _mv = (uint16_t)(READ16_POST(a2));
      WRITE16_POST(a1, _mv);
      flag_z = ((int16_t)(_mv) == 0);
      flag_n = ((int16_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  WRITE16_POST(a1, 0);  /* CLR.W	(A1)+ */
  {  /* MOVE.W	(A2)+,(A1)+ */
      uint16_t _mv = (uint16_t)(READ16_POST(a2));
      WRITE16_POST(a1, _mv);
      flag_z = ((int16_t)(_mv) == 0);
      flag_n = ((int16_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  WRITE16_POST(a1, 0);  /* CLR.W	(A1)+ */
  {  /* MOVE.W	(A2)+,(A1)+ */
      uint16_t _mv = (uint16_t)(READ16_POST(a2));
      WRITE16_POST(a1, _mv);
      flag_z = ((int16_t)(_mv) == 0);
      flag_n = ((int16_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  WRITE16_POST(a1, 0);  /* CLR.W	(A1)+ */
  WRITE16_POST(a4, 0);  /* CLR.W	(A4)+ */
  {  /* SUBQ.L	#2,D5 */
      uint32_t _sr = (uint32_t)(d5 - 2);
      d5 = (uint32_t)_sr;
      flag_z = ((int32_t)(_sr) == 0);
      flag_n = ((int32_t)(_sr) < 0);
    }
  d6 = (uint32_t)(int32_t)(int8_t)(0);  /* MOVEQ.L	#0,D6 */
_sampleloop:
  /* Distortion parameters */
  {  /* MOVE.L	A2,A3 */
      uint32_t _mv = (uint32_t)(a2);
      a3 = _mv;
      flag_z = ((int32_t)(_mv) == 0);
      flag_n = ((int32_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  {  /* MOVE.W	(A3)+,D4 */
      uint16_t _mv = (uint16_t)(READ16_POST(a3));
      W(d4) = (uint16_t)_mv;
      flag_z = ((int16_t)(_mv) == 0);
      flag_n = ((int16_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  /* Modulation wave */
  {  /* MOVE.L	A6,A1 */
      uint32_t _mv = (uint32_t)(a6);
      a1 = _mv;
      flag_z = ((int32_t)(_mv) == 0);
      flag_n = ((int32_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  {  /* MOVE.W	D6,D2 */
      uint16_t _mv = (uint16_t)(W(d6));
      W(d2) = (uint16_t)_mv;
      flag_z = ((int16_t)(_mv) == 0);
      flag_n = ((int16_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  {  /* MOVE.L	(A1)+,D0 */
      uint32_t _mv = (uint32_t)(READ32_POST(a1));
      d0 = _mv;
      flag_z = ((int32_t)(_mv) == 0);
      flag_n = ((int32_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  d0 >>= 2;  /* LSR.L	#2,D0 */
  {  /* MOVE.W	D0,D1 */
      uint16_t _mv = (uint16_t)(W(d0));
      W(d1) = (uint16_t)_mv;
      flag_z = ((int16_t)(_mv) == 0);
      flag_n = ((int16_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  d0 = (d0 >> 16) | (d0 << 16);  /* SWAP.W	D0 */
  d0 = (uint32_t)((uint16_t)(W(d2)) * (uint16_t)W(d0));  /* MULU.W	D2,D0 */
  d1 = (uint32_t)((uint16_t)(W(d2)) * (uint16_t)W(d1));  /* MULU.W	D2,D1 */
  W(d1) = (uint16_t)(0);  /* CLR.W	D1 */
  d1 = (d1 >> 16) | (d1 << 16);  /* SWAP.W	D1 */
  {  /* ADD.L	D1,D0 */
      uint32_t _ar = (uint32_t)(d0 + d1);
      d0 = (uint32_t)_ar;
      flag_z = ((int32_t)(_ar) == 0);
      flag_n = ((int32_t)(_ar) < 0);
    }
do {
  W(d0) = (uint16_t)((uint32_t)(W(d0)) >> 2);  /* LSR.W	#2,D0 */
  {  /* ADD.W	D0,D0 */
      uint16_t _ar = (uint16_t)(W(d0) + W(d0));
      W(d0) = (uint16_t)((uint16_t)_ar);
      flag_z = ((int16_t)(_ar) == 0);
      flag_n = ((int16_t)(_ar) < 0);
    }
  {  /* MOVE.W	0(A0),D0 */
      uint16_t _mv = (uint16_t)(READ16(a0 + 0 + (int16_t)W(d0)));
      W(d0) = (uint16_t)_mv;
      flag_z = ((int16_t)(_mv) == 0);
      flag_n = ((int16_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  {  /* SUB.W	#$1000,D4 — C=1 on borrow (68k SUB carry) */
      flag_c = (W(d4) < (uint16_t)0x1000u);
      uint16_t _sr = (uint16_t)(W(d4) - (uint16_t)(0x1000));
      W(d4) = (uint16_t)((uint16_t)_sr);
      flag_z = ((int16_t)(_sr) == 0);
      flag_n = ((int16_t)(_sr) < 0);
    }
} while (!flag_c);
  W(d4) = (uint16_t)(W(d4) << 4);  /* LSL.W	#4,D4 */
  /* Modulation strength */
  {  /* MOVE.W	D0,D2 */
      uint16_t _mv = (uint16_t)(W(d0));
      W(d2) = (uint16_t)_mv;
      flag_z = ((int16_t)(_mv) == 0);
      flag_n = ((int16_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  {  /* ADD.W	#$8000,D2 */
      uint16_t _ar = (uint16_t)(W(d2) + 0x8000);
      W(d2) = (uint16_t)((uint16_t)_ar);
      flag_z = ((int16_t)(_ar) == 0);
      flag_n = ((int16_t)(_ar) < 0);
    }
  {  /* MOVE.L	(A1),D3 */
      uint32_t _mv = (uint32_t)(READ32(a1));
      d3 = _mv;
      flag_z = ((int32_t)(_mv) == 0);
      flag_n = ((int32_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  d3 >>= 3;  /* LSR.L	#3,D3 */
  {  /* MOVE.L	(A1)+,D0 */
      uint32_t _mv = (uint32_t)(READ32_POST(a1));
      d0 = _mv;
      flag_z = ((int32_t)(_mv) == 0);
      flag_n = ((int32_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  d0 >>= 2;  /* LSR.L	#2,D0 */
  {  /* MOVE.W	D0,D1 */
      uint16_t _mv = (uint16_t)(W(d0));
      W(d1) = (uint16_t)_mv;
      flag_z = ((int16_t)(_mv) == 0);
      flag_n = ((int16_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  d0 = (d0 >> 16) | (d0 << 16);  /* SWAP.W	D0 */
  d0 = (uint32_t)((uint16_t)(W(d2)) * (uint16_t)W(d0));  /* MULU.W	D2,D0 */
  d1 = (uint32_t)((uint16_t)(W(d2)) * (uint16_t)W(d1));  /* MULU.W	D2,D1 */
  W(d1) = (uint16_t)(0);  /* CLR.W	D1 */
  d1 = (d1 >> 16) | (d1 << 16);  /* SWAP.W	D1 */
  {  /* ADD.L	D1,D0 */
      uint32_t _ar = (uint32_t)(d0 + d1);
      d0 = (uint32_t)_ar;
      flag_z = ((int32_t)(_ar) == 0);
      flag_n = ((int32_t)(_ar) < 0);
    }
  {  /* SUB.L	D0,D3 */
      uint32_t _sr = (uint32_t)(d3 - d0);
      d3 = (uint32_t)_sr;
      flag_z = ((int32_t)(_sr) == 0);
      flag_n = ((int32_t)(_sr) < 0);
    }
  /* Base wave */
  {  /* MOVE.W	D6,D2 */
      uint16_t _mv = (uint16_t)(W(d6));
      W(d2) = (uint16_t)_mv;
      flag_z = ((int16_t)(_mv) == 0);
      flag_n = ((int16_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  {  /* MOVE.L	(A1)+,D0 */
      uint32_t _mv = (uint32_t)(READ32_POST(a1));
      d0 = _mv;
      flag_z = ((int32_t)(_mv) == 0);
      flag_n = ((int32_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  d0 >>= 2;  /* LSR.L	#2,D0 */
  {  /* MOVE.W	D0,D1 */
      uint16_t _mv = (uint16_t)(W(d0));
      W(d1) = (uint16_t)_mv;
      flag_z = ((int16_t)(_mv) == 0);
      flag_n = ((int16_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  d0 = (d0 >> 16) | (d0 << 16);  /* SWAP.W	D0 */
  d0 = (uint32_t)((uint16_t)(W(d2)) * (uint16_t)W(d0));  /* MULU.W	D2,D0 */
  d1 = (uint32_t)((uint16_t)(W(d2)) * (uint16_t)W(d1));  /* MULU.W	D2,D1 */
  W(d1) = (uint16_t)(0);  /* CLR.W	D1 */
  d1 = (d1 >> 16) | (d1 << 16);  /* SWAP.W	D1 */
  {  /* ADD.L	D1,D0 */
      uint32_t _ar = (uint32_t)(d0 + d1);
      d0 = (uint32_t)_ar;
      flag_z = ((int32_t)(_ar) == 0);
      flag_n = ((int32_t)(_ar) < 0);
    }
  {  /* SUB.L	D3,D0 */
      uint32_t _sr = (uint32_t)(d0 - d3);
      d0 = (uint32_t)_sr;
      flag_z = ((int32_t)(_sr) == 0);
      flag_n = ((int32_t)(_sr) < 0);
    }
do {
  W(d0) = (uint16_t)((uint32_t)(W(d0)) >> 2);  /* LSR.W	#2,D0 */
  {  /* ADD.W	D0,D0 */
      uint16_t _ar = (uint16_t)(W(d0) + W(d0));
      W(d0) = (uint16_t)((uint16_t)_ar);
      flag_z = ((int16_t)(_ar) == 0);
      flag_n = ((int16_t)(_ar) < 0);
    }
  {  /* MOVE.W	0(A0),D0 */
      uint16_t _mv = (uint16_t)(READ16(a0 + 0 + (int16_t)W(d0)));
      W(d0) = (uint16_t)_mv;
      flag_z = ((int16_t)(_mv) == 0);
      flag_n = ((int16_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  {  /* SUB.W	#$1000,D4 — C=1 on borrow (68k SUB carry) */
      flag_c = (W(d4) < (uint16_t)0x1000u);
      uint16_t _sr = (uint16_t)(W(d4) - (uint16_t)(0x1000));
      W(d4) = (uint16_t)((uint16_t)_sr);
      flag_z = ((int16_t)(_sr) == 0);
      flag_n = ((int16_t)(_sr) < 0);
    }
} while (!flag_c);
  W(d4) = (uint16_t)(W(d4) << 4);  /* LSL.W	#4,D4 */
  /* Amplitude */
  {  /* MOVE.W	(A1)+,D1 */
      uint16_t _mv = (uint16_t)(READ16_POST(a1));
      W(d1) = (uint16_t)_mv;
      flag_z = ((int16_t)(_mv) == 0);
      flag_n = ((int16_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
do {
  d0 = (uint32_t)((int32_t)(int16_t)READ16(a1 + 0) * (int32_t)(int16_t)W(d0));  /* MULS.W	0(A1),D0 */
  {  /* ADD.L	D0,D0 */
      uint32_t _ar = (uint32_t)(d0 + d0);
      d0 = (uint32_t)_ar;
      flag_z = ((int32_t)(_ar) == 0);
      flag_n = ((int32_t)(_ar) < 0);
    }
  d0 = (d0 >> 16) | (d0 << 16);  /* SWAP.W	D0 */
  {  /* SUB.W	#$1000,D4 — C=1 on borrow (68k SUB carry) */
      flag_c = (W(d4) < (uint16_t)0x1000u);
      uint16_t _sr = (uint16_t)(W(d4) - (uint16_t)(0x1000));
      W(d4) = (uint16_t)((uint16_t)_sr);
      flag_z = ((int16_t)(_sr) == 0);
      flag_n = ((int16_t)(_sr) < 0);
    }
} while (!flag_c);
  W(d4) = (uint16_t)(W(d4) << 4);  /* LSL.W	#4,D4 */
  /* Final distortion */
  goto _fdist_in;  /* BRA.B	.fdist_in */
_fdist:
  W(d0) = (uint16_t)((uint32_t)(W(d0)) >> 2);  /* LSR.W	#2,D0 */
  {  /* ADD.W	D0,D0 */
      uint16_t _ar = (uint16_t)(W(d0) + W(d0));
      W(d0) = (uint16_t)((uint16_t)_ar);
      flag_z = ((int16_t)(_ar) == 0);
      flag_n = ((int16_t)(_ar) < 0);
    }
  {  /* MOVE.W	0(A0),D0 */
      uint16_t _mv = (uint16_t)(READ16(a0 + 0 + (int16_t)W(d0)));
      W(d0) = (uint16_t)_mv;
      flag_z = ((int16_t)(_mv) == 0);
      flag_n = ((int16_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
_fdist_in:
  {  /* SUB.W	#$1000,D4 — C=1 on borrow (68k SUB carry) */
      flag_c = (W(d4) < (uint16_t)0x1000u);
      uint16_t _sr = (uint16_t)(W(d4) - (uint16_t)(0x1000));
      W(d4) = (uint16_t)((uint16_t)_sr);
      flag_z = ((int16_t)(_sr) == 0);
      flag_n = ((int16_t)(_sr) < 0);
    }
  if (!flag_c) goto _fdist;  /* carry clear / above-or-equal */  /* BCC.B	.fdist */
  /* Write sample */
  {  /* ADD.W	D0,D0 — must set V: the following BVC saturates on signed overflow */
      uint16_t _a  = (uint16_t)W(d0);
      uint16_t _ar = (uint16_t)(_a + _a);
      flag_v = (((_a ^ _ar) >> 15) & 1);  /* signed overflow of a+a */
      W(d0) = (uint16_t)((uint16_t)_ar);
      flag_z = ((int16_t)(_ar) == 0);
      flag_n = ((int16_t)(_ar) < 0);
    }
  if (flag_v) {
  {  /* SUBQ.W	#1,D0 */
      uint16_t _sr = (uint16_t)(W(d0) - (uint16_t)(1));
      W(d0) = (uint16_t)((uint16_t)_sr);
      flag_z = ((int16_t)(_sr) == 0);
      flag_n = ((int16_t)(_sr) < 0);
    }
  }
  W(d0) = (uint16_t)((uint32_t)((int32_t)W(d0) >> 8));  /* ASR.W	#8,D0 */
  {  /* MOVE.B	D0,(A4)+ */
      uint8_t _mv = (uint8_t)(B(d0));
      WRITE8_POST(a4, _mv);
      flag_z = ((int8_t)(_mv) == 0);
      flag_n = ((int8_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  /* Attack-Decay */
  {  /* MOVE.W	(A3)+,D2 */
      uint16_t _mv = (uint16_t)(READ16_POST(a3));
      W(d2) = (uint16_t)_mv;
      flag_z = ((int16_t)(_mv) == 0);
      flag_n = ((int16_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  {  /* SUB.W	D1,(A1) — must set V for the following BVC (amplitude clamp) */
      uint16_t _a  = (uint16_t)READ16(a1);
      uint16_t _b  = (uint16_t)W(d1);
      uint16_t _sr = (uint16_t)(_a - _b);
      flag_v = ((((_a ^ _b) & (_a ^ _sr)) >> 15) & 1);  /* signed overflow of a-b */
      hw_write16(a1, (uint16_t)_sr);
      flag_z = ((int16_t)(_sr) == 0);
      flag_n = ((int16_t)(_sr) < 0);
    }
  if (flag_v) {
  {  /* MOVE.W	#32767,(A1) */
      uint16_t _mv = (uint16_t)(32767);
      hw_write16(a1, _mv);
      flag_z = ((int16_t)(_mv) == 0);
      flag_n = ((int16_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  {  /* MOVE.W	D2,-(A1) */
      uint16_t _mv = (uint16_t)(W(d2));
      WRITE16_PRE(a1, _mv);
      flag_z = ((int16_t)(_mv) == 0);
      flag_n = ((int16_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  }
  if (flag_n) {
  hw_write16(a1, 0);  /* CLR.W	(A1) */
  }
  /* Pitch and mod decays */
  {  /* MOVE.L	A6,A1 */
      uint32_t _mv = (uint32_t)(a6);
      a1 = _mv;
      flag_z = ((int32_t)(_mv) == 0);
      flag_n = ((int32_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  {  /* MOVE.L	(A1),D0 */
      uint32_t _mv = (uint32_t)(READ32(a1));
      d0 = _mv;
      flag_z = ((int32_t)(_mv) == 0);
      flag_n = ((int32_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  {  /* MOVE.W	(A3)+,D2 */
      uint16_t _mv = (uint16_t)(READ16_POST(a3));
      W(d2) = (uint16_t)_mv;
      flag_z = ((int16_t)(_mv) == 0);
      flag_n = ((int16_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  if (flag_z) goto _pc_off_01a0;  /* equal / zero */  /* BEQ.B	_pc_off_01a0 */
  {  /* MOVE.W	D0,D1 */
      uint16_t _mv = (uint16_t)(W(d0));
      W(d1) = (uint16_t)_mv;
      flag_z = ((int16_t)(_mv) == 0);
      flag_n = ((int16_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  d0 = (d0 >> 16) | (d0 << 16);  /* SWAP.W	D0 */
  d0 = (uint32_t)((uint16_t)(W(d2)) * (uint16_t)W(d0));  /* MULU.W	D2,D0 */
  d1 = (uint32_t)((uint16_t)(W(d2)) * (uint16_t)W(d1));  /* MULU.W	D2,D1 */
  W(d1) = (uint16_t)(0);  /* CLR.W	D1 */
  d1 = (d1 >> 16) | (d1 << 16);  /* SWAP.W	D1 */
  {  /* ADD.L	D1,D0 */
      uint32_t _ar = (uint32_t)(d0 + d1);
      d0 = (uint32_t)_ar;
      flag_z = ((int32_t)(_ar) == 0);
      flag_n = ((int32_t)(_ar) < 0);
    }
  {  /* TST.W	D2 */
      uint16_t _tst = (uint16_t)(W(d2));
      flag_z = (_tst == 0);
      flag_n = ((int16_t)(_tst) < 0);
      flag_c = 0; flag_v = 0;
    }
  if (flag_n) goto _pc_off_01a0;  /* minus / negative */  /* BMI.B	_pc_off_01a0 */
  {  /* ADD.L	(A1),D0 */
      uint32_t _ar = (uint32_t)(d0 + READ32(a1));
      d0 = (uint32_t)_ar;
      flag_z = ((int32_t)(_ar) == 0);
      flag_n = ((int32_t)(_ar) < 0);
    }
_pc_off_01a0:
  {  /* MOVE.L	D0,(A1)+ */
      uint32_t _mv = (uint32_t)(d0);
      WRITE32_POST(a1, _mv);
      flag_z = ((int32_t)(_mv) == 0);
      flag_n = ((int32_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  {  /* MOVE.L	(A1),D0 */
      uint32_t _mv = (uint32_t)(READ32(a1));
      d0 = _mv;
      flag_z = ((int32_t)(_mv) == 0);
      flag_n = ((int32_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  {  /* MOVE.W	(A3)+,D2 */
      uint16_t _mv = (uint16_t)(READ16_POST(a3));
      W(d2) = (uint16_t)_mv;
      flag_z = ((int16_t)(_mv) == 0);
      flag_n = ((int16_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  if (flag_z) goto _pc_off_01bc;  /* equal / zero */  /* BEQ.B	_pc_off_01bc */
  {  /* MOVE.W	D0,D1 */
      uint16_t _mv = (uint16_t)(W(d0));
      W(d1) = (uint16_t)_mv;
      flag_z = ((int16_t)(_mv) == 0);
      flag_n = ((int16_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  d0 = (d0 >> 16) | (d0 << 16);  /* SWAP.W	D0 */
  d0 = (uint32_t)((uint16_t)(W(d2)) * (uint16_t)W(d0));  /* MULU.W	D2,D0 */
  d1 = (uint32_t)((uint16_t)(W(d2)) * (uint16_t)W(d1));  /* MULU.W	D2,D1 */
  W(d1) = (uint16_t)(0);  /* CLR.W	D1 */
  d1 = (d1 >> 16) | (d1 << 16);  /* SWAP.W	D1 */
  {  /* ADD.L	D1,D0 */
      uint32_t _ar = (uint32_t)(d0 + d1);
      d0 = (uint32_t)_ar;
      flag_z = ((int32_t)(_ar) == 0);
      flag_n = ((int32_t)(_ar) < 0);
    }
  {  /* TST.W	D2 */
      uint16_t _tst = (uint16_t)(W(d2));
      flag_z = (_tst == 0);
      flag_n = ((int16_t)(_tst) < 0);
      flag_c = 0; flag_v = 0;
    }
  if (flag_n) goto _pc_off_01bc;  /* minus / negative */  /* BMI.B	_pc_off_01bc */
  {  /* ADD.L	(A1),D0 */
      uint32_t _ar = (uint32_t)(d0 + READ32(a1));
      d0 = (uint32_t)_ar;
      flag_z = ((int32_t)(_ar) == 0);
      flag_n = ((int32_t)(_ar) < 0);
    }
_pc_off_01bc:
  {  /* MOVE.L	D0,(A1)+ */
      uint32_t _mv = (uint32_t)(d0);
      WRITE32_POST(a1, _mv);
      flag_z = ((int32_t)(_mv) == 0);
      flag_n = ((int32_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  {  /* MOVE.L	(A1),D0 */
      uint32_t _mv = (uint32_t)(READ32(a1));
      d0 = _mv;
      flag_z = ((int32_t)(_mv) == 0);
      flag_n = ((int32_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  {  /* MOVE.W	(A3)+,D2 */
      uint16_t _mv = (uint16_t)(READ16_POST(a3));
      W(d2) = (uint16_t)_mv;
      flag_z = ((int16_t)(_mv) == 0);
      flag_n = ((int16_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  if (flag_z) goto _pc_off_01d8;  /* equal / zero */  /* BEQ.B	_pc_off_01d8 */
  {  /* MOVE.W	D0,D1 */
      uint16_t _mv = (uint16_t)(W(d0));
      W(d1) = (uint16_t)_mv;
      flag_z = ((int16_t)(_mv) == 0);
      flag_n = ((int16_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  d0 = (d0 >> 16) | (d0 << 16);  /* SWAP.W	D0 */
  d0 = (uint32_t)((uint16_t)(W(d2)) * (uint16_t)W(d0));  /* MULU.W	D2,D0 */
  d1 = (uint32_t)((uint16_t)(W(d2)) * (uint16_t)W(d1));  /* MULU.W	D2,D1 */
  W(d1) = (uint16_t)(0);  /* CLR.W	D1 */
  d1 = (d1 >> 16) | (d1 << 16);  /* SWAP.W	D1 */
  {  /* ADD.L	D1,D0 */
      uint32_t _ar = (uint32_t)(d0 + d1);
      d0 = (uint32_t)_ar;
      flag_z = ((int32_t)(_ar) == 0);
      flag_n = ((int32_t)(_ar) < 0);
    }
  {  /* TST.W	D2 */
      uint16_t _tst = (uint16_t)(W(d2));
      flag_z = (_tst == 0);
      flag_n = ((int16_t)(_tst) < 0);
      flag_c = 0; flag_v = 0;
    }
  if (flag_n) goto _pc_off_01d8;  /* minus / negative */  /* BMI.B	_pc_off_01d8 */
  {  /* ADD.L	(A1),D0 */
      uint32_t _ar = (uint32_t)(d0 + READ32(a1));
      d0 = (uint32_t)_ar;
      flag_z = ((int32_t)(_ar) == 0);
      flag_n = ((int32_t)(_ar) < 0);
    }
_pc_off_01d8:
  {  /* MOVE.L	D0,(A1)+ */
      uint32_t _mv = (uint32_t)(d0);
      WRITE32_POST(a1, _mv);
      flag_z = ((int32_t)(_mv) == 0);
      flag_n = ((int32_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  {  /* ADDQ.L	#1,D6 */
      uint32_t _ar = (uint32_t)(d6 + 1);
      d6 = (uint32_t)_ar;
      flag_z = ((int32_t)(_ar) == 0);
      flag_n = ((int32_t)(_ar) < 0);
    }
  {  /* CMP.L	D5,D6 — must set V for the following BLT (flag_n!=flag_v) */
      int32_t _lhs = (int32_t)(d6);
      int32_t _rhs = (int32_t)(d5);
      int32_t _cmp = _lhs - _rhs;
      uint32_t _va=d6, _vb=d5, _vr=_va-_vb;
      flag_v = (((_va ^ _vb) & (_va ^ _vr)) >> 31) & 1;
      flag_z = (_cmp == 0);
      flag_n = (_cmp < 0);
      flag_c = ((uint32_t)_lhs < (uint32_t)_rhs);
    }
  if (flag_n!=flag_v) goto _sampleloop;  /* less than (signed) */  /* BLT.W	.sampleloop */
  {  /* MOVE.L	A3,A2 */
      uint32_t _mv = (uint32_t)(a3);
      a2 = _mv;
      flag_z = ((int32_t)(_mv) == 0);
      flag_n = ((int32_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  if ((int16_t)(--d7) >= 0) goto _instrumentloop;  /* DBF	D7,.instrumentloop */
CinterComputePeriods:
  a1 = (uint32_t)(a6 + (intptr_t)c_PeriodTable);  /* LEA c_PeriodTable(A6),A1 — was emitted as stub */
  {  /* MOVE.W	#$e2b3,D0 */
      uint16_t _mv = (uint16_t)(0xe2b3);
      W(d0) = (uint16_t)_mv;
      flag_z = ((int16_t)(_mv) == 0);
      flag_n = ((int16_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  {  /* MOVE.L	#$0fc0fd20,D2 */
      uint32_t _mv = (uint32_t)(0x0fc0fd20);
      d2 = _mv;
      flag_z = ((int32_t)(_mv) == 0);
      flag_n = ((int32_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  d6 = (uint32_t)(int32_t)(int8_t)(0);  /* MOVEQ.L	#0,D6 */
  for (int _i_d7 = 36; _i_d7 >= 0; _i_d7--) {
  d0 = (uint32_t)((uint16_t)(61865) * (uint16_t)W(d0));  /* MULU.W	#61865,D0 */
  d0 = (d0 >> 16) | (d0 << 16);  /* SWAP.W	D0 */
  {  /* MOVE.W	D0,D1 */
      uint16_t _mv = (uint16_t)(W(d0));
      W(d1) = (uint16_t)_mv;
      flag_z = ((int16_t)(_mv) == 0);
      flag_n = ((int16_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  W(d1) = (uint16_t)((uint32_t)(W(d1)) >> 6);  /* LSR.W	#6,D1 */
  {  /* ADD.L	D2,D2 */
      uint32_t _ar = (uint32_t)(d2 + d2);
      d2 = (uint32_t)_ar;
      flag_z = ((int32_t)(_ar) == 0);
      flag_n = ((int32_t)(_ar) < 0);
    }
  W(d1) = (uint16_t)(W(d1) - W(d6) - flag_x);  /* SUBX.W	D6,D1 */
  {  /* MOVE.W	D1,(A1)+ */
      uint16_t _mv = (uint16_t)(W(d1));
      WRITE16_POST(a1, _mv);
      flag_z = ((int16_t)(_mv) == 0);
      flag_n = ((int16_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
}
CinterParseMusic:
  a1 = (uint32_t)(a6 + (intptr_t)c_TrackSize);  /* LEA c_TrackSize(A6),A1 — was emitted as stub */
  {  /* MOVE.W	(A2)+,D1 */
      uint16_t _mv = (uint16_t)(READ16_POST(a2));
      W(d1) = (uint16_t)_mv;
      flag_z = ((int16_t)(_mv) == 0);
      flag_n = ((int16_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  {  /* MOVE.W	(A2)+,D0 */
      uint16_t _mv = (uint16_t)(READ16_POST(a2));
      W(d0) = (uint16_t)_mv;
      flag_z = ((int16_t)(_mv) == 0);
      flag_n = ((int16_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  {  /* MOVE.W	D1,(A1)+ */
      uint16_t _mv = (uint16_t)(W(d1));
      WRITE16_POST(a1, _mv);
      flag_z = ((int16_t)(_mv) == 0);
      flag_n = ((int16_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  {  /* MOVE.L	A2,(A1)+ */
      uint32_t _mv = (uint32_t)(a2);
      WRITE32_POST(a1, _mv);
      flag_z = ((int32_t)(_mv) == 0);
      flag_n = ((int32_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  a2 = (uint32_t)((int32_t)a2 + (int32_t)(int16_t)(W(d0)));  /* ADD.W	D0,A2 */
  {  /* MOVE.L	A2,(A1)+ */
      uint32_t _mv = (uint32_t)(a2);
      WRITE32_POST(a1, _mv);
      flag_z = ((int32_t)(_mv) == 0);
      flag_n = ((int32_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  {  /* MOVE.W	-(A2),D0 */
      uint16_t _mv = (uint16_t)(READ16_PRE(a2));
      W(d0) = (uint16_t)_mv;
      flag_z = ((int16_t)(_mv) == 0);
      flag_n = ((int16_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  a2 = (uint32_t)((int32_t)a2 + (int32_t)(int16_t)(W(d1)));  /* ADD.W	D1,A2 */
  {  /* MOVE.L	A2,(A1)+ */
      uint32_t _mv = (uint32_t)(a2);
      WRITE32_POST(a1, _mv);
      flag_z = ((int32_t)(_mv) == 0);
      flag_n = ((int32_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  a2 = (uint32_t)((int32_t)a2 + (int32_t)(int16_t)(W(d0)));  /* ADD.W	D0,A2 */
  {  /* MOVE.L	A2,(A1)+ */
      uint32_t _mv = (uint32_t)(a2);
      WRITE32_POST(a1, _mv);
      flag_z = ((int32_t)(_mv) == 0);
      flag_n = ((int32_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
CinterInitEnd:
  return;  /* RTS */
}


/* --- CinterPlay1 ---  (PUBLIC) */
void CinterPlay1(void) {
_top: ;
  /* A6 = Cinter working memory */
  /* No filter! */
  /* hw $bfe001 */ (void)(READ8(0xbfe001) | (1u << (1 & 31)));  /* BSET.B	#1,$BFE001 */
  /* Read music data */
  a3 = (uint32_t)0xdff000;  /* LEA.L	$DFF000,A3 */
  a0 = (uint32_t)(a6 + (intptr_t)c_TrackSize);  /* LEA	c_TrackSize(A6),A0 */
  {  /* MOVE.W	(A0)+,D1 */
      uint16_t _mv = (uint16_t)(READ16_POST(a0));
      W(d1) = (uint16_t)_mv;
      flag_z = ((int16_t)(_mv) == 0);
      flag_n = ((int16_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  {  /* MOVE.L	(A0)+,A2 */
      uint32_t _mv = (uint32_t)(READ32_POST(a0));
      a2 = _mv;
      flag_z = ((int32_t)(_mv) == 0);
      flag_n = ((int32_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  {  /* MOVE.L	(A0)+,A1 */
      uint32_t _mv = (uint32_t)(READ32_POST(a0));
      a1 = _mv;
      flag_z = ((int32_t)(_mv) == 0);
      flag_n = ((int32_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  /* Loop when end is reached */
  {  /* CMP.L	(A0)+,A1 */
      int32_t _lhs = (int32_t)(a1);
      int32_t _rhs = (int32_t)(READ32_POST(a0));
      int32_t _cmp = _lhs - _rhs;
      flag_z = (_cmp == 0);
      flag_n = (_cmp < 0);
      flag_c = ((uint32_t)_lhs < (uint32_t)_rhs);
    }
  if (!(flag_c||flag_z)) {
  {  /* MOVE.L	(A0),A1 */
      uint32_t _mv = (uint32_t)(READ32(a0));
      a1 = _mv;
      flag_z = ((int32_t)(_mv) == 0);
      flag_n = ((int32_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  {  /* MOVE.L	A1,-8(A0) */
      uint32_t _mv = (uint32_t)(a1);
      hw_write32(a0 + -8, _mv);
      flag_z = ((int32_t)(_mv) == 0);
      flag_n = ((int32_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  }
  /* Turn off DMA for triggered channels */
  d0 = (uint32_t)(int32_t)(int8_t)(0);  /* MOVEQ.L	#0,D0 */
  {  /* MOVE.W	(A1),D2 */
      uint16_t _mv = (uint16_t)(READ16(a1));
      W(d2) = (uint16_t)_mv;
      flag_z = ((int16_t)(_mv) == 0);
      flag_n = ((int16_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  a1 = (uint32_t)((int32_t)a1 + (int32_t)(int16_t)(W(d1)));  /* ADD.W	D1,A1 */
  {  /* ADD.W	D2,D2 — carry (→X) = old bit 15 of D2 */
      flag_c = flag_x = (W(d2) >> 15) & 1;
      uint16_t _ar = (uint16_t)(W(d2) + W(d2));
      W(d2) = (uint16_t)((uint16_t)_ar);
      flag_z = ((int16_t)(_ar) == 0);
      flag_n = ((int16_t)(_ar) < 0);
    }
  W(d0) = (uint16_t)(W(d0) + W(d0) + flag_x);  /* ADDX.W	D0,D0 */
  {  /* MOVE.W	(A1),D2 */
      uint16_t _mv = (uint16_t)(READ16(a1));
      W(d2) = (uint16_t)_mv;
      flag_z = ((int16_t)(_mv) == 0);
      flag_n = ((int16_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  a1 = (uint32_t)((int32_t)a1 + (int32_t)(int16_t)(W(d1)));  /* ADD.W	D1,A1 */
  {  /* ADD.W	D2,D2 — carry (→X) = old bit 15 of D2 */
      flag_c = flag_x = (W(d2) >> 15) & 1;
      uint16_t _ar = (uint16_t)(W(d2) + W(d2));
      W(d2) = (uint16_t)((uint16_t)_ar);
      flag_z = ((int16_t)(_ar) == 0);
      flag_n = ((int16_t)(_ar) < 0);
    }
  W(d0) = (uint16_t)(W(d0) + W(d0) + flag_x);  /* ADDX.W	D0,D0 */
  {  /* MOVE.W	(A1),D2 */
      uint16_t _mv = (uint16_t)(READ16(a1));
      W(d2) = (uint16_t)_mv;
      flag_z = ((int16_t)(_mv) == 0);
      flag_n = ((int16_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  a1 = (uint32_t)((int32_t)a1 + (int32_t)(int16_t)(W(d1)));  /* ADD.W	D1,A1 */
  {  /* ADD.W	D2,D2 — carry (→X) = old bit 15 of D2 */
      flag_c = flag_x = (W(d2) >> 15) & 1;
      uint16_t _ar = (uint16_t)(W(d2) + W(d2));
      W(d2) = (uint16_t)((uint16_t)_ar);
      flag_z = ((int16_t)(_ar) == 0);
      flag_n = ((int16_t)(_ar) < 0);
    }
  W(d0) = (uint16_t)(W(d0) + W(d0) + flag_x);  /* ADDX.W	D0,D0 */
  {  /* MOVE.W	(A1),D2 */
      uint16_t _mv = (uint16_t)(READ16(a1));
      W(d2) = (uint16_t)_mv;
      flag_z = ((int16_t)(_mv) == 0);
      flag_n = ((int16_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  a1 = (uint32_t)((int32_t)a1 + (int32_t)(int16_t)(W(d1)));  /* ADD.W	D1,A1 */
  {  /* ADD.W	D2,D2 — carry (→X) = old bit 15 of D2 */
      flag_c = flag_x = (W(d2) >> 15) & 1;
      uint16_t _ar = (uint16_t)(W(d2) + W(d2));
      W(d2) = (uint16_t)((uint16_t)_ar);
      flag_z = ((int16_t)(_ar) == 0);
      flag_n = ((int16_t)(_ar) < 0);
    }
  W(d0) = (uint16_t)(W(d0) + W(d0) + flag_x);  /* ADDX.W	D0,D0 — 4th channel; transpiler dropped this, silencing one voice */
  {  /* MOVE.W	D0,150(A3) */
      uint16_t _mv = (uint16_t)(W(d0));
      hw_write16(a3 + 150, _mv);
      flag_z = ((int16_t)(_mv) == 0);
      flag_n = ((int16_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  /* Save line and dma */
  {  /* MOVE.W	6(A3),D1 */
      uint16_t _mv = (uint16_t)(READ16(a3 + 6));
      W(d1) = (uint16_t)_mv;
      flag_z = ((int16_t)(_mv) == 0);
      flag_n = ((int16_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  /* MOVEM.W D0/D1,c_dma-c_MusicLoop(A0): save DMA mask + wait-line to working memory.
   * A0 = a6+c_MusicLoop (100), so destination = a6+c_dma (152) and a6+c_waitline (154).
   * Without this, CinterPlay2 reads 0 from c_dma → skips DMACON write → Paula silent. */
  WRITE16(a6 + c_dma, W(d0));
  WRITE16(a6 + c_waitline, W(d1));
  return;  /* RTS */
}


/* --- CinterPlay2 ---  (PUBLIC) */
void CinterPlay2(void) {
_top: ;
  /* A6 = Cinter working memory */
  /* Advance position */
  a3 = (uint32_t)0xdff000;  /* LEA.L	$DFF000,A3 */
  a0 = (uint32_t)(a6 + (intptr_t)c_TrackSize);  /* LEA	c_TrackSize(A6),A0 */
  {  /* MOVE.W	(A0)+,D1 */
      uint16_t _mv = (uint16_t)(READ16_POST(a0));
      W(d1) = (uint16_t)_mv;
      flag_z = ((int16_t)(_mv) == 0);
      flag_n = ((int16_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  {  /* MOVE.L	(A0)+,A2 */
      uint32_t _mv = (uint32_t)(READ32_POST(a0));
      a2 = _mv;
      flag_z = ((int32_t)(_mv) == 0);
      flag_n = ((int32_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  {  /* MOVE.L	(A0),A1 */
      uint32_t _mv = (uint32_t)(READ32(a0));
      a1 = _mv;
      flag_z = ((int32_t)(_mv) == 0);
      flag_n = ((int32_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  {  /* ADDQ.L	#2,(A0)+ */
      /* Fix: read-modify-write at SAME address, then increment once */
      uint32_t _ar = (uint32_t)(READ32(a0) + 2);
      WRITE32(a0, _ar);
      a0 += 4;
      flag_z = ((int32_t)(_ar) == 0);
      flag_n = ((int32_t)(_ar) < 0);
    }
  a0 = (uint32_t)((int32_t)a0 + (int32_t)(int16_t)(8));  /* ADDQ.L	#8,A0 */
  /* Write to audio registers */
  a3 = (uint32_t)(a3 + 224);  /* LEA.L	224(A3),A3 */
  d5 = 0;  /* CLR.L	D5 */
  for (int _i_d7 = 3; _i_d7 >= 0; _i_d7--) {
  {  /* MOVE.L	(A0)+,D3 */
      uint32_t _mv = (uint32_t)(READ32_POST(a0));
      d3 = _mv;
      flag_z = ((int32_t)(_mv) == 0);
      flag_n = ((int32_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  {  /* MOVE.L	(A0)+,A4 */
      uint32_t _mv = (uint32_t)(READ32_POST(a0));
      a4 = _mv;
      flag_z = ((int32_t)(_mv) == 0);
      flag_n = ((int32_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  {  /* MOVE.L	(A0),D2 */
      uint32_t _mv = (uint32_t)(READ32(a0));
      d2 = _mv;
      flag_z = ((int32_t)(_mv) == 0);
      flag_n = ((int32_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  {  /* MOVE.W	(A1),D0 */
      uint16_t _mv = (uint16_t)(READ16(a1));
      W(d0) = (uint16_t)_mv;
      flag_z = ((int16_t)(_mv) == 0);
      flag_n = ((int16_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  a1 = (uint32_t)((int32_t)a1 + (int32_t)(int16_t)(W(d1)));  /* ADD.W	D1,A1 */
  if (!(flag_n)) {
  /* Adjust volume */
  W(d0) = ROL16(W(d0), 7);  /* ROL.W	#7,D0 */
  {  /* ADD.W	D0,D2 */
      uint16_t _ar = (uint16_t)(W(d2) + W(d0));
      W(d2) = (uint16_t)((uint16_t)_ar);
      flag_z = ((int16_t)(_ar) == 0);
      flag_n = ((int16_t)(_ar) < 0);
    }
  W(d2) &= (uint16_t)(63);  /* AND.W	#63,D2 */
  d2 = (d2 >> 16) | (d2 << 16);  /* SWAP.W	D2 */
  /* Adjust or set period */
  W(d0) = (uint16_t)((uint32_t)((int32_t)W(d0) >> 7));  /* ASR.W	#7,D0 */
  {  /* ADD.W	D0,D2 */
      uint16_t _ar = (uint16_t)(W(d2) + W(d0));
      W(d2) = (uint16_t)((uint16_t)_ar);
      flag_z = ((int16_t)(_ar) == 0);
      flag_n = ((int16_t)(_ar) < 0);
    }
  {  /* ADD.B	D0,D0 — must set V: the following BVC/BVS clamps the note period
        (slide vs period-table lookup); a stale V gives the wrong pitch. */
      uint8_t _a  = B(d0);
      uint8_t _ar = (uint8_t)(_a + _a);
      flag_v = (((_a ^ _ar) >> 7) & 1);  /* signed overflow of a+a (byte) */
      B(d0) = (uint8_t)((uint8_t)_ar);
      flag_z = ((int8_t)(_ar) == 0);
      flag_n = ((int8_t)(_ar) < 0);
    }
  if (flag_v) {
  {  /* MOVE.W	c_PeriodTable(A6),D2 */
      uint16_t _mv = (uint16_t)(READ16(a6 + (intptr_t)c_PeriodTable + (int16_t)W(d0)));
      W(d2) = (uint16_t)_mv;
      flag_z = ((int16_t)(_mv) == 0);
      flag_n = ((int16_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  }
  d2 = (d2 >> 16) | (d2 << 16);  /* SWAP.W	D2 */
  } else {
  /* Set volume */
  W(d0) = ROL16(W(d0), 7);  /* ROL.W	#7,D0 */
  {  /* MOVE.W	D0,D2 */
      uint16_t _mv = (uint16_t)(W(d0));
      W(d2) = (uint16_t)_mv;
      flag_z = ((int16_t)(_mv) == 0);
      flag_n = ((int16_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  W(d2) &= (uint16_t)(63);  /* AND.W	#63,D2 */
  d2 = (d2 >> 16) | (d2 << 16);  /* SWAP.W	D2 */
  /* Look up note */
  W(d0) = (uint16_t)((uint32_t)(W(d0)) >> 7);  /* LSR.W	#7,D0 */
  {  /* MOVE.L	A2,A5 */
      uint32_t _mv = (uint32_t)(a2);
      a5 = _mv;
      flag_z = ((int32_t)(_mv) == 0);
      flag_n = ((int32_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  d3 = (uint32_t)(int32_t)(int8_t)(-8);  /* MOVEQ.L	#-8,D3 */
  d4 = (uint32_t)(int32_t)(int8_t)(0);  /* MOVEQ.L	#0,D4 */
_noteloop:
  {  /* MOVE.B	(A5)+,D2 */
      uint8_t _mv = (uint8_t)(READ8_POST(a5));
      B(d2) = (uint8_t)_mv;
      flag_z = ((int8_t)(_mv) == 0);
      flag_n = ((int8_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  {  /* MOVE.B	(A5)+,D4 */
      uint8_t _mv = (uint8_t)(READ8_POST(a5));
      B(d4) = (uint8_t)_mv;
      flag_z = ((int8_t)(_mv) == 0);
      flag_n = ((int8_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  {  /* MOVE.W	(A5)+,D5 */
      uint16_t _mv = (uint16_t)(READ16_POST(a5));
      W(d5) = (uint16_t)_mv;
      flag_z = ((int16_t)(_mv) == 0);
      flag_n = ((int16_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  if (flag_z) {
  {  /* ADDQ.W	#8,D3 */
      uint16_t _ar = (uint16_t)(W(d3) + 8);
      W(d3) = (uint16_t)((uint16_t)_ar);
      flag_z = ((int16_t)(_ar) == 0);
      flag_n = ((int16_t)(_ar) < 0);
    }
  }
  {  /* SUB.W	D4,D0 — must set V: the following BGE (flag_n==flag_v) selects the
        note-range/instrument; a stale V picks the wrong instrument for notes whose
        subtraction overflows. */
      uint16_t _a  = (uint16_t)W(d0);
      uint16_t _b  = (uint16_t)W(d4);
      uint16_t _sr = (uint16_t)(_a - _b);
      flag_v = ((((_a ^ _b) & (_a ^ _sr)) >> 15) & 1);  /* signed overflow of a-b */
      W(d0) = (uint16_t)((uint16_t)_sr);
      flag_z = ((int16_t)(_sr) == 0);
      flag_n = ((int16_t)(_sr) < 0);
    }
  if (flag_n==flag_v) goto _noteloop;  /* greater or equal (signed) */  /* BGE.B	.noteloop */
  {  /* ADD.W	D4,D0 */
      uint16_t _ar = (uint16_t)(W(d0) + W(d4));
      W(d0) = (uint16_t)((uint16_t)_ar);
      flag_z = ((int16_t)(_ar) == 0);
      flag_n = ((int16_t)(_ar) < 0);
    }
  {  /* ADD.B	D2,D0 */
      uint8_t _ar = (uint8_t)(B(d0) + B(d2));
      B(d0) = (uint8_t)((uint8_t)_ar);
      flag_z = ((int8_t)(_ar) == 0);
      flag_n = ((int8_t)(_ar) < 0);
    }
  {  /* ADD.B	D0,D0 */
      uint8_t _ar = (uint8_t)(B(d0) + B(d0));
      B(d0) = (uint8_t)((uint8_t)_ar);
      flag_z = ((int8_t)(_ar) == 0);
      flag_n = ((int8_t)(_ar) < 0);
    }
  {  /* MOVE.W	c_PeriodTable(A6),D2 */
      uint16_t _mv = (uint16_t)(READ16(a6 + (intptr_t)c_PeriodTable + (int16_t)W(d0)));
      W(d2) = (uint16_t)_mv;
      flag_z = ((int16_t)(_mv) == 0);
      flag_n = ((int16_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  d2 = (d2 >> 16) | (d2 << 16);  /* SWAP.W	D2 */
  /* Set instrument */
  a5 = (uint32_t)(a6 + (intptr_t)c_Instruments);  /* LEA	c_Instruments(A6),A5 */
  a5 = (uint32_t)((int32_t)a5 + (int32_t)(int16_t)(W(d3)));  /* ADD.W	D3,A5 */
  /* Read sample address, length and repeat */
  d6 = (uint32_t)(int32_t)(int8_t)(1);  /* MOVEQ.L	#1,D6 */
  {  /* MOVE.W	(A5)+,D3 */
      uint16_t _mv = (uint16_t)(READ16_POST(a5));
      W(d3) = (uint16_t)_mv;
      flag_z = ((int16_t)(_mv) == 0);
      flag_n = ((int16_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  {  /* MOVE.W	(A5)+,D0 */
      uint16_t _mv = (uint16_t)(READ16_POST(a5));
      W(d0) = (uint16_t)_mv;
      flag_z = ((int16_t)(_mv) == 0);
      flag_n = ((int16_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  {  /* MOVE.L	(A5),A4 */
      uint32_t _mv = (uint32_t)(READ32(a5));
      a4 = _mv;
      flag_z = ((int32_t)(_mv) == 0);
      flag_n = ((int32_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  if (!(flag_z)) {
  {  /* MOVE.W	D0,D6 */
      uint16_t _mv = (uint16_t)(W(d0));
      W(d6) = (uint16_t)_mv;
      flag_z = ((int16_t)(_mv) == 0);
      flag_n = ((int16_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  {  /* SUB.W	D3,D0 */
      uint16_t _sr = (uint16_t)(W(d0) - W(d3));
      W(d0) = (uint16_t)((uint16_t)_sr);
      flag_z = ((int16_t)(_sr) == 0);
      flag_n = ((int16_t)(_sr) < 0);
    }
  a4 = (uint32_t)((int32_t)a4 - (int32_t)(int16_t)(W(d0)));  /* SUB.W	D0,A4 */
  a4 = (uint32_t)((int32_t)a4 - (int32_t)(int16_t)(W(d0)));  /* SUB.W	D0,A4 */
  }
  /* Save restart position and length */
  /* MOVEM.L D6,A4,-8(A0): save updated loop length and restart pointer */
  WRITE32(a0 - 8, d6);
  WRITE32(a0 - 4, a4);
  /* Add offset to sample address */
  {  /* MOVE.L	(A5),A4 */
      uint32_t _mv = (uint32_t)(READ32(a5));
      a4 = _mv;
      flag_z = ((int32_t)(_mv) == 0);
      flag_n = ((int32_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  {  /* SUB.W	D5,D3 */
      uint16_t _sr = (uint16_t)(W(d3) - W(d5));
      W(d3) = (uint16_t)((uint16_t)_sr);
      flag_z = ((int16_t)(_sr) == 0);
      flag_n = ((int16_t)(_sr) < 0);
    }
  {  /* ADD.W	D5,D5 */
      uint16_t _ar = (uint16_t)(W(d5) + W(d5));
      W(d5) = (uint16_t)((uint16_t)_ar);
      flag_z = ((int16_t)(_ar) == 0);
      flag_n = ((int16_t)(_ar) < 0);
    }
  a4 = (uint32_t)((int32_t)a4 + (int32_t)(d5));  /* ADD.L	D5,A4 (full 32-bit; transpiler wrongly truncated D5 to .W) */
  }
  /* Save period and volume */
  {  /* MOVE.L	D2,(A0)+ */
      uint32_t _mv = (uint32_t)(d2);
      WRITE32_POST(a0, _mv);
      flag_z = ((int32_t)(_mv) == 0);
      flag_n = ((int32_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  /* Write to audio registers (use hw_write to intercept 0xDFF0xx → Paula API) */
  a3 = (uint32_t)((int32_t)a3 - (int32_t)(int16_t)(6));  /* SUBQ.L	#6,A3 */
  {  /* MOVE.L	D2,-(A3)  — period (high word) + volume (low word) */
      a3 -= 4;
      hw_write32(a3, (uint32_t)(d2));
    }
  {  /* MOVE.W	D3,-(A3)  — sample length */
      a3 -= 2;
      hw_write16(a3, (uint16_t)(W(d3)));
    }
  {  /* MOVE.L	A4,-(A3)  — sample pointer */
      a3 -= 4;
      hw_write32(a3, (uint32_t)(a4));
    }
}
  /* Wait for old DMA to stop, then start new DMA */
  {  /* MOVE.W	(A0)+,D0 */
      uint16_t _mv = (uint16_t)(READ16_POST(a0));
      W(d0) = (uint16_t)_mv;
      flag_z = ((int16_t)(_mv) == 0);
      flag_n = ((int16_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  if (!(flag_z)) {
  W(d0) |= (uint16_t)(0x8000);  /* OR.W	#$8000,D0 */
  {  /* MOVE.W	(A0)+,D1 */
      uint16_t _mv = (uint16_t)(READ16_POST(a0));
      W(d1) = (uint16_t)_mv;
      flag_z = ((int16_t)(_mv) == 0);
      flag_n = ((int16_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  {  /* ADD.W	#$0780,D1 */
      uint16_t _ar = (uint16_t)(W(d1) + 0x0780);
      W(d1) = (uint16_t)((uint16_t)_ar);
      flag_z = ((int16_t)(_ar) == 0);
      flag_n = ((int16_t)(_ar) < 0);
    }
  a3 = (uint32_t)0xdff000;  /* LEA.L	$DFF000,A3 */
  /* Amiga scanline wait: VHPOSR at 0xDFF006 is uninitialized WASM memory and
   * never updates, so the original do-while would spin forever. Skip it. */
  flag_z = 1;
  {  /* MOVE.W	D0,150(A3) */
      uint16_t _mv = (uint16_t)(W(d0));
      hw_write16(a3 + 150, _mv);
      flag_z = ((int16_t)(_mv) == 0);
      flag_n = ((int16_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  }
  return;  /* RTS */
}


/* TRANSPILER WARNINGS:
 * Line 317: CIA register write $bfe001 — emitted as no-op
 * Line 320: Custom chip write $dff000 — emitted as no-op
 * Line 364: Custom chip write $dff000 — emitted as no-op
 * Line 464: Custom chip write $dff000 — emitted as no-op
 */