/**
 * LexiconBrowser — searchable index of every word the Speak & Spell TMS5220
 * voice can construct from its ROM-mined phoneme library.
 *
 * The word database is an 8 MB TSV asset (public/data/tms5220-lexicon.tsv,
 * generated by tools/tms5220-audit/buildLexicon.ts). It is fetched lazily on
 * first expansion so opening the TMS5220 panel never pays for it, and it never
 * enters the JS bundle.
 */
import React, { useState, useCallback } from 'react';
import { IMPORTED_RECORDING_WORDS } from '@generated/tms5220Recordings';

export interface LexiconEntry {
  word: string;
  phonemes: string;
  tier: number;
  rom: boolean;
  authentic: boolean;
}

interface LexiconBrowserProps {
  accentColor: string;
  mutedColor: string;
  panelBorder: string;
  isCyanTheme: boolean;
  onSpeak: (text: string) => void;
}

const LEXICON_URL = '/data/tms5220-lexicon.tsv';

const TIER_STYLE: Record<number, { label: string; color: string; bg: string }> = {
  0: { label: 'ROM-mined', color: '#22c55e', bg: 'rgba(34,197,94,0.15)' },
  1: { label: 'Alias', color: '#eab308', bg: 'rgba(234,179,8,0.15)' },
  2: { label: 'Derived', color: '#f97316', bg: 'rgba(249,115,22,0.15)' },
};

const MAX_RESULTS = 100;

const AUTHENTIC_WORDS = new Set(IMPORTED_RECORDING_WORDS);

async function fetchLexicon(): Promise<{ entries: LexiconEntry[]; total: number }> {
  const res = await fetch(LEXICON_URL);
  if (!res.ok) throw new Error(`lexicon fetch failed: ${res.status}`);
  const text = await res.text();
  const entries = text.split('\n').filter(Boolean).map((line) => {
    const [word, phonemes, tier, rom] = line.split('\t');
    return {
      word,
      phonemes,
      tier: Number(tier),
      rom: rom === '1',
      authentic: AUTHENTIC_WORDS.has(word),
    };
  });
  return { entries, total: entries.length };
}

export const LexiconBrowser: React.FC<LexiconBrowserProps> = ({
  accentColor,
  mutedColor,
  panelBorder,
  isCyanTheme,
  onSpeak,
}) => {
  const [open, setOpen] = useState(false);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [entries, setEntries] = useState<LexiconEntry[] | null>(null);
  const [total, setTotal] = useState(0);
  const [query, setQuery] = useState('');

  const load = useCallback(() => {
    if (open || loading || entries) return;
    setOpen(true);
    setLoading(true);
    fetchLexicon().then(({ entries: loaded, total: n }) => {
      setTotal(n);
      setEntries(loaded);
      setLoading(false);
    }).catch((err) => {
      setError(err instanceof Error ? err.message : String(err));
      setLoading(false);
    });
  }, [open, loading, entries]);

  const results = useCallback((): LexiconEntry[] => {
    if (!entries) return [];
    const q = query.trim().toUpperCase();
    if (!q) return entries.slice(0, MAX_RESULTS);
    return entries.filter((e) => e.word.startsWith(q)).slice(0, MAX_RESULTS);
  }, [entries, query]);

  const list = results();

  return (
    <div key="lexicon" style={{ flex: '1 1 100%' }}>
      {!open ? (
        <button
          onClick={load}
          style={{
            width: '100%',
            padding: '10px 12px',
            borderRadius: 6,
            border: `1px solid ${panelBorder}`,
            background: `${accentColor}12`,
            color: accentColor,
            fontSize: 11,
            fontWeight: 700,
            textTransform: 'uppercase',
            letterSpacing: '0.05em',
            cursor: 'pointer',
            textAlign: 'left',
          }}
        >
          Load Word Lexicon
        </button>
      ) : loading ? (
        <div style={{ fontSize: 10, color: mutedColor, padding: '6px 2px' }}>
          Loading lexicon…
        </div>
      ) : error ? (
        <div style={{ fontSize: 10, color: '#ef4444', padding: '6px 2px' }}>
          Failed to load lexicon: {error}
        </div>
      ) : (
        <div style={{ display: 'flex', flexDirection: 'column', gap: 6 }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: 6 }}>
            <span style={{ fontSize: 9, color: mutedColor }}>
              {total.toLocaleString()} words
            </span>
            <span style={{ fontSize: 9, color: TIER_STYLE[0].color }}>
              {(entries ?? []).filter((e) => e.tier === 0).length.toLocaleString()} ROM-mined
            </span>
            <span style={{ fontSize: 9, color: TIER_STYLE[1].color }}>
              {(entries ?? []).filter((e) => e.tier === 1).length.toLocaleString()} alias
            </span>
            <span style={{ fontSize: 9, color: TIER_STYLE[2].color }}>
              {(entries ?? []).filter((e) => e.tier === 2).length.toLocaleString()} derived
            </span>
          </div>
          <input
            type="text"
            value={query}
            onChange={(e) => setQuery(e.target.value)}
            placeholder="Search words — click to speak"
            autoFocus
            style={{
              background: isCyanTheme ? '#041010' : '#0d1117',
              color: isCyanTheme ? '#00ffff' : accentColor,
              border: `1px solid ${panelBorder}`,
              borderRadius: 6,
              padding: '8px 12px',
              fontSize: 12,
              fontFamily: 'Monaco, Menlo, monospace',
              outline: 'none',
            }}
          />
          <div style={{
            maxHeight: 260,
            overflowY: 'auto',
            border: `1px solid ${panelBorder}`,
            borderRadius: 6,
          }}>
            {list.length === 0 ? (
              <div style={{ fontSize: 10, color: mutedColor, padding: '10px 12px' }}>
                No words found
              </div>
            ) : list.map((e) => {
              const ts = TIER_STYLE[e.tier] ?? TIER_STYLE[2];
              return (
                <button
                  key={e.word}
                  onClick={() => onSpeak(e.word)}
                  title={`${e.word} — ${e.phonemes}`}
                  style={{
                    display: 'flex',
                    alignItems: 'center',
                    gap: 8,
                    width: '100%',
                    padding: '5px 12px',
                    background: 'transparent',
                    border: 'none',
                    borderBottom: `1px solid ${panelBorder}`,
                    color: '#e2e8f0',
                    fontSize: 12,
                    fontFamily: 'Monaco, Menlo, monospace',
                    cursor: 'pointer',
                    textAlign: 'left',
                    textTransform: 'uppercase',
                  }}
                  onMouseEnter={(ev) => { ev.currentTarget.style.background = `${accentColor}14`; }}
                  onMouseLeave={(ev) => { ev.currentTarget.style.background = 'transparent'; }}
                >
                  <span style={{ flex: 1 }}>{e.word}</span>
                  {e.rom && (
                    <span style={{
                      fontSize: 8,
                      fontWeight: 700,
                      padding: '1px 5px',
                      borderRadius: 4,
                      background: 'rgba(59,130,246,0.15)',
                      color: '#3b82f6',
                    }}>ROM</span>
                  )}
                  {e.authentic && (
                    <span style={{
                      fontSize: 8,
                      fontWeight: 700,
                      padding: '1px 5px',
                      borderRadius: 4,
                      background: 'rgba(168,85,247,0.15)',
                      color: '#a855f7',
                    }}>AUTHENTIC</span>
                  )}
                  <span style={{
                    fontSize: 8,
                    fontWeight: 700,
                    padding: '1px 5px',
                    borderRadius: 4,
                    background: ts.bg,
                    color: ts.color,
                  }}>{ts.label}</span>
                </button>
              );
            })}
          </div>
        </div>
      )}
    </div>
  );
};