/**
 * LexiconBrowser — searchable index of every word the Speak & Spell TMS5220
 * voice can construct from its ROM-mined phoneme library.
 *
 * The word database is an 8 MB TSV asset (public/data/tms5220-lexicon.tsv,
 * generated by tools/tms5220-audit/buildLexicon.ts). It loads when the panel
 * mounts — the fetch and parse are async, and the asset stays out of the JS
 * bundle — and all derived structures (merged list, tier counts) are computed
 * once per load, never per keystroke: this is a 221k-entry list.
 */
import React, { useState, useMemo, useEffect, useSyncExternalStore } from 'react';
import { IMPORTED_RECORDING_WORDS } from '@generated/tms5220Recordings';
import { getRomWordNames, getRomWordVersion, subscribeRomWords } from '@engine/tms5220/TMS5220Synth';

export interface LexiconEntry {
  word: string;
  phonemes: string;
  tier: number;
  rom: boolean;
  authentic: boolean;
}

interface LexiconBrowserProps {
  accentColor: string;
  mutedColor: string;
  panelBorder: string;
  isCyanTheme: boolean;
  onSpeak: (text: string) => void;
}

const LEXICON_URL = '/data/tms5220-lexicon.tsv';

const TIER_STYLE: Record<number, { label: string; color: string; bg: string }> = {
  0: { label: 'ROM-mined', color: '#22c55e', bg: 'rgba(34,197,94,0.15)' },
  1: { label: 'Alias', color: '#eab308', bg: 'rgba(234,179,8,0.15)' },
  2: { label: 'Derived', color: '#f97316', bg: 'rgba(249,115,22,0.15)' },
};

const MAX_RESULTS = 100;

const AUTHENTIC_WORDS = new Set(IMPORTED_RECORDING_WORDS);

async function fetchLexicon(): Promise<{ entries: LexiconEntry[]; total: number }> {
  const res = await fetch(LEXICON_URL);
  if (!res.ok) throw new Error(`lexicon fetch failed: ${res.status}`);
  const text = await res.text();
  const entries = text.split('\n').filter(Boolean).map((line) => {
    const [word, phonemes, tier, rom] = line.split('\t');
    return {
      word,
      phonemes,
      tier: Number(tier),
      rom: rom === '1',
      authentic: AUTHENTIC_WORDS.has(word),
    };
  });
  return { entries, total: entries.length };
}

export const LexiconBrowser: React.FC<LexiconBrowserProps> = ({
  accentColor,
  mutedColor,
  panelBorder,
  isCyanTheme,
  onSpeak,
}) => {
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [entries, setEntries] = useState<LexiconEntry[] | null>(null);
  const [total, setTotal] = useState(0);
  const [query, setQuery] = useState('');

  // Load by default — the lexicon is the TMS5220's word list, not an optional
  // extra. The 8 MB TSV still fetches lazily off the bundle.
  useEffect(() => {
    if (loading || entries) return;
    setLoading(true);
    fetchLexicon().then(({ entries: loaded, total: n }) => {
      setTotal(n);
      setEntries(loaded);
      setLoading(false);
    }).catch((err) => {
      setError(err instanceof Error ? err.message : String(err));
      setLoading(false);
    });
  }, [loading, entries]);

  // ROM words parse out of the VSM binary at runtime. Subscribe so the merged
  // list gains them (ROM badge) whenever the ROM finishes loading.
  useSyncExternalStore(subscribeRomWords, getRomWordVersion, getRomWordVersion);
  const romEntries = useMemo(() => {
    const names = getRomWordNames('TMS5220') ?? [];
    return names.map((word): LexiconEntry => ({
      word,
      phonemes: '',
      tier: 0,
      rom: true,
      authentic: AUTHENTIC_WORDS.has(word),
    }));
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [getRomWordVersion()]);

  // One list: the lexicon TSV plus the runtime ROM word names. TSV entries
  // win on duplicates (they carry phonemes for synthesis fallback). Built once
  // per load — rebuilding a 221k-entry array plus a Set on every keystroke was
  // the typing lag in this panel.
  const merged = useMemo((): LexiconEntry[] => {
    if (!entries) return [];
    const seen = new Set<string>();
    for (const e of entries) seen.add(e.word.toUpperCase());
    return [...entries, ...romEntries.filter((e) => !seen.has(e.word.toUpperCase()))];
  }, [entries, romEntries]);

  const tierCounts = useMemo(() => {
    const counts = [0, 0, 0];
    for (const e of entries ?? []) {
      if (e.tier < 3) counts[e.tier]++;
    }
    return counts;
  }, [entries]);

  // Prefix search with an early exit: never scan past MAX_RESULTS hits.
  const list = useMemo((): LexiconEntry[] => {
    const q = query.trim().toUpperCase();
    const out: LexiconEntry[] = [];
    for (const e of merged) {
      if (q && !e.word.startsWith(q)) continue;
      out.push(e);
      if (out.length >= MAX_RESULTS) break;
    }
    return out;
  }, [merged, query]);

  return (
    <div key="lexicon" style={{ flex: '1 1 100%' }}>
      {loading ? (
        <div style={{ fontSize: 10, color: mutedColor, padding: '6px 2px' }}>
          Loading lexicon…
        </div>
      ) : error ? (
        <div style={{ fontSize: 10, color: '#ef4444', padding: '6px 2px' }}>
          Failed to load lexicon: {error}
        </div>
      ) : (
        <div style={{ display: 'flex', flexDirection: 'column', gap: 6 }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: 6 }}>
            <span style={{ fontSize: 9, color: mutedColor }}>
              {(total + romEntries.length).toLocaleString()} words
            </span>
            <span style={{ fontSize: 9, color: '#3b82f6' }}>
              {romEntries.length.toLocaleString()} ROM
            </span>
            <span style={{ fontSize: 9, color: TIER_STYLE[0].color }}>
              {tierCounts[0].toLocaleString()} ROM-mined
            </span>
            <span style={{ fontSize: 9, color: TIER_STYLE[1].color }}>
              {tierCounts[1].toLocaleString()} alias
            </span>
            <span style={{ fontSize: 9, color: TIER_STYLE[2].color }}>
              {tierCounts[2].toLocaleString()} derived
            </span>
          </div>
          <input
            type="text"
            value={query}
            onChange={(e) => setQuery(e.target.value)}
            placeholder="Search words — click to speak"
            autoFocus
            style={{
              background: isCyanTheme ? '#041010' : '#0d1117',
              color: isCyanTheme ? '#00ffff' : accentColor,
              border: `1px solid ${panelBorder}`,
              borderRadius: 6,
              padding: '8px 12px',
              fontSize: 12,
              fontFamily: 'Monaco, Menlo, monospace',
              outline: 'none',
            }}
          />
          <div style={{
            maxHeight: 260,
            overflowY: 'auto',
            border: `1px solid ${panelBorder}`,
            borderRadius: 6,
          }}>
            {list.length === 0 ? (
              <div style={{ fontSize: 10, color: mutedColor, padding: '10px 12px' }}>
                No words found
              </div>
            ) : list.map((e) => {
              const ts = TIER_STYLE[e.tier] ?? TIER_STYLE[2];
              return (
                <button
                  key={e.word}
                  onClick={() => onSpeak(e.word)}
                  title={`${e.word} — ${e.phonemes}`}
                  style={{
                    display: 'flex',
                    alignItems: 'center',
                    gap: 8,
                    width: '100%',
                    padding: '5px 12px',
                    background: 'transparent',
                    border: 'none',
                    borderBottom: `1px solid ${panelBorder}`,
                    color: '#e2e8f0',
                    fontSize: 12,
                    fontFamily: 'Monaco, Menlo, monospace',
                    cursor: 'pointer',
                    textAlign: 'left',
                    textTransform: 'uppercase',
                  }}
                  onMouseEnter={(ev) => { ev.currentTarget.style.background = `${accentColor}14`; }}
                  onMouseLeave={(ev) => { ev.currentTarget.style.background = 'transparent'; }}
                >
                  <span style={{ flex: 1 }}>{e.word}</span>
                  {e.rom && (
                    <span style={{
                      fontSize: 8,
                      fontWeight: 700,
                      padding: '1px 5px',
                      borderRadius: 4,
                      background: 'rgba(59,130,246,0.15)',
                      color: '#3b82f6',
                    }}>ROM</span>
                  )}
                  {e.authentic && (
                    <span style={{
                      fontSize: 8,
                      fontWeight: 700,
                      padding: '1px 5px',
                      borderRadius: 4,
                      background: 'rgba(168,85,247,0.15)',
                      color: '#a855f7',
                    }}>AUTHENTIC</span>
                  )}
                  <span style={{
                    fontSize: 8,
                    fontWeight: 700,
                    padding: '1px 5px',
                    borderRadius: 4,
                    background: ts.bg,
                    color: ts.color,
                  }}>{ts.label}</span>
                </button>
              );
            })}
          </div>
        </div>
      )}
    </div>
  );
};