/* ====================================================================
 * Auto-generated by asm68k-to-c transpiler
 * Source: ma.asm
 *
 * This file was mechanically translated from Motorola 68000 assembly.
 * Original ASM instructions appear as inline comments.
 * ==================================================================== */

#include "paula_soft.h"
#include <stdint.h>

/* -- 68k Register File ------------------------------------------------
 * Data registers D0-D7:  general-purpose 32-bit registers.
 * Address registers A0-A6: pointer registers (32-bit).
 * SP (A7): stack pointer.  PC: program counter (unused in transpiled code).
 * Flags: Z (zero), N (negative), C (carry), V (overflow), X (extend).
 * -------------------------------------------------------------------- */
static uint32_t d0,d1,d2,d3,d4,d5,d6,d7;
static uint32_t a0,a1,a2,a3,a4,a5,a6,sp,pc;
static int flag_z=0, flag_n=0, flag_c=0, flag_v=0, flag_x=0;

/* -- Sub-register Accessors -------------------------------------------
 * W(d0) -- access the low 16 bits of d0 (read/write).
 * B(d0) -- access the low 8 bits of d0 (read/write).
 * Example: W(d0) = 0x1234;  // sets d0.w, leaves upper 16 bits unchanged
 * -------------------------------------------------------------------- */
#define W(r)  (*((uint16_t*)&(r)))
#define B(r)  (*((uint8_t*)&(r)))

/* -- Memory Access (Big-Endian) ---------------------------------------
 * The 68k is big-endian; these macros byte-swap on little-endian hosts.
 * Uses memcpy for alignment-safe access (68k allows unaligned word/long).
 *
 * READ8(addr)       -- read  byte from address
 * READ16(addr)      -- read  big-endian word from address
 * READ32(addr)      -- read  big-endian longword from address
 * WRITE8(addr,v)    -- write byte to address
 * WRITE16(addr,v)   -- write big-endian word to address
 * WRITE32(addr,v)   -- write big-endian longword to address
 * READ16_POST(reg)  -- read word, then reg += 2  (simulates (An)+ mode)
 * WRITE16_PRE(reg,v)-- reg -= 2, then write word (simulates -(An) mode)
 * -------------------------------------------------------------------- */
#include <string.h>
#define READ8(addr)   (*((const uint8_t*)(uintptr_t)(addr)))
#define WRITE8(addr,v)  (*((uint8_t*)(uintptr_t)(addr)) = (uint8_t)(v))
static inline uint16_t _rd16(uintptr_t a) { uint16_t v; memcpy(&v,(void*)a,2); return v; }
static inline uint32_t _rd32(uintptr_t a) { uint32_t v; memcpy(&v,(void*)a,4); return v; }
static inline void _wr16(uintptr_t a,uint16_t v) { memcpy((void*)a,&v,2); }
static inline void _wr32(uintptr_t a,uint32_t v) { memcpy((void*)a,&v,4); }

/* -- Amiga custom chip write interception --------------------------------
 * Intercept writes to the $dff000-$dff1ff range and route audio register
 * writes to paula_soft functions. Without this, the transpiled replayer
 * writes to raw memory and Paula never receives any DMA/sample data.
 * ----------------------------------------------------------------------- */
static inline void _custom_write16(uint32_t addr, uint16_t val) {
    if (addr >= 0xdff000 && addr < 0xdff200) {
        uint32_t reg = addr - 0xdff000;
        switch (reg) {
            /* Audio channel 0 */
            case 0xa0: /* aud0lc hi */ break; /* handled as 32-bit via 0xa0 */
            case 0xa4: paula_set_length(0, val); return;
            case 0xa6: paula_set_period(0, val); return;
            case 0xa8: paula_set_volume(0, (uint8_t)val); return;
            /* Audio channel 1 */
            case 0xb0: break;
            case 0xb4: paula_set_length(1, val); return;
            case 0xb6: paula_set_period(1, val); return;
            case 0xb8: paula_set_volume(1, (uint8_t)val); return;
            /* Audio channel 2 */
            case 0xc0: break;
            case 0xc4: paula_set_length(2, val); return;
            case 0xc6: paula_set_period(2, val); return;
            case 0xc8: paula_set_volume(2, (uint8_t)val); return;
            /* Audio channel 3 */
            case 0xd0: break;
            case 0xd4: paula_set_length(3, val); return;
            case 0xd6: paula_set_period(3, val); return;
            case 0xd8: paula_set_volume(3, (uint8_t)val); return;
            /* DMA control */
            case 0x96: paula_dma_write(val); return;
            default: return; /* ignore other custom registers */
        }
    }
    _wr16(addr, __builtin_bswap16(val));
}

static inline void _custom_write32(uint32_t addr, uint32_t val) {
    if (addr >= 0xdff000 && addr < 0xdff200) {
        uint32_t reg = addr - 0xdff000;
        /* 32-bit writes to audio pointer registers (aud*lc) */
        if (reg == 0xa0) { paula_set_sample_ptr(0, (const int8_t*)(uintptr_t)val); return; }
        if (reg == 0xb0) { paula_set_sample_ptr(1, (const int8_t*)(uintptr_t)val); return; }
        if (reg == 0xc0) { paula_set_sample_ptr(2, (const int8_t*)(uintptr_t)val); return; }
        if (reg == 0xd0) { paula_set_sample_ptr(3, (const int8_t*)(uintptr_t)val); return; }
        /* 32-bit write to other regs: split into two 16-bit writes */
        _custom_write16(addr, (uint16_t)(val >> 16));
        _custom_write16(addr + 2, (uint16_t)(val & 0xffff));
        return;
    }
    _wr32(addr, __builtin_bswap32(val));
}

#if defined(__BYTE_ORDER__) && __BYTE_ORDER__ == __ORDER_BIG_ENDIAN__
#define READ16(addr)  _rd16((uintptr_t)(addr))
#define READ32(addr)  _rd32((uintptr_t)(addr))
#define WRITE16(addr,v) _custom_write16((uint32_t)(addr),(uint16_t)(v))
#define WRITE32(addr,v) _custom_write32((uint32_t)(addr),(uint32_t)(v))
#else
#define READ16(addr)  __builtin_bswap16(_rd16((uintptr_t)(addr)))
#define READ32(addr)  __builtin_bswap32(_rd32((uintptr_t)(addr)))
#define WRITE16(addr,v) _custom_write16((uint32_t)(addr),(uint16_t)(v))
#define WRITE32(addr,v) _custom_write32((uint32_t)(addr),(uint32_t)(v))
#endif
#define READ8_POST(r)   ({ uint32_t _r=(r); (r)+=1; READ8(_r); })
#define READ16_POST(r)  ({ uint32_t _r=(r); (r)+=2; READ16(_r); })
#define READ32_POST(r)  ({ uint32_t _r=(r); (r)+=4; READ32(_r); })
#define READ8_PRE(r)    ({ (r)-=1; READ8(r); })
#define READ16_PRE(r)   ({ (r)-=2; READ16(r); })
#define READ32_PRE(r)   ({ (r)-=4; READ32(r); })
#define WRITE8_POST(r,v)  ({ WRITE8(r,v);  (r)+=1; })
#define WRITE16_POST(r,v) ({ WRITE16(r,v); (r)+=2; })
#define WRITE32_POST(r,v) ({ WRITE32(r,v); (r)+=4; })
#define WRITE8_PRE(r,v)   ({ (r)-=1; WRITE8(r,v); })
#define WRITE16_PRE(r,v)  ({ (r)-=2; WRITE16(r,v); })
#define WRITE32_PRE(r,v)  ({ (r)-=4; WRITE32(r,v); })

/* -- Rotation Helpers -------------------------------------------------
 * ROL32(v,n) -- rotate 32-bit value left by n bits
 * ROR32(v,n) -- rotate 32-bit value right by n bits
 * -------------------------------------------------------------------- */
#define ROL32(v,n)  (((v)<<(n))|((v)>>(32-(n))))
#define ROR32(v,n)  (((v)>>(n))|((v)<<(32-(n))))

/* -- Unresolved Symbols -------------------------------------------- */
/* These symbols come from include files not available to the transpiler.
 * They are stubbed as 0 so the generated C compiles. */
/* _other* */
#ifndef asm
#define asm 0
#endif
#ifndef DELIRIUM
#define DELIRIUM 0
#endif
#ifndef creator
#define creator 0
#endif
#ifndef songend
#define songend 0
#endif
#ifndef support
#define support 0
#endif
#ifndef all
#define all 0
#endif
/* Amiga custom chip register offsets from $DFF000 base */
#define aud0    0xa0
#define aud0vol 0xa8
#define aud1    0xb0
#define aud1vol 0xb8
#define aud2    0xc0
#define aud2vol 0xc8
#define aud3    0xd0
#define aud3vol 0xd8
#define dmacon  0x96
/* DTP_* */
#ifndef DTP_PlayerName
#define DTP_PlayerName 0
#endif
#ifndef DTP_Creator
#define DTP_Creator 0
#endif
#ifndef DTP_Check2
#define DTP_Check2 0
#endif
#ifndef DTP_SubSongRange
#define DTP_SubSongRange 0
#endif
#ifndef DTP_InitPlayer
#define DTP_InitPlayer 0
#endif
#ifndef DTP_InitSound
#define DTP_InitSound 0
#endif
#ifndef DTP_Interrupt
#define DTP_Interrupt 0
#endif
#ifndef DTP_EndSound
#define DTP_EndSound 0
#endif
#ifndef DTP_EndPlayer
#define DTP_EndPlayer 0
#endif
#ifndef DTP_Volume
#define DTP_Volume 0
#endif
/* dtg_* */
#ifndef dtg_ChkData
#define dtg_ChkData 0
#endif
#ifndef dtg_GetListData
#define dtg_GetListData 0
#endif
#ifndef dtg_AudioAlloc
#define dtg_AudioAlloc 0
#endif
#ifndef dtg_SndNum
#define dtg_SndNum 0
#endif
#ifndef dtg_SongEnd
#define dtg_SongEnd 0
#endif
#ifndef dtg_AudioFree
#define dtg_AudioFree 0
#endif
#ifndef dtg_SndVol
#define dtg_SndVol 0
#endif

/* -- Packed Data Section -------------------------------------------- */
/* All data labels packed into a single contiguous byte array matching
 * 68k memory layout. Accessor macros provide typed pointer access. */
static uint8_t _ds[400] = {
  0x00,0x00,0x00,0x00,0x00,0x00,0x24,0x56,0x45,0x52,0x3a,0x20,0x4d,0x75,0x73,0x69,
  0x63,0x2d,0x41,0x73,0x73,0x65,0x6d,0x62,0x6c,0x65,0x72,0x20,0x70,0x6c,0x61,0x79,
  0x65,0x72,0x20,0x6d,0x6f,0x64,0x75,0x6c,0x65,0x20,0x56,0x30,0x2e,0x31,0x20,0x66,
  0x6f,0x72,0x20,0x55,0x41,0x44,0x45,0x20,0x28,0x32,0x31,0x2e,0x31,0x32,0x2e,0x32,
  0x30,0x30,0x31,0x29,0x00,0x24,0x43,0x4f,0x50,0x59,0x52,0x49,0x47,0x48,0x54,0x3a,
  0x20,0x48,0x65,0x69,0x6b,0x6b,0x69,0x20,0x4f,0x72,0x73,0x69,0x6c,0x61,0x20,0x3c,
  0x68,0x65,0x69,0x6b,0x6b,0x69,0x2e,0x6f,0x72,0x73,0x69,0x6c,0x61,0x40,0x74,0x75,
  0x74,0x2e,0x66,0x69,0x3e,0x00,0x24,0x4c,0x49,0x43,0x45,0x4e,0x53,0x45,0x3a,0x20,
  0x47,0x4e,0x55,0x20,0x4c,0x47,0x50,0x4c,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00, /* table@138 */
  0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,
  0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,
  0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,
  0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,
  0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x80,0x00,0x44,0x74,0x00,0x00,
  0x00,0x02,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x4d,0x75, /* playername@238 */
  0x73,0x69,0x63,0x2d,0x41,0x73,0x73,0x65,0x6d,0x62,0x6c,0x65,0x72,0x00,0x4d,0x41, /* eator@254 */
  0x2d,0x70,0x6c,0x61,0x79,0x65,0x72,0x20,0x66,0x6f,0x72,0x20,0x55,0x41,0x44,0x45,
  0x20,0x62,0x79,0x20,0x73,0x68,0x64,0x2c,0x20,0x0a,0x54,0x68,0x61,0x6e,0x6b,0x73,
  0x20,0x74,0x6f,0x20,0x4c,0x61,0x75,0x72,0x65,0x6e,0x74,0x20,0x43,0x6c,0x65,0x76,
  0x79,0x20,0x66,0x6f,0x72,0x20,0x66,0x6f,0x72,0x6d,0x61,0x74,0x20,0x69,0x6e,0x66,
  0x6f,0x2c,0x20,0x0a,0x42,0x61,0x73,0x65,0x64,0x20,0x6f,0x6e,0x20,0x66,0x6f,0x72,
  0x6d,0x61,0x74,0x20,0x62,0x79,0x20,0x4f,0x73,0x63,0x61,0x72,0x20,0x47,0x69,0x65,
  0x73,0x65,0x6e,0x20,0x61,0x6e,0x64,0x20,0x4d,0x61,0x72,0x63,0x6f,0x20,0x53,0x77,
  0x61,0x67,0x65,0x72,0x6d,0x61,0x6e,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00, /* modptr@376, delibase@380 */
  0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00, /* chandataptr@384, firsttime@388, endpossible@392, counter@396 */
};
#define table ((uint32_t*)(_ds + 138))
#define playername ((uint8_t*)(_ds + 238))
#define eator ((uint8_t*)(_ds + 254))
#define modptr ((uint32_t*)(_ds + 376))
#define delibase ((uint32_t*)(_ds + 380))
#define chandataptr ((uint32_t*)(_ds + 384))
#define firsttime ((uint32_t*)(_ds + 388))
#define endpossible ((uint32_t*)(_ds + 392))
#define counter ((uint32_t*)(_ds + 396))

/* -- Forward Declarations -------------------------------------------- */
static void checktype1(void);
static void Check2(void);
static void SubSongRange(void);
static void InitPlayer(void);
static void InitSound(void);
static void Interrupt(void);
static void EndSound(void);
static void EndPlayer(void);
static void SubSongRange(void) {
    d0 = (uint32_t)(int32_t)(int8_t)(0);  /* MOVEQ	#0,D0 */
    d1 = (uint32_t)(int32_t)(int8_t)(9);  /* MOVEQ	#9,D1 */
    return;  /* RTS */
    return;  /* RTS */
}
static void InitPlayer(void) {
    /* UNIMPLEMENTED: PUSH */  /* PUSH	all */
    d0 = (uint32_t)(int32_t)(int8_t)(0);  /* MOVEQ	#0,D0 */
    {  /* MOVE.L	dtg_GetListData(A5),A0 */
        uint32_t _mv = (uint32_t)(READ32(a5 + (intptr_t)dtg_GetListData));
        a0 = _mv;
        flag_z = ((int32_t)(_mv) == 0);
        flag_n = ((int32_t)(_mv) < 0);
        flag_v = 0; flag_c = 0;
      }
    { uintptr_t _jt=(uintptr_t)(a0); if(_jt) ((void(*)(void))_jt)(); }  /* JSR	(A0) */
    {  /* MOVE.L	A0,modptr */
        uint32_t _mv = (uint32_t)(a0);
        WRITE32((uintptr_t)modptr, _mv);
        flag_z = ((int32_t)(_mv) == 0);
        flag_n = ((int32_t)(_mv) < 0);
        flag_v = 0; flag_c = 0;
      }
    {  /* MOVE.L	A5,delibase */
        uint32_t _mv = (uint32_t)(a5);
        WRITE32((uintptr_t)delibase, _mv);
        flag_z = ((int32_t)(_mv) == 0);
        flag_n = ((int32_t)(_mv) < 0);
        flag_v = 0; flag_c = 0;
      }
    {  /* MOVE.L	dtg_AudioAlloc(A5),A0 */
        uint32_t _mv = (uint32_t)(READ32(a5 + (intptr_t)dtg_AudioAlloc));
        a0 = _mv;
        flag_z = ((int32_t)(_mv) == 0);
        flag_n = ((int32_t)(_mv) < 0);
        flag_v = 0; flag_c = 0;
      }
    { uintptr_t _jt=(uintptr_t)(a0); if(_jt) ((void(*)(void))_jt)(); }  /* JSR	(A0) */
    /* UNIMPLEMENTED: PULL */  /* PULL	all */
    d0 = (uint32_t)(int32_t)(int8_t)(0);  /* MOVEQ	#0,D0 */
    return;  /* RTS */
    return;  /* RTS */
}
static void InitSound(void) {
    /* UNIMPLEMENTED: PUSH */  /* PUSH	all */
    d0 = (uint32_t)(int32_t)(int8_t)(0);  /* MOVEQ	#0,D0 */
    {  /* MOVE	dtg_SndNum(A5),D0 */
        uint32_t _mv = (uint32_t)(READ32(a5 + (intptr_t)dtg_SndNum));
        d0 = _mv;
        flag_z = ((int32_t)(_mv) == 0);
        flag_n = ((int32_t)(_mv) < 0);
        flag_v = 0; flag_c = 0;
      }
    {  /* MOVE.L	modptr,A0 */
        uint32_t _mv = (uint32_t)(READ32((uintptr_t)modptr));
        a0 = _mv;
        flag_z = ((int32_t)(_mv) == 0);
        flag_n = ((int32_t)(_mv) < 0);
        flag_v = 0; flag_c = 0;
      }
    { uintptr_t _jt=(uintptr_t)(a0); if(_jt) ((void(*)(void))_jt)(); }  /* JSR	(A0) */
    {  /* MOVE.L	dtg_ChkData(A5),A0 */
        uint32_t _mv = (uint32_t)(READ32(a5 + (intptr_t)dtg_ChkData));
        a0 = _mv;
        flag_z = ((int32_t)(_mv) == 0);
        flag_n = ((int32_t)(_mv) < 0);
        flag_v = 0; flag_c = 0;
      }
    a0 = (uint32_t)((int32_t)a0 + (int32_t)(int16_t)(0x400));  /* ADD	#$400,A0 */
    {  /* MOVE	#$400,#2,#-1,D7 */
        uint32_t _mv = (uint32_t)(0x400);
        /* write unknown */ (void)(_mv);
        flag_z = ((int32_t)(_mv) == 0);
        flag_n = ((int32_t)(_mv) < 0);
        flag_v = 0; flag_c = 0;
      }
  sloop:
    {  /* MOVE.L	(A0),D0 */
        uint32_t _mv = (uint32_t)(READ32(a0));
        d0 = _mv;
        flag_z = ((int32_t)(_mv) == 0);
        flag_n = ((int32_t)(_mv) < 0);
        flag_v = 0; flag_c = 0;
      }
    d0 &= 0xffffff0f;  /* AND.L	#$ffffff0f,D0 */
    {  /* CMP.L	#$00dff000,D0 */
        int32_t _lhs = (int32_t)(d0);
        int32_t _rhs = (int32_t)(0x00dff000);
        int32_t _cmp = _lhs - _rhs;
        flag_z = (_cmp == 0);
        flag_n = (_cmp < 0);
        flag_c = ((uint32_t)_lhs < (uint32_t)_rhs);
      }
    if (!flag_z) goto notthis;  /* not equal / nonzero */  /* BNE.B	notthis */
    {  /* MOVE.L	38(A0),D0 */
        uint32_t _mv = (uint32_t)(READ32(a0 + 38));
        d0 = _mv;
        flag_z = ((int32_t)(_mv) == 0);
        flag_n = ((int32_t)(_mv) < 0);
        flag_v = 0; flag_c = 0;
      }
    d0 &= 0xffffff0f;  /* AND.L	#$ffffff0f,D0 */
    {  /* CMP.L	#$00dff000,D0 */
        int32_t _lhs = (int32_t)(d0);
        int32_t _rhs = (int32_t)(0x00dff000);
        int32_t _cmp = _lhs - _rhs;
        flag_z = (_cmp == 0);
        flag_n = (_cmp < 0);
        flag_c = ((uint32_t)_lhs < (uint32_t)_rhs);
      }
    if (!flag_z) goto notthis;  /* not equal / nonzero */  /* BNE.B	notthis */
    {  /* MOVE.L	A0,chandataptr */
        uint32_t _mv = (uint32_t)(a0);
        WRITE32((uintptr_t)chandataptr, _mv);
        flag_z = ((int32_t)(_mv) == 0);
        flag_n = ((int32_t)(_mv) < 0);
        flag_v = 0; flag_c = 0;
      }
    goto endsloop;  /* BRA.B	endsloop */
  notthis:
    a0 = (uint32_t)((int32_t)a0 + (int32_t)(int16_t)(2));  /* ADDQ.L	#2,A0 */
    if ((int16_t)(--d7) >= 0) goto sloop;  /* DBF	D7,sloop */
  endsloop:
    /* UNIMPLEMENTED: PULL */  /* PULL	all */
    return;  /* RTS */
    return;  /* RTS */
}
static void Interrupt(void) {
    /* UNIMPLEMENTED: PUSH */  /* PUSH	all */
    /* UNIMPLEMENTED: PUSHR */  /* PUSHR	A5 */
    /* call interrupt */
    {  /* MOVE.L	modptr,A0 */
        uint32_t _mv = (uint32_t)(READ32((uintptr_t)modptr));
        a0 = _mv;
        flag_z = ((int32_t)(_mv) == 0);
        flag_n = ((int32_t)(_mv) < 0);
        flag_v = 0; flag_c = 0;
      }
    { uintptr_t _jt=(uintptr_t)(READ32(a0 + 12)); if(_jt) ((void(*)(void))_jt)(); }  /* JSR	12(A0) */
    /* UNIMPLEMENTED: PULLR */  /* PULLR	A5 */
    {  /* MOVE.L	chandataptr,A0 */
        uint32_t _mv = (uint32_t)(READ32((uintptr_t)chandataptr));
        a0 = _mv;
        flag_z = ((int32_t)(_mv) == 0);
        flag_n = ((int32_t)(_mv) < 0);
        flag_v = 0; flag_c = 0;
      }
    a0 = (uint32_t)((int32_t)a0 + (int32_t)(int16_t)(10));  /* ADD	#10,A0 */
    {  /* MOVE	(A0),D0 */
        uint32_t _mv = (uint32_t)(READ32(a0));
        d0 = _mv;
        flag_z = ((int32_t)(_mv) == 0);
        flag_n = ((int32_t)(_mv) < 0);
        flag_v = 0; flag_c = 0;
      }
    {  /* MOVE	39(A0),D1 */
        uint32_t _mv = (uint32_t)(READ32(a0 + 39));
        d1 = _mv;
        flag_z = ((int32_t)(_mv) == 0);
        flag_n = ((int32_t)(_mv) < 0);
        flag_v = 0; flag_c = 0;
      }
    {  /* MOVE	40(A0),D2 */
        uint32_t _mv = (uint32_t)(READ32(a0 + 40));
        d2 = _mv;
        flag_z = ((int32_t)(_mv) == 0);
        flag_n = ((int32_t)(_mv) < 0);
        flag_v = 0; flag_c = 0;
      }
    {  /* MOVE	41(A0),D3 */
        uint32_t _mv = (uint32_t)(READ32(a0 + 41));
        d3 = _mv;
        flag_z = ((int32_t)(_mv) == 0);
        flag_n = ((int32_t)(_mv) < 0);
        flag_v = 0; flag_c = 0;
      }
    {  /* TST.L	firsttime */
        uint32_t _tst = (uint32_t)(READ32((uintptr_t)firsttime));
        flag_z = (_tst == 0);
        flag_n = ((int32_t)(_tst) < 0);
        flag_c = 0; flag_v = 0;
      }
    if (!flag_z) goto notfirsttime;  /* not equal / nonzero */  /* BNE.B	notfirsttime */
    /* MOVEM: no addr operand */  /* MOVEM	D0,D1,D2,D3,startdata */
    WRITE8((uintptr_t)firsttime, 0xFF);  /* ST	firsttime */
    goto wasfirsttime;  /* BRA.B	wasfirsttime */
  notfirsttime:
    /* MOVEM: no addr operand */  /* MOVEM	startdata,D4,D5,D6,D7 */
    {  /* CMP	D0,D4 */
        int32_t _lhs = (int32_t)(d4);
        int32_t _rhs = (int32_t)(d0);
        int32_t _cmp = _lhs - _rhs;
        flag_z = (_cmp == 0);
        flag_n = (_cmp < 0);
        flag_c = ((uint32_t)_lhs < (uint32_t)_rhs);
      }
    if (!flag_z) goto makeendpossible;  /* not equal / nonzero */  /* BNE.B	makeendpossible */
    {  /* CMP	D1,D5 */
        int32_t _lhs = (int32_t)(d5);
        int32_t _rhs = (int32_t)(d1);
        int32_t _cmp = _lhs - _rhs;
        flag_z = (_cmp == 0);
        flag_n = (_cmp < 0);
        flag_c = ((uint32_t)_lhs < (uint32_t)_rhs);
      }
    if (!flag_z) goto makeendpossible;  /* not equal / nonzero */  /* BNE.B	makeendpossible */
    {  /* CMP	D2,D6 */
        int32_t _lhs = (int32_t)(d6);
        int32_t _rhs = (int32_t)(d2);
        int32_t _cmp = _lhs - _rhs;
        flag_z = (_cmp == 0);
        flag_n = (_cmp < 0);
        flag_c = ((uint32_t)_lhs < (uint32_t)_rhs);
      }
    if (!flag_z) goto makeendpossible;  /* not equal / nonzero */  /* BNE.B	makeendpossible */
    {  /* CMP	D3,D7 */
        int32_t _lhs = (int32_t)(d7);
        int32_t _rhs = (int32_t)(d3);
        int32_t _cmp = _lhs - _rhs;
        flag_z = (_cmp == 0);
        flag_n = (_cmp < 0);
        flag_c = ((uint32_t)_lhs < (uint32_t)_rhs);
      }
    if (!flag_z) goto makeendpossible;  /* not equal / nonzero */  /* BNE.B	makeendpossible */
    {  /* TST.L	endpossible */
        uint32_t _tst = (uint32_t)(READ32((uintptr_t)endpossible));
        flag_z = (_tst == 0);
        flag_n = ((int32_t)(_tst) < 0);
        flag_c = 0; flag_v = 0;
      }
    if (flag_z) goto wasfirsttime;  /* equal / zero */  /* BEQ.B	wasfirsttime */
    {  /* MOVE.L	dtg_SongEnd(A5),A0 */
        uint32_t _mv = (uint32_t)(READ32(a5 + (intptr_t)dtg_SongEnd));
        a0 = _mv;
        flag_z = ((int32_t)(_mv) == 0);
        flag_n = ((int32_t)(_mv) < 0);
        flag_v = 0; flag_c = 0;
      }
    { uintptr_t _jt=(uintptr_t)(a0); if(_jt) ((void(*)(void))_jt)(); }  /* JSR	(A0) */
    goto wasfirsttime;  /* BRA.B	wasfirsttime */
  makeendpossible:
    WRITE8((uintptr_t)endpossible, 0xFF);  /* ST	endpossible */
  wasfirsttime:
    /* UNIMPLEMENTED: PULL */  /* PULL	all */
    return;  /* RTS */
    return;  /* RTS */
}
static void EndSound(void) {
    /* UNIMPLEMENTED: PUSH */  /* PUSH	all */
    a2 = (uint32_t)0xdff000;  /* LEA	$DFF000,A2 */
    d0 = (uint32_t)(int32_t)(int8_t)(0);  /* MOVEQ	#0,D0 */
    {  /* MOVE	D0,aud0vol(A2) */
        uint32_t _mv = (uint32_t)(d0);
        WRITE32(a2 + (intptr_t)aud0vol, _mv);
        flag_z = ((int32_t)(_mv) == 0);
        flag_n = ((int32_t)(_mv) < 0);
        flag_v = 0; flag_c = 0;
      }
    {  /* MOVE	D0,aud1vol(A2) */
        uint32_t _mv = (uint32_t)(d0);
        WRITE32(a2 + (intptr_t)aud1vol, _mv);
        flag_z = ((int32_t)(_mv) == 0);
        flag_n = ((int32_t)(_mv) < 0);
        flag_v = 0; flag_c = 0;
      }
    {  /* MOVE	D0,aud2vol(A2) */
        uint32_t _mv = (uint32_t)(d0);
        WRITE32(a2 + (intptr_t)aud2vol, _mv);
        flag_z = ((int32_t)(_mv) == 0);
        flag_n = ((int32_t)(_mv) < 0);
        flag_v = 0; flag_c = 0;
      }
    {  /* MOVE	D0,aud3vol(A2) */
        uint32_t _mv = (uint32_t)(d0);
        WRITE32(a2 + (intptr_t)aud3vol, _mv);
        flag_z = ((int32_t)(_mv) == 0);
        flag_n = ((int32_t)(_mv) < 0);
        flag_v = 0; flag_c = 0;
      }
    {  /* MOVE	#$000f,dmacon(A2) */
        uint32_t _mv = (uint32_t)(0x000f);
        WRITE32(a2 + (intptr_t)dmacon, _mv);
        flag_z = ((int32_t)(_mv) == 0);
        flag_n = ((int32_t)(_mv) < 0);
        flag_v = 0; flag_c = 0;
      }
    /* UNIMPLEMENTED: PULL */  /* PULL	all */
    return;  /* RTS */
    return;  /* RTS */
}
static void EndPlayer(void) {
    {  /* MOVE.L	dtg_AudioFree(A5),A0 */
        uint32_t _mv = (uint32_t)(READ32(a5 + (intptr_t)dtg_AudioFree));
        a0 = _mv;
        flag_z = ((int32_t)(_mv) == 0);
        flag_n = ((int32_t)(_mv) < 0);
        flag_v = 0; flag_c = 0;
      }
    { uintptr_t _jt=(uintptr_t)(a0); if(_jt) ((void(*)(void))_jt)(); }  /* JSR	(A0) */
    return;  /* RTS */
  setvolume:
    /* UNIMPLEMENTED: PUSH */  /* PUSH	all */
    d0 = (uint32_t)(int32_t)(int8_t)(0);  /* MOVEQ	#0,D0 */
    {  /* MOVE	dtg_SndVol(A5),D0 */
        uint32_t _mv = (uint32_t)(READ32(a5 + (intptr_t)dtg_SndVol));
        d0 = _mv;
        flag_z = ((int32_t)(_mv) == 0);
        flag_n = ((int32_t)(_mv) < 0);
        flag_v = 0; flag_c = 0;
      }
    d1 = (uint32_t)(int32_t)(int8_t)(15);  /* MOVEQ	#15,D1 */
    {  /* MOVE.L	modptr,A0 */
        uint32_t _mv = (uint32_t)(READ32((uintptr_t)modptr));
        a0 = _mv;
        flag_z = ((int32_t)(_mv) == 0);
        flag_n = ((int32_t)(_mv) < 0);
        flag_v = 0; flag_c = 0;
      }
    { uintptr_t _jt=(uintptr_t)(READ32(a0 + 8)); if(_jt) ((void(*)(void))_jt)(); }  /* JSR	8(A0) */
    /* UNIMPLEMENTED: PULL */  /* PULL	all */
    return;  /* RTS */
    return;  /* RTS */
}
static void setvolume(void);


/* ====================================================================
 * Code Section -- Transpiled Functions
 * ==================================================================== */
/* T */

static void _anon0(void) {
  /* UNIMPLEMENTED: INCDIR */  /* INCDIR	asm */
}


/* -- SECTION maplayer ------------------------------------------ */

static void _anon1(void) {
  d0 = (uint32_t)(int32_t)(int8_t)(-1);  /* MOVEQ	#-1,D0 */
  return;  /* RTS */
}


/* --- Check2 --- */
static void Check2(void) {
  {  /* MOVE.L	dtg_ChkData(A5),A0 */
      uint32_t _mv = (uint32_t)(READ32(a5 + (intptr_t)dtg_ChkData));
      a0 = _mv;
      flag_z = ((int32_t)(_mv) == 0);
      flag_n = ((int32_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  /* check file format */
  checktype1();  /* BSR	checktype1 */
  return;  /* RTS */
}


/* --- checktype1 --- */


/* --- startdata --- */
static void startdata(void) {
  /* UNIMPLEMENTED: DCB */  /* DCB	#4,#0 */
}

/* Patch DC.L label references with runtime addresses */
static void _ds_init(void) {
  WRITE32((uintptr_t)(_ds + 2), (uint32_t)(uintptr_t)table);
  WRITE32((uintptr_t)(_ds + 142), (uint32_t)(uintptr_t)playername);
}


/* TRANSPILER WARNINGS:
 * Line 131: Custom chip write $dff000 — emitted as no-op
 */
/* ===== WASM Harness (appended) ===== */
#include "paula_soft.h"
#include <stdlib.h>
#include <string.h>

#ifdef __EMSCRIPTEN__
#include <emscripten.h>
#define EXPORT EMSCRIPTEN_KEEPALIVE
#else
#define EXPORT
#endif

static int g_initialized = 0;
static double g_frames_per_tick = 0.0;
static double g_accum = 0.0;
static uint8_t *g_song_buf = NULL;
static uint32_t g_tick_count = 0;
static double g_output_rate = (double)PAULA_RATE_PAL;

#define VBLANK_HZ 50.0

EXPORT int player_init(const uint8_t *module_data, uint32_t module_size) {
    paula_reset();
    g_accum = 0.0;
    g_tick_count = 0;
    g_frames_per_tick = g_output_rate / VBLANK_HZ;

    if (g_song_buf) { free(g_song_buf); g_song_buf = NULL; }

    g_song_buf = (uint8_t *)malloc(module_size);
    if (!g_song_buf) return -1;
    memcpy(g_song_buf, module_data, module_size);

    a0 = (uint32_t)(uintptr_t)g_song_buf;
    InitSound();
    InitPlayer();

    g_initialized = 1;
    return 0;
}

EXPORT int player_render(float *buf, int frames) {
    if (!g_initialized) return 0;
    float *out = buf;
    int remaining = frames;

    while (remaining > 0) {
        double until_tick = g_frames_per_tick - g_accum;
        int n = (int)until_tick;
        if (n < 1) n = 1;
        if (n > remaining) n = remaining;

        int got = paula_render(out, n);
        out += got * 2;
        remaining -= got;
        g_accum += (double)got;

        if (g_accum >= g_frames_per_tick) {
            g_accum -= g_frames_per_tick;
            Interrupt();
            g_tick_count++;
        }
    }
    return frames;
}

EXPORT void player_stop(void) {
    if (g_initialized) {
        EndPlayer();
        paula_reset();
        if (g_song_buf) { free(g_song_buf); g_song_buf = NULL; }
        g_initialized = 0;
    }
}

EXPORT void player_set_sample_rate(int rate) {
    g_output_rate = (double)rate;
    paula_set_output_rate((float)rate);
    g_frames_per_tick = g_output_rate / VBLANK_HZ;
}

EXPORT int player_is_finished(void) { return 0; }
EXPORT int player_get_subsong_count(void) { return 1; }
EXPORT void player_set_subsong(int n) { (void)n; }
EXPORT const char* player_get_title(void) { return "Music Artist"; }
EXPORT double player_detect_duration(void) { return 0.0; }
