import type { InstrumentPreset } from '../../types/instrument';

// ============================================================================
// CHIPTUNE PRESETS (12) - 8-bit style with arpeggio patterns
// ============================================================================

export const CHIP_PRESETS: InstrumentPreset['config'][] = [
  // Classic chiptune leads with arpeggios
  {
    type: 'synth' as const,
    name: 'NES Major Lead',
    synthType: 'ChipSynth',
    chipSynth: {
      channel: 'pulse1',
      pulse: { duty: 50 },
      bitDepth: 8,
      sampleRate: 22050,
      envelope: { attack: 1, decay: 250, sustain: 0, release: 150 },
      vibrato: { speed: 5, depth: 15, delay: 200 },
      arpeggio: { enabled: true, speed: 15, speedUnit: 'hz', steps: [{ noteOffset: 0 }, { noteOffset: 4 }, { noteOffset: 7 }, { noteOffset: 12 }], mode: 'loop' },
    },
    effects: [],
    volume: -10,
    pan: 0,
  },
  {
    type: 'synth' as const,
    name: 'C64 Minor Arp',
    synthType: 'ChipSynth',
    chipSynth: {
      channel: 'pulse1',
      pulse: { duty: 25 },
      bitDepth: 8,
      sampleRate: 22050,
      envelope: { attack: 1, decay: 300, sustain: 0, release: 200 },
      vibrato: { speed: 4, depth: 10, delay: 300 },
      arpeggio: { enabled: true, speed: 12, speedUnit: 'hz', steps: [{ noteOffset: 0 }, { noteOffset: 3 }, { noteOffset: 7 }, { noteOffset: 12 }], mode: 'loop' },
    },
    effects: [],
    volume: -10,
    pan: 0,
  },
  {
    type: 'synth' as const,
    name: 'SID Dim7 Pad',
    synthType: 'ChipSynth',
    chipSynth: {
      channel: 'pulse1',
      pulse: { duty: 50 },
      bitDepth: 8,
      sampleRate: 22050,
      envelope: { attack: 50, decay: 600, sustain: 0, release: 500 },
      vibrato: { speed: 3, depth: 8, delay: 100 },
      arpeggio: { enabled: true, speed: 8, speedUnit: 'hz', steps: [{ noteOffset: 0 }, { noteOffset: 3 }, { noteOffset: 6 }, { noteOffset: 9 }], mode: 'loop' },
    },
    effects: [],
    volume: -12,
    pan: 0,
  },
  {
    type: 'synth' as const,
    name: 'Gameboy Sus4',
    synthType: 'ChipSynth',
    chipSynth: {
      channel: 'pulse2',
      pulse: { duty: 12.5 },
      bitDepth: 4,
      sampleRate: 16384,
      envelope: { attack: 1, decay: 200, sustain: 0, release: 100 },
      vibrato: { speed: 6, depth: 20, delay: 150 },
      arpeggio: { enabled: true, speed: 18, speedUnit: 'hz', steps: [{ noteOffset: 0 }, { noteOffset: 5 }, { noteOffset: 7 }], mode: 'loop' },
    },
    effects: [],
    volume: -8,
    pan: 0,
  },
  {
    type: 'synth' as const,
    name: 'Atari Dom7',
    synthType: 'ChipSynth',
    chipSynth: {
      channel: 'pulse1',
      pulse: { duty: 50 },
      bitDepth: 4,
      sampleRate: 15720,
      envelope: { attack: 1, decay: 300, sustain: 0, release: 200 },
      vibrato: { speed: 0, depth: 0, delay: 0 },
      arpeggio: { enabled: true, speed: 20, speedUnit: 'hz', steps: [{ noteOffset: 0 }, { noteOffset: 4 }, { noteOffset: 7 }, { noteOffset: 10 }], mode: 'loop' },
    },
    effects: [],
    volume: -10,
    pan: 0,
  },
  {
    type: 'synth' as const,
    name: 'Amiga Power Oct',
    synthType: 'ChipSynth',
    chipSynth: {
      channel: 'triangle',
      bitDepth: 8,
      sampleRate: 28867,
      envelope: { attack: 5, decay: 300, sustain: 0, release: 250 },
      vibrato: { speed: 4, depth: 12, delay: 200 },
      arpeggio: { enabled: true, speed: 14, speedUnit: 'hz', steps: [{ noteOffset: 0 }, { noteOffset: 7 }, { noteOffset: 12 }], mode: 'loop' },
    },
    effects: [],
    volume: -10,
    pan: 0,
  },
  {
    type: 'synth' as const,
    name: 'Fast Maj9 Stab',
    synthType: 'ChipSynth',
    chipSynth: {
      channel: 'pulse1',
      pulse: { duty: 25 },
      bitDepth: 8,
      sampleRate: 22050,
      envelope: { attack: 1, decay: 150, sustain: 0, release: 80 },
      vibrato: { speed: 0, depth: 0, delay: 0 },
      arpeggio: { enabled: true, speed: 30, speedUnit: 'hz', steps: [{ noteOffset: 0 }, { noteOffset: 4 }, { noteOffset: 7 }, { noteOffset: 11 }, { noteOffset: 14 }], mode: 'loop' },
    },
    effects: [],
    volume: -10,
    pan: 0,
  },
  {
    type: 'synth' as const,
    name: 'Slow Min7 Sweep',
    synthType: 'ChipSynth',
    chipSynth: {
      channel: 'pulse1',
      pulse: { duty: 50 },
      bitDepth: 8,
      sampleRate: 22050,
      envelope: { attack: 100, decay: 800, sustain: 0, release: 600 },
      vibrato: { speed: 3, depth: 15, delay: 500 },
      arpeggio: { enabled: true, speed: 4, speedUnit: 'hz', steps: [{ noteOffset: 0 }, { noteOffset: 3 }, { noteOffset: 7 }, { noteOffset: 10 }], mode: 'loop' },
    },
    effects: [],
    volume: -12,
    pan: 0,
  },
  // Non-arpeggio chip sounds
  {
    type: 'synth' as const,
    name: 'Chip Square Lead',
    synthType: 'ChipSynth',
    chipSynth: {
      channel: 'pulse1',
      pulse: { duty: 50 },
      bitDepth: 8,
      sampleRate: 22050,
      envelope: { attack: 5, decay: 300, sustain: 0, release: 200 },
      vibrato: { speed: 6, depth: 15, delay: 200 },
      arpeggio: { enabled: false, speed: 15, speedUnit: 'hz', steps: [{ noteOffset: 0 }, { noteOffset: 4 }, { noteOffset: 7 }], mode: 'loop' },
    },
    effects: [],
    volume: -10,
    pan: 0,
  },
  {
    type: 'synth' as const,
    name: 'Triangle Bass',
    synthType: 'ChipSynth',
    chipSynth: {
      channel: 'triangle',
      bitDepth: 4,
      sampleRate: 22050,
      envelope: { attack: 1, decay: 400, sustain: 0, release: 150 },
      vibrato: { speed: 0, depth: 0, delay: 0 },
      arpeggio: { enabled: false, speed: 15, speedUnit: 'hz', steps: [{ noteOffset: 0 }, { noteOffset: 12 }], mode: 'loop' },
    },
    effects: [],
    volume: -6,
    pan: 0,
  },
  {
    type: 'synth' as const,
    name: 'Noise Snare',
    synthType: 'ChipSynth',
    chipSynth: {
      channel: 'noise',
      bitDepth: 1,
      sampleRate: 22050,
      envelope: { attack: 1, decay: 100, sustain: 0, release: 50 },
      vibrato: { speed: 0, depth: 0, delay: 0 },
      arpeggio: { enabled: false, speed: 15, speedUnit: 'hz', steps: [{ noteOffset: 0 }], mode: 'loop' },
    },
    effects: [],
    volume: -10,
    pan: 0,
  },
  {
    type: 'synth' as const,
    name: 'Octave Jump',
    synthType: 'ChipSynth',
    chipSynth: {
      channel: 'pulse2',
      pulse: { duty: 25 },
      bitDepth: 8,
      sampleRate: 22050,
      envelope: { attack: 1, decay: 250, sustain: 0, release: 150 },
      vibrato: { speed: 5, depth: 10, delay: 250 },
      arpeggio: { enabled: true, speed: 10, speedUnit: 'hz', steps: [{ noteOffset: 0 }, { noteOffset: 12 }, { noteOffset: 24 }], mode: 'loop' },
    },
    effects: [],
    volume: -10,
    pan: 0,
  },
];
