import type { InstrumentPreset } from '../../types/instrument';

// ============================================================================
// DRUM PRESETS (8)
// ============================================================================

export const DRUM_PRESETS: InstrumentPreset['config'][] = [
  V2_PRESET_KICK,
  V2_PRESET_SNARE,
  V2_PRESET_HAT,
  // Membrane Synth Kicks
  {
    type: 'synth' as const,
    name: '808 Kick',
    synthType: 'MembraneSynth',
    oscillator: { type: 'sine', detune: 0, octave: -2 },
    envelope: { attack: 1, decay: 500, sustain: 0, release: 100 },
    filter: { type: 'lowpass', frequency: 100, Q: 1, rolloff: -24 },
    effects: [],
    volume: -6,
    pan: 0,
  },
  {
    type: 'synth' as const,
    name: '909 Kick',
    synthType: 'MembraneSynth',
    oscillator: { type: 'sine', detune: 0, octave: -2 },
    envelope: { attack: 1, decay: 300, sustain: 0, release: 50 },
    filter: { type: 'lowpass', frequency: 80, Q: 2, rolloff: -24 },
    effects: [],
    volume: -6,
    pan: 0,
  },
  {
    type: 'synth' as const,
    name: 'Hardcore Kick',
    synthType: 'MembraneSynth',
    oscillator: { type: 'sine', detune: 0, octave: -2 },
    envelope: { attack: 1, decay: 150, sustain: 0, release: 20 },
    filter: { type: 'lowpass', frequency: 120, Q: 3, rolloff: -24 },
    effects: [],
    volume: -4,
    pan: 0,
  },
  {
    type: 'synth' as const,
    name: 'DnB Snare',
    synthType: 'NoiseSynth',
    oscillator: { type: 'sine', detune: 0, octave: 0 }, // NoiseSynth doesn't use waveform type
    envelope: { attack: 1, decay: 200, sustain: 0, release: 100 },
    filter: { type: 'highpass', frequency: 300, Q: 1, rolloff: -12 },
    effects: [],
    volume: -8,
    pan: 0,
  },
  {
    type: 'synth' as const,
    name: 'Clap',
    synthType: 'NoiseSynth',
    oscillator: { type: 'sine', detune: 0, octave: 0 }, // NoiseSynth doesn't use waveform type
    envelope: { attack: 1, decay: 150, sustain: 0, release: 50 },
    filter: { type: 'bandpass', frequency: 1000, Q: 2, rolloff: -24 },
    effects: [],
    volume: -10,
    pan: 0,
  },
  {
    type: 'synth' as const,
    name: 'Closed Hat',
    synthType: 'MetalSynth',
    oscillator: { type: 'square', detune: 0, octave: 0 },
    envelope: { attack: 1, decay: 50, sustain: 0, release: 20 },
    filter: { type: 'highpass', frequency: 8000, Q: 1, rolloff: -12 },
    effects: [],
    volume: -12,
    pan: 0,
  },
  {
    type: 'synth' as const,
    name: 'Open Hat',
    synthType: 'MetalSynth',
    oscillator: { type: 'square', detune: 0, octave: 0 },
    envelope: { attack: 1, decay: 300, sustain: 0, release: 200 },
    filter: { type: 'highpass', frequency: 7000, Q: 1, rolloff: -12 },
    effects: [],
    volume: -12,
    pan: 0,
  },
  {
    type: 'synth' as const,
    name: 'Crash',
    synthType: 'MetalSynth',
    oscillator: { type: 'square', detune: 0, octave: 0 },
    envelope: { attack: 10, decay: 1500, sustain: 0, release: 1000 },
    filter: { type: 'highpass', frequency: 6000, Q: 1, rolloff: -12 },
    effects: [],
    volume: -14,
    pan: 0,
  },
  {
    type: 'synth' as const,
    name: 'Synth Low Tom',
    synthType: 'MembraneSynth',
    oscillator: { type: 'sine', detune: 0, octave: -1 },
    envelope: { attack: 1, decay: 400, sustain: 0, release: 100 },
    effects: [],
    volume: -8,
    pan: -20,
  },
  {
    type: 'synth' as const,
    name: 'Synth Mid Tom',
    synthType: 'MembraneSynth',
    oscillator: { type: 'sine', detune: 0, octave: -1 },
    envelope: { attack: 1, decay: 350, sustain: 0, release: 80 },
    effects: [],
    volume: -8,
    pan: 0,
  },
  {
    type: 'synth' as const,
    name: 'Synth Hi Tom',
    synthType: 'MembraneSynth',
    oscillator: { type: 'sine', detune: 0, octave: 0 },
    envelope: { attack: 1, decay: 300, sustain: 0, release: 60 },
    effects: [],
    volume: -8,
    pan: 20,
  },
  
  // === SYNARE PRESETS ===
  ...SYNARE_PRESETS,
];
