import type { InstrumentPreset } from '../../types/instrument';

// DRUMNIBUS SAMPLE PACK - Featured Samples (by Legowelt)
// Full pack available in Sample Packs browser (229 samples)
// ============================================================================

export const DRUMNIBUS_PRESETS: InstrumentPreset['config'][] = [
  // Kicks
  {
    type: 'synth' as const,
    name: 'DN 808 A1200',
    synthType: 'Sampler',
    sample: {
      url: 'data/samples/packs/drumnibus/kicks/BD_808A1200.wav',
      baseNote: 'C4',
      detune: 0,
      loop: false,
      loopStart: 0,
      loopEnd: 0,
      reverse: false,
      playbackRate: 1,
    },
    effects: [],
    volume: -6,
    pan: 0,
  },
  {
    type: 'synth' as const,
    name: 'DN Electro Kick',
    synthType: 'Sampler',
    sample: {
      url: 'data/samples/packs/drumnibus/kicks/BD_Electro1shorter.wav',
      baseNote: 'C4',
      detune: 0,
      loop: false,
      loopStart: 0,
      loopEnd: 0,
      reverse: false,
      playbackRate: 1,
    },
    effects: [],
    volume: -6,
    pan: 0,
  },
  {
    type: 'synth' as const,
    name: 'DN SubThud',
    synthType: 'Sampler',
    sample: {
      url: 'data/samples/packs/drumnibus/kicks/BD_SubThud.wav',
      baseNote: 'C4',
      detune: 0,
      loop: false,
      loopStart: 0,
      loopEnd: 0,
      reverse: false,
      playbackRate: 1,
    },
    effects: [],
    volume: -6,
    pan: 0,
  },
  {
    type: 'synth' as const,
    name: 'DN Punchtron Kick',
    synthType: 'Sampler',
    sample: {
      url: 'data/samples/packs/drumnibus/kicks/BD_Punchtron.wav',
      baseNote: 'C4',
      detune: 0,
      loop: false,
      loopStart: 0,
      loopEnd: 0,
      reverse: false,
      playbackRate: 1,
    },
    effects: [],
    volume: -6,
    pan: 0,
  },
  // Snares
  {
    type: 'synth' as const,
    name: 'DN 808 Snare',
    synthType: 'Sampler',
    sample: {
      url: 'data/samples/packs/drumnibus/snares/SD_808A1200.wav',
      baseNote: 'C4',
      detune: 0,
      loop: false,
      loopStart: 0,
      loopEnd: 0,
      reverse: false,
      playbackRate: 1,
    },
    effects: [],
    volume: -6,
    pan: 0,
  },
  {
    type: 'synth' as const,
    name: 'DN Analog Noise',
    synthType: 'Sampler',
    sample: {
      url: 'data/samples/packs/drumnibus/snares/SD_Analog_Noise1.wav',
      baseNote: 'C4',
      detune: 0,
      loop: false,
      loopStart: 0,
      loopEnd: 0,
      reverse: false,
      playbackRate: 1,
    },
    effects: [],
    volume: -6,
    pan: 0,
  },
  {
    type: 'synth' as const,
    name: 'DN Electro 7000',
    synthType: 'Sampler',
    sample: {
      url: 'data/samples/packs/drumnibus/snares/SD_electro7000.wav',
      baseNote: 'C4',
      detune: 0,
      loop: false,
      loopStart: 0,
      loopEnd: 0,
      reverse: false,
      playbackRate: 1,
    },
    effects: [],
    volume: -6,
    pan: 0,
  },
  {
    type: 'synth' as const,
    name: 'DN Wolf Snare',
    synthType: 'Sampler',
    sample: {
      url: 'data/samples/packs/drumnibus/snares/SD_Wolf1.wav',
      baseNote: 'C4',
      detune: 0,
      loop: false,
      loopStart: 0,
      loopEnd: 0,
      reverse: false,
      playbackRate: 1,
    },
    effects: [],
    volume: -6,
    pan: 0,
  },
  // Hi-Hats
  {
    type: 'synth' as const,
    name: 'DN Closed Hat',
    synthType: 'Sampler',
    sample: {
      url: 'data/samples/packs/drumnibus/hihats/CH_Digidap.wav',
      baseNote: 'C4',
      detune: 0,
      loop: false,
      loopStart: 0,
      loopEnd: 0,
      reverse: false,
      playbackRate: 1,
    },
    effects: [],
    volume: -8,
    pan: 0,
  },
  {
    type: 'synth' as const,
    name: 'DN Open Hat',
    synthType: 'Sampler',
    sample: {
      url: 'data/samples/packs/drumnibus/hihats/OH_Digidap.wav',
      baseNote: 'C4',
      detune: 0,
      loop: false,
      loopStart: 0,
      loopEnd: 0,
      reverse: false,
      playbackRate: 1,
    },
    effects: [],
    volume: -8,
    pan: 0,
  },
  {
    type: 'synth' as const,
    name: 'DN Analog Hat',
    synthType: 'Sampler',
    sample: {
      url: 'data/samples/packs/drumnibus/hihats/OH_AnalogHihat1.wav',
      baseNote: 'C4',
      detune: 0,
      loop: false,
      loopStart: 0,
      loopEnd: 0,
      reverse: false,
      playbackRate: 1,
    },
    effects: [],
    volume: -8,
    pan: 0,
  },
  {
    type: 'synth' as const,
    name: 'DN Cymbal',
    synthType: 'Sampler',
    sample: {
      url: 'data/samples/packs/drumnibus/hihats/CYM_Synthique.wav',
      baseNote: 'C4',
      detune: 0,
      loop: false,
      loopStart: 0,
      loopEnd: 0,
      reverse: false,
      playbackRate: 1,
    },
    effects: [],
    volume: -10,
    pan: 0,
  },
  // Percussion
  {
    type: 'synth' as const,
    name: 'DN Clap',
    synthType: 'Sampler',
    sample: {
      url: 'data/samples/packs/drumnibus/percussion/CLAP_Punchtron.wav',
      baseNote: 'C4',
      detune: 0,
      loop: false,
      loopStart: 0,
      loopEnd: 0,
      reverse: false,
      playbackRate: 1,
    },
    effects: [],
    volume: -6,
    pan: 0,
  },
  {
    type: 'synth' as const,
    name: 'DN Clave',
    synthType: 'Sampler',
    sample: {
      url: 'data/samples/packs/drumnibus/percussion/CLAVE_Simple.wav',
      baseNote: 'C4',
      detune: 0,
      loop: false,
      loopStart: 0,
      loopEnd: 0,
      reverse: false,
      playbackRate: 1,
    },
    effects: [],
    volume: -6,
    pan: 0,
  },
  {
    type: 'synth' as const,
    name: 'DN Tom',
    synthType: 'Sampler',
    sample: {
      url: 'data/samples/packs/drumnibus/percussion/TOM_Magnotron.wav',
      baseNote: 'C4',
      detune: 0,
      loop: false,
      loopStart: 0,
      loopEnd: 0,
      reverse: false,
      playbackRate: 1,
    },
    effects: [],
    volume: -6,
    pan: 0,
  },
  {
    type: 'synth' as const,
    name: 'DN Lazer',
    synthType: 'Sampler',
    sample: {
      url: 'data/samples/packs/drumnibus/percussion/LAZ_R900.wav',
      baseNote: 'C4',
      detune: 0,
      loop: false,
      loopStart: 0,
      loopEnd: 0,
      reverse: false,
      playbackRate: 1,
    },
    effects: [],
    volume: -8,
    pan: 0,
  },
  // FX
  {
    type: 'synth' as const,
    name: 'DN Sonar',
    synthType: 'Sampler',
    sample: {
      url: 'data/samples/packs/drumnibus/fx/FX_Sonar.wav',
      baseNote: 'C4',
      detune: 0,
      loop: false,
      loopStart: 0,
      loopEnd: 0,
      reverse: false,
      playbackRate: 1,
    },
    effects: [],
    volume: -10,
    pan: 0,
  },
  {
    type: 'synth' as const,
    name: 'DN Laser',
    synthType: 'Sampler',
    sample: {
      url: 'data/samples/packs/drumnibus/fx/FX_NomiLaser1.wav',
      baseNote: 'C4',
      detune: 0,
      loop: false,
      loopStart: 0,
      loopEnd: 0,
      reverse: false,
      playbackRate: 1,
    },
    effects: [],
    volume: -10,
    pan: 0,
  },
  {
    type: 'synth' as const,
    name: 'DN Burst',
    synthType: 'Sampler',
    sample: {
      url: 'data/samples/packs/drumnibus/fx/FX_Burst1.wav',
      baseNote: 'C4',
      detune: 0,
      loop: false,
      loopStart: 0,
      loopEnd: 0,
      reverse: false,
      playbackRate: 1,
    },
    effects: [],
    volume: -10,
    pan: 0,
  },
];
