import type { InstrumentPreset } from '../../types/instrument';
import { VOWEL_FORMANTS } from '../../types/instrument';

// ============================================================================
// LEAD PRESETS (15)
// ============================================================================

export const LEAD_PRESETS: InstrumentPreset['config'][] = [
  // Pluck Synth
  {
    type: 'synth' as const,
    name: 'Trance Pluck',
    synthType: 'PluckSynth',
    oscillator: { type: 'sine', detune: 0, octave: 0 },
    envelope: { attack: 1, decay: 300, sustain: 0, release: 300 },
    filter: { type: 'lowpass', frequency: 4000, Q: 2, rolloff: -24 },
    effects: [],
    volume: -10,
    pan: 0,
  },
  {
    type: 'synth' as const,
    name: 'Pluck Keys',
    synthType: 'PluckSynth',
    oscillator: { type: 'square', detune: 0, octave: 0 },
    envelope: { attack: 1, decay: 500, sustain: 0, release: 500 },
    filter: { type: 'lowpass', frequency: 2500, Q: 1, rolloff: -12 },
    effects: [],
    volume: -10,
    pan: 0,
  },
  {
    type: 'synth' as const,
    name: 'Guitar Pluck',
    synthType: 'PluckSynth',
    oscillator: { type: 'sawtooth', detune: 0, octave: -1 },
    envelope: { attack: 5, decay: 200, sustain: 0, release: 100 },
    filter: { type: 'highpass', frequency: 200, Q: 1, rolloff: -12 },
    effects: [],
    volume: -8,
    pan: 0,
  },
  // AM Synth
  {
    type: 'synth' as const,
    name: 'AM Bell',
    synthType: 'ToneAM',
    oscillator: { type: 'sine', detune: 0, octave: 0 },
    envelope: { attack: 1, decay: 300, sustain: 0, release: 500 },
    effects: [],
    volume: -6,
    pan: 0,
  },
  {
    type: 'synth' as const,
    name: 'AM Sci-Fi',
    synthType: 'ToneAM',
    oscillator: { type: 'square', detune: 0, octave: 0 },
    envelope: { attack: 50, decay: 500, sustain: 0.5, release: 1000 },
    effects: [],
    volume: -6,
    pan: 0,
  },
  // FM Synth
  {
    type: 'synth' as const,
    name: 'FM Electric Piano',
    synthType: 'FMSynth',
    oscillator: { type: 'sine', detune: 0, octave: 0 },
    envelope: { attack: 1, decay: 500, sustain: 0.2, release: 500 },
    effects: [],
    volume: -6,
    pan: 0,
  },
  // Duo Synth
  {
    type: 'synth' as const,
    name: 'Duo Saw Lead',
    synthType: 'DuoSynth',
    oscillator: { type: 'sawtooth', detune: 10, octave: 0 },
    envelope: { attack: 10, decay: 200, sustain: 0.5, release: 200 },
    effects: [],
    volume: -8,
    pan: 0,
  },
  // Basic Synth
  {
    type: 'synth' as const,
    name: 'Square Lead',
    synthType: 'Synth',
    oscillator: { type: 'square', detune: 0, octave: 0 },
    envelope: { attack: 5, decay: 100, sustain: 0.8, release: 100 },
    effects: [],
    volume: -10,
    pan: 0,
  },
  {
    type: 'synth' as const,
    name: 'Supersaw Lead',
    synthType: 'DuoSynth',
    oscillator: { type: 'sawtooth', detune: 20, octave: 0 },
    envelope: { attack: 20, decay: 400, sustain: 0, release: 300 },
    filter: { type: 'lowpass', frequency: 3000, Q: 2, rolloff: -24 },
    effects: [],
    volume: -12,
    pan: 0,
  },
  {
    type: 'synth' as const,
    name: 'Acid Lead',
    synthType: 'MonoSynth',
    oscillator: { type: 'square', detune: 0, octave: 0 },
    envelope: { attack: 10, decay: 350, sustain: 0, release: 200 },
    filter: { type: 'lowpass', frequency: 2000, Q: 5, rolloff: -24 },
    effects: [],
    volume: -10,
    pan: 0,
  },
  {
    type: 'synth' as const,
    name: 'FM Stab',
    synthType: 'FMSynth',
    oscillator: { type: 'sine', detune: 0, octave: 0 },
    envelope: { attack: 1, decay: 300, sustain: 0, release: 100 },
    filter: { type: 'lowpass', frequency: 4000, Q: 3, rolloff: -24 },
    effects: [],
    volume: -10,
    pan: 0,
  },
  {
    type: 'synth' as const,
    name: 'Sync Lead',
    synthType: 'Synth',
    oscillator: { type: 'sawtooth', detune: 5, octave: 0 },
    envelope: { attack: 10, decay: 450, sustain: 0, release: 300 },
    filter: { type: 'lowpass', frequency: 2500, Q: 3, rolloff: -24 },
    effects: [],
    volume: -12,
    pan: 0,
  },
  {
    type: 'synth' as const,
    name: 'Chip Lead',
    synthType: 'Synth',
    oscillator: { type: 'square', detune: 0, octave: 0 },
    envelope: { attack: 1, decay: 250, sustain: 0, release: 100 },
    filter: { type: 'lowpass', frequency: 3000, Q: 1, rolloff: -12 },
    effects: [],
    volume: -8,
    pan: 0,
  },
  {
    type: 'synth' as const,
    name: 'Trance Pluck',
    synthType: 'PluckSynth',
    oscillator: { type: 'sine', detune: 0, octave: 0 },
    envelope: { attack: 1, decay: 300, sustain: 0, release: 300 },
    filter: { type: 'lowpass', frequency: 4000, Q: 2, rolloff: -24 },
    effects: [],
    volume: -10,
    pan: 0,
  },
  {
    type: 'synth' as const,
    name: 'Detuned Lead',
    synthType: 'DuoSynth',
    oscillator: { type: 'sawtooth', detune: 25, octave: 0 },
    envelope: { attack: 30, decay: 450, sustain: 0, release: 400 },
    filter: { type: 'lowpass', frequency: 2800, Q: 2, rolloff: -24 },
    effects: [],
    volume: -12,
    pan: 0,
  },
  {
    type: 'synth' as const,
    name: 'Filtered Lead',
    synthType: 'MonoSynth',
    oscillator: { type: 'sawtooth', detune: 0, octave: 0 },
    envelope: { attack: 20, decay: 400, sustain: 0, release: 300 },
    filter: { type: 'bandpass', frequency: 2000, Q: 10, rolloff: -24 },
    effects: [],
    volume: -10,
    pan: 0,
  },
  {
    type: 'synth' as const,
    name: 'AM Tremolo Lead',
    synthType: 'ToneAM',
    oscillator: { type: 'sine', detune: 0, octave: 0 },
    envelope: { attack: 10, decay: 300, sustain: 0.5, release: 200 },
    effects: [],
    volume: -8,
    pan: 0,
  },
  {
    type: 'synth' as const,
    name: 'FM Bell Lead',
    synthType: 'FMSynth',
    oscillator: { type: 'sine', detune: 0, octave: 1 },
    envelope: { attack: 1, decay: 1000, sustain: 0, release: 800 },
    effects: [],
    volume: -10,
    pan: 0,
  },
  {
    type: 'synth' as const,
    name: 'Harp Pluck',
    synthType: 'PluckSynth',
    oscillator: { type: 'sine', detune: 0, octave: 1 },
    envelope: { attack: 1, decay: 800, sustain: 0, release: 500 },
    effects: [],
    volume: -8,
    pan: 0,
  },
  {
    type: 'synth' as const,
    name: 'Nylon Guitar',
    synthType: 'PluckSynth',
    oscillator: { type: 'sawtooth', detune: 0, octave: 0 },
    envelope: { attack: 1, decay: 1200, sustain: 0, release: 1000 },
    effects: [],
    volume: -8,
    pan: 0,
  },
  {
    type: 'synth' as const,
    name: 'PWM Solo Lead',
    synthType: 'PWMSynth',
    pwmSynth: {
      pulseWidth: 20,
      pwmDepth: 40,
      pwmRate: 1.5,
      pwmWaveform: 'sine',
      oscillators: 2,
      detune: 5,
      envelope: { attack: 10, decay: 300, sustain: 0.6, release: 200 },
      filter: { type: 'lowpass', cutoff: 3000, resonance: 30, envelopeAmount: 20, keyTracking: 50 },
      filterEnvelope: { attack: 5, decay: 400, sustain: 0.2, release: 100 },
    },
    effects: [],
    volume: -10,
    pan: 0,
  },
  {
    type: 'synth' as const,
    name: 'Poly Brass',
    synthType: 'PolySynth',
    polySynth: {
      voiceCount: 6,
      voiceType: 'Synth',
      stealMode: 'oldest',
      oscillator: { type: 'sawtooth', detune: 5, octave: 0 },
      envelope: { attack: 50, decay: 400, sustain: 0.7, release: 200 },
      filter: { type: 'lowpass', frequency: 2000, Q: 1, rolloff: -12 },
      portamento: 0,
    },
    effects: [],
    volume: -10,
    pan: 0,
  },
  {
    type: 'synth' as const,
    name: 'SuperSaw Lead',
    synthType: 'SuperSaw',
    superSaw: {
      voices: 7,
      detune: 40,
      mix: 70,
      stereoSpread: 80,
      envelope: { attack: 10, decay: 300, sustain: 50, release: 200 },
      filter: { type: 'lowpass', cutoff: 5000, resonance: 20, envelopeAmount: 50 },
      filterEnvelope: { attack: 5, decay: 400, sustain: 0, release: 100 },
    },
    effects: [],
    volume: -12,
    pan: 0,
  },
  {
    type: 'synth' as const,
    name: 'Robot Talk',
    synthType: 'FormantSynth',
    formantSynth: {
      vowel: 'E',
      vowelMorph: { target: 'U', amount: 80, rate: 2, mode: 'manual' },
      oscillator: { type: 'square' },
      formants: { ...VOWEL_FORMANTS.E, bandwidth: 120 },
      envelope: { attack: 5, decay: 200, sustain: 0.5, release: 100 },
      brightness: 80,
    },
    effects: [],
    volume: -10,
    pan: 0,
  },
];
