import type { InstrumentPreset } from '../../types/instrument';
import { VOWEL_FORMANTS } from '../../types/instrument';

// ============================================================================
// PAD PRESETS (4)
// ============================================================================

export const PAD_PRESETS: InstrumentPreset['config'][] = [
  {
    type: 'synth' as const,
    name: 'Ambient Pad',
    synthType: 'Synth',
    oscillator: { type: 'sine', detune: 3, octave: 0 },
    envelope: { attack: 800, decay: 2000, sustain: 0, release: 1500 },
    filter: { type: 'lowpass', frequency: 1500, Q: 1, rolloff: -12 },
    effects: [],
    volume: -14,
    pan: 0,
  },
  {
    type: 'synth' as const,
    name: 'Dark Pad',
    synthType: 'DuoSynth',
    oscillator: { type: 'triangle', detune: 8, octave: 0 },
    envelope: { attack: 1000, decay: 2500, sustain: 0, release: 2000 },
    filter: { type: 'lowpass', frequency: 800, Q: 2, rolloff: -24 },
    effects: [],
    volume: -16,
    pan: 0,
  },
  {
    type: 'synth' as const,
    name: 'String Pad',
    synthType: 'Synth',
    oscillator: { type: 'sawtooth', detune: 5, octave: 0 },
    envelope: { attack: 500, decay: 1800, sustain: 0, release: 1200 },
    filter: { type: 'lowpass', frequency: 2000, Q: 1.5, rolloff: -12 },
    effects: [],
    volume: -14,
    pan: 0,
  },
  {
    type: 'synth' as const,
    name: 'Noise Sweep',
    synthType: 'NoiseSynth',
    oscillator: { type: 'sine', detune: 0, octave: 0 }, // NoiseSynth doesn't use waveform type
    envelope: { attack: 300, decay: 1500, sustain: 0, release: 1000 },
    filter: { type: 'bandpass', frequency: 1000, Q: 5, rolloff: -24 },
    effects: [],
    volume: -18,
    pan: 0,
  },
  {
    type: 'synth' as const,
    name: 'AM Atmospheric',
    synthType: 'ToneAM',
    oscillator: { type: 'sine', detune: 5, octave: 0 },
    envelope: { attack: 1500, decay: 3000, sustain: 0.8, release: 2000 },
    effects: [],
    volume: -12,
    pan: 0,
  },
  {
    type: 'synth' as const,
    name: 'Wavetable Evolving Pad',
    synthType: 'Wavetable',
    wavetable: {
      wavetableId: 'evolve-1',
      morphPosition: 0,
      morphModSource: 'lfo',
      morphModAmount: 80,
      morphLFORate: 0.1,
      unison: { voices: 4, detune: 12, stereoSpread: 60 },
      envelope: { attack: 1000, decay: 2000, sustain: 0.7, release: 1500 },
      filter: { type: 'lowpass', cutoff: 1500, resonance: 20, envelopeAmount: 30 },
      filterEnvelope: { attack: 2000, decay: 1000, sustain: 0.5, release: 1000 },
    },
    effects: [],
    volume: -12,
    pan: 0,
  },
  {
    type: 'synth' as const,
    name: 'Poly Soft Strings',
    synthType: 'PolySynth',
    polySynth: {
      voiceCount: 8,
      voiceType: 'Synth',
      stealMode: 'oldest',
      oscillator: { type: 'sawtooth', detune: 10, octave: 0 },
      envelope: { attack: 500, decay: 1000, sustain: 0.8, release: 1200 },
      filter: { type: 'lowpass', frequency: 2000, Q: 1, rolloff: -12 },
      portamento: 0,
    },
    effects: [],
    volume: -14,
    pan: 0,
  },
  {
    type: 'synth' as const,
    name: 'PWM Strings',
    synthType: 'PWMSynth',
    pwmSynth: {
      pulseWidth: 50,
      pwmDepth: 30,
      pwmRate: 0.5,
      pwmWaveform: 'sine',
      oscillators: 3,
      detune: 12,
      envelope: { attack: 800, decay: 1500, sustain: 0.9, release: 1500 },
      filter: { type: 'lowpass', cutoff: 1200, resonance: 15, envelopeAmount: 0, keyTracking: 30 },
      filterEnvelope: { attack: 10, decay: 500, sustain: 1, release: 100 },
    },
    effects: [],
    volume: -12,
    pan: 0,
  },
  {
    type: 'synth' as const,
    name: 'Solina Ensemble',
    synthType: 'StringMachine',
    stringMachine: {
      sections: { violin: 100, viola: 80, cello: 60, bass: 40 },
      ensemble: { depth: 70, rate: 2.5, voices: 4 },
      attack: 300,
      release: 1500,
      brightness: 50,
    },
    effects: [],
    volume: -10,
    pan: 0,
  },
  {
    type: 'synth' as const,
    name: 'Ethereal Choir',
    synthType: 'FormantSynth',
    formantSynth: {
      vowel: 'A',
      vowelMorph: { target: 'O', amount: 50, rate: 0.2, mode: 'lfo' },
      oscillator: { type: 'sawtooth' },
      formants: { ...VOWEL_FORMANTS.A, bandwidth: 80 },
      envelope: { attack: 1000, decay: 2000, sustain: 0.8, release: 2000 },
      brightness: 60,
    },
    effects: [],
    volume: -12,
    pan: 0,
  },
  {
    type: 'synth' as const,
    name: 'VFX Digital Pad',
    synthType: 'MAMEVFX',
    effects: [],
    volume: -10,
    pan: 0,
  },
  {
    type: 'synth' as const,
    name: 'Wavetable Morph Pad',
    synthType: 'Wavetable',
    wavetable: {
      wavetableId: 'morph-2',
      morphPosition: 50,
      morphModSource: 'lfo',
      morphModAmount: 40,
      morphLFORate: 0.2,
      unison: { voices: 6, detune: 20, stereoSpread: 90 },
      envelope: { attack: 1200, decay: 2500, sustain: 0.8, release: 2000 },
      filter: { type: 'lowpass', cutoff: 2000, resonance: 10, envelopeAmount: 0 },
      filterEnvelope: { attack: 10, decay: 500, sustain: 1, release: 100 },
    },
    effects: [],
    volume: -12,
    pan: 0,
  },
  {
    type: 'synth' as const,
    name: 'PWM Soft Pad',
    synthType: 'PWMSynth',
    pwmSynth: {
      pulseWidth: 50,
      pwmDepth: 20,
      pwmRate: 0.3,
      pwmWaveform: 'sine',
      oscillators: 2,
      detune: 8,
      envelope: { attack: 1500, decay: 2000, sustain: 0.9, release: 2000 },
      filter: { type: 'lowpass', cutoff: 800, resonance: 5, envelopeAmount: 0, keyTracking: 20 },
      filterEnvelope: { attack: 10, decay: 500, sustain: 1, release: 100 },
    },
    effects: [],
    volume: -14,
    pan: 0,
  },
  {
    type: 'synth' as const,
    name: 'Granular Cloud',
    synthType: 'GranularSynth',
    granular: {
      sampleUrl: '', // To be loaded by user
      grainSize: 0.1,
      grainOverlap: 0.05,
      detune: 5,
      playbackRate: 1,
      randomPitch: 0,
      randomPosition: 0,
      scanPosition: 0,
      scanSpeed: 0,
      density: 1,
      reverse: false,
      envelope: { attack: 10, release: 100 },
      filter: { type: 'lowpass', cutoff: 2000, resonance: 1 },
    },
    effects: [],
    volume: -10,
    pan: 0,
  },
];
