import type { InstrumentPreset } from '../../types/instrument';

// TR-505 PRESETS (16) - Roland TR-505 sample-based drum machine
// Classic 12-bit digital drum sounds from 1986
// ============================================================================

export const TR505_PRESETS: InstrumentPreset['config'][] = [
  {
    type: 'synth' as const,
    name: '505 Kick',
    synthType: 'Sampler',
    sample: {
      url: 'data/samples/tr505/tr505-kick.wav',
      baseNote: 'C4',
      detune: 0,
      loop: false,
      loopStart: 0,
      loopEnd: 0,
      reverse: false,
      playbackRate: 1,
    },
    effects: [],
    volume: -6,
    pan: 0,
  },
  {
    type: 'synth' as const,
    name: '505 Snare',
    synthType: 'Sampler',
    sample: {
      url: 'data/samples/tr505/tr505-snare.wav',
      baseNote: 'C4',
      detune: 0,
      loop: false,
      loopStart: 0,
      loopEnd: 0,
      reverse: false,
      playbackRate: 1,
    },
    effects: [],
    volume: -6,
    pan: 0,
  },
  {
    type: 'synth' as const,
    name: '505 Clap',
    synthType: 'Sampler',
    sample: {
      url: 'data/samples/tr505/tr505-clap.wav',
      baseNote: 'C4',
      detune: 0,
      loop: false,
      loopStart: 0,
      loopEnd: 0,
      reverse: false,
      playbackRate: 1,
    },
    effects: [],
    volume: -6,
    pan: 0,
  },
  {
    type: 'synth' as const,
    name: '505 Closed Hat',
    synthType: 'Sampler',
    sample: {
      url: 'data/samples/tr505/tr505-hihat-closed.wav',
      baseNote: 'C4',
      detune: 0,
      loop: false,
      loopStart: 0,
      loopEnd: 0,
      reverse: false,
      playbackRate: 1,
    },
    effects: [],
    volume: -8,
    pan: 0,
  },
  {
    type: 'synth' as const,
    name: '505 Open Hat',
    synthType: 'Sampler',
    sample: {
      url: 'data/samples/tr505/tr505-hihat-open.wav',
      baseNote: 'C4',
      detune: 0,
      loop: false,
      loopStart: 0,
      loopEnd: 0,
      reverse: false,
      playbackRate: 1,
    },
    effects: [],
    volume: -8,
    pan: 0,
  },
  {
    type: 'synth' as const,
    name: '505 Rim',
    synthType: 'Sampler',
    sample: {
      url: 'data/samples/tr505/tr505-rim.wav',
      baseNote: 'C4',
      detune: 0,
      loop: false,
      loopStart: 0,
      loopEnd: 0,
      reverse: false,
      playbackRate: 1,
    },
    effects: [],
    volume: -6,
    pan: 0,
  },
  {
    type: 'synth' as const,
    name: '505 Low Tom',
    synthType: 'Sampler',
    sample: {
      url: 'data/samples/tr505/tr505-tom-l.wav',
      baseNote: 'C4',
      detune: 0,
      loop: false,
      loopStart: 0,
      loopEnd: 0,
      reverse: false,
      playbackRate: 1,
    },
    effects: [],
    volume: -6,
    pan: -30,
  },
  {
    type: 'synth' as const,
    name: '505 Mid Tom',
    synthType: 'Sampler',
    sample: {
      url: 'data/samples/tr505/tr505-tom-m.wav',
      baseNote: 'C4',
      detune: 0,
      loop: false,
      loopStart: 0,
      loopEnd: 0,
      reverse: false,
      playbackRate: 1,
    },
    effects: [],
    volume: -6,
    pan: 0,
  },
  {
    type: 'synth' as const,
    name: '505 High Tom',
    synthType: 'Sampler',
    sample: {
      url: 'data/samples/tr505/tr505-tom-h.wav',
      baseNote: 'C4',
      detune: 0,
      loop: false,
      loopStart: 0,
      loopEnd: 0,
      reverse: false,
      playbackRate: 1,
    },
    effects: [],
    volume: -6,
    pan: 30,
  },
  {
    type: 'synth' as const,
    name: '505 Crash',
    synthType: 'Sampler',
    sample: {
      url: 'data/samples/tr505/tr505-crash.wav',
      baseNote: 'C4',
      detune: 0,
      loop: false,
      loopStart: 0,
      loopEnd: 0,
      reverse: false,
      playbackRate: 1,
    },
    effects: [],
    volume: -10,
    pan: -20,
  },
  {
    type: 'synth' as const,
    name: '505 Ride',
    synthType: 'Sampler',
    sample: {
      url: 'data/samples/tr505/tr505-ride.wav',
      baseNote: 'C4',
      detune: 0,
      loop: false,
      loopStart: 0,
      loopEnd: 0,
      reverse: false,
      playbackRate: 1,
    },
    effects: [],
    volume: -10,
    pan: 20,
  },
  {
    type: 'synth' as const,
    name: '505 Low Cowbell',
    synthType: 'Sampler',
    sample: {
      url: 'data/samples/tr505/tr505-cowb-l.wav',
      baseNote: 'C4',
      detune: 0,
      loop: false,
      loopStart: 0,
      loopEnd: 0,
      reverse: false,
      playbackRate: 1,
    },
    effects: [],
    volume: -8,
    pan: 0,
  },
  {
    type: 'synth' as const,
    name: '505 High Cowbell',
    synthType: 'Sampler',
    sample: {
      url: 'data/samples/tr505/tr505-cowb-h.wav',
      baseNote: 'C4',
      detune: 0,
      loop: false,
      loopStart: 0,
      loopEnd: 0,
      reverse: false,
      playbackRate: 1,
    },
    effects: [],
    volume: -8,
    pan: 0,
  },
  {
    type: 'synth' as const,
    name: '505 Low Conga',
    synthType: 'Sampler',
    sample: {
      url: 'data/samples/tr505/tr505-conga-l.wav',
      baseNote: 'C4',
      detune: 0,
      loop: false,
      loopStart: 0,
      loopEnd: 0,
      reverse: false,
      playbackRate: 1,
    },
    effects: [],
    volume: -6,
    pan: -20,
  },
  {
    type: 'synth' as const,
    name: '505 High Conga',
    synthType: 'Sampler',
    sample: {
      url: 'data/samples/tr505/tr505-conga-h.wav',
      baseNote: 'C4',
      detune: 0,
      loop: false,
      loopStart: 0,
      loopEnd: 0,
      reverse: false,
      playbackRate: 1,
    },
    effects: [],
    volume: -6,
    pan: 20,
  },
  {
    type: 'synth' as const,
    name: '505 Timbale',
    synthType: 'Sampler',
    sample: {
      url: 'data/samples/tr505/tr505-timbal.wav',
      baseNote: 'C4',
      detune: 0,
      loop: false,
      loopStart: 0,
      loopEnd: 0,
      reverse: false,
      playbackRate: 1,
    },
    effects: [],
    volume: -6,
    pan: 0,
  },
];
