import type { InstrumentPreset } from '../../types/instrument';

// TR-707 PRESETS (15) - Roland TR-707 sample-based drum machine
// Classic digital drum sounds from 1985 with rumble variants
// ============================================================================

export const TR707_PRESETS: InstrumentPreset['config'][] = [
  {
    type: 'synth' as const,
    name: '707 Kick',
    synthType: 'Sampler',
    sample: {
      url: 'data/samples/tr707/tr707-kick.wav',
      baseNote: 'C4',
      detune: 0,
      loop: false,
      loopStart: 0,
      loopEnd: 0,
      reverse: false,
      playbackRate: 1,
    },
    effects: [],
    volume: -6,
    pan: 0,
  },
  {
    type: 'synth' as const,
    name: '707 Kick Rumble',
    synthType: 'Sampler',
    sample: {
      url: 'data/samples/tr707/tr707-kick-rumble.wav',
      baseNote: 'C4',
      detune: 0,
      loop: false,
      loopStart: 0,
      loopEnd: 0,
      reverse: false,
      playbackRate: 1,
    },
    effects: [],
    volume: -6,
    pan: 0,
  },
  {
    type: 'synth' as const,
    name: '707 Snare',
    synthType: 'Sampler',
    sample: {
      url: 'data/samples/tr707/tr707-snare.wav',
      baseNote: 'C4',
      detune: 0,
      loop: false,
      loopStart: 0,
      loopEnd: 0,
      reverse: false,
      playbackRate: 1,
    },
    effects: [],
    volume: -6,
    pan: 0,
  },
  {
    type: 'synth' as const,
    name: '707 Clap',
    synthType: 'Sampler',
    sample: {
      url: 'data/samples/tr707/tr707-clap.wav',
      baseNote: 'C4',
      detune: 0,
      loop: false,
      loopStart: 0,
      loopEnd: 0,
      reverse: false,
      playbackRate: 1,
    },
    effects: [],
    volume: -6,
    pan: 0,
  },
  {
    type: 'synth' as const,
    name: '707 Closed Hat',
    synthType: 'Sampler',
    sample: {
      url: 'data/samples/tr707/tr707-hihat-closed.wav',
      baseNote: 'C4',
      detune: 0,
      loop: false,
      loopStart: 0,
      loopEnd: 0,
      reverse: false,
      playbackRate: 1,
    },
    effects: [],
    volume: -8,
    pan: 0,
  },
  {
    type: 'synth' as const,
    name: '707 Open Hat',
    synthType: 'Sampler',
    sample: {
      url: 'data/samples/tr707/tr707-hihat-open.wav',
      baseNote: 'C4',
      detune: 0,
      loop: false,
      loopStart: 0,
      loopEnd: 0,
      reverse: false,
      playbackRate: 1,
    },
    effects: [],
    volume: -8,
    pan: 0,
  },
  {
    type: 'synth' as const,
    name: '707 Rim',
    synthType: 'Sampler',
    sample: {
      url: 'data/samples/tr707/tr707-rim.wav',
      baseNote: 'C4',
      detune: 0,
      loop: false,
      loopStart: 0,
      loopEnd: 0,
      reverse: false,
      playbackRate: 1,
    },
    effects: [],
    volume: -6,
    pan: 0,
  },
  {
    type: 'synth' as const,
    name: '707 Low Tom',
    synthType: 'Sampler',
    sample: {
      url: 'data/samples/tr707/tr707-tom-l.wav',
      baseNote: 'C4',
      detune: 0,
      loop: false,
      loopStart: 0,
      loopEnd: 0,
      reverse: false,
      playbackRate: 1,
    },
    effects: [],
    volume: -6,
    pan: -30,
  },
  {
    type: 'synth' as const,
    name: '707 Low Tom Rumble',
    synthType: 'Sampler',
    sample: {
      url: 'data/samples/tr707/tr707-tom-l-rumble.wav',
      baseNote: 'C4',
      detune: 0,
      loop: false,
      loopStart: 0,
      loopEnd: 0,
      reverse: false,
      playbackRate: 1,
    },
    effects: [],
    volume: -6,
    pan: -30,
  },
  {
    type: 'synth' as const,
    name: '707 Mid Tom',
    synthType: 'Sampler',
    sample: {
      url: 'data/samples/tr707/tr707-tom-m.wav',
      baseNote: 'C4',
      detune: 0,
      loop: false,
      loopStart: 0,
      loopEnd: 0,
      reverse: false,
      playbackRate: 1,
    },
    effects: [],
    volume: -6,
    pan: 0,
  },
  {
    type: 'synth' as const,
    name: '707 High Tom',
    synthType: 'Sampler',
    sample: {
      url: 'data/samples/tr707/tr707-tom-h.wav',
      baseNote: 'C4',
      detune: 0,
      loop: false,
      loopStart: 0,
      loopEnd: 0,
      reverse: false,
      playbackRate: 1,
    },
    effects: [],
    volume: -6,
    pan: 30,
  },
  {
    type: 'synth' as const,
    name: '707 Cowbell',
    synthType: 'Sampler',
    sample: {
      url: 'data/samples/tr707/tr707-cowbell.wav',
      baseNote: 'C4',
      detune: 0,
      loop: false,
      loopStart: 0,
      loopEnd: 0,
      reverse: false,
      playbackRate: 1,
    },
    effects: [],
    volume: -8,
    pan: 0,
  },
  {
    type: 'synth' as const,
    name: '707 Crash',
    synthType: 'Sampler',
    sample: {
      url: 'data/samples/tr707/tr707-crash.wav',
      baseNote: 'C4',
      detune: 0,
      loop: false,
      loopStart: 0,
      loopEnd: 0,
      reverse: false,
      playbackRate: 1,
    },
    effects: [],
    volume: -10,
    pan: -20,
  },
  {
    type: 'synth' as const,
    name: '707 Ride',
    synthType: 'Sampler',
    sample: {
      url: 'data/samples/tr707/tr707-ride.wav',
      baseNote: 'C4',
      detune: 0,
      loop: false,
      loopStart: 0,
      loopEnd: 0,
      reverse: false,
      playbackRate: 1,
    },
    effects: [],
    volume: -10,
    pan: 20,
  },
  {
    type: 'synth' as const,
    name: '707 Tambourine',
    synthType: 'Sampler',
    sample: {
      url: 'data/samples/tr707/tr707-tambourine.wav',
      baseNote: 'C4',
      detune: 0,
      loop: false,
      loopStart: 0,
      loopEnd: 0,
      reverse: false,
      playbackRate: 1,
    },
    effects: [],
    volume: -8,
    pan: 0,
  },
];
