import type { InstrumentPreset } from '../../types/instrument';

// TR-808 PRESETS — Each preset maps to a specific IO808 drum voice
// These use the authentic circuit-modeled IO808 synth engine (port of io-808)
// ============================================================================

export const TR808_PRESETS: InstrumentPreset['config'][] = [
  {
    type: 'synth' as const,
    name: '808 Kick',
    synthType: 'TR808',
    parameters: { io808Type: 'kick' },
    drumMachine: { drumType: 'kick', machineType: '808' },
    effects: [],
    volume: -6,
    pan: 0,
  },
  {
    type: 'synth' as const,
    name: '808 Snare',
    synthType: 'TR808',
    parameters: { io808Type: 'snare' },
    drumMachine: { drumType: 'snare', machineType: '808' },
    effects: [],
    volume: -8,
    pan: 0,
  },
  {
    type: 'synth' as const,
    name: '808 Clap',
    synthType: 'TR808',
    parameters: { io808Type: 'clap' },
    drumMachine: { drumType: 'clap', machineType: '808' },
    effects: [],
    volume: -10,
    pan: 0,
  },
  {
    type: 'synth' as const,
    name: '808 Rimshot',
    synthType: 'TR808',
    parameters: { io808Type: 'rimshot' },
    drumMachine: { drumType: 'rimshot', machineType: '808' },
    effects: [],
    volume: -10,
    pan: 0,
  },
  {
    type: 'synth' as const,
    name: '808 Clave',
    synthType: 'TR808',
    parameters: { io808Type: 'clave' },
    drumMachine: { drumType: 'clave', machineType: '808' },
    effects: [],
    volume: -10,
    pan: 0,
  },
  {
    type: 'synth' as const,
    name: '808 Cowbell',
    synthType: 'TR808',
    parameters: { io808Type: 'cowbell' },
    drumMachine: { drumType: 'cowbell', machineType: '808' },
    effects: [],
    volume: -10,
    pan: 0,
  },
  {
    type: 'synth' as const,
    name: '808 Maracas',
    synthType: 'TR808',
    parameters: { io808Type: 'maracas' },
    drumMachine: { drumType: 'maracas', machineType: '808' },
    effects: [],
    volume: -12,
    pan: 0,
  },
  {
    type: 'synth' as const,
    name: '808 Closed Hat',
    synthType: 'TR808',
    parameters: { io808Type: 'closedHat' },
    drumMachine: { drumType: 'hihat', machineType: '808' },
    effects: [],
    volume: -12,
    pan: 0,
  },
  {
    type: 'synth' as const,
    name: '808 Open Hat',
    synthType: 'TR808',
    parameters: { io808Type: 'openHat' },
    drumMachine: { drumType: 'hihat', machineType: '808' },
    effects: [],
    volume: -12,
    pan: 0,
  },
  {
    type: 'synth' as const,
    name: '808 Cymbal',
    synthType: 'TR808',
    parameters: { io808Type: 'cymbal' },
    drumMachine: { drumType: 'cymbal', machineType: '808' },
    effects: [],
    volume: -14,
    pan: 0,
  },
  {
    type: 'synth' as const,
    name: '808 Low Tom',
    synthType: 'TR808',
    parameters: { io808Type: 'tomLow' },
    drumMachine: { drumType: 'tom', machineType: '808' },
    effects: [],
    volume: -8,
    pan: 0,
  },
  {
    type: 'synth' as const,
    name: '808 Mid Tom',
    synthType: 'TR808',
    parameters: { io808Type: 'tomMid' },
    drumMachine: { drumType: 'tom', machineType: '808' },
    effects: [],
    volume: -8,
    pan: 0,
  },
  {
    type: 'synth' as const,
    name: '808 Hi Tom',
    synthType: 'TR808',
    parameters: { io808Type: 'tomHigh' },
    drumMachine: { drumType: 'tom', machineType: '808' },
    effects: [],
    volume: -8,
    pan: 0,
  },
  {
    type: 'synth' as const,
    name: '808 Low Conga',
    synthType: 'TR808',
    parameters: { io808Type: 'congaLow' },
    drumMachine: { drumType: 'conga', machineType: '808' },
    effects: [],
    volume: -8,
    pan: 0,
  },
  {
    type: 'synth' as const,
    name: '808 Mid Conga',
    synthType: 'TR808',
    parameters: { io808Type: 'congaMid' },
    drumMachine: { drumType: 'conga', machineType: '808' },
    effects: [],
    volume: -8,
    pan: 0,
  },
  {
    type: 'synth' as const,
    name: '808 Hi Conga',
    synthType: 'TR808',
    parameters: { io808Type: 'congaHigh' },
    drumMachine: { drumType: 'conga', machineType: '808' },
    effects: [],
    volume: -8,
    pan: 0,
  },
];
