import type { InstrumentPreset } from '../../types/instrument';

// TR-909 PRESETS — Each preset maps to a specific TR909 drum voice
// These use the authentic hybrid sample/synthesis TR909 engine (port of tr-909)
// ============================================================================

export const TR909_PRESETS: InstrumentPreset['config'][] = [
  {
    type: 'synth' as const,
    name: '909 Kick',
    synthType: 'TR909',
    parameters: { tr909Type: 'kick' },
    drumMachine: { drumType: 'kick', machineType: '909' },
    effects: [],
    volume: -6,
    pan: 0,
  },
  {
    type: 'synth' as const,
    name: '909 Snare',
    synthType: 'TR909',
    parameters: { tr909Type: 'snare' },
    drumMachine: { drumType: 'snare', machineType: '909' },
    effects: [],
    volume: -8,
    pan: 0,
  },
  {
    type: 'synth' as const,
    name: '909 Clap',
    synthType: 'TR909',
    parameters: { tr909Type: 'clap' },
    drumMachine: { drumType: 'clap', machineType: '909' },
    effects: [],
    volume: -10,
    pan: 0,
  },
  {
    type: 'synth' as const,
    name: '909 Rimshot',
    synthType: 'TR909',
    parameters: { tr909Type: 'rimshot' },
    drumMachine: { drumType: 'rimshot', machineType: '909' },
    effects: [],
    volume: -10,
    pan: 0,
  },
  {
    type: 'synth' as const,
    name: '909 Closed Hat',
    synthType: 'TR909',
    parameters: { tr909Type: 'closedHat' },
    drumMachine: { drumType: 'hihat', machineType: '909' },
    effects: [],
    volume: -12,
    pan: 0,
  },
  {
    type: 'synth' as const,
    name: '909 Open Hat',
    synthType: 'TR909',
    parameters: { tr909Type: 'openHat' },
    drumMachine: { drumType: 'hihat', machineType: '909' },
    effects: [],
    volume: -12,
    pan: 0,
  },
  {
    type: 'synth' as const,
    name: '909 Low Tom',
    synthType: 'TR909',
    parameters: { tr909Type: 'tomLow' },
    drumMachine: { drumType: 'tom', machineType: '909' },
    effects: [],
    volume: -8,
    pan: 0,
  },
  {
    type: 'synth' as const,
    name: '909 Mid Tom',
    synthType: 'TR909',
    parameters: { tr909Type: 'tomMid' },
    drumMachine: { drumType: 'tom', machineType: '909' },
    effects: [],
    volume: -8,
    pan: 0,
  },
  {
    type: 'synth' as const,
    name: '909 Hi Tom',
    synthType: 'TR909',
    parameters: { tr909Type: 'tomHigh' },
    drumMachine: { drumType: 'tom', machineType: '909' },
    effects: [],
    volume: -8,
    pan: 0,
  },
  {
    type: 'synth' as const,
    name: '909 Crash',
    synthType: 'TR909',
    parameters: { tr909Type: 'crash' },
    drumMachine: { drumType: 'cymbal', machineType: '909' },
    effects: [],
    volume: -14,
    pan: 0,
  },
  {
    type: 'synth' as const,
    name: '909 Ride',
    synthType: 'TR909',
    parameters: { tr909Type: 'ride' },
    drumMachine: { drumType: 'cymbal', machineType: '909' },
    effects: [],
    volume: -14,
    pan: 0,
  },
];
