#!/usr/bin/env python3
"""Generate stubs/Factory.h from aelapse's five .preset files.

Mirrors what aelapse's juce_binarybuilder target would produce for the
factory preset bank. Run from the project root or the script directory.
"""
import os

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..", ".."))

PRESETS = [
    ("dreamy_preset",       "third-party/aelapse/src/Presets/factory/dreamy.preset"),
    ("springreverb_preset", "third-party/aelapse/src/Presets/factory/springreverb.preset"),
    ("otherworldly_preset", "third-party/aelapse/src/Presets/factory/otherworldly.preset"),
    ("reverse_preset",      "third-party/aelapse/src/Presets/factory/reverse.preset"),
    ("chaotic_preset",      "third-party/aelapse/src/Presets/factory/chaotic.preset"),
]

lines = [
    "// Auto-generated by juce-wasm/aelapse-ui/stubs/gen_factory.py",
    "// Mirror of what aelapse normally gets from its juce_binarybuilder target.",
    "#pragma once",
    "#include <cstddef>",
    "",
    "namespace Factory {",
    "",
]

total = 0
for name, rel in PRESETS:
    path = os.path.join(ROOT, rel)
    with open(path, "rb") as f:
        data = f.read()
    total += len(data)
    # PresetManager.h expects factoryPreset_t = tuple<const char*, const char*, size_t>
    # so we emit `const char` arrays (signed), matching juce_binarybuilder output.
    lines.append(f"inline const char {name}[] = {{")
    for i in range(0, len(data), 16):
        chunk = data[i:i+16]
        # cast to signed byte so C++ accepts it in a const char[] initializer
        vals = []
        for b in chunk:
            s = b - 256 if b >= 128 else b
            vals.append(f"{s}")
        lines.append("    " + ", ".join(vals) + ",")
    lines.append("};")
    lines.append(f"inline constexpr size_t {name}Size = {len(data)};")
    lines.append("")

lines.append("} // namespace Factory")

out_path = os.path.join(os.path.dirname(__file__), "Factory.h")
with open(out_path, "w") as f:
    f.write("\n".join(lines))

print(f"Wrote {out_path} ({total} preset bytes across {len(PRESETS)} files)")
