#!/usr/bin/env python3
"""Generate stubs/Fonts.h from aelapse's three TTF files.

Mirrors what aelapse's juce_binarybuilder target would produce during the
upstream build. Run from the project root:

    python3 juce-wasm/aelapse-ui/stubs/gen_fonts.py
"""
import os
import sys

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..", ".."))

FONTS = [
    ("NunitoSans320300_ttf", "third-party/aelapse/src/GUI/fonts/NunitoSans-320-300.ttf"),
    ("Lexend300_ttf",        "third-party/aelapse/src/GUI/fonts/Lexend-300.ttf"),
    ("Roboto425_ttf",        "third-party/aelapse/src/GUI/fonts/Roboto-425.ttf"),
]

lines = [
    "// Auto-generated by juce-wasm/aelapse-ui/stubs/gen_fonts.py",
    "// Mirror of what aelapse normally gets from its juce_binarybuilder target.",
    "#pragma once",
    "#include <cstddef>",
    "",
    "namespace Fonts {",
    "",
]

total = 0
for name, rel in FONTS:
    path = os.path.join(ROOT, rel)
    with open(path, "rb") as f:
        data = f.read()
    total += len(data)
    lines.append(f"inline const unsigned char {name}[] = {{")
    for i in range(0, len(data), 16):
        chunk = data[i:i+16]
        lines.append("    " + ", ".join("0x{0:02X}".format(b) for b in chunk) + ",")
    lines.append("};")
    lines.append(f"inline constexpr size_t {name}Size = {len(data)};")
    lines.append("")

lines.append("} // namespace Fonts")

out_path = os.path.join(os.path.dirname(__file__), "Fonts.h")
with open(out_path, "w") as f:
    f.write("\n".join(lines))

print(f"Wrote {out_path} ({total} font bytes across {len(FONTS)} files)")
