/**
 * Channel auto-naming — infer "what's in this channel" from instrument
 * metadata + note statistics and produce a human-readable label.
 *
 * Scope: classic tracker formats (MOD/S3M/IT) and blank native projects
 * that leave channels labelled "Channel N" / "CHN". Strictly additive to
 * `classifyPattern()` in MusicAnalysis — uses the existing role enum,
 * adds a subrole axis, and never mutates passed data.
 *
 * Pure functions. Callers apply the returned rename diff via the existing
 * `useTrackerStore.updateChannelName` path.
 */

import type { ChannelData, Pattern } from '@/types/tracker';
import type { InstrumentConfig } from '@/types/instrument/defaults';
import type { SampleCategory } from '@typedefs/samplePack';
import { classifyChannel, PERCUSSION_NAME_RE, type ChannelAnalysis, type ChannelRole } from './MusicAnalysis';
import { categorizeSample } from '@/lib/import/maxForLiveImport';
import { DRUM_SYNTHS } from '@/midi/performance/lightGuide';
import { analyzeEnvelopeShape } from '@/lib/import/EnvelopeConverter';
import { analyzeSampleForClassification } from './SampleSpectrum';

// ─── Public types ────────────────────────────────────────────────────────────

export type ChannelSubrole = 'kick' | 'snare' | 'hat' | 'clap' | 'perc' | 'sub' | 'synth' | 'mixed';

export interface InstrumentClassification {
  role: ChannelRole;
  subrole?: ChannelSubrole;
  /** 0-1 — how much weight the resolver should give this instrument vs
   *  note-statistics when deciding the final channel role. */
  confidence: number;
}

export interface EnhancedChannelAnalysis extends ChannelAnalysis {
  subrole?: ChannelSubrole;
}

export interface ChannelRename {
  index: number;
  oldName: string;
  newName: string;
}

// ─── Name recognition ────────────────────────────────────────────────────────

const GENERIC_NAME_PATTERNS: RegExp[] = [
  /^Channel \d+$/,   // MODParser / XMParser / ITParser / createEmptyPattern
  /^CH\d+$/,         // UI fallback (PatternEditorCanvas:3041)
  /^\d+$/,           // Scope strip numeric-only labels
  /^\s*$/,           // Blank / whitespace
];

/** True if the name looks auto-generated by the importer or the UI fallback
 *  and would be safe to replace. User renames like "My Lead" return false. */
export function isGenericChannelName(name: string | null | undefined): boolean {
  if (name === null || name === undefined) return true;
  for (const re of GENERIC_NAME_PATTERNS) {
    if (re.test(name)) return true;
  }
  return false;
}

// ─── Channel → instrument frequency ──────────────────────────────────────────

/** Count how often each instrument id appears in the channel's rows.
 *  Instrument 0 (unset) is ignored. Empty map = no instruments ever played. */
export function getChannelInstruments(channel: ChannelData): Map<number, number> {
  const freq = new Map<number, number>();
  for (const cell of channel.rows) {
    if (!cell) continue;
    const id = cell.instrument;
    if (id && id >= 1 && id <= 128) {
      freq.set(id, (freq.get(id) ?? 0) + 1);
    }
  }
  return freq;
}

// ─── Regexes for name-based classification ──────────────────────────────────

const BASS_NAME_RE = /\bbass\b|\bbs\b|\bsub\b/i;
const LEAD_NAME_RE = /\blead\b|\bld\b|\bsolo\b|\barp\b/i;
const PAD_NAME_RE = /\bpad\b|\bstring\b|\bchoir\b|\bpiano\b|\borgan\b|\bkey/i;
const ARP_NAME_RE = /\barp\b|\barpeggi/i;
const CHORD_NAME_RE = /\bchord\b|\bchrd\b|\bstab\b/i;

// ─── Instrument → role/subrole mapping ──────────────────────────────────────

const SAMPLE_CATEGORY_MAP: Record<SampleCategory, { role: ChannelRole; subrole?: ChannelSubrole } | null> = {
  kicks:      { role: 'percussion', subrole: 'kick' },
  snares:     { role: 'percussion', subrole: 'snare' },
  hihats:     { role: 'percussion', subrole: 'hat' },
  claps:      { role: 'percussion', subrole: 'clap' },
  percussion: { role: 'percussion', subrole: 'perc' },
  bass:       { role: 'bass',       subrole: 'synth' },
  leads:      { role: 'lead',       subrole: 'synth' },
  pads:       { role: 'pad' },
  fx:         { role: 'lead' },   // FX channels are usually non-musical leads
  vocals:     { role: 'lead' },
  loops:      null,
  other:      null,
};

/** Classify a single instrument by inspecting its config. Priority order:
 *  explicit drumMachine.drumType > DRUM_SYNTHS set > sample filename (with
 *  categorize hit) > SAMPLE SPECTRUM (data:audio/wav PCM analysis) >
 *  instrument name regex > envelope shape. Higher-confidence signals win. */
export function classifyInstrument(inst: InstrumentConfig | null | undefined): InstrumentClassification {
  if (!inst) return { role: 'empty', confidence: 0 };

  // 1. Explicit drumType — strongest signal.
  if (inst.drumMachine?.drumType) {
    const dt = inst.drumMachine.drumType;
    if (dt === 'kick')    return { role: 'percussion', subrole: 'kick',  confidence: 1.0 };
    if (dt === 'snare')   return { role: 'percussion', subrole: 'snare', confidence: 1.0 };
    if (dt === 'clap')    return { role: 'percussion', subrole: 'clap',  confidence: 1.0 };
    if (dt === 'hihat')   return { role: 'percussion', subrole: 'hat',   confidence: 1.0 };
    if (dt === 'rimshot') return { role: 'percussion', subrole: 'perc',  confidence: 1.0 };
    // tom / cymbal / cowbell / conga / clave / maracas → generic perc
    return { role: 'percussion', subrole: 'perc', confidence: 1.0 };
  }

  // 2. Drum-type synth — almost always percussion.
  if (DRUM_SYNTHS.has(inst.synthType)) {
    return { role: 'percussion', subrole: 'perc', confidence: 0.9 };
  }

  // 3. Sample filename (if sample-based instrument with a real URL).
  const sampleUrl = inst.sample?.url;
  if (sampleUrl && typeof sampleUrl === 'string' && sampleUrl.length > 0) {
    const cat = categorizeSample(sampleUrl);
    const mapped = SAMPLE_CATEGORY_MAP[cat];
    if (mapped) {
      return { role: mapped.role, subrole: mapped.subrole, confidence: 0.8 };
    }
  }

  // 4. Sample spectrum — read the raw PCM out of data:audio/wav;base64 URLs
  //    and classify by FFT features (centroid / flatness / envelope). Handles
  //    MODs whose instrument-name slots hold greeting-scroller text + Amiga
  //    bass encoded in octave 3 (both defeat the note-stats + name paths).
  //    Skipped when no URL or the URL isn't a WAV data URL.
  if (sampleUrl && typeof sampleUrl === 'string' && sampleUrl.length > 0) {
    const spec = analyzeSampleForClassification(sampleUrl);
    if (spec && spec.role !== 'empty' && spec.confidence >= 0.5) {
      return { role: spec.role, subrole: spec.subrole, confidence: spec.confidence };
    }
  }

  // 5. Instrument name regex. Check drums first (most common + overlaps).
  const nm = inst.name ?? '';
  if (nm) {
    if (PERCUSSION_NAME_RE.test(nm)) {
      // Try to pick a specific subrole from the name.
      if (/kick|\bbd\b|bassdrum/i.test(nm))  return { role: 'percussion', subrole: 'kick',  confidence: 0.65 };
      if (/snare|\bsd\b/i.test(nm))          return { role: 'percussion', subrole: 'snare', confidence: 0.65 };
      if (/hat|\bhh\b|hihat/i.test(nm))      return { role: 'percussion', subrole: 'hat',   confidence: 0.65 };
      if (/clap|snap/i.test(nm))             return { role: 'percussion', subrole: 'clap',  confidence: 0.65 };
      return { role: 'percussion', subrole: 'perc', confidence: 0.6 };
    }
    if (BASS_NAME_RE.test(nm))  return { role: 'bass',     subrole: 'synth', confidence: 0.6 };
    if (ARP_NAME_RE.test(nm))   return { role: 'arpeggio', confidence: 0.6 };
    if (LEAD_NAME_RE.test(nm))  return { role: 'lead',     subrole: 'synth', confidence: 0.6 };
    if (PAD_NAME_RE.test(nm))   return { role: 'pad',                      confidence: 0.6 };
    if (CHORD_NAME_RE.test(nm)) return { role: 'chord',                    confidence: 0.6 };
  }

  // 6. Envelope shape hint (low confidence — only disambiguates).
  const env = inst.metadata?.originalEnvelope;
  if (env) {
    const shape = analyzeEnvelopeShape(env);
    if (shape.type === 'percussive') {
      return { role: 'percussion', subrole: 'perc', confidence: 0.4 };
    }
    if (shape.type === 'pad') {
      return { role: 'pad', confidence: 0.4 };
    }
    if (shape.type === 'pluck') {
      return { role: 'lead', subrole: 'synth', confidence: 0.35 };
    }
  }

  return { role: 'empty', confidence: 0 };
}

// ─── Channel classifier combining note-stats + instrument signals ───────────

/** Extract the raw note sequence for classifyChannel(). */
function collectNotes(channel: ChannelData): number[] {
  const notes: number[] = [];
  for (const cell of channel.rows) {
    if (cell && cell.note >= 1 && cell.note <= 96) notes.push(cell.note);
  }
  return notes;
}

/** Enhanced per-channel analysis that blends the existing note-statistic
 *  classifier with instrument-derived role signals. Instrument signals at
 *  confidence ≥ 0.8 override note-statistics; lower signals merely inform
 *  the subrole field. Percussion subrole becomes 'mixed' when the top two
 *  instruments are both percussion but with different subroles (kit-style
 *  channel playing kick + snare + hat). Low-octave bass is auto-tagged
 *  `subrole='sub'` regardless of instrument. */
export function classifyChannelWithInstruments(
  channel: ChannelData,
  channelIndex: number,
  lookup: Map<number, InstrumentConfig>,
): EnhancedChannelAnalysis {
  const notes = collectNotes(channel);
  const numRows = channel.rows.length;
  const noteAnalysis = classifyChannel(channelIndex, notes, numRows);

  const freq = getChannelInstruments(channel);
  if (freq.size === 0) {
    return noteAnalysis;
  }

  // Sort instruments by frequency (desc). Top 2 are "dominant".
  const sorted = [...freq.entries()].sort((a, b) => b[1] - a[1]);
  const totalCells = sorted.reduce((s, [, c]) => s + c, 0);
  const [top1Id, top1Count] = sorted[0];
  const top1 = lookup.get(top1Id);
  const top1Class = classifyInstrument(top1);

  const enhanced: EnhancedChannelAnalysis = { ...noteAnalysis };

  // Apply dominant-instrument override only when it's clearly dominant
  // (>= 70% of cells) AND high-confidence.
  const dominance = totalCells > 0 ? top1Count / totalCells : 0;
  if (top1Class.confidence >= 0.8 && dominance >= 0.7) {
    enhanced.role = top1Class.role;
    if (top1Class.subrole) enhanced.subrole = top1Class.subrole;
  } else if (top1Class.confidence >= 0.6 && enhanced.role === 'empty') {
    // Note-stats said empty (maybe sparse pattern) — instrument name
    // saves us from leaving it unlabelled.
    enhanced.role = top1Class.role;
    if (top1Class.subrole) enhanced.subrole = top1Class.subrole;
  } else if (top1Class.subrole && enhanced.role === top1Class.role) {
    // Roles already agree — adopt the subrole.
    enhanced.subrole = top1Class.subrole;
  }

  // Percussion "mixed kit" detection: when top 2 instruments BOTH classify
  // as percussion with different subroles, treat the channel as a drum kit
  // — override role to percussion even if dominance didn't pass the 70%
  // threshold above (a 50/50 kick+snare split would otherwise fall through
  // to note-stats and get tagged 'bass' by low-octave heuristics).
  if (sorted.length >= 2) {
    const [top2Id] = sorted[1];
    const top2Class = classifyInstrument(lookup.get(top2Id));
    if (top1Class.role === 'percussion'
        && top2Class.role === 'percussion'
        && top1Class.subrole
        && top2Class.subrole
        && top1Class.subrole !== top2Class.subrole) {
      enhanced.role = 'percussion';
      enhanced.subrole = 'mixed';
    }
  }

  // Sub-bass tag — only avgOctave < 1 (i.e., octave-0 notes, C-0 through B-0)
  // qualifies. Notes at octave 1 are normal "Bass" territory in tracker music.
  if (enhanced.role === 'bass' && noteAnalysis.avgOctave < 1) {
    enhanced.subrole = 'sub';
  }

  return enhanced;
}

// ─── Role + subrole → pretty label ──────────────────────────────────────────

export function suggestChannelName(analysis: EnhancedChannelAnalysis): string | null {
  switch (analysis.role) {
    case 'percussion':
      if (analysis.subrole === 'kick')  return 'Kick';
      if (analysis.subrole === 'snare') return 'Snare';
      if (analysis.subrole === 'hat')   return 'Hi-Hat';
      if (analysis.subrole === 'clap')  return 'Clap';
      return 'Drums';
    case 'bass':
      return analysis.subrole === 'sub' ? 'Sub Bass' : 'Bass';
    case 'lead':
      return 'Lead';
    case 'chord':
      return 'Chords';
    case 'arpeggio':
      return 'Arp';
    case 'pad':
      return 'Pad';
    case 'empty':
    default:
      return null;
  }
}

// ─── Song-wide role classification ──────────────────────────────────────────

/** Cached by `patterns` array identity. Tracker store edits go through immer
 *  and produce a fresh `patterns` array, so the cache invalidates on any edit.
 *  `instruments` identity is ignored — instrument renames are rare and roles
 *  are only loosely tied to instrument metadata. */
const _songRolesCache = new WeakMap<Pattern[], EnhancedChannelAnalysis[]>();

/**
 * Classify every channel of a song by picking the pattern where that channel
 * has the most notes and running `classifyChannelWithInstruments` on it.
 *
 * Use this when you need STABLE song-wide roles (auto-dub rule targeting,
 * auto-DJ bass-swap gating, analysis) — classifying the currently-playing
 * pattern alone risks hitting a sparse intro and returning `empty` for every
 * channel that isn't yet active. For per-pattern visualization,
 * `classifyPattern` in MusicAnalysis is the right call.
 */
export function classifySongChannels(
  patterns: Pattern[],
  instruments: Map<number, InstrumentConfig>,
): EnhancedChannelAnalysis[] {
  const cached = _songRolesCache.get(patterns);
  if (cached) return cached;

  if (patterns.length === 0) return [];
  const schema = patterns[0];
  if (!schema || !Array.isArray(schema.channels)) return [];

  const analyses: EnhancedChannelAnalysis[] = schema.channels.map((_, idx) => {
    let best: { pat: Pattern; noteCount: number } | null = null;
    for (const pat of patterns) {
      const ch = pat.channels?.[idx];
      if (!ch) continue;
      let n = 0;
      for (const cell of ch.rows) if (cell && cell.note >= 1 && cell.note <= 96) n++;
      if (!best || n > best.noteCount) best = { pat, noteCount: n };
    }
    const pat = best ? best.pat : schema;
    return classifyChannelWithInstruments(pat.channels[idx], idx, instruments);
  });

  _songRolesCache.set(patterns, analyses);
  return analyses;
}

const _songRolesProjectionCache = new WeakMap<Pattern[], ChannelRole[]>();

/** Convenience: song-wide roles only (no subrole/density). Cached alongside
 *  `classifySongChannels` so repeated calls (AutoDub ticks 4× per second)
 *  return the same array instance and don't re-project on every tick. */
export function classifySongRoles(
  patterns: Pattern[],
  instruments: Map<number, InstrumentConfig>,
): ChannelRole[] {
  const cached = _songRolesProjectionCache.get(patterns);
  if (cached) return cached;
  const roles = classifySongChannels(patterns, instruments).map(a => a.role);
  _songRolesProjectionCache.set(patterns, roles);
  return roles;
}

// ─── Full-song rename proposal ──────────────────────────────────────────────

/** Walk every channel of the first pattern (names are global per the store's
 *  `updateChannelName`), compute a rename proposal, skip channels whose name
 *  is not generic (user-renamed), and disambiguate duplicates by numeric
 *  suffix in channel-index order. Returns a rename diff — never mutates. */
export function autoNameChannels(
  patterns: Pattern[],
  instruments: Map<number, InstrumentConfig>,
): ChannelRename[] {
  if (patterns.length === 0) return [];
  // Use the first pattern as the channel schema (channel count/name identity
  // stays consistent across patterns per the store's global rename behaviour).
  const schema = patterns[0];
  if (!schema || !Array.isArray(schema.channels)) return [];

  // Share the richest-per-channel classification with classifySongChannels so
  // auto-naming and role-targeted auto-dub agree on every channel's role.
  const analyses = classifySongChannels(patterns, instruments);

  // First pass: build proposals (only for channels with generic current names).
  const proposals: Array<{ index: number; oldName: string; proposed: string | null }> = [];
  for (let i = 0; i < schema.channels.length; i++) {
    const ch = schema.channels[i];
    const oldName = ch.name ?? '';
    if (!isGenericChannelName(oldName)) {
      proposals.push({ index: i, oldName, proposed: null });
      continue;
    }
    proposals.push({ index: i, oldName, proposed: suggestChannelName(analyses[i]) });
  }

  // Second pass: count duplicates, assign numeric suffixes in index order.
  const nameCount = new Map<string, number>();
  for (const p of proposals) {
    if (p.proposed) nameCount.set(p.proposed, (nameCount.get(p.proposed) ?? 0) + 1);
  }
  const runningIdx = new Map<string, number>();
  const renames: ChannelRename[] = [];
  for (const p of proposals) {
    if (p.proposed === null) continue;
    const duplicates = nameCount.get(p.proposed) ?? 1;
    let finalName: string;
    if (duplicates > 1) {
      const n = (runningIdx.get(p.proposed) ?? 0) + 1;
      runningIdx.set(p.proposed, n);
      finalName = `${p.proposed} ${n}`;
    } else {
      finalName = p.proposed;
    }
    if (finalName !== p.oldName) {
      renames.push({ index: p.index, oldName: p.oldName, newName: finalName });
    }
  }
  return renames;
}
