/**
 * Actionamics synth presets — Envelope ADSR, portamento, sample lists, arpeggio lists
 *
 * Each preset defines instrument parameters for act_set_instrument_param().
 * ADSR: attackEndVolume/attackSpeed, decayEndVolume/decaySpeed, sustainDelay,
 *       releaseEndVolume/releaseSpeed
 * Lists: sampleNumber (waveform sequencing), arpeggio, frequency — each with
 *        listNumber, listValues, startDelta, counterEnd
 * Categories: bass, lead, pad, drum, fx, arpeggio
 */

export interface ActionamicsPreset {
  name: string;
  category: 'bass' | 'lead' | 'pad' | 'drum' | 'fx' | 'arpeggio';
  params: Record<string, number>;
}

export const ACTIONAMICS_PRESETS: ActionamicsPreset[] = [
  // -- Bass -------------------------------------------------------------------
  {
    name: 'Solid Sub Bass',
    category: 'bass',
    params: {
      sampleNumberListNumber: 0,
      sampleNumberListValues: 1,
      sampleNumberListStartDelta: 1,
      sampleNumberListCounterEnd: 1,
      arpeggioListNumber: 0,
      arpeggioListValues: 1,
      arpeggioListStartDelta: 1,
      arpeggioListCounterEnd: 1,
      frequencyListNumber: 0,
      frequencyListValues: 1,
      frequencyListStartDelta: 1,
      frequencyListCounterEnd: 1,
      portamentoIncrement: 0,
      portamentoDelay: 0,
      noteTranspose: 0,
      attackEndVolume: 64,
      attackSpeed: 2,
      decayEndVolume: 50,
      decaySpeed: 4,
      sustainDelay: 20,
      releaseEndVolume: 0,
      releaseSpeed: 6,
    },
  },
  {
    name: 'Portamento Glide Bass',
    category: 'bass',
    params: {
      sampleNumberListNumber: 0,
      sampleNumberListValues: 1,
      sampleNumberListStartDelta: 1,
      sampleNumberListCounterEnd: 1,
      arpeggioListNumber: 0,
      arpeggioListValues: 1,
      arpeggioListStartDelta: 1,
      arpeggioListCounterEnd: 1,
      frequencyListNumber: 0,
      frequencyListValues: 1,
      frequencyListStartDelta: 1,
      frequencyListCounterEnd: 1,
      portamentoIncrement: 3,
      portamentoDelay: 2,
      noteTranspose: 0,
      attackEndVolume: 60,
      attackSpeed: 1,
      decayEndVolume: 48,
      decaySpeed: 3,
      sustainDelay: 30,
      releaseEndVolume: 0,
      releaseSpeed: 5,
    },
  },

  // -- Lead -------------------------------------------------------------------
  {
    name: 'Sharp Attack Lead',
    category: 'lead',
    params: {
      sampleNumberListNumber: 0,
      sampleNumberListValues: 1,
      sampleNumberListStartDelta: 1,
      sampleNumberListCounterEnd: 1,
      arpeggioListNumber: 0,
      arpeggioListValues: 1,
      arpeggioListStartDelta: 1,
      arpeggioListCounterEnd: 1,
      frequencyListNumber: 0,
      frequencyListValues: 1,
      frequencyListStartDelta: 1,
      frequencyListCounterEnd: 1,
      portamentoIncrement: 0,
      portamentoDelay: 0,
      noteTranspose: 0,
      attackEndVolume: 64,
      attackSpeed: 1,
      decayEndVolume: 48,
      decaySpeed: 3,
      sustainDelay: 40,
      releaseEndVolume: 0,
      releaseSpeed: 4,
    },
  },
  {
    name: 'Portamento Slide Lead',
    category: 'lead',
    params: {
      sampleNumberListNumber: 0,
      sampleNumberListValues: 2,
      sampleNumberListStartDelta: 1,
      sampleNumberListCounterEnd: 2,
      arpeggioListNumber: 0,
      arpeggioListValues: 1,
      arpeggioListStartDelta: 1,
      arpeggioListCounterEnd: 1,
      frequencyListNumber: 0,
      frequencyListValues: 1,
      frequencyListStartDelta: 1,
      frequencyListCounterEnd: 1,
      portamentoIncrement: 4,
      portamentoDelay: 1,
      noteTranspose: 0,
      attackEndVolume: 60,
      attackSpeed: 2,
      decayEndVolume: 52,
      decaySpeed: 2,
      sustainDelay: 50,
      releaseEndVolume: 0,
      releaseSpeed: 3,
    },
  },
  {
    name: 'Waveform Cycle Lead',
    category: 'lead',
    params: {
      sampleNumberListNumber: 0,
      sampleNumberListValues: 4,
      sampleNumberListStartDelta: 1,
      sampleNumberListCounterEnd: 4,
      arpeggioListNumber: 0,
      arpeggioListValues: 1,
      arpeggioListStartDelta: 1,
      arpeggioListCounterEnd: 1,
      frequencyListNumber: 0,
      frequencyListValues: 1,
      frequencyListStartDelta: 1,
      frequencyListCounterEnd: 1,
      portamentoIncrement: 0,
      portamentoDelay: 0,
      noteTranspose: 0,
      attackEndVolume: 64,
      attackSpeed: 1,
      decayEndVolume: 56,
      decaySpeed: 2,
      sustainDelay: 30,
      releaseEndVolume: 0,
      releaseSpeed: 5,
    },
  },

  // -- Pad --------------------------------------------------------------------
  {
    name: 'Slow Swell Pad',
    category: 'pad',
    params: {
      sampleNumberListNumber: 0,
      sampleNumberListValues: 1,
      sampleNumberListStartDelta: 1,
      sampleNumberListCounterEnd: 1,
      arpeggioListNumber: 0,
      arpeggioListValues: 1,
      arpeggioListStartDelta: 1,
      arpeggioListCounterEnd: 1,
      frequencyListNumber: 0,
      frequencyListValues: 1,
      frequencyListStartDelta: 1,
      frequencyListCounterEnd: 1,
      portamentoIncrement: 0,
      portamentoDelay: 0,
      noteTranspose: 0,
      attackEndVolume: 48,
      attackSpeed: 8,
      decayEndVolume: 40,
      decaySpeed: 6,
      sustainDelay: 80,
      releaseEndVolume: 0,
      releaseSpeed: 10,
    },
  },
  {
    name: 'Evolving Wave Pad',
    category: 'pad',
    params: {
      sampleNumberListNumber: 0,
      sampleNumberListValues: 6,
      sampleNumberListStartDelta: 2,
      sampleNumberListCounterEnd: 6,
      arpeggioListNumber: 0,
      arpeggioListValues: 1,
      arpeggioListStartDelta: 1,
      arpeggioListCounterEnd: 1,
      frequencyListNumber: 0,
      frequencyListValues: 1,
      frequencyListStartDelta: 1,
      frequencyListCounterEnd: 1,
      portamentoIncrement: 0,
      portamentoDelay: 0,
      noteTranspose: 0,
      attackEndVolume: 44,
      attackSpeed: 6,
      decayEndVolume: 36,
      decaySpeed: 4,
      sustainDelay: 100,
      releaseEndVolume: 0,
      releaseSpeed: 8,
    },
  },

  // -- Drum / Percussion ------------------------------------------------------
  {
    name: 'Short Synth Kick',
    category: 'drum',
    params: {
      sampleNumberListNumber: 0,
      sampleNumberListValues: 1,
      sampleNumberListStartDelta: 1,
      sampleNumberListCounterEnd: 1,
      arpeggioListNumber: 0,
      arpeggioListValues: 1,
      arpeggioListStartDelta: 1,
      arpeggioListCounterEnd: 1,
      frequencyListNumber: 0,
      frequencyListValues: 2,
      frequencyListStartDelta: 1,
      frequencyListCounterEnd: 2,
      portamentoIncrement: 0,
      portamentoDelay: 0,
      noteTranspose: -12,
      attackEndVolume: 64,
      attackSpeed: 1,
      decayEndVolume: 0,
      decaySpeed: 3,
      sustainDelay: 0,
      releaseEndVolume: 0,
      releaseSpeed: 1,
    },
  },
  {
    name: 'Freq Sweep Snare',
    category: 'drum',
    params: {
      sampleNumberListNumber: 0,
      sampleNumberListValues: 1,
      sampleNumberListStartDelta: 1,
      sampleNumberListCounterEnd: 1,
      arpeggioListNumber: 0,
      arpeggioListValues: 1,
      arpeggioListStartDelta: 1,
      arpeggioListCounterEnd: 1,
      frequencyListNumber: 0,
      frequencyListValues: 3,
      frequencyListStartDelta: 1,
      frequencyListCounterEnd: 3,
      portamentoIncrement: 0,
      portamentoDelay: 0,
      noteTranspose: 0,
      attackEndVolume: 64,
      attackSpeed: 1,
      decayEndVolume: 20,
      decaySpeed: 4,
      sustainDelay: 2,
      releaseEndVolume: 0,
      releaseSpeed: 3,
    },
  },

  // -- FX / SFX ---------------------------------------------------------------
  {
    name: 'Pitch Dive FX',
    category: 'fx',
    params: {
      sampleNumberListNumber: 0,
      sampleNumberListValues: 1,
      sampleNumberListStartDelta: 1,
      sampleNumberListCounterEnd: 1,
      arpeggioListNumber: 0,
      arpeggioListValues: 1,
      arpeggioListStartDelta: 1,
      arpeggioListCounterEnd: 1,
      frequencyListNumber: 0,
      frequencyListValues: 4,
      frequencyListStartDelta: 1,
      frequencyListCounterEnd: 4,
      portamentoIncrement: -8,
      portamentoDelay: 0,
      noteTranspose: 12,
      attackEndVolume: 64,
      attackSpeed: 1,
      decayEndVolume: 30,
      decaySpeed: 2,
      sustainDelay: 10,
      releaseEndVolume: 0,
      releaseSpeed: 4,
    },
  },
  {
    name: 'Wave Table Sweep',
    category: 'fx',
    params: {
      sampleNumberListNumber: 0,
      sampleNumberListValues: 8,
      sampleNumberListStartDelta: 1,
      sampleNumberListCounterEnd: 8,
      arpeggioListNumber: 0,
      arpeggioListValues: 1,
      arpeggioListStartDelta: 1,
      arpeggioListCounterEnd: 1,
      frequencyListNumber: 0,
      frequencyListValues: 1,
      frequencyListStartDelta: 1,
      frequencyListCounterEnd: 1,
      portamentoIncrement: 0,
      portamentoDelay: 0,
      noteTranspose: 0,
      attackEndVolume: 56,
      attackSpeed: 2,
      decayEndVolume: 40,
      decaySpeed: 3,
      sustainDelay: 20,
      releaseEndVolume: 0,
      releaseSpeed: 6,
    },
  },

  // -- Arpeggio ---------------------------------------------------------------
  {
    name: 'Fast Chip Arp',
    category: 'arpeggio',
    params: {
      sampleNumberListNumber: 0,
      sampleNumberListValues: 1,
      sampleNumberListStartDelta: 1,
      sampleNumberListCounterEnd: 1,
      arpeggioListNumber: 0,
      arpeggioListValues: 3,
      arpeggioListStartDelta: 1,
      arpeggioListCounterEnd: 3,
      frequencyListNumber: 0,
      frequencyListValues: 1,
      frequencyListStartDelta: 1,
      frequencyListCounterEnd: 1,
      portamentoIncrement: 0,
      portamentoDelay: 0,
      noteTranspose: 0,
      attackEndVolume: 60,
      attackSpeed: 1,
      decayEndVolume: 50,
      decaySpeed: 2,
      sustainDelay: 40,
      releaseEndVolume: 0,
      releaseSpeed: 4,
    },
  },
  {
    name: 'Wave Cycling Arp',
    category: 'arpeggio',
    params: {
      sampleNumberListNumber: 0,
      sampleNumberListValues: 3,
      sampleNumberListStartDelta: 1,
      sampleNumberListCounterEnd: 3,
      arpeggioListNumber: 0,
      arpeggioListValues: 4,
      arpeggioListStartDelta: 1,
      arpeggioListCounterEnd: 4,
      frequencyListNumber: 0,
      frequencyListValues: 1,
      frequencyListStartDelta: 1,
      frequencyListCounterEnd: 1,
      portamentoIncrement: 0,
      portamentoDelay: 0,
      noteTranspose: 0,
      attackEndVolume: 56,
      attackSpeed: 1,
      decayEndVolume: 48,
      decaySpeed: 3,
      sustainDelay: 30,
      releaseEndVolume: 0,
      releaseSpeed: 5,
    },
  },
];
