/**
 * Delta Music 1.0 synth presets — ADSR envelope, vibrato, bend rate, portamento,
 * synth waveform table
 *
 * Each preset defines instrument parameters for dm1_set_instrument_param().
 * ADSR: attackStep/attackDelay, decayStep/decayDelay, sustain,
 *       releaseStep/releaseDelay
 * Vibrato: vibratoWait, vibratoStep, vibratoLength
 * All uint8 params are 0-255 range. bendRate is int8 (-128..127).
 * Categories: bass, lead, pad, drum, fx, arpeggio
 */

export interface DeltaMusic1Preset {
  name: string;
  category: 'bass' | 'lead' | 'pad' | 'drum' | 'fx' | 'arpeggio';
  params: Record<string, number>;
}

export const DELTA_MUSIC_1_PRESETS: DeltaMusic1Preset[] = [
  // -- Bass -------------------------------------------------------------------
  {
    name: 'Solid Synth Bass',
    category: 'bass',
    params: {
      volume: 64,
      attackStep: 16,
      attackDelay: 1,
      decayStep: 4,
      decayDelay: 3,
      sustain: 200,
      releaseStep: 8,
      releaseDelay: 2,
      vibratoWait: 0,
      vibratoStep: 0,
      vibratoLength: 0,
      bendRate: 0,
      portamento: 0,
      tableDelay: 4,
    },
  },
  {
    name: 'Pitch Bend Bass',
    category: 'bass',
    params: {
      volume: 60,
      attackStep: 12,
      attackDelay: 1,
      decayStep: 3,
      decayDelay: 4,
      sustain: 180,
      releaseStep: 6,
      releaseDelay: 3,
      vibratoWait: 0,
      vibratoStep: 0,
      vibratoLength: 0,
      bendRate: -2,
      portamento: 3,
      tableDelay: 6,
    },
  },

  // -- Lead -------------------------------------------------------------------
  {
    name: 'Bright Vibrato Lead',
    category: 'lead',
    params: {
      volume: 56,
      attackStep: 20,
      attackDelay: 1,
      decayStep: 4,
      decayDelay: 2,
      sustain: 190,
      releaseStep: 10,
      releaseDelay: 2,
      vibratoWait: 8,
      vibratoStep: 3,
      vibratoLength: 20,
      bendRate: 0,
      portamento: 0,
      tableDelay: 3,
    },
  },
  {
    name: 'Bending Slide Lead',
    category: 'lead',
    params: {
      volume: 58,
      attackStep: 16,
      attackDelay: 1,
      decayStep: 5,
      decayDelay: 3,
      sustain: 180,
      releaseStep: 8,
      releaseDelay: 2,
      vibratoWait: 12,
      vibratoStep: 4,
      vibratoLength: 16,
      bendRate: 1,
      portamento: 4,
      tableDelay: 2,
    },
  },
  {
    name: 'Staccato Chip Lead',
    category: 'lead',
    params: {
      volume: 64,
      attackStep: 32,
      attackDelay: 1,
      decayStep: 8,
      decayDelay: 1,
      sustain: 120,
      releaseStep: 16,
      releaseDelay: 1,
      vibratoWait: 0,
      vibratoStep: 0,
      vibratoLength: 0,
      bendRate: 0,
      portamento: 0,
      tableDelay: 2,
    },
  },

  // -- Pad --------------------------------------------------------------------
  {
    name: 'Slow Swell Pad',
    category: 'pad',
    params: {
      volume: 48,
      attackStep: 2,
      attackDelay: 6,
      decayStep: 1,
      decayDelay: 8,
      sustain: 140,
      releaseStep: 2,
      releaseDelay: 10,
      vibratoWait: 20,
      vibratoStep: 2,
      vibratoLength: 30,
      bendRate: 0,
      portamento: 0,
      tableDelay: 8,
    },
  },
  {
    name: 'Wavering Pad',
    category: 'pad',
    params: {
      volume: 44,
      attackStep: 3,
      attackDelay: 5,
      decayStep: 1,
      decayDelay: 6,
      sustain: 130,
      releaseStep: 2,
      releaseDelay: 8,
      vibratoWait: 10,
      vibratoStep: 4,
      vibratoLength: 40,
      bendRate: 0,
      portamento: 0,
      tableDelay: 10,
    },
  },

  // -- Drum / Percussion ------------------------------------------------------
  {
    name: 'Table Kick',
    category: 'drum',
    params: {
      volume: 64,
      attackStep: 32,
      attackDelay: 1,
      decayStep: 12,
      decayDelay: 1,
      sustain: 0,
      releaseStep: 32,
      releaseDelay: 1,
      vibratoWait: 0,
      vibratoStep: 0,
      vibratoLength: 0,
      bendRate: -8,
      portamento: 0,
      tableDelay: 1,
    },
  },
  {
    name: 'Bend Snare',
    category: 'drum',
    params: {
      volume: 60,
      attackStep: 32,
      attackDelay: 1,
      decayStep: 10,
      decayDelay: 2,
      sustain: 20,
      releaseStep: 16,
      releaseDelay: 1,
      vibratoWait: 0,
      vibratoStep: 0,
      vibratoLength: 0,
      bendRate: 4,
      portamento: 0,
      tableDelay: 1,
    },
  },

  // -- FX / SFX ---------------------------------------------------------------
  {
    name: 'Pitch Dive FX',
    category: 'fx',
    params: {
      volume: 56,
      attackStep: 20,
      attackDelay: 1,
      decayStep: 4,
      decayDelay: 3,
      sustain: 60,
      releaseStep: 6,
      releaseDelay: 4,
      vibratoWait: 0,
      vibratoStep: 6,
      vibratoLength: 50,
      bendRate: -6,
      portamento: 0,
      tableDelay: 2,
    },
  },
  {
    name: 'Wobble Riser',
    category: 'fx',
    params: {
      volume: 52,
      attackStep: 4,
      attackDelay: 3,
      decayStep: 2,
      decayDelay: 5,
      sustain: 100,
      releaseStep: 4,
      releaseDelay: 6,
      vibratoWait: 0,
      vibratoStep: 8,
      vibratoLength: 60,
      bendRate: 3,
      portamento: 0,
      tableDelay: 3,
    },
  },

  // -- Arpeggio ---------------------------------------------------------------
  {
    name: 'Fast Table Arp',
    category: 'arpeggio',
    params: {
      volume: 56,
      attackStep: 24,
      attackDelay: 1,
      decayStep: 6,
      decayDelay: 2,
      sustain: 170,
      releaseStep: 10,
      releaseDelay: 2,
      vibratoWait: 0,
      vibratoStep: 0,
      vibratoLength: 0,
      bendRate: 0,
      portamento: 0,
      tableDelay: 1,
    },
  },
  {
    name: 'Vibrato Arp',
    category: 'arpeggio',
    params: {
      volume: 52,
      attackStep: 16,
      attackDelay: 1,
      decayStep: 4,
      decayDelay: 3,
      sustain: 160,
      releaseStep: 8,
      releaseDelay: 3,
      vibratoWait: 6,
      vibratoStep: 3,
      vibratoLength: 12,
      bendRate: 0,
      portamento: 0,
      tableDelay: 2,
    },
  },
];
