/**
 * Fred Editor synth presets — pulse synth, blend synth, ADSR envelope, vibrato, arpeggio
 *
 * Each preset defines instrument parameters for fred_set_instrument_param().
 * Categories: bass, lead, pad, drum, fx, arpeggio
 *
 * Instrument types (FredInstrumentType): 0=sample, 1=pulse, 2=blend
 * instSync flags: 0x01=pulse xshot, 0x02=pulse sync, 0x04=blend xshot, 0x08=blend sync
 * Pulse params: pulseRateMin/pulseRatePlus (int8), pulseSpeed, pulseStart, pulseEnd, pulseDelay
 * Blend param: blend, blendDelay
 * ADSR: attackSpeed/attackVolume, decaySpeed/decayVolume, sustainDelay, releaseSpeed/releaseVolume
 * envVol: base envelope volume. period: Amiga period.
 * vibDelay, vibSpeed (int8), vibAmpl (int8)
 * arpSpeed, arpCount: arpeggio control
 * pulseShotCounter, blendShotCounter: one-shot counters
 */

export interface FredEditorPreset {
  name: string;
  category: 'bass' | 'lead' | 'pad' | 'drum' | 'fx' | 'arpeggio';
  params: Record<string, number>;
}

export const FRED_EDITOR_PRESETS: FredEditorPreset[] = [
  // -- Bass ------------------------------------------------------------------
  {
    name: 'Deep Pulse Bass',
    category: 'bass',
    params: {
      instType: 1, // pulse
      repeatLen: 32,
      length: 32,
      period: 428,
      vibDelay: 0,
      vibSpeed: 0,
      vibAmpl: 0,
      envVol: 64,
      attackSpeed: 1,
      attackVolume: 64,
      decaySpeed: 4,
      decayVolume: 48,
      sustainDelay: 32,
      releaseSpeed: 6,
      releaseVolume: 0,
      arpSpeed: 0,
      pulseRateMin: -2,
      pulseRatePlus: 4,
      pulseSpeed: 3,
      pulseStart: 4,
      pulseEnd: 28,
      pulseDelay: 0,
      instSync: 0,
      blend: 0,
      blendDelay: 0,
      pulseShotCounter: 0,
      blendShotCounter: 0,
      arpCount: 0,
    },
  },
  {
    name: 'Blend Sub Bass',
    category: 'bass',
    params: {
      instType: 2, // blend
      repeatLen: 64,
      length: 64,
      period: 508,
      vibDelay: 0,
      vibSpeed: 0,
      vibAmpl: 0,
      envVol: 64,
      attackSpeed: 2,
      attackVolume: 64,
      decaySpeed: 3,
      decayVolume: 52,
      sustainDelay: 48,
      releaseSpeed: 4,
      releaseVolume: 0,
      arpSpeed: 0,
      pulseRateMin: 0,
      pulseRatePlus: 0,
      pulseSpeed: 0,
      pulseStart: 0,
      pulseEnd: 0,
      pulseDelay: 0,
      instSync: 0,
      blend: 8,
      blendDelay: 2,
      pulseShotCounter: 0,
      blendShotCounter: 0,
      arpCount: 0,
    },
  },
  {
    name: 'Pulse Growl Bass',
    category: 'bass',
    params: {
      instType: 1,
      repeatLen: 32,
      length: 32,
      period: 380,
      vibDelay: 4,
      vibSpeed: 3,
      vibAmpl: 2,
      envVol: 60,
      attackSpeed: 1,
      attackVolume: 60,
      decaySpeed: 5,
      decayVolume: 40,
      sustainDelay: 24,
      releaseSpeed: 8,
      releaseVolume: 0,
      arpSpeed: 0,
      pulseRateMin: -4,
      pulseRatePlus: 6,
      pulseSpeed: 5,
      pulseStart: 2,
      pulseEnd: 30,
      pulseDelay: 0,
      instSync: 0x02,
      blend: 0,
      blendDelay: 0,
      pulseShotCounter: 0,
      blendShotCounter: 0,
      arpCount: 0,
    },
  },

  // -- Lead ------------------------------------------------------------------
  {
    name: 'Bright Pulse Lead',
    category: 'lead',
    params: {
      instType: 1,
      repeatLen: 16,
      length: 16,
      period: 214,
      vibDelay: 4,
      vibSpeed: 6,
      vibAmpl: 4,
      envVol: 56,
      attackSpeed: 1,
      attackVolume: 56,
      decaySpeed: 3,
      decayVolume: 40,
      sustainDelay: 20,
      releaseSpeed: 4,
      releaseVolume: 0,
      arpSpeed: 0,
      pulseRateMin: -3,
      pulseRatePlus: 5,
      pulseSpeed: 4,
      pulseStart: 2,
      pulseEnd: 14,
      pulseDelay: 0,
      instSync: 0,
      blend: 0,
      blendDelay: 0,
      pulseShotCounter: 0,
      blendShotCounter: 0,
      arpCount: 0,
    },
  },
  {
    name: 'Blend Sweep Lead',
    category: 'lead',
    params: {
      instType: 2,
      repeatLen: 32,
      length: 32,
      period: 254,
      vibDelay: 2,
      vibSpeed: 8,
      vibAmpl: 5,
      envVol: 54,
      attackSpeed: 1,
      attackVolume: 54,
      decaySpeed: 4,
      decayVolume: 36,
      sustainDelay: 16,
      releaseSpeed: 6,
      releaseVolume: 0,
      arpSpeed: 0,
      pulseRateMin: 0,
      pulseRatePlus: 0,
      pulseSpeed: 0,
      pulseStart: 0,
      pulseEnd: 0,
      pulseDelay: 0,
      instSync: 0,
      blend: 12,
      blendDelay: 1,
      pulseShotCounter: 0,
      blendShotCounter: 0,
      arpCount: 0,
    },
  },
  {
    name: 'Sync Pulse Lead',
    category: 'lead',
    params: {
      instType: 1,
      repeatLen: 16,
      length: 16,
      period: 190,
      vibDelay: 6,
      vibSpeed: 5,
      vibAmpl: 3,
      envVol: 58,
      attackSpeed: 1,
      attackVolume: 58,
      decaySpeed: 2,
      decayVolume: 44,
      sustainDelay: 24,
      releaseSpeed: 3,
      releaseVolume: 0,
      arpSpeed: 0,
      pulseRateMin: -6,
      pulseRatePlus: 8,
      pulseSpeed: 6,
      pulseStart: 1,
      pulseEnd: 15,
      pulseDelay: 0,
      instSync: 0x02,
      blend: 0,
      blendDelay: 0,
      pulseShotCounter: 0,
      blendShotCounter: 0,
      arpCount: 0,
    },
  },

  // -- Pad -------------------------------------------------------------------
  {
    name: 'Slow Blend Pad',
    category: 'pad',
    params: {
      instType: 2,
      repeatLen: 64,
      length: 64,
      period: 340,
      vibDelay: 16,
      vibSpeed: 2,
      vibAmpl: 2,
      envVol: 44,
      attackSpeed: 1,
      attackVolume: 44,
      decaySpeed: 1,
      decayVolume: 36,
      sustainDelay: 64,
      releaseSpeed: 2,
      releaseVolume: 0,
      arpSpeed: 0,
      pulseRateMin: 0,
      pulseRatePlus: 0,
      pulseSpeed: 0,
      pulseStart: 0,
      pulseEnd: 0,
      pulseDelay: 0,
      instSync: 0,
      blend: 4,
      blendDelay: 4,
      pulseShotCounter: 0,
      blendShotCounter: 0,
      arpCount: 0,
    },
  },
  {
    name: 'Pulse Width Pad',
    category: 'pad',
    params: {
      instType: 1,
      repeatLen: 64,
      length: 64,
      period: 380,
      vibDelay: 20,
      vibSpeed: 2,
      vibAmpl: 1,
      envVol: 42,
      attackSpeed: 1,
      attackVolume: 42,
      decaySpeed: 1,
      decayVolume: 34,
      sustainDelay: 80,
      releaseSpeed: 2,
      releaseVolume: 0,
      arpSpeed: 0,
      pulseRateMin: -1,
      pulseRatePlus: 2,
      pulseSpeed: 1,
      pulseStart: 8,
      pulseEnd: 56,
      pulseDelay: 4,
      instSync: 0,
      blend: 0,
      blendDelay: 0,
      pulseShotCounter: 0,
      blendShotCounter: 0,
      arpCount: 0,
    },
  },
  {
    name: 'XShot Blend Pad',
    category: 'pad',
    params: {
      instType: 2,
      repeatLen: 64,
      length: 64,
      period: 428,
      vibDelay: 12,
      vibSpeed: 3,
      vibAmpl: 3,
      envVol: 40,
      attackSpeed: 1,
      attackVolume: 40,
      decaySpeed: 1,
      decayVolume: 32,
      sustainDelay: 48,
      releaseSpeed: 3,
      releaseVolume: 0,
      arpSpeed: 0,
      pulseRateMin: 0,
      pulseRatePlus: 0,
      pulseSpeed: 0,
      pulseStart: 0,
      pulseEnd: 0,
      pulseDelay: 0,
      instSync: 0x04,
      blend: 6,
      blendDelay: 2,
      pulseShotCounter: 0,
      blendShotCounter: 8,
      arpCount: 0,
    },
  },

  // -- Drum ------------------------------------------------------------------
  {
    name: 'Pulse Kick',
    category: 'drum',
    params: {
      instType: 1,
      repeatLen: 0,
      length: 32,
      period: 600,
      vibDelay: 0,
      vibSpeed: 0,
      vibAmpl: 0,
      envVol: 64,
      attackSpeed: 1,
      attackVolume: 64,
      decaySpeed: 8,
      decayVolume: 0,
      sustainDelay: 0,
      releaseSpeed: 1,
      releaseVolume: 0,
      arpSpeed: 0,
      pulseRateMin: -8,
      pulseRatePlus: 12,
      pulseSpeed: 8,
      pulseStart: 4,
      pulseEnd: 28,
      pulseDelay: 0,
      instSync: 0x01,
      blend: 0,
      blendDelay: 0,
      pulseShotCounter: 4,
      blendShotCounter: 0,
      arpCount: 0,
    },
  },
  {
    name: 'Blend Snare',
    category: 'drum',
    params: {
      instType: 2,
      repeatLen: 0,
      length: 16,
      period: 280,
      vibDelay: 0,
      vibSpeed: 0,
      vibAmpl: 0,
      envVol: 60,
      attackSpeed: 1,
      attackVolume: 60,
      decaySpeed: 10,
      decayVolume: 0,
      sustainDelay: 0,
      releaseSpeed: 1,
      releaseVolume: 0,
      arpSpeed: 0,
      pulseRateMin: 0,
      pulseRatePlus: 0,
      pulseSpeed: 0,
      pulseStart: 0,
      pulseEnd: 0,
      pulseDelay: 0,
      instSync: 0x04,
      blend: 24,
      blendDelay: 0,
      pulseShotCounter: 0,
      blendShotCounter: 3,
      arpCount: 0,
    },
  },
  {
    name: 'Hi-Hat Tick',
    category: 'drum',
    params: {
      instType: 1,
      repeatLen: 0,
      length: 8,
      period: 160,
      vibDelay: 0,
      vibSpeed: 0,
      vibAmpl: 0,
      envVol: 48,
      attackSpeed: 1,
      attackVolume: 48,
      decaySpeed: 16,
      decayVolume: 0,
      sustainDelay: 0,
      releaseSpeed: 1,
      releaseVolume: 0,
      arpSpeed: 0,
      pulseRateMin: -10,
      pulseRatePlus: 10,
      pulseSpeed: 12,
      pulseStart: 1,
      pulseEnd: 7,
      pulseDelay: 0,
      instSync: 0x01,
      blend: 0,
      blendDelay: 0,
      pulseShotCounter: 2,
      blendShotCounter: 0,
      arpCount: 0,
    },
  },

  // -- FX --------------------------------------------------------------------
  {
    name: 'Laser Zap',
    category: 'fx',
    params: {
      instType: 1,
      repeatLen: 0,
      length: 32,
      period: 160,
      vibDelay: 0,
      vibSpeed: 0,
      vibAmpl: 0,
      envVol: 64,
      attackSpeed: 1,
      attackVolume: 64,
      decaySpeed: 6,
      decayVolume: 0,
      sustainDelay: 0,
      releaseSpeed: 1,
      releaseVolume: 0,
      arpSpeed: 0,
      pulseRateMin: -12,
      pulseRatePlus: 16,
      pulseSpeed: 10,
      pulseStart: 2,
      pulseEnd: 30,
      pulseDelay: 0,
      instSync: 0,
      blend: 0,
      blendDelay: 0,
      pulseShotCounter: 0,
      blendShotCounter: 0,
      arpCount: 0,
    },
  },
  {
    name: 'Blend Morph Riser',
    category: 'fx',
    params: {
      instType: 2,
      repeatLen: 64,
      length: 64,
      period: 320,
      vibDelay: 0,
      vibSpeed: 8,
      vibAmpl: 6,
      envVol: 52,
      attackSpeed: 1,
      attackVolume: 52,
      decaySpeed: 2,
      decayVolume: 32,
      sustainDelay: 32,
      releaseSpeed: 4,
      releaseVolume: 0,
      arpSpeed: 0,
      pulseRateMin: 0,
      pulseRatePlus: 0,
      pulseSpeed: 0,
      pulseStart: 0,
      pulseEnd: 0,
      pulseDelay: 0,
      instSync: 0,
      blend: 16,
      blendDelay: 0,
      pulseShotCounter: 0,
      blendShotCounter: 0,
      arpCount: 0,
    },
  },
  {
    name: 'Sync Pulse Stab',
    category: 'fx',
    params: {
      instType: 1,
      repeatLen: 0,
      length: 16,
      period: 200,
      vibDelay: 0,
      vibSpeed: 12,
      vibAmpl: 8,
      envVol: 60,
      attackSpeed: 1,
      attackVolume: 60,
      decaySpeed: 12,
      decayVolume: 0,
      sustainDelay: 0,
      releaseSpeed: 1,
      releaseVolume: 0,
      arpSpeed: 0,
      pulseRateMin: -8,
      pulseRatePlus: 10,
      pulseSpeed: 8,
      pulseStart: 1,
      pulseEnd: 15,
      pulseDelay: 0,
      instSync: 0x03,
      blend: 0,
      blendDelay: 0,
      pulseShotCounter: 6,
      blendShotCounter: 0,
      arpCount: 0,
    },
  },

  // -- Arpeggio --------------------------------------------------------------
  {
    name: 'Clean Pulse Arp',
    category: 'arpeggio',
    params: {
      instType: 1,
      repeatLen: 16,
      length: 16,
      period: 254,
      vibDelay: 8,
      vibSpeed: 2,
      vibAmpl: 1,
      envVol: 56,
      attackSpeed: 1,
      attackVolume: 56,
      decaySpeed: 2,
      decayVolume: 44,
      sustainDelay: 32,
      releaseSpeed: 3,
      releaseVolume: 0,
      arpSpeed: 3,
      pulseRateMin: -2,
      pulseRatePlus: 3,
      pulseSpeed: 2,
      pulseStart: 4,
      pulseEnd: 12,
      pulseDelay: 0,
      instSync: 0,
      blend: 0,
      blendDelay: 0,
      pulseShotCounter: 0,
      blendShotCounter: 0,
      arpCount: 3,
    },
  },
  {
    name: 'Blend Arp',
    category: 'arpeggio',
    params: {
      instType: 2,
      repeatLen: 32,
      length: 32,
      period: 286,
      vibDelay: 0,
      vibSpeed: 0,
      vibAmpl: 0,
      envVol: 52,
      attackSpeed: 1,
      attackVolume: 52,
      decaySpeed: 2,
      decayVolume: 40,
      sustainDelay: 24,
      releaseSpeed: 4,
      releaseVolume: 0,
      arpSpeed: 4,
      pulseRateMin: 0,
      pulseRatePlus: 0,
      pulseSpeed: 0,
      pulseStart: 0,
      pulseEnd: 0,
      pulseDelay: 0,
      instSync: 0,
      blend: 6,
      blendDelay: 1,
      pulseShotCounter: 0,
      blendShotCounter: 0,
      arpCount: 4,
    },
  },
  {
    name: 'Fast Sync Arp',
    category: 'arpeggio',
    params: {
      instType: 1,
      repeatLen: 16,
      length: 16,
      period: 214,
      vibDelay: 4,
      vibSpeed: 3,
      vibAmpl: 2,
      envVol: 54,
      attackSpeed: 1,
      attackVolume: 54,
      decaySpeed: 3,
      decayVolume: 38,
      sustainDelay: 16,
      releaseSpeed: 5,
      releaseVolume: 0,
      arpSpeed: 2,
      pulseRateMin: -4,
      pulseRatePlus: 6,
      pulseSpeed: 4,
      pulseStart: 2,
      pulseEnd: 14,
      pulseDelay: 0,
      instSync: 0x02,
      blend: 0,
      blendDelay: 0,
      pulseShotCounter: 0,
      blendShotCounter: 0,
      arpCount: 3,
    },
  },
];
