/**
 * InStereo! 2.0 synth presets — wavetable with ADSR, AMF, vibrato, EG modes
 *
 * Each preset defines instrument parameters for is2_set_instrument_param().
 * Categories: bass, lead, pad, drum, fx, arpeggio
 *
 * EG modes: 0=disabled, 1=calc, 2=free
 * Volume: 0-64. All uint8_t params: 0-255.
 * startLen/stopRep/speedUp/speedDown control the envelope generator shape.
 */

export interface InStereo2Preset {
  name: string;
  category: 'bass' | 'lead' | 'pad' | 'drum' | 'fx' | 'arpeggio';
  params: Record<string, number>;
}

export const IN_STEREO_2_PRESETS: InStereo2Preset[] = [
  // -- Bass ------------------------------------------------------------------
  {
    name: 'Warm Sub Bass',
    category: 'bass',
    params: {
      waveformLength: 64,
      volume: 64,
      vibratoDelay: 0,
      vibratoSpeed: 0,
      vibratoLevel: 0,
      portamentoSpeed: 0,
      adsrLength: 48,
      adsrRepeat: 40,
      sustainPoint: 36,
      sustainSpeed: 2,
      amfLength: 32,
      amfRepeat: 28,
      egMode: 0,
      startLen: 0,
      stopRep: 0,
      speedUp: 0,
      speedDown: 0,
    },
  },
  {
    name: 'EG Calc Bass',
    category: 'bass',
    params: {
      waveformLength: 64,
      volume: 60,
      vibratoDelay: 4,
      vibratoSpeed: 2,
      vibratoLevel: 2,
      portamentoSpeed: 3,
      adsrLength: 40,
      adsrRepeat: 34,
      sustainPoint: 28,
      sustainSpeed: 3,
      amfLength: 24,
      amfRepeat: 20,
      egMode: 1,
      startLen: 8,
      stopRep: 32,
      speedUp: 4,
      speedDown: 2,
    },
  },
  {
    name: 'Growl Bass',
    category: 'bass',
    params: {
      waveformLength: 32,
      volume: 62,
      vibratoDelay: 0,
      vibratoSpeed: 6,
      vibratoLevel: 4,
      portamentoSpeed: 0,
      adsrLength: 24,
      adsrRepeat: 20,
      sustainPoint: 16,
      sustainSpeed: 4,
      amfLength: 16,
      amfRepeat: 12,
      egMode: 2,
      startLen: 4,
      stopRep: 16,
      speedUp: 6,
      speedDown: 3,
    },
  },

  // -- Lead ------------------------------------------------------------------
  {
    name: 'Bright Calc Lead',
    category: 'lead',
    params: {
      waveformLength: 32,
      volume: 56,
      vibratoDelay: 4,
      vibratoSpeed: 8,
      vibratoLevel: 5,
      portamentoSpeed: 2,
      adsrLength: 28,
      adsrRepeat: 24,
      sustainPoint: 20,
      sustainSpeed: 2,
      amfLength: 24,
      amfRepeat: 20,
      egMode: 1,
      startLen: 4,
      stopRep: 24,
      speedUp: 6,
      speedDown: 4,
    },
  },
  {
    name: 'Free Sweep Lead',
    category: 'lead',
    params: {
      waveformLength: 32,
      volume: 54,
      vibratoDelay: 2,
      vibratoSpeed: 10,
      vibratoLevel: 6,
      portamentoSpeed: 4,
      adsrLength: 32,
      adsrRepeat: 28,
      sustainPoint: 24,
      sustainSpeed: 1,
      amfLength: 32,
      amfRepeat: 28,
      egMode: 2,
      startLen: 2,
      stopRep: 28,
      speedUp: 8,
      speedDown: 2,
    },
  },
  {
    name: 'Piercing Lead',
    category: 'lead',
    params: {
      waveformLength: 16,
      volume: 58,
      vibratoDelay: 6,
      vibratoSpeed: 12,
      vibratoLevel: 4,
      portamentoSpeed: 0,
      adsrLength: 20,
      adsrRepeat: 16,
      sustainPoint: 14,
      sustainSpeed: 3,
      amfLength: 16,
      amfRepeat: 12,
      egMode: 1,
      startLen: 2,
      stopRep: 16,
      speedUp: 10,
      speedDown: 6,
    },
  },

  // -- Pad -------------------------------------------------------------------
  {
    name: 'Gentle Pad',
    category: 'pad',
    params: {
      waveformLength: 128,
      volume: 44,
      vibratoDelay: 16,
      vibratoSpeed: 2,
      vibratoLevel: 2,
      portamentoSpeed: 0,
      adsrLength: 128,
      adsrRepeat: 120,
      sustainPoint: 96,
      sustainSpeed: 1,
      amfLength: 64,
      amfRepeat: 56,
      egMode: 1,
      startLen: 8,
      stopRep: 64,
      speedUp: 1,
      speedDown: 1,
    },
  },
  {
    name: 'Free EG Pad',
    category: 'pad',
    params: {
      waveformLength: 128,
      volume: 42,
      vibratoDelay: 20,
      vibratoSpeed: 3,
      vibratoLevel: 3,
      portamentoSpeed: 0,
      adsrLength: 128,
      adsrRepeat: 124,
      sustainPoint: 112,
      sustainSpeed: 1,
      amfLength: 96,
      amfRepeat: 88,
      egMode: 2,
      startLen: 4,
      stopRep: 96,
      speedUp: 2,
      speedDown: 1,
    },
  },
  {
    name: 'Stereo Motion Pad',
    category: 'pad',
    params: {
      waveformLength: 64,
      volume: 40,
      vibratoDelay: 12,
      vibratoSpeed: 4,
      vibratoLevel: 4,
      portamentoSpeed: 1,
      adsrLength: 96,
      adsrRepeat: 88,
      sustainPoint: 80,
      sustainSpeed: 1,
      amfLength: 48,
      amfRepeat: 40,
      egMode: 2,
      startLen: 6,
      stopRep: 48,
      speedUp: 3,
      speedDown: 2,
    },
  },

  // -- Drum ------------------------------------------------------------------
  {
    name: 'Synth Kick',
    category: 'drum',
    params: {
      waveformLength: 32,
      volume: 64,
      vibratoDelay: 0,
      vibratoSpeed: 0,
      vibratoLevel: 0,
      portamentoSpeed: 0,
      adsrLength: 8,
      adsrRepeat: 0,
      sustainPoint: 0,
      sustainSpeed: 0,
      amfLength: 8,
      amfRepeat: 0,
      egMode: 1,
      startLen: 2,
      stopRep: 6,
      speedUp: 12,
      speedDown: 8,
    },
  },
  {
    name: 'Crack Snare',
    category: 'drum',
    params: {
      waveformLength: 16,
      volume: 60,
      vibratoDelay: 0,
      vibratoSpeed: 0,
      vibratoLevel: 0,
      portamentoSpeed: 0,
      adsrLength: 6,
      adsrRepeat: 0,
      sustainPoint: 0,
      sustainSpeed: 0,
      amfLength: 4,
      amfRepeat: 0,
      egMode: 2,
      startLen: 1,
      stopRep: 4,
      speedUp: 16,
      speedDown: 12,
    },
  },
  {
    name: 'Metallic Hat',
    category: 'drum',
    params: {
      waveformLength: 16,
      volume: 48,
      vibratoDelay: 0,
      vibratoSpeed: 0,
      vibratoLevel: 0,
      portamentoSpeed: 0,
      adsrLength: 4,
      adsrRepeat: 0,
      sustainPoint: 0,
      sustainSpeed: 0,
      amfLength: 4,
      amfRepeat: 0,
      egMode: 1,
      startLen: 1,
      stopRep: 3,
      speedUp: 20,
      speedDown: 16,
    },
  },

  // -- FX --------------------------------------------------------------------
  {
    name: 'Rising Sweep',
    category: 'fx',
    params: {
      waveformLength: 64,
      volume: 52,
      vibratoDelay: 0,
      vibratoSpeed: 14,
      vibratoLevel: 10,
      portamentoSpeed: 6,
      adsrLength: 64,
      adsrRepeat: 0,
      sustainPoint: 0,
      sustainSpeed: 0,
      amfLength: 48,
      amfRepeat: 0,
      egMode: 2,
      startLen: 2,
      stopRep: 48,
      speedUp: 4,
      speedDown: 1,
    },
  },
  {
    name: 'Descending Wail',
    category: 'fx',
    params: {
      waveformLength: 32,
      volume: 56,
      vibratoDelay: 0,
      vibratoSpeed: 16,
      vibratoLevel: 12,
      portamentoSpeed: 0,
      adsrLength: 32,
      adsrRepeat: 0,
      sustainPoint: 0,
      sustainSpeed: 0,
      amfLength: 24,
      amfRepeat: 0,
      egMode: 1,
      startLen: 4,
      stopRep: 24,
      speedUp: 2,
      speedDown: 8,
    },
  },
  {
    name: 'Calc Wobble',
    category: 'fx',
    params: {
      waveformLength: 64,
      volume: 50,
      vibratoDelay: 0,
      vibratoSpeed: 8,
      vibratoLevel: 16,
      portamentoSpeed: 0,
      adsrLength: 48,
      adsrRepeat: 40,
      sustainPoint: 32,
      sustainSpeed: 2,
      amfLength: 32,
      amfRepeat: 24,
      egMode: 1,
      startLen: 4,
      stopRep: 32,
      speedUp: 6,
      speedDown: 6,
    },
  },

  // -- Arpeggio --------------------------------------------------------------
  {
    name: 'Clean Arp',
    category: 'arpeggio',
    params: {
      waveformLength: 32,
      volume: 56,
      vibratoDelay: 8,
      vibratoSpeed: 2,
      vibratoLevel: 1,
      portamentoSpeed: 0,
      adsrLength: 40,
      adsrRepeat: 36,
      sustainPoint: 32,
      sustainSpeed: 1,
      amfLength: 32,
      amfRepeat: 28,
      egMode: 0,
      startLen: 0,
      stopRep: 0,
      speedUp: 0,
      speedDown: 0,
    },
  },
  {
    name: 'EG Arp',
    category: 'arpeggio',
    params: {
      waveformLength: 32,
      volume: 52,
      vibratoDelay: 0,
      vibratoSpeed: 0,
      vibratoLevel: 0,
      portamentoSpeed: 0,
      adsrLength: 36,
      adsrRepeat: 32,
      sustainPoint: 28,
      sustainSpeed: 2,
      amfLength: 24,
      amfRepeat: 20,
      egMode: 1,
      startLen: 2,
      stopRep: 20,
      speedUp: 4,
      speedDown: 3,
    },
  },
];
