/**
 * InStereo! 1.0 synth presets — dual waveforms, ADSR, vibrato, EGC, portamento
 *
 * Each preset defines instrument parameters for is1_set_instrument_param().
 * Categories: bass, lead, pad, drum, fx, arpeggio
 *
 * EGC modes: 0=off, 1=ones (one-shot), 2=repeat
 * Volume: 0-64. Waveform length: power of 2 (16/32/64/128).
 * All uint8_t params: 0-255 unless noted.
 */

export interface InStereo1Preset {
  name: string;
  category: 'bass' | 'lead' | 'pad' | 'drum' | 'fx' | 'arpeggio';
  params: Record<string, number>;
}

export const IN_STEREO_1_PRESETS: InStereo1Preset[] = [
  // -- Bass ------------------------------------------------------------------
  {
    name: 'Thick Sub Bass',
    category: 'bass',
    params: {
      synthesisEnabled: 1,
      waveformNumber: 0,
      waveformLength: 64,
      repeatLength: 64,
      volume: 64,
      portamentoEnabled: 0,
      portamentoSpeed: 0,
      adsrEnabled: 1,
      adsrTableNumber: 0,
      adsrTableLength: 48,
      vibratoDelay: 0,
      vibratoSpeed: 0,
      vibratoLevel: 0,
      egcOffset: 0,
      egcMode: 0,
      egcTableNumber: 0,
      egcTableLength: 0,
    },
  },
  {
    name: 'Portamento Bass',
    category: 'bass',
    params: {
      synthesisEnabled: 1,
      waveformNumber: 0,
      waveformLength: 64,
      repeatLength: 64,
      volume: 60,
      portamentoEnabled: 1,
      portamentoSpeed: 4,
      adsrEnabled: 1,
      adsrTableNumber: 0,
      adsrTableLength: 40,
      vibratoDelay: 6,
      vibratoSpeed: 3,
      vibratoLevel: 2,
      egcOffset: 0,
      egcMode: 1,
      egcTableNumber: 0,
      egcTableLength: 16,
    },
  },
  {
    name: 'Punch Bass',
    category: 'bass',
    params: {
      synthesisEnabled: 1,
      waveformNumber: 0,
      waveformLength: 32,
      repeatLength: 32,
      volume: 62,
      portamentoEnabled: 0,
      portamentoSpeed: 0,
      adsrEnabled: 1,
      adsrTableNumber: 0,
      adsrTableLength: 20,
      vibratoDelay: 0,
      vibratoSpeed: 0,
      vibratoLevel: 0,
      egcOffset: 0,
      egcMode: 1,
      egcTableNumber: 0,
      egcTableLength: 12,
    },
  },

  // -- Lead ------------------------------------------------------------------
  {
    name: 'Vibrato Lead',
    category: 'lead',
    params: {
      synthesisEnabled: 1,
      waveformNumber: 0,
      waveformLength: 32,
      repeatLength: 32,
      volume: 56,
      portamentoEnabled: 1,
      portamentoSpeed: 2,
      adsrEnabled: 1,
      adsrTableNumber: 0,
      adsrTableLength: 32,
      vibratoDelay: 4,
      vibratoSpeed: 8,
      vibratoLevel: 6,
      egcOffset: 0,
      egcMode: 2,
      egcTableNumber: 0,
      egcTableLength: 24,
    },
  },
  {
    name: 'Sharp Attack Lead',
    category: 'lead',
    params: {
      synthesisEnabled: 1,
      waveformNumber: 0,
      waveformLength: 32,
      repeatLength: 32,
      volume: 58,
      portamentoEnabled: 0,
      portamentoSpeed: 0,
      adsrEnabled: 1,
      adsrTableNumber: 0,
      adsrTableLength: 24,
      vibratoDelay: 8,
      vibratoSpeed: 5,
      vibratoLevel: 4,
      egcOffset: 0,
      egcMode: 1,
      egcTableNumber: 0,
      egcTableLength: 20,
    },
  },
  {
    name: 'Sliding Lead',
    category: 'lead',
    params: {
      synthesisEnabled: 1,
      waveformNumber: 0,
      waveformLength: 32,
      repeatLength: 32,
      volume: 54,
      portamentoEnabled: 1,
      portamentoSpeed: 6,
      adsrEnabled: 1,
      adsrTableNumber: 0,
      adsrTableLength: 36,
      vibratoDelay: 2,
      vibratoSpeed: 10,
      vibratoLevel: 5,
      egcOffset: 0,
      egcMode: 2,
      egcTableNumber: 0,
      egcTableLength: 32,
    },
  },

  // -- Pad -------------------------------------------------------------------
  {
    name: 'Slow Evolving Pad',
    category: 'pad',
    params: {
      synthesisEnabled: 1,
      waveformNumber: 0,
      waveformLength: 128,
      repeatLength: 128,
      volume: 44,
      portamentoEnabled: 0,
      portamentoSpeed: 0,
      adsrEnabled: 1,
      adsrTableNumber: 0,
      adsrTableLength: 128,
      vibratoDelay: 16,
      vibratoSpeed: 2,
      vibratoLevel: 2,
      egcOffset: 0,
      egcMode: 2,
      egcTableNumber: 0,
      egcTableLength: 64,
    },
  },
  {
    name: 'Stereo Wash Pad',
    category: 'pad',
    params: {
      synthesisEnabled: 1,
      waveformNumber: 0,
      waveformLength: 128,
      repeatLength: 128,
      volume: 40,
      portamentoEnabled: 0,
      portamentoSpeed: 0,
      adsrEnabled: 1,
      adsrTableNumber: 0,
      adsrTableLength: 96,
      vibratoDelay: 20,
      vibratoSpeed: 3,
      vibratoLevel: 3,
      egcOffset: 0,
      egcMode: 2,
      egcTableNumber: 0,
      egcTableLength: 48,
    },
  },
  {
    name: 'Drifting Pad',
    category: 'pad',
    params: {
      synthesisEnabled: 1,
      waveformNumber: 0,
      waveformLength: 64,
      repeatLength: 64,
      volume: 42,
      portamentoEnabled: 1,
      portamentoSpeed: 1,
      adsrEnabled: 1,
      adsrTableNumber: 0,
      adsrTableLength: 80,
      vibratoDelay: 12,
      vibratoSpeed: 4,
      vibratoLevel: 4,
      egcOffset: 0,
      egcMode: 2,
      egcTableNumber: 0,
      egcTableLength: 40,
    },
  },

  // -- Drum ------------------------------------------------------------------
  {
    name: 'Synth Kick',
    category: 'drum',
    params: {
      synthesisEnabled: 1,
      waveformNumber: 0,
      waveformLength: 32,
      repeatLength: 0,
      volume: 64,
      portamentoEnabled: 0,
      portamentoSpeed: 0,
      adsrEnabled: 1,
      adsrTableNumber: 0,
      adsrTableLength: 8,
      vibratoDelay: 0,
      vibratoSpeed: 0,
      vibratoLevel: 0,
      egcOffset: 0,
      egcMode: 1,
      egcTableNumber: 0,
      egcTableLength: 6,
    },
  },
  {
    name: 'Short Snare',
    category: 'drum',
    params: {
      synthesisEnabled: 1,
      waveformNumber: 0,
      waveformLength: 16,
      repeatLength: 0,
      volume: 60,
      portamentoEnabled: 0,
      portamentoSpeed: 0,
      adsrEnabled: 1,
      adsrTableNumber: 0,
      adsrTableLength: 6,
      vibratoDelay: 0,
      vibratoSpeed: 0,
      vibratoLevel: 0,
      egcOffset: 0,
      egcMode: 0,
      egcTableNumber: 0,
      egcTableLength: 0,
    },
  },
  {
    name: 'Tight Hat',
    category: 'drum',
    params: {
      synthesisEnabled: 1,
      waveformNumber: 0,
      waveformLength: 16,
      repeatLength: 0,
      volume: 48,
      portamentoEnabled: 0,
      portamentoSpeed: 0,
      adsrEnabled: 1,
      adsrTableNumber: 0,
      adsrTableLength: 4,
      vibratoDelay: 0,
      vibratoSpeed: 0,
      vibratoLevel: 0,
      egcOffset: 0,
      egcMode: 0,
      egcTableNumber: 0,
      egcTableLength: 0,
    },
  },

  // -- FX --------------------------------------------------------------------
  {
    name: 'EGC Sweep',
    category: 'fx',
    params: {
      synthesisEnabled: 1,
      waveformNumber: 0,
      waveformLength: 64,
      repeatLength: 64,
      volume: 52,
      portamentoEnabled: 0,
      portamentoSpeed: 0,
      adsrEnabled: 1,
      adsrTableNumber: 0,
      adsrTableLength: 48,
      vibratoDelay: 0,
      vibratoSpeed: 12,
      vibratoLevel: 10,
      egcOffset: 0,
      egcMode: 1,
      egcTableNumber: 0,
      egcTableLength: 48,
    },
  },
  {
    name: 'Vibrato Stab',
    category: 'fx',
    params: {
      synthesisEnabled: 1,
      waveformNumber: 0,
      waveformLength: 32,
      repeatLength: 0,
      volume: 64,
      portamentoEnabled: 0,
      portamentoSpeed: 0,
      adsrEnabled: 1,
      adsrTableNumber: 0,
      adsrTableLength: 12,
      vibratoDelay: 0,
      vibratoSpeed: 16,
      vibratoLevel: 12,
      egcOffset: 0,
      egcMode: 0,
      egcTableNumber: 0,
      egcTableLength: 0,
    },
  },
  {
    name: 'Riser',
    category: 'fx',
    params: {
      synthesisEnabled: 1,
      waveformNumber: 0,
      waveformLength: 64,
      repeatLength: 64,
      volume: 48,
      portamentoEnabled: 1,
      portamentoSpeed: 8,
      adsrEnabled: 1,
      adsrTableNumber: 0,
      adsrTableLength: 64,
      vibratoDelay: 0,
      vibratoSpeed: 6,
      vibratoLevel: 8,
      egcOffset: 0,
      egcMode: 2,
      egcTableNumber: 0,
      egcTableLength: 64,
    },
  },

  // -- Arpeggio --------------------------------------------------------------
  {
    name: 'Clean Chip Arp',
    category: 'arpeggio',
    params: {
      synthesisEnabled: 1,
      waveformNumber: 0,
      waveformLength: 32,
      repeatLength: 32,
      volume: 56,
      portamentoEnabled: 0,
      portamentoSpeed: 0,
      adsrEnabled: 1,
      adsrTableNumber: 0,
      adsrTableLength: 40,
      vibratoDelay: 8,
      vibratoSpeed: 2,
      vibratoLevel: 1,
      egcOffset: 0,
      egcMode: 0,
      egcTableNumber: 0,
      egcTableLength: 0,
    },
  },
  {
    name: 'EGC Arp',
    category: 'arpeggio',
    params: {
      synthesisEnabled: 1,
      waveformNumber: 0,
      waveformLength: 32,
      repeatLength: 32,
      volume: 52,
      portamentoEnabled: 0,
      portamentoSpeed: 0,
      adsrEnabled: 1,
      adsrTableNumber: 0,
      adsrTableLength: 36,
      vibratoDelay: 0,
      vibratoSpeed: 0,
      vibratoLevel: 0,
      egcOffset: 0,
      egcMode: 2,
      egcTableNumber: 0,
      egcTableLength: 24,
    },
  },
];
