/**
 * Sonic Arranger synth presets — 17 synthesis effects + ADSR/AMF/vibrato
 *
 * Each preset defines instrument parameters for sa_set_instrument_param().
 * Categories: bass, lead, pad, drum, fx, arpeggio
 */

export interface SonicArrangerPreset {
  name: string;
  category: 'bass' | 'lead' | 'pad' | 'drum' | 'fx' | 'arpeggio';
  params: Record<string, number>;
}

export const SONIC_ARRANGER_PRESETS: SonicArrangerPreset[] = [
  // ── Bass ─────────────────────────────────────────────────────────────────
  {
    name: 'Deep Sub Bass',
    category: 'bass',
    params: {
      type: 1, // synth
      waveformNumber: 0,
      waveformLength: 64,
      repeatLength: 64,
      volume: 64,
      fineTuning: 0,
      portamentoSpeed: 0,
      vibratoDelay: 0,
      vibratoSpeed: 0,
      vibratoLevel: 0,
      amfNumber: 0,
      amfDelay: 0,
      amfLength: 128,
      amfRepeat: 0,
      adsrNumber: 0,
      adsrDelay: 0,
      adsrLength: 64,
      adsrRepeat: 60,
      sustainPoint: 48,
      sustainDelay: 0,
      effect: 13, // LowPassFilter1
      effectArg1: 4,
      effectArg2: 8,
      effectArg3: 0,
      effectDelay: 0,
    },
  },
  {
    name: 'Acid Bass',
    category: 'bass',
    params: {
      type: 1,
      waveformNumber: 0,
      waveformLength: 64,
      repeatLength: 64,
      volume: 60,
      fineTuning: 0,
      portamentoSpeed: 3,
      vibratoDelay: 8,
      vibratoSpeed: 6,
      vibratoLevel: 4,
      amfNumber: 0,
      amfDelay: 0,
      amfLength: 128,
      amfRepeat: 0,
      adsrNumber: 0,
      adsrDelay: 0,
      adsrLength: 32,
      adsrRepeat: 28,
      sustainPoint: 20,
      sustainDelay: 4,
      effect: 14, // LowPassFilter2
      effectArg1: 8,
      effectArg2: 16,
      effectArg3: 2,
      effectDelay: 1,
    },
  },
  {
    name: 'Wobble Bass',
    category: 'bass',
    params: {
      type: 1,
      waveformNumber: 0,
      waveformLength: 64,
      repeatLength: 64,
      volume: 58,
      fineTuning: 0,
      portamentoSpeed: 0,
      vibratoDelay: 0,
      vibratoSpeed: 12,
      vibratoLevel: 8,
      amfNumber: 0,
      amfDelay: 0,
      amfLength: 64,
      amfRepeat: 0,
      adsrNumber: 0,
      adsrDelay: 0,
      adsrLength: 48,
      adsrRepeat: 40,
      sustainPoint: 32,
      sustainDelay: 0,
      effect: 9, // Metamorph
      effectArg1: 6,
      effectArg2: 12,
      effectArg3: 0,
      effectDelay: 2,
    },
  },
  {
    name: 'Funky Slap Bass',
    category: 'bass',
    params: {
      type: 1,
      waveformNumber: 0,
      waveformLength: 32,
      repeatLength: 32,
      volume: 64,
      fineTuning: 0,
      portamentoSpeed: 0,
      vibratoDelay: 0,
      vibratoSpeed: 0,
      vibratoLevel: 0,
      amfNumber: 0,
      amfDelay: 0,
      amfLength: 32,
      amfRepeat: 0,
      adsrNumber: 0,
      adsrDelay: 0,
      adsrLength: 16,
      adsrRepeat: 12,
      sustainPoint: 0,
      sustainDelay: 0,
      effect: 1, // WaveNegator
      effectArg1: 2,
      effectArg2: 0,
      effectArg3: 0,
      effectDelay: 0,
    },
  },

  // ── Lead ─────────────────────────────────────────────────────────────────
  {
    name: 'Screaming Lead',
    category: 'lead',
    params: {
      type: 1,
      waveformNumber: 0,
      waveformLength: 32,
      repeatLength: 32,
      volume: 56,
      fineTuning: 0,
      portamentoSpeed: 2,
      vibratoDelay: 4,
      vibratoSpeed: 8,
      vibratoLevel: 6,
      amfNumber: 0,
      amfDelay: 2,
      amfLength: 64,
      amfRepeat: 0,
      adsrNumber: 0,
      adsrDelay: 0,
      adsrLength: 32,
      adsrRepeat: 28,
      sustainPoint: 24,
      sustainDelay: 0,
      effect: 10, // Laser
      effectArg1: 4,
      effectArg2: 2,
      effectArg3: 0,
      effectDelay: 0,
    },
  },
  {
    name: 'Alien Voice Lead',
    category: 'lead',
    params: {
      type: 1,
      waveformNumber: 0,
      waveformLength: 64,
      repeatLength: 64,
      volume: 52,
      fineTuning: 0,
      portamentoSpeed: 0,
      vibratoDelay: 2,
      vibratoSpeed: 10,
      vibratoLevel: 5,
      amfNumber: 0,
      amfDelay: 0,
      amfLength: 128,
      amfRepeat: 0,
      adsrNumber: 0,
      adsrDelay: 0,
      adsrLength: 48,
      adsrRepeat: 40,
      sustainPoint: 36,
      sustainDelay: 2,
      effect: 5, // AlienVoice
      effectArg1: 3,
      effectArg2: 7,
      effectArg3: 0,
      effectDelay: 1,
    },
  },
  {
    name: 'Poly Negator Lead',
    category: 'lead',
    params: {
      type: 1,
      waveformNumber: 0,
      waveformLength: 32,
      repeatLength: 32,
      volume: 60,
      fineTuning: 0,
      portamentoSpeed: 1,
      vibratoDelay: 6,
      vibratoSpeed: 4,
      vibratoLevel: 3,
      amfNumber: 0,
      amfDelay: 0,
      amfLength: 64,
      amfRepeat: 0,
      adsrNumber: 0,
      adsrDelay: 0,
      adsrLength: 40,
      adsrRepeat: 36,
      sustainPoint: 32,
      sustainDelay: 0,
      effect: 6, // PolyNegator
      effectArg1: 2,
      effectArg2: 4,
      effectArg3: 0,
      effectDelay: 0,
    },
  },
  {
    name: 'Oscillator Sync Lead',
    category: 'lead',
    params: {
      type: 1,
      waveformNumber: 0,
      waveformLength: 64,
      repeatLength: 64,
      volume: 58,
      fineTuning: 0,
      portamentoSpeed: 4,
      vibratoDelay: 0,
      vibratoSpeed: 6,
      vibratoLevel: 4,
      amfNumber: 0,
      amfDelay: 0,
      amfLength: 128,
      amfRepeat: 0,
      adsrNumber: 0,
      adsrDelay: 0,
      adsrLength: 64,
      adsrRepeat: 56,
      sustainPoint: 48,
      sustainDelay: 0,
      effect: 15, // Oszilator
      effectArg1: 8,
      effectArg2: 4,
      effectArg3: 0,
      effectDelay: 0,
    },
  },

  // ── Pad ──────────────────────────────────────────────────────────────────
  {
    name: 'Warm Pad',
    category: 'pad',
    params: {
      type: 1,
      waveformNumber: 0,
      waveformLength: 128,
      repeatLength: 128,
      volume: 48,
      fineTuning: 0,
      portamentoSpeed: 0,
      vibratoDelay: 16,
      vibratoSpeed: 3,
      vibratoLevel: 2,
      amfNumber: 0,
      amfDelay: 8,
      amfLength: 128,
      amfRepeat: 0,
      adsrNumber: 0,
      adsrDelay: 0,
      adsrLength: 128,
      adsrRepeat: 120,
      sustainPoint: 96,
      sustainDelay: 16,
      effect: 3, // RotateVertical
      effectArg1: 1,
      effectArg2: 0,
      effectArg3: 0,
      effectDelay: 4,
    },
  },
  {
    name: 'Shimmering Pad',
    category: 'pad',
    params: {
      type: 1,
      waveformNumber: 0,
      waveformLength: 128,
      repeatLength: 128,
      volume: 44,
      fineTuning: 0,
      portamentoSpeed: 0,
      vibratoDelay: 12,
      vibratoSpeed: 5,
      vibratoLevel: 3,
      amfNumber: 0,
      amfDelay: 4,
      amfLength: 128,
      amfRepeat: 0,
      adsrNumber: 0,
      adsrDelay: 0,
      adsrLength: 128,
      adsrRepeat: 124,
      sustainPoint: 112,
      sustainDelay: 8,
      effect: 4, // RotateHorizontal
      effectArg1: 2,
      effectArg2: 1,
      effectArg3: 0,
      effectDelay: 2,
    },
  },
  {
    name: 'Wave Alias Pad',
    category: 'pad',
    params: {
      type: 1,
      waveformNumber: 0,
      waveformLength: 128,
      repeatLength: 128,
      volume: 42,
      fineTuning: 0,
      portamentoSpeed: 0,
      vibratoDelay: 20,
      vibratoSpeed: 2,
      vibratoLevel: 2,
      amfNumber: 0,
      amfDelay: 0,
      amfLength: 128,
      amfRepeat: 0,
      adsrNumber: 0,
      adsrDelay: 0,
      adsrLength: 128,
      adsrRepeat: 126,
      sustainPoint: 120,
      sustainDelay: 12,
      effect: 11, // WaveAlias
      effectArg1: 3,
      effectArg2: 6,
      effectArg3: 0,
      effectDelay: 6,
    },
  },

  // ── Drum / Percussion ────────────────────────────────────────────────────
  {
    name: 'FM Kick',
    category: 'drum',
    params: {
      type: 1,
      waveformNumber: 0,
      waveformLength: 32,
      repeatLength: 0,
      volume: 64,
      fineTuning: 0,
      portamentoSpeed: 0,
      vibratoDelay: 0,
      vibratoSpeed: 0,
      vibratoLevel: 0,
      amfNumber: 0,
      amfDelay: 0,
      amfLength: 16,
      amfRepeat: 0,
      adsrNumber: 0,
      adsrDelay: 0,
      adsrLength: 8,
      adsrRepeat: 0,
      sustainPoint: 0,
      sustainDelay: 0,
      effect: 17, // FmDrum
      effectArg1: 16,
      effectArg2: 8,
      effectArg3: 4,
      effectDelay: 0,
    },
  },
  {
    name: 'FM Snare',
    category: 'drum',
    params: {
      type: 1,
      waveformNumber: 0,
      waveformLength: 16,
      repeatLength: 0,
      volume: 60,
      fineTuning: 0,
      portamentoSpeed: 0,
      vibratoDelay: 0,
      vibratoSpeed: 0,
      vibratoLevel: 0,
      amfNumber: 0,
      amfDelay: 0,
      amfLength: 8,
      amfRepeat: 0,
      adsrNumber: 0,
      adsrDelay: 0,
      adsrLength: 6,
      adsrRepeat: 0,
      sustainPoint: 0,
      sustainDelay: 0,
      effect: 17, // FmDrum
      effectArg1: 32,
      effectArg2: 24,
      effectArg3: 12,
      effectDelay: 0,
    },
  },
  {
    name: 'Noise Hi-Hat',
    category: 'drum',
    params: {
      type: 1,
      waveformNumber: 0,
      waveformLength: 16,
      repeatLength: 0,
      volume: 48,
      fineTuning: 0,
      portamentoSpeed: 0,
      vibratoDelay: 0,
      vibratoSpeed: 0,
      vibratoLevel: 0,
      amfNumber: 0,
      amfDelay: 0,
      amfLength: 4,
      amfRepeat: 0,
      adsrNumber: 0,
      adsrDelay: 0,
      adsrLength: 4,
      adsrRepeat: 0,
      sustainPoint: 0,
      sustainDelay: 0,
      effect: 12, // NoiseGenerator1
      effectArg1: 8,
      effectArg2: 0,
      effectArg3: 0,
      effectDelay: 0,
    },
  },
  {
    name: 'Noise Clap',
    category: 'drum',
    params: {
      type: 1,
      waveformNumber: 0,
      waveformLength: 32,
      repeatLength: 0,
      volume: 56,
      fineTuning: 0,
      portamentoSpeed: 0,
      vibratoDelay: 0,
      vibratoSpeed: 0,
      vibratoLevel: 0,
      amfNumber: 0,
      amfDelay: 0,
      amfLength: 12,
      amfRepeat: 0,
      adsrNumber: 0,
      adsrDelay: 0,
      adsrLength: 10,
      adsrRepeat: 0,
      sustainPoint: 0,
      sustainDelay: 0,
      effect: 16, // NoiseGenerator2
      effectArg1: 16,
      effectArg2: 4,
      effectArg3: 0,
      effectDelay: 0,
    },
  },

  // ── FX / SFX ─────────────────────────────────────────────────────────────
  {
    name: 'Laser Zap',
    category: 'fx',
    params: {
      type: 1,
      waveformNumber: 0,
      waveformLength: 32,
      repeatLength: 0,
      volume: 64,
      fineTuning: 0,
      portamentoSpeed: 8,
      vibratoDelay: 0,
      vibratoSpeed: 0,
      vibratoLevel: 0,
      amfNumber: 0,
      amfDelay: 0,
      amfLength: 16,
      amfRepeat: 0,
      adsrNumber: 0,
      adsrDelay: 0,
      adsrLength: 12,
      adsrRepeat: 0,
      sustainPoint: 0,
      sustainDelay: 0,
      effect: 10, // Laser
      effectArg1: 16,
      effectArg2: 8,
      effectArg3: 0,
      effectDelay: 0,
    },
  },
  {
    name: 'ShackWave Riser',
    category: 'fx',
    params: {
      type: 1,
      waveformNumber: 0,
      waveformLength: 64,
      repeatLength: 64,
      volume: 52,
      fineTuning: 0,
      portamentoSpeed: 0,
      vibratoDelay: 0,
      vibratoSpeed: 16,
      vibratoLevel: 12,
      amfNumber: 0,
      amfDelay: 0,
      amfLength: 128,
      amfRepeat: 0,
      adsrNumber: 0,
      adsrDelay: 0,
      adsrLength: 128,
      adsrRepeat: 0,
      sustainPoint: 0,
      sustainDelay: 0,
      effect: 7, // ShackWave1
      effectArg1: 4,
      effectArg2: 8,
      effectArg3: 0,
      effectDelay: 0,
    },
  },
  {
    name: 'Free Negator Sweep',
    category: 'fx',
    params: {
      type: 1,
      waveformNumber: 0,
      waveformLength: 64,
      repeatLength: 64,
      volume: 48,
      fineTuning: 0,
      portamentoSpeed: 0,
      vibratoDelay: 0,
      vibratoSpeed: 4,
      vibratoLevel: 6,
      amfNumber: 0,
      amfDelay: 0,
      amfLength: 128,
      amfRepeat: 0,
      adsrNumber: 0,
      adsrDelay: 0,
      adsrLength: 96,
      adsrRepeat: 0,
      sustainPoint: 0,
      sustainDelay: 0,
      effect: 2, // FreeNegator
      effectArg1: 6,
      effectArg2: 3,
      effectArg3: 0,
      effectDelay: 0,
    },
  },

  // ── Arpeggio ─────────────────────────────────────────────────────────────
  {
    name: 'Major Chord Arp',
    category: 'arpeggio',
    params: {
      type: 1,
      waveformNumber: 0,
      waveformLength: 32,
      repeatLength: 32,
      volume: 56,
      fineTuning: 0,
      portamentoSpeed: 0,
      vibratoDelay: 8,
      vibratoSpeed: 3,
      vibratoLevel: 2,
      amfNumber: 0,
      amfDelay: 0,
      amfLength: 64,
      amfRepeat: 0,
      adsrNumber: 0,
      adsrDelay: 0,
      adsrLength: 48,
      adsrRepeat: 44,
      sustainPoint: 40,
      sustainDelay: 0,
      effect: 0, // None
      effectArg1: 0,
      effectArg2: 0,
      effectArg3: 0,
      effectDelay: 0,
    },
  },
  {
    name: 'Minor Chord Arp',
    category: 'arpeggio',
    params: {
      type: 1,
      waveformNumber: 0,
      waveformLength: 32,
      repeatLength: 32,
      volume: 56,
      fineTuning: 0,
      portamentoSpeed: 0,
      vibratoDelay: 8,
      vibratoSpeed: 3,
      vibratoLevel: 2,
      amfNumber: 0,
      amfDelay: 0,
      amfLength: 64,
      amfRepeat: 0,
      adsrNumber: 0,
      adsrDelay: 0,
      adsrLength: 48,
      adsrRepeat: 44,
      sustainPoint: 40,
      sustainDelay: 0,
      effect: 0,
      effectArg1: 0,
      effectArg2: 0,
      effectArg3: 0,
      effectDelay: 0,
    },
  },
];
