/**
 * SoundMon synth presets — wavetable synthesis with ADSR, LFO, EG, FX, MOD
 *
 * Each preset defines instrument parameters for sm_set_instrument_param().
 * Categories: bass, lead, pad, drum, fx, arpeggio
 *
 * FX control values: 0=none, 1=averaging, 2=transform2, 3=transform3,
 *   4=transform4, 5=transform3-alt, 6=wave-copy
 * ADSR/LFO/EG/MOD control: 0=off, 1+=table index (enables the feature)
 * All uint8_t params: 0-255. Volume: 0-64. Wave length: power of 2.
 */

export interface SoundMonPreset {
  name: string;
  category: 'bass' | 'lead' | 'pad' | 'drum' | 'fx' | 'arpeggio';
  params: Record<string, number>;
}

export const SOUND_MON_PRESETS: SoundMonPreset[] = [
  // -- Bass ------------------------------------------------------------------
  {
    name: 'Deep Sub Bass',
    category: 'bass',
    params: {
      isSynth: 1,
      volume: 64,
      waveTable: 0,
      waveLength: 64,
      adsrControl: 1,
      adsrTable: 0,
      adsrLength: 48,
      adsrSpeed: 2,
      lfoControl: 0,
      lfoTable: 0,
      lfoDepth: 0,
      lfoLength: 0,
      lfoDelay: 0,
      lfoSpeed: 0,
      egControl: 0,
      egTable: 0,
      egLength: 0,
      egDelay: 0,
      egSpeed: 0,
      fxControl: 1,
      fxSpeed: 6,
      fxDelay: 0,
      modControl: 0,
      modTable: 0,
      modSpeed: 0,
      modDelay: 0,
      modLength: 0,
    },
  },
  {
    name: 'Squelch Bass',
    category: 'bass',
    params: {
      isSynth: 1,
      volume: 60,
      waveTable: 0,
      waveLength: 32,
      adsrControl: 1,
      adsrTable: 0,
      adsrLength: 32,
      adsrSpeed: 3,
      lfoControl: 1,
      lfoTable: 0,
      lfoDepth: 8,
      lfoLength: 16,
      lfoDelay: 0,
      lfoSpeed: 4,
      egControl: 1,
      egTable: 0,
      egLength: 24,
      egDelay: 0,
      egSpeed: 2,
      fxControl: 2,
      fxSpeed: 4,
      fxDelay: 1,
      modControl: 0,
      modTable: 0,
      modSpeed: 0,
      modDelay: 0,
      modLength: 0,
    },
  },
  {
    name: 'Round Bass',
    category: 'bass',
    params: {
      isSynth: 1,
      volume: 58,
      waveTable: 0,
      waveLength: 64,
      adsrControl: 1,
      adsrTable: 0,
      adsrLength: 40,
      adsrSpeed: 2,
      lfoControl: 0,
      lfoTable: 0,
      lfoDepth: 0,
      lfoLength: 0,
      lfoDelay: 0,
      lfoSpeed: 0,
      egControl: 0,
      egTable: 0,
      egLength: 0,
      egDelay: 0,
      egSpeed: 0,
      fxControl: 1,
      fxSpeed: 3,
      fxDelay: 2,
      modControl: 1,
      modTable: 0,
      modSpeed: 2,
      modDelay: 4,
      modLength: 32,
    },
  },

  // -- Lead ------------------------------------------------------------------
  {
    name: 'Bright Lead',
    category: 'lead',
    params: {
      isSynth: 1,
      volume: 56,
      waveTable: 0,
      waveLength: 32,
      adsrControl: 1,
      adsrTable: 0,
      adsrLength: 24,
      adsrSpeed: 4,
      lfoControl: 1,
      lfoTable: 0,
      lfoDepth: 6,
      lfoLength: 32,
      lfoDelay: 8,
      lfoSpeed: 5,
      egControl: 1,
      egTable: 0,
      egLength: 32,
      egDelay: 0,
      egSpeed: 3,
      fxControl: 3,
      fxSpeed: 3,
      fxDelay: 0,
      modControl: 0,
      modTable: 0,
      modSpeed: 0,
      modDelay: 0,
      modLength: 0,
    },
  },
  {
    name: 'Nasal Lead',
    category: 'lead',
    params: {
      isSynth: 1,
      volume: 52,
      waveTable: 0,
      waveLength: 32,
      adsrControl: 1,
      adsrTable: 0,
      adsrLength: 28,
      adsrSpeed: 3,
      lfoControl: 1,
      lfoTable: 0,
      lfoDepth: 4,
      lfoLength: 24,
      lfoDelay: 4,
      lfoSpeed: 6,
      egControl: 0,
      egTable: 0,
      egLength: 0,
      egDelay: 0,
      egSpeed: 0,
      fxControl: 4,
      fxSpeed: 5,
      fxDelay: 0,
      modControl: 1,
      modTable: 0,
      modSpeed: 3,
      modDelay: 2,
      modLength: 16,
    },
  },
  {
    name: 'Siren Lead',
    category: 'lead',
    params: {
      isSynth: 1,
      volume: 60,
      waveTable: 0,
      waveLength: 32,
      adsrControl: 1,
      adsrTable: 0,
      adsrLength: 48,
      adsrSpeed: 2,
      lfoControl: 1,
      lfoTable: 0,
      lfoDepth: 12,
      lfoLength: 48,
      lfoDelay: 0,
      lfoSpeed: 8,
      egControl: 1,
      egTable: 0,
      egLength: 48,
      egDelay: 0,
      egSpeed: 4,
      fxControl: 2,
      fxSpeed: 2,
      fxDelay: 0,
      modControl: 0,
      modTable: 0,
      modSpeed: 0,
      modDelay: 0,
      modLength: 0,
    },
  },

  // -- Pad -------------------------------------------------------------------
  {
    name: 'Warm Evolving Pad',
    category: 'pad',
    params: {
      isSynth: 1,
      volume: 44,
      waveTable: 0,
      waveLength: 128,
      adsrControl: 1,
      adsrTable: 0,
      adsrLength: 128,
      adsrSpeed: 1,
      lfoControl: 1,
      lfoTable: 0,
      lfoDepth: 3,
      lfoLength: 64,
      lfoDelay: 16,
      lfoSpeed: 2,
      egControl: 1,
      egTable: 0,
      egLength: 64,
      egDelay: 8,
      egSpeed: 1,
      fxControl: 1,
      fxSpeed: 2,
      fxDelay: 6,
      modControl: 1,
      modTable: 0,
      modSpeed: 1,
      modDelay: 12,
      modLength: 64,
    },
  },
  {
    name: 'Glassy Pad',
    category: 'pad',
    params: {
      isSynth: 1,
      volume: 40,
      waveTable: 0,
      waveLength: 64,
      adsrControl: 1,
      adsrTable: 0,
      adsrLength: 96,
      adsrSpeed: 1,
      lfoControl: 1,
      lfoTable: 0,
      lfoDepth: 5,
      lfoLength: 48,
      lfoDelay: 12,
      lfoSpeed: 3,
      egControl: 1,
      egTable: 0,
      egLength: 48,
      egDelay: 4,
      egSpeed: 2,
      fxControl: 3,
      fxSpeed: 1,
      fxDelay: 4,
      modControl: 0,
      modTable: 0,
      modSpeed: 0,
      modDelay: 0,
      modLength: 0,
    },
  },
  {
    name: 'Modulated Texture',
    category: 'pad',
    params: {
      isSynth: 1,
      volume: 42,
      waveTable: 0,
      waveLength: 128,
      adsrControl: 1,
      adsrTable: 0,
      adsrLength: 128,
      adsrSpeed: 1,
      lfoControl: 1,
      lfoTable: 0,
      lfoDepth: 8,
      lfoLength: 64,
      lfoDelay: 0,
      lfoSpeed: 4,
      egControl: 0,
      egTable: 0,
      egLength: 0,
      egDelay: 0,
      egSpeed: 0,
      fxControl: 5,
      fxSpeed: 3,
      fxDelay: 2,
      modControl: 1,
      modTable: 0,
      modSpeed: 2,
      modDelay: 8,
      modLength: 128,
    },
  },

  // -- Drum ------------------------------------------------------------------
  {
    name: 'Synth Kick',
    category: 'drum',
    params: {
      isSynth: 1,
      volume: 64,
      waveTable: 0,
      waveLength: 32,
      adsrControl: 1,
      adsrTable: 0,
      adsrLength: 8,
      adsrSpeed: 8,
      lfoControl: 0,
      lfoTable: 0,
      lfoDepth: 0,
      lfoLength: 0,
      lfoDelay: 0,
      lfoSpeed: 0,
      egControl: 1,
      egTable: 0,
      egLength: 8,
      egDelay: 0,
      egSpeed: 6,
      fxControl: 4,
      fxSpeed: 12,
      fxDelay: 0,
      modControl: 0,
      modTable: 0,
      modSpeed: 0,
      modDelay: 0,
      modLength: 0,
    },
  },
  {
    name: 'Snare Hit',
    category: 'drum',
    params: {
      isSynth: 1,
      volume: 60,
      waveTable: 0,
      waveLength: 16,
      adsrControl: 1,
      adsrTable: 0,
      adsrLength: 6,
      adsrSpeed: 10,
      lfoControl: 0,
      lfoTable: 0,
      lfoDepth: 0,
      lfoLength: 0,
      lfoDelay: 0,
      lfoSpeed: 0,
      egControl: 0,
      egTable: 0,
      egLength: 0,
      egDelay: 0,
      egSpeed: 0,
      fxControl: 2,
      fxSpeed: 16,
      fxDelay: 0,
      modControl: 0,
      modTable: 0,
      modSpeed: 0,
      modDelay: 0,
      modLength: 0,
    },
  },
  {
    name: 'Hi-Hat Tick',
    category: 'drum',
    params: {
      isSynth: 1,
      volume: 48,
      waveTable: 0,
      waveLength: 16,
      adsrControl: 1,
      adsrTable: 0,
      adsrLength: 4,
      adsrSpeed: 12,
      lfoControl: 0,
      lfoTable: 0,
      lfoDepth: 0,
      lfoLength: 0,
      lfoDelay: 0,
      lfoSpeed: 0,
      egControl: 0,
      egTable: 0,
      egLength: 0,
      egDelay: 0,
      egSpeed: 0,
      fxControl: 3,
      fxSpeed: 24,
      fxDelay: 0,
      modControl: 0,
      modTable: 0,
      modSpeed: 0,
      modDelay: 0,
      modLength: 0,
    },
  },

  // -- FX --------------------------------------------------------------------
  {
    name: 'Wave Copy Morph',
    category: 'fx',
    params: {
      isSynth: 1,
      volume: 52,
      waveTable: 0,
      waveLength: 64,
      adsrControl: 1,
      adsrTable: 0,
      adsrLength: 32,
      adsrSpeed: 2,
      lfoControl: 1,
      lfoTable: 0,
      lfoDepth: 10,
      lfoLength: 32,
      lfoDelay: 0,
      lfoSpeed: 6,
      egControl: 0,
      egTable: 0,
      egLength: 0,
      egDelay: 0,
      egSpeed: 0,
      fxControl: 6,
      fxSpeed: 8,
      fxDelay: 0,
      modControl: 0,
      modTable: 0,
      modSpeed: 0,
      modDelay: 0,
      modLength: 0,
    },
  },
  {
    name: 'Glitch Sweep',
    category: 'fx',
    params: {
      isSynth: 1,
      volume: 56,
      waveTable: 0,
      waveLength: 32,
      adsrControl: 1,
      adsrTable: 0,
      adsrLength: 64,
      adsrSpeed: 1,
      lfoControl: 1,
      lfoTable: 0,
      lfoDepth: 16,
      lfoLength: 48,
      lfoDelay: 0,
      lfoSpeed: 10,
      egControl: 1,
      egTable: 0,
      egLength: 32,
      egDelay: 0,
      egSpeed: 6,
      fxControl: 4,
      fxSpeed: 8,
      fxDelay: 0,
      modControl: 1,
      modTable: 0,
      modSpeed: 4,
      modDelay: 0,
      modLength: 32,
    },
  },
  {
    name: 'Descending Zap',
    category: 'fx',
    params: {
      isSynth: 1,
      volume: 64,
      waveTable: 0,
      waveLength: 32,
      adsrControl: 1,
      adsrTable: 0,
      adsrLength: 12,
      adsrSpeed: 6,
      lfoControl: 0,
      lfoTable: 0,
      lfoDepth: 0,
      lfoLength: 0,
      lfoDelay: 0,
      lfoSpeed: 0,
      egControl: 1,
      egTable: 0,
      egLength: 12,
      egDelay: 0,
      egSpeed: 8,
      fxControl: 5,
      fxSpeed: 10,
      fxDelay: 0,
      modControl: 0,
      modTable: 0,
      modSpeed: 0,
      modDelay: 0,
      modLength: 0,
    },
  },

  // -- Arpeggio --------------------------------------------------------------
  {
    name: 'Fast Chip Arp',
    category: 'arpeggio',
    params: {
      isSynth: 1,
      volume: 56,
      waveTable: 0,
      waveLength: 32,
      adsrControl: 1,
      adsrTable: 0,
      adsrLength: 48,
      adsrSpeed: 2,
      lfoControl: 0,
      lfoTable: 0,
      lfoDepth: 0,
      lfoLength: 0,
      lfoDelay: 0,
      lfoSpeed: 0,
      egControl: 0,
      egTable: 0,
      egLength: 0,
      egDelay: 0,
      egSpeed: 0,
      fxControl: 0,
      fxSpeed: 0,
      fxDelay: 0,
      modControl: 0,
      modTable: 0,
      modSpeed: 0,
      modDelay: 0,
      modLength: 0,
    },
  },
  {
    name: 'Modulated Arp',
    category: 'arpeggio',
    params: {
      isSynth: 1,
      volume: 52,
      waveTable: 0,
      waveLength: 32,
      adsrControl: 1,
      adsrTable: 0,
      adsrLength: 40,
      adsrSpeed: 3,
      lfoControl: 1,
      lfoTable: 0,
      lfoDepth: 4,
      lfoLength: 32,
      lfoDelay: 4,
      lfoSpeed: 3,
      egControl: 0,
      egTable: 0,
      egLength: 0,
      egDelay: 0,
      egSpeed: 0,
      fxControl: 0,
      fxSpeed: 0,
      fxDelay: 0,
      modControl: 1,
      modTable: 0,
      modSpeed: 2,
      modDelay: 0,
      modLength: 32,
    },
  },
  {
    name: 'Transform Arp',
    category: 'arpeggio',
    params: {
      isSynth: 1,
      volume: 54,
      waveTable: 0,
      waveLength: 32,
      adsrControl: 1,
      adsrTable: 0,
      adsrLength: 36,
      adsrSpeed: 2,
      lfoControl: 0,
      lfoTable: 0,
      lfoDepth: 0,
      lfoLength: 0,
      lfoDelay: 0,
      lfoSpeed: 0,
      egControl: 1,
      egTable: 0,
      egLength: 24,
      egDelay: 0,
      egSpeed: 3,
      fxControl: 2,
      fxSpeed: 3,
      fxDelay: 2,
      modControl: 0,
      modTable: 0,
      modSpeed: 0,
      modDelay: 0,
      modLength: 0,
    },
  },
];
