/**
 * SoundFactory synth presets — ADSR, vibrato, tremolo, phasing, filter, portamento
 *
 * Each preset defines instrument parameters for sf_set_instrument_param().
 * effectByte is a bitmask of SfInstrFlag:
 *   0x01=ONE_SHOT, 0x02=VIBRATO, 0x04=ARPEGGIO, 0x08=PHASING,
 *   0x10=PORTAMENTO, 0x20=RELEASE, 0x40=TREMOLO, 0x80=FILTER
 * Categories: bass, lead, pad, drum, fx, arpeggio
 */

export interface SoundFactoryPreset {
  name: string;
  category: 'bass' | 'lead' | 'pad' | 'drum' | 'fx' | 'arpeggio';
  params: Record<string, number>;
}

export const SOUND_FACTORY_PRESETS: SoundFactoryPreset[] = [
  // -- Bass -------------------------------------------------------------------
  {
    name: 'Deep Sub Bass',
    category: 'bass',
    params: {
      effectByte: 0xa0, // RELEASE + FILTER
      attackTime: 2,
      decayTime: 20,
      sustainLevel: 200,
      releaseTime: 40,
      filterFrequency: 20,
      filterEnd: 80,
      filterSpeed: 3,
      tremoloSpeed: 0,
      tremoloStep: 0,
      tremoloRange: 0,
      vibratoDelay: 0,
      vibratoSpeed: 0,
      vibratoStep: 0,
      vibratoAmount: 0,
      phasingStart: 0,
      phasingEnd: 0,
      phasingSpeed: 0,
      phasingStep: 0,
      portamentoStep: 0,
      portamentoSpeed: 0,
      arpeggioSpeed: 0,
      waveCount: 1,
      octave: 2,
      dasrSustainOffset: 0,
      dasrReleaseOffset: 0,
    },
  },
  {
    name: 'Acid Squelch Bass',
    category: 'bass',
    params: {
      effectByte: 0xb0, // RELEASE + PORTAMENTO + FILTER
      attackTime: 1,
      decayTime: 12,
      sustainLevel: 160,
      releaseTime: 30,
      filterFrequency: 10,
      filterEnd: 200,
      filterSpeed: 8,
      tremoloSpeed: 0,
      tremoloStep: 0,
      tremoloRange: 0,
      vibratoDelay: 0,
      vibratoSpeed: 0,
      vibratoStep: 0,
      vibratoAmount: 0,
      phasingStart: 0,
      phasingEnd: 0,
      phasingSpeed: 0,
      phasingStep: 0,
      portamentoStep: 80,
      portamentoSpeed: 4,
      arpeggioSpeed: 0,
      waveCount: 2,
      octave: 2,
      dasrSustainOffset: 0,
      dasrReleaseOffset: 0,
    },
  },

  // -- Lead -------------------------------------------------------------------
  {
    name: 'Bright Vibrato Lead',
    category: 'lead',
    params: {
      effectByte: 0x22, // RELEASE + VIBRATO
      attackTime: 1,
      decayTime: 8,
      sustainLevel: 180,
      releaseTime: 20,
      filterFrequency: 0,
      filterEnd: 0,
      filterSpeed: 0,
      tremoloSpeed: 0,
      tremoloStep: 0,
      tremoloRange: 0,
      vibratoDelay: 6,
      vibratoSpeed: 4,
      vibratoStep: 3,
      vibratoAmount: 12,
      phasingStart: 0,
      phasingEnd: 0,
      phasingSpeed: 0,
      phasingStep: 0,
      portamentoStep: 0,
      portamentoSpeed: 0,
      arpeggioSpeed: 0,
      waveCount: 2,
      octave: 4,
      dasrSustainOffset: 0,
      dasrReleaseOffset: 0,
    },
  },
  {
    name: 'Phaser Lead',
    category: 'lead',
    params: {
      effectByte: 0x2a, // RELEASE + PHASING + VIBRATO
      attackTime: 1,
      decayTime: 6,
      sustainLevel: 200,
      releaseTime: 15,
      filterFrequency: 0,
      filterEnd: 0,
      filterSpeed: 0,
      tremoloSpeed: 0,
      tremoloStep: 0,
      tremoloRange: 0,
      vibratoDelay: 10,
      vibratoSpeed: 3,
      vibratoStep: 2,
      vibratoAmount: 8,
      phasingStart: 10,
      phasingEnd: 60,
      phasingSpeed: 4,
      phasingStep: 2,
      portamentoStep: 0,
      portamentoSpeed: 0,
      arpeggioSpeed: 0,
      waveCount: 3,
      octave: 4,
      dasrSustainOffset: 0,
      dasrReleaseOffset: 0,
    },
  },
  {
    name: 'Portamento Glide Lead',
    category: 'lead',
    params: {
      effectByte: 0x32, // RELEASE + PORTAMENTO + VIBRATO
      attackTime: 2,
      decayTime: 10,
      sustainLevel: 190,
      releaseTime: 25,
      filterFrequency: 0,
      filterEnd: 0,
      filterSpeed: 0,
      tremoloSpeed: 0,
      tremoloStep: 0,
      tremoloRange: 0,
      vibratoDelay: 12,
      vibratoSpeed: 5,
      vibratoStep: 2,
      vibratoAmount: 6,
      phasingStart: 0,
      phasingEnd: 0,
      phasingSpeed: 0,
      phasingStep: 0,
      portamentoStep: 120,
      portamentoSpeed: 3,
      arpeggioSpeed: 0,
      waveCount: 2,
      octave: 4,
      dasrSustainOffset: 0,
      dasrReleaseOffset: 0,
    },
  },

  // -- Pad --------------------------------------------------------------------
  {
    name: 'Warm Tremolo Pad',
    category: 'pad',
    params: {
      effectByte: 0x68, // RELEASE + TREMOLO + PHASING
      attackTime: 15,
      decayTime: 30,
      sustainLevel: 140,
      releaseTime: 60,
      filterFrequency: 0,
      filterEnd: 0,
      filterSpeed: 0,
      tremoloSpeed: 3,
      tremoloStep: 2,
      tremoloRange: 20,
      vibratoDelay: 0,
      vibratoSpeed: 0,
      vibratoStep: 0,
      vibratoAmount: 0,
      phasingStart: 5,
      phasingEnd: 40,
      phasingSpeed: 2,
      phasingStep: 1,
      portamentoStep: 0,
      portamentoSpeed: 0,
      arpeggioSpeed: 0,
      waveCount: 4,
      octave: 3,
      dasrSustainOffset: 0,
      dasrReleaseOffset: 0,
    },
  },
  {
    name: 'Filter Sweep Pad',
    category: 'pad',
    params: {
      effectByte: 0xa2, // RELEASE + FILTER + VIBRATO
      attackTime: 20,
      decayTime: 40,
      sustainLevel: 120,
      releaseTime: 80,
      filterFrequency: 5,
      filterEnd: 180,
      filterSpeed: 1,
      tremoloSpeed: 0,
      tremoloStep: 0,
      tremoloRange: 0,
      vibratoDelay: 20,
      vibratoSpeed: 2,
      vibratoStep: 1,
      vibratoAmount: 4,
      phasingStart: 0,
      phasingEnd: 0,
      phasingSpeed: 0,
      phasingStep: 0,
      portamentoStep: 0,
      portamentoSpeed: 0,
      arpeggioSpeed: 0,
      waveCount: 4,
      octave: 3,
      dasrSustainOffset: 0,
      dasrReleaseOffset: 0,
    },
  },

  // -- Drum / Percussion ------------------------------------------------------
  {
    name: 'Synth Kick',
    category: 'drum',
    params: {
      effectByte: 0x81, // FILTER + ONE_SHOT
      attackTime: 0,
      decayTime: 8,
      sustainLevel: 0,
      releaseTime: 0,
      filterFrequency: 200,
      filterEnd: 20,
      filterSpeed: 12,
      tremoloSpeed: 0,
      tremoloStep: 0,
      tremoloRange: 0,
      vibratoDelay: 0,
      vibratoSpeed: 0,
      vibratoStep: 0,
      vibratoAmount: 0,
      phasingStart: 0,
      phasingEnd: 0,
      phasingSpeed: 0,
      phasingStep: 0,
      portamentoStep: 0,
      portamentoSpeed: 0,
      arpeggioSpeed: 0,
      waveCount: 1,
      octave: 1,
      dasrSustainOffset: 0,
      dasrReleaseOffset: 0,
    },
  },
  {
    name: 'Noise Snare',
    category: 'drum',
    params: {
      effectByte: 0x41, // TREMOLO + ONE_SHOT
      attackTime: 0,
      decayTime: 6,
      sustainLevel: 0,
      releaseTime: 0,
      filterFrequency: 0,
      filterEnd: 0,
      filterSpeed: 0,
      tremoloSpeed: 8,
      tremoloStep: 6,
      tremoloRange: 60,
      vibratoDelay: 0,
      vibratoSpeed: 0,
      vibratoStep: 0,
      vibratoAmount: 0,
      phasingStart: 0,
      phasingEnd: 0,
      phasingSpeed: 0,
      phasingStep: 0,
      portamentoStep: 0,
      portamentoSpeed: 0,
      arpeggioSpeed: 0,
      waveCount: 1,
      octave: 4,
      dasrSustainOffset: 0,
      dasrReleaseOffset: 0,
    },
  },
  {
    name: 'Closed Hat',
    category: 'drum',
    params: {
      effectByte: 0x09, // PHASING + ONE_SHOT
      attackTime: 0,
      decayTime: 3,
      sustainLevel: 0,
      releaseTime: 0,
      filterFrequency: 0,
      filterEnd: 0,
      filterSpeed: 0,
      tremoloSpeed: 0,
      tremoloStep: 0,
      tremoloRange: 0,
      vibratoDelay: 0,
      vibratoSpeed: 0,
      vibratoStep: 0,
      vibratoAmount: 0,
      phasingStart: 2,
      phasingEnd: 30,
      phasingSpeed: 12,
      phasingStep: 4,
      portamentoStep: 0,
      portamentoSpeed: 0,
      arpeggioSpeed: 0,
      waveCount: 1,
      octave: 6,
      dasrSustainOffset: 0,
      dasrReleaseOffset: 0,
    },
  },

  // -- FX / SFX ---------------------------------------------------------------
  {
    name: 'Laser Zap',
    category: 'fx',
    params: {
      effectByte: 0x91, // FILTER + PORTAMENTO + ONE_SHOT
      attackTime: 0,
      decayTime: 15,
      sustainLevel: 0,
      releaseTime: 0,
      filterFrequency: 240,
      filterEnd: 10,
      filterSpeed: 10,
      tremoloSpeed: 0,
      tremoloStep: 0,
      tremoloRange: 0,
      vibratoDelay: 0,
      vibratoSpeed: 0,
      vibratoStep: 0,
      vibratoAmount: 0,
      phasingStart: 0,
      phasingEnd: 0,
      phasingSpeed: 0,
      phasingStep: 0,
      portamentoStep: 200,
      portamentoSpeed: 6,
      arpeggioSpeed: 0,
      waveCount: 1,
      octave: 5,
      dasrSustainOffset: 0,
      dasrReleaseOffset: 0,
    },
  },
  {
    name: 'Rising Phaser Sweep',
    category: 'fx',
    params: {
      effectByte: 0x0a, // PHASING + VIBRATO
      attackTime: 4,
      decayTime: 30,
      sustainLevel: 100,
      releaseTime: 50,
      filterFrequency: 0,
      filterEnd: 0,
      filterSpeed: 0,
      tremoloSpeed: 0,
      tremoloStep: 0,
      tremoloRange: 0,
      vibratoDelay: 0,
      vibratoSpeed: 8,
      vibratoStep: 4,
      vibratoAmount: 20,
      phasingStart: 2,
      phasingEnd: 120,
      phasingSpeed: 1,
      phasingStep: 3,
      portamentoStep: 0,
      portamentoSpeed: 0,
      arpeggioSpeed: 0,
      waveCount: 2,
      octave: 4,
      dasrSustainOffset: 0,
      dasrReleaseOffset: 0,
    },
  },

  // -- Arpeggio ---------------------------------------------------------------
  {
    name: 'Fast Chip Arp',
    category: 'arpeggio',
    params: {
      effectByte: 0x24, // RELEASE + ARPEGGIO
      attackTime: 0,
      decayTime: 4,
      sustainLevel: 220,
      releaseTime: 10,
      filterFrequency: 0,
      filterEnd: 0,
      filterSpeed: 0,
      tremoloSpeed: 0,
      tremoloStep: 0,
      tremoloRange: 0,
      vibratoDelay: 0,
      vibratoSpeed: 0,
      vibratoStep: 0,
      vibratoAmount: 0,
      phasingStart: 0,
      phasingEnd: 0,
      phasingSpeed: 0,
      phasingStep: 0,
      portamentoStep: 0,
      portamentoSpeed: 0,
      arpeggioSpeed: 2,
      waveCount: 1,
      octave: 4,
      dasrSustainOffset: 0,
      dasrReleaseOffset: 0,
    },
  },
  {
    name: 'Slow Phased Arp',
    category: 'arpeggio',
    params: {
      effectByte: 0x2c, // RELEASE + PHASING + ARPEGGIO
      attackTime: 2,
      decayTime: 10,
      sustainLevel: 180,
      releaseTime: 20,
      filterFrequency: 0,
      filterEnd: 0,
      filterSpeed: 0,
      tremoloSpeed: 0,
      tremoloStep: 0,
      tremoloRange: 0,
      vibratoDelay: 0,
      vibratoSpeed: 0,
      vibratoStep: 0,
      vibratoAmount: 0,
      phasingStart: 8,
      phasingEnd: 50,
      phasingSpeed: 3,
      phasingStep: 2,
      portamentoStep: 0,
      portamentoSpeed: 0,
      arpeggioSpeed: 6,
      waveCount: 2,
      octave: 4,
      dasrSustainOffset: 0,
      dasrReleaseOffset: 0,
    },
  },
];
