/**
 * Synthesis synth presets — 16 synth effects + ADSR, arpeggio, vibrato, EGC
 *
 * Each preset defines instrument parameters for syn_set_instrument_param().
 * Categories: bass, lead, pad, drum, fx, arpeggio
 *
 * Synth effects (SynSynthEffect):
 *   0=None, 1=Rotate1, 2=Rotate2, 3=Alien, 4=Negator, 5=PolyNeg,
 *   6=Shaker1, 7=Shaker2, 8=AMF_LFO, 9=Laser, 10=OctFX1, 11=OctFX2,
 *   12=Alising, 13=EGFX1, 14=EGFX2, 15=Changer, 16=FmDrum
 *
 * EGC modes (SynEgcMode): 0=off, 1=ones (one-shot), 2=repeat
 * Volume: 0-64. All uint8_t params: 0-255.
 */

export interface SynthesisPreset {
  name: string;
  category: 'bass' | 'lead' | 'pad' | 'drum' | 'fx' | 'arpeggio';
  params: Record<string, number>;
}

export const SYNTHESIS_PRESETS: SynthesisPreset[] = [
  // -- Bass ------------------------------------------------------------------
  {
    name: 'Rotator Sub Bass',
    category: 'bass',
    params: {
      synthesisEnabled: 1,
      waveformNumber: 0,
      waveformLength: 64,
      repeatLength: 64,
      volume: 64,
      portamentoSpeed: 0,
      adsrEnabled: 1,
      adsrTableNumber: 0,
      adsrTableLength: 48,
      arpeggioStart: 0,
      arpeggioLength: 0,
      arpeggioRepeatLength: 0,
      effect: 1, // Rotate1
      vibratoDelay: 0,
      vibratoSpeed: 0,
      vibratoLevel: 0,
      egcOffset: 0,
      egcMode: 0,
      egcTableNumber: 0,
      egcTableLength: 0,
    },
  },
  {
    name: 'Negator Punch Bass',
    category: 'bass',
    params: {
      synthesisEnabled: 1,
      waveformNumber: 0,
      waveformLength: 32,
      repeatLength: 32,
      volume: 62,
      portamentoSpeed: 0,
      adsrEnabled: 1,
      adsrTableNumber: 0,
      adsrTableLength: 24,
      arpeggioStart: 0,
      arpeggioLength: 0,
      arpeggioRepeatLength: 0,
      effect: 4, // Negator
      vibratoDelay: 4,
      vibratoSpeed: 2,
      vibratoLevel: 2,
      egcOffset: 0,
      egcMode: 1,
      egcTableNumber: 0,
      egcTableLength: 16,
    },
  },
  {
    name: 'Shaker Bass',
    category: 'bass',
    params: {
      synthesisEnabled: 1,
      waveformNumber: 0,
      waveformLength: 64,
      repeatLength: 64,
      volume: 60,
      portamentoSpeed: 3,
      adsrEnabled: 1,
      adsrTableNumber: 0,
      adsrTableLength: 40,
      arpeggioStart: 0,
      arpeggioLength: 0,
      arpeggioRepeatLength: 0,
      effect: 6, // Shaker1
      vibratoDelay: 6,
      vibratoSpeed: 3,
      vibratoLevel: 3,
      egcOffset: 0,
      egcMode: 0,
      egcTableNumber: 0,
      egcTableLength: 0,
    },
  },

  // -- Lead ------------------------------------------------------------------
  {
    name: 'Alien Voice Lead',
    category: 'lead',
    params: {
      synthesisEnabled: 1,
      waveformNumber: 0,
      waveformLength: 32,
      repeatLength: 32,
      volume: 56,
      portamentoSpeed: 2,
      adsrEnabled: 1,
      adsrTableNumber: 0,
      adsrTableLength: 32,
      arpeggioStart: 0,
      arpeggioLength: 0,
      arpeggioRepeatLength: 0,
      effect: 3, // Alien
      vibratoDelay: 4,
      vibratoSpeed: 8,
      vibratoLevel: 5,
      egcOffset: 0,
      egcMode: 2,
      egcTableNumber: 0,
      egcTableLength: 24,
    },
  },
  {
    name: 'Laser Lead',
    category: 'lead',
    params: {
      synthesisEnabled: 1,
      waveformNumber: 0,
      waveformLength: 32,
      repeatLength: 32,
      volume: 58,
      portamentoSpeed: 4,
      adsrEnabled: 1,
      adsrTableNumber: 0,
      adsrTableLength: 28,
      arpeggioStart: 0,
      arpeggioLength: 0,
      arpeggioRepeatLength: 0,
      effect: 9, // Laser
      vibratoDelay: 2,
      vibratoSpeed: 10,
      vibratoLevel: 6,
      egcOffset: 0,
      egcMode: 1,
      egcTableNumber: 0,
      egcTableLength: 20,
    },
  },
  {
    name: 'OctFX Screamer',
    category: 'lead',
    params: {
      synthesisEnabled: 1,
      waveformNumber: 0,
      waveformLength: 32,
      repeatLength: 32,
      volume: 54,
      portamentoSpeed: 0,
      adsrEnabled: 1,
      adsrTableNumber: 0,
      adsrTableLength: 36,
      arpeggioStart: 0,
      arpeggioLength: 0,
      arpeggioRepeatLength: 0,
      effect: 10, // OctFX1
      vibratoDelay: 6,
      vibratoSpeed: 6,
      vibratoLevel: 4,
      egcOffset: 0,
      egcMode: 2,
      egcTableNumber: 0,
      egcTableLength: 32,
    },
  },
  {
    name: 'PolyNeg Lead',
    category: 'lead',
    params: {
      synthesisEnabled: 1,
      waveformNumber: 0,
      waveformLength: 32,
      repeatLength: 32,
      volume: 56,
      portamentoSpeed: 1,
      adsrEnabled: 1,
      adsrTableNumber: 0,
      adsrTableLength: 30,
      arpeggioStart: 0,
      arpeggioLength: 0,
      arpeggioRepeatLength: 0,
      effect: 5, // PolyNeg
      vibratoDelay: 4,
      vibratoSpeed: 5,
      vibratoLevel: 3,
      egcOffset: 0,
      egcMode: 1,
      egcTableNumber: 0,
      egcTableLength: 24,
    },
  },

  // -- Pad -------------------------------------------------------------------
  {
    name: 'Rotate Evolving Pad',
    category: 'pad',
    params: {
      synthesisEnabled: 1,
      waveformNumber: 0,
      waveformLength: 128,
      repeatLength: 128,
      volume: 44,
      portamentoSpeed: 0,
      adsrEnabled: 1,
      adsrTableNumber: 0,
      adsrTableLength: 128,
      arpeggioStart: 0,
      arpeggioLength: 0,
      arpeggioRepeatLength: 0,
      effect: 2, // Rotate2
      vibratoDelay: 16,
      vibratoSpeed: 2,
      vibratoLevel: 2,
      egcOffset: 0,
      egcMode: 2,
      egcTableNumber: 0,
      egcTableLength: 64,
    },
  },
  {
    name: 'AMF LFO Pad',
    category: 'pad',
    params: {
      synthesisEnabled: 1,
      waveformNumber: 0,
      waveformLength: 128,
      repeatLength: 128,
      volume: 42,
      portamentoSpeed: 0,
      adsrEnabled: 1,
      adsrTableNumber: 0,
      adsrTableLength: 96,
      arpeggioStart: 0,
      arpeggioLength: 0,
      arpeggioRepeatLength: 0,
      effect: 8, // AMF_LFO
      vibratoDelay: 20,
      vibratoSpeed: 3,
      vibratoLevel: 3,
      egcOffset: 0,
      egcMode: 2,
      egcTableNumber: 0,
      egcTableLength: 48,
    },
  },
  {
    name: 'Changer Texture Pad',
    category: 'pad',
    params: {
      synthesisEnabled: 1,
      waveformNumber: 0,
      waveformLength: 64,
      repeatLength: 64,
      volume: 40,
      portamentoSpeed: 0,
      adsrEnabled: 1,
      adsrTableNumber: 0,
      adsrTableLength: 80,
      arpeggioStart: 0,
      arpeggioLength: 0,
      arpeggioRepeatLength: 0,
      effect: 15, // Changer
      vibratoDelay: 12,
      vibratoSpeed: 4,
      vibratoLevel: 4,
      egcOffset: 0,
      egcMode: 2,
      egcTableNumber: 0,
      egcTableLength: 40,
    },
  },

  // -- Drum ------------------------------------------------------------------
  {
    name: 'FM Kick',
    category: 'drum',
    params: {
      synthesisEnabled: 1,
      waveformNumber: 0,
      waveformLength: 32,
      repeatLength: 0,
      volume: 64,
      portamentoSpeed: 0,
      adsrEnabled: 1,
      adsrTableNumber: 0,
      adsrTableLength: 8,
      arpeggioStart: 0,
      arpeggioLength: 0,
      arpeggioRepeatLength: 0,
      effect: 16, // FmDrum
      vibratoDelay: 0,
      vibratoSpeed: 0,
      vibratoLevel: 0,
      egcOffset: 0,
      egcMode: 0,
      egcTableNumber: 0,
      egcTableLength: 0,
    },
  },
  {
    name: 'Shaker Snare',
    category: 'drum',
    params: {
      synthesisEnabled: 1,
      waveformNumber: 0,
      waveformLength: 16,
      repeatLength: 0,
      volume: 60,
      portamentoSpeed: 0,
      adsrEnabled: 1,
      adsrTableNumber: 0,
      adsrTableLength: 6,
      arpeggioStart: 0,
      arpeggioLength: 0,
      arpeggioRepeatLength: 0,
      effect: 7, // Shaker2
      vibratoDelay: 0,
      vibratoSpeed: 0,
      vibratoLevel: 0,
      egcOffset: 0,
      egcMode: 0,
      egcTableNumber: 0,
      egcTableLength: 0,
    },
  },
  {
    name: 'Alising Hat',
    category: 'drum',
    params: {
      synthesisEnabled: 1,
      waveformNumber: 0,
      waveformLength: 16,
      repeatLength: 0,
      volume: 48,
      portamentoSpeed: 0,
      adsrEnabled: 1,
      adsrTableNumber: 0,
      adsrTableLength: 4,
      arpeggioStart: 0,
      arpeggioLength: 0,
      arpeggioRepeatLength: 0,
      effect: 12, // Alising
      vibratoDelay: 0,
      vibratoSpeed: 0,
      vibratoLevel: 0,
      egcOffset: 0,
      egcMode: 0,
      egcTableNumber: 0,
      egcTableLength: 0,
    },
  },

  // -- FX --------------------------------------------------------------------
  {
    name: 'Laser Zap',
    category: 'fx',
    params: {
      synthesisEnabled: 1,
      waveformNumber: 0,
      waveformLength: 32,
      repeatLength: 0,
      volume: 64,
      portamentoSpeed: 8,
      adsrEnabled: 1,
      adsrTableNumber: 0,
      adsrTableLength: 12,
      arpeggioStart: 0,
      arpeggioLength: 0,
      arpeggioRepeatLength: 0,
      effect: 9, // Laser
      vibratoDelay: 0,
      vibratoSpeed: 0,
      vibratoLevel: 0,
      egcOffset: 0,
      egcMode: 0,
      egcTableNumber: 0,
      egcTableLength: 0,
    },
  },
  {
    name: 'EGFX Sweep',
    category: 'fx',
    params: {
      synthesisEnabled: 1,
      waveformNumber: 0,
      waveformLength: 64,
      repeatLength: 64,
      volume: 52,
      portamentoSpeed: 0,
      adsrEnabled: 1,
      adsrTableNumber: 0,
      adsrTableLength: 48,
      arpeggioStart: 0,
      arpeggioLength: 0,
      arpeggioRepeatLength: 0,
      effect: 13, // EGFX1
      vibratoDelay: 0,
      vibratoSpeed: 12,
      vibratoLevel: 10,
      egcOffset: 0,
      egcMode: 1,
      egcTableNumber: 0,
      egcTableLength: 48,
    },
  },
  {
    name: 'OctFX2 Glitch',
    category: 'fx',
    params: {
      synthesisEnabled: 1,
      waveformNumber: 0,
      waveformLength: 32,
      repeatLength: 32,
      volume: 56,
      portamentoSpeed: 0,
      adsrEnabled: 1,
      adsrTableNumber: 0,
      adsrTableLength: 24,
      arpeggioStart: 0,
      arpeggioLength: 0,
      arpeggioRepeatLength: 0,
      effect: 11, // OctFX2
      vibratoDelay: 0,
      vibratoSpeed: 16,
      vibratoLevel: 8,
      egcOffset: 0,
      egcMode: 0,
      egcTableNumber: 0,
      egcTableLength: 0,
    },
  },

  // -- Arpeggio --------------------------------------------------------------
  {
    name: 'Major Triad Arp',
    category: 'arpeggio',
    params: {
      synthesisEnabled: 1,
      waveformNumber: 0,
      waveformLength: 32,
      repeatLength: 32,
      volume: 56,
      portamentoSpeed: 0,
      adsrEnabled: 1,
      adsrTableNumber: 0,
      adsrTableLength: 40,
      arpeggioStart: 0,
      arpeggioLength: 3,
      arpeggioRepeatLength: 3,
      effect: 0, // None
      vibratoDelay: 8,
      vibratoSpeed: 2,
      vibratoLevel: 1,
      egcOffset: 0,
      egcMode: 0,
      egcTableNumber: 0,
      egcTableLength: 0,
    },
  },
  {
    name: 'Rotate Arp',
    category: 'arpeggio',
    params: {
      synthesisEnabled: 1,
      waveformNumber: 0,
      waveformLength: 32,
      repeatLength: 32,
      volume: 52,
      portamentoSpeed: 0,
      adsrEnabled: 1,
      adsrTableNumber: 0,
      adsrTableLength: 36,
      arpeggioStart: 0,
      arpeggioLength: 4,
      arpeggioRepeatLength: 4,
      effect: 1, // Rotate1
      vibratoDelay: 0,
      vibratoSpeed: 0,
      vibratoLevel: 0,
      egcOffset: 0,
      egcMode: 2,
      egcTableNumber: 0,
      egcTableLength: 24,
    },
  },
  {
    name: 'EGFX2 Shimmer Arp',
    category: 'arpeggio',
    params: {
      synthesisEnabled: 1,
      waveformNumber: 0,
      waveformLength: 32,
      repeatLength: 32,
      volume: 50,
      portamentoSpeed: 0,
      adsrEnabled: 1,
      adsrTableNumber: 0,
      adsrTableLength: 44,
      arpeggioStart: 0,
      arpeggioLength: 3,
      arpeggioRepeatLength: 3,
      effect: 14, // EGFX2
      vibratoDelay: 4,
      vibratoSpeed: 3,
      vibratoLevel: 2,
      egcOffset: 0,
      egcMode: 1,
      egcTableNumber: 0,
      egcTableLength: 32,
    },
  },
];
