/**
 * Buzzmachine effect descriptors — GENERATED by scripts/gen-buzzmachine-effects.cjs from
 * BUZZMACHINE_INFO (effect-type machines). Reuses the proven BuzzmachineSynth audio path
 * (input -> WASM worklet -> output); create() seeds the indexed params and live updates
 * dispatch through BuzzmachineSynth.setParam. Do not hand-edit — regenerate.
 */
import { EffectRegistry } from '../EffectRegistry';
import type { EffectDescriptor } from '../EffectDescriptor';
import type { EffectConfig } from '@typedefs/instrument';
import { BuzzmachineType } from '@engine/buzzmachines/BuzzmachineEngine';
import { BuzzmachineSynth } from '@engine/buzzmachines/BuzzmachineSynth';

async function makeBuzz(type: string, config: EffectConfig): Promise<BuzzmachineSynth> {
  const s = new BuzzmachineSynth(type as never);
  await s.ensureInitialized();
  for (const [k, v] of Object.entries(config.parameters || {})) {
    const idx = Number(k);
    if (Number.isInteger(idx)) s.setParameter(idx, Number(v));
  }
  return s;
}

const BUZZ_EFFECTS: EffectDescriptor[] = [
  {
    id: 'ArguruDistortion', name: "Arguru Distortion", category: 'wasm', group: 'Distortion',
    loadMode: 'lazy',
    create: (c: EffectConfig) => makeBuzz(BuzzmachineType.ARGURU_DISTORTION, c),
    getDefaultParameters: () => ({ '0': 256, '1': 512, '2': 512, '3': 1024, '4': 0, '5': 0 }),
    parameters: [
      { key: '0', label: "Input Gain", type: 'knob', min: 1, max: 2048, default: 256 },
      { key: '1', label: "Threshold (-)", type: 'knob', min: 1, max: 32768, default: 512 },
      { key: '2', label: "Threshold (+)", type: 'knob', min: 1, max: 32768, default: 512 },
      { key: '3', label: "Output Gain", type: 'knob', min: 1, max: 2048, default: 1024 },
      { key: '4', label: "Phase Inversor", type: 'toggle', min: 0, max: 1, default: 0 },
      { key: '5', label: "Mode", type: 'toggle', min: 0, max: 1, default: 0 },
    ],
    presets: [
      { name: 'Gentle', params: { '0': 308 } },
      { name: 'Medium', params: { '0': 1025 } },
      { name: 'Strong', params: { '0': 1741 } },
    ],
  },
  {
    id: 'ElakSVF', name: "Elak SVF Filter", category: 'wasm', group: 'Filter',
    loadMode: 'lazy',
    create: (c: EffectConfig) => makeBuzz(BuzzmachineType.ELAK_SVF, c),
    getDefaultParameters: () => ({ '0': 512, '1': 512 }),
    parameters: [
      { key: '0', label: "Cutoff", type: 'knob', min: 0, max: 1000, default: 512 },
      { key: '1', label: "Resonance", type: 'knob', min: 0, max: 65534, default: 512 },
    ],
    presets: [
      { name: 'Gentle', params: { '0': 150 } },
      { name: 'Medium', params: { '0': 500 } },
      { name: 'Strong', params: { '0': 850 } },
    ],
  },
  {
    id: 'ElakDist2', name: "Elak Dist2", category: 'wasm', group: 'Distortion',
    loadMode: 'lazy',
    create: (c: EffectConfig) => makeBuzz(BuzzmachineType.ELAK_DIST2, c),
    getDefaultParameters: () => ({ '0': 1, '1': 1, '2': 1 }),
    parameters: [
      { key: '0', label: "ScatterInt", type: 'knob', min: 0, max: 254, default: 1 },
      { key: '1', label: "ScatterAmount", type: 'knob', min: 1, max: 65534, default: 1 },
      { key: '2', label: "KindOf", type: 'knob', min: 1, max: 3, default: 1 },
    ],
    presets: [
      { name: 'Gentle', params: { '0': 38 } },
      { name: 'Medium', params: { '0': 127 } },
      { name: 'Strong', params: { '0': 216 } },
    ],
  },
  {
    id: 'JeskolaDistortion', name: "Jeskola Distortion", category: 'wasm', group: 'Distortion',
    loadMode: 'lazy',
    create: (c: EffectConfig) => makeBuzz(BuzzmachineType.JESKOLA_DISTORTION, c),
    getDefaultParameters: () => ({ '0': 512, '1': 4096, '2': 512, '3': 4096, '4': 127 }),
    parameters: [
      { key: '0', label: "+Threshold", type: 'knob', min: 0, max: 65534, default: 512 },
      { key: '1', label: "+Clamp", type: 'knob', min: 0, max: 65534, default: 4096 },
      { key: '2', label: "-Threshold", type: 'knob', min: 0, max: 65534, default: 512 },
      { key: '3', label: "-Clamp", type: 'knob', min: 0, max: 65534, default: 4096 },
      { key: '4', label: "Amount", type: 'knob', min: 0, max: 127, default: 127 },
    ],
    presets: [
      { name: 'Gentle', params: { '0': 9830 } },
      { name: 'Medium', params: { '0': 32767 } },
      { name: 'Strong', params: { '0': 55704 } },
    ],
  },
  {
    id: 'GeonikOverdrive', name: "Geonik Overdrive", category: 'wasm', group: 'Distortion',
    loadMode: 'lazy',
    create: (c: EffectConfig) => makeBuzz(BuzzmachineType.GEONIK_OVERDRIVE, c),
    getDefaultParameters: () => ({ '0': 81, '1': 44, '2': 108, '3': 95 }),
    parameters: [
      { key: '0', label: "Drive", type: 'knob', min: 48, max: 96, default: 81 },
      { key: '1', label: "Asymmetry", type: 'knob', min: 0, max: 128, default: 44 },
      { key: '2', label: "CutOff", type: 'knob', min: 0, max: 128, default: 108 },
      { key: '3', label: "Emphasis", type: 'knob', min: 0, max: 128, default: 95 },
    ],
    presets: [
      { name: 'Gentle', params: { '0': 55 } },
      { name: 'Medium', params: { '0': 72 } },
      { name: 'Strong', params: { '0': 89 } },
    ],
  },
  {
    id: 'GraueSoftSat', name: "Graue SoftSat", category: 'wasm', group: 'Distortion',
    loadMode: 'lazy',
    create: (c: EffectConfig) => makeBuzz(BuzzmachineType.GRAUE_SOFTSAT, c),
    getDefaultParameters: () => ({ '0': 32768, '1': 1024 }),
    parameters: [
      { key: '0', label: "Threshold", type: 'knob', min: 16, max: 32768, default: 32768 },
      { key: '1', label: "Hardness", type: 'knob', min: 1, max: 2048, default: 1024 },
    ],
    presets: [
      { name: 'Gentle', params: { '0': 4929 } },
      { name: 'Medium', params: { '0': 16392 } },
      { name: 'Strong', params: { '0': 27855 } },
    ],
  },
  {
    id: 'WhiteNoiseStereoDist', name: "WhiteNoise StereoDist", category: 'wasm', group: 'Distortion',
    loadMode: 'lazy',
    create: (c: EffectConfig) => makeBuzz(BuzzmachineType.WHITENOISE_STEREODIST, c),
    getDefaultParameters: () => ({ '0': 32, '1': 254, '2': 254, '3': 0, '4': 0, '5': 1000, '6': 0, '7': 48, '8': 48 }),
    parameters: [
      { key: '0', label: "Drive", type: 'knob', min: 0, max: 96, default: 32 },
      { key: '1', label: "Top", type: 'knob', min: 0, max: 248, default: 254 },
      { key: '2', label: "Bottom", type: 'knob', min: 0, max: 248, default: 254 },
      { key: '3', label: "Top Mode", type: 'knob', min: 0, max: 5, default: 0 },
      { key: '4', label: "Bottom Mode", type: 'knob', min: 0, max: 5, default: 0 },
      { key: '5', label: "Lowpass", type: 'knob', min: 0, max: 1000, default: 1000 },
      { key: '6', label: "Hipass", type: 'knob', min: 0, max: 1000, default: 0 },
      { key: '7', label: "Dry", type: 'knob', min: 0, max: 96, default: 48 },
      { key: '8', label: "Wet", type: 'knob', min: 0, max: 96, default: 48 },
    ],
    presets: [
      { name: 'Gentle', params: { '0': 14 } },
      { name: 'Medium', params: { '0': 48 } },
      { name: 'Strong', params: { '0': 82 } },
    ],
  },
  {
    id: 'CyanPhaseNotch', name: "CyanPhase Notch", category: 'wasm', group: 'Filter',
    loadMode: 'lazy',
    create: (c: EffectConfig) => makeBuzz(BuzzmachineType.CYANPHASE_NOTCH, c),
    getDefaultParameters: () => ({ '0': 2000, '1': 100, '2': 2000, '3': 2000, '4': 100, '5': 2000, '6': 2000, '7': 2000, '8': 2000, '9': 100, '10': 100 }),
    parameters: [
      { key: '0', label: "Fixed1 Freq", type: 'knob', min: 5, max: 21500, default: 2000 },
      { key: '1', label: "Fixed1 BW", type: 'knob', min: 2, max: 2500, default: 100 },
      { key: '2', label: "Fixed1 Inertia", type: 'knob', min: 1, max: 65534, default: 2000 },
      { key: '3', label: "Fixed2 Freq", type: 'knob', min: 5, max: 21500, default: 2000 },
      { key: '4', label: "Fixed2 BW", type: 'knob', min: 2, max: 2500, default: 100 },
      { key: '5', label: "Fixed2 Inertia", type: 'knob', min: 1, max: 65534, default: 2000 },
      { key: '6', label: "LFO Freq1", type: 'knob', min: 5, max: 21500, default: 2000 },
      { key: '7', label: "LFO Freq2", type: 'knob', min: 5, max: 21500, default: 2000 },
      { key: '8', label: "LFO Rate", type: 'knob', min: 1, max: 65534, default: 2000 },
      { key: '9', label: "LFO BW1", type: 'knob', min: 2, max: 2500, default: 100 },
      { key: '10', label: "LFO BW2", type: 'knob', min: 2, max: 2500, default: 100 },
    ],
    presets: [
      { name: 'Gentle', params: { '0': 3229 } },
      { name: 'Medium', params: { '0': 10753 } },
      { name: 'Strong', params: { '0': 18276 } },
    ],
  },
  {
    id: 'QZfilter', name: "Q Zfilter", category: 'wasm', group: 'Filter',
    loadMode: 'lazy',
    create: (c: EffectConfig) => makeBuzz(BuzzmachineType.Q_ZFILTER, c),
    getDefaultParameters: () => ({ '0': 49152, '1': 65534, '2': 32767, '3': 32767, '4': 16384 }),
    parameters: [
      { key: '0', label: "b0", type: 'knob', min: 0, max: 65534, default: 49152 },
      { key: '1', label: "a1", type: 'knob', min: 0, max: 65534, default: 65534 },
      { key: '2', label: "b1", type: 'knob', min: 0, max: 65534, default: 32767 },
      { key: '3', label: "a2", type: 'knob', min: 0, max: 65534, default: 32767 },
      { key: '4', label: "b2", type: 'knob', min: 0, max: 65534, default: 16384 },
    ],
    presets: [
      { name: 'Gentle', params: { '0': 9830 } },
      { name: 'Medium', params: { '0': 32767 } },
      { name: 'Strong', params: { '0': 55704 } },
    ],
  },
  {
    id: 'FSMPhilta', name: "FSM Philta", category: 'wasm', group: 'Filter',
    loadMode: 'lazy',
    create: (c: EffectConfig) => makeBuzz(BuzzmachineType.FSM_PHILTA, c),
    getDefaultParameters: () => ({ '0': 120, '1': 120, '2': 6, '3': 30, '4': 60, '5': 0, '6': 10 }),
    parameters: [
      { key: '0', label: "Cutoff", type: 'knob', min: 0, max: 240, default: 120 },
      { key: '1', label: "Resonance", type: 'knob', min: 0, max: 240, default: 120 },
      { key: '2', label: "Filter", type: 'knob', min: 0, max: 7, default: 6 },
      { key: '3', label: "LFO Rate", type: 'knob', min: 0, max: 254, default: 30 },
      { key: '4', label: "LFO Mod", type: 'knob', min: 0, max: 240, default: 60 },
      { key: '5', label: "LFO Shape", type: 'knob', min: 0, max: 16, default: 0 },
      { key: '6', label: "Inertia", type: 'knob', min: 0, max: 60, default: 10 },
    ],
    presets: [
      { name: 'Gentle', params: { '0': 36 } },
      { name: 'Medium', params: { '0': 120 } },
      { name: 'Strong', params: { '0': 204 } },
    ],
  },
  {
    id: 'JeskolaDelay', name: "Jeskola Delay", category: 'wasm', group: 'Reverb & Delay',
    loadMode: 'lazy',
    create: (c: EffectConfig) => makeBuzz(BuzzmachineType.JESKOLA_DELAY, c),
    getDefaultParameters: () => ({ '0': 3, '1': 0, '2': 96, '3': 48 }),
    parameters: [
      { key: '0', label: "Length", type: 'knob', min: 1, max: 32768, default: 3 },
      { key: '1', label: "Length Unit", type: 'knob', min: 0, max: 3, default: 0 },
      { key: '2', label: "Feedback", type: 'knob', min: 0, max: 128, default: 96 },
      { key: '3', label: "Wet Out", type: 'knob', min: 0, max: 128, default: 48 },
    ],
    presets: [
      { name: 'Gentle', params: { '0': 4916 } },
      { name: 'Medium', params: { '0': 16385 } },
      { name: 'Strong', params: { '0': 27853 } },
    ],
  },
  {
    id: 'JeskolaCrossDelay', name: "Jeskola CrossDelay", category: 'wasm', group: 'Reverb & Delay',
    loadMode: 'lazy',
    create: (c: EffectConfig) => makeBuzz(BuzzmachineType.JESKOLA_CROSSDELAY, c),
    getDefaultParameters: () => ({ '0': 3, '1': 3, '2': 0, '3': 96, '4': 48 }),
    parameters: [
      { key: '0', label: "L Length", type: 'knob', min: 1, max: 32768, default: 3 },
      { key: '1', label: "R Length", type: 'knob', min: 1, max: 32768, default: 3 },
      { key: '2', label: "Length Unit", type: 'knob', min: 0, max: 3, default: 0 },
      { key: '3', label: "Feedback", type: 'knob', min: 0, max: 128, default: 96 },
      { key: '4', label: "Wet Out", type: 'knob', min: 0, max: 128, default: 48 },
    ],
    presets: [
      { name: 'Gentle', params: { '0': 4916 } },
      { name: 'Medium', params: { '0': 16385 } },
      { name: 'Strong', params: { '0': 27853 } },
    ],
  },
  {
    id: 'JeskolaFreeverb', name: "Jeskola Freeverb", category: 'wasm', group: 'Reverb & Delay',
    loadMode: 'lazy',
    create: (c: EffectConfig) => makeBuzz(BuzzmachineType.JESKOLA_FREEVERB, c),
    getDefaultParameters: () => ({ '0': 40, '1': 50, '2': 0, '3': 0, '4': 127, '5': 80, '6': 127 }),
    parameters: [
      { key: '0', label: "RevTime", type: 'knob', min: 0, max: 127, default: 40 },
      { key: '1', label: "HiDamp", type: 'knob', min: 0, max: 127, default: 50 },
      { key: '2', label: "PreDelay", type: 'knob', min: 0, max: 127, default: 0 },
      { key: '3', label: "LowCut", type: 'knob', min: 0, max: 127, default: 0 },
      { key: '4', label: "HiCut", type: 'knob', min: 0, max: 127, default: 127 },
      { key: '5', label: "RevOut", type: 'knob', min: 0, max: 127, default: 80 },
      { key: '6', label: "DryOut", type: 'knob', min: 0, max: 127, default: 127 },
    ],
    presets: [
      { name: 'Gentle', params: { '0': 19 } },
      { name: 'Medium', params: { '0': 64 } },
      { name: 'Strong', params: { '0': 108 } },
    ],
  },
  {
    id: 'FSMPanzerDelay', name: "FSM PanzerDelay", category: 'wasm', group: 'Reverb & Delay',
    loadMode: 'lazy',
    create: (c: EffectConfig) => makeBuzz(BuzzmachineType.FSM_PANZERDELAY, c),
    getDefaultParameters: () => ({ '0': 240, '1': 0, '2': 120, '3': 120, '4': 3, '5': 3, '6': 240, '7': 150, '8': 0 }),
    parameters: [
      { key: '0', label: "Dry Amp", type: 'knob', min: 0, max: 240, default: 240 },
      { key: '1', label: "Filter Type", type: 'knob', min: 0, max: 3, default: 0 },
      { key: '2', label: "Cutoff", type: 'knob', min: 0, max: 240, default: 120 },
      { key: '3', label: "Resonance", type: 'knob', min: 0, max: 240, default: 120 },
      { key: '4', label: "L Delay Len", type: 'knob', min: 1, max: 20000, default: 3 },
      { key: '5', label: "R Delay Len", type: 'knob', min: 1, max: 20000, default: 3 },
      { key: '6', label: "Tap Amp", type: 'knob', min: 0, max: 240, default: 240 },
      { key: '7', label: "FB Amp", type: 'knob', min: 0, max: 239, default: 150 },
      { key: '8', label: "FB PingPong", type: 'toggle', min: 0, max: 1, default: 0 },
    ],
    presets: [
      { name: 'Gentle', params: { '0': 36 } },
      { name: 'Medium', params: { '0': 120 } },
      { name: 'Strong', params: { '0': 204 } },
    ],
  },
  {
    id: 'FSMChorus', name: "FSM Chorus", category: 'wasm', group: 'Modulation',
    loadMode: 'lazy',
    create: (c: EffectConfig) => makeBuzz(BuzzmachineType.FSM_CHORUS, c),
    getDefaultParameters: () => ({ '0': 240, '1': 20, '2': 30, '3': 150, '4': 240, '5': 64 }),
    parameters: [
      { key: '0', label: "Dry Out", type: 'knob', min: 0, max: 240, default: 240 },
      { key: '1', label: "Min Delay", type: 'knob', min: 1, max: 100, default: 20 },
      { key: '2', label: "Modulation", type: 'knob', min: 1, max: 100, default: 30 },
      { key: '3', label: "LFO Rate", type: 'knob', min: 0, max: 240, default: 150 },
      { key: '4', label: "Wet Out", type: 'knob', min: 0, max: 240, default: 240 },
      { key: '5', label: "Feedback", type: 'knob', min: 0, max: 128, default: 64 },
    ],
    presets: [
      { name: 'Gentle', params: { '0': 36 } },
      { name: 'Medium', params: { '0': 120 } },
      { name: 'Strong', params: { '0': 204 } },
    ],
  },
  {
    id: 'FSMChorus2', name: "FSM Chorus2", category: 'wasm', group: 'Modulation',
    loadMode: 'lazy',
    create: (c: EffectConfig) => makeBuzz(BuzzmachineType.FSM_CHORUS2, c),
    getDefaultParameters: () => ({ '0': 80, '1': 90, '2': 60, '3': 3, '4': 120 }),
    parameters: [
      { key: '0', label: "Min Delay", type: 'knob', min: 0, max: 240, default: 80 },
      { key: '1', label: "Mod Depth", type: 'knob', min: 0, max: 240, default: 90 },
      { key: '2', label: "Mod Rate", type: 'knob', min: 0, max: 240, default: 60 },
      { key: '3', label: "Fatness", type: 'knob', min: 1, max: 6, default: 3 },
      { key: '4', label: "Stereo", type: 'knob', min: 0, max: 240, default: 120 },
    ],
    presets: [
      { name: 'Gentle', params: { '0': 36 } },
      { name: 'Medium', params: { '0': 120 } },
      { name: 'Strong', params: { '0': 204 } },
    ],
  },
  {
    id: 'WhiteNoiseWhiteChorus', name: "WhiteNoise WhiteChorus", category: 'wasm', group: 'Reverb & Delay',
    loadMode: 'lazy',
    create: (c: EffectConfig) => makeBuzz(BuzzmachineType.WHITENOISE_WHITECHORUS, c),
    getDefaultParameters: () => ({ '0': 1, '1': 0, '2': 1, '3': 5, '4': 10, '5': 3, '6': 6, '7': 0, '8': 150, '9': 64 }),
    parameters: [
      { key: '0', label: "Voices", type: 'knob', min: 1, max: 3, default: 1 },
      { key: '1', label: "LFO Shape", type: 'toggle', min: 0, max: 1, default: 0 },
      { key: '2', label: "Min Delay", type: 'knob', min: 0, max: 200, default: 1 },
      { key: '3', label: "Delay Mod", type: 'knob', min: 0, max: 200, default: 5 },
      { key: '4', label: "Rate", type: 'knob', min: 0, max: 127, default: 10 },
      { key: '5', label: "Phase Diff", type: 'knob', min: 1, max: 23, default: 3 },
      { key: '6', label: "Stereo Phase", type: 'knob', min: 0, max: 23, default: 6 },
      { key: '7', label: "Delay Spread", type: 'knob', min: 0, max: 10, default: 0 },
      { key: '8', label: "Feedback", type: 'knob', min: 1, max: 199, default: 150 },
      { key: '9', label: "Mix", type: 'knob', min: 0, max: 127, default: 64 },
    ],
    presets: [
      { name: 'Gentle', params: { '0': 1 } },
      { name: 'Medium', params: { '0': 2 } },
      { name: 'Strong', params: { '0': 3 } },
    ],
  },
  {
    id: 'BigyoFrequencyShifter', name: "Bigyo FrequencyShifter", category: 'wasm', group: 'Pitch',
    loadMode: 'lazy',
    create: (c: EffectConfig) => makeBuzz(BuzzmachineType.BIGYO_FREQUENCYSHIFTER, c),
    getDefaultParameters: () => ({ '0': 0, '1': 0, '2': 0 }),
    parameters: [
      { key: '0', label: "Frequency", type: 'knob', min: 0, max: 65534, default: 0 },
      { key: '1', label: "Left Direction", type: 'knob', min: 0, max: 2, default: 0 },
      { key: '2', label: "Right Direction", type: 'knob', min: 0, max: 2, default: 0 },
    ],
    presets: [
      { name: 'Gentle', params: { '0': 9830 } },
      { name: 'Medium', params: { '0': 32767 } },
      { name: 'Strong', params: { '0': 55704 } },
    ],
  },
  {
    id: 'GeonikCompressor', name: "Geonik Compressor", category: 'wasm', group: 'Dynamics',
    loadMode: 'lazy',
    create: (c: EffectConfig) => makeBuzz(BuzzmachineType.GEONIK_COMPRESSOR, c),
    getDefaultParameters: () => ({ '0': 92, '1': 20, '2': 10, '3': 2000, '4': 6 }),
    parameters: [
      { key: '0', label: "Threshold", type: 'knob', min: 0, max: 128, default: 92 },
      { key: '1', label: "Ratio", type: 'knob', min: 0, max: 240, default: 20 },
      { key: '2', label: "Attack", type: 'knob', min: 5, max: 8000, default: 10 },
      { key: '3', label: "Release", type: 'knob', min: 30, max: 8000, default: 2000 },
      { key: '4', label: "Gain", type: 'knob', min: 0, max: 128, default: 6 },
    ],
    presets: [
      { name: 'Gentle', params: { '0': 19 } },
      { name: 'Medium', params: { '0': 64 } },
      { name: 'Strong', params: { '0': 109 } },
    ],
  },
  {
    id: 'LdSLimit', name: "Ld SLimit", category: 'wasm', group: 'Dynamics',
    loadMode: 'lazy',
    create: (c: EffectConfig) => makeBuzz(BuzzmachineType.LD_SLIMIT, c),
    getDefaultParameters: () => ({ '0': 128, '1': 128, '2': 128, '3': 32 }),
    parameters: [
      { key: '0', label: "Input Gain", type: 'knob', min: 0, max: 128, default: 128 },
      { key: '1', label: "Threshold", type: 'knob', min: 0, max: 128, default: 128 },
      { key: '2', label: "Output", type: 'knob', min: 0, max: 128, default: 128 },
      { key: '3', label: "Release", type: 'knob', min: 0, max: 128, default: 32 },
    ],
    presets: [
      { name: 'Gentle', params: { '0': 19 } },
      { name: 'Medium', params: { '0': 64 } },
      { name: 'Strong', params: { '0': 109 } },
    ],
  },
  {
    id: 'OomekExciter', name: "Oomek Exciter", category: 'wasm', group: 'Distortion',
    loadMode: 'lazy',
    create: (c: EffectConfig) => makeBuzz(BuzzmachineType.OOMEK_EXCITER, c),
    getDefaultParameters: () => ({ '0': 60, '1': 128, '2': 60, '3': 60 }),
    parameters: [
      { key: '0', label: "Drive", type: 'knob', min: 1, max: 240, default: 60 },
      { key: '1', label: "Pre Cut", type: 'knob', min: 1, max: 239, default: 128 },
      { key: '2', label: "Post Cut", type: 'knob', min: 1, max: 239, default: 60 },
      { key: '3', label: "Amount", type: 'knob', min: 0, max: 240, default: 60 },
    ],
    presets: [
      { name: 'Gentle', params: { '0': 37 } },
      { name: 'Medium', params: { '0': 121 } },
      { name: 'Strong', params: { '0': 204 } },
    ],
  },
  {
    id: 'DedaCodeStereoGain', name: "DedaCode StereoGain", category: 'wasm', group: 'Dynamics',
    loadMode: 'lazy',
    create: (c: EffectConfig) => makeBuzz(BuzzmachineType.DEDACODE_STEREOGAIN, c),
    getDefaultParameters: () => ({ '0': 100, '1': 100, '2': 100 }),
    parameters: [
      { key: '0', label: "Volume", type: 'knob', min: 0, max: 600, default: 100 },
      { key: '1', label: "Right", type: 'knob', min: 0, max: 100, default: 100 },
      { key: '2', label: "Left", type: 'knob', min: 0, max: 100, default: 100 },
    ],
    presets: [
      { name: 'Gentle', params: { '0': 90 } },
      { name: 'Medium', params: { '0': 300 } },
      { name: 'Strong', params: { '0': 510 } },
    ],
  },
];

EffectRegistry.register(BUZZ_EFFECTS);

export const BUZZ_EFFECT_IDS = BUZZ_EFFECTS.map((e) => e.id);
