import { readFileSync } from 'fs';
import { join } from 'path';
import { parseSunTronicV13Score } from '../../src/lib/import/formats/SunTronicV13';
import { CORPUS_DIR } from './suntronicLib';
const name=process.argv[2] ?? 'gliders.src';
const data=new Uint8Array(readFileSync(join(CORPUS_DIR,name)));
const s=parseSunTronicV13Score(data);
console.log('deltaA',s.deltaA.toString(16),'deltaB',s.deltaB.toString(16));
const a6base_h1 = 0x318 + s.deltaA;
const runtimeH1Base = 0x264dc - a6base_h1;
const drin_h1 = 0x2828b - runtimeH1Base;
const periods_h1 = a6base_h1 + 0x11ae;
console.log('a6base_h1',a6base_h1.toString(16),'runtimeH1Base',runtimeH1Base.toString(16),'drin_h1',drin_h1.toString(16),'periods_h1',periods_h1.toString(16));
const h1=s.h1;
const drin=[]; for(let i=0;i<32;i++) drin.push((h1[drin_h1+i]<<24>>24));
console.log('drin h1:', drin.join(','));
const per=[]; for(let i=0;i<24;i++) per.push('0x'+((h1[periods_h1+i*2]<<8|h1[periods_h1+i*2+1])).toString(16));
console.log('PERIODS h1:', per.join(','));
console.log('subsongs', s.subsongs.length, 'entries[0]', s.subsongs[0].entries.length, 'synthInstr', s.synthInstruments.length, 'sampledInstr', s.sampledInstruments.length);
console.log('seq0 entry0', JSON.stringify(s.subsongs[0].entries[0]));
console.log('synthTableOff', s.synthTableOff.toString(16), 'sampledTableOff', s.sampledTableOff.toString(16), 'runtime typeA', (s.synthTableOff+runtimeH1Base).toString(16), 'typeB', (s.sampledTableOff+runtimeH1Base).toString(16));
