import { readFileSync } from 'fs';
import { isSunTronicV13Format } from '../../src/lib/import/formats/SunTronicV13';
import { parseSunTronicFile } from '../../src/lib/import/formats/SunTronicParser';
const p1='/Users/spot/Code/DEViLBOX/public/data/songs/SUNTronicTunes/ready';
const buf = new Uint8Array(readFileSync(p1));
console.log('isV13:', isSunTronicV13Format(buf));
const ab = readFileSync(p1);
const buffer = ab.buffer.slice(ab.byteOffset, ab.byteOffset+ab.byteLength);
const song:any = parseSunTronicFile(buffer as ArrayBuffer, 'ready');
console.log('parsed sourceFormat/patterns:', song.patterns.length, 'name:', song.name);
console.log('has uadeVariableLayout:', !!song.uadeVariableLayout, 'engine hint:', song.metadata?.playbackEngine ?? song.playbackEngine ?? '?');
