/**
 * templateDerive.ts — single source of truth for the committed SunTronic V1.3
 * export template (`src/generated/sunTronicV13Template.ts`).
 *
 * `deriveSunTronicV13Template(muleBytes)` decomposes the reference module
 * (mule.src) into the "reference-player wrap" the compiler emits around new /
 * edited score data. `renderTemplateSource(t)` renders the committed .ts.
 *
 * Both the extract CLI (extract-template.ts) and the golden test
 * (src/generated/__tests__/sunTronicV13Template.test.ts) call `derive` so the
 * committed artifact can never drift from mule.src.
 *
 * DEVIATION FROM PLAN 4.1 (documented): the plan sketched a template that stored
 * only the invariant hunk#1 *code region* (`replayerCode`) + workspace zeros,
 * implying a from-scratch re-assembly of the instrument tables / envelopes /
 * waveforms. This bakes the WHOLE reference module instead. Reusing the complete,
 * load-validated reference hunk#1 as the wrap skeleton is strictly more
 * byte-faithful (deltaA = deltaB = 0, RELOC32 preserved verbatim) and avoids
 * synthesizing synth-descriptor / PCM-table bytes the pilot has no oracle for.
 * It matches the src/generated precedent (cinterPresets/sonixPresets bake ripped
 * binary reference data). Full independent score-topology synthesis is Phase 5+.
 */
import { parseSunTronicV13Score } from '../../src/lib/import/formats/SunTronicV13';

export interface SunTronicV13TemplateLayout {
  /** end of the instrument-name string block at hunk#1+0 (name-block pad target) */
  nameBlockEnd: number;
  /** name-block shift of the reference (0 for mule — it IS the reference) */
  deltaA: number;
  /** table/score shift of the reference (0 for mule) */
  deltaB: number;
  /** hunk#1-relative subsong table offset */
  subsongTableOff: number;
  /** hunk#1-relative workspace base (a6) */
  a6BaseOff: number;
  /** hunk#1-relative synth instrument table offset */
  synthTableOff: number;
  /** hunk#1-relative sampled instrument table offset */
  sampledTableOff: number;
  /** number of unique track-stream blocks in the reference score */
  blockCount: number;
  /** hunk#1-relative start of the first track-stream block (track region start) */
  trackRegionStart: number;
}

export interface SunTronicV13Template {
  /** base64 of the full reference module (mule.src) — the wrap skeleton */
  module: string;
  /** reference instrument (external sample file) names, in slot order */
  instrumentNames: string[];
  layout: SunTronicV13TemplateLayout;
}

function toBase64(bytes: Uint8Array): string {
  // Node + browser-safe base64 (chunked to avoid call-stack limits).
  let bin = '';
  const CHUNK = 0x8000;
  for (let i = 0; i < bytes.length; i += CHUNK) {
    bin += String.fromCharCode(...bytes.subarray(i, i + CHUNK));
  }
  // eslint-disable-next-line no-undef
  return typeof Buffer !== 'undefined' ? Buffer.from(bytes).toString('base64') : btoa(bin);
}

export function deriveSunTronicV13Template(muleBytes: Uint8Array): SunTronicV13Template {
  const score = parseSunTronicV13Score(muleBytes);
  const trackRegionStart = score.blocks.length > 0
    ? Math.min(...score.blocks.map((b) => b.h1Offset))
    : score.h1.length;
  return {
    module: toBase64(muleBytes),
    instrumentNames: score.instrumentNames,
    layout: {
      nameBlockEnd: score.nameBlockEnd,
      deltaA: score.deltaA,
      deltaB: score.deltaB,
      subsongTableOff: 0xd9e + score.deltaB,
      a6BaseOff: 0x318 + score.deltaA,
      synthTableOff: score.synthTableOff,
      sampledTableOff: score.sampledTableOff,
      blockCount: score.blocks.length,
      trackRegionStart,
    },
  };
}

/** Deep structural equality for two derived templates (used by the golden test). */
export function templatesEqual(a: SunTronicV13Template, b: SunTronicV13Template): boolean {
  return JSON.stringify(a) === JSON.stringify(b);
}

export function renderTemplateSource(t: SunTronicV13Template): string {
  return `/**
 * sunTronicV13Template — AUTO-GENERATED by tools/suntronic-re/extract-template.ts. DO NOT EDIT.
 *
 * The SunTronic V1.3 "reference-player wrap": the full reference module (mule.src)
 * decoded to the offsets the native exporter needs to patch new / edited score data
 * into a byte-faithful, load-validated hunk executable.
 *
 * Regenerate: npx tsx tools/suntronic-re/extract-template.ts
 * Guarded by src/generated/__tests__/sunTronicV13Template.test.ts (re-derives from
 * mule.src at test time and asserts equality — the artifact cannot drift).
 */
export interface SunTronicV13Template {
  /** base64 of the full reference module (mule.src) — the wrap skeleton */
  module: string;
  /** reference instrument (external sample file) names, in slot order */
  instrumentNames: string[];
  layout: {
    nameBlockEnd: number;
    deltaA: number;
    deltaB: number;
    subsongTableOff: number;
    a6BaseOff: number;
    synthTableOff: number;
    sampledTableOff: number;
    blockCount: number;
    trackRegionStart: number;
  };
}

export const SUNTRONIC_V13_TEMPLATE: SunTronicV13Template = ${JSON.stringify(t, null, 2)} as const;
`;
}
