import type { SynthInfo } from './types';

export const amigaSynthEntries: Record<string, SynthInfo> = {
  HivelySynth: {
    type: 'HivelySynth',
    name: 'HivelyTracker',
    shortName: 'HVL',
    description: 'Amiga HivelyTracker/AHX chip synth with 4 waveforms, filter sweeps, and performance lists',
    bestFor: ['Chiptune', 'Amiga', 'AHX', 'Chip arpeggios', 'Filter sweeps'],
    icon: 'Cpu',
    color: 'text-green-400',
  },
  UADESynth: {
    type: 'UADESynth',
    name: 'UADE',
    shortName: 'UADE',
    description: 'Playback-only engine for 130+ exotic Amiga tracker formats via UADE',
    bestFor: ['Amiga modules', 'Exotic formats', 'Playback'],
    icon: 'Disc',
    color: 'text-gray-500',
  },
  SoundMonSynth: {
    type: 'SoundMonSynth',
    name: 'SoundMon',
    shortName: 'SoundMon',
    description: 'SoundMon II / Brian Postma wavetable synthesizer',
    bestFor: ['Amiga chiptune', 'Wavetable'],
    icon: 'Disc',
    color: 'text-gray-500',
  },
  SidMonSynth: {
    type: 'SidMonSynth',
    name: 'SidMon',
    shortName: 'SidMon',
    description: 'SidMon II SID-like synthesis for Amiga',
    bestFor: ['Amiga chiptune', 'SID-like'],
    icon: 'Disc',
    color: 'text-gray-500',
  },
  DigMugSynth: {
    type: 'DigMugSynth',
    name: 'Digital Mugician',
    shortName: 'DigMug',
    description: 'Digital Mugician 4-wave blending wavetable synthesizer',
    bestFor: ['Amiga chiptune', 'Wavetable'],
    icon: 'Disc',
    color: 'text-gray-500',
  },
  FCSynth: {
    type: 'FCSynth',
    name: 'Future Composer',
    shortName: 'FC',
    description: 'Future Composer 1.3/1.4 with 47 waveforms and synth macro',
    bestFor: ['Amiga chiptune', 'Wavetable'],
    icon: 'Disc',
    color: 'text-gray-500',
  },
  FredSynth: {
    type: 'FredSynth',
    name: 'Fred Editor',
    shortName: 'Fred',
    description: 'Fred Editor macro-driven wavetable synthesizer',
    bestFor: ['Amiga chiptune', 'Wavetable'],
    icon: 'Disc',
    color: 'text-gray-500',
  },
  TFMXSynth: {
    type: 'TFMXSynth',
    name: 'TFMX',
    shortName: 'TFMX',
    description: 'TFMX / Jochen Hippel SndMod/VolMod sequence synthesizer',
    bestFor: ['Amiga chiptune', 'Game music'],
    icon: 'Disc',
    color: 'text-gray-500',
  },
  HippelCoSoSynth: {
    type: 'HippelCoSoSynth',
    name: 'Hippel CoSo',
    shortName: 'CoSo',
    description: 'Jochen Hippel CoSo pure synthesis engine with frequency/volume sequences, vibrato and portamento',
    bestFor: ['Amiga chiptune', 'Game music', 'Jochen Hippel'],
    icon: 'Disc',
    color: 'text-amber-400',
  },
  RobHubbardSynth: {
    type: 'RobHubbardSynth',
    name: 'Rob Hubbard',
    shortName: 'Rob Hubbard',
    description: 'Rob Hubbard Amiga PCM synthesis with period-based vibrato, wobble oscillator and portamento',
    bestFor: ['Amiga chiptune', 'Game music', 'Rob Hubbard'],
    icon: 'Disc',
    color: 'text-amber-500',
  },
  SidMon1Synth: {
    type: 'SidMon1Synth',
    name: 'SidMon 1.0',
    shortName: 'SidMon1',
    description: 'SidMon 1.0 wavetable synthesizer with ADSR envelope, 16-step arpeggio and phase LFO',
    bestFor: ['Amiga chiptune', 'Wavetable', 'SID-like'],
    icon: 'Disc',
    color: 'text-amber-300',
  },
  OctaMEDSynth: {
    type: 'OctaMEDSynth',
    name: 'OctaMED SynthInstr',
    shortName: 'OctaMED',
    description: 'OctaMED synthesizer instrument: vol/wf command-table oscillator with up to 10 waveforms',
    bestFor: ['Amiga chiptune', 'Wavetable', 'Tracker synth'],
    icon: 'Waveform',
    color: 'text-cyan-300',
  },
  DavidWhittakerSynth: {
    type: 'DavidWhittakerSynth',
    name: 'David Whittaker',
    shortName: 'DW',
    description: 'David Whittaker Amiga synthesis engine with period-based frequency/volume sequences and vibrato',
    bestFor: ['Amiga chiptune', 'Game music', 'David Whittaker'],
    icon: 'Disc',
    color: 'text-green-400',
  },
  SymphonieSynth: {
    type: 'SymphonieSynth',
    name: 'Symphonie Pro',
    shortName: 'SYM',
    description: 'Symphonie Pro Amiga tracker engine with DSP echo/delay ring buffer effects',
    bestFor: ['Amiga tracker', 'DSP effects', 'Symphonie Pro'],
    icon: 'Music',
    color: 'text-purple-400',
  },
  MusicLineSynth: {
    type: 'MusicLineSynth',
    name: 'MusicLine',
    shortName: 'MLN',
    description: 'MusicLine Amiga tracker engine with wavetable synthesis',
    bestFor: ['Amiga wavetable', 'Chiptune', 'MusicLine'],
    icon: 'Waves',
    color: 'text-teal-400',
  },
  DeltaMusic1Synth: {
    type: 'DeltaMusic1Synth',
    name: 'Delta Music 1.0',
    shortName: 'DM1',
    description: 'Amiga Delta Music 1.0 — 4-channel wavetable synth with ADSR envelopes and arpeggios',
    bestFor: ['Amiga chiptune', 'Wavetable', '4-channel'],
    icon: 'Disc',
    color: 'text-gray-400',
  },
  DeltaMusic2Synth: {
    type: 'DeltaMusic2Synth',
    name: 'Delta Music 2.0',
    shortName: 'DM2',
    description: 'Amiga Delta Music 2.0 — 4-channel wavetable synth with vol/vib tables',
    bestFor: ['Amiga chiptune', 'Wavetable', '4-channel'],
    icon: 'Disc',
    color: 'text-gray-400',
  },
  SonicArrangerSynth: {
    type: 'SonicArrangerSynth',
    name: 'Sonic Arranger',
    shortName: 'SA',
    description: 'Amiga Sonic Arranger — 4-channel synth with 18 real-time waveform effects',
    bestFor: ['Amiga chiptune', 'Wavetable', 'Synthesis effects'],
    icon: 'Disc',
    color: 'text-gray-400',
  },
  JamCrackerSynth: {
    type: 'JamCrackerSynth',
    name: 'JamCracker',
    shortName: 'JC',
    description: 'Amiga JamCracker — 4-channel tracker with AM synthesis and PCM samples',
    bestFor: ['Amiga', 'AM synthesis', 'Tracker'],
    icon: 'Disc',
    color: 'text-gray-400',
  },
  FuturePlayerSynth: {
    type: 'FuturePlayerSynth',
    name: 'Future Player',
    shortName: 'FP',
    description: 'Amiga Future Player — 4-channel synth with wavetable, modulation and envelope effects',
    bestFor: ['Amiga', 'Wavetable', 'Modulation synthesis'],
    icon: 'Disc',
    color: 'text-gray-400',
  },
};
