import type { SynthInfo } from './types';

export const amigaSynthEntries: Record<string, SynthInfo> = {
  HivelySynth: {
    type: 'HivelySynth',
    name: 'HivelyTracker',
    shortName: 'HVL',
    description: 'Amiga HivelyTracker/AHX chip synth with 4 waveforms, filter sweeps, and performance lists',
    bestFor: ['Chiptune', 'Amiga', 'AHX', 'Chip arpeggios', 'Filter sweeps'],
    icon: 'Cpu',
    color: 'text-green-400',
  },
  UADESynth: {
    type: 'UADESynth',
    name: 'UADE',
    shortName: 'UADE',
    description: 'Playback-only engine for 130+ exotic Amiga tracker formats via UADE',
    bestFor: ['Amiga modules', 'Exotic formats', 'Playback'],
    icon: 'Disc',
    color: 'text-text-muted',
  },
  SoundMonSynth: {
    type: 'SoundMonSynth',
    name: 'SoundMon',
    shortName: 'SoundMon',
    description: 'SoundMon II / Brian Postma wavetable synthesizer',
    bestFor: ['Amiga chiptune', 'Wavetable'],
    icon: 'Disc',
    color: 'text-text-muted',
  },
  SidMonSynth: {
    type: 'SidMonSynth',
    name: 'SidMon',
    shortName: 'SidMon',
    description: 'SidMon II SID-like synthesis for Amiga',
    bestFor: ['Amiga chiptune', 'SID-like'],
    icon: 'Disc',
    color: 'text-text-muted',
  },
  DigMugSynth: {
    type: 'DigMugSynth',
    name: 'Digital Mugician',
    shortName: 'DigMug',
    description: 'Digital Mugician 4-wave blending wavetable synthesizer',
    bestFor: ['Amiga chiptune', 'Wavetable'],
    icon: 'Disc',
    color: 'text-text-muted',
  },
  FCSynth: {
    type: 'FCSynth',
    name: 'Future Composer',
    shortName: 'FC',
    description: 'Future Composer 1.3/1.4 with 47 waveforms and synth macro',
    bestFor: ['Amiga chiptune', 'Wavetable'],
    icon: 'Disc',
    color: 'text-text-muted',
  },
  FredSynth: {
    type: 'FredSynth',
    name: 'Fred Editor',
    shortName: 'Fred',
    description: 'Fred Editor macro-driven wavetable synthesizer',
    bestFor: ['Amiga chiptune', 'Wavetable'],
    icon: 'Disc',
    color: 'text-text-muted',
  },
  TFMXSynth: {
    type: 'TFMXSynth',
    name: 'TFMX',
    shortName: 'TFMX',
    description: 'TFMX / Jochen Hippel SndMod/VolMod sequence synthesizer',
    bestFor: ['Amiga chiptune', 'Game music'],
    icon: 'Disc',
    color: 'text-text-muted',
  },
  HippelCoSoSynth: {
    type: 'HippelCoSoSynth',
    name: 'Hippel CoSo',
    shortName: 'CoSo',
    description: 'Jochen Hippel CoSo pure synthesis engine with frequency/volume sequences, vibrato and portamento',
    bestFor: ['Amiga chiptune', 'Game music', 'Jochen Hippel'],
    icon: 'Disc',
    color: 'text-amber-400',
  },
  RobHubbardSynth: {
    type: 'RobHubbardSynth',
    name: 'Rob Hubbard',
    shortName: 'Rob Hubbard',
    description: 'Rob Hubbard Amiga PCM synthesis with period-based vibrato, wobble oscillator and portamento',
    bestFor: ['Amiga chiptune', 'Game music', 'Rob Hubbard'],
    icon: 'Disc',
    color: 'text-amber-500',
  },
  SteveTurnerSynth: {
    type: 'SteveTurnerSynth',
    name: 'Steve Turner',
    shortName: 'SteveTurner',
    description: 'Steve Turner Amiga PCM synthesis with multi-phase envelope, vibrato table and pitch slide',
    bestFor: ['Amiga game music', 'Off Road Racer', 'Steve Turner'],
    icon: 'Disc',
    color: 'text-green-500',
  },
  SidMon1Synth: {
    type: 'SidMon1Synth',
    name: 'SidMon 1.0',
    shortName: 'SidMon1',
    description: 'SidMon 1.0 wavetable synthesizer with ADSR envelope, 16-step arpeggio and phase LFO',
    bestFor: ['Amiga chiptune', 'Wavetable', 'SID-like'],
    icon: 'Disc',
    color: 'text-amber-300',
  },
  SidMon2Synth: {
    type: 'SidMon2Synth',
    name: 'SidMon 2.0',
    shortName: 'SidMon2',
    description: 'SidMon 2.0 advanced SID-style synthesis with ADSR, vibrato, portamento, and 8-step arpeggio table',
    bestFor: ['Amiga chiptune', 'Wavetable', 'SID-like'],
    icon: 'Disc',
    color: 'text-amber-400',
  },
  OctaMEDSynth: {
    type: 'OctaMEDSynth',
    name: 'OctaMED SynthInstr',
    shortName: 'OctaMED',
    description: 'OctaMED synthesizer instrument: vol/wf command-table oscillator with up to 10 waveforms',
    bestFor: ['Amiga chiptune', 'Wavetable', 'Tracker synth'],
    icon: 'Waveform',
    color: 'text-accent-highlight',
  },
  DavidWhittakerSynth: {
    type: 'DavidWhittakerSynth',
    name: 'David Whittaker',
    shortName: 'DW',
    description: 'David Whittaker Amiga synthesis engine with period-based frequency/volume sequences and vibrato',
    bestFor: ['Amiga chiptune', 'Game music', 'David Whittaker'],
    icon: 'Disc',
    color: 'text-green-400',
  },
  SymphonieSynth: {
    type: 'SymphonieSynth',
    name: 'Symphonie Pro',
    shortName: 'SYM',
    description: 'Symphonie Pro Amiga tracker engine with DSP echo/delay ring buffer effects',
    bestFor: ['Amiga tracker', 'DSP effects', 'Symphonie Pro'],
    icon: 'Music',
    color: 'text-purple-400',
  },
  MusicLineSynth: {
    type: 'MusicLineSynth',
    name: 'MusicLine',
    shortName: 'MLN',
    description: 'MusicLine Amiga tracker engine with wavetable synthesis',
    bestFor: ['Amiga wavetable', 'Chiptune', 'MusicLine'],
    icon: 'Waves',
    color: 'text-teal-400',
  },
  DeltaMusic1Synth: {
    type: 'DeltaMusic1Synth',
    name: 'Delta Music 1.0',
    shortName: 'DM1',
    description: 'Amiga Delta Music 1.0 — 4-channel wavetable synth with ADSR envelopes and arpeggios',
    bestFor: ['Amiga chiptune', 'Wavetable', '4-channel'],
    icon: 'Disc',
    color: 'text-text-secondary',
  },
  DeltaMusic2Synth: {
    type: 'DeltaMusic2Synth',
    name: 'Delta Music 2.0',
    shortName: 'DM2',
    description: 'Amiga Delta Music 2.0 — 4-channel wavetable synth with vol/vib tables',
    bestFor: ['Amiga chiptune', 'Wavetable', '4-channel'],
    icon: 'Disc',
    color: 'text-text-secondary',
  },
  SonicArrangerSynth: {
    type: 'SonicArrangerSynth',
    name: 'Sonic Arranger',
    shortName: 'SA',
    description: 'Amiga Sonic Arranger — 4-channel synth with 18 real-time waveform effects',
    bestFor: ['Amiga chiptune', 'Wavetable', 'Synthesis effects'],
    icon: 'Disc',
    color: 'text-text-secondary',
  },
  InStereo2Synth: {
    type: 'InStereo2Synth',
    name: 'InStereo! 2.0',
    shortName: 'IS20',
    description: 'Amiga InStereo! 2.0 — 4-channel wavetable synth with ADSR, LFO, EG, arpeggios',
    bestFor: ['Amiga chiptune', 'Wavetable', 'Dual waveform'],
    icon: 'Disc',
    color: 'text-text-secondary',
  },
  InStereo1Synth: {
    type: 'InStereo1Synth',
    name: 'InStereo! 1.0',
    shortName: 'IS10',
    description: 'Amiga InStereo! 1.0 — 4-channel wavetable synth with ADSR, EGC, vibrato',
    bestFor: ['Amiga chiptune', 'Wavetable', 'Synthesis'],
    icon: 'Disc',
    color: 'text-text-secondary',
  },
  JamCrackerSynth: {
    type: 'JamCrackerSynth',
    name: 'JamCracker',
    shortName: 'JC',
    description: 'Amiga JamCracker — 4-channel tracker with AM synthesis and PCM samples',
    bestFor: ['Amiga', 'AM synthesis', 'Tracker'],
    icon: 'Disc',
    color: 'text-text-secondary',
  },
  FuturePlayerSynth: {
    type: 'FuturePlayerSynth',
    name: 'Future Player',
    shortName: 'FP',
    description: 'Amiga Future Player — 4-channel synth with wavetable, modulation and envelope effects',
    bestFor: ['Amiga', 'Wavetable', 'Modulation synthesis'],
    icon: 'Disc',
    color: 'text-text-secondary',
  },
  C64SID: {
    type: 'C64SID',
    name: 'C64 SID',
    shortName: 'SID',
    description: 'Commodore 64 SID chip — 3-voice synthesis with ring mod, sync, filters and ADSR envelopes',
    bestFor: ['C64', 'SID', 'Chiptune', '8-bit'],
    icon: 'Cpu',
    color: 'text-purple-400',
  },
  GTUltraSynth: {
    type: 'GTUltraSynth',
    name: 'GoatTracker Ultra',
    shortName: 'GTU',
    description: 'GoatTracker Ultra SID — full C64 SID tracker with wave/pulse/filter/speed tables',
    bestFor: ['C64', 'SID', 'Chiptune', 'Tracker'],
    icon: 'Cpu',
    color: 'text-green-400',
  },
  SF2Synth: {
    type: 'SF2Synth',
    name: 'SID Factory II',
    shortName: 'SF2',
    description: 'SID Factory II — C64 SID editor with driver-defined instrument tables and live 6502 emulation',
    bestFor: ['C64', 'SID', 'Chiptune', 'Tracker'],
    icon: 'Cpu',
    color: 'text-cyan-400',
  },
  KlysSynth: {
    type: 'KlysSynth',
    name: 'Klystrack',
    shortName: 'Klys',
    description: 'Klystrack chiptune tracker with wavetable synthesis, FM, filters and effects',
    bestFor: ['Chiptune', 'Wavetable', 'Tracker'],
    icon: 'Disc',
    color: 'text-accent-highlight',
  },
  Sc68Synth: {
    type: 'Sc68Synth',
    name: 'SC68',
    shortName: 'SC68',
    description: 'Atari ST YM2149 + 68000 replayer for .sc68/.sndh chiptune formats',
    bestFor: ['Atari ST', 'YM2149', 'Chiptune'],
    icon: 'Cpu',
    color: 'text-amber-400',
  },
  StartrekkerAMSynth: {
    type: 'StartrekkerAMSynth',
    name: 'StarTrekker AM',
    shortName: 'STAM',
    description: 'StarTrekker AM synthesis — 4 waveforms (sine/saw/square/noise) with ADSR envelopes, vibrato and period shifting',
    bestFor: ['Amiga', 'AM synthesis', 'StarTrekker'],
    icon: 'Cpu',
    color: 'text-cyan-400',
  },
  EupminiSynth: {
    type: 'EupminiSynth',
    name: 'EUP Mini',
    shortName: 'EUP',
    description: 'EUP (Elfin Unified Player) PC-98 music format playback',
    bestFor: ['PC-98', 'Japanese PC', 'FM'],
    icon: 'Disc',
    color: 'text-text-muted',
  },
  PreTrackerSynth: {
    type: 'PreTrackerSynth',
    name: 'PreTracker',
    shortName: 'PT',
    description: 'PreTracker Amiga wavetable synth with customizable waveforms, envelopes, and modulation',
    bestFor: ['Amiga', 'Wavetable', 'Chiptune'],
    icon: 'Cpu',
    color: 'text-green-400',
  },
  RonKlarenSynth: {
    type: 'RonKlarenSynth',
    name: 'Ron Klaren',
    shortName: 'RK',
    description: 'Ron Klaren custom Amiga sound system with per-instrument wavetables',
    bestFor: ['Amiga chiptune', 'Custom synth'],
    icon: 'Cpu',
    color: 'text-green-400',
  },
  SawteethSynth: {
    type: 'SawteethSynth',
    name: 'Sawteeth',
    shortName: 'Sawteeth',
    description: 'Sawteeth PSP/GP2X 4-channel wavetable tracker with filter sweeps and instrument patterns',
    bestFor: ['Chiptune', 'Wavetable', 'Modern tracker'],
    icon: 'Cpu',
    color: 'text-green-400',
  },
};
