import type { SynthInfo } from './types';

export const buzzMachineEntries: Record<string, SynthInfo> = {
  Buzzmachine: {
    type: 'Buzzmachine',
    name: 'Buzzmachine',
    shortName: 'Buzz',
    description: 'Jeskola Buzz machines - classic tracker effects and generators from the Buzz ecosystem',
    bestFor: ['Effects', 'Generators', 'Classic tracker sounds', 'Buzz compatibility'],
    icon: 'Cpu',
    color: 'text-yellow-500',
  },
  BuzzDTMF: {
    type: 'BuzzDTMF',
    name: 'CyanPhase DTMF',
    shortName: 'DTMF',
    description: 'Phone dial tone generator - classic DTMF tones',
    bestFor: ['Phone tones', 'Retro effects', 'Experimental'],
    icon: 'Phone',
    color: 'text-cyan-400',
  },
  BuzzFreqBomb: {
    type: 'BuzzFreqBomb',
    name: 'Frequency Bomb',
    shortName: 'FreqBomb',
    description: 'Elenzil Frequency Bomb - chaotic frequency modulation',
    bestFor: ['Noise', 'Chaos', 'Experimental'],
    icon: 'Bomb',
    color: 'text-red-500',
  },
  BuzzKick: {
    type: 'BuzzKick',
    name: 'FSM Kick',
    shortName: 'Kick',
    description: 'FSM Kick drum synthesizer',
    bestFor: ['Kick drums', 'Bass drums', 'Percussion'],
    icon: 'Drum',
    color: 'text-orange-500',
  },
  BuzzKickXP: {
    type: 'BuzzKickXP',
    name: 'FSM KickXP',
    shortName: 'KickXP',
    description: 'Extended FSM Kick with more parameters',
    bestFor: ['Kick drums', 'Deep bass', 'EDM kicks'],
    icon: 'Drum',
    color: 'text-orange-600',
  },
  BuzzNoise: {
    type: 'BuzzNoise',
    name: 'Jeskola Noise',
    shortName: 'Noise',
    description: 'Jeskola Noise generator',
    bestFor: ['Noise', 'Hi-hats', 'Textures'],
    icon: 'Waves',
    color: 'text-gray-400',
  },
  BuzzTrilok: {
    type: 'BuzzTrilok',
    name: 'Jeskola Trilok',
    shortName: 'Trilok',
    description: 'Jeskola Trilok bass drum synthesizer',
    bestFor: ['Bass drums', 'Toms', 'Percussion'],
    icon: 'Drum',
    color: 'text-amber-500',
  },
  Buzz4FM2F: {
    type: 'Buzz4FM2F',
    name: 'MadBrain 4FM2F',
    shortName: '4FM2F',
    description: '4-operator FM synthesizer with 2 filters',
    bestFor: ['FM sounds', 'Complex timbres', 'DX-style'],
    icon: 'Radio',
    color: 'text-purple-500',
  },
  BuzzDynamite6: {
    type: 'BuzzDynamite6',
    name: 'MadBrain Dynamite6',
    shortName: 'Dyn6',
    description: '6-voice additive synthesizer',
    bestFor: ['Additive synthesis', 'Organs', 'Complex sounds'],
    icon: 'Zap',
    color: 'text-yellow-500',
  },
  BuzzM3: {
    type: 'BuzzM3',
    name: 'Makk M3',
    shortName: 'M3',
    description: 'Dual-oscillator mono synth',
    bestFor: ['Bass', 'Leads', 'Classic synth'],
    icon: 'AudioLines',
    color: 'text-green-500',
  },
  Buzz3o3: {
    type: 'Buzz3o3',
    name: 'Oomek Aggressor 3o3',
    shortName: '3o3',
    description: 'TB-303 style acid synth clone',
    bestFor: ['Acid bass', 'Squelchy lines', 'Techno'],
    icon: 'Zap',
    color: 'text-lime-500',
  },
  Buzz3o3DF: {
    type: 'Buzz3o3DF',
    name: 'Aggressor Devil Fish',
    shortName: '3o3DF',
    description: 'Enhanced TB-303 clone with Devil Fish mods - accent decay, VEG, filter tracking, muffler',
    bestFor: ['Acid bass', 'Deep acid', 'Experimental', 'Devil Fish tones'],
    icon: 'Zap',
    color: 'text-lime-400',
  },
  BuzzM4: {
    type: 'BuzzM4',
    name: 'Makk M4',
    shortName: 'M4',
    description: 'Wavetable synth with 100+ waveforms, dual oscillators, sub osc, and dual LFOs',
    bestFor: ['Wavetable', 'Leads', 'Pads', 'Bass'],
    icon: 'Layers',
    color: 'text-sky-400',
  },
};
