/**
 * Synth Categories - Organized groupings of synth types
 */

import type { SynthCategory } from './types';
import { SYNTH_INFO } from './synthInfo';

export const SYNTH_CATEGORIES: SynthCategory[] = [
  {
    id: 'bass',
    name: 'Bass',
    description: 'Deep and punchy bass synths',
    synths: [SYNTH_INFO.TB303, SYNTH_INFO.MonoSynth, SYNTH_INFO.WobbleBass],
  },
  {
    id: 'lead',
    name: 'Lead',
    description: 'Melodic lead synthesizers',
    synths: [
      SYNTH_INFO.Synth,
      SYNTH_INFO.DuoSynth,
      SYNTH_INFO.FMSynth,
      SYNTH_INFO.AMSynth,
      SYNTH_INFO.PluckSynth,
      SYNTH_INFO.SuperSaw,
      SYNTH_INFO.ChipSynth,
      SYNTH_INFO.PWMSynth,
      SYNTH_INFO.FormantSynth,
      SYNTH_INFO.ModularSynth,
      SYNTH_INFO.V2,
    ],
  },
  {
    id: 'drums',
    name: 'Drums',
    description: 'Percussion and drum synthesis',
    synths: [SYNTH_INFO.MembraneSynth, SYNTH_INFO.MetalSynth, SYNTH_INFO.NoiseSynth, SYNTH_INFO.DrumMachine, SYNTH_INFO.DrumKit, SYNTH_INFO.Synare, SYNTH_INFO.MAMETR707],
  },
  {
    id: 'speech',
    name: 'Speech & Voice',
    description: 'Speech synthesis and voice generation',
    synths: [
      SYNTH_INFO.Sam,
      SYNTH_INFO.V2Speech,
      SYNTH_INFO.MAMETMS5220,
      SYNTH_INFO.MAMEVotrax,
      SYNTH_INFO.MAMESP0250,
      SYNTH_INFO.MAMEMEA8000,
      SYNTH_INFO.MAMEUPD931,
    ],
  },
  {
    id: 'pads',
    name: 'Pads',
    description: 'Evolving textures and pads',
    synths: [SYNTH_INFO.Wavetable, SYNTH_INFO.GranularSynth, SYNTH_INFO.PolySynth, SYNTH_INFO.StringMachine, SYNTH_INFO.HarmonicSynth, SYNTH_INFO.V2],
  },
  {
    id: 'dub',
    name: 'Dub & FX',
    description: 'Classic sound system and special effects',
    synths: [SYNTH_INFO.DubSiren, SYNTH_INFO.SpaceLaser, SYNTH_INFO.V2, SYNTH_INFO.Synare],
  },
  {
    id: 'vintage',
    name: 'Keys',
    description: 'Keyboard instruments',
    synths: [SYNTH_INFO.Organ],
  },
  {
    id: 'samples',
    name: 'Samples',
    description: 'Sample-based instruments',
    synths: [SYNTH_INFO.Sampler, SYNTH_INFO.Player, SYNTH_INFO.ChiptuneModule, SYNTH_INFO.MusicLineSynth],
  },
  {
    id: 'plugins',
    name: 'Plugins',
    description: 'External Web Audio Modules (WAM 2.0)',
    synths: [SYNTH_INFO.WAMOBXd, SYNTH_INFO.WAMSynth101, SYNTH_INFO.WAMTinySynth, SYNTH_INFO.WAMFaustFlute, SYNTH_INFO.WAM],
  },
  {
    id: 'fx',
    name: 'FX',
    description: 'Sound effects and noise generators',
    synths: [
      SYNTH_INFO.DubSiren,
    ],
  },
  {
    id: 'furnace',
    name: '🔥 Furnace Chips',
    description: 'All Furnace chip emulations - 70+ authentic retro sound chips',
    synths: [
      // FM Chips
      SYNTH_INFO.FurnaceOPN,
      SYNTH_INFO.FurnaceOPN2203,
      SYNTH_INFO.FurnaceOPNA,
      SYNTH_INFO.FurnaceOPNB,
      SYNTH_INFO.FurnaceOPNBB,
      SYNTH_INFO.FurnaceOPM,
      SYNTH_INFO.FurnaceOPL,
      SYNTH_INFO.FurnaceOPLL,
      SYNTH_INFO.FurnaceOPL4,
      SYNTH_INFO.FurnaceOPZ,
      SYNTH_INFO.FurnaceY8950,
      SYNTH_INFO.FurnaceESFM,
      SYNTH_INFO.FurnaceVRC7,
      // Console Chips
      SYNTH_INFO.FurnaceNES,
      SYNTH_INFO.FurnaceGB,
      SYNTH_INFO.FurnaceSNES,
      SYNTH_INFO.FurnacePCE,
      SYNTH_INFO.FurnacePSG,
      SYNTH_INFO.FurnaceVB,
      SYNTH_INFO.FurnaceLynx,
      SYNTH_INFO.FurnaceSWAN,
      SYNTH_INFO.FurnaceNDS,
      SYNTH_INFO.FurnaceGBA,
      SYNTH_INFO.FurnacePOKEMINI,
      SYNTH_INFO.FurnaceVRC6,
      SYNTH_INFO.FurnaceN163,
      SYNTH_INFO.FurnaceFDS,
      SYNTH_INFO.FurnaceMMC5,
      // Computer Chips
      SYNTH_INFO.FurnaceC64,
      SYNTH_INFO.FurnaceSID6581,
      SYNTH_INFO.FurnaceSID8580,
      SYNTH_INFO.FurnaceAY,
      SYNTH_INFO.FurnaceAY8930,
      SYNTH_INFO.FurnaceVIC,
      SYNTH_INFO.FurnacePET,
      SYNTH_INFO.FurnaceSAA,
      SYNTH_INFO.FurnaceTED,
      SYNTH_INFO.FurnaceDAVE,
      SYNTH_INFO.FurnaceVERA,
      SYNTH_INFO.FurnaceSCC,
      SYNTH_INFO.FurnaceTIA,
      SYNTH_INFO.FurnacePOKEY,
      SYNTH_INFO.FurnaceZXBEEPER,
      SYNTH_INFO.FurnaceAMIGA,
      SYNTH_INFO.FurnacePCSPKR,
      // Arcade PCM
      SYNTH_INFO.FurnaceSEGAPCM,
      SYNTH_INFO.FurnaceQSOUND,
      SYNTH_INFO.FurnaceES5506,
      SYNTH_INFO.FurnaceRF5C68,
      SYNTH_INFO.FurnaceC140,
      SYNTH_INFO.FurnaceK007232,
      SYNTH_INFO.FurnaceK053260,
      SYNTH_INFO.FurnaceGA20,
      SYNTH_INFO.FurnaceOKI,
      SYNTH_INFO.FurnaceYMZ280B,
      SYNTH_INFO.FurnaceX1_010,
      SYNTH_INFO.FurnaceBUBBLE,
      SYNTH_INFO.FurnaceMULTIPCM,
      SYNTH_INFO.FurnaceMSM6258,
      SYNTH_INFO.FurnaceMSM5232,
      SYNTH_INFO.FurnaceNAMCO,
      // Other Chips
      SYNTH_INFO.FurnaceSM8521,
      SYNTH_INFO.FurnaceT6W28,
      SYNTH_INFO.FurnaceSUPERVISION,
      SYNTH_INFO.FurnaceUPD1771,
      SYNTH_INFO.FurnacePONG,
      SYNTH_INFO.FurnacePV1000,
      SYNTH_INFO.FurnaceSU,
      SYNTH_INFO.FurnacePOWERNOISE,
      SYNTH_INFO.FurnaceSCVTONE,
      SYNTH_INFO.FurnacePCMDAC,
      SYNTH_INFO.Furnace,
    ],
  },
  {
    id: 'chiptune-fm',
    name: 'FM Chips',
    description: 'Yamaha FM synthesis chips (OPN, OPL, OPM families)',
    synths: [
      SYNTH_INFO.FurnaceOPN,
      SYNTH_INFO.FurnaceOPN2203,
      SYNTH_INFO.FurnaceOPNA,
      SYNTH_INFO.FurnaceOPNB,
      SYNTH_INFO.FurnaceOPNBB,
      SYNTH_INFO.FurnaceOPM,
      SYNTH_INFO.FurnaceOPL,
      SYNTH_INFO.FurnaceOPLL,
      SYNTH_INFO.FurnaceOPL4,
      SYNTH_INFO.FurnaceOPZ,
      SYNTH_INFO.FurnaceY8950,
      SYNTH_INFO.FurnaceESFM,
      SYNTH_INFO.FurnaceVRC7,
    ],
  },
  {
    id: 'chiptune-console',
    name: 'Console Chips',
    description: 'Game console sound chips (Nintendo, Sega, etc.)',
    synths: [
      SYNTH_INFO.FurnaceNES,
      SYNTH_INFO.FurnaceGB,
      SYNTH_INFO.FurnaceSNES,
      SYNTH_INFO.FurnacePCE,
      SYNTH_INFO.FurnacePSG,
      SYNTH_INFO.FurnaceVB,
      SYNTH_INFO.FurnaceLynx,
      SYNTH_INFO.FurnaceSWAN,
      SYNTH_INFO.FurnaceNDS,
      SYNTH_INFO.FurnaceGBA,
      SYNTH_INFO.FurnacePOKEMINI,
      SYNTH_INFO.FurnaceVRC6,
      SYNTH_INFO.FurnaceN163,
      SYNTH_INFO.FurnaceFDS,
      SYNTH_INFO.FurnaceMMC5,
    ],
  },
  {
    id: 'chiptune-computer',
    name: 'Computer Chips',
    description: 'Home computer sound chips (C64, Spectrum, etc.)',
    synths: [
      SYNTH_INFO.FurnaceC64,
      SYNTH_INFO.FurnaceSID6581,
      SYNTH_INFO.FurnaceSID8580,
      SYNTH_INFO.FurnaceAY,
      SYNTH_INFO.FurnaceAY8930,
      SYNTH_INFO.FurnaceVIC,
      SYNTH_INFO.FurnacePET,
      SYNTH_INFO.FurnaceSAA,
      SYNTH_INFO.FurnaceTED,
      SYNTH_INFO.FurnaceDAVE,
      SYNTH_INFO.FurnaceVERA,
      SYNTH_INFO.FurnaceSCC,
      SYNTH_INFO.FurnaceTIA,
      SYNTH_INFO.FurnacePOKEY,
      SYNTH_INFO.FurnaceZXBEEPER,
      SYNTH_INFO.FurnaceAMIGA,
      SYNTH_INFO.FurnacePCSPKR,
      SYNTH_INFO.HivelySynth,
      SYNTH_INFO.HippelCoSoSynth,
      SYNTH_INFO.RobHubbardSynth,
      SYNTH_INFO.DavidWhittakerSynth,
      SYNTH_INFO.UADESynth,
      SYNTH_INFO.SoundMonSynth,
      SYNTH_INFO.SidMonSynth,
      SYNTH_INFO.SidMon1Synth,
      SYNTH_INFO.DigMugSynth,
      SYNTH_INFO.FCSynth,
      SYNTH_INFO.FredSynth,
      SYNTH_INFO.TFMXSynth,
      SYNTH_INFO.OctaMEDSynth,
      SYNTH_INFO.SymphonieSynth,
      SYNTH_INFO.C64SID,
      SYNTH_INFO.KlysSynth,
      SYNTH_INFO.Sc68Synth,
    ],
  },
  {
    id: 'chiptune-arcade',
    name: 'Arcade PCM',
    description: 'Arcade game PCM/ADPCM chips (Sega, Namco, Konami, Capcom)',
    synths: [
      SYNTH_INFO.FurnaceSEGAPCM,
      SYNTH_INFO.FurnaceQSOUND,
      SYNTH_INFO.FurnaceES5506,
      SYNTH_INFO.FurnaceRF5C68,
      SYNTH_INFO.FurnaceC140,
      SYNTH_INFO.FurnaceK007232,
      SYNTH_INFO.FurnaceK053260,
      SYNTH_INFO.FurnaceGA20,
      SYNTH_INFO.FurnaceOKI,
      SYNTH_INFO.FurnaceYMZ280B,
      SYNTH_INFO.FurnaceX1_010,
      SYNTH_INFO.FurnaceBUBBLE,
      SYNTH_INFO.FurnaceMULTIPCM,
      SYNTH_INFO.FurnaceMSM6258,
      SYNTH_INFO.FurnaceMSM5232,
      SYNTH_INFO.FurnaceNAMCO,
    ],
  },
  {
    id: 'chiptune-other',
    name: 'Other Chips',
    description: 'Obscure and miscellaneous sound chips',
    synths: [
      SYNTH_INFO.FurnaceSM8521,
      SYNTH_INFO.FurnaceT6W28,
      SYNTH_INFO.FurnaceSUPERVISION,
      SYNTH_INFO.FurnaceUPD1771,
      SYNTH_INFO.FurnacePONG,
      SYNTH_INFO.FurnacePV1000,
      SYNTH_INFO.FurnaceSU,
      SYNTH_INFO.FurnacePOWERNOISE,
      SYNTH_INFO.FurnaceSCVTONE,
      SYNTH_INFO.FurnacePCMDAC,
      SYNTH_INFO.Furnace, // Generic fallback
    ],
  },
  {
    id: 'buzzmachines',
    name: 'Buzzmachines',
    description: 'Jeskola Buzz machines - classic tracker synths and drums',
    synths: [
      SYNTH_INFO.Buzzmachine,     // Generic Buzz fallback
      SYNTH_INFO.Buzz3o3,         // TB-303 clone
      SYNTH_INFO.Buzz3o3DF,       // Devil Fish enhanced 303
      SYNTH_INFO.BuzzM3,          // Dual-osc synth
      SYNTH_INFO.BuzzM4,          // 100-waveform wavetable synth
      SYNTH_INFO.Buzz4FM2F,       // 4-op FM
      SYNTH_INFO.BuzzDynamite6,   // 6-op additive
      SYNTH_INFO.BuzzKick,        // Kick drum
      SYNTH_INFO.BuzzKickXP,      // Extended kick
      SYNTH_INFO.BuzzTrilok,      // Bass drum
      SYNTH_INFO.BuzzNoise,       // Noise generator
      SYNTH_INFO.BuzzFreqBomb,    // Frequency sweep
      SYNTH_INFO.BuzzDTMF,        // Phone tones
    ],
  },
  {
    id: 'mame-synths',
    name: 'MAME Hardware Synths',
    description: 'Hardware-accurate synth and keyboard chip emulations',
    synths: [
      SYNTH_INFO.MAMEVFX,
      SYNTH_INFO.VFX,
      SYNTH_INFO.D50,
      SYNTH_INFO.MAMEDOC,
      SYNTH_INFO.MAMEES5503,
      SYNTH_INFO.MAMERSA,
      SYNTH_INFO.MAMESWP30,
      SYNTH_INFO.CZ101,
      SYNTH_INFO.MAMEUPD933,
      SYNTH_INFO.CEM3394,
      SYNTH_INFO.SCSP,
      SYNTH_INFO.MAMEVASynth,
      SYNTH_INFO.MAMEYMF271,
      SYNTH_INFO.MAMEYMOPQ,
    ],
  },
  {
    id: 'mame-arcade',
    name: 'MAME Arcade & Retro',
    description: 'Arcade game and retro computer sound chips (MAME-emulated)',
    synths: [
      SYNTH_INFO.MAMEAICA,
      SYNTH_INFO.MAMEASC,
      SYNTH_INFO.MAMEAstrocade,
      SYNTH_INFO.MAMEC352,
      SYNTH_INFO.MAMEICS2115,
      SYNTH_INFO.MAMEK054539,
      SYNTH_INFO.MAMEMSM5232,
      SYNTH_INFO.MAMERF5C400,
      SYNTH_INFO.MAMESN76477,
      SYNTH_INFO.MAMESNKWave,
      SYNTH_INFO.MAMETIA,
      SYNTH_INFO.MAMETMS36XX,
    ],
  },
  {
    id: 'juce-synths',
    name: '🎛️ JUCE Synths',
    description: 'Professional quality WASM-based synth emulations',
    synths: [
      SYNTH_INFO.Dexed,
      SYNTH_INFO.OBXd,
      SYNTH_INFO.SunVoxSynth,
    ],
  },
  {
    id: 'scripted',
    name: '📝 Scripted',
    description: 'Live-coded and algorithmically scripted synthesis',
    synths: [
      SYNTH_INFO.SuperCollider,
    ],
  },
  {
    id: 'gearmulator',
    name: '🔧 Gearmulator (ROM)',
    description: 'DSP56300 emulations of classic VA synths — requires user-provided firmware ROMs',
    synths: [
      SYNTH_INFO.GearmulatorVirus,
      SYNTH_INFO.GearmulatorVirusTI,
      SYNTH_INFO.GearmulatorMicroQ,
      SYNTH_INFO.GearmulatorXT,
      SYNTH_INFO.GearmulatorNord,
      SYNTH_INFO.GearmulatorJP8000,
    ],
  },
  {
    id: 'vstbridge',
    name: '🔌 VST Bridge',
    description: 'Open-source synths ported via the generic VSTBridge framework',
    synths: [
      SYNTH_INFO.Vital,
      SYNTH_INFO.Surge,
      SYNTH_INFO.Odin2,
      SYNTH_INFO.DexedBridge,
      SYNTH_INFO.Helm,
      SYNTH_INFO.Sorcer,
      SYNTH_INFO.Amsynth,
      SYNTH_INFO.OBXf,
      SYNTH_INFO.TonewheelOrgan,
      SYNTH_INFO.Melodica,
      SYNTH_INFO.Monique,
    ],
  },
];
