import type { SynthInfo } from './types';

export const classicSynthEntries: Record<string, SynthInfo> = {
  TB303: {
    type: 'TB303',
    name: 'TB-303',
    shortName: '303',
    description: 'Classic acid bass synthesizer with resonant filter and slide',
    bestFor: ['Acid bass', 'Squelchy lines', 'Techno', 'House'],
    icon: 'Zap',
    color: 'text-accent-primary',
  },
  MonoSynth: {
    type: 'MonoSynth',
    name: 'Mono Synth',
    shortName: 'Mono',
    description: 'Single-voice synth with oscillator, filter, and envelope',
    bestFor: ['Bass', 'Lead lines', 'Portamento'],
    icon: 'AudioLines',
    color: 'text-blue-400',
  },
  Synth: {
    type: 'Synth',
    name: 'Basic Synth',
    shortName: 'Synth',
    description: 'Simple polyphonic synthesizer with amplitude envelope',
    bestFor: ['Pads', 'Chords', 'Simple sounds'],
    icon: 'Music2',
    color: 'text-purple-400',
  },
  DuoSynth: {
    type: 'DuoSynth',
    name: 'Duo Synth',
    shortName: 'Duo',
    description: 'Two-voice synth with harmonics and vibratoesque LFO',
    bestFor: ['Rich leads', 'Detuned sounds', 'Fat bass'],
    icon: 'Layers',
    color: 'text-indigo-400',
  },
  FMSynth: {
    type: 'FMSynth',
    name: 'FM Synth',
    shortName: 'FM',
    description: 'Frequency modulation synth for complex harmonic tones',
    bestFor: ['Bells', 'Electric piano', 'Metallic sounds'],
    icon: 'Radio',
    color: 'text-cyan-400',
  },
  AMSynth: {
    type: 'AMSynth',
    name: 'AM Synth',
    shortName: 'AM',
    description: 'Amplitude modulation synth with ring modulation character',
    bestFor: ['Tremolo effects', 'Ring mod', 'Atmospheric'],
    icon: 'Activity',
    color: 'text-teal-400',
  },
  PluckSynth: {
    type: 'PluckSynth',
    name: 'Pluck Synth',
    shortName: 'Pluck',
    description: 'Karplus-Strong string synthesis for plucked strings',
    bestFor: ['Guitar', 'Harp', 'Pizzicato', 'String plucks'],
    icon: 'Guitar',
    color: 'text-amber-400',
  },
  SuperSaw: {
    type: 'SuperSaw',
    name: 'SuperSaw',
    shortName: 'SSaw',
    description: 'Massive detuned saw waves for trance and EDM',
    bestFor: ['Trance leads', 'EDM drops', 'Big chords', 'Supersaw stabs'],
    icon: 'Layers',
    color: 'text-orange-500',
  },
  PolySynth: {
    type: 'PolySynth',
    name: 'Poly Synth',
    shortName: 'Poly',
    description: 'True polyphonic synth with voice management',
    bestFor: ['Chords', 'Pads', 'Polyphonic parts', 'Layered sounds'],
    icon: 'LayoutGrid',
    color: 'text-blue-500',
  },
  Organ: {
    type: 'Organ',
    name: 'Drawbar Organ',
    shortName: 'Organ',
    description: 'Hammond-style tonewheel organ with drawbars',
    bestFor: ['House', 'Gospel', 'Jazz', 'Rock organ'],
    icon: 'Piano',
    color: 'text-amber-600',
  },
  ChipSynth: {
    type: 'ChipSynth',
    name: 'Chip Synth',
    shortName: 'Chip',
    description: '8-bit video game console sounds',
    bestFor: ['Chiptune', 'Retro', 'Lo-fi', 'Arpeggios'],
    icon: 'Gamepad2',
    color: 'text-green-400',
  },
  PWMSynth: {
    type: 'PWMSynth',
    name: 'PWM Synth',
    shortName: 'PWM',
    description: 'Pulse width modulation for rich analog tones',
    bestFor: ['Analog pads', 'Warm leads', 'Classic synth'],
    icon: 'Waves',
    color: 'text-emerald-400',
  },
  StringMachine: {
    type: 'StringMachine',
    name: 'String Machine',
    shortName: 'Strings',
    description: 'Vintage ensemble strings (Solina-style)',
    bestFor: ['Lush pads', 'Disco strings', 'Ambient', 'Retro'],
    icon: 'Music4',
    color: 'text-rose-400',
  },
  FormantSynth: {
    type: 'FormantSynth',
    name: 'Formant Synth',
    shortName: 'Vocal',
    description: 'Vowel synthesis for vocal-like sounds',
    bestFor: ['Vocal pads', 'Talk box', 'Choir', 'Robotic'],
    icon: 'Mic',
    color: 'text-fuchsia-400',
  },
  Wavetable: {
    type: 'Wavetable',
    name: 'Wavetable',
    shortName: 'Wave',
    description: 'Wavetable synth with morphing and unison',
    bestFor: ['Evolving pads', 'Modern bass', 'Complex timbres'],
    icon: 'Waves',
    color: 'text-pink-400',
  },
  HarmonicSynth: {
    type: 'HarmonicSynth',
    name: 'Harmonic Synth',
    shortName: 'Harmonic',
    description: 'Additive/spectral synth with 32-harmonic editor',
    bestFor: ['Organ tones', 'Bells', 'Custom timbres', 'Spectral design'],
    icon: 'BarChart3',
    color: 'text-emerald-400',
  },
  WobbleBass: {
    type: 'WobbleBass',
    name: 'Wobble Bass',
    shortName: 'Wobble',
    description: 'Dubstep/DnB bass with tempo-synced LFO, Reese detuning, FM growl',
    bestFor: ['Dubstep', 'DnB', 'Jungle', 'Neurofunk', 'Riddim'],
    icon: 'Waves',
    color: 'text-fuchsia-500',
  },
  ModularSynth: {
    type: 'ModularSynth',
    name: 'Modular Synth',
    shortName: 'Modular',
    description: 'Patch editor with modules (VCO, VCF, VCA, ADSR, LFO) and cable routing',
    bestFor: ['Sound design', 'Experimental', 'Custom patches', 'Flexible routing'],
    icon: 'Cable',
    color: 'text-indigo-500',
  },
};
