import type { SynthInfo } from './types';

export const furnaceChipEntries: Record<string, SynthInfo> = {
  Furnace: {
    type: 'Furnace',
    name: 'Furnace FM',
    shortName: 'FUI',
    description: 'FM engine compatible with Furnace Tracker (.fui) instruments',
    bestFor: ['Genesis bass', 'FM bells', 'Retro arcade', '4-op FM'],
    icon: 'Cpu',
    color: 'text-amber-500',
  },
  FurnaceOPN: {
    type: 'FurnaceOPN',
    name: 'Sega Genesis (YM2612)',
    shortName: 'Genesis',
    description: 'Sega Genesis / Mega Drive YM2612 - 6 channels of 4-op FM',
    bestFor: ['Genesis bass', 'FM leads', 'Slap bass', '16-bit game music'],
    icon: 'Gamepad2',
    color: 'text-blue-500',
  },
  FurnaceOPM: {
    type: 'FurnaceOPM',
    name: 'Arcade / X68000 (YM2151)',
    shortName: 'OPM',
    description: 'Yamaha YM2151 - Sharp X68000, arcade machines',
    bestFor: ['Arcade FM', 'Bright leads', 'Brass', 'Game music'],
    icon: 'Cpu',
    color: 'text-accent-highlight',
  },
  FurnaceOPL: {
    type: 'FurnaceOPL',
    name: 'AdLib / Sound Blaster (OPL3)',
    shortName: 'OPL3',
    description: 'Yamaha YMF262 - AdLib, Sound Blaster, DOS games',
    bestFor: ['DOS game music', 'MIDI synth', 'Organs', 'PC gaming'],
    icon: 'Monitor',
    color: 'text-yellow-500',
  },
  FurnaceOPLL: {
    type: 'FurnaceOPLL',
    name: 'MSX / Sega (OPLL)',
    shortName: 'OPLL',
    description: 'Yamaha YM2413 - MSX, SMS FM unit, budget FM',
    bestFor: ['MSX music', 'SMS FM', 'Lo-fi FM', 'Simple FM'],
    icon: 'Radio',
    color: 'text-orange-400',
  },
  FurnaceESFM: {
    type: 'FurnaceESFM',
    name: 'ESFM',
    shortName: 'ESFM',
    description: 'Enhanced Sound FM - advanced OPL3 with operator detune',
    bestFor: ['Modern retro', 'Enhanced FM', 'Detuned sounds'],
    icon: 'Zap',
    color: 'text-purple-500',
  },
  FurnaceOPZ: {
    type: 'FurnaceOPZ',
    name: 'Yamaha TX81Z (OPZ)',
    shortName: 'OPZ',
    description: 'Yamaha YM2414 - TX81Z, DX11, advanced FM',
    bestFor: ['Lately bass', 'DX bells', 'Complex FM', 'E-piano'],
    icon: 'Piano',
    color: 'text-indigo-500',
  },
  FurnaceNES: {
    type: 'FurnaceNES',
    name: 'Nintendo NES (2A03)',
    shortName: 'NES',
    description: 'Nintendo Entertainment System - 2 pulse, triangle, noise, DPCM',
    bestFor: ['NES chiptune', '8-bit melodies', 'Retro drums', 'Famicom'],
    icon: 'Gamepad2',
    color: 'text-red-500',
  },
  FurnaceGB: {
    type: 'FurnaceGB',
    name: 'Nintendo Game Boy',
    shortName: 'GB',
    description: 'Nintendo Game Boy - 2 pulse, wave, noise channels',
    bestFor: ['Game Boy music', 'Lo-fi chiptune', 'Portable gaming'],
    icon: 'Smartphone',
    color: 'text-green-500',
  },
  FurnaceC64: {
    type: 'FurnaceC64',
    name: 'Commodore 64 (SID)',
    shortName: 'SID',
    description: 'Commodore 64 SID chip - 3 voices with filters',
    bestFor: ['SID leads', 'Arpeggios', 'Filter sweeps', 'Demoscene'],
    icon: 'Save',
    color: 'text-violet-500',
  },
  FurnaceAY: {
    type: 'FurnaceAY',
    name: 'ZX Spectrum / Amstrad (AY)',
    shortName: 'AY',
    description: 'General Instrument AY - ZX Spectrum, MSX, Atari ST',
    bestFor: ['ZX Spectrum', 'MSX', 'Amstrad CPC', 'Envelope tricks'],
    icon: 'Tv',
    color: 'text-sky-500',
  },
  FurnaceTIA: {
    type: 'FurnaceTIA',
    name: 'Atari TIA',
    shortName: 'TIA',
    description: 'Atari 2600 - primitive but distinctive sound',
    bestFor: ['Atari 2600', 'Primitive bleeps', 'Retro FX'],
    icon: 'Joystick',
    color: 'text-amber-600',
  },
  FurnaceVERA: {
    type: 'FurnaceVERA',
    name: 'Commander X16 (VERA)',
    shortName: 'VERA',
    description: 'Commander X16 - modern retro 16 channels PSG + PCM',
    bestFor: ['Modern retro', 'X16 music', 'Rich PSG'],
    icon: 'Cpu',
    color: 'text-teal-500',
  },
  FurnaceSAA: {
    type: 'FurnaceSAA',
    name: 'SAM Coupé (SAA1099)',
    shortName: 'SAA',
    description: 'Philips SAA1099 - Sam Coupé, some PC sound cards',
    bestFor: ['Sam Coupé', 'Stereo chips', 'European home computers'],
    icon: 'Speaker',
    color: 'text-pink-500',
  },
  FurnacePSG: {
    type: 'FurnacePSG',
    name: 'Sega Master System (PSG)',
    shortName: 'PSG',
    description: 'TI SN76489 - Master System, Game Gear, BBC Micro',
    bestFor: ['Master System', 'Colecovision', 'Square wave PSG'],
    icon: 'SquareStack',
    color: 'text-emerald-500',
  },
  FurnaceVIC: {
    type: 'FurnaceVIC',
    name: 'Commodore VIC-20',
    shortName: 'VIC',
    description: 'Commodore VIC-20 - 3 square + noise',
    bestFor: ['VIC-20 music', 'Early 80s', 'Simple tones'],
    icon: 'Monitor',
    color: 'text-lime-500',
  },
  FurnaceLynx: {
    type: 'FurnaceLynx',
    name: 'Atari Lynx',
    shortName: 'Lynx',
    description: 'Atari Lynx - 4 channel wavetable',
    bestFor: ['Lynx music', 'Portable gaming', 'Wavetable'],
    icon: 'Gamepad',
    color: 'text-rose-500',
  },
  FurnaceSID6581: {
    type: 'FurnaceSID6581',
    name: 'SID 6581',
    shortName: '6581',
    description: 'Classic C64 SID - warm, gritty original chip',
    bestFor: ['Authentic C64', 'Warm bass', 'Classic demoscene'],
    icon: 'Save',
    color: 'text-violet-400',
  },
  FurnaceSID8580: {
    type: 'FurnaceSID8580',
    name: 'SID 8580',
    shortName: '8580',
    description: 'Revised SID - cleaner filter, brighter sound',
    bestFor: ['Clean SID', 'Later C64/C128', 'Clearer filters'],
    icon: 'Save',
    color: 'text-violet-600',
  },
  FurnaceOPNA: {
    type: 'FurnaceOPNA',
    name: 'NEC PC-98 (OPNA)',
    shortName: 'OPNA',
    description: 'YM2608 - NEC PC-98, arcade machines',
    bestFor: ['PC-98 music', 'Touhou-style', 'Japanese arcade'],
    icon: 'Cpu',
    color: 'text-blue-400',
  },
  FurnaceOPNB: {
    type: 'FurnaceOPNB',
    name: 'SNK Neo Geo (OPNB)',
    shortName: 'OPNB',
    description: 'YM2610 - SNK Neo Geo',
    bestFor: ['Neo Geo music', 'Fighting games', 'SNK'],
    icon: 'Gamepad2',
    color: 'text-red-400',
  },
  FurnaceOPL4: {
    type: 'FurnaceOPL4',
    name: 'Yamaha OPL4',
    shortName: 'OPL4',
    description: 'Yamaha YMF278 - FM + wavetable hybrid',
    bestFor: ['Advanced OPL', 'FM + samples', 'Late DOS'],
    icon: 'Layers',
    color: 'text-yellow-400',
  },
  FurnaceY8950: {
    type: 'FurnaceY8950',
    name: 'MSX-Audio (Y8950)',
    shortName: 'Y8950',
    description: 'Yamaha Y8950 - MSX-Audio, OPL + ADPCM',
    bestFor: ['MSX-Audio', 'OPL with drums', 'Japanese PC'],
    icon: 'Radio',
    color: 'text-orange-300',
  },
  FurnacePCE: {
    type: 'FurnacePCE',
    name: 'PC Engine / TurboGrafx',
    shortName: 'PCE',
    description: 'PC Engine / TurboGrafx-16 - 6 channel wavetable',
    bestFor: ['PC Engine', 'TurboGrafx', 'HuCard games'],
    icon: 'Tv',
    color: 'text-orange-500',
  },
  FurnaceSNES: {
    type: 'FurnaceSNES',
    name: 'Super Nintendo (SPC700)',
    shortName: 'SNES',
    description: 'Super Nintendo - Sony SPC700 8-channel BRR',
    bestFor: ['SNES music', '16-bit classics', 'BRR samples'],
    icon: 'Gamepad2',
    color: 'text-purple-400',
  },
  FurnaceVB: {
    type: 'FurnaceVB',
    name: 'Nintendo Virtual Boy',
    shortName: 'VB',
    description: 'Nintendo Virtual Boy - 6 channel wavetable',
    bestFor: ['Virtual Boy', 'Stereo 3D audio', 'Nintendo VB'],
    icon: 'Glasses',
    color: 'text-red-600',
  },
  FurnaceSWAN: {
    type: 'FurnaceSWAN',
    name: 'Bandai WonderSwan',
    shortName: 'SWAN',
    description: 'Bandai WonderSwan - 4 channel wavetable + PCM',
    bestFor: ['WonderSwan', 'Portable gaming', 'Bandai'],
    icon: 'Smartphone',
    color: 'text-accent-highlight',
  },
  FurnaceVRC6: {
    type: 'FurnaceVRC6',
    name: 'Famicom (VRC6)',
    shortName: 'VRC6',
    description: 'Konami VRC6 - 2 pulse + saw (Castlevania 3 JP)',
    bestFor: ['Castlevania 3', 'Konami NES', 'Extra channels'],
    icon: 'Zap',
    color: 'text-amber-400',
  },
  FurnaceVRC7: {
    type: 'FurnaceVRC7',
    name: 'Famicom (VRC7)',
    shortName: 'VRC7',
    description: 'Konami VRC7 - OPLL clone (Lagrange Point)',
    bestFor: ['Lagrange Point', 'FM on NES', 'Konami FM'],
    icon: 'Radio',
    color: 'text-amber-500',
  },
  FurnaceN163: {
    type: 'FurnaceN163',
    name: 'Namco Arcade (N163)',
    shortName: 'N163',
    description: 'Namco 163 - 8 channel wavetable',
    bestFor: ['Namco NES', 'Wavetable', 'Complex tones'],
    icon: 'Waves',
    color: 'text-green-400',
  },
  FurnaceFDS: {
    type: 'FurnaceFDS',
    name: 'Famicom Disk System',
    shortName: 'FDS',
    description: 'Famicom Disk System - wavetable + modulation',
    bestFor: ['FDS games', 'Wavy bass', 'Zelda FDS'],
    icon: 'Disc',
    color: 'text-yellow-500',
  },
  FurnaceMMC5: {
    type: 'FurnaceMMC5',
    name: 'Famicom (MMC5)',
    shortName: 'MMC5',
    description: 'MMC5 - 2 extra pulse channels',
    bestFor: ['Castlevania 3 US', 'Extra NES pulse', 'CV3'],
    icon: 'Plus',
    color: 'text-blue-300',
  },
  FurnaceTED: {
    type: 'FurnaceTED',
    name: 'Commodore Plus/4 (TED)',
    shortName: 'TED',
    description: 'Commodore Plus/4 TED - 2 square + noise',
    bestFor: ['Plus/4 music', 'Commodore 16', 'Budget C64'],
    icon: 'Monitor',
    color: 'text-violet-400',
  },
  FurnaceSEGAPCM: {
    type: 'FurnaceSEGAPCM',
    name: 'Sega Arcade (SegaPCM)',
    shortName: 'SEGAPCM',
    description: 'Sega System 16/18 - 16 channel PCM',
    bestFor: ['OutRun', 'After Burner', 'Sega arcade'],
    icon: 'Speaker',
    color: 'text-blue-500',
  },
  FurnaceQSOUND: {
    type: 'FurnaceQSOUND',
    name: 'Capcom Arcade (QSound)',
    shortName: 'QSound',
    description: 'Capcom QSound - CPS1/CPS2 with 3D audio',
    bestFor: ['Street Fighter', 'CPS games', '3D positioning'],
    icon: 'Headphones',
    color: 'text-purple-500',
  },
  FurnaceES5506: {
    type: 'FurnaceES5506',
    name: 'ES5506',
    shortName: 'ES5506',
    description: 'Ensoniq ES5506 - 32 voice wavetable',
    bestFor: ['Taito F3', 'Ensoniq synths', 'High quality'],
    icon: 'AudioLines',
    color: 'text-pink-400',
  },
  FurnaceRF5C68: {
    type: 'FurnaceRF5C68',
    name: 'RF5C68',
    shortName: 'RF5C68',
    description: 'Ricoh RF5C68 - Sega CD, 8 channel PCM',
    bestFor: ['Sega CD', 'Mega CD', 'CD audio'],
    icon: 'Disc',
    color: 'text-accent-highlight',
  },
  FurnaceC140: {
    type: 'FurnaceC140',
    name: 'C140',
    shortName: 'C140',
    description: 'Namco C140 - System 2, 24 channel PCM',
    bestFor: ['Namco arcade', 'System 2', 'Assault'],
    icon: 'Cpu',
    color: 'text-yellow-400',
  },
  FurnaceK007232: {
    type: 'FurnaceK007232',
    name: 'K007232',
    shortName: 'K007232',
    description: 'Konami K007232 - 2 channel PCM',
    bestFor: ['Contra arcade', 'Konami PCM', 'TMNT'],
    icon: 'Speaker',
    color: 'text-red-400',
  },
  FurnaceK053260: {
    type: 'FurnaceK053260',
    name: 'K053260',
    shortName: 'K053260',
    description: 'Konami K053260 - 4 channel PCM with ADPCM',
    bestFor: ['Sunset Riders', 'Simpsons', 'Konami 90s'],
    icon: 'Speaker',
    color: 'text-orange-400',
  },
  FurnaceGA20: {
    type: 'FurnaceGA20',
    name: 'GA20',
    shortName: 'GA20',
    description: 'Irem GA20 - 4 channel PCM',
    bestFor: ['R-Type Leo', 'Irem arcade', 'In the Hunt'],
    icon: 'Cpu',
    color: 'text-teal-400',
  },
  FurnaceOKI: {
    type: 'FurnaceOKI',
    name: 'OKI MSM6295',
    shortName: 'OKI',
    description: 'OKI MSM6295 - 4 channel ADPCM',
    bestFor: ['Neo Geo', 'Data East', 'ADPCM drums'],
    icon: 'Volume2',
    color: 'text-text-secondary',
  },
  FurnaceYMZ280B: {
    type: 'FurnaceYMZ280B',
    name: 'YMZ280B',
    shortName: 'YMZ280B',
    description: 'Yamaha YMZ280B - 8 channel ADPCM',
    bestFor: ['Cave shmups', 'Late arcade', 'High quality'],
    icon: 'AudioLines',
    color: 'text-indigo-400',
  },
  FurnaceSCC: {
    type: 'FurnaceSCC',
    name: 'Konami SCC',
    shortName: 'SCC',
    description: 'Konami SCC - 5 channel wavetable (MSX)',
    bestFor: ['Gradius', 'Snatcher', 'MSX Konami'],
    icon: 'Waves',
    color: 'text-green-500',
  },
  FurnaceX1_010: {
    type: 'FurnaceX1_010',
    name: 'X1-010',
    shortName: 'X1-010',
    description: 'Seta X1-010 - 16 channel wavetable',
    bestFor: ['Seta arcade', 'Wavetable', 'Twin Eagle'],
    icon: 'Waves',
    color: 'text-lime-400',
  },
  FurnaceBUBBLE: {
    type: 'FurnaceBUBBLE',
    name: 'Bubble System',
    shortName: 'BUBBLE',
    description: 'Konami Bubble System - wavetable',
    bestFor: ['Konami arcade', 'Bubble System', 'Wavetable'],
    icon: 'Circle',
    color: 'text-sky-400',
  },
  FurnaceSM8521: {
    type: 'FurnaceSM8521',
    name: 'SM8521',
    shortName: 'SM8521',
    description: 'Sharp SM8521 - Game.com',
    bestFor: ['Game.com', 'Tiger electronics', 'Obscure'],
    icon: 'Smartphone',
    color: 'text-text-muted',
  },
  FurnaceT6W28: {
    type: 'FurnaceT6W28',
    name: 'T6W28',
    shortName: 'T6W28',
    description: 'NEC T6W28 - PC-6001, stereo PSG',
    bestFor: ['NEC PC-6001', 'Japanese PC', 'Stereo PSG'],
    icon: 'Monitor',
    color: 'text-blue-300',
  },
  FurnaceSUPERVISION: {
    type: 'FurnaceSUPERVISION',
    name: 'Supervision',
    shortName: 'SV',
    description: 'Watara Supervision - 4 channel + noise/DMA',
    bestFor: ['Supervision', 'Portable gaming', 'Watara'],
    icon: 'Gamepad',
    color: 'text-emerald-400',
  },
  FurnaceUPD1771: {
    type: 'FurnaceUPD1771',
    name: 'μPD1771',
    shortName: 'UPD1771',
    description: 'NEC μPD1771 - Epoch Super Cassette Vision',
    bestFor: ['Super Cassette Vision', 'Epoch', 'Japanese'],
    icon: 'Tv',
    color: 'text-stone-400',
  },
  FurnaceOPN2203: {
    type: 'FurnaceOPN2203',
    name: 'YM2203 / OPN',
    shortName: 'OPN',
    description: 'YM2203 - PC-88/98, simpler 3-channel FM + SSG',
    bestFor: ['PC-88 music', 'Japanese PC games', 'Simpler FM'],
    icon: 'Cpu',
    color: 'text-blue-300',
  },
  FurnaceOPNBB: {
    type: 'FurnaceOPNBB',
    name: 'YM2610B',
    shortName: 'OPNB-B',
    description: 'YM2610B - Extended Neo Geo with more FM channels',
    bestFor: ['Neo Geo CD', 'Extended OPNB', 'SNK'],
    icon: 'Gamepad2',
    color: 'text-red-300',
  },
  FurnaceAY8930: {
    type: 'FurnaceAY8930',
    name: 'AY-8930',
    shortName: 'AY+',
    description: 'Enhanced AY-3-8910 with expanded features',
    bestFor: ['Enhanced chiptune', 'Extended AY', 'Microchip'],
    icon: 'Tv',
    color: 'text-sky-400',
  },
  FurnaceNDS: {
    type: 'FurnaceNDS',
    name: 'Nintendo DS',
    shortName: 'NDS',
    description: 'Nintendo DS - 16 channel PCM/PSG',
    bestFor: ['NDS music', 'Portable gaming', 'Modern chiptune'],
    icon: 'Smartphone',
    color: 'text-slate-400',
  },
  FurnaceGBA: {
    type: 'FurnaceGBA',
    name: 'Game Boy Advance',
    shortName: 'GBA',
    description: 'GBA DMA Sound - 2 channel direct PCM',
    bestFor: ['GBA music', 'Portable gaming', 'PCM'],
    icon: 'Gamepad',
    color: 'text-purple-300',
  },
  FurnacePOKEMINI: {
    type: 'FurnacePOKEMINI',
    name: 'Pokemon Mini',
    shortName: 'PKMN',
    description: 'Pokemon Mini - tiny handheld sound',
    bestFor: ['Pokemon Mini', 'Tiny tunes', 'Lo-fi'],
    icon: 'Star',
    color: 'text-yellow-300',
  },
  FurnaceNAMCO: {
    type: 'FurnaceNAMCO',
    name: 'Namco WSG',
    shortName: 'WSG',
    description: 'Namco WSG - Pac-Man, Galaga wavetable',
    bestFor: ['Pac-Man', 'Galaga', 'Classic arcade'],
    icon: 'Circle',
    color: 'text-yellow-400',
  },
  FurnacePET: {
    type: 'FurnacePET',
    name: 'Commodore PET',
    shortName: 'PET',
    description: 'Commodore PET - single voice shift register',
    bestFor: ['PET music', 'Early 80s', 'Primitive'],
    icon: 'Monitor',
    color: 'text-green-300',
  },
  FurnacePOKEY: {
    type: 'FurnacePOKEY',
    name: 'Atari POKEY',
    shortName: 'POKEY',
    description: 'Atari POKEY - Atari 800/5200/arcade',
    bestFor: ['Atari 8-bit', 'Atari arcade', 'Classic chiptune'],
    icon: 'Joystick',
    color: 'text-orange-400',
  },
  FurnaceMSM6258: {
    type: 'FurnaceMSM6258',
    name: 'MSM6258',
    shortName: 'MSM6258',
    description: 'OKI MSM6258 - 4-bit ADPCM voice',
    bestFor: ['Voice samples', 'ADPCM', 'Japanese arcade'],
    icon: 'Mic',
    color: 'text-pink-300',
  },
  FurnaceMSM5232: {
    type: 'FurnaceMSM5232',
    name: 'MSM5232',
    shortName: 'MSM5232',
    description: 'OKI MSM5232 - 8-voice PSG synthesizer',
    bestFor: ['Early arcade', 'Organ sounds', '8-voice'],
    icon: 'Music2',
    color: 'text-amber-300',
  },
  FurnaceMULTIPCM: {
    type: 'FurnaceMULTIPCM',
    name: 'Sega MultiPCM',
    shortName: 'MPCM',
    description: 'Sega MultiPCM - System 32, Model 1/2',
    bestFor: ['Virtua Racing', 'Sega arcade', 'High quality PCM'],
    icon: 'Headphones',
    color: 'text-blue-400',
  },
  FurnaceAMIGA: {
    type: 'FurnaceAMIGA',
    name: 'Amiga Paula',
    shortName: 'PAULA',
    description: 'Amiga Paula - 4 channel 8-bit PCM',
    bestFor: ['Amiga MODs', 'Demoscene', 'Classic samples'],
    icon: 'Disc',
    color: 'text-slate-300',
  },
  FurnacePCSPKR: {
    type: 'FurnacePCSPKR',
    name: 'PC Speaker',
    shortName: 'PCSPK',
    description: 'PC Speaker - internal IBM PC beeper',
    bestFor: ['DOS games', 'Beeper music', 'Lo-fi PC'],
    icon: 'Volume2',
    color: 'text-text-secondary',
  },
  FurnacePONG: {
    type: 'FurnacePONG',
    name: 'AY-3-8500',
    shortName: 'PONG',
    description: 'AY-3-8500 - original Pong chip sound',
    bestFor: ['Pong', 'Retro bleeps', 'Primitive'],
    icon: 'Circle',
    color: 'text-white',
  },
  FurnacePV1000: {
    type: 'FurnacePV1000',
    name: 'Casio PV-1000',
    shortName: 'PV1K',
    description: 'Casio PV-1000 - 3 channel PSG',
    bestFor: ['PV-1000', 'Obscure', 'Japanese'],
    icon: 'Tv',
    color: 'text-green-400',
  },
  FurnaceDAVE: {
    type: 'FurnaceDAVE',
    name: 'Enterprise DAVE',
    shortName: 'DAVE',
    description: 'Enterprise DAVE - 3 channel + noise',
    bestFor: ['Enterprise 64/128', 'Hungarian', 'European'],
    icon: 'Monitor',
    color: 'text-red-300',
  },
  FurnaceSU: {
    type: 'FurnaceSU',
    name: 'Sound Unit',
    shortName: 'SU',
    description: 'Commander X16 Sound Unit',
    bestFor: ['X16 music', 'Modern retro', 'Sound Unit'],
    icon: 'Speaker',
    color: 'text-teal-300',
  },
  FurnacePOWERNOISE: {
    type: 'FurnacePOWERNOISE',
    name: 'Power Noise',
    shortName: 'PNOISE',
    description: 'Power Noise - noise generator chip',
    bestFor: ['Noise music', 'Experimental', 'Harsh sounds'],
    icon: 'Zap',
    color: 'text-violet-400',
  },
  FurnaceZXBEEPER: {
    type: 'FurnaceZXBEEPER',
    name: 'ZX Beeper',
    shortName: 'BEEP',
    description: 'ZX Spectrum beeper - 1-bit audio',
    bestFor: ['ZX Spectrum', 'Beeper music', '1-bit audio'],
    icon: 'Speaker',
    color: 'text-accent-highlight',
  },
  FurnaceSCVTONE: {
    type: 'FurnaceSCVTONE',
    name: 'SCV Tone',
    shortName: 'SCV',
    description: 'Epoch SCV tone generator',
    bestFor: ['Super Cassette Vision', 'Epoch', 'Japanese'],
    icon: 'Tv',
    color: 'text-stone-300',
  },
  FurnacePCMDAC: {
    type: 'FurnacePCMDAC',
    name: 'PCM DAC',
    shortName: 'DAC',
    description: 'Generic PCM DAC output',
    bestFor: ['PCM output', 'Generic DAC', 'Simple samples'],
    icon: 'AudioLines',
    color: 'text-text-secondary',
  },
};
