import type { SynthInfo } from './types';

export const mameSynthEntries: Record<string, SynthInfo> = {
  MAMEVFX: {
    type: 'MAMEVFX',
    name: 'Ensoniq VFX',
    shortName: 'VFX',
    description: 'Ensoniq ES5506 (OTTO) 32-voice wavetable synthesis',
    bestFor: ['Evolving pads', '90s digital', 'Cinematic', 'Layers'],
    icon: 'AudioLines',
    color: 'text-pink-400',
  },
  MAMEDOC: {
    type: 'MAMEDOC',
    name: 'Ensoniq ESQ-1',
    shortName: 'DOC',
    description: 'Ensoniq ES5503 (DOC) 8-bit wavetable synthesis',
    bestFor: ['Lo-fi digital', 'ESQ-1 pads', 'Gritty bass', '80s digital'],
    icon: 'Waves',
    color: 'text-amber-400',
  },
  MAMERSA: {
    type: 'MAMERSA',
    name: 'Roland SA',
    shortName: 'MKS20',
    description: 'Roland Structured Adaptive Synthesis (MKS-20/RD-1000)',
    bestFor: ['Electric piano', 'Authentic piano', '80s keys'],
    icon: 'Piano',
    color: 'text-sky-400',
  },
  MAMESWP30: {
    type: 'MAMESWP30',
    name: 'Yamaha SWP30',
    shortName: 'AWM2',
    description: 'Yamaha SWP30 (AWM2) 64-voice ROMpler/DSP engine',
    bestFor: ['Realistic instruments', '90s ROMpler', 'Advanced effects', 'AWM2 sounds'],
    icon: 'Cpu',
    color: 'text-emerald-400',
  },
  CZ101: {
    type: 'CZ101',
    name: 'Casio CZ-101',
    shortName: 'CZ',
    description: 'Casio Phase Distortion synthesis - 8 voices, dual oscillator with DCO/DCW/DCA envelopes',
    bestFor: ['Digital bass', 'Metallic leads', 'Synth brass', '80s digital', 'Phase distortion'],
    icon: 'Activity',
    color: 'text-violet-400',
  },
  CEM3394: {
    type: 'CEM3394',
    name: 'CEM3394 (Curtis)',
    shortName: 'CEM',
    description: 'Curtis Electromusic analog synth voice - used in Prophet VS, Matrix-6, ESQ-1, Six-Trak',
    bestFor: ['Analog bass', 'Warm pads', 'Classic leads', '80s analog', 'Prophet sounds'],
    icon: 'Waves',
    color: 'text-emerald-400',
  },
  SCSP: {
    type: 'SCSP',
    name: 'Sega Saturn SCSP',
    shortName: 'SCSP',
    description: 'Yamaha YMF292-F 32-voice sound processor - Sega Saturn, Model 2/3 arcade',
    bestFor: ['Arcade sounds', '90s gaming', 'Saturn pads', 'Virtua sounds', 'Sega classics'],
    icon: 'Gamepad2',
    color: 'text-blue-500',
  },
  MAMEASC: {
    type: 'MAMEASC',
    name: 'Apple Sound Chip',
    shortName: 'ASC',
    description: 'Apple ASC - 4-voice wavetable synthesis from Apple IIGS and Mac',
    bestFor: ['Retro Mac', 'Wavetable', 'IIGS sounds', '80s digital'],
    icon: 'Cpu',
    color: 'text-text-secondary',
  },
  MAMEAstrocade: {
    type: 'MAMEAstrocade',
    name: 'Bally Astrocade',
    shortName: 'Astro',
    description: 'Bally Astrocade custom sound - 3 voices + noise, vibrato modulation',
    bestFor: ['Retro arcade', 'Lo-fi', 'Noise FX', 'Vintage gaming'],
    icon: 'Gamepad2',
    color: 'text-purple-400',
  },
  MAMEC352: {
    type: 'MAMEC352',
    name: 'Namco C352',
    shortName: 'C352',
    description: 'Namco System 22/23 - 32-voice PCM with built-in effects (needs ROM)',
    bestFor: ['Namco arcade', 'Ridge Racer', 'Tekken sounds', 'Arcade PCM'],
    icon: 'Gamepad2',
    color: 'text-red-400',
  },
  MAMEES5503: {
    type: 'MAMEES5503',
    name: 'Ensoniq ES5503',
    shortName: 'ES5503',
    description: 'Ensoniq DOC - 32-oscillator wavetable chip (Apple IIGS, ESQ-1, Mirage)',
    bestFor: ['Wavetable', 'Lo-fi digital', '80s synth', 'IIGS music'],
    icon: 'Waves',
    color: 'text-amber-400',
  },
  MAMEICS2115: {
    type: 'MAMEICS2115',
    name: 'ICS WaveFront',
    shortName: 'ICS',
    description: 'ICS 2115 WaveFront - 32-voice wavetable with interpolation (needs ROM)',
    bestFor: ['Wavetable', '90s soundcard', 'GUS compatible', 'Tracker music'],
    icon: 'Cpu',
    color: 'text-teal-400',
  },
  MAMEK054539: {
    type: 'MAMEK054539',
    name: 'Konami K054539',
    shortName: 'K054',
    description: 'Konami 054539 - 8-channel PCM for Konami arcade (needs ROM)',
    bestFor: ['Konami arcade', 'TMNT', 'Gradius', 'Arcade samples'],
    icon: 'Gamepad2',
    color: 'text-yellow-400',
  },
  MAMEMEA8000: {
    type: 'MAMEMEA8000',
    name: 'Philips MEA8000',
    shortName: 'MEA',
    description: 'Philips MEA8000 - LPC speech synthesis with formant modeling',
    bestFor: ['Speech', 'Robotic voice', 'Retro talking', 'Voice FX'],
    icon: 'Mic',
    color: 'text-green-400',
  },
  MAMEMSM5232: {
    type: 'MAMEMSM5232',
    name: 'OKI MSM5232',
    shortName: 'MSM',
    description: 'OKI MSM5232 - 8-voice PSG organ/synth chip (MAME native emulation)',
    bestFor: ['Organ', 'Arcade melody', 'Retro synth', 'Simple tones'],
    icon: 'Cpu',
    color: 'text-orange-400',
  },
  MAMERF5C400: {
    type: 'MAMERF5C400',
    name: 'Ricoh RF5C400',
    shortName: 'RF5C',
    description: 'Ricoh RF5C400 - 32-voice PCM with digital filtering (needs ROM)',
    bestFor: ['Seta arcade', 'PCM playback', 'Arcade samples'],
    icon: 'Cpu',
    color: 'text-indigo-400',
  },
  MAMESN76477: {
    type: 'MAMESN76477',
    name: 'TI SN76477',
    shortName: 'SN77',
    description: 'TI SN76477 Complex Sound Generator - VCO, noise, envelope, mixer',
    bestFor: ['Sci-fi FX', 'Laser sounds', 'Space Invaders', 'Retro arcade FX'],
    icon: 'Zap',
    color: 'text-green-500',
  },
  MAMESNKWave: {
    type: 'MAMESNKWave',
    name: 'SNK Wave',
    shortName: 'SNK',
    description: 'SNK custom wavetable sound generator - Neo Geo era',
    bestFor: ['Retro arcade', 'Wavetable', 'SNK sounds', 'Lo-fi'],
    icon: 'Gamepad2',
    color: 'text-red-500',
  },
  MAMESP0250: {
    type: 'MAMESP0250',
    name: 'GI SP0250',
    shortName: 'SP02',
    description: 'General Instrument SP0250 - LPC speech synthesis for arcade machines',
    bestFor: ['Arcade speech', 'Robotic voice', 'Q*bert sounds', 'Retro talking'],
    icon: 'Mic',
    color: 'text-yellow-500',
  },
  MAMETIA: {
    type: 'MAMETIA',
    name: 'Atari TIA (MAME)',
    shortName: 'TIA',
    description: 'Atari 2600 TIA - MAME-accurate 2-voice with 16 distortion modes',
    bestFor: ['Atari sounds', '2600 bleeps', 'Lo-fi', 'Retro FX'],
    icon: 'Gamepad2',
    color: 'text-amber-500',
  },
  MAMETMS36XX: {
    type: 'MAMETMS36XX',
    name: 'TMS36XX Organ',
    shortName: 'TMS3',
    description: 'TI TMS3615/3617 - electronic organ chip with 13 chromatic notes',
    bestFor: ['Electronic organ', 'Retro tones', 'Circus music', 'Simple melody'],
    icon: 'Music2',
    color: 'text-rose-400',
  },
  MAMETMS5220: {
    type: 'MAMETMS5220',
    name: 'Speak & Spell',
    shortName: 'TMS5',
    description: 'TI TMS5220 LPC speech - the Speak & Spell chip, phoneme-based voice',
    bestFor: ['Speech', 'Speak & Spell', 'Robotic voice', 'LPC vocoder'],
    icon: 'Mic',
    color: 'text-orange-500',
  },
  MAMETR707: {
    type: 'MAMETR707',
    name: 'Roland TR-707',
    shortName: '707',
    description: 'Roland TR-707 PCM drum machine - 10 voices with analog filtering (needs ROM)',
    bestFor: ['House drums', 'Electro beats', '80s rhythm', 'Classic drum machine'],
    icon: 'Disc',
    color: 'text-red-400',
  },
  MAMEUPD931: {
    type: 'MAMEUPD931',
    name: 'NEC uPD931',
    shortName: '931',
    description: 'NEC uPD931 - dual waveform keyboard synthesizer (Casio)',
    bestFor: ['Casio keys', 'Retro organ', 'Dual waveform', 'Keyboard'],
    icon: 'Piano',
    color: 'text-accent-highlight',
  },
  MAMEUPD933: {
    type: 'MAMEUPD933',
    name: 'NEC uPD933',
    shortName: '933',
    description: 'NEC uPD933 raw phase distortion chip - the core of the Casio CZ series',
    bestFor: ['Phase distortion', 'CZ sounds', 'Digital bass', 'Metallic leads'],
    icon: 'Activity',
    color: 'text-violet-400',
  },
  MAMEVotrax: {
    type: 'MAMEVotrax',
    name: 'Votrax SC-01',
    shortName: 'Vtrx',
    description: 'Votrax SC-01 - classic 1980s phoneme speech synthesizer chip',
    bestFor: ['Robotic speech', 'Arcade talking', 'Q*bert', 'Retro voice'],
    icon: 'Mic',
    color: 'text-emerald-400',
  },
  MAMEYMF271: {
    type: 'MAMEYMF271',
    name: 'Yamaha OPX',
    shortName: 'OPX',
    description: 'Yamaha YMF271 OPX - 12-voice FM+PCM synthesis for arcade hardware',
    bestFor: ['Arcade FM', 'FM+PCM', 'Jaleco sounds', 'Complex FM'],
    icon: 'Radio',
    color: 'text-blue-500',
  },
  MAMEYMOPQ: {
    type: 'MAMEYMOPQ',
    name: 'Yamaha OPQ',
    shortName: 'OPQ',
    description: 'Yamaha YM3806 OPQ - 4-op FM synthesis for Yamaha keyboards',
    bestFor: ['FM synthesis', 'Yamaha sounds', 'Vintage FM', 'Keyboard sounds'],
    icon: 'Radio',
    color: 'text-indigo-500',
  },
  MAMECMI: {
    type: 'MAMECMI',
    name: 'Fairlight CMI IIx',
    shortName: 'CMI',
    description: 'Fairlight CMI IIx 8-voice sampling synthesizer (1982) - iconic 80s orchestral sampler',
    bestFor: ['Orchestral', '80s pop', 'Sampling', 'Vintage digital', 'Cinematic'],
    icon: 'Cpu',
    color: 'text-yellow-400',
  },
  MAMEVASynth: {
    type: 'MAMEVASynth',
    name: 'Virtual Analog',
    shortName: 'VA',
    description: 'Virtual Analog modeling synthesizer - subtractive with multi-waveform oscillators',
    bestFor: ['Analog modeling', 'Bass', 'Leads', 'Pads', 'Classic analog'],
    icon: 'Waves',
    color: 'text-pink-500',
  },
  VFX: {
    type: 'VFX',
    name: 'Ensoniq VFX (alias)',
    shortName: 'VFX',
    description: 'Ensoniq VFX transwave synthesizer - alias for MAMEVFX',
    bestFor: ['Transwave', 'Digital', 'Pads', 'Textures'],
    icon: 'Cpu',
    color: 'text-accent-highlight',
  },
  D50: {
    type: 'D50',
    name: 'Roland D-50',
    shortName: 'D-50',
    description: 'Roland D-50 virtual analog synthesizer',
    bestFor: ['Digital', 'Pads', 'Strings', 'Vintage digital'],
    icon: 'Cpu',
    color: 'text-rose-500',
  },
  MAMEFZPCM: {
    type: 'MAMEFZPCM',
    name: 'Casio FZ PCM',
    shortName: 'FZ-PCM',
    description: 'Casio FZ-1 (1987) 8-voice 16-bit PCM sampler - professional sampling with 2MB wave RAM',
    bestFor: ['Sampling', 'PCM', 'Vintage digital', '80s sampler'],
    icon: 'Cpu',
    color: 'text-cyan-400',
  },
  MAMEPS1SPU: {
    type: 'MAMEPS1SPU',
    name: 'PlayStation SPU',
    shortName: 'PS1-SPU',
    description: 'PlayStation 1 CXD2922BQ SPU (1994) 24-voice ADPCM sampler with ADSR envelopes',
    bestFor: ['Game audio', 'ADPCM', 'Retro gaming', '90s sampling'],
    icon: 'Cpu',
    color: 'text-blue-400',
  },
  MAMEZSG2: {
    type: 'MAMEZSG2',
    name: 'ZOOM ZSG-2',
    shortName: 'ZSG-2',
    description: 'ZOOM ZSG-2 48-channel ROM sampler with proprietary ADPCM and IIR filter',
    bestFor: ['Effects', 'Guitar processing', 'ROM sampling', 'Multi-channel'],
    icon: 'Cpu',
    color: 'text-green-400',
  },
  MAMEKS0164: {
    type: 'MAMEKS0164',
    name: 'Samsung KS0164',
    shortName: 'KS0164',
    description: 'Samsung KS0164 32-voice wavetable GM synthesizer with 8-bit decode table',
    bestFor: ['GM synthesis', 'Wavetable', 'ROM sampling', 'General MIDI'],
    icon: 'Cpu',
    color: 'text-indigo-400',
  },
  MAMESWP00: {
    type: 'MAMESWP00',
    name: 'Yamaha SWP00',
    shortName: 'SWP00',
    description: 'Yamaha SWP00 AWM2 32-voice ROMpler (MU50) with Chamberlin filter and LFO',
    bestFor: ['XG synthesis', 'AWM2', 'Chamberlin filter', 'Yamaha XG'],
    icon: 'Cpu',
    color: 'text-purple-400',
  },
  MAMESWP20: {
    type: 'MAMESWP20',
    name: 'Yamaha SWP20',
    shortName: 'SWP20',
    description: 'Yamaha SWP20 AWM2 32-voice ROMpler (MU50/MU80) - approximated from SWP00/SWP30 family',
    bestFor: ['XG synthesis', 'AWM2', 'ROM streaming', 'Yamaha XG'],
    icon: 'Cpu',
    color: 'text-violet-400',
  },
  MAMERolandGP: {
    type: 'MAMERolandGP',
    name: 'Roland GP',
    shortName: 'GP-TC6116',
    description: 'Roland TC6116 PCM 28-channel chip (SC-88/JV-series) with dual volume envelopes and filter',
    bestFor: ['Roland GS', 'PCM', 'SC-88 sound', 'General MIDI'],
    icon: 'Cpu',
    color: 'text-red-400',
  },
  MAMEMultiPCM: {
    type: 'MAMEMultiPCM',
    name: 'MultiPCM',
    shortName: 'YMW258-F',
    description: 'Yamaha YMW258-F MultiPCM 28-channel PCM chip (Sega Model 1/2 arcade)',
    bestFor: ['Sega arcade', 'PCM', 'Model 1', 'Model 2'],
    icon: 'Cpu',
    color: 'text-yellow-400',
  },
  MAMES14001A: {
    type: 'MAMES14001A',
    name: 'Berzerk S14001A',
    shortName: 'S140',
    description: 'SSi TSI S14001A — Berzerk (1980) delta modulation speech',
    bestFor: ['Berzerk speech', 'Robotic voice', 'Delta modulation', 'Retro arcade'],
    icon: 'Mic',
    color: 'text-red-500',
  },
  MAMEVLM5030: {
    type: 'MAMEVLM5030',
    name: 'Track & Field VLM5030',
    shortName: 'VLM',
    description: 'Sanyo VLM5030 — Track & Field (1983) LPC speech synthesis',
    bestFor: ['Konami speech', 'Arcade voice', 'LPC synthesis', 'Track & Field'],
    icon: 'Mic',
    color: 'text-blue-400',
  },
  MAMEHC55516: {
    type: 'MAMEHC55516',
    name: 'Sinistar HC55516',
    shortName: 'CVSD',
    description: 'Harris HC55516 CVSD — Sinistar (1982) arcade speech codec',
    bestFor: ['Williams speech', 'CVSD voice', 'Sinistar', 'Pinball sounds'],
    icon: 'Mic',
    color: 'text-purple-500',
  },
};
