import type { SynthInfo } from './types';

export const percussionSynthEntries: Record<string, SynthInfo> = {
  MembraneSynth: {
    type: 'MembraneSynth',
    name: 'Membrane Synth',
    shortName: 'Membrane',
    description: 'Drum membrane simulation for kicks and toms',
    bestFor: ['Kick drums', 'Toms', 'Percussion'],
    icon: 'Circle',
    color: 'text-orange-400',
  },
  MetalSynth: {
    type: 'MetalSynth',
    name: 'Metal Synth',
    shortName: 'Metal',
    description: 'Metallic percussion synthesis with harmonics',
    bestFor: ['Hi-hats', 'Cymbals', 'Bells', 'Metallic hits'],
    icon: 'Hexagon',
    color: 'text-yellow-400',
  },
  NoiseSynth: {
    type: 'NoiseSynth',
    name: 'Noise Synth',
    shortName: 'Noise',
    description: 'Filtered noise generator with envelope',
    bestFor: ['Snares', 'Hi-hats', 'Risers', 'FX'],
    icon: 'Hash',
    color: 'text-text-secondary',
  },
  TR808: {
    type: 'TR808',
    name: 'Roland TR-808',
    shortName: 'TR-808',
    description: '1:1 circuit-modeled TR-808 — pure Web Audio synthesis (port of io-808)',
    bestFor: ['808 kicks', '808 snares', '808 hats', 'Cowbell', 'Claves'],
    icon: 'Disc',
    color: 'text-red-500',
  },
  TR909: {
    type: 'TR909',
    name: 'Roland TR-909',
    shortName: 'TR-909',
    description: 'Hybrid sample/synthesis TR-909 — PCM samples + pitch/decay control (port of tr-909)',
    bestFor: ['909 kicks', '909 snares', 'Toms', 'Ride', 'Crash'],
    icon: 'Disc',
    color: 'text-orange-500',
  },
  DrumMachine: {
    type: 'DrumMachine',
    name: 'Drum Machine (Legacy)',
    shortName: 'Legacy',
    description: 'Basic Tone.js drum approximation (use TR-808 or TR-909 instead)',
    bestFor: ['Simple drums'],
    icon: 'Disc',
    color: 'text-gray-500',
  },
  DrumKit: {
    type: 'DrumKit',
    name: 'Drum Kit',
    shortName: 'Kit',
    description: 'Multi-sample instrument with keymap - assign different samples to different notes',
    bestFor: ['Drum kits', 'Instrument layers', 'Velocity splits', 'Sample mapping'],
    icon: 'Piano',
    color: 'text-amber-500',
  },
  Synare: {
    type: 'Synare',
    name: 'Synare 3',
    shortName: 'Synare',
    description: 'Classic electronic percussion synthesizer for "disco tom" and dub sounds',
    bestFor: ['Dub percussion', 'Disco toms', 'Electronic drums', 'SFX'],
    icon: 'Drum',
    color: 'text-yellow-500',
  },
  Geonkick: {
    type: 'Geonkick',
    name: 'Geonkick',
    shortName: 'Gkick',
    description: 'Quamplex Geonkick percussion synthesizer (WASM port) — multi-oscillator, envelope-driven kick/snare/hat synth',
    bestFor: ['808 kicks', 'Hard kicks', 'Snares', 'Hi-hats', 'Toms', 'Synthetic percussion'],
    icon: 'Drum',
    color: 'text-accent-primary',
  },
};
