import type { SynthInfo } from './types';

export const pluginSynthEntries: Record<string, SynthInfo> = {
  // Demoscene 4k/64k intro synths
  WaveSabreSlaughter: {
    type: 'WaveSabreSynth',
    name: 'WaveSabre Slaughter',
    shortName: 'Slaugh',
    description: 'Demoscene synth from 64k intros - 3 oscillators, multimode filter, distortion, chorus. Used in Logicoma, Conspiracy demos.',
    bestFor: ['Demoscene', '64k intros', 'Aggressive leads', 'Bass', 'Pads'],
    icon: 'Flame',
    color: 'text-red-500',
    defaultConfig: { xrns: { synthType: 'wavesabre-slaughter' } },
  },
  WaveSabreFalcon: {
    type: 'WaveSabreSynth',
    name: 'WaveSabre Falcon',
    shortName: 'Falcon',
    description: 'Demoscene synth from 64k intros - lightweight FM/subtractive hybrid. Used in Logicoma, Conspiracy demos.',
    bestFor: ['Demoscene', '64k intros', 'FM sounds', 'Lightweight'],
    icon: 'Bird',
    color: 'text-orange-400',
    defaultConfig: { xrns: { synthType: 'wavesabre-falcon' } },
  },
  WaveSabreAdultery: {
    type: 'WaveSabreSynth',
    name: 'WaveSabre Adultery',
    shortName: 'Adult',
    description: 'Demoscene GM sampler from 64k intros - plays General MIDI samples from system DLS. Used in Logicoma demos.',
    bestFor: ['Demoscene', '64k intros', 'General MIDI', 'Orchestral'],
    icon: 'Music',
    color: 'text-purple-400',
    defaultConfig: { xrns: { synthType: 'wavesabre-adultery' } },
  },
  OidosSynth: {
    type: 'OidosSynth',
    name: 'Oidos',
    shortName: 'Oidos',
    description: 'Additive synth from Loonies demoscene group - 256 partials, frequency modulation, distortion. Tiny code size for 4k/8k intros.',
    bestFor: ['Demoscene', '4k intros', 'Additive synthesis', 'Rich pads', 'Complex timbres'],
    icon: 'Sparkles',
    color: 'text-accent-highlight',
  },
  TunefishSynth: {
    type: 'TunefishSynth',
    name: 'Tunefish 4',
    shortName: 'TF4',
    description: 'Additive/subtractive synth from Brain Control - 2 oscillators, bandpass array, noise, modulation matrix. Used in demoscene.',
    bestFor: ['Demoscene', '64k intros', 'Versatile', 'Pads', 'Leads', 'Bass'],
    icon: 'Fish',
    color: 'text-teal-400',
  },
  WAM: {
    type: 'WAM',
    name: 'Web Audio Module',
    shortName: 'WAM',
    description: 'Load external audio plugins from URL (standard WAM 2.0 format)',
    bestFor: ['External plugins', 'Community synths', 'Rich UI'],
    icon: 'Globe',
    color: 'text-accent-highlight',
  },
  WAMOBXd: {
    type: 'WAMOBXd',
    name: 'OB-Xd (WAM)',
    shortName: 'OBXd-W',
    description: 'Oberheim OB-X virtual analog synth via WAM 2.0',
    bestFor: ['Analog pads', 'Warm leads', 'Classic analog', 'Rich UI'],
    icon: 'Waves',
    color: 'text-amber-400',
  },
  WAMSynth101: {
    type: 'WAMSynth101',
    name: 'Synth-101 (WAM)',
    shortName: 'SH101',
    description: 'Roland SH-101 monophonic synthesizer via WAM 2.0',
    bestFor: ['Mono bass', 'Acid lines', 'Classic mono', 'Rich UI'],
    icon: 'AudioLines',
    color: 'text-blue-400',
  },
  WAMTinySynth: {
    type: 'WAMTinySynth',
    name: 'TinySynth (WAM)',
    shortName: 'Tiny',
    description: 'GM-mapped multi-timbral synth via WAM 2.0',
    bestFor: ['General MIDI', 'Multi-timbral', 'Quick patches', 'Rich UI'],
    icon: 'Music2',
    color: 'text-green-400',
  },
  WAMFaustFlute: {
    type: 'WAMFaustFlute',
    name: 'Faust Flute (WAM)',
    shortName: 'Flute',
    description: 'Physical modelling flute via Faust DSP and WAM 2.0',
    bestFor: ['Physical model', 'Wind instruments', 'Expressive', 'Rich UI'],
    icon: 'Wind',
    color: 'text-sky-400',
  },
  MdaEPiano: {
    type: 'MdaEPiano',
    name: 'MDA ePiano (Rhodes)',
    shortName: 'ePiano',
    description: 'Fender Rhodes electric piano — 32-voice polyphonic sample-based with tremolo, autopan, overdrive',
    bestFor: ['Electric Piano', 'Rhodes', 'Keys', 'Soul', 'Jazz', 'Lo-fi'],
    icon: 'Piano',
    color: 'text-orange-400',
  },
  MdaJX10: {
    type: 'MdaJX10',
    name: 'MDA JX-10 (Poly Synth)',
    shortName: 'JX-10',
    description: 'Roland JX-8P inspired dual-oscillator poly synth — 8 voices, state-variable filter, glide, 64 presets',
    bestFor: ['Pads', 'Leads', 'Strings', 'Poly Synth', 'Analog', 'Sweep'],
    icon: 'Waves',
    color: 'text-blue-400',
  },
  MdaDX10: {
    type: 'MdaDX10',
    name: 'MDA DX10 (FM Synth)',
    shortName: 'DX10',
    description: '2-operator FM synth — 8 voices, carrier/modulator with independent envelopes, 32 presets',
    bestFor: ['Electric Piano', 'Bass', 'Bells', 'FM', 'Percussion', 'Leads'],
    icon: 'Zap',
    color: 'text-yellow-400',
  },
  ToneAM: {
    type: 'ToneAM',
    name: 'Tone AM Synth',
    shortName: 'ToneAM',
    description: 'Dual-oscillator subtractive synth — multi-mode filter, dual ADSR, LFO, distortion, reverb, 41 params',
    bestFor: ['Bass', 'Leads', 'Pads', 'Analog', 'Subtractive'],
    icon: 'Waves',
    color: 'text-green-400',
  },
  RaffoSynth: {
    type: 'RaffoSynth',
    name: 'Raffo (Minimoog)',
    shortName: 'Minimoog',
    description: 'Minimoog clone — 4 oscillators, monophonic with legato, IIR filter, glide, dual ADSR',
    bestFor: ['Bass', 'Leads', 'Mono', 'Minimoog', 'Classic Analog'],
    icon: 'Music',
    color: 'text-amber-500',
  },
  CalfMono: {
    type: 'CalfMono',
    name: 'Calf Monosynth',
    shortName: 'CalfMono',
    description: '2-oscillator mono subtractive synth — 16 waveforms, dual ADSR with fade, multi-mode filter, 2 LFOs, unison',
    bestFor: ['Bass', 'Leads', 'Mono', 'Acid', 'Subtractive'],
    icon: 'Music',
    color: 'text-cyan-400',
  },
  SetBfree: {
    type: 'SetBfree',
    name: 'setBfree (Hammond B3)',
    shortName: 'B3 Organ',
    description: 'Tonewheel organ emulator — 3 manuals with 9 drawbars each, percussion, vibrato/chorus scanner, Leslie speaker, overdrive, reverb',
    bestFor: ['Organ', 'Gospel', 'Jazz', 'Rock', 'Blues', 'Hammond', 'Leslie'],
    icon: 'Music',
    color: 'text-yellow-500',
  },
  SynthV1: {
    type: 'SynthV1',
    name: 'SynthV1 (4-Osc Poly)',
    shortName: 'SynthV1',
    description: 'Dual-page 4-oscillator polyphonic subtractive — DCO/DCF/DCA/LFO × 2 pages, chorus/flanger/phaser/delay/reverb',
    bestFor: ['Pads', 'Strings', 'Poly', 'Subtractive', 'Old-school'],
    icon: 'Music',
    color: 'text-indigo-400',
  },
  TalNoizeMaker: {
    type: 'TalNoizeMaker',
    name: 'TAL-NoiseMaker',
    shortName: 'TAL-NM',
    description: 'Virtual analog synth — 3 oscillators, multi-mode filter, 2 LFOs, chorus/reverb/delay, bitcrusher, unison',
    bestFor: ['Bass', 'Leads', 'VA', 'Acid', 'Lo-Fi', 'Unison'],
    icon: 'Music',
    color: 'text-pink-400',
  },
  Aeolus: {
    type: 'Aeolus',
    name: 'Aeolus (Pipe Organ)',
    shortName: 'Aeolus',
    description: 'Pipe organ emulator — multiple divisions (Great/Swell/Pedal), stops, tremulant, couplers, reverb',
    bestFor: ['Organ', 'Church', 'Classical', 'Pipe Organ', 'Baroque'],
    icon: 'Music',
    color: 'text-stone-400',
  },
  FluidSynth: {
    type: 'FluidSynth',
    name: 'FluidSynth (SF2)',
    shortName: 'SF2',
    description: 'SoundFont SF2 sample player — GM/GS instruments, reverb, chorus, multi-timbral',
    bestFor: ['General MIDI', 'Piano', 'Strings', 'SoundFont', 'Orchestral'],
    icon: 'Music',
    color: 'text-blue-400',
  },
  Sfizz: {
    type: 'Sfizz',
    name: 'Sfizz (SFZ)',
    shortName: 'SFZ',
    description: 'SFZ format sample player — high-fidelity sample playback with SFZ scripting, velocity layers, round-robins',
    bestFor: ['Samples', 'SFZ', 'Orchestral', 'Drums', 'Realistic'],
    icon: 'Music',
    color: 'text-teal-400',
  },
  ZynAddSubFX: {
    type: 'ZynAddSubFX',
    name: 'ZynAddSubFX',
    shortName: 'ZynAdd',
    description: 'Mega-synth with ADDsynth (additive), SUBsynth (subtractive), PADsynth (wavetable) engines + 8 effects',
    bestFor: ['Pads', 'Bass', 'Leads', 'Additive', 'Subtractive', 'Wavetable', 'Experimental'],
    icon: 'Music',
    color: 'text-violet-500',
  },
  Vital: {
    type: 'Vital',
    name: 'Vital (Wavetable)',
    shortName: 'Vital',
    description: 'Spectral warping wavetable synthesizer - 3 oscillators with spectral morphing, 13 morph types, phase distortion',
    bestFor: ['Wavetable', 'Spectral', 'Modern bass', 'Pads', 'Leads', 'Sound design'],
    icon: 'Waves',
    color: 'text-violet-400',
  },
  Odin2: {
    type: 'Odin2',
    name: 'Odin2 (Hybrid)',
    shortName: 'Odin2',
    description: 'Semi-modular hybrid synth - 11 oscillator types (analog, wavetable, FM, vector, chiptune), 9 filter types, modulation matrix',
    bestFor: ['Hybrid synthesis', 'Analog', 'Wavetable', 'FM', 'Vector', 'Chiptune'],
    icon: 'Zap',
    color: 'text-emerald-400',
  },
  Surge: {
    type: 'Surge',
    name: 'Surge XT (Hybrid)',
    shortName: 'Surge',
    description: 'Professional hybrid synth - dual scenes, 12 oscillator types, 32 effect types, 765 parameters, open source since 2018',
    bestFor: ['Professional', 'Hybrid', 'Sound design', 'Bass', 'Pads', 'Leads', 'FX'],
    icon: 'Activity',
    color: 'text-accent-highlight',
  },
  TonewheelOrgan: {
    type: 'TonewheelOrgan',
    name: 'Tonewheel Organ',
    shortName: 'Organ',
    description: 'Hammond-style tonewheel organ - 9 drawbars, key click, percussion, vibrato/chorus scanner, overdrive',
    bestFor: ['Reggae organ', 'Gospel', 'Jazz', 'Blues', 'Rock organ', 'Ska'],
    icon: 'Music',
    color: 'text-amber-400',
  },
  Melodica: {
    type: 'Melodica',
    name: 'Melodica',
    shortName: 'Melod',
    description: 'Monophonic reed instrument physical model - breath dynamics, body resonance, vibrato, portamento',
    bestFor: ['Reggae melodica', 'Dub', 'Ska', 'Augustus Pablo', 'Lead melodies'],
    icon: 'Wind',
    color: 'text-teal-400',
  },
  Monique: {
    type: 'Monique',
    name: 'Monique (Monosynth)',
    shortName: 'Monique',
    description: 'Morphing monosynth - 3 morphable oscillators, 3 cross-routed filters, 4 tempo-synced MFOs, arpeggiator',
    bestFor: ['Mono bass', 'Acid', 'Leads', 'Sound design', 'Morphing'],
    icon: 'Sparkles',
    color: 'text-fuchsia-400',
  },
  VL1: {
    type: 'VL1',
    name: 'Casio VL-Tone',
    shortName: 'VL-1',
    description: 'Casio VL-1 emulation - 10 wavetable sounds, authentic ADSR envelopes, vibrato/tremolo, 10 built-in rhythm patterns',
    bestFor: ['Lo-fi', 'Retro', 'Chiptune', 'Novelty', 'Rhythm'],
    icon: 'Music',
    color: 'text-amber-400',
  },
  Helm: {
    type: 'Helm',
    name: 'Helm (Polyphonic)',
    shortName: 'Helm',
    description: 'Polyphonic synth by Matt Tytel - 2 oscillators, sub, 2 filters, 2 LFOs, 2 step sequencers, effects',
    bestFor: ['Modern leads', 'Bass', 'Pads', 'Keys', 'EDM'],
    icon: 'Waves',
    color: 'text-accent-highlight',
  },
  Sorcer: {
    type: 'Sorcer',
    name: 'Sorcer (Wavetable)',
    shortName: 'Sorcer',
    description: 'FAUST-based wavetable synth by OpenAV - wavetable oscillator, Butterworth filter, compressor, LFO',
    bestFor: ['Wavetable', 'EDM', 'Pads', 'Sound design'],
    icon: 'Sparkles',
    color: 'text-purple-500',
  },
  Amsynth: {
    type: 'Amsynth',
    name: 'amsynth (Analog)',
    shortName: 'amsynth',
    description: 'Classic analog modeling by Nick Dowell - 2 oscillators, filter, 2 envelopes, LFO, Freeverb, distortion',
    bestFor: ['Analog bass', 'Vintage leads', 'Pads', 'Retro sounds'],
    icon: 'Radio',
    color: 'text-orange-400',
  },
  OBXf: {
    type: 'OBXf',
    name: 'OB-Xf (Analog)',
    shortName: 'OB-Xf',
    description: 'Oberheim OB-X/OB-Xa modeling by Surge Synth Team - 2 oscillators, multimode filter, 2 LFOs, voice variation',
    bestFor: ['Oberheim brass', 'Vintage strings', 'Analog bass', 'Classic pads'],
    icon: 'Speaker',
    color: 'text-indigo-500',
  },
  SunVoxSynth: {
    type: 'SunVoxSynth',
    name: 'SunVox',
    shortName: 'SVX',
    description: 'SunVox WASM modular synth patch player (.sunsynth / .sunvox)',
    bestFor: ['Modular synth', 'SunVox patches', 'Complex synthesis'],
    icon: 'Sun',
    color: 'text-yellow-400',
  },
  SunVoxModular: {
    type: 'SunVoxModular',
    name: 'SunVox Modular',
    shortName: 'SVM',
    description: 'Visual modular editor with 41 SunVox module types — build patches with patch cables',
    bestFor: ['Modular synth', 'Sound design', 'Complex patches', 'Subtractive', 'FM'],
    icon: 'Sun',
    color: 'text-yellow-500',
  },
  SuperCollider: {
    type: 'SuperCollider',
    name: 'SuperCollider',
    shortName: 'SC',
    description: 'SuperCollider SynthDef scripted synthesis via scsynth WASM',
    bestFor: ['Algorithmic composition', 'Live coding', 'Experimental'],
    icon: 'Code2',
    color: 'text-lime-400',
  },
  // Retromulator WASM synths
  OpenWurli: {
    type: 'OpenWurli',
    name: 'Wurlitzer 200A',
    shortName: 'Wurli',
    description: 'Wurlitzer 200A electric piano emulation — authentic reed vibration, tremolo, speaker character modeling',
    bestFor: ['Electric Piano', 'Wurlitzer', 'Keys', 'Vintage', 'Soul'],
    icon: 'Piano',
    color: 'text-amber-500',
  },
  OPL3: {
    type: 'OPL3',
    name: 'OPL3 (YMF262)',
    shortName: 'OPL3',
    description: 'Yamaha YMF262 OPL3 FM synthesis — 2-operator FM with 8 waveforms, Nuked OPL3 cycle-accurate emulation',
    bestFor: ['FM', 'Retro PC', 'AdLib', 'Sound Blaster', 'DOS games'],
    icon: 'Cpu',
    color: 'text-cyan-400',
  },
  DX7: {
    type: 'DX7',
    name: 'DX7 (VDX7)',
    shortName: 'VDX7',
    description: 'Cycle-accurate Yamaha DX7 emulation — HD6303R CPU + EGS/OPS chips, 1120 factory patches from 35 sysex banks',
    bestFor: ['FM', 'Electric Piano', 'Bass', 'Bells', 'Brass', 'Classic DX7'],
    icon: 'Piano',
    color: 'text-blue-500',
  },
  Kontakt: {
    type: 'Kontakt',
    name: 'Kontakt (Bridge)',
    shortName: 'Kontakt',
    description: 'NI Kontakt instrument loaded via bridge — MIDI routed to external Kontakt instance',
    bestFor: ['External instruments', 'NKS presets', 'Sample libraries'],
    icon: 'ExternalLink',
    color: 'text-sky-400',
  },
};
