import type { SynthInfo } from './types';

export const pluginSynthEntries: Record<string, SynthInfo> = {
  // Demoscene 4k/64k intro synths
  WaveSabreSlaughter: {
    type: 'WaveSabreSynth',
    name: 'WaveSabre Slaughter',
    shortName: 'Slaugh',
    description: 'Demoscene synth from 64k intros - 3 oscillators, multimode filter, distortion, chorus. Used in Logicoma, Conspiracy demos.',
    bestFor: ['Demoscene', '64k intros', 'Aggressive leads', 'Bass', 'Pads'],
    icon: 'Flame',
    color: 'text-red-500',
    defaultConfig: { xrns: { synthType: 'wavesabre-slaughter' } },
  },
  WaveSabreFalcon: {
    type: 'WaveSabreSynth',
    name: 'WaveSabre Falcon',
    shortName: 'Falcon',
    description: 'Demoscene synth from 64k intros - lightweight FM/subtractive hybrid. Used in Logicoma, Conspiracy demos.',
    bestFor: ['Demoscene', '64k intros', 'FM sounds', 'Lightweight'],
    icon: 'Bird',
    color: 'text-orange-400',
    defaultConfig: { xrns: { synthType: 'wavesabre-falcon' } },
  },
  WaveSabreAdultery: {
    type: 'WaveSabreSynth',
    name: 'WaveSabre Adultery',
    shortName: 'Adult',
    description: 'Demoscene GM sampler from 64k intros - plays General MIDI samples from system DLS. Used in Logicoma demos.',
    bestFor: ['Demoscene', '64k intros', 'General MIDI', 'Orchestral'],
    icon: 'Music',
    color: 'text-purple-400',
    defaultConfig: { xrns: { synthType: 'wavesabre-adultery' } },
  },
  OidosSynth: {
    type: 'OidosSynth',
    name: 'Oidos',
    shortName: 'Oidos',
    description: 'Additive synth from Loonies demoscene group - 256 partials, frequency modulation, distortion. Tiny code size for 4k/8k intros.',
    bestFor: ['Demoscene', '4k intros', 'Additive synthesis', 'Rich pads', 'Complex timbres'],
    icon: 'Sparkles',
    color: 'text-accent-highlight',
  },
  TunefishSynth: {
    type: 'TunefishSynth',
    name: 'Tunefish 4',
    shortName: 'TF4',
    description: 'Additive/subtractive synth from Brain Control - 2 oscillators, bandpass array, noise, modulation matrix. Used in demoscene.',
    bestFor: ['Demoscene', '64k intros', 'Versatile', 'Pads', 'Leads', 'Bass'],
    icon: 'Fish',
    color: 'text-teal-400',
  },
  WAM: {
    type: 'WAM',
    name: 'Web Audio Module',
    shortName: 'WAM',
    description: 'Load external audio plugins from URL (standard WAM 2.0 format)',
    bestFor: ['External plugins', 'Community synths', 'Rich UI'],
    icon: 'Globe',
    color: 'text-accent-highlight',
  },
  WAMOBXd: {
    type: 'WAMOBXd',
    name: 'OB-Xd (WAM)',
    shortName: 'OBXd-W',
    description: 'Oberheim OB-X virtual analog synth via WAM 2.0',
    bestFor: ['Analog pads', 'Warm leads', 'Classic analog', 'Rich UI'],
    icon: 'Waves',
    color: 'text-amber-400',
  },
  WAMSynth101: {
    type: 'WAMSynth101',
    name: 'Synth-101 (WAM)',
    shortName: 'SH101',
    description: 'Roland SH-101 monophonic synthesizer via WAM 2.0',
    bestFor: ['Mono bass', 'Acid lines', 'Classic mono', 'Rich UI'],
    icon: 'AudioLines',
    color: 'text-blue-400',
  },
  WAMTinySynth: {
    type: 'WAMTinySynth',
    name: 'TinySynth (WAM)',
    shortName: 'Tiny',
    description: 'GM-mapped multi-timbral synth via WAM 2.0',
    bestFor: ['General MIDI', 'Multi-timbral', 'Quick patches', 'Rich UI'],
    icon: 'Music2',
    color: 'text-green-400',
  },
  WAMFaustFlute: {
    type: 'WAMFaustFlute',
    name: 'Faust Flute (WAM)',
    shortName: 'Flute',
    description: 'Physical modelling flute via Faust DSP and WAM 2.0',
    bestFor: ['Physical model', 'Wind instruments', 'Expressive', 'Rich UI'],
    icon: 'Wind',
    color: 'text-sky-400',
  },
  Dexed: {
    type: 'Dexed',
    name: 'Dexed (DX7)',
    shortName: 'DX7',
    description: 'Yamaha DX7 FM synthesizer emulation - 6-operator FM with 32 algorithms',
    bestFor: ['FM Bass', 'Electric Piano', 'Bells', 'Pads', 'Classic FM sounds'],
    icon: 'Piano',
    color: 'text-blue-400',
  },
  OBXd: {
    type: 'OBXd',
    name: 'OBXd (Oberheim)',
    shortName: 'OBXd',
    description: 'Oberheim OB-X analog polysynth emulation - classic warm analog sounds',
    bestFor: ['Pads', 'Brass', 'Strings', 'Warm leads', 'Analog sounds'],
    icon: 'Waves',
    color: 'text-amber-400',
  },
  DexedBridge: {
    type: 'DexedBridge',
    name: 'Dexed DX7 (Bridge)',
    shortName: 'DX7B',
    description: 'Dexed DX7 via VSTBridge generic framework - test/validation of the bridge',
    bestFor: ['FM Bass', 'Electric Piano', 'Bells', 'Bridge testing'],
    icon: 'Plug',
    color: 'text-purple-400',
  },
  Vital: {
    type: 'Vital',
    name: 'Vital (Wavetable)',
    shortName: 'Vital',
    description: 'Spectral warping wavetable synthesizer - 3 oscillators with spectral morphing, 13 morph types, phase distortion',
    bestFor: ['Wavetable', 'Spectral', 'Modern bass', 'Pads', 'Leads', 'Sound design'],
    icon: 'Waves',
    color: 'text-violet-400',
  },
  Odin2: {
    type: 'Odin2',
    name: 'Odin2 (Hybrid)',
    shortName: 'Odin2',
    description: 'Semi-modular hybrid synth - 11 oscillator types (analog, wavetable, FM, vector, chiptune), 9 filter types, modulation matrix',
    bestFor: ['Hybrid synthesis', 'Analog', 'Wavetable', 'FM', 'Vector', 'Chiptune'],
    icon: 'Zap',
    color: 'text-emerald-400',
  },
  Surge: {
    type: 'Surge',
    name: 'Surge XT (Hybrid)',
    shortName: 'Surge',
    description: 'Professional hybrid synth - dual scenes, 12 oscillator types, 32 effect types, 765 parameters, open source since 2018',
    bestFor: ['Professional', 'Hybrid', 'Sound design', 'Bass', 'Pads', 'Leads', 'FX'],
    icon: 'Activity',
    color: 'text-accent-highlight',
  },
  TonewheelOrgan: {
    type: 'TonewheelOrgan',
    name: 'Tonewheel Organ',
    shortName: 'Organ',
    description: 'Hammond-style tonewheel organ - 9 drawbars, key click, percussion, vibrato/chorus scanner, overdrive',
    bestFor: ['Reggae organ', 'Gospel', 'Jazz', 'Blues', 'Rock organ', 'Ska'],
    icon: 'Music',
    color: 'text-amber-400',
  },
  Melodica: {
    type: 'Melodica',
    name: 'Melodica',
    shortName: 'Melod',
    description: 'Monophonic reed instrument physical model - breath dynamics, body resonance, vibrato, portamento',
    bestFor: ['Reggae melodica', 'Dub', 'Ska', 'Augustus Pablo', 'Lead melodies'],
    icon: 'Wind',
    color: 'text-teal-400',
  },
  Monique: {
    type: 'Monique',
    name: 'Monique (Monosynth)',
    shortName: 'Monique',
    description: 'Morphing monosynth - 3 morphable oscillators, 3 cross-routed filters, 4 tempo-synced MFOs, arpeggiator',
    bestFor: ['Mono bass', 'Acid', 'Leads', 'Sound design', 'Morphing'],
    icon: 'Sparkles',
    color: 'text-fuchsia-400',
  },
  Helm: {
    type: 'Helm',
    name: 'Helm (Polyphonic)',
    shortName: 'Helm',
    description: 'Polyphonic synth by Matt Tytel - 2 oscillators, sub, 2 filters, 2 LFOs, 2 step sequencers, effects',
    bestFor: ['Modern leads', 'Bass', 'Pads', 'Keys', 'EDM'],
    icon: 'Waves',
    color: 'text-accent-highlight',
  },
  Sorcer: {
    type: 'Sorcer',
    name: 'Sorcer (Wavetable)',
    shortName: 'Sorcer',
    description: 'FAUST-based wavetable synth by OpenAV - wavetable oscillator, Butterworth filter, compressor, LFO',
    bestFor: ['Wavetable', 'EDM', 'Pads', 'Sound design'],
    icon: 'Sparkles',
    color: 'text-purple-500',
  },
  Amsynth: {
    type: 'Amsynth',
    name: 'amsynth (Analog)',
    shortName: 'amsynth',
    description: 'Classic analog modeling by Nick Dowell - 2 oscillators, filter, 2 envelopes, LFO, Freeverb, distortion',
    bestFor: ['Analog bass', 'Vintage leads', 'Pads', 'Retro sounds'],
    icon: 'Radio',
    color: 'text-orange-400',
  },
  OBXf: {
    type: 'OBXf',
    name: 'OB-Xf (Analog)',
    shortName: 'OB-Xf',
    description: 'Oberheim OB-X/OB-Xa modeling by Surge Synth Team - 2 oscillators, multimode filter, 2 LFOs, voice variation',
    bestFor: ['Oberheim brass', 'Vintage strings', 'Analog bass', 'Classic pads'],
    icon: 'Speaker',
    color: 'text-indigo-500',
  },
  SunVoxSynth: {
    type: 'SunVoxSynth',
    name: 'SunVox',
    shortName: 'SVX',
    description: 'SunVox WASM modular synth patch player (.sunsynth / .sunvox)',
    bestFor: ['Modular synth', 'SunVox patches', 'Complex synthesis'],
    icon: 'Sun',
    color: 'text-yellow-400',
  },
  SuperCollider: {
    type: 'SuperCollider',
    name: 'SuperCollider',
    shortName: 'SC',
    description: 'SuperCollider SynthDef scripted synthesis via scsynth WASM',
    bestFor: ['Algorithmic composition', 'Live coding', 'Experimental'],
    icon: 'Code2',
    color: 'text-lime-400',
  },
  // Gearmulator DSP56300 VA synths (require user-provided firmware ROMs)
  GearmulatorVirus: {
    type: 'GearmulatorVirus',
    name: 'Access Virus A/B/C',
    shortName: 'Virus',
    description: 'DSP56300 emulation of Access Virus A/B/C VA synth (requires firmware ROM)',
    bestFor: ['Trance leads', 'VA bass', 'Supersaw pads', 'Classic VA'],
    icon: 'Cpu',
    color: 'text-red-400',
  },
  GearmulatorVirusTI: {
    type: 'GearmulatorVirusTI',
    name: 'Access Virus TI',
    shortName: 'VTI',
    description: 'DSP56300 emulation of Access Virus TI/TI2/Snow (requires firmware ROM)',
    bestFor: ['Modern VA', 'Wavetable', 'Multi-timbral', 'Trance'],
    icon: 'Cpu',
    color: 'text-red-500',
  },
  GearmulatorMicroQ: {
    type: 'GearmulatorMicroQ',
    name: 'Waldorf microQ',
    shortName: 'uQ',
    description: 'DSP56300 emulation of Waldorf microQ VA synth (requires firmware ROM)',
    bestFor: ['Wavetable', 'Digital pads', 'Complex modulation'],
    icon: 'Cpu',
    color: 'text-blue-400',
  },
  GearmulatorXT: {
    type: 'GearmulatorXT',
    name: 'Waldorf MW II/XT',
    shortName: 'XT',
    description: 'DSP56300 emulation of Waldorf Microwave II/XT (requires firmware ROM)',
    bestFor: ['Wavetable', 'Digital textures', 'Experimental'],
    icon: 'Cpu',
    color: 'text-blue-500',
  },
  GearmulatorNord: {
    type: 'GearmulatorNord',
    name: 'Nord Lead 2x',
    shortName: 'NL2x',
    description: 'DSP56300 emulation of Clavia Nord Lead 2x (requires firmware ROM)',
    bestFor: ['Classic VA leads', 'Analog modeling', 'Synth brass'],
    icon: 'Cpu',
    color: 'text-orange-400',
  },
  GearmulatorJP8000: {
    type: 'GearmulatorJP8000',
    name: 'Roland JP-8000',
    shortName: 'JP8K',
    description: 'DSP56300 emulation of Roland JP-8000 (requires firmware ROM)',
    bestFor: ['Supersaw', 'Trance', 'VA leads', 'Classic Roland'],
    icon: 'Cpu',
    color: 'text-purple-400',
  },
};
