/**
 * Factory Presets - 36+ ready-to-use instrument presets
 * Organized by category: Bass, Leads, Pads, Drums, FX
 */

import type { InstrumentConfig } from '@typedefs/instrument';

// ============================================================================
// BASS PRESETS (12)
// ============================================================================

export const BASS_PRESETS: Omit<InstrumentConfig, 'id'>[] = [
  // TB-303 Acid Bass (8 presets)
  {
    name: '303 Classic',
    synthType: 'TB303',
    tb303: {
      oscillator: { type: 'sawtooth' },
      filter: { cutoff: 800, resonance: 65 },
      filterEnvelope: { envMod: 60, decay: 200 },
      accent: { amount: 70 },
      slide: { time: 60, mode: 'exponential' },
    },
    effects: [],
    volume: -12,
    pan: 0,
  },
  {
    name: '303 Squelchy',
    synthType: 'TB303',
    tb303: {
      oscillator: { type: 'sawtooth' },
      filter: { cutoff: 1200, resonance: 85 },
      filterEnvelope: { envMod: 80, decay: 150 },
      accent: { amount: 80 },
      slide: { time: 50, mode: 'exponential' },
    },
    effects: [],
    volume: -12,
    pan: 0,
  },
  {
    name: '303 Deep',
    synthType: 'TB303',
    tb303: {
      oscillator: { type: 'sawtooth' },
      filter: { cutoff: 400, resonance: 40 },
      filterEnvelope: { envMod: 30, decay: 300 },
      accent: { amount: 60 },
      slide: { time: 80, mode: 'exponential' },
    },
    effects: [],
    volume: -10,
    pan: 0,
  },
  {
    name: '303 Square',
    synthType: 'TB303',
    tb303: {
      oscillator: { type: 'square' },
      filter: { cutoff: 700, resonance: 60 },
      filterEnvelope: { envMod: 50, decay: 180 },
      accent: { amount: 70 },
      slide: { time: 60, mode: 'exponential' },
    },
    effects: [],
    volume: -12,
    pan: 0,
  },
  {
    name: '303 Screamer',
    synthType: 'TB303',
    tb303: {
      oscillator: { type: 'sawtooth' },
      filter: { cutoff: 2000, resonance: 92 },
      filterEnvelope: { envMod: 95, decay: 100 },
      accent: { amount: 90 },
      slide: { time: 40, mode: 'exponential' },
    },
    effects: [],
    volume: -14,
    pan: 0,
  },
  {
    name: '303 Bubbly',
    synthType: 'TB303',
    tb303: {
      oscillator: { type: 'sawtooth' },
      filter: { cutoff: 1500, resonance: 75 },
      filterEnvelope: { envMod: 70, decay: 80 },
      accent: { amount: 75 },
      slide: { time: 30, mode: 'exponential' },
    },
    effects: [],
    volume: -12,
    pan: 0,
  },
  {
    name: '303 Self-Osc',
    synthType: 'TB303',
    tb303: {
      oscillator: { type: 'sawtooth' },
      filter: { cutoff: 1500, resonance: 98 },
      filterEnvelope: { envMod: 85, decay: 200 },
      accent: { amount: 85 },
      slide: { time: 70, mode: 'exponential' },
    },
    effects: [],
    volume: -14,
    pan: 0,
  },
  {
    name: '303 Plastikman',
    synthType: 'TB303',
    tb303: {
      oscillator: { type: 'sawtooth' },
      filter: { cutoff: 600, resonance: 55 },
      filterEnvelope: { envMod: 40, decay: 250 },
      accent: { amount: 65 },
      slide: { time: 100, mode: 'exponential' },
    },
    effects: [],
    volume: -10,
    pan: 0,
  },

  // Devil Fish TB-303 Presets (15 presets)
  {
    name: 'DF Classic',
    synthType: 'TB303',
    tb303: {
      oscillator: { type: 'sawtooth' },
      filter: { cutoff: 900, resonance: 70 },
      filterEnvelope: { envMod: 55, decay: 250 },
      accent: { amount: 75 },
      slide: { time: 50, mode: 'exponential' },
      devilFish: {
        enabled: true,
        normalDecay: 300,
        accentDecay: 150,
        vegDecay: 2500,
        vegSustain: 0,
        softAttack: 2,
        filterTracking: 0,
        filterFM: 0,
        sweepSpeed: 'normal',
        accentSweepEnabled: true,
        highResonance: false,
        muffler: 'off',
      },
    },
    effects: [],
    volume: -10,
    pan: 0,
  },
  {
    name: 'DF Infinite Drone',
    synthType: 'TB303',
    tb303: {
      oscillator: { type: 'sawtooth' },
      filter: { cutoff: 600, resonance: 55 },
      filterEnvelope: { envMod: 30, decay: 400 },
      accent: { amount: 50 },
      slide: { time: 120, mode: 'exponential' },
      devilFish: {
        enabled: true,
        normalDecay: 800,
        accentDecay: 600,
        vegDecay: 3000,
        vegSustain: 100,
        softAttack: 15,
        filterTracking: 50,
        filterFM: 10,
        sweepSpeed: 'slow',
        accentSweepEnabled: true,
        highResonance: false,
        muffler: 'soft',
      },
    },
    effects: [],
    volume: -12,
    pan: 0,
  },
  {
    name: 'DF Chaos Engine',
    synthType: 'TB303',
    tb303: {
      oscillator: { type: 'sawtooth' },
      filter: { cutoff: 1400, resonance: 85 },
      filterEnvelope: { envMod: 80, decay: 350 },
      accent: { amount: 100 },
      slide: { time: 30, mode: 'exponential' },
      overdrive: { amount: 70 },
      devilFish: {
        enabled: true,
        normalDecay: 200,
        accentDecay: 100,
        vegDecay: 500,
        vegSustain: 20,
        softAttack: 0.5,
        filterTracking: 80,
        filterFM: 80,
        sweepSpeed: 'fast',
        accentSweepEnabled: true,
        highResonance: true,
        muffler: 'hard',
      },
    },
    effects: [],
    volume: -14,
    pan: 0,
  },
  {
    name: 'DF Whistler',
    synthType: 'TB303',
    tb303: {
      oscillator: { type: 'sawtooth' },
      filter: { cutoff: 1600, resonance: 92 },
      filterEnvelope: { envMod: 70, decay: 500 },
      accent: { amount: 80 },
      slide: { time: 100, mode: 'exponential' },
      devilFish: {
        enabled: true,
        normalDecay: 400,
        accentDecay: 300,
        vegDecay: 1500,
        vegSustain: 30,
        softAttack: 5,
        filterTracking: 150,
        filterFM: 25,
        sweepSpeed: 'slow',
        accentSweepEnabled: true,
        highResonance: true,
        muffler: 'off',
      },
    },
    effects: [],
    volume: -14,
    pan: 0,
  },
  {
    name: 'DF Muffled Punch',
    synthType: 'TB303',
    tb303: {
      oscillator: { type: 'sawtooth' },
      filter: { cutoff: 800, resonance: 60 },
      filterEnvelope: { envMod: 65, decay: 150 },
      accent: { amount: 90 },
      slide: { time: 45, mode: 'exponential' },
      devilFish: {
        enabled: true,
        normalDecay: 100,
        accentDecay: 80,
        vegDecay: 200,
        vegSustain: 0,
        softAttack: 0.5,
        filterTracking: 30,
        filterFM: 15,
        sweepSpeed: 'fast',
        accentSweepEnabled: true,
        highResonance: false,
        muffler: 'soft',
      },
    },
    effects: [],
    volume: -10,
    pan: 0,
  },
  {
    name: 'DF Acid Low',
    synthType: 'TB303',
    tb303: {
      oscillator: { type: 'square' },
      filter: { cutoff: 400, resonance: 72 },
      filterEnvelope: { envMod: 50, decay: 300 },
      accent: { amount: 80 },
      slide: { time: 80, mode: 'exponential' },
      devilFish: {
        enabled: true,
        normalDecay: 250,
        accentDecay: 120,
        vegDecay: 800,
        vegSustain: 15,
        softAttack: 1.5,
        filterTracking: 40,
        filterFM: 20,
        sweepSpeed: 'fast',
        accentSweepEnabled: true,
        highResonance: false,
        muffler: 'off',
      },
    },
    effects: [],
    volume: -10,
    pan: 0,
  },
  {
    name: 'DF Resonant Sweep',
    synthType: 'TB303',
    tb303: {
      oscillator: { type: 'sawtooth' },
      filter: { cutoff: 1200, resonance: 88 },
      filterEnvelope: { envMod: 90, decay: 600 },
      accent: { amount: 95 },
      slide: { time: 60, mode: 'exponential' },
      devilFish: {
        enabled: true,
        normalDecay: 500,
        accentDecay: 400,
        vegDecay: 1200,
        vegSustain: 10,
        softAttack: 3,
        filterTracking: 100,
        filterFM: 35,
        sweepSpeed: 'slow',
        accentSweepEnabled: true,
        highResonance: true,
        muffler: 'off',
      },
    },
    effects: [],
    volume: -12,
    pan: 0,
  },
  {
    name: 'DF Soft Pad',
    synthType: 'TB303',
    tb303: {
      oscillator: { type: 'sawtooth' },
      filter: { cutoff: 700, resonance: 40 },
      filterEnvelope: { envMod: 20, decay: 800 },
      accent: { amount: 30 },
      slide: { time: 200, mode: 'exponential' },
      devilFish: {
        enabled: true,
        normalDecay: 1500,
        accentDecay: 1200,
        vegDecay: 3000,
        vegSustain: 80,
        softAttack: 25,
        filterTracking: 60,
        filterFM: 5,
        sweepSpeed: 'slow',
        accentSweepEnabled: false,
        highResonance: false,
        muffler: 'soft',
      },
    },
    effects: [],
    volume: -12,
    pan: 0,
  },
  {
    name: 'DF Hardstyle',
    synthType: 'TB303',
    tb303: {
      oscillator: { type: 'sawtooth' },
      filter: { cutoff: 1800, resonance: 75 },
      filterEnvelope: { envMod: 85, decay: 80 },
      accent: { amount: 100 },
      slide: { time: 25, mode: 'exponential' },
      overdrive: { amount: 60 },
      devilFish: {
        enabled: true,
        normalDecay: 60,
        accentDecay: 40,
        vegDecay: 150,
        vegSustain: 0,
        softAttack: 0.3,
        filterTracking: 50,
        filterFM: 45,
        sweepSpeed: 'fast',
        accentSweepEnabled: true,
        highResonance: false,
        muffler: 'hard',
      },
    },
    effects: [],
    volume: -12,
    pan: 0,
  },
  {
    name: 'DF Singing Filter',
    synthType: 'TB303',
    tb303: {
      oscillator: { type: 'sawtooth' },
      filter: { cutoff: 2200, resonance: 95 },
      filterEnvelope: { envMod: 60, decay: 700 },
      accent: { amount: 70 },
      slide: { time: 150, mode: 'exponential' },
      devilFish: {
        enabled: true,
        normalDecay: 600,
        accentDecay: 500,
        vegDecay: 2000,
        vegSustain: 50,
        softAttack: 8,
        filterTracking: 180,
        filterFM: 15,
        sweepSpeed: 'normal',
        accentSweepEnabled: true,
        highResonance: true,
        muffler: 'off',
      },
    },
    effects: [],
    volume: -14,
    pan: 0,
  },
  {
    name: 'DF Gritty Bass',
    synthType: 'TB303',
    tb303: {
      oscillator: { type: 'square' },
      filter: { cutoff: 500, resonance: 65 },
      filterEnvelope: { envMod: 45, decay: 200 },
      accent: { amount: 85 },
      slide: { time: 70, mode: 'exponential' },
      overdrive: { amount: 40 },
      devilFish: {
        enabled: true,
        normalDecay: 180,
        accentDecay: 100,
        vegDecay: 400,
        vegSustain: 5,
        softAttack: 1,
        filterTracking: 25,
        filterFM: 55,
        sweepSpeed: 'fast',
        accentSweepEnabled: true,
        highResonance: false,
        muffler: 'hard',
      },
    },
    effects: [],
    volume: -10,
    pan: 0,
  },
  {
    name: 'DF Bubbly Acid',
    synthType: 'TB303',
    tb303: {
      oscillator: { type: 'sawtooth' },
      filter: { cutoff: 1500, resonance: 78 },
      filterEnvelope: { envMod: 75, decay: 50 },
      accent: { amount: 90 },
      slide: { time: 20, mode: 'exponential' },
      devilFish: {
        enabled: true,
        normalDecay: 40,
        accentDecay: 30,
        vegDecay: 100,
        vegSustain: 0,
        softAttack: 0.5,
        filterTracking: 70,
        filterFM: 30,
        sweepSpeed: 'fast',
        accentSweepEnabled: true,
        highResonance: false,
        muffler: 'off',
      },
    },
    effects: [],
    volume: -10,
    pan: 0,
  },
  {
    name: 'DF Ambient Drone',
    synthType: 'TB303',
    tb303: {
      oscillator: { type: 'sawtooth' },
      filter: { cutoff: 900, resonance: 50 },
      filterEnvelope: { envMod: 25, decay: 1500 },
      accent: { amount: 35 },
      slide: { time: 300, mode: 'exponential' },
      devilFish: {
        enabled: true,
        normalDecay: 2500,
        accentDecay: 2000,
        vegDecay: 3000,
        vegSustain: 95,
        softAttack: 30,
        filterTracking: 80,
        filterFM: 8,
        sweepSpeed: 'slow',
        accentSweepEnabled: false,
        highResonance: false,
        muffler: 'soft',
      },
    },
    effects: [],
    volume: -14,
    pan: 0,
  },
  {
    name: 'DF Techno Stab',
    synthType: 'TB303',
    tb303: {
      oscillator: { type: 'sawtooth' },
      filter: { cutoff: 2000, resonance: 70 },
      filterEnvelope: { envMod: 70, decay: 100 },
      accent: { amount: 100 },
      slide: { time: 30, mode: 'exponential' },
      devilFish: {
        enabled: true,
        normalDecay: 80,
        accentDecay: 50,
        vegDecay: 180,
        vegSustain: 0,
        softAttack: 0.3,
        filterTracking: 45,
        filterFM: 40,
        sweepSpeed: 'fast',
        accentSweepEnabled: true,
        highResonance: false,
        muffler: 'soft',
      },
    },
    effects: [],
    volume: -10,
    pan: 0,
  },
  {
    name: 'DF Screaming Lead',
    synthType: 'TB303',
    tb303: {
      oscillator: { type: 'sawtooth' },
      filter: { cutoff: 3000, resonance: 90 },
      filterEnvelope: { envMod: 95, decay: 400 },
      accent: { amount: 100 },
      slide: { time: 50, mode: 'exponential' },
      overdrive: { amount: 50 },
      devilFish: {
        enabled: true,
        normalDecay: 350,
        accentDecay: 250,
        vegDecay: 800,
        vegSustain: 25,
        softAttack: 2,
        filterTracking: 150,
        filterFM: 60,
        sweepSpeed: 'normal',
        accentSweepEnabled: true,
        highResonance: true,
        muffler: 'off',
      },
    },
    effects: [],
    volume: -16,
    pan: 0,
  },

  // Non-303 Bass (4 presets)
  {
    name: '808 Sub',
    synthType: 'MonoSynth',
    oscillator: { type: 'sine', detune: 0, octave: -1 },
    envelope: { attack: 5, decay: 300, sustain: 40, release: 100 },
    filter: { type: 'lowpass', frequency: 200, Q: 1, rolloff: -24 },
    effects: [],
    volume: -8,
    pan: 0,
  },
  {
    name: 'Reese Bass',
    synthType: 'DuoSynth',
    oscillator: { type: 'sawtooth', detune: 15, octave: 0 },
    envelope: { attack: 10, decay: 200, sustain: 70, release: 200 },
    filter: { type: 'lowpass', frequency: 800, Q: 3, rolloff: -24 },
    effects: [],
    volume: -10,
    pan: 0,
  },
  {
    name: 'House Pluck',
    synthType: 'PluckSynth',
    oscillator: { type: 'sine', detune: 0, octave: 0 },
    envelope: { attack: 1, decay: 500, sustain: 0, release: 500 },
    filter: { type: 'lowpass', frequency: 2000, Q: 1, rolloff: -12 },
    effects: [],
    volume: -8,
    pan: 0,
  },
  {
    name: 'Wobble Bass',
    synthType: 'FMSynth',
    oscillator: { type: 'sine', detune: 0, octave: 0 },
    envelope: { attack: 5, decay: 200, sustain: 30, release: 100 },
    filter: { type: 'lowpass', frequency: 1000, Q: 8, rolloff: -24 },
    effects: [],
    volume: -10,
    pan: 0,
  },
];

// ============================================================================
// LEAD PRESETS (8)
// ============================================================================

export const LEAD_PRESETS: Omit<InstrumentConfig, 'id'>[] = [
  {
    name: 'Supersaw Lead',
    synthType: 'DuoSynth',
    oscillator: { type: 'sawtooth', detune: 20, octave: 0 },
    envelope: { attack: 20, decay: 100, sustain: 80, release: 300 },
    filter: { type: 'lowpass', frequency: 3000, Q: 2, rolloff: -24 },
    effects: [],
    volume: -12,
    pan: 0,
  },
  {
    name: 'Acid Lead',
    synthType: 'MonoSynth',
    oscillator: { type: 'square', detune: 0, octave: 0 },
    envelope: { attack: 10, decay: 150, sustain: 60, release: 200 },
    filter: { type: 'lowpass', frequency: 2000, Q: 5, rolloff: -24 },
    effects: [],
    volume: -10,
    pan: 0,
  },
  {
    name: 'FM Stab',
    synthType: 'FMSynth',
    oscillator: { type: 'sine', detune: 0, octave: 0 },
    envelope: { attack: 1, decay: 300, sustain: 20, release: 100 },
    filter: { type: 'lowpass', frequency: 4000, Q: 3, rolloff: -24 },
    effects: [],
    volume: -10,
    pan: 0,
  },
  {
    name: 'Sync Lead',
    synthType: 'Synth',
    oscillator: { type: 'sawtooth', detune: 5, octave: 0 },
    envelope: { attack: 10, decay: 200, sustain: 70, release: 300 },
    filter: { type: 'lowpass', frequency: 2500, Q: 3, rolloff: -24 },
    effects: [],
    volume: -12,
    pan: 0,
  },
  {
    name: 'Chip Lead',
    synthType: 'Synth',
    oscillator: { type: 'square', detune: 0, octave: 0 },
    envelope: { attack: 1, decay: 100, sustain: 50, release: 100 },
    filter: { type: 'lowpass', frequency: 3000, Q: 1, rolloff: -12 },
    effects: [],
    volume: -8,
    pan: 0,
  },
  {
    name: 'Trance Pluck',
    synthType: 'PluckSynth',
    oscillator: { type: 'sine', detune: 0, octave: 0 },
    envelope: { attack: 1, decay: 300, sustain: 0, release: 300 },
    filter: { type: 'lowpass', frequency: 4000, Q: 2, rolloff: -24 },
    effects: [],
    volume: -10,
    pan: 0,
  },
  {
    name: 'Detuned Lead',
    synthType: 'DuoSynth',
    oscillator: { type: 'sawtooth', detune: 25, octave: 0 },
    envelope: { attack: 30, decay: 150, sustain: 70, release: 400 },
    filter: { type: 'lowpass', frequency: 2800, Q: 2, rolloff: -24 },
    effects: [],
    volume: -12,
    pan: 0,
  },
  {
    name: 'Filtered Lead',
    synthType: 'MonoSynth',
    oscillator: { type: 'sawtooth', detune: 0, octave: 0 },
    envelope: { attack: 20, decay: 200, sustain: 60, release: 300 },
    filter: { type: 'bandpass', frequency: 2000, Q: 10, rolloff: -24 },
    effects: [],
    volume: -10,
    pan: 0,
  },
];

// ============================================================================
// PAD PRESETS (4)
// ============================================================================

export const PAD_PRESETS: Omit<InstrumentConfig, 'id'>[] = [
  {
    name: 'Ambient Pad',
    synthType: 'Synth',
    oscillator: { type: 'sine', detune: 3, octave: 0 },
    envelope: { attack: 800, decay: 500, sustain: 70, release: 1500 },
    filter: { type: 'lowpass', frequency: 1500, Q: 1, rolloff: -12 },
    effects: [],
    volume: -14,
    pan: 0,
  },
  {
    name: 'Dark Pad',
    synthType: 'DuoSynth',
    oscillator: { type: 'triangle', detune: 8, octave: 0 },
    envelope: { attack: 1000, decay: 300, sustain: 80, release: 2000 },
    filter: { type: 'lowpass', frequency: 800, Q: 2, rolloff: -24 },
    effects: [],
    volume: -16,
    pan: 0,
  },
  {
    name: 'String Pad',
    synthType: 'Synth',
    oscillator: { type: 'sawtooth', detune: 5, octave: 0 },
    envelope: { attack: 500, decay: 300, sustain: 70, release: 1200 },
    filter: { type: 'lowpass', frequency: 2000, Q: 1.5, rolloff: -12 },
    effects: [],
    volume: -14,
    pan: 0,
  },
  {
    name: 'Noise Sweep',
    synthType: 'NoiseSynth',
    oscillator: { type: 'sine', detune: 0, octave: 0 }, // NoiseSynth doesn't use waveform type
    envelope: { attack: 300, decay: 1000, sustain: 50, release: 1000 },
    filter: { type: 'bandpass', frequency: 1000, Q: 5, rolloff: -24 },
    effects: [],
    volume: -18,
    pan: 0,
  },
];

// ============================================================================
// DRUM PRESETS (8)
// ============================================================================

export const DRUM_PRESETS: Omit<InstrumentConfig, 'id'>[] = [
  {
    name: '808 Kick',
    synthType: 'MembraneSynth',
    oscillator: { type: 'sine', detune: 0, octave: -2 },
    envelope: { attack: 1, decay: 500, sustain: 0, release: 100 },
    filter: { type: 'lowpass', frequency: 100, Q: 1, rolloff: -24 },
    effects: [],
    volume: -6,
    pan: 0,
  },
  {
    name: '909 Kick',
    synthType: 'MembraneSynth',
    oscillator: { type: 'sine', detune: 0, octave: -2 },
    envelope: { attack: 1, decay: 300, sustain: 0, release: 50 },
    filter: { type: 'lowpass', frequency: 80, Q: 2, rolloff: -24 },
    effects: [],
    volume: -6,
    pan: 0,
  },
  {
    name: 'Hardcore Kick',
    synthType: 'MembraneSynth',
    oscillator: { type: 'sine', detune: 0, octave: -2 },
    envelope: { attack: 1, decay: 150, sustain: 0, release: 20 },
    filter: { type: 'lowpass', frequency: 120, Q: 3, rolloff: -24 },
    effects: [],
    volume: -4,
    pan: 0,
  },
  {
    name: 'DnB Snare',
    synthType: 'NoiseSynth',
    oscillator: { type: 'sine', detune: 0, octave: 0 }, // NoiseSynth doesn't use waveform type
    envelope: { attack: 1, decay: 200, sustain: 0, release: 100 },
    filter: { type: 'highpass', frequency: 300, Q: 1, rolloff: -12 },
    effects: [],
    volume: -8,
    pan: 0,
  },
  {
    name: 'Clap',
    synthType: 'NoiseSynth',
    oscillator: { type: 'sine', detune: 0, octave: 0 }, // NoiseSynth doesn't use waveform type
    envelope: { attack: 1, decay: 150, sustain: 0, release: 50 },
    filter: { type: 'bandpass', frequency: 1000, Q: 2, rolloff: -24 },
    effects: [],
    volume: -10,
    pan: 0,
  },
  {
    name: 'Closed Hat',
    synthType: 'MetalSynth',
    oscillator: { type: 'square', detune: 0, octave: 0 },
    envelope: { attack: 1, decay: 50, sustain: 0, release: 20 },
    filter: { type: 'highpass', frequency: 8000, Q: 1, rolloff: -12 },
    effects: [],
    volume: -12,
    pan: 0,
  },
  {
    name: 'Open Hat',
    synthType: 'MetalSynth',
    oscillator: { type: 'square', detune: 0, octave: 0 },
    envelope: { attack: 1, decay: 300, sustain: 0, release: 200 },
    filter: { type: 'highpass', frequency: 7000, Q: 1, rolloff: -12 },
    effects: [],
    volume: -12,
    pan: 0,
  },
  {
    name: 'Crash',
    synthType: 'MetalSynth',
    oscillator: { type: 'square', detune: 0, octave: 0 },
    envelope: { attack: 10, decay: 1500, sustain: 0, release: 1000 },
    filter: { type: 'highpass', frequency: 6000, Q: 1, rolloff: -12 },
    effects: [],
    volume: -14,
    pan: 0,
  },
];

// ============================================================================
// FX PRESETS (4)
// ============================================================================

export const FX_PRESETS: Omit<InstrumentConfig, 'id'>[] = [
  {
    name: 'Riser',
    synthType: 'NoiseSynth',
    oscillator: { type: 'sine', detune: 0, octave: 0 }, // NoiseSynth doesn't use waveform type
    envelope: { attack: 2000, decay: 100, sustain: 0, release: 100 },
    filter: { type: 'lowpass', frequency: 200, Q: 5, rolloff: -24 },
    effects: [],
    volume: -16,
    pan: 0,
  },
  {
    name: 'Downlifter',
    synthType: 'MonoSynth',
    oscillator: { type: 'sawtooth', detune: 0, octave: 0 },
    envelope: { attack: 10, decay: 2000, sustain: 0, release: 100 },
    filter: { type: 'lowpass', frequency: 5000, Q: 3, rolloff: -24 },
    effects: [],
    volume: -14,
    pan: 0,
  },
  {
    name: 'Impact',
    synthType: 'NoiseSynth',
    oscillator: { type: 'sine', detune: 0, octave: 0 }, // NoiseSynth doesn't use waveform type
    envelope: { attack: 1, decay: 500, sustain: 0, release: 200 },
    filter: { type: 'lowpass', frequency: 300, Q: 2, rolloff: -24 },
    effects: [],
    volume: -8,
    pan: 0,
  },
  {
    name: 'Laser Zap',
    synthType: 'FMSynth',
    oscillator: { type: 'sine', detune: 0, octave: 0 },
    envelope: { attack: 1, decay: 300, sustain: 0, release: 100 },
    filter: { type: 'bandpass', frequency: 2000, Q: 10, rolloff: -24 },
    effects: [],
    volume: -12,
    pan: 0,
  },
];

// ============================================================================
// COMBINED FACTORY PRESETS
// ============================================================================

export const FACTORY_PRESETS: Omit<InstrumentConfig, 'id'>[] = [
  ...BASS_PRESETS,
  ...LEAD_PRESETS,
  ...PAD_PRESETS,
  ...DRUM_PRESETS,
  ...FX_PRESETS,
];

// Preset categories for browsing
export const PRESET_CATEGORIES = {
  Bass: BASS_PRESETS,
  Leads: LEAD_PRESETS,
  Pads: PAD_PRESETS,
  Drums: DRUM_PRESETS,
  FX: FX_PRESETS,
};

export type PresetCategory = keyof typeof PRESET_CATEGORIES;
