/**
 * Synth Presets - 20 quality presets per synth type
 * Each preset is designed for immediate musical use
 */

import type {
  SynthType,
  TB303Config,
  ChipSynthConfig,
  DrumMachineConfig,
  SuperSawConfig,
  PolySynthConfig,
  OrganConfig,
  PWMSynthConfig,
  StringMachineConfig,
  FormantSynthConfig,
  WavetableConfig as _WavetableConfig,
  GranularConfig as _GranularConfig,
} from '@typedefs/instrument';

export interface SynthPreset {
  id: string;
  name: string;
  description: string;
  category: 'bass' | 'lead' | 'pad' | 'key' | 'fx' | 'drum' | 'pluck' | 'string';
  config: Partial<any>;
}

// ============================================
// TB-303 PRESETS (Acid Bass)
// ============================================
export const TB303_PRESETS: SynthPreset[] = [
  {
    id: 'tb303-squelch',
    name: 'Classic Squelch',
    description: 'The iconic acid sound with resonant filter sweep',
    category: 'bass',
    config: {
      oscillator: { type: 'sawtooth' },
      filter: { cutoff: 800, resonance: 85 },
      filterEnvelope: { envMod: 80, decay: 300 },
      accent: { amount: 70 },
      slide: { time: 60, mode: 'exponential' },
    } as Partial<TB303Config>,
  },
  {
    id: 'tb303-devilfish',
    name: 'Devil Fish',
    description: 'Extended range with Robin Whittle mod character',
    category: 'bass',
    config: {
      oscillator: { type: 'sawtooth' },
      filter: { cutoff: 600, resonance: 90 },
      filterEnvelope: { envMod: 100, decay: 200 },
      devilFish: { enabled: true, highResonance: true, filterTracking: 150 },
    } as Partial<TB303Config>,
  },
  {
    id: 'tb303-bubbling',
    name: 'Bubbling Bass',
    description: 'Fast decay with resonant bubbles',
    category: 'bass',
    config: {
      oscillator: { type: 'sawtooth' },
      filter: { cutoff: 500, resonance: 75 },
      filterEnvelope: { envMod: 90, decay: 150 },
    } as Partial<TB303Config>,
  },
  {
    id: 'tb303-square-bass',
    name: 'Square Throb',
    description: 'Hollow square wave bass',
    category: 'bass',
    config: {
      oscillator: { type: 'square' },
      filter: { cutoff: 1200, resonance: 40 },
      filterEnvelope: { envMod: 50, decay: 400 },
    } as Partial<TB303Config>,
  },
  {
    id: 'tb303-screamer',
    name: 'Screamer',
    description: 'Self-oscillating filter scream',
    category: 'lead',
    config: {
      oscillator: { type: 'sawtooth' },
      filter: { cutoff: 2000, resonance: 95 },
      filterEnvelope: { envMod: 70, decay: 500 },
      devilFish: { enabled: true, highResonance: true },
    } as Partial<TB303Config>,
  },
  {
    id: 'tb303-rubber',
    name: 'Rubber Bass',
    description: 'Bouncy low-end with slow filter',
    category: 'bass',
    config: {
      oscillator: { type: 'sawtooth' },
      filter: { cutoff: 400, resonance: 60 },
      filterEnvelope: { envMod: 60, decay: 800 },
      slide: { time: 120, mode: 'exponential' },
    } as Partial<TB303Config>,
  },
  {
    id: 'tb303-dirty',
    name: 'Dirty Acid',
    description: 'Heavy distortion with filter growl',
    category: 'bass',
    config: {
      oscillator: { type: 'sawtooth' },
      filter: { cutoff: 700, resonance: 80 },
      filterEnvelope: { envMod: 85, decay: 250 },
      overdrive: { amount: 70 },
    } as Partial<TB303Config>,
  },
  {
    id: 'tb303-subtle',
    name: 'Subtle Sub',
    description: 'Deep sub-bass with minimal filter',
    category: 'bass',
    config: {
      oscillator: { type: 'square' },
      filter: { cutoff: 300, resonance: 20 },
      filterEnvelope: { envMod: 20, decay: 600 },
    } as Partial<TB303Config>,
  },
  {
    id: 'tb303-psychedelic',
    name: 'Psychedelic',
    description: 'Trippy slow sweep with high resonance',
    category: 'lead',
    config: {
      oscillator: { type: 'sawtooth' },
      filter: { cutoff: 1500, resonance: 88 },
      filterEnvelope: { envMod: 95, decay: 1200 },
    } as Partial<TB303Config>,
  },
  {
    id: 'tb303-stab',
    name: 'Acid Stab',
    description: 'Sharp attack for staccato lines',
    category: 'bass',
    config: {
      oscillator: { type: 'sawtooth' },
      filter: { cutoff: 1800, resonance: 70 },
      filterEnvelope: { envMod: 75, decay: 100 },
    } as Partial<TB303Config>,
  },
  {
    id: 'tb303-hardfloor',
    name: 'Hardfloor',
    description: 'Classic hardfloor acid style',
    category: 'bass',
    config: {
      oscillator: { type: 'sawtooth' },
      filter: { cutoff: 900, resonance: 82 },
      filterEnvelope: { envMod: 88, decay: 280 },
      accent: { amount: 80 },
    } as Partial<TB303Config>,
  },
  {
    id: 'tb303-phuture',
    name: 'Phuture',
    description: 'Acid Tracks tribute sound',
    category: 'bass',
    config: {
      oscillator: { type: 'sawtooth' },
      filter: { cutoff: 750, resonance: 78 },
      filterEnvelope: { envMod: 82, decay: 350 },
      slide: { time: 80, mode: 'exponential' },
    } as Partial<TB303Config>,
  },
  {
    id: 'tb303-talking',
    name: 'Talking Bass',
    description: 'Vowel-like filter movement',
    category: 'bass',
    config: {
      oscillator: { type: 'sawtooth' },
      filter: { cutoff: 1100, resonance: 85 },
      filterEnvelope: { envMod: 70, decay: 450 },
    } as Partial<TB303Config>,
  },
  {
    id: 'tb303-minimal',
    name: 'Minimal Techno',
    description: 'Clean, tight bass for minimal',
    category: 'bass',
    config: {
      oscillator: { type: 'square' },
      filter: { cutoff: 600, resonance: 45 },
      filterEnvelope: { envMod: 40, decay: 200 },
    } as Partial<TB303Config>,
  },
  {
    id: 'tb303-wobble',
    name: 'Wobble Bass',
    description: 'Proto-dubstep wobbly bass',
    category: 'bass',
    config: {
      oscillator: { type: 'sawtooth' },
      filter: { cutoff: 500, resonance: 70 },
      filterEnvelope: { envMod: 65, decay: 600 },
    } as Partial<TB303Config>,
  },
  {
    id: 'tb303-uk-hard',
    name: 'UK Hardcore',
    description: 'Fast decay for breakbeat acid',
    category: 'bass',
    config: {
      oscillator: { type: 'sawtooth' },
      filter: { cutoff: 1200, resonance: 75 },
      filterEnvelope: { envMod: 80, decay: 120 },
      accent: { amount: 85 },
    } as Partial<TB303Config>,
  },
  {
    id: 'tb303-goa',
    name: 'Goa Acid',
    description: 'Psychedelic trance acid',
    category: 'lead',
    config: {
      oscillator: { type: 'sawtooth' },
      filter: { cutoff: 2200, resonance: 80 },
      filterEnvelope: { envMod: 90, decay: 400 },
    } as Partial<TB303Config>,
  },
  {
    id: 'tb303-electro',
    name: 'Electro Bass',
    description: 'Punchy electro-style bass',
    category: 'bass',
    config: {
      oscillator: { type: 'sawtooth' },
      filter: { cutoff: 800, resonance: 55 },
      filterEnvelope: { envMod: 55, decay: 180 },
    } as Partial<TB303Config>,
  },
  {
    id: 'tb303-dark',
    name: 'Dark Matter',
    description: 'Very low, ominous bass',
    category: 'bass',
    config: {
      oscillator: { type: 'square' },
      filter: { cutoff: 250, resonance: 30 },
      filterEnvelope: { envMod: 25, decay: 700 },
    } as Partial<TB303Config>,
  },
  {
    id: 'tb303-resonant-lead',
    name: 'Resonant Lead',
    description: 'High-pitched screaming lead',
    category: 'lead',
    config: {
      oscillator: { type: 'sawtooth' },
      filter: { cutoff: 3000, resonance: 92 },
      filterEnvelope: { envMod: 60, decay: 350 },
    } as Partial<TB303Config>,
  },
];

// ============================================
// CHIPSYNTH PRESETS (8-bit / Chiptune)
// ============================================
export const CHIPSYNTH_PRESETS: SynthPreset[] = [
  {
    id: 'chip-major-arp',
    name: 'Major Chord Arp',
    description: 'Classic NES major chord arpeggio',
    category: 'lead',
    config: {
      channel: 'pulse1',
      pulse: { duty: 50 },
      bitDepth: 8,
      sampleRate: 22050,
      arpeggio: {
        enabled: true,
        speed: 20,
        speedUnit: 'hz',
        steps: [
          { noteOffset: 0 },
          { noteOffset: 4 },
          { noteOffset: 7 },
        ],
        mode: 'loop',
      },
      envelope: { attack: 5, decay: 200, sustain: 0, release: 50 },
    } as Partial<ChipSynthConfig>,
  },
  {
    id: 'chip-minor-arp',
    name: 'Minor Chord Arp',
    description: 'Melancholic minor arpeggio',
    category: 'lead',
    config: {
      channel: 'pulse1',
      pulse: { duty: 25 },
      bitDepth: 8,
      arpeggio: {
        enabled: true,
        speed: 18,
        speedUnit: 'hz',
        steps: [
          { noteOffset: 0 },
          { noteOffset: 3 },
          { noteOffset: 7 },
        ],
        mode: 'loop',
      },
      envelope: { attack: 5, decay: 300, sustain: 0, release: 50 },
    } as Partial<ChipSynthConfig>,
  },
  {
    id: 'chip-triangle-bass',
    name: 'Triangle Bass',
    description: 'Pure NES triangle wave bass',
    category: 'bass',
    config: {
      channel: 'triangle',
      bitDepth: 4,
      sampleRate: 22050,
      envelope: { attack: 5, decay: 400, sustain: 0, release: 100 },
    } as Partial<ChipSynthConfig>,
  },
  {
    id: 'chip-noise-kick',
    name: 'Noise Kick',
    description: 'Periodic noise drum kick',
    category: 'drum',
    config: {
      channel: 'noise',
      noise: { mode: 'periodic', period: 4 },
      bitDepth: 8,
      envelope: { attack: 0, decay: 80, sustain: 0, release: 20 },
    } as Partial<ChipSynthConfig>,
  },
  {
    id: 'chip-noise-hat',
    name: 'Noise Hi-Hat',
    description: 'White noise hi-hat',
    category: 'drum',
    config: {
      channel: 'noise',
      noise: { mode: 'white', period: 1 },
      bitDepth: 8,
      envelope: { attack: 0, decay: 50, sustain: 0, release: 10 },
    } as Partial<ChipSynthConfig>,
  },
  {
    id: 'chip-pulse-lead',
    name: 'Pulse Lead',
    description: '25% duty cycle lead',
    category: 'lead',
    config: {
      channel: 'pulse1',
      pulse: { duty: 25 },
      bitDepth: 8,
      vibrato: { speed: 6, depth: 15, delay: 150 },
      envelope: { attack: 5, decay: 500, sustain: 0, release: 100 },
    } as Partial<ChipSynthConfig>,
  },
  {
    id: 'chip-square-lead',
    name: 'Square Lead',
    description: 'Full 50% square wave',
    category: 'lead',
    config: {
      channel: 'pulse1',
      pulse: { duty: 50 },
      bitDepth: 8,
      envelope: { attack: 5, decay: 400, sustain: 0, release: 100 },
    } as Partial<ChipSynthConfig>,
  },
  {
    id: 'chip-octave-arp',
    name: 'Octave Arp',
    description: 'Fast octave switching',
    category: 'lead',
    config: {
      channel: 'pulse1',
      pulse: { duty: 50 },
      arpeggio: {
        enabled: true,
        speed: 25,
        speedUnit: 'hz',
        steps: [
          { noteOffset: 0 },
          { noteOffset: 12 },
        ],
        mode: 'loop',
      },
      envelope: { attack: 5, decay: 300, sustain: 0, release: 50 },
    } as Partial<ChipSynthConfig>,
  },
  {
    id: 'chip-power-chord',
    name: 'Power Chord',
    description: 'Fifth interval arp',
    category: 'lead',
    config: {
      channel: 'pulse1',
      pulse: { duty: 25 },
      arpeggio: {
        enabled: true,
        speed: 22,
        speedUnit: 'hz',
        steps: [
          { noteOffset: 0 },
          { noteOffset: 7 },
        ],
        mode: 'loop',
      },
      envelope: { attack: 5, decay: 350, sustain: 0, release: 50 },
    } as Partial<ChipSynthConfig>,
  },
  {
    id: 'chip-diminished',
    name: 'Diminished',
    description: 'Tense diminished arpeggio',
    category: 'lead',
    config: {
      channel: 'pulse1',
      pulse: { duty: 25 },
      arpeggio: {
        enabled: true,
        speed: 18,
        speedUnit: 'hz',
        steps: [
          { noteOffset: 0 },
          { noteOffset: 3 },
          { noteOffset: 6 },
        ],
        mode: 'loop',
      },
      envelope: { attack: 5, decay: 300, sustain: 0, release: 50 },
    } as Partial<ChipSynthConfig>,
  },
  {
    id: 'chip-mega-man',
    name: 'Mega Man',
    description: 'Capcom NES style lead',
    category: 'lead',
    config: {
      channel: 'pulse1',
      pulse: { duty: 50 },
      bitDepth: 8,
      vibrato: { speed: 8, depth: 20, delay: 100 },
      envelope: { attack: 5, decay: 600, sustain: 0, release: 100 },
    } as Partial<ChipSynthConfig>,
  },
  {
    id: 'chip-castlevania',
    name: 'Castlevania',
    description: 'Gothic NES bass sound',
    category: 'bass',
    config: {
      channel: 'pulse2',
      pulse: { duty: 12.5 },
      bitDepth: 8,
      envelope: { attack: 5, decay: 500, sustain: 0, release: 100 },
    } as Partial<ChipSynthConfig>,
  },
  {
    id: 'chip-gb-wave',
    name: 'Game Boy Wave',
    description: 'Gameboy custom wave channel',
    category: 'lead',
    config: {
      channel: 'triangle',
      bitDepth: 4,
      sampleRate: 16384,
      envelope: { attack: 5, decay: 400, sustain: 0, release: 100 },
    } as Partial<ChipSynthConfig>,
  },
  {
    id: 'chip-snare',
    name: 'Chip Snare',
    description: 'Periodic noise snare',
    category: 'drum',
    config: {
      channel: 'noise',
      noise: { mode: 'periodic', period: 8 },
      bitDepth: 8,
      envelope: { attack: 0, decay: 120, sustain: 0, release: 30 },
    } as Partial<ChipSynthConfig>,
  },
  {
    id: 'chip-sus4-arp',
    name: 'Sus4 Arp',
    description: 'Suspended 4th arpeggio',
    category: 'lead',
    config: {
      channel: 'pulse1',
      pulse: { duty: 50 },
      arpeggio: {
        enabled: true,
        speed: 20,
        speedUnit: 'hz',
        steps: [
          { noteOffset: 0 },
          { noteOffset: 5 },
          { noteOffset: 7 },
        ],
        mode: 'loop',
      },
      envelope: { attack: 5, decay: 300, sustain: 0, release: 50 },
    } as Partial<ChipSynthConfig>,
  },
  {
    id: 'chip-7th-arp',
    name: 'Major 7th Arp',
    description: 'Jazzy major 7th arpeggio',
    category: 'lead',
    config: {
      channel: 'pulse1',
      pulse: { duty: 25 },
      arpeggio: {
        enabled: true,
        speed: 16,
        speedUnit: 'hz',
        steps: [
          { noteOffset: 0 },
          { noteOffset: 4 },
          { noteOffset: 7 },
          { noteOffset: 11 },
        ],
        mode: 'loop',
      },
      envelope: { attack: 5, decay: 400, sustain: 0, release: 50 },
    } as Partial<ChipSynthConfig>,
  },
  {
    id: 'chip-pingpong',
    name: 'Ping Pong Arp',
    description: 'Bouncing ping-pong pattern',
    category: 'lead',
    config: {
      channel: 'pulse1',
      pulse: { duty: 50 },
      arpeggio: {
        enabled: true,
        speed: 18,
        speedUnit: 'hz',
        steps: [
          { noteOffset: 0 },
          { noteOffset: 4 },
          { noteOffset: 7 },
          { noteOffset: 12 },
        ],
        mode: 'pingpong',
      },
      envelope: { attack: 5, decay: 350, sustain: 0, release: 50 },
    } as Partial<ChipSynthConfig>,
  },
  {
    id: 'chip-random',
    name: 'Random Notes',
    description: 'Chaotic random arpeggio',
    category: 'fx',
    config: {
      channel: 'pulse1',
      pulse: { duty: 25 },
      arpeggio: {
        enabled: true,
        speed: 15,
        speedUnit: 'hz',
        steps: [
          { noteOffset: 0 },
          { noteOffset: 5 },
          { noteOffset: 7 },
          { noteOffset: 12 },
        ],
        mode: 'random',
      },
      envelope: { attack: 5, decay: 200, sustain: 0, release: 50 },
    } as Partial<ChipSynthConfig>,
  },
  {
    id: 'chip-thin',
    name: 'Thin Pulse',
    description: 'Nasal 12.5% duty',
    category: 'lead',
    config: {
      channel: 'pulse1',
      pulse: { duty: 12.5 },
      bitDepth: 8,
      envelope: { attack: 5, decay: 350, sustain: 0, release: 100 },
    } as Partial<ChipSynthConfig>,
  },
  {
    id: 'chip-vibrato-lead',
    name: 'Vibrato Lead',
    description: 'Expressive vibrato lead',
    category: 'lead',
    config: {
      channel: 'pulse1',
      pulse: { duty: 50 },
      bitDepth: 8,
      vibrato: { speed: 5, depth: 30, delay: 80 },
      envelope: { attack: 5, decay: 800, sustain: 0, release: 150 },
    } as Partial<ChipSynthConfig>,
  },
];

// ============================================
// SUPERSAW PRESETS (Trance / EDM)
// ============================================
export const SUPERSAW_PRESETS: SynthPreset[] = [
  {
    id: 'supersaw-classic',
    name: 'Classic Supersaw',
    description: 'JP-8000 style trance supersaw',
    category: 'lead',
    config: {
      voices: 7,
      detune: 30,
      mix: 50,
      stereoSpread: 80,
      envelope: { attack: 10, decay: 600, sustain: 0, release: 150 },
      filter: { type: 'lowpass', cutoff: 8000, resonance: 20, envelopeAmount: 0 },
    } as Partial<SuperSawConfig>,
  },
  {
    id: 'supersaw-anthem',
    name: 'Anthem Lead',
    description: 'Massive anthem-style lead',
    category: 'lead',
    config: {
      voices: 9,
      detune: 40,
      mix: 60,
      stereoSpread: 100,
      envelope: { attack: 20, decay: 800, sustain: 0, release: 200 },
      filter: { type: 'lowpass', cutoff: 10000, resonance: 15, envelopeAmount: 20 },
    } as Partial<SuperSawConfig>,
  },
  {
    id: 'supersaw-bass',
    name: 'Supersaw Bass',
    description: 'Thick detuned bass',
    category: 'bass',
    config: {
      voices: 5,
      detune: 15,
      mix: 70,
      stereoSpread: 30,
      envelope: { attack: 5, decay: 400, sustain: 0, release: 80 },
      filter: { type: 'lowpass', cutoff: 2000, resonance: 30, envelopeAmount: 40 },
    } as Partial<SuperSawConfig>,
  },
  {
    id: 'supersaw-pad',
    name: 'Supersaw Pad',
    description: 'Lush evolving pad',
    category: 'pad',
    config: {
      voices: 7,
      detune: 25,
      mix: 50,
      stereoSpread: 90,
      envelope: { attack: 500, decay: 2000, sustain: 60, release: 1000 },
      filter: { type: 'lowpass', cutoff: 6000, resonance: 10, envelopeAmount: -30 },
    } as Partial<SuperSawConfig>,
  },
  {
    id: 'supersaw-stab',
    name: 'Stab',
    description: 'Short punchy stab',
    category: 'lead',
    config: {
      voices: 7,
      detune: 35,
      mix: 55,
      stereoSpread: 70,
      envelope: { attack: 5, decay: 200, sustain: 0, release: 50 },
      filter: { type: 'lowpass', cutoff: 12000, resonance: 10, envelopeAmount: 0 },
    } as Partial<SuperSawConfig>,
  },
  {
    id: 'supersaw-minimal',
    name: 'Minimal Saw',
    description: 'Less voices, tighter sound',
    category: 'lead',
    config: {
      voices: 3,
      detune: 10,
      mix: 50,
      stereoSpread: 40,
      envelope: { attack: 10, decay: 400, sustain: 0, release: 100 },
      filter: { type: 'lowpass', cutoff: 5000, resonance: 25, envelopeAmount: 30 },
    } as Partial<SuperSawConfig>,
  },
  {
    id: 'supersaw-wide',
    name: 'Ultra Wide',
    description: 'Maximum stereo spread',
    category: 'lead',
    config: {
      voices: 9,
      detune: 50,
      mix: 45,
      stereoSpread: 100,
      envelope: { attack: 15, decay: 700, sustain: 0, release: 180 },
      filter: { type: 'lowpass', cutoff: 9000, resonance: 15, envelopeAmount: 10 },
    } as Partial<SuperSawConfig>,
  },
  {
    id: 'supersaw-dark',
    name: 'Dark Supersaw',
    description: 'Filtered dark trance',
    category: 'lead',
    config: {
      voices: 7,
      detune: 30,
      mix: 55,
      stereoSpread: 75,
      envelope: { attack: 10, decay: 500, sustain: 0, release: 120 },
      filter: { type: 'lowpass', cutoff: 3500, resonance: 35, envelopeAmount: 50 },
    } as Partial<SuperSawConfig>,
  },
  {
    id: 'supersaw-bright',
    name: 'Bright Saw',
    description: 'Cutting bright lead',
    category: 'lead',
    config: {
      voices: 7,
      detune: 28,
      mix: 50,
      stereoSpread: 80,
      envelope: { attack: 8, decay: 550, sustain: 0, release: 130 },
      filter: { type: 'highpass', cutoff: 200, resonance: 10, envelopeAmount: 0 },
    } as Partial<SuperSawConfig>,
  },
  {
    id: 'supersaw-pluck',
    name: 'Saw Pluck',
    description: 'Short plucky supersaw',
    category: 'pluck',
    config: {
      voices: 5,
      detune: 20,
      mix: 50,
      stereoSpread: 60,
      envelope: { attack: 3, decay: 150, sustain: 0, release: 40 },
      filter: { type: 'lowpass', cutoff: 8000, resonance: 20, envelopeAmount: 60 },
    } as Partial<SuperSawConfig>,
  },
  {
    id: 'supersaw-uplifting',
    name: 'Uplifting',
    description: 'Epic uplifting trance',
    category: 'lead',
    config: {
      voices: 7,
      detune: 32,
      mix: 52,
      stereoSpread: 85,
      envelope: { attack: 12, decay: 650, sustain: 0, release: 160 },
      filter: { type: 'lowpass', cutoff: 7500, resonance: 18, envelopeAmount: 25 },
    } as Partial<SuperSawConfig>,
  },
  {
    id: 'supersaw-progressive',
    name: 'Progressive',
    description: 'Prog house supersaw',
    category: 'lead',
    config: {
      voices: 5,
      detune: 22,
      mix: 60,
      stereoSpread: 65,
      envelope: { attack: 15, decay: 500, sustain: 0, release: 120 },
      filter: { type: 'lowpass', cutoff: 6000, resonance: 22, envelopeAmount: 35 },
    } as Partial<SuperSawConfig>,
  },
  {
    id: 'supersaw-hard',
    name: 'Hardstyle',
    description: 'Hard-hitting hardstyle',
    category: 'lead',
    config: {
      voices: 7,
      detune: 38,
      mix: 50,
      stereoSpread: 75,
      envelope: { attack: 5, decay: 350, sustain: 0, release: 80 },
      filter: { type: 'lowpass', cutoff: 5500, resonance: 30, envelopeAmount: 45 },
    } as Partial<SuperSawConfig>,
  },
  {
    id: 'supersaw-euphoric',
    name: 'Euphoric',
    description: 'Euphoric hardstyle',
    category: 'lead',
    config: {
      voices: 9,
      detune: 35,
      mix: 48,
      stereoSpread: 90,
      envelope: { attack: 10, decay: 600, sustain: 0, release: 150 },
      filter: { type: 'lowpass', cutoff: 8500, resonance: 12, envelopeAmount: 15 },
    } as Partial<SuperSawConfig>,
  },
  {
    id: 'supersaw-layer',
    name: 'Layer Saw',
    description: 'Good for layering',
    category: 'lead',
    config: {
      voices: 5,
      detune: 18,
      mix: 55,
      stereoSpread: 50,
      envelope: { attack: 8, decay: 450, sustain: 0, release: 100 },
      filter: { type: 'bandpass', cutoff: 4000, resonance: 15, envelopeAmount: 0 },
    } as Partial<SuperSawConfig>,
  },
  {
    id: 'supersaw-vocal',
    name: 'Vocal Saw',
    description: 'Voice-like quality',
    category: 'lead',
    config: {
      voices: 7,
      detune: 25,
      mix: 50,
      stereoSpread: 70,
      envelope: { attack: 50, decay: 800, sustain: 0, release: 200 },
      filter: { type: 'bandpass', cutoff: 2500, resonance: 30, envelopeAmount: 20 },
    } as Partial<SuperSawConfig>,
  },
  {
    id: 'supersaw-mono',
    name: 'Mono Lead',
    description: 'Center-focused lead',
    category: 'lead',
    config: {
      voices: 7,
      detune: 30,
      mix: 70,
      stereoSpread: 0,
      envelope: { attack: 5, decay: 500, sustain: 0, release: 100 },
      filter: { type: 'lowpass', cutoff: 7000, resonance: 20, envelopeAmount: 30 },
    } as Partial<SuperSawConfig>,
  },
  {
    id: 'supersaw-acid',
    name: 'Acid Saw',
    description: 'Resonant filter sweep',
    category: 'lead',
    config: {
      voices: 5,
      detune: 20,
      mix: 50,
      stereoSpread: 60,
      envelope: { attack: 5, decay: 400, sustain: 0, release: 80 },
      filter: { type: 'lowpass', cutoff: 2000, resonance: 60, envelopeAmount: 70 },
    } as Partial<SuperSawConfig>,
  },
  {
    id: 'supersaw-dreamy',
    name: 'Dreamy',
    description: 'Ethereal dream trance',
    category: 'pad',
    config: {
      voices: 9,
      detune: 35,
      mix: 45,
      stereoSpread: 95,
      envelope: { attack: 300, decay: 1500, sustain: 40, release: 800 },
      filter: { type: 'lowpass', cutoff: 5000, resonance: 15, envelopeAmount: -20 },
    } as Partial<SuperSawConfig>,
  },
  {
    id: 'supersaw-gritty',
    name: 'Gritty Saw',
    description: 'Aggressive and raw',
    category: 'lead',
    config: {
      voices: 7,
      detune: 45,
      mix: 55,
      stereoSpread: 70,
      envelope: { attack: 3, decay: 350, sustain: 0, release: 60 },
      filter: { type: 'lowpass', cutoff: 4500, resonance: 40, envelopeAmount: 50 },
    } as Partial<SuperSawConfig>,
  },
];

// ============================================
// ORGAN PRESETS (Hammond B3 Style)
// ============================================
export const ORGAN_PRESETS: SynthPreset[] = [
  {
    id: 'organ-rock',
    name: 'Rock Organ',
    description: 'Classic rock 888000000',
    category: 'key',
    config: {
      drawbars: [8, 8, 8, 0, 0, 0, 0, 0, 0],
      percussion: { enabled: false, volume: 50, decay: 'fast', harmonic: 'third' },
      keyClick: 30,
      rotary: { enabled: true, speed: 'slow' },
    } as Partial<OrganConfig>,
  },
  {
    id: 'organ-gospel',
    name: 'Gospel Full',
    description: 'Full gospel drawbars',
    category: 'key',
    config: {
      drawbars: [8, 8, 8, 8, 8, 8, 8, 8, 8],
      percussion: { enabled: true, volume: 70, decay: 'fast', harmonic: 'third' },
      keyClick: 50,
      rotary: { enabled: true, speed: 'fast' },
    } as Partial<OrganConfig>,
  },
  {
    id: 'organ-jazz',
    name: 'Jazz Combo',
    description: 'Smooth jazz setting',
    category: 'key',
    config: {
      drawbars: [8, 0, 8, 0, 0, 0, 0, 0, 0],
      percussion: { enabled: true, volume: 60, decay: 'slow', harmonic: 'second' },
      keyClick: 20,
      rotary: { enabled: true, speed: 'slow' },
    } as Partial<OrganConfig>,
  },
  {
    id: 'organ-blues',
    name: 'Blues Grind',
    description: 'Gritty blues tone',
    category: 'key',
    config: {
      drawbars: [8, 8, 6, 4, 0, 0, 0, 0, 0],
      percussion: { enabled: false, volume: 50, decay: 'fast', harmonic: 'third' },
      keyClick: 40,
      rotary: { enabled: true, speed: 'fast' },
    } as Partial<OrganConfig>,
  },
  {
    id: 'organ-theatre',
    name: 'Theatre Organ',
    description: 'Big Wurlitzer style',
    category: 'key',
    config: {
      drawbars: [6, 8, 8, 6, 4, 6, 4, 4, 4],
      percussion: { enabled: false, volume: 50, decay: 'fast', harmonic: 'third' },
      keyClick: 10,
      rotary: { enabled: false, speed: 'slow' },
    } as Partial<OrganConfig>,
  },
  {
    id: 'organ-ballad',
    name: 'Ballad',
    description: 'Soft romantic setting',
    category: 'key',
    config: {
      drawbars: [0, 0, 8, 8, 0, 0, 0, 0, 0],
      percussion: { enabled: true, volume: 40, decay: 'slow', harmonic: 'second' },
      keyClick: 15,
      rotary: { enabled: true, speed: 'slow' },
    } as Partial<OrganConfig>,
  },
  {
    id: 'organ-ska',
    name: 'Ska Bubble',
    description: 'Bouncy ska/reggae',
    category: 'key',
    config: {
      drawbars: [8, 6, 8, 0, 0, 0, 0, 0, 0],
      percussion: { enabled: true, volume: 80, decay: 'fast', harmonic: 'third' },
      keyClick: 60,
      rotary: { enabled: false, speed: 'slow' },
    } as Partial<OrganConfig>,
  },
  {
    id: 'organ-prog',
    name: 'Prog Rock',
    description: 'ELP/Yes style',
    category: 'key',
    config: {
      drawbars: [8, 8, 8, 8, 0, 0, 0, 0, 8],
      percussion: { enabled: true, volume: 60, decay: 'fast', harmonic: 'third' },
      keyClick: 35,
      rotary: { enabled: true, speed: 'fast' },
    } as Partial<OrganConfig>,
  },
  {
    id: 'organ-church',
    name: 'Church',
    description: 'Pipe organ style',
    category: 'key',
    config: {
      drawbars: [8, 4, 8, 4, 8, 4, 4, 4, 4],
      percussion: { enabled: false, volume: 50, decay: 'fast', harmonic: 'third' },
      keyClick: 5,
      rotary: { enabled: false, speed: 'slow' },
    } as Partial<OrganConfig>,
  },
  {
    id: 'organ-funk',
    name: 'Funk Clavinet',
    description: 'Clavinet-ish funk',
    category: 'key',
    config: {
      drawbars: [0, 0, 8, 8, 8, 0, 0, 0, 0],
      percussion: { enabled: true, volume: 90, decay: 'fast', harmonic: 'second' },
      keyClick: 70,
      rotary: { enabled: false, speed: 'slow' },
    } as Partial<OrganConfig>,
  },
  {
    id: 'organ-soul',
    name: 'Soul',
    description: 'Motown soul organ',
    category: 'key',
    config: {
      drawbars: [8, 8, 4, 0, 0, 0, 0, 0, 0],
      percussion: { enabled: true, volume: 50, decay: 'fast', harmonic: 'third' },
      keyClick: 25,
      rotary: { enabled: true, speed: 'slow' },
    } as Partial<OrganConfig>,
  },
  {
    id: 'organ-booker-t',
    name: 'Booker T',
    description: 'Green Onions style',
    category: 'key',
    config: {
      drawbars: [8, 8, 8, 0, 0, 0, 0, 0, 0],
      percussion: { enabled: false, volume: 50, decay: 'fast', harmonic: 'third' },
      keyClick: 45,
      rotary: { enabled: true, speed: 'slow' },
    } as Partial<OrganConfig>,
  },
  {
    id: 'organ-deep-purple',
    name: 'Deep Purple',
    description: 'Jon Lord style',
    category: 'key',
    config: {
      drawbars: [8, 8, 8, 8, 0, 0, 0, 4, 0],
      percussion: { enabled: true, volume: 65, decay: 'fast', harmonic: 'third' },
      keyClick: 55,
      rotary: { enabled: true, speed: 'fast' },
    } as Partial<OrganConfig>,
  },
  {
    id: 'organ-whiter-shade',
    name: 'Whiter Shade',
    description: 'Procol Harum style',
    category: 'key',
    config: {
      drawbars: [8, 8, 8, 0, 0, 4, 0, 4, 0],
      percussion: { enabled: false, volume: 50, decay: 'fast', harmonic: 'third' },
      keyClick: 20,
      rotary: { enabled: true, speed: 'slow' },
    } as Partial<OrganConfig>,
  },
  {
    id: 'organ-doors',
    name: 'The Doors',
    description: 'Ray Manzarek style',
    category: 'key',
    config: {
      drawbars: [8, 8, 8, 6, 0, 0, 0, 0, 0],
      percussion: { enabled: true, volume: 55, decay: 'fast', harmonic: 'second' },
      keyClick: 40,
      rotary: { enabled: true, speed: 'slow' },
    } as Partial<OrganConfig>,
  },
  {
    id: 'organ-purdie',
    name: 'Purdie Shuffle',
    description: 'R&B shuffle organ',
    category: 'key',
    config: {
      drawbars: [8, 6, 8, 4, 0, 0, 0, 0, 0],
      percussion: { enabled: true, volume: 60, decay: 'fast', harmonic: 'third' },
      keyClick: 35,
      rotary: { enabled: true, speed: 'fast' },
    } as Partial<OrganConfig>,
  },
  {
    id: 'organ-leslie-slow',
    name: 'Leslie Slow',
    description: 'Gentle Leslie rotation',
    category: 'key',
    config: {
      drawbars: [8, 8, 6, 0, 0, 0, 0, 0, 0],
      percussion: { enabled: false, volume: 50, decay: 'fast', harmonic: 'third' },
      keyClick: 25,
      vibrato: { type: 'C3', depth: 60 },
      rotary: { enabled: true, speed: 'slow' },
    } as Partial<OrganConfig>,
  },
  {
    id: 'organ-leslie-fast',
    name: 'Leslie Fast',
    description: 'Spinning Leslie effect',
    category: 'key',
    config: {
      drawbars: [8, 8, 8, 0, 0, 0, 0, 0, 0],
      percussion: { enabled: false, volume: 50, decay: 'fast', harmonic: 'third' },
      keyClick: 30,
      vibrato: { type: 'C3', depth: 70 },
      rotary: { enabled: true, speed: 'fast' },
    } as Partial<OrganConfig>,
  },
  {
    id: 'organ-flute',
    name: 'Flute Stop',
    description: '8ft flute only',
    category: 'key',
    config: {
      drawbars: [0, 0, 8, 0, 0, 0, 0, 0, 0],
      percussion: { enabled: false, volume: 50, decay: 'fast', harmonic: 'third' },
      keyClick: 10,
      rotary: { enabled: true, speed: 'slow' },
    } as Partial<OrganConfig>,
  },
  {
    id: 'organ-full-stop',
    name: 'Full Stops',
    description: 'All harmonics equal',
    category: 'key',
    config: {
      drawbars: [8, 8, 8, 8, 8, 8, 8, 8, 8],
      percussion: { enabled: false, volume: 50, decay: 'fast', harmonic: 'third' },
      keyClick: 40,
      rotary: { enabled: true, speed: 'slow' },
    } as Partial<OrganConfig>,
  },
];

// ============================================
// DRUM MACHINE PRESETS (808/909)
// ============================================
export const DRUM_MACHINE_PRESETS: SynthPreset[] = [
  {
    id: 'drum-909-kick',
    name: '909 Kick',
    description: 'Classic TR-909 kick',
    category: 'drum',
    config: {
      drumType: 'kick',
      machineType: '909',
      kick: { pitch: 80, decay: 300, drive: 50, envAmount: 2.5, envDuration: 50, filterFreq: 3000 },
    } as Partial<DrumMachineConfig>,
  },
  {
    id: 'drum-808-kick',
    name: '808 Kick',
    description: 'Booming TR-808 kick',
    category: 'drum',
    config: {
      drumType: 'kick',
      machineType: '808',
      kick: { pitch: 48, decay: 400, drive: 60, envAmount: 2.0, envDuration: 110, filterFreq: 250 },
    } as Partial<DrumMachineConfig>,
  },
  {
    id: 'drum-909-snare',
    name: '909 Snare',
    description: 'Punchy TR-909 snare',
    category: 'drum',
    config: {
      drumType: 'snare',
      machineType: '909',
      snare: { pitch: 220, decay: 100, snappy: 70, envAmount: 4.0, filterType: 'notch', filterFreq: 1000 },
    } as Partial<DrumMachineConfig>,
  },
  {
    id: 'drum-808-snare',
    name: '808 Snare',
    description: 'Crisp TR-808 snare',
    category: 'drum',
    config: {
      drumType: 'snare',
      machineType: '808',
      snare: { pitch: 238, decay: 100, snappy: 60, envAmount: 1.0, filterType: 'highpass', filterFreq: 1000 },
    } as Partial<DrumMachineConfig>,
  },
  {
    id: 'drum-909-clap',
    name: '909 Clap',
    description: 'Filtered noise clap',
    category: 'drum',
    config: {
      drumType: 'clap',
      machineType: '909',
      clap: { tone: 55, decay: 80, spread: 10, filterFreqs: [900, 1200], modulatorFreq: 40 },
    } as Partial<DrumMachineConfig>,
  },
  {
    id: 'drum-808-clap',
    name: '808 Clap',
    description: 'Classic 808 clap',
    category: 'drum',
    config: {
      drumType: 'clap',
      machineType: '808',
      clap: { tone: 50, decay: 115, spread: 100, filterFreqs: [1000, 1000], modulatorFreq: 10 },
    } as Partial<DrumMachineConfig>,
  },
  {
    id: 'drum-closed-hat',
    name: 'Closed Hat',
    description: 'Tight closed hi-hat',
    category: 'drum',
    config: {
      drumType: 'hihat',
      machineType: '808',
      hihat: { tone: 60, decay: 50, metallic: 60 },
    } as Partial<DrumMachineConfig>,
  },
  {
    id: 'drum-open-hat',
    name: 'Open Hat',
    description: 'Sustaining open hi-hat',
    category: 'drum',
    config: {
      drumType: 'hihat',
      machineType: '808',
      hihat: { tone: 50, decay: 300, metallic: 50 },
    } as Partial<DrumMachineConfig>,
  },
  {
    id: 'drum-low-tom',
    name: 'Low Tom',
    description: 'Deep floor tom',
    category: 'drum',
    config: {
      drumType: 'tom',
      machineType: '808',
      tom: { pitch: 100, decay: 250, tone: 10, envAmount: 2.0, envDuration: 100 },
    } as Partial<DrumMachineConfig>,
  },
  {
    id: 'drum-mid-tom',
    name: 'Mid Tom',
    description: 'Medium tom',
    category: 'drum',
    config: {
      drumType: 'tom',
      machineType: '808',
      tom: { pitch: 150, decay: 200, tone: 8, envAmount: 2.0, envDuration: 100 },
    } as Partial<DrumMachineConfig>,
  },
  {
    id: 'drum-high-tom',
    name: 'High Tom',
    description: 'High rack tom',
    category: 'drum',
    config: {
      drumType: 'tom',
      machineType: '808',
      tom: { pitch: 200, decay: 180, tone: 5, envAmount: 2.0, envDuration: 100 },
    } as Partial<DrumMachineConfig>,
  },
  {
    id: 'drum-cowbell',
    name: 'Cowbell',
    description: '808 cowbell',
    category: 'drum',
    config: {
      drumType: 'cowbell',
      machineType: '808',
      cowbell: { decay: 400, filterFreq: 2640 },
    } as Partial<DrumMachineConfig>,
  },
  {
    id: 'drum-rimshot',
    name: 'Rimshot',
    description: 'Resonant rim click',
    category: 'drum',
    config: {
      drumType: 'rimshot',
      machineType: '909',
      rimshot: { decay: 30, filterFreqs: [220, 500, 950], filterQ: 10.5, saturation: 3.0 },
    } as Partial<DrumMachineConfig>,
  },
  {
    id: 'drum-clave',
    name: 'Clave',
    description: '808 wood clave',
    category: 'drum',
    config: {
      drumType: 'clave',
      machineType: '808',
      clave: { decay: 40, pitch: 2450, pitchSecondary: 1750, filterFreq: 2450 },
    } as Partial<DrumMachineConfig>,
  },
  {
    id: 'drum-conga-low',
    name: 'Low Conga',
    description: '808 tumba',
    category: 'drum',
    config: {
      drumType: 'conga',
      machineType: '808',
      conga: { pitch: 195, decay: 180, tuning: 0 },
    } as Partial<DrumMachineConfig>,
  },
  {
    id: 'drum-conga-mid',
    name: 'Mid Conga',
    description: '808 conga',
    category: 'drum',
    config: {
      drumType: 'conga',
      machineType: '808',
      conga: { pitch: 280, decay: 180, tuning: 50 },
    } as Partial<DrumMachineConfig>,
  },
  {
    id: 'drum-conga-high',
    name: 'High Conga',
    description: '808 quinto',
    category: 'drum',
    config: {
      drumType: 'conga',
      machineType: '808',
      conga: { pitch: 410, decay: 180, tuning: 100 },
    } as Partial<DrumMachineConfig>,
  },
  {
    id: 'drum-maracas',
    name: 'Maracas',
    description: '808 shaker',
    category: 'drum',
    config: {
      drumType: 'maracas',
      machineType: '808',
      maracas: { decay: 30, filterFreq: 5000 },
    } as Partial<DrumMachineConfig>,
  },
  {
    id: 'drum-cymbal',
    name: 'Crash Cymbal',
    description: '808 crash',
    category: 'drum',
    config: {
      drumType: 'cymbal',
      machineType: '808',
      cymbal: { tone: 50, decay: 3000 },
    } as Partial<DrumMachineConfig>,
  },
  {
    id: 'drum-trap-kick',
    name: 'Trap Kick',
    description: '808 sub kick for trap',
    category: 'drum',
    config: {
      drumType: 'kick',
      machineType: '808',
      kick: { pitch: 40, decay: 600, drive: 40, envAmount: 3.0, envDuration: 150, filterFreq: 200 },
    } as Partial<DrumMachineConfig>,
  },
];

// ============================================
// PWM SYNTH PRESETS
// ============================================
export const PWM_SYNTH_PRESETS: SynthPreset[] = [
  {
    id: 'pwm-classic',
    name: 'Classic PWM',
    description: 'Warm analog-style PWM',
    category: 'pad',
    config: {
      pulseWidth: 50,
      pwmDepth: 40,
      pwmRate: 1.5,
      pwmWaveform: 'sine',
      oscillators: 2,
      detune: 8,
      envelope: { attack: 100, decay: 800, sustain: 0, release: 300 },
      filter: { type: 'lowpass', cutoff: 5000, resonance: 20, envelopeAmount: 30, keyTracking: 50 },
    } as Partial<PWMSynthConfig>,
  },
  {
    id: 'pwm-strings',
    name: 'PWM Strings',
    description: 'String ensemble emulation',
    category: 'string',
    config: {
      pulseWidth: 50,
      pwmDepth: 50,
      pwmRate: 3,
      pwmWaveform: 'triangle',
      oscillators: 3,
      detune: 15,
      envelope: { attack: 200, decay: 1000, sustain: 70, release: 500 },
      filter: { type: 'lowpass', cutoff: 6000, resonance: 10, envelopeAmount: 20, keyTracking: 60 },
    } as Partial<PWMSynthConfig>,
  },
  {
    id: 'pwm-bass',
    name: 'PWM Bass',
    description: 'Fat PWM bass',
    category: 'bass',
    config: {
      pulseWidth: 40,
      pwmDepth: 20,
      pwmRate: 2,
      pwmWaveform: 'sine',
      oscillators: 2,
      detune: 5,
      envelope: { attack: 5, decay: 400, sustain: 0, release: 100 },
      filter: { type: 'lowpass', cutoff: 2000, resonance: 40, envelopeAmount: 50, keyTracking: 30 },
    } as Partial<PWMSynthConfig>,
  },
  {
    id: 'pwm-lead',
    name: 'PWM Lead',
    description: 'Cutting PWM lead',
    category: 'lead',
    config: {
      pulseWidth: 30,
      pwmDepth: 30,
      pwmRate: 4,
      pwmWaveform: 'sawtooth',
      oscillators: 2,
      detune: 10,
      envelope: { attack: 10, decay: 500, sustain: 0, release: 150 },
      filter: { type: 'lowpass', cutoff: 8000, resonance: 25, envelopeAmount: 40, keyTracking: 70 },
    } as Partial<PWMSynthConfig>,
  },
  {
    id: 'pwm-pad',
    name: 'Lush Pad',
    description: 'Evolving pad sound',
    category: 'pad',
    config: {
      pulseWidth: 50,
      pwmDepth: 60,
      pwmRate: 0.5,
      pwmWaveform: 'sine',
      oscillators: 3,
      detune: 20,
      envelope: { attack: 500, decay: 2000, sustain: 60, release: 1000 },
      filter: { type: 'lowpass', cutoff: 4000, resonance: 15, envelopeAmount: -20, keyTracking: 40 },
    } as Partial<PWMSynthConfig>,
  },
  {
    id: 'pwm-pluck',
    name: 'PWM Pluck',
    description: 'Short plucky sound',
    category: 'pluck',
    config: {
      pulseWidth: 25,
      pwmDepth: 10,
      pwmRate: 8,
      pwmWaveform: 'sine',
      oscillators: 1,
      detune: 0,
      envelope: { attack: 2, decay: 150, sustain: 0, release: 50 },
      filter: { type: 'lowpass', cutoff: 6000, resonance: 30, envelopeAmount: 60, keyTracking: 80 },
    } as Partial<PWMSynthConfig>,
  },
  {
    id: 'pwm-hollow',
    name: 'Hollow',
    description: 'Thin hollow sound',
    category: 'lead',
    config: {
      pulseWidth: 10,
      pwmDepth: 80,
      pwmRate: 2,
      pwmWaveform: 'triangle',
      oscillators: 2,
      detune: 12,
      envelope: { attack: 50, decay: 600, sustain: 0, release: 200 },
      filter: { type: 'bandpass', cutoff: 3000, resonance: 40, envelopeAmount: 30, keyTracking: 60 },
    } as Partial<PWMSynthConfig>,
  },
  {
    id: 'pwm-wide',
    name: 'Wide PWM',
    description: 'Stereo detuned PWM',
    category: 'pad',
    config: {
      pulseWidth: 50,
      pwmDepth: 45,
      pwmRate: 1,
      pwmWaveform: 'sine',
      oscillators: 3,
      detune: 30,
      envelope: { attack: 150, decay: 1000, sustain: 50, release: 400 },
      filter: { type: 'lowpass', cutoff: 5500, resonance: 18, envelopeAmount: 25, keyTracking: 50 },
    } as Partial<PWMSynthConfig>,
  },
  {
    id: 'pwm-slow',
    name: 'Slow Mod',
    description: 'Very slow PWM movement',
    category: 'pad',
    config: {
      pulseWidth: 50,
      pwmDepth: 70,
      pwmRate: 0.2,
      pwmWaveform: 'sine',
      oscillators: 2,
      detune: 10,
      envelope: { attack: 300, decay: 1500, sustain: 40, release: 600 },
      filter: { type: 'lowpass', cutoff: 4500, resonance: 12, envelopeAmount: -15, keyTracking: 45 },
    } as Partial<PWMSynthConfig>,
  },
  {
    id: 'pwm-fast',
    name: 'Fast Mod',
    description: 'Rapid PWM modulation',
    category: 'lead',
    config: {
      pulseWidth: 50,
      pwmDepth: 50,
      pwmRate: 10,
      pwmWaveform: 'sine',
      oscillators: 1,
      detune: 0,
      envelope: { attack: 10, decay: 400, sustain: 0, release: 100 },
      filter: { type: 'lowpass', cutoff: 7000, resonance: 20, envelopeAmount: 35, keyTracking: 60 },
    } as Partial<PWMSynthConfig>,
  },
  {
    id: 'pwm-bright',
    name: 'Bright PWM',
    description: 'Unfiltered bright tone',
    category: 'lead',
    config: {
      pulseWidth: 25,
      pwmDepth: 35,
      pwmRate: 3,
      pwmWaveform: 'triangle',
      oscillators: 2,
      detune: 8,
      envelope: { attack: 5, decay: 500, sustain: 0, release: 120 },
      filter: { type: 'lowpass', cutoff: 15000, resonance: 5, envelopeAmount: 0, keyTracking: 50 },
    } as Partial<PWMSynthConfig>,
  },
  {
    id: 'pwm-dark',
    name: 'Dark PWM',
    description: 'Muffled dark tone',
    category: 'bass',
    config: {
      pulseWidth: 60,
      pwmDepth: 25,
      pwmRate: 1,
      pwmWaveform: 'sine',
      oscillators: 2,
      detune: 6,
      envelope: { attack: 20, decay: 600, sustain: 0, release: 150 },
      filter: { type: 'lowpass', cutoff: 1500, resonance: 35, envelopeAmount: 40, keyTracking: 20 },
    } as Partial<PWMSynthConfig>,
  },
  {
    id: 'pwm-resonant',
    name: 'Resonant PWM',
    description: 'High resonance sweep',
    category: 'lead',
    config: {
      pulseWidth: 40,
      pwmDepth: 40,
      pwmRate: 2,
      pwmWaveform: 'sine',
      oscillators: 2,
      detune: 10,
      envelope: { attack: 10, decay: 450, sustain: 0, release: 120 },
      filter: { type: 'lowpass', cutoff: 3000, resonance: 70, envelopeAmount: 60, keyTracking: 70 },
    } as Partial<PWMSynthConfig>,
  },
  {
    id: 'pwm-sync',
    name: 'Sync-ish',
    description: 'Hard sync-like character',
    category: 'lead',
    config: {
      pulseWidth: 20,
      pwmDepth: 60,
      pwmRate: 6,
      pwmWaveform: 'sawtooth',
      oscillators: 2,
      detune: 25,
      envelope: { attack: 5, decay: 350, sustain: 0, release: 80 },
      filter: { type: 'lowpass', cutoff: 4500, resonance: 45, envelopeAmount: 55, keyTracking: 65 },
    } as Partial<PWMSynthConfig>,
  },
  {
    id: 'pwm-choir',
    name: 'Choir',
    description: 'Voice-like pad',
    category: 'pad',
    config: {
      pulseWidth: 50,
      pwmDepth: 55,
      pwmRate: 1.2,
      pwmWaveform: 'sine',
      oscillators: 3,
      detune: 18,
      envelope: { attack: 400, decay: 1500, sustain: 55, release: 700 },
      filter: { type: 'bandpass', cutoff: 2000, resonance: 25, envelopeAmount: 15, keyTracking: 55 },
    } as Partial<PWMSynthConfig>,
  },
  {
    id: 'pwm-vintage',
    name: 'Vintage',
    description: 'Prophet-5 style',
    category: 'pad',
    config: {
      pulseWidth: 45,
      pwmDepth: 35,
      pwmRate: 2.5,
      pwmWaveform: 'triangle',
      oscillators: 2,
      detune: 7,
      envelope: { attack: 80, decay: 700, sustain: 30, release: 300 },
      filter: { type: 'lowpass', cutoff: 4800, resonance: 22, envelopeAmount: 35, keyTracking: 55 },
    } as Partial<PWMSynthConfig>,
  },
  {
    id: 'pwm-mono',
    name: 'Mono PWM',
    description: 'Single osc mono',
    category: 'lead',
    config: {
      pulseWidth: 50,
      pwmDepth: 40,
      pwmRate: 3,
      pwmWaveform: 'sine',
      oscillators: 1,
      detune: 0,
      envelope: { attack: 5, decay: 400, sustain: 0, release: 100 },
      filter: { type: 'lowpass', cutoff: 6000, resonance: 30, envelopeAmount: 45, keyTracking: 60 },
    } as Partial<PWMSynthConfig>,
  },
  {
    id: 'pwm-thick',
    name: 'Thick',
    description: 'Three oscillator thick',
    category: 'bass',
    config: {
      pulseWidth: 50,
      pwmDepth: 30,
      pwmRate: 1.8,
      pwmWaveform: 'sine',
      oscillators: 3,
      detune: 12,
      envelope: { attack: 10, decay: 500, sustain: 0, release: 120 },
      filter: { type: 'lowpass', cutoff: 2500, resonance: 35, envelopeAmount: 45, keyTracking: 40 },
    } as Partial<PWMSynthConfig>,
  },
  {
    id: 'pwm-ethereal',
    name: 'Ethereal',
    description: 'Dreamy slow pad',
    category: 'pad',
    config: {
      pulseWidth: 50,
      pwmDepth: 65,
      pwmRate: 0.3,
      pwmWaveform: 'sine',
      oscillators: 3,
      detune: 25,
      envelope: { attack: 800, decay: 3000, sustain: 50, release: 1500 },
      filter: { type: 'lowpass', cutoff: 3500, resonance: 10, envelopeAmount: -25, keyTracking: 35 },
    } as Partial<PWMSynthConfig>,
  },
  {
    id: 'pwm-key',
    name: 'PWM Keys',
    description: 'Electric piano-ish',
    category: 'key',
    config: {
      pulseWidth: 35,
      pwmDepth: 15,
      pwmRate: 5,
      pwmWaveform: 'sine',
      oscillators: 2,
      detune: 5,
      envelope: { attack: 5, decay: 300, sustain: 20, release: 200 },
      filter: { type: 'lowpass', cutoff: 5000, resonance: 20, envelopeAmount: 50, keyTracking: 80 },
    } as Partial<PWMSynthConfig>,
  },
];

// ============================================
// STRING MACHINE PRESETS
// ============================================
export const STRING_MACHINE_PRESETS: SynthPreset[] = [
  {
    id: 'string-full',
    name: 'Full Orchestra',
    description: 'All sections balanced',
    category: 'string',
    config: {
      sections: { violin: 100, viola: 80, cello: 70, bass: 60 },
      ensemble: { depth: 60, rate: 3, voices: 4 },
      attack: 200,
      release: 1000,
      brightness: 60,
    } as Partial<StringMachineConfig>,
  },
  {
    id: 'string-violin',
    name: 'Violin Solo',
    description: 'High strings only',
    category: 'string',
    config: {
      sections: { violin: 100, viola: 30, cello: 0, bass: 0 },
      ensemble: { depth: 40, rate: 4, voices: 3 },
      attack: 100,
      release: 800,
      brightness: 80,
    } as Partial<StringMachineConfig>,
  },
  {
    id: 'string-cello',
    name: 'Cello Section',
    description: 'Rich cello tone',
    category: 'string',
    config: {
      sections: { violin: 0, viola: 40, cello: 100, bass: 50 },
      ensemble: { depth: 50, rate: 2.5, voices: 4 },
      attack: 250,
      release: 1200,
      brightness: 50,
    } as Partial<StringMachineConfig>,
  },
  {
    id: 'string-bass',
    name: 'Bass Section',
    description: 'Deep string bass',
    category: 'bass',
    config: {
      sections: { violin: 0, viola: 0, cello: 30, bass: 100 },
      ensemble: { depth: 30, rate: 2, voices: 3 },
      attack: 300,
      release: 1500,
      brightness: 30,
    } as Partial<StringMachineConfig>,
  },
  {
    id: 'string-chamber',
    name: 'Chamber Strings',
    description: 'Small ensemble',
    category: 'string',
    config: {
      sections: { violin: 80, viola: 70, cello: 60, bass: 40 },
      ensemble: { depth: 35, rate: 3.5, voices: 2 },
      attack: 150,
      release: 900,
      brightness: 65,
    } as Partial<StringMachineConfig>,
  },
  {
    id: 'string-solina',
    name: 'Solina Strings',
    description: 'Classic ensemble machine',
    category: 'string',
    config: {
      sections: { violin: 100, viola: 80, cello: 60, bass: 40 },
      ensemble: { depth: 70, rate: 6, voices: 6 },
      attack: 80,
      release: 600,
      brightness: 70,
    } as Partial<StringMachineConfig>,
  },
  {
    id: 'string-warm',
    name: 'Warm Strings',
    description: 'Dark warm pad',
    category: 'pad',
    config: {
      sections: { violin: 60, viola: 80, cello: 100, bass: 80 },
      ensemble: { depth: 50, rate: 2, voices: 4 },
      attack: 400,
      release: 1500,
      brightness: 35,
    } as Partial<StringMachineConfig>,
  },
  {
    id: 'string-bright',
    name: 'Bright Strings',
    description: 'Cutting bright strings',
    category: 'string',
    config: {
      sections: { violin: 100, viola: 70, cello: 50, bass: 30 },
      ensemble: { depth: 55, rate: 4, voices: 4 },
      attack: 100,
      release: 700,
      brightness: 90,
    } as Partial<StringMachineConfig>,
  },
  {
    id: 'string-slow',
    name: 'Slow Strings',
    description: 'Gentle slow attack',
    category: 'pad',
    config: {
      sections: { violin: 90, viola: 80, cello: 70, bass: 60 },
      ensemble: { depth: 45, rate: 2, voices: 4 },
      attack: 800,
      release: 2000,
      brightness: 50,
    } as Partial<StringMachineConfig>,
  },
  {
    id: 'string-fast',
    name: 'Fast Strings',
    description: 'Quick attack strings',
    category: 'string',
    config: {
      sections: { violin: 100, viola: 80, cello: 60, bass: 40 },
      ensemble: { depth: 50, rate: 5, voices: 4 },
      attack: 30,
      release: 400,
      brightness: 70,
    } as Partial<StringMachineConfig>,
  },
  {
    id: 'string-lush',
    name: 'Lush Ensemble',
    description: 'Maximum chorus depth',
    category: 'pad',
    config: {
      sections: { violin: 100, viola: 100, cello: 100, bass: 100 },
      ensemble: { depth: 100, rate: 3, voices: 6 },
      attack: 300,
      release: 1200,
      brightness: 55,
    } as Partial<StringMachineConfig>,
  },
  {
    id: 'string-dry',
    name: 'Dry Strings',
    description: 'Minimal chorus',
    category: 'string',
    config: {
      sections: { violin: 100, viola: 80, cello: 70, bass: 50 },
      ensemble: { depth: 15, rate: 3, voices: 2 },
      attack: 150,
      release: 800,
      brightness: 60,
    } as Partial<StringMachineConfig>,
  },
  {
    id: 'string-80s',
    name: '80s Strings',
    description: 'Retro synth strings',
    category: 'string',
    config: {
      sections: { violin: 100, viola: 60, cello: 40, bass: 20 },
      ensemble: { depth: 80, rate: 5.5, voices: 6 },
      attack: 50,
      release: 500,
      brightness: 75,
    } as Partial<StringMachineConfig>,
  },
  {
    id: 'string-movie',
    name: 'Movie Score',
    description: 'Cinematic strings',
    category: 'string',
    config: {
      sections: { violin: 80, viola: 90, cello: 100, bass: 70 },
      ensemble: { depth: 40, rate: 2.5, voices: 4 },
      attack: 350,
      release: 1400,
      brightness: 55,
    } as Partial<StringMachineConfig>,
  },
  {
    id: 'string-pizz',
    name: 'Pizzicato',
    description: 'Short plucked strings',
    category: 'pluck',
    config: {
      sections: { violin: 100, viola: 80, cello: 60, bass: 40 },
      ensemble: { depth: 20, rate: 3, voices: 2 },
      attack: 5,
      release: 200,
      brightness: 80,
    } as Partial<StringMachineConfig>,
  },
  {
    id: 'string-tremolo',
    name: 'Tremolo',
    description: 'Fast tremolo strings',
    category: 'string',
    config: {
      sections: { violin: 100, viola: 80, cello: 60, bass: 40 },
      ensemble: { depth: 100, rate: 6, voices: 6 },
      attack: 20,
      release: 300,
      brightness: 70,
    } as Partial<StringMachineConfig>,
  },
  {
    id: 'string-spooky',
    name: 'Spooky',
    description: 'Eerie horror strings',
    category: 'fx',
    config: {
      sections: { violin: 70, viola: 90, cello: 100, bass: 100 },
      ensemble: { depth: 70, rate: 0.5, voices: 4 },
      attack: 600,
      release: 2500,
      brightness: 25,
    } as Partial<StringMachineConfig>,
  },
  {
    id: 'string-epic',
    name: 'Epic',
    description: 'Big dramatic strings',
    category: 'string',
    config: {
      sections: { violin: 100, viola: 100, cello: 100, bass: 100 },
      ensemble: { depth: 60, rate: 3, voices: 4 },
      attack: 200,
      release: 1000,
      brightness: 70,
    } as Partial<StringMachineConfig>,
  },
  {
    id: 'string-gentle',
    name: 'Gentle',
    description: 'Soft delicate strings',
    category: 'pad',
    config: {
      sections: { violin: 60, viola: 70, cello: 50, bass: 30 },
      ensemble: { depth: 35, rate: 2, voices: 3 },
      attack: 500,
      release: 1500,
      brightness: 40,
    } as Partial<StringMachineConfig>,
  },
  {
    id: 'string-synth',
    name: 'Synth Strings',
    description: 'Very synthetic sound',
    category: 'pad',
    config: {
      sections: { violin: 100, viola: 50, cello: 30, bass: 20 },
      ensemble: { depth: 90, rate: 5, voices: 6 },
      attack: 30,
      release: 400,
      brightness: 85,
    } as Partial<StringMachineConfig>,
  },
];

// ============================================
// FORMANT SYNTH PRESETS
// ============================================
export const FORMANT_SYNTH_PRESETS: SynthPreset[] = [
  {
    id: 'formant-a',
    name: 'Vowel A',
    description: '"Ahhh" sound',
    category: 'pad',
    config: {
      vowel: 'A',
      vowelMorph: { target: 'A', amount: 0, rate: 1, mode: 'manual' },
      oscillator: { type: 'sawtooth' },
      formants: { f1: 800, f2: 1200, f3: 2500, bandwidth: 100 },
      envelope: { attack: 100, decay: 800, sustain: 0, release: 300 },
      brightness: 70,
    } as Partial<FormantSynthConfig>,
  },
  {
    id: 'formant-e',
    name: 'Vowel E',
    description: '"Ehh" sound',
    category: 'pad',
    config: {
      vowel: 'E',
      vowelMorph: { target: 'E', amount: 0, rate: 1, mode: 'manual' },
      oscillator: { type: 'sawtooth' },
      formants: { f1: 400, f2: 2000, f3: 2600, bandwidth: 100 },
      envelope: { attack: 100, decay: 800, sustain: 0, release: 300 },
      brightness: 70,
    } as Partial<FormantSynthConfig>,
  },
  {
    id: 'formant-i',
    name: 'Vowel I',
    description: '"Eee" sound',
    category: 'lead',
    config: {
      vowel: 'I',
      vowelMorph: { target: 'I', amount: 0, rate: 1, mode: 'manual' },
      oscillator: { type: 'sawtooth' },
      formants: { f1: 300, f2: 2300, f3: 3000, bandwidth: 100 },
      envelope: { attack: 50, decay: 600, sustain: 0, release: 200 },
      brightness: 80,
    } as Partial<FormantSynthConfig>,
  },
  {
    id: 'formant-o',
    name: 'Vowel O',
    description: '"Ohh" sound',
    category: 'pad',
    config: {
      vowel: 'O',
      vowelMorph: { target: 'O', amount: 0, rate: 1, mode: 'manual' },
      oscillator: { type: 'sawtooth' },
      formants: { f1: 500, f2: 800, f3: 2500, bandwidth: 100 },
      envelope: { attack: 150, decay: 900, sustain: 0, release: 400 },
      brightness: 60,
    } as Partial<FormantSynthConfig>,
  },
  {
    id: 'formant-u',
    name: 'Vowel U',
    description: '"Ooo" sound',
    category: 'pad',
    config: {
      vowel: 'U',
      vowelMorph: { target: 'U', amount: 0, rate: 1, mode: 'manual' },
      oscillator: { type: 'sawtooth' },
      formants: { f1: 350, f2: 600, f3: 2400, bandwidth: 100 },
      envelope: { attack: 200, decay: 1000, sustain: 0, release: 500 },
      brightness: 50,
    } as Partial<FormantSynthConfig>,
  },
  {
    id: 'formant-ae',
    name: 'A to E Morph',
    description: 'Morphing between vowels',
    category: 'pad',
    config: {
      vowel: 'A',
      vowelMorph: { target: 'E', amount: 50, rate: 1, mode: 'lfo' },
      oscillator: { type: 'sawtooth' },
      envelope: { attack: 200, decay: 1000, sustain: 50, release: 500 },
      brightness: 70,
    } as Partial<FormantSynthConfig>,
  },
  {
    id: 'formant-choir',
    name: 'Choir',
    description: 'Evolving choir pad',
    category: 'pad',
    config: {
      vowel: 'A',
      vowelMorph: { target: 'O', amount: 60, rate: 0.5, mode: 'lfo' },
      oscillator: { type: 'sawtooth' },
      envelope: { attack: 400, decay: 1500, sustain: 60, release: 800 },
      brightness: 65,
    } as Partial<FormantSynthConfig>,
  },
  {
    id: 'formant-robot',
    name: 'Robot',
    description: 'Robotic voice',
    category: 'fx',
    config: {
      vowel: 'E',
      vowelMorph: { target: 'I', amount: 40, rate: 8, mode: 'lfo' },
      oscillator: { type: 'square' },
      envelope: { attack: 5, decay: 400, sustain: 0, release: 100 },
      brightness: 90,
    } as Partial<FormantSynthConfig>,
  },
  {
    id: 'formant-talk',
    name: 'Talking',
    description: 'Speech-like sound',
    category: 'lead',
    config: {
      vowel: 'A',
      vowelMorph: { target: 'I', amount: 70, rate: 2, mode: 'envelope' },
      oscillator: { type: 'sawtooth' },
      envelope: { attack: 50, decay: 500, sustain: 0, release: 200 },
      brightness: 75,
    } as Partial<FormantSynthConfig>,
  },
  {
    id: 'formant-whisper',
    name: 'Whisper',
    description: 'Breathy whisper',
    category: 'pad',
    config: {
      vowel: 'O',
      vowelMorph: { target: 'U', amount: 30, rate: 0.3, mode: 'lfo' },
      oscillator: { type: 'sawtooth' },
      formants: { f1: 500, f2: 800, f3: 2500, bandwidth: 200 },
      envelope: { attack: 300, decay: 1200, sustain: 40, release: 600 },
      brightness: 40,
    } as Partial<FormantSynthConfig>,
  },
  {
    id: 'formant-square',
    name: 'Square Vocal',
    description: 'Square wave formant',
    category: 'lead',
    config: {
      vowel: 'A',
      vowelMorph: { target: 'E', amount: 0, rate: 1, mode: 'manual' },
      oscillator: { type: 'square' },
      envelope: { attack: 20, decay: 500, sustain: 0, release: 150 },
      brightness: 80,
    } as Partial<FormantSynthConfig>,
  },
  {
    id: 'formant-bass',
    name: 'Vocal Bass',
    description: 'Deep vocal bass',
    category: 'bass',
    config: {
      vowel: 'O',
      vowelMorph: { target: 'U', amount: 20, rate: 0.5, mode: 'lfo' },
      oscillator: { type: 'sawtooth' },
      formants: { f1: 400, f2: 700, f3: 2000, bandwidth: 80 },
      envelope: { attack: 10, decay: 400, sustain: 0, release: 100 },
      brightness: 40,
    } as Partial<FormantSynthConfig>,
  },
  {
    id: 'formant-lead',
    name: 'Vocal Lead',
    description: 'Singing lead sound',
    category: 'lead',
    config: {
      vowel: 'I',
      vowelMorph: { target: 'A', amount: 30, rate: 3, mode: 'envelope' },
      oscillator: { type: 'sawtooth' },
      envelope: { attack: 30, decay: 600, sustain: 0, release: 200 },
      brightness: 85,
    } as Partial<FormantSynthConfig>,
  },
  {
    id: 'formant-alien',
    name: 'Alien',
    description: 'Strange alien voice',
    category: 'fx',
    config: {
      vowel: 'E',
      vowelMorph: { target: 'U', amount: 80, rate: 5, mode: 'lfo' },
      oscillator: { type: 'triangle' },
      formants: { f1: 250, f2: 3000, f3: 4000, bandwidth: 50 },
      envelope: { attack: 100, decay: 800, sustain: 30, release: 400 },
      brightness: 60,
    } as Partial<FormantSynthConfig>,
  },
  {
    id: 'formant-angel',
    name: 'Angelic',
    description: 'Heavenly choir',
    category: 'pad',
    config: {
      vowel: 'A',
      vowelMorph: { target: 'O', amount: 40, rate: 0.2, mode: 'lfo' },
      oscillator: { type: 'sawtooth' },
      envelope: { attack: 600, decay: 2000, sustain: 50, release: 1000 },
      brightness: 55,
    } as Partial<FormantSynthConfig>,
  },
  {
    id: 'formant-opera',
    name: 'Opera',
    description: 'Operatic voice',
    category: 'pad',
    config: {
      vowel: 'A',
      vowelMorph: { target: 'O', amount: 50, rate: 1.5, mode: 'lfo' },
      oscillator: { type: 'sawtooth' },
      formants: { f1: 900, f2: 1300, f3: 2700, bandwidth: 120 },
      envelope: { attack: 300, decay: 1200, sustain: 60, release: 700 },
      brightness: 75,
    } as Partial<FormantSynthConfig>,
  },
  {
    id: 'formant-wide',
    name: 'Wide Vowel',
    description: 'Wide bandwidth formant',
    category: 'pad',
    config: {
      vowel: 'A',
      vowelMorph: { target: 'E', amount: 0, rate: 1, mode: 'manual' },
      oscillator: { type: 'sawtooth' },
      formants: { f1: 800, f2: 1200, f3: 2500, bandwidth: 200 },
      envelope: { attack: 150, decay: 800, sustain: 0, release: 400 },
      brightness: 60,
    } as Partial<FormantSynthConfig>,
  },
  {
    id: 'formant-narrow',
    name: 'Narrow Vowel',
    description: 'Tight resonant formant',
    category: 'lead',
    config: {
      vowel: 'I',
      vowelMorph: { target: 'E', amount: 0, rate: 1, mode: 'manual' },
      oscillator: { type: 'sawtooth' },
      formants: { f1: 300, f2: 2300, f3: 3000, bandwidth: 50 },
      envelope: { attack: 20, decay: 500, sustain: 0, release: 150 },
      brightness: 90,
    } as Partial<FormantSynthConfig>,
  },
  {
    id: 'formant-sweep',
    name: 'Vowel Sweep',
    description: 'Full vowel sweep',
    category: 'fx',
    config: {
      vowel: 'A',
      vowelMorph: { target: 'U', amount: 100, rate: 0.1, mode: 'lfo' },
      oscillator: { type: 'sawtooth' },
      envelope: { attack: 200, decay: 2000, sustain: 70, release: 800 },
      brightness: 65,
    } as Partial<FormantSynthConfig>,
  },
  {
    id: 'formant-pluck',
    name: 'Vocal Pluck',
    description: 'Short vocal pluck',
    category: 'pluck',
    config: {
      vowel: 'E',
      vowelMorph: { target: 'A', amount: 60, rate: 1, mode: 'envelope' },
      oscillator: { type: 'sawtooth' },
      envelope: { attack: 5, decay: 150, sustain: 0, release: 50 },
      brightness: 80,
    } as Partial<FormantSynthConfig>,
  },
];

// ============================================
// POLYSYNTH PRESETS
// ============================================
export const POLYSYNTH_PRESETS: SynthPreset[] = [
  {
    id: 'poly-warm',
    name: 'Warm Poly',
    description: 'Classic warm poly sound',
    category: 'pad',
    config: {
      voiceCount: 8,
      voiceType: 'Synth',
      stealMode: 'oldest',
      oscillator: { type: 'sawtooth', detune: 5, octave: 0 },
      envelope: { attack: 100, decay: 800, sustain: 0, release: 400 },
      portamento: 0,
    } as Partial<PolySynthConfig>,
  },
  {
    id: 'poly-brass',
    name: 'Poly Brass',
    description: 'Brass-like poly',
    category: 'pad',
    config: {
      voiceCount: 6,
      voiceType: 'Synth',
      stealMode: 'oldest',
      oscillator: { type: 'sawtooth', detune: 10, octave: 0 },
      envelope: { attack: 50, decay: 600, sustain: 0, release: 300 },
      portamento: 0,
    } as Partial<PolySynthConfig>,
  },
  {
    id: 'poly-strings',
    name: 'Poly Strings',
    description: 'String ensemble',
    category: 'string',
    config: {
      voiceCount: 8,
      voiceType: 'Synth',
      stealMode: 'oldest',
      oscillator: { type: 'sawtooth', detune: 15, octave: 0 },
      envelope: { attack: 300, decay: 1500, sustain: 70, release: 800 },
      portamento: 0,
    } as Partial<PolySynthConfig>,
  },
  {
    id: 'poly-organ',
    name: 'Poly Organ',
    description: 'Organ-like poly',
    category: 'key',
    config: {
      voiceCount: 8,
      voiceType: 'Synth',
      stealMode: 'oldest',
      oscillator: { type: 'square', detune: 0, octave: 0 },
      envelope: { attack: 5, decay: 100, sustain: 100, release: 100 },
      portamento: 0,
    } as Partial<PolySynthConfig>,
  },
  {
    id: 'poly-fm-bell',
    name: 'FM Bell',
    description: 'Bell-like FM poly',
    category: 'key',
    config: {
      voiceCount: 8,
      voiceType: 'FMSynth',
      stealMode: 'oldest',
      oscillator: { type: 'sine', detune: 0, octave: 0 },
      envelope: { attack: 5, decay: 1500, sustain: 0, release: 500 },
      portamento: 0,
    } as Partial<PolySynthConfig>,
  },
  {
    id: 'poly-fm-ep',
    name: 'FM E.Piano',
    description: 'FM electric piano',
    category: 'key',
    config: {
      voiceCount: 8,
      voiceType: 'FMSynth',
      stealMode: 'oldest',
      oscillator: { type: 'sine', detune: 0, octave: 0 },
      envelope: { attack: 10, decay: 800, sustain: 0, release: 300 },
      portamento: 0,
    } as Partial<PolySynthConfig>,
  },
  {
    id: 'poly-am',
    name: 'AM Poly',
    description: 'Amplitude modulation poly',
    category: 'lead',
    config: {
      voiceCount: 6,
      voiceType: 'AMSynth',
      stealMode: 'oldest',
      oscillator: { type: 'sawtooth', detune: 5, octave: 0 },
      envelope: { attack: 20, decay: 600, sustain: 0, release: 200 },
      portamento: 0,
    } as Partial<PolySynthConfig>,
  },
  {
    id: 'poly-pluck',
    name: 'Poly Pluck',
    description: 'Short plucky poly',
    category: 'pluck',
    config: {
      voiceCount: 8,
      voiceType: 'Synth',
      stealMode: 'oldest',
      oscillator: { type: 'triangle', detune: 0, octave: 0 },
      envelope: { attack: 3, decay: 200, sustain: 0, release: 80 },
      portamento: 0,
    } as Partial<PolySynthConfig>,
  },
  {
    id: 'poly-glide',
    name: 'Glide Poly',
    description: 'Portamento poly',
    category: 'lead',
    config: {
      voiceCount: 4,
      voiceType: 'Synth',
      stealMode: 'lowest',
      oscillator: { type: 'sawtooth', detune: 8, octave: 0 },
      envelope: { attack: 50, decay: 700, sustain: 0, release: 300 },
      portamento: 100,
    } as Partial<PolySynthConfig>,
  },
  {
    id: 'poly-square',
    name: 'Square Poly',
    description: 'Hollow square wave poly',
    category: 'pad',
    config: {
      voiceCount: 8,
      voiceType: 'Synth',
      stealMode: 'oldest',
      oscillator: { type: 'square', detune: 7, octave: 0 },
      envelope: { attack: 80, decay: 900, sustain: 0, release: 400 },
      portamento: 0,
    } as Partial<PolySynthConfig>,
  },
  {
    id: 'poly-sine',
    name: 'Pure Sine',
    description: 'Clean sine wave poly',
    category: 'pad',
    config: {
      voiceCount: 8,
      voiceType: 'Synth',
      stealMode: 'oldest',
      oscillator: { type: 'sine', detune: 0, octave: 0 },
      envelope: { attack: 100, decay: 1000, sustain: 50, release: 500 },
      portamento: 0,
    } as Partial<PolySynthConfig>,
  },
  {
    id: 'poly-tri',
    name: 'Triangle Poly',
    description: 'Soft triangle wave',
    category: 'pad',
    config: {
      voiceCount: 8,
      voiceType: 'Synth',
      stealMode: 'oldest',
      oscillator: { type: 'triangle', detune: 5, octave: 0 },
      envelope: { attack: 150, decay: 1000, sustain: 40, release: 600 },
      portamento: 0,
    } as Partial<PolySynthConfig>,
  },
  {
    id: 'poly-thick',
    name: 'Thick Poly',
    description: 'Heavy detuned poly',
    category: 'pad',
    config: {
      voiceCount: 4,
      voiceType: 'Synth',
      stealMode: 'oldest',
      oscillator: { type: 'sawtooth', detune: 30, octave: 0 },
      envelope: { attack: 80, decay: 700, sustain: 0, release: 350 },
      portamento: 0,
    } as Partial<PolySynthConfig>,
  },
  {
    id: 'poly-thin',
    name: 'Thin Poly',
    description: 'Light clean poly',
    category: 'lead',
    config: {
      voiceCount: 8,
      voiceType: 'Synth',
      stealMode: 'oldest',
      oscillator: { type: 'triangle', detune: 0, octave: 1 },
      envelope: { attack: 10, decay: 400, sustain: 0, release: 150 },
      portamento: 0,
    } as Partial<PolySynthConfig>,
  },
  {
    id: 'poly-sub',
    name: 'Sub Poly',
    description: 'Deep sub bass poly',
    category: 'bass',
    config: {
      voiceCount: 4,
      voiceType: 'Synth',
      stealMode: 'oldest',
      oscillator: { type: 'sine', detune: 0, octave: -1 },
      envelope: { attack: 20, decay: 600, sustain: 0, release: 200 },
      portamento: 0,
    } as Partial<PolySynthConfig>,
  },
  {
    id: 'poly-bright',
    name: 'Bright Poly',
    description: 'Bright cutting poly',
    category: 'lead',
    config: {
      voiceCount: 6,
      voiceType: 'Synth',
      stealMode: 'oldest',
      oscillator: { type: 'sawtooth', detune: 5, octave: 1 },
      envelope: { attack: 10, decay: 500, sustain: 0, release: 200 },
      portamento: 0,
    } as Partial<PolySynthConfig>,
  },
  {
    id: 'poly-dark',
    name: 'Dark Poly',
    description: 'Muffled dark poly',
    category: 'pad',
    config: {
      voiceCount: 8,
      voiceType: 'Synth',
      stealMode: 'oldest',
      oscillator: { type: 'sawtooth', detune: 10, octave: -1 },
      envelope: { attack: 200, decay: 1200, sustain: 40, release: 600 },
      portamento: 0,
    } as Partial<PolySynthConfig>,
  },
  {
    id: 'poly-stab',
    name: 'Stab',
    description: 'Short chord stab',
    category: 'key',
    config: {
      voiceCount: 8,
      voiceType: 'Synth',
      stealMode: 'oldest',
      oscillator: { type: 'sawtooth', detune: 12, octave: 0 },
      envelope: { attack: 5, decay: 150, sustain: 0, release: 50 },
      portamento: 0,
    } as Partial<PolySynthConfig>,
  },
  {
    id: 'poly-swirl',
    name: 'Swirl',
    description: 'Evolving detune pad',
    category: 'pad',
    config: {
      voiceCount: 6,
      voiceType: 'Synth',
      stealMode: 'oldest',
      oscillator: { type: 'sawtooth', detune: 25, octave: 0 },
      envelope: { attack: 500, decay: 2000, sustain: 60, release: 1000 },
      portamento: 50,
    } as Partial<PolySynthConfig>,
  },
  {
    id: 'poly-vintage',
    name: 'Vintage',
    description: 'Classic polysynth',
    category: 'pad',
    config: {
      voiceCount: 6,
      voiceType: 'Synth',
      stealMode: 'oldest',
      oscillator: { type: 'sawtooth', detune: 8, octave: 0 },
      envelope: { attack: 60, decay: 600, sustain: 30, release: 300 },
      portamento: 0,
    } as Partial<PolySynthConfig>,
  },
];

// ============================================
// Get presets by synth type
// ============================================
export function getPresetsForSynthType(synthType: SynthType): SynthPreset[] {
  switch (synthType) {
    case 'TB303':
      return TB303_PRESETS;
    case 'ChipSynth':
      return CHIPSYNTH_PRESETS;
    case 'SuperSaw':
      return SUPERSAW_PRESETS;
    case 'Organ':
      return ORGAN_PRESETS;
    case 'DrumMachine':
      return DRUM_MACHINE_PRESETS;
    case 'PWMSynth':
      return PWM_SYNTH_PRESETS;
    case 'StringMachine':
      return STRING_MACHINE_PRESETS;
    case 'FormantSynth':
      return FORMANT_SYNTH_PRESETS;
    case 'PolySynth':
      return POLYSYNTH_PRESETS;
    default:
      return [];
  }
}

// Export all presets
export const ALL_PRESETS: Record<string, SynthPreset[]> = {
  TB303: TB303_PRESETS,
  ChipSynth: CHIPSYNTH_PRESETS,
  SuperSaw: SUPERSAW_PRESETS,
  Organ: ORGAN_PRESETS,
  DrumMachine: DRUM_MACHINE_PRESETS,
  PWMSynth: PWM_SYNTH_PRESETS,
  StringMachine: STRING_MACHINE_PRESETS,
  FormantSynth: FORMANT_SYNTH_PRESETS,
  PolySynth: POLYSYNTH_PRESETS,
};
