/**
 * Synth Categories - Organized synth types with descriptions and guidance
 */

import type { SynthType } from '@typedefs/instrument';

export interface SynthInfo {
  type: SynthType;
  name: string;
  shortName: string;
  description: string;
  bestFor: string[];
  icon: string; // Lucide icon name
  color: string; // Tailwind color class
}

export interface SynthCategory {
  id: string;
  name: string;
  description: string;
  synths: SynthInfo[];
}

// Individual synth information
export const SYNTH_INFO: Record<SynthType, SynthInfo> = {
  TB303: {
    type: 'TB303',
    name: 'TB-303',
    shortName: '303',
    description: 'Classic acid bass synthesizer with resonant filter and slide',
    bestFor: ['Acid bass', 'Squelchy lines', 'Techno', 'House'],
    icon: 'Zap',
    color: 'text-accent-primary',
  },
  MonoSynth: {
    type: 'MonoSynth',
    name: 'Mono Synth',
    shortName: 'Mono',
    description: 'Single-voice synth with oscillator, filter, and envelope',
    bestFor: ['Bass', 'Lead lines', 'Portamento'],
    icon: 'AudioLines',
    color: 'text-blue-400',
  },
  Synth: {
    type: 'Synth',
    name: 'Basic Synth',
    shortName: 'Synth',
    description: 'Simple polyphonic synthesizer with amplitude envelope',
    bestFor: ['Pads', 'Chords', 'Simple sounds'],
    icon: 'Music2',
    color: 'text-purple-400',
  },
  DuoSynth: {
    type: 'DuoSynth',
    name: 'Duo Synth',
    shortName: 'Duo',
    description: 'Two-voice synth with harmonics and vibratoesque LFO',
    bestFor: ['Rich leads', 'Detuned sounds', 'Fat bass'],
    icon: 'Layers',
    color: 'text-indigo-400',
  },
  FMSynth: {
    type: 'FMSynth',
    name: 'FM Synth',
    shortName: 'FM',
    description: 'Frequency modulation synth for complex harmonic tones',
    bestFor: ['Bells', 'Electric piano', 'Metallic sounds'],
    icon: 'Radio',
    color: 'text-cyan-400',
  },
  AMSynth: {
    type: 'AMSynth',
    name: 'AM Synth',
    shortName: 'AM',
    description: 'Amplitude modulation synth with ring modulation character',
    bestFor: ['Tremolo effects', 'Ring mod', 'Atmospheric'],
    icon: 'Activity',
    color: 'text-teal-400',
  },
  PluckSynth: {
    type: 'PluckSynth',
    name: 'Pluck Synth',
    shortName: 'Pluck',
    description: 'Karplus-Strong string synthesis for plucked strings',
    bestFor: ['Guitar', 'Harp', 'Pizzicato', 'String plucks'],
    icon: 'Guitar',
    color: 'text-amber-400',
  },
  MembraneSynth: {
    type: 'MembraneSynth',
    name: 'Membrane Synth',
    shortName: 'Membrane',
    description: 'Drum membrane simulation for kicks and toms',
    bestFor: ['Kick drums', 'Toms', 'Percussion'],
    icon: 'Circle',
    color: 'text-orange-400',
  },
  MetalSynth: {
    type: 'MetalSynth',
    name: 'Metal Synth',
    shortName: 'Metal',
    description: 'Metallic percussion synthesis with harmonics',
    bestFor: ['Hi-hats', 'Cymbals', 'Bells', 'Metallic hits'],
    icon: 'Hexagon',
    color: 'text-yellow-400',
  },
  NoiseSynth: {
    type: 'NoiseSynth',
    name: 'Noise Synth',
    shortName: 'Noise',
    description: 'Filtered noise generator with envelope',
    bestFor: ['Snares', 'Hi-hats', 'Risers', 'FX'],
    icon: 'Hash',
    color: 'text-gray-400',
  },
  Wavetable: {
    type: 'Wavetable',
    name: 'Wavetable',
    shortName: 'Wave',
    description: 'Wavetable synth with morphing and unison',
    bestFor: ['Evolving pads', 'Modern bass', 'Complex timbres'],
    icon: 'Waves',
    color: 'text-pink-400',
  },
  Sampler: {
    type: 'Sampler',
    name: 'Sampler',
    shortName: 'Sampler',
    description: 'Multi-sample playback with velocity layers',
    bestFor: ['Realistic instruments', 'Sample kits', 'One-shots'],
    icon: 'FileAudio',
    color: 'text-rose-400',
  },
  Player: {
    type: 'Player',
    name: 'Sample Player',
    shortName: 'Player',
    description: 'Simple one-shot sample playback',
    bestFor: ['Loops', 'One-shots', 'Vocal samples'],
    icon: 'Play',
    color: 'text-lime-400',
  },
  GranularSynth: {
    type: 'GranularSynth',
    name: 'Granular Synth',
    shortName: 'Granular',
    description: 'Sample-based granular synthesis with grain manipulation',
    bestFor: ['Textures', 'Pads', 'Ambient', 'Sound design', 'Glitch'],
    icon: 'Sparkles',
    color: 'text-violet-400',
  },
  // New synths
  SuperSaw: {
    type: 'SuperSaw',
    name: 'SuperSaw',
    shortName: 'SSaw',
    description: 'Massive detuned saw waves for trance and EDM',
    bestFor: ['Trance leads', 'EDM drops', 'Big chords', 'Supersaw stabs'],
    icon: 'Layers',
    color: 'text-orange-500',
  },
  PolySynth: {
    type: 'PolySynth',
    name: 'Poly Synth',
    shortName: 'Poly',
    description: 'True polyphonic synth with voice management',
    bestFor: ['Chords', 'Pads', 'Polyphonic parts', 'Layered sounds'],
    icon: 'LayoutGrid',
    color: 'text-blue-500',
  },
  Organ: {
    type: 'Organ',
    name: 'Drawbar Organ',
    shortName: 'Organ',
    description: 'Hammond-style tonewheel organ with drawbars',
    bestFor: ['House', 'Gospel', 'Jazz', 'Rock organ'],
    icon: 'Piano',
    color: 'text-amber-600',
  },
  DrumMachine: {
    type: 'DrumMachine',
    name: 'Drum Machine',
    shortName: '808/909',
    description: 'Analog drum synthesis (808/909 style)',
    bestFor: ['Kicks', 'Snares', 'Hi-hats', 'Electronic drums'],
    icon: 'Disc',
    color: 'text-red-500',
  },
  ChipSynth: {
    type: 'ChipSynth',
    name: 'Chip Synth',
    shortName: 'Chip',
    description: '8-bit video game console sounds',
    bestFor: ['Chiptune', 'Retro', 'Lo-fi', 'Arpeggios'],
    icon: 'Gamepad2',
    color: 'text-green-400',
  },
  PWMSynth: {
    type: 'PWMSynth',
    name: 'PWM Synth',
    shortName: 'PWM',
    description: 'Pulse width modulation for rich analog tones',
    bestFor: ['Analog pads', 'Warm leads', 'Classic synth'],
    icon: 'Waves',
    color: 'text-emerald-400',
  },
  StringMachine: {
    type: 'StringMachine',
    name: 'String Machine',
    shortName: 'Strings',
    description: 'Vintage ensemble strings (Solina-style)',
    bestFor: ['Lush pads', 'Disco strings', 'Ambient', 'Retro'],
    icon: 'Music4',
    color: 'text-rose-400',
  },
  FormantSynth: {
    type: 'FormantSynth',
    name: 'Formant Synth',
    shortName: 'Vocal',
    description: 'Vowel synthesis for vocal-like sounds',
    bestFor: ['Vocal pads', 'Talk box', 'Choir', 'Robotic'],
    icon: 'Mic',
    color: 'text-fuchsia-400',
  },
  Furnace: {
    type: 'Furnace',
    name: 'Furnace FM',
    shortName: 'FUI',
    description: 'FM engine compatible with Furnace Tracker (.fui) instruments',
    bestFor: ['Genesis bass', 'FM bells', 'Retro arcade', '4-op FM'],
    icon: 'Cpu',
    color: 'text-amber-500',
  },
  // Furnace Chip Types
  FurnaceOPN: {
    type: 'FurnaceOPN',
    name: 'Genesis / OPN2',
    shortName: 'OPN2',
    description: 'Sega Genesis / Mega Drive YM2612 - 6 channels of 4-op FM',
    bestFor: ['Genesis bass', 'FM leads', 'Slap bass', '16-bit game music'],
    icon: 'Gamepad2',
    color: 'text-blue-500',
  },
  FurnaceOPM: {
    type: 'FurnaceOPM',
    name: 'OPM / X68000',
    shortName: 'OPM',
    description: 'Yamaha YM2151 - Sharp X68000, arcade machines',
    bestFor: ['Arcade FM', 'Bright leads', 'Brass', 'Game music'],
    icon: 'Cpu',
    color: 'text-cyan-500',
  },
  FurnaceOPL: {
    type: 'FurnaceOPL',
    name: 'OPL3 / AdLib',
    shortName: 'OPL3',
    description: 'Yamaha YMF262 - AdLib, Sound Blaster, DOS games',
    bestFor: ['DOS game music', 'MIDI synth', 'Organs', 'PC gaming'],
    icon: 'Monitor',
    color: 'text-yellow-500',
  },
  FurnaceOPLL: {
    type: 'FurnaceOPLL',
    name: 'OPLL / MSX',
    shortName: 'OPLL',
    description: 'Yamaha YM2413 - MSX, SMS FM unit, budget FM',
    bestFor: ['MSX music', 'SMS FM', 'Lo-fi FM', 'Simple FM'],
    icon: 'Radio',
    color: 'text-orange-400',
  },
  FurnaceESFM: {
    type: 'FurnaceESFM',
    name: 'ESFM',
    shortName: 'ESFM',
    description: 'Enhanced Sound FM - advanced OPL3 with operator detune',
    bestFor: ['Modern retro', 'Enhanced FM', 'Detuned sounds'],
    icon: 'Zap',
    color: 'text-purple-500',
  },
  FurnaceOPZ: {
    type: 'FurnaceOPZ',
    name: 'OPZ / TX81Z',
    shortName: 'OPZ',
    description: 'Yamaha YM2414 - TX81Z, DX11, advanced FM',
    bestFor: ['Lately bass', 'DX bells', 'Complex FM', 'E-piano'],
    icon: 'Piano',
    color: 'text-indigo-500',
  },
  FurnaceNES: {
    type: 'FurnaceNES',
    name: 'NES / 2A03',
    shortName: 'NES',
    description: 'Nintendo Entertainment System - 2 pulse, triangle, noise, DPCM',
    bestFor: ['NES chiptune', '8-bit melodies', 'Retro drums', 'Famicom'],
    icon: 'Gamepad2',
    color: 'text-red-500',
  },
  FurnaceGB: {
    type: 'FurnaceGB',
    name: 'Game Boy',
    shortName: 'GB',
    description: 'Nintendo Game Boy - 2 pulse, wave, noise channels',
    bestFor: ['Game Boy music', 'Lo-fi chiptune', 'Portable gaming'],
    icon: 'Smartphone',
    color: 'text-green-500',
  },
  FurnaceC64: {
    type: 'FurnaceC64',
    name: 'C64 / SID',
    shortName: 'SID',
    description: 'Commodore 64 SID chip - 3 voices with filters',
    bestFor: ['SID leads', 'Arpeggios', 'Filter sweeps', 'Demoscene'],
    icon: 'Terminal',
    color: 'text-violet-500',
  },
  FurnaceAY: {
    type: 'FurnaceAY',
    name: 'AY-3-8910',
    shortName: 'AY',
    description: 'General Instrument AY - ZX Spectrum, MSX, Atari ST',
    bestFor: ['ZX Spectrum', 'MSX', 'Amstrad CPC', 'Envelope tricks'],
    icon: 'Tv',
    color: 'text-sky-500',
  },
  FurnaceTIA: {
    type: 'FurnaceTIA',
    name: 'Atari TIA',
    shortName: 'TIA',
    description: 'Atari 2600 - primitive but distinctive sound',
    bestFor: ['Atari 2600', 'Primitive bleeps', 'Retro FX'],
    icon: 'Joystick',
    color: 'text-amber-600',
  },
  FurnaceVERA: {
    type: 'FurnaceVERA',
    name: 'VERA',
    shortName: 'VERA',
    description: 'Commander X16 - modern retro 16 channels PSG + PCM',
    bestFor: ['Modern retro', 'X16 music', 'Rich PSG'],
    icon: 'Cpu',
    color: 'text-teal-500',
  },
  FurnaceSAA: {
    type: 'FurnaceSAA',
    name: 'SAA1099',
    shortName: 'SAA',
    description: 'Philips SAA1099 - Sam Coupé, some PC sound cards',
    bestFor: ['Sam Coupé', 'Stereo chips', 'European home computers'],
    icon: 'Speaker',
    color: 'text-pink-500',
  },
  FurnacePSG: {
    type: 'FurnacePSG',
    name: 'SN76489 / PSG',
    shortName: 'PSG',
    description: 'TI SN76489 - Master System, Game Gear, BBC Micro',
    bestFor: ['Master System', 'Colecovision', 'Square wave PSG'],
    icon: 'SquareStack',
    color: 'text-emerald-500',
  },
  FurnaceVIC: {
    type: 'FurnaceVIC',
    name: 'VIC-20',
    shortName: 'VIC',
    description: 'Commodore VIC-20 - 3 square + noise',
    bestFor: ['VIC-20 music', 'Early 80s', 'Simple tones'],
    icon: 'Monitor',
    color: 'text-lime-500',
  },
  FurnaceLynx: {
    type: 'FurnaceLynx',
    name: 'Atari Lynx',
    shortName: 'Lynx',
    description: 'Atari Lynx - 4 channel wavetable',
    bestFor: ['Lynx music', 'Portable gaming', 'Wavetable'],
    icon: 'Gamepad',
    color: 'text-rose-500',
  },
  // Additional FM chips
  FurnaceOPNA: {
    type: 'FurnaceOPNA',
    name: 'OPNA / PC-98',
    shortName: 'OPNA',
    description: 'YM2608 - NEC PC-98, arcade machines',
    bestFor: ['PC-98 music', 'Touhou-style', 'Japanese arcade'],
    icon: 'Cpu',
    color: 'text-blue-400',
  },
  FurnaceOPNB: {
    type: 'FurnaceOPNB',
    name: 'OPNB / Neo Geo',
    shortName: 'OPNB',
    description: 'YM2610 - SNK Neo Geo',
    bestFor: ['Neo Geo music', 'Fighting games', 'SNK'],
    icon: 'Gamepad2',
    color: 'text-red-400',
  },
  FurnaceOPL4: {
    type: 'FurnaceOPL4',
    name: 'OPL4',
    shortName: 'OPL4',
    description: 'Yamaha YMF278 - FM + wavetable hybrid',
    bestFor: ['Advanced OPL', 'FM + samples', 'Late DOS'],
    icon: 'Layers',
    color: 'text-yellow-400',
  },
  FurnaceY8950: {
    type: 'FurnaceY8950',
    name: 'Y8950 / MSX-Audio',
    shortName: 'Y8950',
    description: 'Yamaha Y8950 - MSX-Audio, OPL + ADPCM',
    bestFor: ['MSX-Audio', 'OPL with drums', 'Japanese PC'],
    icon: 'Radio',
    color: 'text-orange-300',
  },
  // Console chips
  FurnacePCE: {
    type: 'FurnacePCE',
    name: 'PC Engine',
    shortName: 'PCE',
    description: 'PC Engine / TurboGrafx-16 - 6 channel wavetable',
    bestFor: ['PC Engine', 'TurboGrafx', 'HuCard games'],
    icon: 'Tv',
    color: 'text-orange-500',
  },
  FurnaceSNES: {
    type: 'FurnaceSNES',
    name: 'SNES / SPC700',
    shortName: 'SNES',
    description: 'Super Nintendo - Sony SPC700 8-channel BRR',
    bestFor: ['SNES music', '16-bit classics', 'BRR samples'],
    icon: 'Gamepad2',
    color: 'text-purple-400',
  },
  FurnaceVB: {
    type: 'FurnaceVB',
    name: 'Virtual Boy',
    shortName: 'VB',
    description: 'Nintendo Virtual Boy - 6 channel wavetable',
    bestFor: ['Virtual Boy', 'Stereo 3D audio', 'Nintendo VB'],
    icon: 'Glasses',
    color: 'text-red-600',
  },
  FurnaceSWAN: {
    type: 'FurnaceSWAN',
    name: 'WonderSwan',
    shortName: 'SWAN',
    description: 'Bandai WonderSwan - 4 channel wavetable + PCM',
    bestFor: ['WonderSwan', 'Portable gaming', 'Bandai'],
    icon: 'Smartphone',
    color: 'text-cyan-400',
  },
  // NES Expansion
  FurnaceVRC6: {
    type: 'FurnaceVRC6',
    name: 'VRC6',
    shortName: 'VRC6',
    description: 'Konami VRC6 - 2 pulse + saw (Castlevania 3 JP)',
    bestFor: ['Castlevania 3', 'Konami NES', 'Extra channels'],
    icon: 'Zap',
    color: 'text-amber-400',
  },
  FurnaceVRC7: {
    type: 'FurnaceVRC7',
    name: 'VRC7',
    shortName: 'VRC7',
    description: 'Konami VRC7 - OPLL clone (Lagrange Point)',
    bestFor: ['Lagrange Point', 'FM on NES', 'Konami FM'],
    icon: 'Radio',
    color: 'text-amber-500',
  },
  FurnaceN163: {
    type: 'FurnaceN163',
    name: 'Namco 163',
    shortName: 'N163',
    description: 'Namco 163 - 8 channel wavetable',
    bestFor: ['Namco NES', 'Wavetable', 'Complex tones'],
    icon: 'Waves',
    color: 'text-green-400',
  },
  FurnaceFDS: {
    type: 'FurnaceFDS',
    name: 'FDS',
    shortName: 'FDS',
    description: 'Famicom Disk System - wavetable + modulation',
    bestFor: ['FDS games', 'Wavy bass', 'Zelda FDS'],
    icon: 'Disc',
    color: 'text-yellow-500',
  },
  FurnaceMMC5: {
    type: 'FurnaceMMC5',
    name: 'MMC5',
    shortName: 'MMC5',
    description: 'MMC5 - 2 extra pulse channels',
    bestFor: ['Castlevania 3 US', 'Extra NES pulse', 'CV3'],
    icon: 'Plus',
    color: 'text-blue-300',
  },
  // Computer chips
  FurnaceTED: {
    type: 'FurnaceTED',
    name: 'TED',
    shortName: 'TED',
    description: 'Commodore Plus/4 TED - 2 square + noise',
    bestFor: ['Plus/4 music', 'Commodore 16', 'Budget C64'],
    icon: 'Monitor',
    color: 'text-violet-400',
  },
  // Arcade PCM chips
  FurnaceSEGAPCM: {
    type: 'FurnaceSEGAPCM',
    name: 'Sega PCM',
    shortName: 'SEGAPCM',
    description: 'Sega System 16/18 - 16 channel PCM',
    bestFor: ['OutRun', 'After Burner', 'Sega arcade'],
    icon: 'Speaker',
    color: 'text-blue-500',
  },
  FurnaceQSOUND: {
    type: 'FurnaceQSOUND',
    name: 'QSound',
    shortName: 'QSound',
    description: 'Capcom QSound - CPS1/CPS2 with 3D audio',
    bestFor: ['Street Fighter', 'CPS games', '3D positioning'],
    icon: 'Headphones',
    color: 'text-purple-500',
  },
  FurnaceES5506: {
    type: 'FurnaceES5506',
    name: 'ES5506',
    shortName: 'ES5506',
    description: 'Ensoniq ES5506 - 32 voice wavetable',
    bestFor: ['Taito F3', 'Ensoniq synths', 'High quality'],
    icon: 'AudioLines',
    color: 'text-pink-400',
  },
  FurnaceRF5C68: {
    type: 'FurnaceRF5C68',
    name: 'RF5C68',
    shortName: 'RF5C68',
    description: 'Ricoh RF5C68 - Sega CD, 8 channel PCM',
    bestFor: ['Sega CD', 'Mega CD', 'CD audio'],
    icon: 'Disc',
    color: 'text-cyan-500',
  },
  FurnaceC140: {
    type: 'FurnaceC140',
    name: 'C140',
    shortName: 'C140',
    description: 'Namco C140 - System 2, 24 channel PCM',
    bestFor: ['Namco arcade', 'System 2', 'Assault'],
    icon: 'Cpu',
    color: 'text-yellow-400',
  },
  FurnaceK007232: {
    type: 'FurnaceK007232',
    name: 'K007232',
    shortName: 'K007232',
    description: 'Konami K007232 - 2 channel PCM',
    bestFor: ['Contra arcade', 'Konami PCM', 'TMNT'],
    icon: 'Speaker',
    color: 'text-red-400',
  },
  FurnaceK053260: {
    type: 'FurnaceK053260',
    name: 'K053260',
    shortName: 'K053260',
    description: 'Konami K053260 - 4 channel PCM with ADPCM',
    bestFor: ['Sunset Riders', 'Simpsons', 'Konami 90s'],
    icon: 'Speaker',
    color: 'text-orange-400',
  },
  FurnaceGA20: {
    type: 'FurnaceGA20',
    name: 'GA20',
    shortName: 'GA20',
    description: 'Irem GA20 - 4 channel PCM',
    bestFor: ['R-Type Leo', 'Irem arcade', 'In the Hunt'],
    icon: 'Cpu',
    color: 'text-teal-400',
  },
  FurnaceOKI: {
    type: 'FurnaceOKI',
    name: 'OKI MSM6295',
    shortName: 'OKI',
    description: 'OKI MSM6295 - 4 channel ADPCM',
    bestFor: ['Neo Geo', 'Data East', 'ADPCM drums'],
    icon: 'Volume2',
    color: 'text-gray-400',
  },
  FurnaceYMZ280B: {
    type: 'FurnaceYMZ280B',
    name: 'YMZ280B',
    shortName: 'YMZ280B',
    description: 'Yamaha YMZ280B - 8 channel ADPCM',
    bestFor: ['Cave shmups', 'Late arcade', 'High quality'],
    icon: 'AudioLines',
    color: 'text-indigo-400',
  },
  // Wavetable chips
  FurnaceSCC: {
    type: 'FurnaceSCC',
    name: 'Konami SCC',
    shortName: 'SCC',
    description: 'Konami SCC - 5 channel wavetable (MSX)',
    bestFor: ['Gradius', 'Snatcher', 'MSX Konami'],
    icon: 'Waves',
    color: 'text-green-500',
  },
  FurnaceX1_010: {
    type: 'FurnaceX1_010',
    name: 'X1-010',
    shortName: 'X1-010',
    description: 'Seta X1-010 - 16 channel wavetable',
    bestFor: ['Seta arcade', 'Wavetable', 'Twin Eagle'],
    icon: 'Waves',
    color: 'text-lime-400',
  },
  FurnaceBUBBLE: {
    type: 'FurnaceBUBBLE',
    name: 'Bubble System',
    shortName: 'BUBBLE',
    description: 'Konami Bubble System - wavetable',
    bestFor: ['Konami arcade', 'Bubble System', 'Wavetable'],
    icon: 'Circle',
    color: 'text-sky-400',
  },
  // Other chips
  FurnaceSM8521: {
    type: 'FurnaceSM8521',
    name: 'SM8521',
    shortName: 'SM8521',
    description: 'Sharp SM8521 - Game.com',
    bestFor: ['Game.com', 'Tiger electronics', 'Obscure'],
    icon: 'Smartphone',
    color: 'text-gray-500',
  },
  FurnaceT6W28: {
    type: 'FurnaceT6W28',
    name: 'T6W28',
    shortName: 'T6W28',
    description: 'NEC T6W28 - PC-6001, stereo PSG',
    bestFor: ['NEC PC-6001', 'Japanese PC', 'Stereo PSG'],
    icon: 'Monitor',
    color: 'text-blue-300',
  },
  FurnaceSUPERVISION: {
    type: 'FurnaceSUPERVISION',
    name: 'Supervision',
    shortName: 'SV',
    description: 'Watara Supervision - 4 channel + noise/DMA',
    bestFor: ['Supervision', 'Portable gaming', 'Watara'],
    icon: 'Gamepad',
    color: 'text-emerald-400',
  },
  FurnaceUPD1771: {
    type: 'FurnaceUPD1771',
    name: 'μPD1771',
    shortName: 'UPD1771',
    description: 'NEC μPD1771 - Epoch Super Cassette Vision',
    bestFor: ['Super Cassette Vision', 'Epoch', 'Japanese'],
    icon: 'Tv',
    color: 'text-stone-400',
  },
  ChiptuneModule: {
    type: 'ChiptuneModule',
    name: 'Chiptune Module',
    shortName: 'MOD',
    description: 'Libopenmpt-powered playback for MOD/XM/IT/S3M files',
    bestFor: ['Tracker modules', 'Retro game music', 'Sample-accurate playback'],
    icon: 'Gamepad2',
    color: 'text-lime-400',
  },
  WobbleBass: {
    type: 'WobbleBass',
    name: 'Wobble Bass',
    shortName: 'Wobble',
    description: 'Dubstep/DnB bass with tempo-synced LFO, Reese detuning, FM growl',
    bestFor: ['Dubstep', 'DnB', 'Jungle', 'Neurofunk', 'Riddim'],
    icon: 'Waves',
    color: 'text-fuchsia-500',
  },
  DrumKit: {
    type: 'DrumKit',
    name: 'Drum Kit',
    shortName: 'Kit',
    description: 'Multi-sample instrument with keymap - assign different samples to different notes',
    bestFor: ['Drum kits', 'Instrument layers', 'Velocity splits', 'Sample mapping'],
    icon: 'Piano',
    color: 'text-amber-500',
  },
};

// Organized categories
export const SYNTH_CATEGORIES: SynthCategory[] = [
  {
    id: 'bass',
    name: 'Bass',
    description: 'Deep and punchy bass synths',
    synths: [SYNTH_INFO.TB303, SYNTH_INFO.MonoSynth, SYNTH_INFO.SuperSaw, SYNTH_INFO.WobbleBass],
  },
  {
    id: 'lead',
    name: 'Lead',
    description: 'Melodic lead synthesizers',
    synths: [
      SYNTH_INFO.Synth,
      SYNTH_INFO.DuoSynth,
      SYNTH_INFO.FMSynth,
      SYNTH_INFO.AMSynth,
      SYNTH_INFO.PluckSynth,
      SYNTH_INFO.SuperSaw,
      SYNTH_INFO.ChipSynth,
      SYNTH_INFO.PWMSynth,
      SYNTH_INFO.FormantSynth,
    ],
  },
  {
    id: 'drums',
    name: 'Drums',
    description: 'Percussion and drum synthesis',
    synths: [SYNTH_INFO.MembraneSynth, SYNTH_INFO.MetalSynth, SYNTH_INFO.NoiseSynth, SYNTH_INFO.DrumMachine, SYNTH_INFO.DrumKit],
  },
  {
    id: 'pads',
    name: 'Pads',
    description: 'Evolving textures and pads',
    synths: [SYNTH_INFO.Synth, SYNTH_INFO.DuoSynth, SYNTH_INFO.Wavetable, SYNTH_INFO.GranularSynth, SYNTH_INFO.PolySynth, SYNTH_INFO.StringMachine, SYNTH_INFO.PWMSynth],
  },
  {
    id: 'keys',
    name: 'Keys',
    description: 'Keyboard instruments',
    synths: [SYNTH_INFO.FMSynth, SYNTH_INFO.Organ, SYNTH_INFO.FurnaceOPZ],
  },
  {
    id: 'samples',
    name: 'Samples',
    description: 'Sample-based instruments',
    synths: [SYNTH_INFO.Sampler, SYNTH_INFO.Player, SYNTH_INFO.GranularSynth],
  },
  {
    id: 'chiptune-fm',
    name: 'FM Chips',
    description: 'Yamaha FM synthesis chips (OPN, OPL, OPM families)',
    synths: [
      SYNTH_INFO.FurnaceOPN,
      SYNTH_INFO.FurnaceOPNA,
      SYNTH_INFO.FurnaceOPNB,
      SYNTH_INFO.FurnaceOPM,
      SYNTH_INFO.FurnaceOPL,
      SYNTH_INFO.FurnaceOPLL,
      SYNTH_INFO.FurnaceOPL4,
      SYNTH_INFO.FurnaceOPZ,
      SYNTH_INFO.FurnaceY8950,
      SYNTH_INFO.FurnaceESFM,
      SYNTH_INFO.FurnaceVRC7,
    ],
  },
  {
    id: 'chiptune-console',
    name: 'Console Chips',
    description: 'Game console sound chips (Nintendo, Sega, etc.)',
    synths: [
      SYNTH_INFO.FurnaceNES,
      SYNTH_INFO.FurnaceGB,
      SYNTH_INFO.FurnaceSNES,
      SYNTH_INFO.FurnacePCE,
      SYNTH_INFO.FurnacePSG,
      SYNTH_INFO.FurnaceVB,
      SYNTH_INFO.FurnaceLynx,
      SYNTH_INFO.FurnaceSWAN,
      SYNTH_INFO.FurnaceVRC6,
      SYNTH_INFO.FurnaceN163,
      SYNTH_INFO.FurnaceFDS,
      SYNTH_INFO.FurnaceMMC5,
    ],
  },
  {
    id: 'chiptune-computer',
    name: 'Computer Chips',
    description: 'Home computer sound chips (C64, Spectrum, etc.)',
    synths: [
      SYNTH_INFO.FurnaceC64,
      SYNTH_INFO.FurnaceAY,
      SYNTH_INFO.FurnaceVIC,
      SYNTH_INFO.FurnaceSAA,
      SYNTH_INFO.FurnaceTED,
      SYNTH_INFO.FurnaceVERA,
      SYNTH_INFO.FurnaceSCC,
      SYNTH_INFO.FurnaceTIA,
    ],
  },
  {
    id: 'chiptune-arcade',
    name: 'Arcade PCM',
    description: 'Arcade game PCM/ADPCM chips (Sega, Namco, Konami, Capcom)',
    synths: [
      SYNTH_INFO.FurnaceSEGAPCM,
      SYNTH_INFO.FurnaceQSOUND,
      SYNTH_INFO.FurnaceES5506,
      SYNTH_INFO.FurnaceRF5C68,
      SYNTH_INFO.FurnaceC140,
      SYNTH_INFO.FurnaceK007232,
      SYNTH_INFO.FurnaceK053260,
      SYNTH_INFO.FurnaceGA20,
      SYNTH_INFO.FurnaceOKI,
      SYNTH_INFO.FurnaceYMZ280B,
      SYNTH_INFO.FurnaceX1_010,
      SYNTH_INFO.FurnaceBUBBLE,
    ],
  },
  {
    id: 'chiptune-other',
    name: 'Other Chips',
    description: 'Obscure and miscellaneous sound chips',
    synths: [
      SYNTH_INFO.FurnaceSM8521,
      SYNTH_INFO.FurnaceT6W28,
      SYNTH_INFO.FurnaceSUPERVISION,
      SYNTH_INFO.FurnaceUPD1771,
      SYNTH_INFO.Furnace, // Generic fallback
    ],
  },
];

// Get all synth types as a flat list (sorted A-Z by short name)
export const ALL_SYNTH_TYPES: SynthType[] = (Object.keys(SYNTH_INFO) as SynthType[]).sort((a, b) =>
  SYNTH_INFO[a].shortName.localeCompare(SYNTH_INFO[b].shortName)
);

// Helper to get category for a synth type (returns primary category)
export function getCategoryForSynth(synthType: SynthType): SynthCategory | undefined {
  return SYNTH_CATEGORIES.find((cat) => cat.synths.some((s) => s.type === synthType));
}

// Helper to get synth info
export function getSynthInfo(synthType: SynthType): SynthInfo {
  return SYNTH_INFO[synthType];
}
