/**
 * Synth Categories - Organized synth types with descriptions and guidance
 */

import type { SynthType } from '@typedefs/instrument';

export interface SynthInfo {
  type: SynthType;
  name: string;
  shortName: string;
  description: string;
  bestFor: string[];
  icon: string; // Lucide icon name
  color: string; // Tailwind color class
}

export interface SynthCategory {
  id: string;
  name: string;
  description: string;
  synths: SynthInfo[];
}

// Individual synth information
export const SYNTH_INFO: Record<SynthType, SynthInfo> = {
  TB303: {
    type: 'TB303',
    name: 'TB-303',
    shortName: '303',
    description: 'Classic acid bass synthesizer with resonant filter and slide',
    bestFor: ['Acid bass', 'Squelchy lines', 'Techno', 'House'],
    icon: 'Zap',
    color: 'text-accent-primary',
  },
  MonoSynth: {
    type: 'MonoSynth',
    name: 'Mono Synth',
    shortName: 'Mono',
    description: 'Single-voice synth with oscillator, filter, and envelope',
    bestFor: ['Bass', 'Lead lines', 'Portamento'],
    icon: 'AudioLines',
    color: 'text-blue-400',
  },
  Synth: {
    type: 'Synth',
    name: 'Basic Synth',
    shortName: 'Synth',
    description: 'Simple polyphonic synthesizer with amplitude envelope',
    bestFor: ['Pads', 'Chords', 'Simple sounds'],
    icon: 'Music2',
    color: 'text-purple-400',
  },
  DuoSynth: {
    type: 'DuoSynth',
    name: 'Duo Synth',
    shortName: 'Duo',
    description: 'Two-voice synth with harmonics and vibratoesque LFO',
    bestFor: ['Rich leads', 'Detuned sounds', 'Fat bass'],
    icon: 'Layers',
    color: 'text-indigo-400',
  },
  FMSynth: {
    type: 'FMSynth',
    name: 'FM Synth',
    shortName: 'FM',
    description: 'Frequency modulation synth for complex harmonic tones',
    bestFor: ['Bells', 'Electric piano', 'Metallic sounds'],
    icon: 'Radio',
    color: 'text-cyan-400',
  },
  AMSynth: {
    type: 'AMSynth',
    name: 'AM Synth',
    shortName: 'AM',
    description: 'Amplitude modulation synth with ring modulation character',
    bestFor: ['Tremolo effects', 'Ring mod', 'Atmospheric'],
    icon: 'Activity',
    color: 'text-teal-400',
  },
  PluckSynth: {
    type: 'PluckSynth',
    name: 'Pluck Synth',
    shortName: 'Pluck',
    description: 'Karplus-Strong string synthesis for plucked strings',
    bestFor: ['Guitar', 'Harp', 'Pizzicato', 'String plucks'],
    icon: 'Guitar',
    color: 'text-amber-400',
  },
  MembraneSynth: {
    type: 'MembraneSynth',
    name: 'Membrane Synth',
    shortName: 'Membrane',
    description: 'Drum membrane simulation for kicks and toms',
    bestFor: ['Kick drums', 'Toms', 'Percussion'],
    icon: 'Circle',
    color: 'text-orange-400',
  },
  MetalSynth: {
    type: 'MetalSynth',
    name: 'Metal Synth',
    shortName: 'Metal',
    description: 'Metallic percussion synthesis with harmonics',
    bestFor: ['Hi-hats', 'Cymbals', 'Bells', 'Metallic hits'],
    icon: 'Hexagon',
    color: 'text-yellow-400',
  },
  NoiseSynth: {
    type: 'NoiseSynth',
    name: 'Noise Synth',
    shortName: 'Noise',
    description: 'Filtered noise generator with envelope',
    bestFor: ['Snares', 'Hi-hats', 'Risers', 'FX'],
    icon: 'Hash',
    color: 'text-gray-400',
  },
  Wavetable: {
    type: 'Wavetable',
    name: 'Wavetable',
    shortName: 'Wave',
    description: 'Wavetable synth with morphing and unison',
    bestFor: ['Evolving pads', 'Modern bass', 'Complex timbres'],
    icon: 'Waves',
    color: 'text-pink-400',
  },
  Sampler: {
    type: 'Sampler',
    name: 'Sampler',
    shortName: 'Sampler',
    description: 'Multi-sample playback with velocity layers',
    bestFor: ['Realistic instruments', 'Sample kits', 'One-shots'],
    icon: 'FileAudio',
    color: 'text-rose-400',
  },
  Player: {
    type: 'Player',
    name: 'Sample Player',
    shortName: 'Player',
    description: 'Simple one-shot sample playback',
    bestFor: ['Loops', 'One-shots', 'Vocal samples'],
    icon: 'Play',
    color: 'text-lime-400',
  },
  GranularSynth: {
    type: 'GranularSynth',
    name: 'Granular Synth',
    shortName: 'Granular',
    description: 'Sample-based granular synthesis with grain manipulation',
    bestFor: ['Textures', 'Pads', 'Ambient', 'Sound design', 'Glitch'],
    icon: 'Sparkles',
    color: 'text-violet-400',
  },
  // New synths
  SuperSaw: {
    type: 'SuperSaw',
    name: 'SuperSaw',
    shortName: 'SSaw',
    description: 'Massive detuned saw waves for trance and EDM',
    bestFor: ['Trance leads', 'EDM drops', 'Big chords', 'Supersaw stabs'],
    icon: 'Layers',
    color: 'text-orange-500',
  },
  PolySynth: {
    type: 'PolySynth',
    name: 'Poly Synth',
    shortName: 'Poly',
    description: 'True polyphonic synth with voice management',
    bestFor: ['Chords', 'Pads', 'Polyphonic parts', 'Layered sounds'],
    icon: 'LayoutGrid',
    color: 'text-blue-500',
  },
  Organ: {
    type: 'Organ',
    name: 'Drawbar Organ',
    shortName: 'Organ',
    description: 'Hammond-style tonewheel organ with drawbars',
    bestFor: ['House', 'Gospel', 'Jazz', 'Rock organ'],
    icon: 'Piano',
    color: 'text-amber-600',
  },
  DrumMachine: {
    type: 'DrumMachine',
    name: 'Drum Machine',
    shortName: '808/909',
    description: 'Analog drum synthesis (808/909 style)',
    bestFor: ['Kicks', 'Snares', 'Hi-hats', 'Electronic drums'],
    icon: 'Disc',
    color: 'text-red-500',
  },
  ChipSynth: {
    type: 'ChipSynth',
    name: 'Chip Synth',
    shortName: 'Chip',
    description: '8-bit video game console sounds',
    bestFor: ['Chiptune', 'Retro', 'Lo-fi', 'Arpeggios'],
    icon: 'Gamepad2',
    color: 'text-green-400',
  },
  PWMSynth: {
    type: 'PWMSynth',
    name: 'PWM Synth',
    shortName: 'PWM',
    description: 'Pulse width modulation for rich analog tones',
    bestFor: ['Analog pads', 'Warm leads', 'Classic synth'],
    icon: 'Waves',
    color: 'text-emerald-400',
  },
  StringMachine: {
    type: 'StringMachine',
    name: 'String Machine',
    shortName: 'Strings',
    description: 'Vintage ensemble strings (Solina-style)',
    bestFor: ['Lush pads', 'Disco strings', 'Ambient', 'Retro'],
    icon: 'Music4',
    color: 'text-rose-400',
  },
  FormantSynth: {
    type: 'FormantSynth',
    name: 'Formant Synth',
    shortName: 'Vocal',
    description: 'Vowel synthesis for vocal-like sounds',
    bestFor: ['Vocal pads', 'Talk box', 'Choir', 'Robotic'],
    icon: 'Mic',
    color: 'text-fuchsia-400',
  },
  Furnace: {
    type: 'Furnace',
    name: 'Furnace FM',
    shortName: 'FUI',
    description: 'FM engine compatible with Furnace Tracker (.fui) instruments',
    bestFor: ['Genesis bass', 'FM bells', 'Retro arcade', '4-op FM'],
    icon: 'Cpu',
    color: 'text-amber-500',
  },
  // Furnace Chip Types
  FurnaceOPN: {
    type: 'FurnaceOPN',
    name: 'Sega Genesis (YM2612)',
    shortName: 'Genesis',
    description: 'Sega Genesis / Mega Drive YM2612 - 6 channels of 4-op FM',
    bestFor: ['Genesis bass', 'FM leads', 'Slap bass', '16-bit game music'],
    icon: 'Gamepad2',
    color: 'text-blue-500',
  },
  FurnaceOPM: {
    type: 'FurnaceOPM',
    name: 'Arcade / X68000 (YM2151)',
    shortName: 'OPM',
    description: 'Yamaha YM2151 - Sharp X68000, arcade machines',
    bestFor: ['Arcade FM', 'Bright leads', 'Brass', 'Game music'],
    icon: 'Cpu',
    color: 'text-cyan-500',
  },
  FurnaceOPL: {
    type: 'FurnaceOPL',
    name: 'AdLib / Sound Blaster (OPL3)',
    shortName: 'OPL3',
    description: 'Yamaha YMF262 - AdLib, Sound Blaster, DOS games',
    bestFor: ['DOS game music', 'MIDI synth', 'Organs', 'PC gaming'],
    icon: 'Monitor',
    color: 'text-yellow-500',
  },
  FurnaceOPLL: {
    type: 'FurnaceOPLL',
    name: 'MSX / Sega (OPLL)',
    shortName: 'OPLL',
    description: 'Yamaha YM2413 - MSX, SMS FM unit, budget FM',
    bestFor: ['MSX music', 'SMS FM', 'Lo-fi FM', 'Simple FM'],
    icon: 'Radio',
    color: 'text-orange-400',
  },
  FurnaceESFM: {
    type: 'FurnaceESFM',
    name: 'ESFM',
    shortName: 'ESFM',
    description: 'Enhanced Sound FM - advanced OPL3 with operator detune',
    bestFor: ['Modern retro', 'Enhanced FM', 'Detuned sounds'],
    icon: 'Zap',
    color: 'text-purple-500',
  },
  FurnaceOPZ: {
    type: 'FurnaceOPZ',
    name: 'Yamaha TX81Z (OPZ)',
    shortName: 'OPZ',
    description: 'Yamaha YM2414 - TX81Z, DX11, advanced FM',
    bestFor: ['Lately bass', 'DX bells', 'Complex FM', 'E-piano'],
    icon: 'Piano',
    color: 'text-indigo-500',
  },
  FurnaceNES: {
    type: 'FurnaceNES',
    name: 'Nintendo NES (2A03)',
    shortName: 'NES',
    description: 'Nintendo Entertainment System - 2 pulse, triangle, noise, DPCM',
    bestFor: ['NES chiptune', '8-bit melodies', 'Retro drums', 'Famicom'],
    icon: 'Gamepad2',
    color: 'text-red-500',
  },
  FurnaceGB: {
    type: 'FurnaceGB',
    name: 'Nintendo Game Boy',
    shortName: 'GB',
    description: 'Nintendo Game Boy - 2 pulse, wave, noise channels',
    bestFor: ['Game Boy music', 'Lo-fi chiptune', 'Portable gaming'],
    icon: 'Smartphone',
    color: 'text-green-500',
  },
  FurnaceC64: {
    type: 'FurnaceC64',
    name: 'Commodore 64 (SID)',
    shortName: 'SID',
    description: 'Commodore 64 SID chip - 3 voices with filters',
    bestFor: ['SID leads', 'Arpeggios', 'Filter sweeps', 'Demoscene'],
    icon: 'Terminal',
    color: 'text-violet-500',
  },
  FurnaceAY: {
    type: 'FurnaceAY',
    name: 'ZX Spectrum / Amstrad (AY)',
    shortName: 'AY',
    description: 'General Instrument AY - ZX Spectrum, MSX, Atari ST',
    bestFor: ['ZX Spectrum', 'MSX', 'Amstrad CPC', 'Envelope tricks'],
    icon: 'Tv',
    color: 'text-sky-500',
  },
  FurnaceTIA: {
    type: 'FurnaceTIA',
    name: 'Atari TIA',
    shortName: 'TIA',
    description: 'Atari 2600 - primitive but distinctive sound',
    bestFor: ['Atari 2600', 'Primitive bleeps', 'Retro FX'],
    icon: 'Joystick',
    color: 'text-amber-600',
  },
  FurnaceVERA: {
    type: 'FurnaceVERA',
    name: 'Commander X16 (VERA)',
    shortName: 'VERA',
    description: 'Commander X16 - modern retro 16 channels PSG + PCM',
    bestFor: ['Modern retro', 'X16 music', 'Rich PSG'],
    icon: 'Cpu',
    color: 'text-teal-500',
  },
  FurnaceSAA: {
    type: 'FurnaceSAA',
    name: 'SAM Coupé (SAA1099)',
    shortName: 'SAA',
    description: 'Philips SAA1099 - Sam Coupé, some PC sound cards',
    bestFor: ['Sam Coupé', 'Stereo chips', 'European home computers'],
    icon: 'Speaker',
    color: 'text-pink-500',
  },
  FurnacePSG: {
    type: 'FurnacePSG',
    name: 'Sega Master System (PSG)',
    shortName: 'PSG',
    description: 'TI SN76489 - Master System, Game Gear, BBC Micro',
    bestFor: ['Master System', 'Colecovision', 'Square wave PSG'],
    icon: 'SquareStack',
    color: 'text-emerald-500',
  },
  FurnaceVIC: {
    type: 'FurnaceVIC',
    name: 'Commodore VIC-20',
    shortName: 'VIC',
    description: 'Commodore VIC-20 - 3 square + noise',
    bestFor: ['VIC-20 music', 'Early 80s', 'Simple tones'],
    icon: 'Monitor',
    color: 'text-lime-500',
  },
  FurnaceLynx: {
    type: 'FurnaceLynx',
    name: 'Atari Lynx',
    shortName: 'Lynx',
    description: 'Atari Lynx - 4 channel wavetable',
    bestFor: ['Lynx music', 'Portable gaming', 'Wavetable'],
    icon: 'Gamepad',
    color: 'text-rose-500',
  },
  // Furnace Chip Types
  FurnaceSID6581: {
    type: 'FurnaceSID6581',
    name: 'SID 6581',
    shortName: '6581',
    description: 'Classic C64 SID - warm, gritty original chip',
    bestFor: ['Authentic C64', 'Warm bass', 'Classic demoscene'],
    icon: 'Terminal',
    color: 'text-violet-400',
  },
  FurnaceSID8580: {
    type: 'FurnaceSID8580',
    name: 'SID 8580',
    shortName: '8580',
    description: 'Revised SID - cleaner filter, brighter sound',
    bestFor: ['Clean SID', 'Later C64/C128', 'Clearer filters'],
    icon: 'Terminal',
    color: 'text-violet-600',
  },
  // Additional FM chips
  FurnaceOPNA: {
    type: 'FurnaceOPNA',
    name: 'NEC PC-98 (OPNA)',
    shortName: 'OPNA',
    description: 'YM2608 - NEC PC-98, arcade machines',
    bestFor: ['PC-98 music', 'Touhou-style', 'Japanese arcade'],
    icon: 'Cpu',
    color: 'text-blue-400',
  },
  FurnaceOPNB: {
    type: 'FurnaceOPNB',
    name: 'SNK Neo Geo (OPNB)',
    shortName: 'OPNB',
    description: 'YM2610 - SNK Neo Geo',
    bestFor: ['Neo Geo music', 'Fighting games', 'SNK'],
    icon: 'Gamepad2',
    color: 'text-red-400',
  },
  FurnaceOPL4: {
    type: 'FurnaceOPL4',
    name: 'Yamaha OPL4',
    shortName: 'OPL4',
    description: 'Yamaha YMF278 - FM + wavetable hybrid',
    bestFor: ['Advanced OPL', 'FM + samples', 'Late DOS'],
    icon: 'Layers',
    color: 'text-yellow-400',
  },
  FurnaceY8950: {
    type: 'FurnaceY8950',
    name: 'MSX-Audio (Y8950)',
    shortName: 'Y8950',
    description: 'Yamaha Y8950 - MSX-Audio, OPL + ADPCM',
    bestFor: ['MSX-Audio', 'OPL with drums', 'Japanese PC'],
    icon: 'Radio',
    color: 'text-orange-300',
  },
  // Console chips
  FurnacePCE: {
    type: 'FurnacePCE',
    name: 'PC Engine / TurboGrafx',
    shortName: 'PCE',
    description: 'PC Engine / TurboGrafx-16 - 6 channel wavetable',
    bestFor: ['PC Engine', 'TurboGrafx', 'HuCard games'],
    icon: 'Tv',
    color: 'text-orange-500',
  },
  FurnaceSNES: {
    type: 'FurnaceSNES',
    name: 'Super Nintendo (SPC700)',
    shortName: 'SNES',
    description: 'Super Nintendo - Sony SPC700 8-channel BRR',
    bestFor: ['SNES music', '16-bit classics', 'BRR samples'],
    icon: 'Gamepad2',
    color: 'text-purple-400',
  },
  FurnaceVB: {
    type: 'FurnaceVB',
    name: 'Nintendo Virtual Boy',
    shortName: 'VB',
    description: 'Nintendo Virtual Boy - 6 channel wavetable',
    bestFor: ['Virtual Boy', 'Stereo 3D audio', 'Nintendo VB'],
    icon: 'Glasses',
    color: 'text-red-600',
  },
  FurnaceSWAN: {
    type: 'FurnaceSWAN',
    name: 'Bandai WonderSwan',
    shortName: 'SWAN',
    description: 'Bandai WonderSwan - 4 channel wavetable + PCM',
    bestFor: ['WonderSwan', 'Portable gaming', 'Bandai'],
    icon: 'Smartphone',
    color: 'text-cyan-400',
  },
  // NES Expansion
  FurnaceVRC6: {
    type: 'FurnaceVRC6',
    name: 'Famicom (VRC6)',
    shortName: 'VRC6',
    description: 'Konami VRC6 - 2 pulse + saw (Castlevania 3 JP)',
    bestFor: ['Castlevania 3', 'Konami NES', 'Extra channels'],
    icon: 'Zap',
    color: 'text-amber-400',
  },
  FurnaceVRC7: {
    type: 'FurnaceVRC7',
    name: 'Famicom (VRC7)',
    shortName: 'VRC7',
    description: 'Konami VRC7 - OPLL clone (Lagrange Point)',
    bestFor: ['Lagrange Point', 'FM on NES', 'Konami FM'],
    icon: 'Radio',
    color: 'text-amber-500',
  },
  FurnaceN163: {
    type: 'FurnaceN163',
    name: 'Namco Arcade (N163)',
    shortName: 'N163',
    description: 'Namco 163 - 8 channel wavetable',
    bestFor: ['Namco NES', 'Wavetable', 'Complex tones'],
    icon: 'Waves',
    color: 'text-green-400',
  },
  FurnaceFDS: {
    type: 'FurnaceFDS',
    name: 'Famicom Disk System',
    shortName: 'FDS',
    description: 'Famicom Disk System - wavetable + modulation',
    bestFor: ['FDS games', 'Wavy bass', 'Zelda FDS'],
    icon: 'Disc',
    color: 'text-yellow-500',
  },
  FurnaceMMC5: {
    type: 'FurnaceMMC5',
    name: 'Famicom (MMC5)',
    shortName: 'MMC5',
    description: 'MMC5 - 2 extra pulse channels',
    bestFor: ['Castlevania 3 US', 'Extra NES pulse', 'CV3'],
    icon: 'Plus',
    color: 'text-blue-300',
  },
  // Computer chips
  FurnaceTED: {
    type: 'FurnaceTED',
    name: 'Commodore Plus/4 (TED)',
    shortName: 'TED',
    description: 'Commodore Plus/4 TED - 2 square + noise',
    bestFor: ['Plus/4 music', 'Commodore 16', 'Budget C64'],
    icon: 'Monitor',
    color: 'text-violet-400',
  },
  // Arcade PCM chips
  FurnaceSEGAPCM: {
    type: 'FurnaceSEGAPCM',
    name: 'Sega Arcade (SegaPCM)',
    shortName: 'SEGAPCM',
    description: 'Sega System 16/18 - 16 channel PCM',
    bestFor: ['OutRun', 'After Burner', 'Sega arcade'],
    icon: 'Speaker',
    color: 'text-blue-500',
  },
  FurnaceQSOUND: {
    type: 'FurnaceQSOUND',
    name: 'Capcom Arcade (QSound)',
    shortName: 'QSound',
    description: 'Capcom QSound - CPS1/CPS2 with 3D audio',
    bestFor: ['Street Fighter', 'CPS games', '3D positioning'],
    icon: 'Headphones',
    color: 'text-purple-500',
  },
  FurnaceES5506: {
    type: 'FurnaceES5506',
    name: 'ES5506',
    shortName: 'ES5506',
    description: 'Ensoniq ES5506 - 32 voice wavetable',
    bestFor: ['Taito F3', 'Ensoniq synths', 'High quality'],
    icon: 'AudioLines',
    color: 'text-pink-400',
  },
  FurnaceRF5C68: {
    type: 'FurnaceRF5C68',
    name: 'RF5C68',
    shortName: 'RF5C68',
    description: 'Ricoh RF5C68 - Sega CD, 8 channel PCM',
    bestFor: ['Sega CD', 'Mega CD', 'CD audio'],
    icon: 'Disc',
    color: 'text-cyan-500',
  },
  FurnaceC140: {
    type: 'FurnaceC140',
    name: 'C140',
    shortName: 'C140',
    description: 'Namco C140 - System 2, 24 channel PCM',
    bestFor: ['Namco arcade', 'System 2', 'Assault'],
    icon: 'Cpu',
    color: 'text-yellow-400',
  },
  FurnaceK007232: {
    type: 'FurnaceK007232',
    name: 'K007232',
    shortName: 'K007232',
    description: 'Konami K007232 - 2 channel PCM',
    bestFor: ['Contra arcade', 'Konami PCM', 'TMNT'],
    icon: 'Speaker',
    color: 'text-red-400',
  },
  FurnaceK053260: {
    type: 'FurnaceK053260',
    name: 'K053260',
    shortName: 'K053260',
    description: 'Konami K053260 - 4 channel PCM with ADPCM',
    bestFor: ['Sunset Riders', 'Simpsons', 'Konami 90s'],
    icon: 'Speaker',
    color: 'text-orange-400',
  },
  FurnaceGA20: {
    type: 'FurnaceGA20',
    name: 'GA20',
    shortName: 'GA20',
    description: 'Irem GA20 - 4 channel PCM',
    bestFor: ['R-Type Leo', 'Irem arcade', 'In the Hunt'],
    icon: 'Cpu',
    color: 'text-teal-400',
  },
  FurnaceOKI: {
    type: 'FurnaceOKI',
    name: 'OKI MSM6295',
    shortName: 'OKI',
    description: 'OKI MSM6295 - 4 channel ADPCM',
    bestFor: ['Neo Geo', 'Data East', 'ADPCM drums'],
    icon: 'Volume2',
    color: 'text-gray-400',
  },
  FurnaceYMZ280B: {
    type: 'FurnaceYMZ280B',
    name: 'YMZ280B',
    shortName: 'YMZ280B',
    description: 'Yamaha YMZ280B - 8 channel ADPCM',
    bestFor: ['Cave shmups', 'Late arcade', 'High quality'],
    icon: 'AudioLines',
    color: 'text-indigo-400',
  },
  // Wavetable chips
  FurnaceSCC: {
    type: 'FurnaceSCC',
    name: 'Konami SCC',
    shortName: 'SCC',
    description: 'Konami SCC - 5 channel wavetable (MSX)',
    bestFor: ['Gradius', 'Snatcher', 'MSX Konami'],
    icon: 'Waves',
    color: 'text-green-500',
  },
  FurnaceX1_010: {
    type: 'FurnaceX1_010',
    name: 'X1-010',
    shortName: 'X1-010',
    description: 'Seta X1-010 - 16 channel wavetable',
    bestFor: ['Seta arcade', 'Wavetable', 'Twin Eagle'],
    icon: 'Waves',
    color: 'text-lime-400',
  },
  FurnaceBUBBLE: {
    type: 'FurnaceBUBBLE',
    name: 'Bubble System',
    shortName: 'BUBBLE',
    description: 'Konami Bubble System - wavetable',
    bestFor: ['Konami arcade', 'Bubble System', 'Wavetable'],
    icon: 'Circle',
    color: 'text-sky-400',
  },
  // Other chips
  FurnaceSM8521: {
    type: 'FurnaceSM8521',
    name: 'SM8521',
    shortName: 'SM8521',
    description: 'Sharp SM8521 - Game.com',
    bestFor: ['Game.com', 'Tiger electronics', 'Obscure'],
    icon: 'Smartphone',
    color: 'text-gray-500',
  },
  FurnaceT6W28: {
    type: 'FurnaceT6W28',
    name: 'T6W28',
    shortName: 'T6W28',
    description: 'NEC T6W28 - PC-6001, stereo PSG',
    bestFor: ['NEC PC-6001', 'Japanese PC', 'Stereo PSG'],
    icon: 'Monitor',
    color: 'text-blue-300',
  },
  FurnaceSUPERVISION: {
    type: 'FurnaceSUPERVISION',
    name: 'Supervision',
    shortName: 'SV',
    description: 'Watara Supervision - 4 channel + noise/DMA',
    bestFor: ['Supervision', 'Portable gaming', 'Watara'],
    icon: 'Gamepad',
    color: 'text-emerald-400',
  },
  FurnaceUPD1771: {
    type: 'FurnaceUPD1771',
    name: 'μPD1771',
    shortName: 'UPD1771',
    description: 'NEC μPD1771 - Epoch Super Cassette Vision',
    bestFor: ['Super Cassette Vision', 'Epoch', 'Japanese'],
    icon: 'Tv',
    color: 'text-stone-400',
  },
  // NEW Furnace Chip Types (47-72)
  FurnaceOPN2203: {
    type: 'FurnaceOPN2203',
    name: 'YM2203 / OPN',
    shortName: 'OPN',
    description: 'YM2203 - PC-88/98, simpler 3-channel FM + SSG',
    bestFor: ['PC-88 music', 'Japanese PC games', 'Simpler FM'],
    icon: 'Cpu',
    color: 'text-blue-300',
  },
  FurnaceOPNBB: {
    type: 'FurnaceOPNBB',
    name: 'YM2610B',
    shortName: 'OPNB-B',
    description: 'YM2610B - Extended Neo Geo with more FM channels',
    bestFor: ['Neo Geo CD', 'Extended OPNB', 'SNK'],
    icon: 'Gamepad2',
    color: 'text-red-300',
  },
  FurnaceAY8930: {
    type: 'FurnaceAY8930',
    name: 'AY-8930',
    shortName: 'AY+',
    description: 'Enhanced AY-3-8910 with expanded features',
    bestFor: ['Enhanced chiptune', 'Extended AY', 'Microchip'],
    icon: 'Tv',
    color: 'text-sky-400',
  },
  FurnaceNDS: {
    type: 'FurnaceNDS',
    name: 'Nintendo DS',
    shortName: 'NDS',
    description: 'Nintendo DS - 16 channel PCM/PSG',
    bestFor: ['NDS music', 'Portable gaming', 'Modern chiptune'],
    icon: 'Smartphone',
    color: 'text-slate-400',
  },
  FurnaceGBA: {
    type: 'FurnaceGBA',
    name: 'Game Boy Advance',
    shortName: 'GBA',
    description: 'GBA DMA Sound - 2 channel direct PCM',
    bestFor: ['GBA music', 'Portable gaming', 'PCM'],
    icon: 'Gamepad',
    color: 'text-purple-300',
  },
  FurnacePOKEMINI: {
    type: 'FurnacePOKEMINI',
    name: 'Pokemon Mini',
    shortName: 'PKMN',
    description: 'Pokemon Mini - tiny handheld sound',
    bestFor: ['Pokemon Mini', 'Tiny tunes', 'Lo-fi'],
    icon: 'Star',
    color: 'text-yellow-300',
  },
  FurnaceNAMCO: {
    type: 'FurnaceNAMCO',
    name: 'Namco WSG',
    shortName: 'WSG',
    description: 'Namco WSG - Pac-Man, Galaga wavetable',
    bestFor: ['Pac-Man', 'Galaga', 'Classic arcade'],
    icon: 'Circle',
    color: 'text-yellow-400',
  },
  FurnacePET: {
    type: 'FurnacePET',
    name: 'Commodore PET',
    shortName: 'PET',
    description: 'Commodore PET - single voice shift register',
    bestFor: ['PET music', 'Early 80s', 'Primitive'],
    icon: 'Monitor',
    color: 'text-green-300',
  },
  FurnacePOKEY: {
    type: 'FurnacePOKEY',
    name: 'Atari POKEY',
    shortName: 'POKEY',
    description: 'Atari POKEY - Atari 800/5200/arcade',
    bestFor: ['Atari 8-bit', 'Atari arcade', 'Classic chiptune'],
    icon: 'Joystick',
    color: 'text-orange-400',
  },
  FurnaceMSM6258: {
    type: 'FurnaceMSM6258',
    name: 'MSM6258',
    shortName: 'MSM6258',
    description: 'OKI MSM6258 - 4-bit ADPCM voice',
    bestFor: ['Voice samples', 'ADPCM', 'Japanese arcade'],
    icon: 'Mic',
    color: 'text-pink-300',
  },
  FurnaceMSM5232: {
    type: 'FurnaceMSM5232',
    name: 'MSM5232',
    shortName: 'MSM5232',
    description: 'OKI MSM5232 - 8-voice PSG synthesizer',
    bestFor: ['Early arcade', 'Organ sounds', '8-voice'],
    icon: 'Music2',
    color: 'text-amber-300',
  },
  FurnaceMULTIPCM: {
    type: 'FurnaceMULTIPCM',
    name: 'Sega MultiPCM',
    shortName: 'MPCM',
    description: 'Sega MultiPCM - System 32, Model 1/2',
    bestFor: ['Virtua Racing', 'Sega arcade', 'High quality PCM'],
    icon: 'Headphones',
    color: 'text-blue-400',
  },
  FurnaceAMIGA: {
    type: 'FurnaceAMIGA',
    name: 'Amiga Paula',
    shortName: 'PAULA',
    description: 'Amiga Paula - 4 channel 8-bit PCM',
    bestFor: ['Amiga MODs', 'Demoscene', 'Classic samples'],
    icon: 'Disc',
    color: 'text-slate-300',
  },
  FurnacePCSPKR: {
    type: 'FurnacePCSPKR',
    name: 'PC Speaker',
    shortName: 'PCSPK',
    description: 'PC Speaker - internal IBM PC beeper',
    bestFor: ['DOS games', 'Beeper music', 'Lo-fi PC'],
    icon: 'Volume2',
    color: 'text-gray-400',
  },
  FurnacePONG: {
    type: 'FurnacePONG',
    name: 'AY-3-8500',
    shortName: 'PONG',
    description: 'AY-3-8500 - original Pong chip sound',
    bestFor: ['Pong', 'Retro bleeps', 'Primitive'],
    icon: 'Circle',
    color: 'text-white',
  },
  FurnacePV1000: {
    type: 'FurnacePV1000',
    name: 'Casio PV-1000',
    shortName: 'PV1K',
    description: 'Casio PV-1000 - 3 channel PSG',
    bestFor: ['PV-1000', 'Obscure', 'Japanese'],
    icon: 'Tv',
    color: 'text-green-400',
  },
  FurnaceDAVE: {
    type: 'FurnaceDAVE',
    name: 'Enterprise DAVE',
    shortName: 'DAVE',
    description: 'Enterprise DAVE - 3 channel + noise',
    bestFor: ['Enterprise 64/128', 'Hungarian', 'European'],
    icon: 'Monitor',
    color: 'text-red-300',
  },
  FurnaceSU: {
    type: 'FurnaceSU',
    name: 'Sound Unit',
    shortName: 'SU',
    description: 'Commander X16 Sound Unit',
    bestFor: ['X16 music', 'Modern retro', 'Sound Unit'],
    icon: 'Speaker',
    color: 'text-teal-300',
  },
  FurnacePOWERNOISE: {
    type: 'FurnacePOWERNOISE',
    name: 'Power Noise',
    shortName: 'PNOISE',
    description: 'Power Noise - noise generator chip',
    bestFor: ['Noise music', 'Experimental', 'Harsh sounds'],
    icon: 'Zap',
    color: 'text-violet-400',
  },
  FurnaceZXBEEPER: {
    type: 'FurnaceZXBEEPER',
    name: 'ZX Beeper',
    shortName: 'BEEP',
    description: 'ZX Spectrum beeper - 1-bit audio',
    bestFor: ['ZX Spectrum', 'Beeper music', '1-bit audio'],
    icon: 'Speaker',
    color: 'text-cyan-300',
  },
  FurnaceSCVTONE: {
    type: 'FurnaceSCVTONE',
    name: 'SCV Tone',
    shortName: 'SCV',
    description: 'Epoch SCV tone generator',
    bestFor: ['Super Cassette Vision', 'Epoch', 'Japanese'],
    icon: 'Tv',
    color: 'text-stone-300',
  },
  FurnacePCMDAC: {
    type: 'FurnacePCMDAC',
    name: 'PCM DAC',
    shortName: 'DAC',
    description: 'Generic PCM DAC output',
    bestFor: ['PCM output', 'Generic DAC', 'Simple samples'],
    icon: 'AudioLines',
    color: 'text-gray-300',
  },
  ChiptuneModule: {
    type: 'ChiptuneModule',
    name: 'Chiptune Module',
    shortName: 'MOD',
    description: 'Libopenmpt-powered playback for MOD/XM/IT/S3M files',
    bestFor: ['Tracker modules', 'Retro game music', 'Sample-accurate playback'],
    icon: 'Gamepad2',
    color: 'text-lime-400',
  },
  WobbleBass: {
    type: 'WobbleBass',
    name: 'Wobble Bass',
    shortName: 'Wobble',
    description: 'Dubstep/DnB bass with tempo-synced LFO, Reese detuning, FM growl',
    bestFor: ['Dubstep', 'DnB', 'Jungle', 'Neurofunk', 'Riddim'],
    icon: 'Waves',
    color: 'text-fuchsia-500',
  },
  DrumKit: {
    type: 'DrumKit',
    name: 'Drum Kit',
    shortName: 'Kit',
    description: 'Multi-sample instrument with keymap - assign different samples to different notes',
    bestFor: ['Drum kits', 'Instrument layers', 'Velocity splits', 'Sample mapping'],
    icon: 'Piano',
    color: 'text-amber-500',
  },
  Buzzmachine: {
    type: 'Buzzmachine',
    name: 'Buzzmachine',
    shortName: 'Buzz',
    description: 'Jeskola Buzz machines - classic tracker effects and generators from the Buzz ecosystem',
    bestFor: ['Effects', 'Generators', 'Classic tracker sounds', 'Buzz compatibility'],
    icon: 'Cpu',
    color: 'text-yellow-500',
  },
  BuzzDTMF: {
    type: 'BuzzDTMF',
    name: 'CyanPhase DTMF',
    shortName: 'DTMF',
    description: 'Phone dial tone generator - classic DTMF tones',
    bestFor: ['Phone tones', 'Retro effects', 'Experimental'],
    icon: 'Phone',
    color: 'text-cyan-400',
  },
  BuzzFreqBomb: {
    type: 'BuzzFreqBomb',
    name: 'Frequency Bomb',
    shortName: 'FreqBomb',
    description: 'Elenzil Frequency Bomb - chaotic frequency modulation',
    bestFor: ['Noise', 'Chaos', 'Experimental'],
    icon: 'Bomb',
    color: 'text-red-500',
  },
  BuzzKick: {
    type: 'BuzzKick',
    name: 'FSM Kick',
    shortName: 'Kick',
    description: 'FSM Kick drum synthesizer',
    bestFor: ['Kick drums', 'Bass drums', 'Percussion'],
    icon: 'Drum',
    color: 'text-orange-500',
  },
  BuzzKickXP: {
    type: 'BuzzKickXP',
    name: 'FSM KickXP',
    shortName: 'KickXP',
    description: 'Extended FSM Kick with more parameters',
    bestFor: ['Kick drums', 'Deep bass', 'EDM kicks'],
    icon: 'Drum',
    color: 'text-orange-600',
  },
  BuzzNoise: {
    type: 'BuzzNoise',
    name: 'Jeskola Noise',
    shortName: 'Noise',
    description: 'Jeskola Noise generator',
    bestFor: ['Noise', 'Hi-hats', 'Textures'],
    icon: 'Waves',
    color: 'text-gray-400',
  },
  BuzzTrilok: {
    type: 'BuzzTrilok',
    name: 'Jeskola Trilok',
    shortName: 'Trilok',
    description: 'Jeskola Trilok bass drum synthesizer',
    bestFor: ['Bass drums', 'Toms', 'Percussion'],
    icon: 'Drum',
    color: 'text-amber-500',
  },
  Buzz4FM2F: {
    type: 'Buzz4FM2F',
    name: 'MadBrain 4FM2F',
    shortName: '4FM2F',
    description: '4-operator FM synthesizer with 2 filters',
    bestFor: ['FM sounds', 'Complex timbres', 'DX-style'],
    icon: 'Radio',
    color: 'text-purple-500',
  },
  BuzzDynamite6: {
    type: 'BuzzDynamite6',
    name: 'MadBrain Dynamite6',
    shortName: 'Dyn6',
    description: '6-voice additive synthesizer',
    bestFor: ['Additive synthesis', 'Organs', 'Complex sounds'],
    icon: 'Zap',
    color: 'text-yellow-500',
  },
  BuzzM3: {
    type: 'BuzzM3',
    name: 'Makk M3',
    shortName: 'M3',
    description: 'Dual-oscillator mono synth',
    bestFor: ['Bass', 'Leads', 'Classic synth'],
    icon: 'AudioLines',
    color: 'text-green-500',
  },
  Buzz3o3: {
    type: 'Buzz3o3',
    name: 'Oomek Aggressor 3o3',
    shortName: '3o3',
    description: 'TB-303 style acid synth clone',
    bestFor: ['Acid bass', 'Squelchy lines', 'Techno'],
    icon: 'Zap',
    color: 'text-lime-500',
  },
  MAMEVFX: {
    type: 'MAMEVFX',
    name: 'Ensoniq VFX',
    shortName: 'VFX',
    description: 'Ensoniq ES5506 (OTTO) 32-voice wavetable synthesis',
    bestFor: ['Evolving pads', '90s digital', 'Cinematic', 'Layers'],
    icon: 'AudioLines',
    color: 'text-pink-400',
  },
  MAMEDOC: {
    type: 'MAMEDOC',
    name: 'Ensoniq ESQ-1',
    shortName: 'DOC',
    description: 'Ensoniq ES5503 (DOC) 8-bit wavetable synthesis',
    bestFor: ['Lo-fi digital', 'ESQ-1 pads', 'Gritty bass', '80s digital'],
    icon: 'Waves',
    color: 'text-amber-400',
  },
  MAMERSA: {
    type: 'MAMERSA',
    name: 'Roland SA',
    shortName: 'MKS20',
    description: 'Roland Structured Adaptive Synthesis (MKS-20/RD-1000)',
    bestFor: ['Electric piano', 'Authentic piano', '80s keys'],
    icon: 'Piano',
    color: 'text-sky-400',
  },
  MAMESWP30: {
    type: 'MAMESWP30',
    name: 'Yamaha SWP30',
    shortName: 'AWM2',
    description: 'Yamaha SWP30 (AWM2) 64-voice ROMpler/DSP engine',
    bestFor: ['Realistic instruments', '90s ROMpler', 'Advanced effects', 'AWM2 sounds'],
    icon: 'Cpu',
    color: 'text-emerald-400',
  },
  DubSiren: {
    type: 'DubSiren',
    name: 'Dub Siren',
    shortName: 'Siren',
    description: 'Classic dub sound system siren with LFO and delay',
    bestFor: ['Dub FX', 'Reggae', 'Sound system', 'Alerts'],
    icon: 'Megaphone',
    color: 'text-red-500',
  },
  SpaceLaser: {
    type: 'SpaceLaser',
    name: 'Space Laser',
    shortName: 'Laser',
    description: 'FM-based cosmic zap generator for classic reggae and anime effects',
    bestFor: ['Laser shots', 'Anime FX', 'Reggae dubs', 'Sci-fi'],
    icon: 'Zap',
    color: 'text-green-500',
  },
  V2: {
    type: 'V2',
    name: 'Farbrausch V2 Synth',
    shortName: 'V2',
    description: 'Authentic 4k/64k demoscene synthesis with multi-voice subtractive engine.',
    bestFor: ['Demoscene', 'Trance', 'Techno', 'Leads'],
    icon: 'Radio',
    color: 'amber',
  },
  Sam: {
    type: 'Sam',
    name: 'Commodore SAM',
    shortName: 'SAM',
    description: 'Software Automatic Mouth - classic 8-bit speech synthesizer from 1982.',
    bestFor: ['Speech', 'Robotic Voices', 'Lo-Fi', 'FX'],
    icon: 'MessageSquare',
    color: 'amber',
  },
  Synare: {
    type: 'Synare',
    name: 'Synare 3',
    shortName: 'Synare',
    description: 'Classic electronic percussion synthesizer for "disco tom" and dub sounds',
    bestFor: ['Dub percussion', 'Disco toms', 'Electronic drums', 'SFX'],
    icon: 'Drum',
    color: 'text-yellow-500',
  },
};

// Organized categories
export const SYNTH_CATEGORIES: SynthCategory[] = [
  {
    id: 'bass',
    name: 'Bass',
    description: 'Deep and punchy bass synths',
    synths: [SYNTH_INFO.TB303, SYNTH_INFO.MonoSynth, SYNTH_INFO.WobbleBass],
  },
  {
    id: 'lead',
    name: 'Lead',
    description: 'Melodic lead synthesizers',
    synths: [
      SYNTH_INFO.Synth,
      SYNTH_INFO.DuoSynth,
      SYNTH_INFO.FMSynth,
      SYNTH_INFO.AMSynth,
      SYNTH_INFO.PluckSynth,
      SYNTH_INFO.SuperSaw,
      SYNTH_INFO.ChipSynth,
      SYNTH_INFO.PWMSynth,
      SYNTH_INFO.FormantSynth,
      SYNTH_INFO.V2,
    ],
  },
  {
    id: 'drums',
    name: 'Drums',
    description: 'Percussion and drum synthesis',
    synths: [SYNTH_INFO.MembraneSynth, SYNTH_INFO.MetalSynth, SYNTH_INFO.NoiseSynth, SYNTH_INFO.DrumMachine, SYNTH_INFO.DrumKit, SYNTH_INFO.Synare],
  },
  {
    id: 'pads',
    name: 'Pads',
    description: 'Evolving textures and pads',
    synths: [SYNTH_INFO.Wavetable, SYNTH_INFO.GranularSynth, SYNTH_INFO.PolySynth, SYNTH_INFO.StringMachine, SYNTH_INFO.V2],
  },
  {
    id: 'dub',
    name: 'Dub & FX',
    description: 'Classic sound system and special effects',
    synths: [SYNTH_INFO.DubSiren, SYNTH_INFO.SpaceLaser, SYNTH_INFO.V2, SYNTH_INFO.Synare],
  },
  {
    id: 'vintage',
    name: 'Keys',
    description: 'Keyboard instruments',
    synths: [SYNTH_INFO.Organ],
  },
  {
    id: 'samples',
    name: 'Samples',
    description: 'Sample-based instruments',
    synths: [SYNTH_INFO.Sampler, SYNTH_INFO.Player],
  },
  {
    id: 'fx',
    name: 'FX',
    description: 'Sound effects and noise generators',
    synths: [
      SYNTH_INFO.DubSiren,
    ],
  },
  {
    id: 'chiptune-fm',
    name: 'FM Chips',
    description: 'Yamaha FM synthesis chips (OPN, OPL, OPM families)',
    synths: [
      SYNTH_INFO.FurnaceOPN,
      SYNTH_INFO.FurnaceOPN2203,
      SYNTH_INFO.FurnaceOPNA,
      SYNTH_INFO.FurnaceOPNB,
      SYNTH_INFO.FurnaceOPNBB,
      SYNTH_INFO.FurnaceOPM,
      SYNTH_INFO.FurnaceOPL,
      SYNTH_INFO.FurnaceOPLL,
      SYNTH_INFO.FurnaceOPL4,
      SYNTH_INFO.FurnaceOPZ,
      SYNTH_INFO.FurnaceY8950,
      SYNTH_INFO.FurnaceESFM,
      SYNTH_INFO.FurnaceVRC7,
    ],
  },
  {
    id: 'chiptune-console',
    name: 'Console Chips',
    description: 'Game console sound chips (Nintendo, Sega, etc.)',
    synths: [
      SYNTH_INFO.FurnaceNES,
      SYNTH_INFO.FurnaceGB,
      SYNTH_INFO.FurnaceSNES,
      SYNTH_INFO.FurnacePCE,
      SYNTH_INFO.FurnacePSG,
      SYNTH_INFO.FurnaceVB,
      SYNTH_INFO.FurnaceLynx,
      SYNTH_INFO.FurnaceSWAN,
      SYNTH_INFO.FurnaceNDS,
      SYNTH_INFO.FurnaceGBA,
      SYNTH_INFO.FurnacePOKEMINI,
      SYNTH_INFO.FurnaceVRC6,
      SYNTH_INFO.FurnaceN163,
      SYNTH_INFO.FurnaceFDS,
      SYNTH_INFO.FurnaceMMC5,
    ],
  },
  {
    id: 'chiptune-computer',
    name: 'Computer Chips',
    description: 'Home computer sound chips (C64, Spectrum, etc.)',
    synths: [
      SYNTH_INFO.FurnaceC64,
      SYNTH_INFO.FurnaceSID6581,
      SYNTH_INFO.FurnaceSID8580,
      SYNTH_INFO.FurnaceAY,
      SYNTH_INFO.FurnaceAY8930,
      SYNTH_INFO.FurnaceVIC,
      SYNTH_INFO.FurnacePET,
      SYNTH_INFO.FurnaceSAA,
      SYNTH_INFO.FurnaceTED,
      SYNTH_INFO.FurnaceDAVE,
      SYNTH_INFO.FurnaceVERA,
      SYNTH_INFO.FurnaceSCC,
      SYNTH_INFO.FurnaceTIA,
      SYNTH_INFO.FurnacePOKEY,
      SYNTH_INFO.FurnaceZXBEEPER,
      SYNTH_INFO.FurnaceAMIGA,
      SYNTH_INFO.FurnacePCSPKR,
    ],
  },
  {
    id: 'chiptune-arcade',
    name: 'Arcade PCM',
    description: 'Arcade game PCM/ADPCM chips (Sega, Namco, Konami, Capcom)',
    synths: [
      SYNTH_INFO.FurnaceSEGAPCM,
      SYNTH_INFO.FurnaceQSOUND,
      SYNTH_INFO.FurnaceES5506,
      SYNTH_INFO.FurnaceRF5C68,
      SYNTH_INFO.FurnaceC140,
      SYNTH_INFO.FurnaceK007232,
      SYNTH_INFO.FurnaceK053260,
      SYNTH_INFO.FurnaceGA20,
      SYNTH_INFO.FurnaceOKI,
      SYNTH_INFO.FurnaceYMZ280B,
      SYNTH_INFO.FurnaceX1_010,
      SYNTH_INFO.FurnaceBUBBLE,
      SYNTH_INFO.FurnaceMULTIPCM,
      SYNTH_INFO.FurnaceMSM6258,
      SYNTH_INFO.FurnaceMSM5232,
      SYNTH_INFO.FurnaceNAMCO,
    ],
  },
  {
    id: 'chiptune-other',
    name: 'Other Chips',
    description: 'Obscure and miscellaneous sound chips',
    synths: [
      SYNTH_INFO.FurnaceSM8521,
      SYNTH_INFO.FurnaceT6W28,
      SYNTH_INFO.FurnaceSUPERVISION,
      SYNTH_INFO.FurnaceUPD1771,
      SYNTH_INFO.FurnacePONG,
      SYNTH_INFO.FurnacePV1000,
      SYNTH_INFO.FurnaceSU,
      SYNTH_INFO.FurnacePOWERNOISE,
      SYNTH_INFO.FurnaceSCVTONE,
      SYNTH_INFO.FurnacePCMDAC,
      SYNTH_INFO.Furnace, // Generic fallback
    ],
  },
  {
    id: 'buzzmachines',
    name: 'Buzzmachines',
    description: 'Jeskola Buzz machines - classic tracker synths and drums',
    synths: [
      SYNTH_INFO.Buzz3o3,         // TB-303 clone
      SYNTH_INFO.BuzzM3,          // Dual-osc synth
      SYNTH_INFO.Buzz4FM2F,       // 4-op FM
      SYNTH_INFO.BuzzDynamite6,   // 6-op additive
      SYNTH_INFO.BuzzKick,        // Kick drum
      SYNTH_INFO.BuzzKickXP,      // Extended kick
      SYNTH_INFO.BuzzTrilok,      // Bass drum
      SYNTH_INFO.BuzzNoise,       // Noise generator
      SYNTH_INFO.BuzzFreqBomb,    // Frequency sweep
      SYNTH_INFO.BuzzDTMF,        // Phone tones
    ],
  },
  {
    id: 'mame-synths',
    name: '🎹 MAME Classics',
    description: 'Authentic hardware-accurate classic synths',
    synths: [
      SYNTH_INFO.MAMEVFX,
      SYNTH_INFO.MAMEDOC,
      SYNTH_INFO.MAMERSA,
      SYNTH_INFO.MAMESWP30,
    ],
  },
];

// Get all synth types as a flat list (sorted A-Z by short name)
export const ALL_SYNTH_TYPES: SynthType[] = (Object.keys(SYNTH_INFO) as SynthType[]).sort((a, b) =>
  SYNTH_INFO[a].shortName.localeCompare(SYNTH_INFO[b].shortName)
);

// Helper to get category for a synth type (returns primary category)
export function getCategoryForSynth(synthType: SynthType): SynthCategory | undefined {
  return SYNTH_CATEGORIES.find((cat) => cat.synths.some((s) => s.type === synthType));
}

// Helper to get synth info
export function getSynthInfo(synthType: SynthType): SynthInfo {
  return SYNTH_INFO[synthType];
}
