/**
 * Global application version
 * This is the single source of truth for the version number across the app.
 * AUTO-GENERATED BY increment-minor-version.cjs - DO NOT EDIT MANUALLY
 */
export const APP_VERSION = '1.190.0';
