// WallyBeben_wrapper.c — Emscripten C-linkage shim
// Auto-generated by asm68k-to-c. DO NOT EDIT.
// Pattern: mirrors musicline-wasm/common/MusicLineWrapper.cpp

#include "WallyBeben.h"
#include "paula_soft.h"
#include <stdint.h>
#include <string.h>

static int   s_loaded         = 0;
static int   s_finished       = 0;
static float s_tick_accum     = 0.0f;
static float s_ticks_per_sec  = 50.0f;  // CIA 50 Hz PAL
static float s_samples_per_tick = 0.0f;

void player_init(int sample_rate) {
    (void)sample_rate;
    s_ticks_per_sec    = 50.0f;
    s_samples_per_tick = (float)PAULA_RATE_PAL / s_ticks_per_sec;
    
    paula_reset();
    s_loaded   = 0;
    s_finished = 0;
    s_tick_accum = 0.0f;
}

int player_load(const uint8_t* data, int len) {
    if (!data || len <= 0) return 0;
    /* Pass module data via the init function's a0 convention.
     * The generated replayer exposes set_module_data() or takes it via InitPlay.
     * For now, call init with no args — replayer reads data from
     * module pointer set in a0 register file. */
    InitPlay();
    (void)data; (void)len;
    s_loaded   = 1;
    s_finished = 0;
    s_tick_accum = 0.0f;
    return 1;
}

int player_render(float* buffer, int frames) {
    if (!s_loaded) { memset(buffer, 0, frames * 2 * sizeof(float)); return -1; }
    if (s_finished) { memset(buffer, 0, frames * 2 * sizeof(float)); return 0; }
    int written = 0;
    while (written < frames) {
        int chunk = (frames - written) < 64 ? (frames - written) : 64;
        paula_render(buffer + written * 2, chunk);
        written += chunk;
        s_tick_accum += (float)chunk;
        while (s_tick_accum >= s_samples_per_tick) {
            s_tick_accum -= s_samples_per_tick;
            PlayMusic();
        }
    }
    return frames;
}

void player_stop(void) {
    paula_reset();
    s_loaded   = 0;
    s_finished = 1;
}

int player_is_finished(void) { return s_finished ? 1 : 0; }
int player_get_subsong_count(void) { return 1; }
void player_set_subsong(int n) { (void)n; }
const char* player_get_title(void) { return "WallyBeben"; }
double player_detect_duration(void) { return 0.0; }
