/**
 * PixiNonEditableDialog — GL-native read-only pattern warning dialog.
 * Pixel-perfect match to DOM: src/components/dialogs/NonEditableDialog.tsx
 *
 * DOM structure:
 *   backdrop bg-black/60 → PixiModal overlayAlpha=0.6
 *   container bg-dark-bgSecondary border-dark-border rounded-lg w-[420px]
 *   header: px-5 py-4 border-b → PixiModalHeader
 *   body: px-5 py-4 space-y-3 → padding 20/16, gap 12
 *   footer: px-5 py-3 border-t → PixiModalFooter
 */

import React, { useCallback } from 'react';
import { PixiModal, PixiModalHeader, PixiModalFooter, PixiButton, PixiLabel } from '../components';
import { usePixiTheme } from '../theme';
import { PIXI_FONTS } from '../fonts';
import { useUIStore } from '@stores/useUIStore';

const MODAL_W = 420;
const MODAL_H = 300;

export const PixiNonEditableDialog: React.FC = () => {
  const theme = usePixiTheme();
  const isOpen = useUIStore((s) => s.nonEditableDialogOpen);
  const close = useUIStore((s) => s.closeNonEditableDialog);

  const handleClose = useCallback(() => {
    close();
  }, [close]);

  if (!isOpen) return null;

  return (
    <PixiModal isOpen={true} onClose={handleClose} width={MODAL_W} height={MODAL_H} overlayAlpha={0.6}>
      {/* Header — Lock icon + title */}
      <layoutContainer
        layout={{
          flexDirection: 'row',
          alignItems: 'center',
          gap: 12,
          paddingLeft: 20,
          paddingRight: 20,
          paddingTop: 16,
          paddingBottom: 16,
          backgroundColor: theme.bgSecondary.color,
          borderBottomWidth: 1,
          borderColor: theme.border.color,
        }}
      >
        <pixiBitmapText
          text="🔒"
          style={{ fontFamily: PIXI_FONTS.SANS, fontSize: 14, fill: 0xffffff }}
          tint={theme.accent.color}
          layout={{}}
        />
        <pixiBitmapText
          text="Pattern is Read-Only"
          style={{ fontFamily: PIXI_FONTS.SANS_SEMIBOLD, fontSize: 14, fill: 0xffffff }}
          tint={theme.text.color}
          layout={{}}
        />
      </layoutContainer>

      {/* Body — px-5 py-4 space-y-3 → padding 20/16, gap 12 */}
      <layoutContainer
        layout={{
          flex: 1,
          flexDirection: 'column',
          paddingLeft: 20,
          paddingRight: 20,
          paddingTop: 16,
          paddingBottom: 16,
          gap: 12,
        }}
      >
        <PixiLabel
          text={'This song was imported in UADE playback mode because the enhanced scan could not extract editable audio data from it.'}
          size="sm"
          color="text"
          layout={{ maxWidth: MODAL_W - 42 }}
        />

        <PixiLabel
          text="This usually happens with synthesis-based formats where samples are generated by the 68k CPU at runtime rather than stored as PCM in the file."
          size="sm"
          color="textMuted"
          layout={{ maxWidth: MODAL_W - 42 }}
        />

        {/* Tip box — p-3 bg-dark-bg border-dark-border rounded */}
        <layoutContainer
          layout={{
            flexDirection: 'row',
            gap: 8,
            padding: 12,
            borderRadius: 6,
            backgroundColor: theme.bg.color,
            borderWidth: 1,
            borderColor: theme.border.color,
            alignItems: 'flex-start',
          }}
        >
          <pixiBitmapText
            text="↻"
            style={{ fontFamily: PIXI_FONTS.SANS, fontSize: 10, fill: 0xffffff }}
            tint={theme.accent.color}
            layout={{ marginTop: 2 }}
          />
          <PixiLabel
            text="To edit this song, re-import the file. If the format has a native parser, it will load with full instrument and pattern editing support."
            size="xs"
            color="textMuted"
            layout={{ maxWidth: MODAL_W - 74 }}
          />
        </layoutContainer>
      </layoutContainer>

      {/* Footer — px-5 py-3 → standard footer, right-aligned */}
      <PixiModalFooter>
        <PixiButton label="OK" variant="primary" size="sm" onClick={handleClose} />
      </PixiModalFooter>
    </PixiModal>
  );
};
