/* ====================================================================
 * Auto-generated by asm68k-to-c transpiler
 * Source: hip.asm
 *
 * This file was mechanically translated from Motorola 68000 assembly.
 * Original ASM instructions appear as inline comments.
 * ==================================================================== */

#include "paula_soft.h"
#include <stdint.h>

/* -- 68k Register File ------------------------------------------------
 * Data registers D0-D7:  general-purpose 32-bit registers.
 * Address registers A0-A6: pointer registers (32-bit).
 * SP (A7): stack pointer.  PC: program counter (unused in transpiled code).
 * Flags: Z (zero), N (negative), C (carry), V (overflow), X (extend).
 * -------------------------------------------------------------------- */
static uint32_t d0,d1,d2,d3,d4,d5,d6,d7;
static uint32_t a0,a1,a2,a3,a4,a5,a6,sp,pc;
static int flag_z=0, flag_n=0, flag_c=0, flag_v=0, flag_x=0;

/* -- Sub-register Accessors -------------------------------------------
 * W(d0) -- access the low 16 bits of d0 (read/write).
 * B(d0) -- access the low 8 bits of d0 (read/write).
 * Example: W(d0) = 0x1234;  // sets d0.w, leaves upper 16 bits unchanged
 * -------------------------------------------------------------------- */
#define W(r)  (*((uint16_t*)&(r)))
#define B(r)  (*((uint8_t*)&(r)))

/* -- Memory Access (Big-Endian) ---------------------------------------
 * The 68k is big-endian; these macros byte-swap on little-endian hosts.
 * Uses memcpy for alignment-safe access (68k allows unaligned word/long).
 *
 * READ8(addr)       -- read  byte from address
 * READ16(addr)      -- read  big-endian word from address
 * READ32(addr)      -- read  big-endian longword from address
 * WRITE8(addr,v)    -- write byte to address
 * WRITE16(addr,v)   -- write big-endian word to address
 * WRITE32(addr,v)   -- write big-endian longword to address
 * READ16_POST(reg)  -- read word, then reg += 2  (simulates (An)+ mode)
 * WRITE16_PRE(reg,v)-- reg -= 2, then write word (simulates -(An) mode)
 * -------------------------------------------------------------------- */
#include <string.h>
#define READ8(addr)   (*((const uint8_t*)(uintptr_t)(addr)))
#define WRITE8(addr,v)  (*((uint8_t*)(uintptr_t)(addr)) = (uint8_t)(v))
static inline uint16_t _rd16(uintptr_t a) { uint16_t v; memcpy(&v,(void*)a,2); return v; }
static inline uint32_t _rd32(uintptr_t a) { uint32_t v; memcpy(&v,(void*)a,4); return v; }
static inline void _wr16(uintptr_t a,uint16_t v) { memcpy((void*)a,&v,2); }
static inline void _wr32(uintptr_t a,uint32_t v) { memcpy((void*)a,&v,4); }
#if defined(__BYTE_ORDER__) && __BYTE_ORDER__ == __ORDER_BIG_ENDIAN__
#define READ16(addr)  _rd16((uintptr_t)(addr))
#define READ32(addr)  _rd32((uintptr_t)(addr))
#define WRITE16(addr,v) _wr16((uintptr_t)(addr),(uint16_t)(v))
#define WRITE32(addr,v) _wr32((uintptr_t)(addr),(uint32_t)(v))
#else
#define READ16(addr)  __builtin_bswap16(_rd16((uintptr_t)(addr)))
#define READ32(addr)  __builtin_bswap32(_rd32((uintptr_t)(addr)))
#define WRITE16(addr,v) _wr16((uintptr_t)(addr),__builtin_bswap16((uint16_t)(v)))
#define WRITE32(addr,v) _wr32((uintptr_t)(addr),__builtin_bswap32((uint32_t)(v)))
#endif
#define READ8_POST(r)   ({ uint32_t _r=(r); (r)+=1; READ8(_r); })
#define READ16_POST(r)  ({ uint32_t _r=(r); (r)+=2; READ16(_r); })
#define READ32_POST(r)  ({ uint32_t _r=(r); (r)+=4; READ32(_r); })
#define READ8_PRE(r)    ({ (r)-=1; READ8(r); })
#define READ16_PRE(r)   ({ (r)-=2; READ16(r); })
#define READ32_PRE(r)   ({ (r)-=4; READ32(r); })
#define WRITE8_POST(r,v)  ({ WRITE8(r,v);  (r)+=1; })
#define WRITE16_POST(r,v) ({ WRITE16(r,v); (r)+=2; })
#define WRITE32_POST(r,v) ({ WRITE32(r,v); (r)+=4; })
#define WRITE8_PRE(r,v)   ({ (r)-=1; WRITE8(r,v); })
#define WRITE16_PRE(r,v)  ({ (r)-=2; WRITE16(r,v); })
#define WRITE32_PRE(r,v)  ({ (r)-=4; WRITE32(r,v); })

/* -- Rotation Helpers -------------------------------------------------
 * ROL32(v,n) -- rotate 32-bit value left by n bits
 * ROR32(v,n) -- rotate 32-bit value right by n bits
 * -------------------------------------------------------------------- */
#define ROL32(v,n)  (((v)<<(n))|((v)>>(32-(n))))
#define ROR32(v,n)  (((v)>>(n))|((v)<<(32-(n))))

/* -- Unresolved Symbols -------------------------------------------- */
/* These symbols come from include files not available to the transpiler.
 * They are stubbed as 0 so the generated C compiles. */
/* _other* */
#ifndef asm
/* #define asm 0 */
#endif
#ifndef DELIRIUM
/* #define DELIRIUM 0 */
#endif
#ifndef songend
/* #define songend 0 */
#endif
#ifndef support
/* #define support 0 */
#endif
#ifndef Hippel
/* #define Hippel 0 */
#endif
#ifndef add
/* #define add 0 */
#endif
#ifndef init
/* #define init 0 */
#endif
#ifndef bsr
/* #define bsr 0 */
#endif
#ifndef offset
/* #define offset 0 */
#endif
#ifndef lea
/* #define lea 0 */
#endif
#ifndef xyz
/* #define xyz 0 */
#endif
#ifndef clear
/* #define clear 0 */
#endif
#ifndef flag
/* #define flag 0 */
#endif
#ifndef that
/* #define that 0 */
#endif
#ifndef prevents
/* #define prevents 0 */
#endif
#ifndef playing
/* #define playing 0 */
#endif
#ifndef check
/* #define check 0 */
#endif
#ifndef for
/* #define for 0 */
#endif
#ifndef push
/* #define push 0 */
#endif
#ifndef all
/* #define all 0 */
#endif
#ifndef BSR
/* #define BSR 0 */
#endif
#ifndef it
/* #define it 0 */
#endif
#ifndef go
/* #define go 0 */
#endif
#ifndef to
/* #define to 0 */  /* Removed: conflicts with emscripten.h */
#endif
#ifndef func
/* #define func 0 */  /* Removed: conflicts with emscripten.h */
#endif
#ifndef COSO
/* #define COSO 0 */
#endif
#ifndef counter
/* #define counter 0 */
#endif
#ifndef TFMX
/* #define TFMX 0 */
#endif
#ifndef max
/* #define max 0 */  /* Removed: conflicts with system headers */
#endif
#ifndef subsong
/* #define subsong 0 */
#endif
#ifndef subsongs
/* #define subsongs 0 */
#endif
#ifndef sub
/* #define sub 0 */
#endif
#ifndef tab
/* #define tab 0 */
#endif
#ifndef InitFuncPtr
/* #define InitFuncPtr 0 */
#endif
#ifndef replaced
/* #define replaced 0 */
#endif
#ifndef code
/* #define code 0 */
#endif
#ifndef line
/* #define line 0 */
#endif
#ifndef aud0vol
/* #define aud0vol 0 */
#endif
#ifndef aud1vol
/* #define aud1vol 0 */
#endif
#ifndef aud2vol
/* #define aud2vol 0 */
#endif
#ifndef aud3vol
/* #define aud3vol 0 */
#endif
#ifndef dmacon
/* #define dmacon 0 */
#endif
/* DTP_* */
#ifndef DTP_PlayerName
/* #define DTP_PlayerName 0 */
#endif
#ifndef DTP_Creator
/* #define DTP_Creator 0 */
#endif
#ifndef DTP_Check2
/* #define DTP_Check2 0 */
#endif
#ifndef DTP_SubSongRange
/* #define DTP_SubSongRange 0 */
#endif
#ifndef DTP_InitPlayer
/* #define DTP_InitPlayer 0 */
#endif
#ifndef DTP_InitSound
/* #define DTP_InitSound 0 */
#endif
#ifndef DTP_Interrupt
/* #define DTP_Interrupt 0 */
#endif
#ifndef DTP_EndSound
/* #define DTP_EndSound 0 */
#endif
#ifndef DTP_EndPlayer
/* #define DTP_EndPlayer 0 */
#endif
/* dtg_* */
#ifndef dtg_ChkData
/* #define dtg_ChkData 0 */
#endif
#ifndef dtg_ChkSize
/* #define dtg_ChkSize 0 */
#endif
#ifndef dtg_SongEnd
/* #define dtg_SongEnd 0 */
#endif
#ifndef dtg_GetListData
/* #define dtg_GetListData 0 */
#endif
#ifndef dtg_AudioAlloc
/* #define dtg_AudioAlloc 0 */
#endif
#ifndef dtg_SndNum
/* #define dtg_SndNum 0 */
#endif
#ifndef dtg_AudioFree
/* #define dtg_AudioFree 0 */
#endif

/* Stub definitions for UADE framework symbols */
static uint32_t dtg_ChkData = 0;
static uint32_t dtg_ChkSize = 0;
static uint32_t dtg_SongEnd = 0;
static uint32_t dtg_GetListData = 0;
static uint32_t dtg_AudioAlloc = 0;
static uint32_t dtg_SndNum = 0;
static uint32_t dtg_AudioFree = 0;
static uint32_t InitFuncPtr = 0;

/* Amiga Paula chip register offsets (stub values for macro expansion) */
static uint32_t aud0vol = 0xa6;
static uint32_t aud1vol = 0xb6;
static uint32_t aud2vol = 0xc6;
static uint32_t aud3vol = 0xd6;
static uint32_t dmacon = 0x96;

/* -- Packed Data Section -------------------------------------------- */
/* All data labels packed into a single contiguous byte array matching
 * 68k memory layout. Accessor macros provide typed pointer access. */
static uint8_t _ds[284] = {
  0x00,0x00,0x00,0x00,0x00,0x00,0x24,0x56,0x45,0x52,0x3a,0x20,0x4a,0x6f,0x63,0x68,
  0x65,0x6e,0x20,0x48,0x69,0x70,0x70,0x65,0x6c,0x20,0x70,0x6c,0x61,0x79,0x65,0x72,
  0x20,0x6d,0x6f,0x64,0x75,0x6c,0x65,0x20,0x56,0x30,0x2e,0x31,0x20,0x66,0x6f,0x72,
  0x20,0x55,0x41,0x44,0x45,0x20,0x28,0x32,0x32,0x2e,0x31,0x32,0x2e,0x32,0x30,0x30,
  0x31,0x29,0x00,0x24,0x43,0x4f,0x50,0x59,0x52,0x49,0x47,0x48,0x54,0x3a,0x20,0x48,
  0x65,0x69,0x6b,0x6b,0x69,0x20,0x4f,0x72,0x73,0x69,0x6c,0x61,0x20,0x3c,0x68,0x65,
  0x69,0x6b,0x6b,0x69,0x2e,0x6f,0x72,0x73,0x69,0x6c,0x61,0x40,0x74,0x75,0x74,0x2e,
  0x66,0x69,0x3e,0x00,0x24,0x4c,0x49,0x43,0x45,0x4e,0x53,0x45,0x3a,0x20,0x47,0x4e,
  0x55,0x20,0x4c,0x47,0x50,0x4c,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00, /* table@136 */
  0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,
  0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,
  0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,
  0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,
  0x80,0x00,0x44,0x74,0x00,0x00,0x00,0x02,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,
  0x00,0x00,0x00,0x00,0x00,0x00,0x4a,0x6f,0x63,0x68,0x65,0x6e,0x20,0x48,0x69,0x70, /* playername@228, creator@230 */
  0x70,0x65,0x6c,0x20,0x70,0x6c,0x61,0x79,0x65,0x72,0x20,0x66,0x6f,0x72,0x20,0x55,
  0x41,0x44,0x45,0x20,0x62,0x79,0x20,0x73,0x68,0x64,0x00,0x00,0x00,0x00,0x00,0x00, /* delibase@268 */
  0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00, /* initfuncptr@272, intfuncptr@276, maxsubsong@280 */
};
#define table ((uint32_t*)(_ds + 136))
#define playername ((uint8_t*)(_ds + 228))
#define creator ((uint8_t*)(_ds + 230))
#define delibase ((uint32_t*)(_ds + 268))
#define initfuncptr ((uint32_t*)(_ds + 272))
#define intfuncptr ((uint32_t*)(_ds + 276))
#define maxsubsong ((uint32_t*)(_ds + 280))

/* -- Forward Declarations -------------------------------------------- */
static void checktype1(void);
static void checktype2(void);
static void checktype3(void);
static void checksubs(void);
static void patchmod(void);
static void gotoinitbsrfunc(void);
static void songendfunc(void);
static void jsrcom(void);
static void Check2(void);
static void SubSongRange(void);
static void InitPlayer(void);
static void InitSound(void);
static void Interrupt(void);
static void EndSound(void);
static void EndPlayer(void);


/* ====================================================================
 * Code Section -- Transpiled Functions
 * ==================================================================== */
/* T */

static void SubSongRange(void) {
    d0 = (uint32_t)(int32_t)(int8_t)(1);  /* MOVEQ	#1,D0 */
    {  /* MOVE.L	maxsubsong,D1 */
        uint32_t _mv = (uint32_t)(READ32((uintptr_t)maxsubsong));
        d1 = _mv;
        flag_z = ((int32_t)(_mv) == 0);
        flag_n = ((int32_t)(_mv) < 0);
        flag_v = 0; flag_c = 0;
      }
    return;  /* RTS */
    return;  /* RTS */
}
static void InitPlayer(void) {
    /* UNIMPLEMENTED: PUSH */  /* PUSH	all */
    d0 = (uint32_t)(int32_t)(int8_t)(0);  /* MOVEQ	#0,D0 */
    {  /* MOVE.L	dtg_GetListData(A5),A0 */
        uint32_t _mv = (uint32_t)(READ32(a5 + (intptr_t)dtg_GetListData));
        a0 = _mv;
        flag_z = ((int32_t)(_mv) == 0);
        flag_n = ((int32_t)(_mv) < 0);
        flag_v = 0; flag_c = 0;
      }
    { uintptr_t _jt=(uintptr_t)(a0); if(_jt) ((void(*)(void))_jt)(); }  /* JSR	(A0) */
    {  /* MOVE.L	dtg_AudioAlloc(A5),A0 */
        uint32_t _mv = (uint32_t)(READ32(a5 + (intptr_t)dtg_AudioAlloc));
        a0 = _mv;
        flag_z = ((int32_t)(_mv) == 0);
        flag_n = ((int32_t)(_mv) < 0);
        flag_v = 0; flag_c = 0;
      }
    { uintptr_t _jt=(uintptr_t)(a0); if(_jt) ((void(*)(void))_jt)(); }  /* JSR	(A0) */
    /* UNIMPLEMENTED: PULL */  /* PULL	all */
    d0 = (uint32_t)(int32_t)(int8_t)(0);  /* MOVEQ	#0,D0 */
    return;  /* RTS */
    return;  /* RTS */
}
static void InitSound(void) {
    /* UNIMPLEMENTED: PUSH */  /* PUSH	all */
    d0 = (uint32_t)(int32_t)(int8_t)(0);  /* MOVEQ	#0,D0 */
    {  /* MOVE	dtg_SndNum(A5),D0 */
        uint32_t _mv = (uint32_t)(READ32(a5 + (intptr_t)dtg_SndNum));
        d0 = _mv;
        flag_z = ((int32_t)(_mv) == 0);
        flag_n = ((int32_t)(_mv) < 0);
        flag_v = 0; flag_c = 0;
      }
    {  /* MOVE.L	initfuncptr,A0 */
        uint32_t _mv = (uint32_t)(READ32((uintptr_t)initfuncptr));
        a0 = _mv;
        flag_z = ((int32_t)(_mv) == 0);
        flag_n = ((int32_t)(_mv) < 0);
        flag_v = 0; flag_c = 0;
      }
    { uintptr_t _jt=(uintptr_t)(a0); if(_jt) ((void(*)(void))_jt)(); }  /* JSR	(A0) */
    /* UNIMPLEMENTED: PULL */  /* PULL	all */
    return;  /* RTS */
    return;  /* RTS */
}
static void Interrupt(void) {
    /* UNIMPLEMENTED: PUSH */  /* PUSH	all */
    {  /* MOVE.L	intfuncptr,A0 */
        uint32_t _mv = (uint32_t)(READ32((uintptr_t)intfuncptr));
        a0 = _mv;
        flag_z = ((int32_t)(_mv) == 0);
        flag_n = ((int32_t)(_mv) < 0);
        flag_v = 0; flag_c = 0;
      }
    { uintptr_t _jt=(uintptr_t)(a0); if(_jt) ((void(*)(void))_jt)(); }  /* JSR	(A0) */
    /* UNIMPLEMENTED: PULL */  /* PULL	all */
    return;  /* RTS */
    return;  /* RTS */
}
static void EndSound(void) {
    /* UNIMPLEMENTED: PUSH */  /* PUSH	all */
    a2 = (uint32_t)0xdff000;  /* LEA	$DFF000,A2 */
    d0 = (uint32_t)(int32_t)(int8_t)(0);  /* MOVEQ	#0,D0 */
    {  /* MOVE	D0,aud0vol(A2) */
        uint32_t _mv = (uint32_t)(d0);
        WRITE32(a2 + (intptr_t)aud0vol, _mv);
        flag_z = ((int32_t)(_mv) == 0);
        flag_n = ((int32_t)(_mv) < 0);
        flag_v = 0; flag_c = 0;
      }
    {  /* MOVE	D0,aud1vol(A2) */
        uint32_t _mv = (uint32_t)(d0);
        WRITE32(a2 + (intptr_t)aud1vol, _mv);
        flag_z = ((int32_t)(_mv) == 0);
        flag_n = ((int32_t)(_mv) < 0);
        flag_v = 0; flag_c = 0;
      }
    {  /* MOVE	D0,aud2vol(A2) */
        uint32_t _mv = (uint32_t)(d0);
        WRITE32(a2 + (intptr_t)aud2vol, _mv);
        flag_z = ((int32_t)(_mv) == 0);
        flag_n = ((int32_t)(_mv) < 0);
        flag_v = 0; flag_c = 0;
      }
    {  /* MOVE	D0,aud3vol(A2) */
        uint32_t _mv = (uint32_t)(d0);
        WRITE32(a2 + (intptr_t)aud3vol, _mv);
        flag_z = ((int32_t)(_mv) == 0);
        flag_n = ((int32_t)(_mv) < 0);
        flag_v = 0; flag_c = 0;
      }
    {  /* MOVE	#$000f,dmacon(A2) */
        uint32_t _mv = (uint32_t)(0x000f);
        WRITE32(a2 + (intptr_t)dmacon, _mv);
        flag_z = ((int32_t)(_mv) == 0);
        flag_n = ((int32_t)(_mv) < 0);
        flag_v = 0; flag_c = 0;
      }
    /* UNIMPLEMENTED: PULL */  /* PULL	all */
    return;  /* RTS */
    return;  /* RTS */
}
static void EndPlayer(void) {
    {  /* MOVE.L	dtg_AudioFree(A5),A0 */
        uint32_t _mv = (uint32_t)(READ32(a5 + (intptr_t)dtg_AudioFree));
        a0 = _mv;
        flag_z = ((int32_t)(_mv) == 0);
        flag_n = ((int32_t)(_mv) < 0);
        flag_v = 0; flag_c = 0;
      }
    { uintptr_t _jt=(uintptr_t)(a0); if(_jt) ((void(*)(void))_jt)(); }  /* JSR	(A0) */
    return;  /* RTS */
    return;  /* RTS */
}
static void _anon0(void) {
  /* UNIMPLEMENTED: INCDIR */  /* INCDIR	asm */
}


/* -- SECTION hippelplayer ------------------------------------------ */

static void _anon1(void) {
  d0 = (uint32_t)(int32_t)(int8_t)(-1);  /* MOVEQ	#-1,D0 */
  return;  /* RTS */
}


/* --- Check2 --- */
static void Check2(void) {
  {  /* MOVE.L	A5,delibase */
      uint32_t _mv = (uint32_t)(a5);
      WRITE32((uintptr_t)delibase, _mv);
      flag_z = ((int32_t)(_mv) == 0);
      flag_n = ((int32_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  {  /* MOVE.L	dtg_ChkData(A5),A0 */
      uint32_t _mv = (uint32_t)(READ32(a5 + (intptr_t)dtg_ChkData));
      a0 = _mv;
      flag_z = ((int32_t)(_mv) == 0);
      flag_n = ((int32_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  /* check file format */
  checktype1();  /* BSR	checktype1 */
  {  /* TST.L	D0 */
      uint32_t _tst = (uint32_t)(d0);
      flag_z = (_tst == 0);
      flag_n = ((int32_t)(_tst) < 0);
      flag_c = 0; flag_v = 0;
    }
  if (flag_z) goto checksub1;  /* equal / zero */  /* BEQ.B	checksub1 */
  checktype2();  /* BSR	checktype2 */
  {  /* TST.L	D0 */
      uint32_t _tst = (uint32_t)(d0);
      flag_z = (_tst == 0);
      flag_n = ((int32_t)(_tst) < 0);
      flag_c = 0; flag_v = 0;
    }
  if (flag_z) goto checksub2;  /* equal / zero */  /* BEQ.B	checksub2 */
  checktype3();  /* BSR	checktype3 */
  {  /* TST.L	D0 */
      uint32_t _tst = (uint32_t)(d0);
      flag_z = (_tst == 0);
      flag_n = ((int32_t)(_tst) < 0);
      flag_c = 0; flag_v = 0;
    }
  if (flag_z) goto checksub3;  /* equal / zero */  /* BEQ.B	checksub3 */
  return;  /* RTS */
checksub1:
checksub2:
checksub3:
  checksubs();  /* BSR	checksubs */
  patchmod();  /* BSR	patchmod */
  {  /* TST.L	D0 */
      uint32_t _tst = (uint32_t)(d0);
      flag_z = (_tst == 0);
      flag_n = ((int32_t)(_tst) < 0);
      flag_c = 0; flag_v = 0;
    }
  return;  /* RTS */
}


/* --- checktype1 --- */
static void checktype1(void) {
  d0 = (uint32_t)(int32_t)(int8_t)(-1);  /* MOVEQ	#-1,D0 */
  {  /* MOVE.L	A0,A1 */
      uint32_t _mv = (uint32_t)(a0);
      a1 = _mv;
      flag_z = ((int32_t)(_mv) == 0);
      flag_n = ((int32_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  gotoinitbsrfunc();  /* BSR	gotoinitbsrfunc */
  {  /* TST.L	D1 */
      uint32_t _tst = (uint32_t)(d1);
      flag_z = (_tst == 0);
      flag_n = ((int32_t)(_tst) < 0);
      flag_c = 0; flag_v = 0;
    }
  if (!flag_z) goto nottype1;  /* not equal / nonzero */  /* BNE.B	nottype1 */
  {  /* MOVE.L	A2,intfuncptr */
      uint32_t _mv = (uint32_t)(a2);
      WRITE32((uintptr_t)intfuncptr, _mv);
      flag_z = ((int32_t)(_mv) == 0);
      flag_n = ((int32_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  {  /* CMP.L	#$48e7fffe,(A1) */
      int32_t _lhs = (int32_t)(READ32(a1));
      int32_t _rhs = (int32_t)(0x48e7fffe);
      int32_t _cmp = _lhs - _rhs;
      flag_z = (_cmp == 0);
      flag_n = (_cmp < 0);
      flag_c = ((uint32_t)_lhs < (uint32_t)_rhs);
    }
  if (!flag_z) goto nottype1;  /* not equal / nonzero */  /* BNE.B	nottype1 */
  {  /* CMP.B	#$61,4(A1) */
      int32_t _lhs = (int32_t)(READ8(a1 + 4));
      int32_t _rhs = (int32_t)(0x61);
      int32_t _cmp = _lhs - _rhs;
      flag_z = (_cmp == 0);
      flag_n = (_cmp < 0);
      flag_c = ((uint32_t)_lhs < (uint32_t)_rhs);
    }
  if (!flag_z) goto nottype1;  /* not equal / nonzero */  /* BNE.B	nottype1 */
  d1 = (uint32_t)(int32_t)(int8_t)(0);  /* MOVEQ	#0,D1 */
  {  /* MOVE.B	5(A1),D1 */
      uint8_t _mv = (uint8_t)(READ8(a1 + 5));
      B(d1) = (uint8_t)_mv;
      flag_z = ((int8_t)(_mv) == 0);
      flag_n = ((int8_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  if (!flag_z) goto ibe1;  /* not equal / nonzero */  /* BNE.B	ibe1 */
  a1 = (uint32_t)((int32_t)a1 + (int32_t)(int16_t)(READ32(a1 + 6)));  /* ADD	6(A1),A1,add,init,bsr,offset */
  goto ibehandled;  /* BRA.B	ibehandled */
ibe1:
  a1 = (uint32_t)((int32_t)a1 + (int32_t)(int16_t)(d1));  /* ADD	D1,A1 */
ibehandled:
  a1 = (uint32_t)((int32_t)a1 + (int32_t)(int16_t)(6));  /* ADDQ.L	#6,A1 */
  {  /* MOVE.L	A1,initfuncptr */
      uint32_t _mv = (uint32_t)(a1);
      WRITE32((uintptr_t)initfuncptr, _mv);
      flag_z = ((int32_t)(_mv) == 0);
      flag_n = ((int32_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  {  /* CMP	#$2f00,(A1) */
      int32_t _lhs = (int32_t)(READ32(a1));
      int32_t _rhs = (int32_t)(0x2f00);
      int32_t _cmp = _lhs - _rhs;
      flag_z = (_cmp == 0);
      flag_n = (_cmp < 0);
      flag_c = ((uint32_t)_lhs < (uint32_t)_rhs);
    }
  if (!flag_z) goto nottype1;  /* not equal / nonzero */  /* BNE.B	nottype1 */
  {  /* CMP	#$201f,6(A1) */
      int32_t _lhs = (int32_t)(READ32(a1 + 6));
      int32_t _rhs = (int32_t)(0x201f);
      int32_t _cmp = _lhs - _rhs;
      flag_z = (_cmp == 0);
      flag_n = (_cmp < 0);
      flag_c = ((uint32_t)_lhs < (uint32_t)_rhs);
    }
  if (!flag_z) goto type1bb;  /* not equal / nonzero */  /* BNE.B	type1bb */
  a1 = (uint32_t)((int32_t)a1 + (int32_t)(int16_t)(4));  /* ADDQ.L	#4,A1 */
  a1 = (uint32_t)((int32_t)a1 + (int32_t)(int16_t)(READ32(a1)));  /* ADD	(A1),A1 */
  goto type1wb;  /* BRA.B	type1wb */
type1bb:
  d1 = (uint32_t)(int32_t)(int8_t)(0);  /* MOVEQ	#0,D1 */
  {  /* MOVE.B	3(A1),D1 */
      uint8_t _mv = (uint8_t)(READ8(a1 + 3));
      B(d1) = (uint8_t)_mv;
      flag_z = ((int8_t)(_mv) == 0);
      flag_n = ((int8_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  a1 = (uint32_t)((int32_t)a1 + (int32_t)(int16_t)(4));  /* ADDQ.L	#4,A1 */
  a1 = (uint32_t)((int32_t)a1 + (int32_t)(int16_t)(d1));  /* ADD.L	D1,A1 */
type1wb:
  {  /* CMP	#$41fa,(A1),lea,xyz(PC),A0 */
      int32_t _lhs = (int32_t)(READ32(a1));
      int32_t _rhs = (int32_t)(0x41fa);
      int32_t _cmp = _lhs - _rhs;
      flag_z = (_cmp == 0);
      flag_n = (_cmp < 0);
      flag_c = ((uint32_t)_lhs < (uint32_t)_rhs);
    }
  if (!flag_z) goto nottype1;  /* not equal / nonzero */  /* BNE.B	nottype1 */
  {  /* CMP	#$6600,6(A1) */
      int32_t _lhs = (int32_t)(READ32(a1 + 6));
      int32_t _rhs = (int32_t)(0x6600);
      int32_t _cmp = _lhs - _rhs;
      flag_z = (_cmp == 0);
      flag_n = (_cmp < 0);
      flag_c = ((uint32_t)_lhs < (uint32_t)_rhs);
    }
  if (!flag_z) goto notfmx;  /* not equal / nonzero */  /* BNE.B	notfmx */
  a1 = (uint32_t)((int32_t)a1 + (int32_t)(int16_t)(2));  /* ADDQ	#2,A1 */
  a1 = (uint32_t)((int32_t)a1 + (int32_t)(int16_t)(READ32(a1)));  /* ADD	(A1),A1 */
  WRITE32(a1, 0);  /* CLR	(A1),clear,flag,that,prevents,playing */
notfmx:
  d0 = (uint32_t)(int32_t)(int8_t)(0);  /* MOVEQ	#0,D0 */
nottype1:
  return;  /* RTS */
}


/* --- checktype2 --- */
static void checktype2(void) {
  d0 = (uint32_t)(int32_t)(int8_t)(-1);  /* MOVEQ	#-1,D0 */
  {  /* MOVE.L	A0,A1 */
      uint32_t _mv = (uint32_t)(a0);
      a1 = _mv;
      flag_z = ((int32_t)(_mv) == 0);
      flag_n = ((int32_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  gotoinitbsrfunc();  /* BSR	gotoinitbsrfunc */
  {  /* TST.L	D1 */
      uint32_t _tst = (uint32_t)(d1);
      flag_z = (_tst == 0);
      flag_n = ((int32_t)(_tst) < 0);
      flag_c = 0; flag_v = 0;
    }
  if (!flag_z) goto nottype2;  /* not equal / nonzero */  /* BNE.B	nottype2 */
  {  /* MOVE.L	A2,intfuncptr */
      uint32_t _mv = (uint32_t)(a2);
      WRITE32((uintptr_t)intfuncptr, _mv);
      flag_z = ((int32_t)(_mv) == 0);
      flag_n = ((int32_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  {  /* CMP.L	#$48e7fffe,(A1),check,for,push,all */
      int32_t _lhs = (int32_t)(READ32(a1));
      int32_t _rhs = (int32_t)(0x48e7fffe);
      int32_t _cmp = _lhs - _rhs;
      flag_z = (_cmp == 0);
      flag_n = (_cmp < 0);
      flag_c = ((uint32_t)_lhs < (uint32_t)_rhs);
    }
  if (!flag_z) goto nottype2;  /* not equal / nonzero */  /* BNE.B	nottype2 */
  {  /* CMP.B	#$61,4(A1) */
      int32_t _lhs = (int32_t)(READ8(a1 + 4));
      int32_t _rhs = (int32_t)(0x61);
      int32_t _cmp = _lhs - _rhs;
      flag_z = (_cmp == 0);
      flag_n = (_cmp < 0);
      flag_c = ((uint32_t)_lhs < (uint32_t)_rhs);
    }
  if (!flag_z) goto nottype2;  /* not equal / nonzero */  /* BNE.B	nottype2 */
  d1 = (uint32_t)(int32_t)(int8_t)(0);  /* MOVEQ	#0,D1 */
  {  /* MOVE.B	5(A1),D1 */
      uint8_t _mv = (uint8_t)(READ8(a1 + 5));
      B(d1) = (uint8_t)_mv;
      flag_z = ((int8_t)(_mv) == 0);
      flag_n = ((int8_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  if (!flag_z) goto ibe2;  /* not equal / nonzero */  /* BNE.B	ibe2 */
  a1 = (uint32_t)((int32_t)a1 + (int32_t)(int16_t)(READ32(a1 + 6)));  /* ADD	6(A1),A1,add,init,bsr,offset */
  goto ibehandled2;  /* BRA.B	ibehandled2 */
ibe2:
  a1 = (uint32_t)((int32_t)a1 + (int32_t)(int16_t)(d1));  /* ADD	D1,A1,add,init,BSR,offset */
ibehandled2:
  a1 = (uint32_t)((int32_t)a1 + (int32_t)(int16_t)(6));  /* ADDQ.L	#6,A1 */
  {  /* MOVE.L	A1,initfuncptr */
      uint32_t _mv = (uint32_t)(a1);
      WRITE32((uintptr_t)initfuncptr, _mv);
      flag_z = ((int32_t)(_mv) == 0);
      flag_n = ((int32_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  {  /* CMP	#$4a40,(A1) */
      int32_t _lhs = (int32_t)(READ32(a1));
      int32_t _rhs = (int32_t)(0x4a40);
      int32_t _cmp = _lhs - _rhs;
      flag_z = (_cmp == 0);
      flag_n = (_cmp < 0);
      flag_c = ((uint32_t)_lhs < (uint32_t)_rhs);
    }
  if (!flag_z) goto noskipt2;  /* not equal / nonzero */  /* BNE.B	noskipt2 */
  {  /* CMP.B	#$67,2(A1) */
      int32_t _lhs = (int32_t)(READ8(a1 + 2));
      int32_t _rhs = (int32_t)(0x67);
      int32_t _cmp = _lhs - _rhs;
      flag_z = (_cmp == 0);
      flag_n = (_cmp < 0);
      flag_c = ((uint32_t)_lhs < (uint32_t)_rhs);
    }
  if (!flag_z) goto noskipt2;  /* not equal / nonzero */  /* BNE.B	noskipt2 */
  a1 = (uint32_t)((int32_t)a1 + (int32_t)(int16_t)(4));  /* ADDQ	#4,A1 */
noskipt2:
  {  /* CMP	#$41fa,(A1) */
      int32_t _lhs = (int32_t)(READ32(a1));
      int32_t _rhs = (int32_t)(0x41fa);
      int32_t _cmp = _lhs - _rhs;
      flag_z = (_cmp == 0);
      flag_n = (_cmp < 0);
      flag_c = ((uint32_t)_lhs < (uint32_t)_rhs);
    }
  if (!flag_z) goto nottype2;  /* not equal / nonzero */  /* BNE.B	nottype2 */
  a1 = (uint32_t)((int32_t)a1 + (int32_t)(int16_t)(2));  /* ADDQ	#2,A1 */
  a1 = (uint32_t)((int32_t)a1 + (int32_t)(int16_t)(READ32(a1)));  /* ADD	(A1),A1 */
  {  /* CMP.L	#$434f534f,(A1) */
      int32_t _lhs = (int32_t)(READ32(a1));
      int32_t _rhs = (int32_t)(0x434f534f);
      int32_t _cmp = _lhs - _rhs;
      flag_z = (_cmp == 0);
      flag_n = (_cmp < 0);
      flag_c = ((uint32_t)_lhs < (uint32_t)_rhs);
    }
  if (!flag_z) goto nottype2;  /* not equal / nonzero */  /* BNE.B	nottype2 */
  d0 = (uint32_t)(int32_t)(int8_t)(0);  /* MOVEQ	#0,D0 */
nottype2:
  return;  /* RTS */
}


/* --- checktype3 --- */
static void checktype3(void) {
  d0 = (uint32_t)(int32_t)(int8_t)(-1);  /* MOVEQ	#-1,D0 */
  {  /* MOVE.L	A0,A1 */
      uint32_t _mv = (uint32_t)(a0);
      a1 = _mv;
      flag_z = ((int32_t)(_mv) == 0);
      flag_n = ((int32_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  gotoinitbsrfunc();  /* BSR	gotoinitbsrfunc */
  {  /* TST.L	D1 */
      uint32_t _tst = (uint32_t)(d1);
      flag_z = (_tst == 0);
      flag_n = ((int32_t)(_tst) < 0);
      flag_c = 0; flag_v = 0;
    }
  if (!flag_z) goto nottype3;  /* not equal / nonzero */  /* BNE.B	nottype3 */
  {  /* MOVE.L	A2,intfuncptr */
      uint32_t _mv = (uint32_t)(a2);
      WRITE32((uintptr_t)intfuncptr, _mv);
      flag_z = ((int32_t)(_mv) == 0);
      flag_n = ((int32_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  {  /* CMP.L	#$48e7fffe,(A1),check,for,push,all */
      int32_t _lhs = (int32_t)(READ32(a1));
      int32_t _rhs = (int32_t)(0x48e7fffe);
      int32_t _cmp = _lhs - _rhs;
      flag_z = (_cmp == 0);
      flag_n = (_cmp < 0);
      flag_c = ((uint32_t)_lhs < (uint32_t)_rhs);
    }
  if (!flag_z) goto nottype3;  /* not equal / nonzero */  /* BNE.B	nottype3 */
  {  /* CMP	#$41fa,4(A1) */
      int32_t _lhs = (int32_t)(READ32(a1 + 4));
      int32_t _rhs = (int32_t)(0x41fa);
      int32_t _cmp = _lhs - _rhs;
      flag_z = (_cmp == 0);
      flag_n = (_cmp < 0);
      flag_c = ((uint32_t)_lhs < (uint32_t)_rhs);
    }
  if (!flag_z) goto nottype3;  /* not equal / nonzero */  /* BNE.B	nottype3 */
  a2 = (uint32_t)(a1 + 6);  /* LEA	6(A1),A2 */
  a2 = (uint32_t)((int32_t)a2 + (int32_t)(int16_t)(READ32(a2)));  /* ADD	(A2),A2 */
  {  /* CMP.L	#$54464d58,(A2) */
      int32_t _lhs = (int32_t)(READ32(a2));
      int32_t _rhs = (int32_t)(0x54464d58);
      int32_t _cmp = _lhs - _rhs;
      flag_z = (_cmp == 0);
      flag_n = (_cmp < 0);
      flag_c = ((uint32_t)_lhs < (uint32_t)_rhs);
    }
  if (!flag_z) goto nottype3;  /* not equal / nonzero */  /* BNE.B	nottype3 */
  {  /* MOVE.L	A1,initfuncptr */
      uint32_t _mv = (uint32_t)(a1);
      WRITE32((uintptr_t)initfuncptr, _mv);
      flag_z = ((int32_t)(_mv) == 0);
      flag_n = ((int32_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  d0 = (uint32_t)(int32_t)(int8_t)(0);  /* MOVEQ	#0,D0 */
nottype3:
  return;  /* RTS */
}


/* --- gotoinitbsrfunc --- */
static void gotoinitbsrfunc(void) {
  {  /* CMP.B	#$60,(A1) */
      int32_t _lhs = (int32_t)(READ8(a1));
      int32_t _rhs = (int32_t)(0x60);
      int32_t _cmp = _lhs - _rhs;
      flag_z = (_cmp == 0);
      flag_n = (_cmp < 0);
      flag_c = ((uint32_t)_lhs < (uint32_t)_rhs);
    }
  if (!flag_z) goto gotoiniterr;  /* not equal / nonzero */  /* BNE.B	gotoiniterr */
  {  /* CMP.B	#$60,2(A1) */
      int32_t _lhs = (int32_t)(READ8(a1 + 2));
      int32_t _rhs = (int32_t)(0x60);
      int32_t _cmp = _lhs - _rhs;
      flag_z = (_cmp == 0);
      flag_n = (_cmp < 0);
      flag_c = ((uint32_t)_lhs < (uint32_t)_rhs);
    }
  if (flag_z) goto gotoinitbsr1;  /* equal / zero */  /* BEQ.B	gotoinitbsr1 */
  {  /* CMP	#$6000,4(A1) */
      int32_t _lhs = (int32_t)(READ32(a1 + 4));
      int32_t _rhs = (int32_t)(0x6000);
      int32_t _cmp = _lhs - _rhs;
      flag_z = (_cmp == 0);
      flag_n = (_cmp < 0);
      flag_c = ((uint32_t)_lhs < (uint32_t)_rhs);
    }
  if (!flag_z) goto gotoiniterr;  /* not equal / nonzero */  /* BNE.B	gotoiniterr */
  a1 = (uint32_t)((int32_t)a1 + (int32_t)(int16_t)(2));  /* ADDQ	#2,A1,it,s bra */
  a1 = (uint32_t)((int32_t)a1 + (int32_t)(int16_t)(READ32(a1)));  /* ADD	(A1),A1,go,to,init,bsr,func */
  a2 = (uint32_t)(a0 + 4);  /* LEA	4(A0),A2 */
  goto gotoinitbsr2;  /* BRA.B	gotoinitbsr2 */
gotoinitbsr1:
  d1 = (uint32_t)(int32_t)(int8_t)(0);  /* MOVEQ	#0,D1,it,s bra.b */
  {  /* MOVE.B	1(A1),D1 */
      uint8_t _mv = (uint8_t)(READ8(a1 + 1));
      B(d1) = (uint8_t)_mv;
      flag_z = ((int8_t)(_mv) == 0);
      flag_n = ((int8_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  a1 = (uint32_t)((int32_t)a1 + (int32_t)(int16_t)(2));  /* ADDQ.L	#2,A1 */
  a1 = (uint32_t)((int32_t)a1 + (int32_t)(int16_t)(d1));  /* ADD	D1,A1,go,to,init,bsr,func */
  a2 = (uint32_t)(a0 + 2);  /* LEA	2(A0),A2 */
gotoinitbsr2:
  d1 = (uint32_t)(int32_t)(int8_t)(0);  /* MOVEQ	#0,D1 */
  return;  /* RTS */
gotoiniterr:
  d1 = (uint32_t)(int32_t)(int8_t)(-1);  /* MOVEQ	#-1,D1 */
  return;  /* RTS */
}


/* --- checksubs --- */
static void checksubs(void) {
  /* UNIMPLEMENTED: PUSH */  /* PUSH	all */
  {  /* MOVE.L	dtg_ChkData(A5),A0 */
      uint32_t _mv = (uint32_t)(READ32(a5 + (intptr_t)dtg_ChkData));
      a0 = _mv;
      flag_z = ((int32_t)(_mv) == 0);
      flag_n = ((int32_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  {  /* MOVE.L	dtg_ChkSize(A5),D0 */
      uint32_t _mv = (uint32_t)(READ32(a5 + (intptr_t)dtg_ChkSize));
      d0 = _mv;
      flag_z = ((int32_t)(_mv) == 0);
      flag_n = ((int32_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  {  /* ADD.L	A0,D0 */
      uint32_t _ar = (uint32_t)(d0 + a0);
      d0 = (uint32_t)_ar;
      flag_z = ((int32_t)(_ar) == 0);
      flag_n = ((int32_t)(_ar) < 0);
    }
  d0 = d0 & ~(1u << (0 & 31));  /* BCLR	#0,D0 */
  {  /* MOVE.L	D0,A1 */
      uint32_t _mv = (uint32_t)(d0);
      a1 = _mv;
      flag_z = ((int32_t)(_mv) == 0);
      flag_n = ((int32_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  {  /* MOVE.L	#$434f534f,D4 */
      uint32_t _mv = (uint32_t)(0x434f534f);
      d4 = _mv;
      flag_z = ((int32_t)(_mv) == 0);
      flag_n = ((int32_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  {  /* MOVE.L	#$54464d58,D5 */
      uint32_t _mv = (uint32_t)(0x54464d58);
      d5 = _mv;
      flag_z = ((int32_t)(_mv) == 0);
      flag_n = ((int32_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  d2 = (uint32_t)(int32_t)(int8_t)(0);  /* MOVEQ	#0,D2,COSO,counter */
  d3 = (uint32_t)(int32_t)(int8_t)(0);  /* MOVEQ	#0,D3,TFMX,counter */
csloop1:
  {  /* MOVE.L	(A0),D0 */
      uint32_t _mv = (uint32_t)(READ32(a0));
      d0 = _mv;
      flag_z = ((int32_t)(_mv) == 0);
      flag_n = ((int32_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  {  /* CMP.L	D0,D4,COSO */
      int32_t _lhs = (int32_t)(d4);
      int32_t _rhs = (int32_t)(d0);
      int32_t _cmp = _lhs - _rhs;
      flag_z = (_cmp == 0);
      flag_n = (_cmp < 0);
      flag_c = ((uint32_t)_lhs < (uint32_t)_rhs);
    }
  if (!flag_z) goto notcoso;  /* not equal / nonzero */  /* BNE.B	notcoso */
  {  /* CMP.L	32(A0),D5,TFMX */
      int32_t _lhs = (int32_t)(d5);
      int32_t _rhs = (int32_t)(READ32(a0 + 32));
      int32_t _cmp = _lhs - _rhs;
      flag_z = (_cmp == 0);
      flag_n = (_cmp < 0);
      flag_c = ((uint32_t)_lhs < (uint32_t)_rhs);
    }
  if (!flag_z) goto notcoso;  /* not equal / nonzero */  /* BNE.B	notcoso */
  {  /* ADDQ.L	#1,D2 */
      uint32_t _ar = (uint32_t)(d2 + 1);
      d2 = (uint32_t)_ar;
      flag_z = ((int32_t)(_ar) == 0);
      flag_n = ((int32_t)(_ar) < 0);
    }
notcoso:
  {  /* CMP.L	D0,D5,TFMX */
      int32_t _lhs = (int32_t)(d5);
      int32_t _rhs = (int32_t)(d0);
      int32_t _cmp = _lhs - _rhs;
      flag_z = (_cmp == 0);
      flag_n = (_cmp < 0);
      flag_c = ((uint32_t)_lhs < (uint32_t)_rhs);
    }
  if (!flag_z) goto nottfmx;  /* not equal / nonzero */  /* BNE.B	nottfmx */
  {  /* ADDQ.L	#1,D3 */
      uint32_t _ar = (uint32_t)(d3 + 1);
      d3 = (uint32_t)_ar;
      flag_z = ((int32_t)(_ar) == 0);
      flag_n = ((int32_t)(_ar) < 0);
    }
nottfmx:
  a0 = (uint32_t)((int32_t)a0 + (int32_t)(int16_t)(2));  /* ADDQ.L	#2,A0 */
  {  /* CMP.L	A0,A1 */
      int32_t _lhs = (int32_t)(a1);
      int32_t _rhs = (int32_t)(a0);
      int32_t _cmp = _lhs - _rhs;
      flag_z = (_cmp == 0);
      flag_n = (_cmp < 0);
      flag_c = ((uint32_t)_lhs < (uint32_t)_rhs);
    }
  if (!flag_z && (flag_n==flag_v)) goto csloop1;  /* greater than (signed) */  /* BGT.B	csloop1 */
  {  /* TST.L	D2 */
      uint32_t _tst = (uint32_t)(d2);
      flag_z = (_tst == 0);
      flag_n = ((int32_t)(_tst) < 0);
      flag_c = 0; flag_v = 0;
    }
  if (!flag_z) goto cosocheck;  /* not equal / nonzero */  /* BNE.B	cosocheck */
  {  /* TST.L	D3 */
      uint32_t _tst = (uint32_t)(d3);
      flag_z = (_tst == 0);
      flag_n = ((int32_t)(_tst) < 0);
      flag_c = 0; flag_v = 0;
    }
  if (flag_z) goto csend;  /* equal / zero */  /* BEQ	csend */
tfmxcheck:
  {  /* MOVE.L	dtg_ChkData(A5),A0 */
      uint32_t _mv = (uint32_t)(READ32(a5 + (intptr_t)dtg_ChkData));
      a0 = _mv;
      flag_z = ((int32_t)(_mv) == 0);
      flag_n = ((int32_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  {  /* MOVE.L	dtg_ChkSize(A5),D0 */
      uint32_t _mv = (uint32_t)(READ32(a5 + (intptr_t)dtg_ChkSize));
      d0 = _mv;
      flag_z = ((int32_t)(_mv) == 0);
      flag_n = ((int32_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  {  /* ADD.L	A0,D0 */
      uint32_t _ar = (uint32_t)(d0 + a0);
      d0 = (uint32_t)_ar;
      flag_z = ((int32_t)(_ar) == 0);
      flag_n = ((int32_t)(_ar) < 0);
    }
  d0 = d0 & ~(1u << (0 & 31));  /* BCLR	#0,D0 */
  {  /* MOVE.L	D0,A1 */
      uint32_t _mv = (uint32_t)(d0);
      a1 = _mv;
      flag_z = ((int32_t)(_mv) == 0);
      flag_n = ((int32_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  d7 = (uint32_t)(int32_t)(int8_t)(0);  /* MOVEQ	#0,D7,max,subsong */
cstloop1:
  {  /* CMP.L	(A0),D5,TFMX */
      int32_t _lhs = (int32_t)(d5);
      int32_t _rhs = (int32_t)(READ32(a0));
      int32_t _cmp = _lhs - _rhs;
      flag_z = (_cmp == 0);
      flag_n = (_cmp < 0);
      flag_c = ((uint32_t)_lhs < (uint32_t)_rhs);
    }
  if (!flag_z) goto notcoso3;  /* not equal / nonzero */  /* BNE.B	notcoso3 */
  d1 = (uint32_t)(int32_t)(int8_t)(0);  /* MOVEQ	#0,D1 */
  d0 = (uint32_t)(int32_t)(int8_t)(0);  /* MOVEQ	#0,D0 */
  {  /* MOVE	4(A0),D0 */
      uint32_t _mv = (uint32_t)(READ32(a0 + 4));
      d0 = _mv;
      flag_z = ((int32_t)(_mv) == 0);
      flag_n = ((int32_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  {  /* ADD	6(A0),D0 */
      uint32_t _ar = (uint32_t)(d0 + READ32(a0 + 6));
      d0 = (uint32_t)_ar;
      flag_z = ((int32_t)(_ar) == 0);
      flag_n = ((int32_t)(_ar) < 0);
    }
  {  /* ADDQ	#2,D0 */
      uint32_t _ar = (uint32_t)(d0 + 2);
      d0 = (uint32_t)_ar;
      flag_z = ((int32_t)(_ar) == 0);
      flag_n = ((int32_t)(_ar) < 0);
    }
  d0 = d0 << 6;  /* LSL	#6,D0 */
  {  /* ADD.L	D0,D1 */
      uint32_t _ar = (uint32_t)(d1 + d0);
      d1 = (uint32_t)_ar;
      flag_z = ((int32_t)(_ar) == 0);
      flag_n = ((int32_t)(_ar) < 0);
    }
  {  /* MOVE	8(A0),D0 */
      uint32_t _mv = (uint32_t)(READ32(a0 + 8));
      d0 = _mv;
      flag_z = ((int32_t)(_mv) == 0);
      flag_n = ((int32_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  {  /* ADDQ	#1,D0 */
      uint32_t _ar = (uint32_t)(d0 + 1);
      d0 = (uint32_t)_ar;
      flag_z = ((int32_t)(_ar) == 0);
      flag_n = ((int32_t)(_ar) < 0);
    }
  d0 = (uint32_t)((uint16_t)READ32(a0 + 12) * (uint16_t)W(d0));  /* MULU	12(A0),D0 */
  {  /* ADD.L	D0,D1 */
      uint32_t _ar = (uint32_t)(d1 + d0);
      d1 = (uint32_t)_ar;
      flag_z = ((int32_t)(_ar) == 0);
      flag_n = ((int32_t)(_ar) < 0);
    }
  {  /* MOVE	10(A0),D0 */
      uint32_t _mv = (uint32_t)(READ32(a0 + 10));
      d0 = _mv;
      flag_z = ((int32_t)(_mv) == 0);
      flag_n = ((int32_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  {  /* ADDQ	#1,D0 */
      uint32_t _ar = (uint32_t)(d0 + 1);
      d0 = (uint32_t)_ar;
      flag_z = ((int32_t)(_ar) == 0);
      flag_n = ((int32_t)(_ar) < 0);
    }
  d0 = (uint32_t)((uint16_t)12 * (uint16_t)W(d0));  /* MULU	#12,D0 */
  {  /* ADD.L	D0,D1 */
      uint32_t _ar = (uint32_t)(d1 + d0);
      d1 = (uint32_t)_ar;
      flag_z = ((int32_t)(_ar) == 0);
      flag_n = ((int32_t)(_ar) < 0);
    }
  {  /* CMP.L	dtg_ChkSize(A5),D1 */
      int32_t _lhs = (int32_t)(d1);
      int32_t _rhs = (int32_t)(READ32(a5 + (intptr_t)dtg_ChkSize));
      int32_t _cmp = _lhs - _rhs;
      flag_z = (_cmp == 0);
      flag_n = (_cmp < 0);
      flag_c = ((uint32_t)_lhs < (uint32_t)_rhs);
    }
  if (flag_n==flag_v) goto notcoso3;  /* greater or equal (signed) */  /* BGE.B	notcoso3 */
  a2 = (uint32_t)(a0 + 34);  /* LEA	34(A0),A2 */
cstloop2:
  {  /* TST	(A2) */
      uint32_t _tst = (uint32_t)(READ32(a2));
      flag_z = (_tst == 0);
      flag_n = ((int32_t)(_tst) < 0);
      flag_c = 0; flag_v = 0;
    }
  if (flag_z) goto notcoso3;  /* equal / zero */  /* BEQ.B	notcoso3 */
  {  /* ADDQ.L	#1,D7 */
      uint32_t _ar = (uint32_t)(d7 + 1);
      d7 = (uint32_t)_ar;
      flag_z = ((int32_t)(_ar) == 0);
      flag_n = ((int32_t)(_ar) < 0);
    }
  {  /* CMP.L	#64,D7,max,#64,subsongs */
      int32_t _lhs = (int32_t)(d7);
      int32_t _rhs = (int32_t)(64);
      int32_t _cmp = _lhs - _rhs;
      flag_z = (_cmp == 0);
      flag_n = (_cmp < 0);
      flag_c = ((uint32_t)_lhs < (uint32_t)_rhs);
    }
  if (flag_n==flag_v) goto notcoso3;  /* greater or equal (signed) */  /* BGE.B	notcoso3 */
  a2 = (uint32_t)((int32_t)a2 + (int32_t)(int16_t)(6));  /* ADDQ.L	#6,A2 */
  goto cstloop2;  /* BRA.B	cstloop2 */
notcoso3:
  a0 = (uint32_t)((int32_t)a0 + (int32_t)(int16_t)(2));  /* ADDQ.L	#2,A0 */
  {  /* CMP.L	A0,A1 */
      int32_t _lhs = (int32_t)(a1);
      int32_t _rhs = (int32_t)(a0);
      int32_t _cmp = _lhs - _rhs;
      flag_z = (_cmp == 0);
      flag_n = (_cmp < 0);
      flag_c = ((uint32_t)_lhs < (uint32_t)_rhs);
    }
  if (!flag_z && (flag_n==flag_v)) goto cstloop1;  /* greater than (signed) */  /* BGT.B	cstloop1 */
  {  /* MOVE.L	D7,maxsubsong */
      uint32_t _mv = (uint32_t)(d7);
      WRITE32((uintptr_t)maxsubsong, _mv);
      flag_z = ((int32_t)(_mv) == 0);
      flag_n = ((int32_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  goto csend;  /* BRA.B	csend */
cosocheck:
  {  /* MOVE.L	dtg_ChkData(A5),A0 */
      uint32_t _mv = (uint32_t)(READ32(a5 + (intptr_t)dtg_ChkData));
      a0 = _mv;
      flag_z = ((int32_t)(_mv) == 0);
      flag_n = ((int32_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  {  /* MOVE.L	dtg_ChkSize(A5),D0 */
      uint32_t _mv = (uint32_t)(READ32(a5 + (intptr_t)dtg_ChkSize));
      d0 = _mv;
      flag_z = ((int32_t)(_mv) == 0);
      flag_n = ((int32_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  {  /* ADD.L	A0,D0 */
      uint32_t _ar = (uint32_t)(d0 + a0);
      d0 = (uint32_t)_ar;
      flag_z = ((int32_t)(_ar) == 0);
      flag_n = ((int32_t)(_ar) < 0);
    }
  d0 = d0 & ~(1u << (0 & 31));  /* BCLR	#0,D0 */
  {  /* MOVE.L	D0,A1 */
      uint32_t _mv = (uint32_t)(d0);
      a1 = _mv;
      flag_z = ((int32_t)(_mv) == 0);
      flag_n = ((int32_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  d7 = (uint32_t)(int32_t)(int8_t)(0);  /* MOVEQ	#0,D7,max,subsong */
cscloop1:
  {  /* CMP.L	(A0),D4,COSO */
      int32_t _lhs = (int32_t)(d4);
      int32_t _rhs = (int32_t)(READ32(a0));
      int32_t _cmp = _lhs - _rhs;
      flag_z = (_cmp == 0);
      flag_n = (_cmp < 0);
      flag_c = ((uint32_t)_lhs < (uint32_t)_rhs);
    }
  if (!flag_z) goto notcoso2;  /* not equal / nonzero */  /* BNE.B	notcoso2 */
  {  /* CMP.L	32(A0),D5,TFMX */
      int32_t _lhs = (int32_t)(d5);
      int32_t _rhs = (int32_t)(READ32(a0 + 32));
      int32_t _cmp = _lhs - _rhs;
      flag_z = (_cmp == 0);
      flag_n = (_cmp < 0);
      flag_c = ((uint32_t)_lhs < (uint32_t)_rhs);
    }
  if (!flag_z) goto notcoso2;  /* not equal / nonzero */  /* BNE.B	notcoso2 */
  {  /* MOVE.L	20(A0),D0,sub,tab,offset */
      uint32_t _mv = (uint32_t)(READ32(a0 + 20));
      d0 = _mv;
      flag_z = ((int32_t)(_mv) == 0);
      flag_n = ((int32_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  if (flag_z) goto notcoso2;  /* equal / zero */  /* BEQ.B	notcoso2 */
  a2 = (uint32_t)(a0 + 2);  /* LEA	2(A0),A2 */
cscloop2:
  {  /* TST	(A2) */
      uint32_t _tst = (uint32_t)(READ32(a2));
      flag_z = (_tst == 0);
      flag_n = ((int32_t)(_tst) < 0);
      flag_c = 0; flag_v = 0;
    }
  if (flag_z) goto notcoso2;  /* equal / zero */  /* BEQ.B	notcoso2 */
  {  /* ADDQ.L	#1,D7 */
      uint32_t _ar = (uint32_t)(d7 + 1);
      d7 = (uint32_t)_ar;
      flag_z = ((int32_t)(_ar) == 0);
      flag_n = ((int32_t)(_ar) < 0);
    }
  {  /* CMP.L	#64,D7,max,#64,subsongs */
      int32_t _lhs = (int32_t)(d7);
      int32_t _rhs = (int32_t)(64);
      int32_t _cmp = _lhs - _rhs;
      flag_z = (_cmp == 0);
      flag_n = (_cmp < 0);
      flag_c = ((uint32_t)_lhs < (uint32_t)_rhs);
    }
  if (flag_n==flag_v) goto notcoso2;  /* greater or equal (signed) */  /* BGE.B	notcoso2 */
  a2 = (uint32_t)((int32_t)a2 + (int32_t)(int16_t)(6));  /* ADDQ.L	#6,A2 */
  goto cscloop2;  /* BRA.B	cscloop2 */
notcoso2:
  a0 = (uint32_t)((int32_t)a0 + (int32_t)(int16_t)(2));  /* ADDQ.L	#2,A0 */
  {  /* CMP.L	A0,A1 */
      int32_t _lhs = (int32_t)(a1);
      int32_t _rhs = (int32_t)(a0);
      int32_t _cmp = _lhs - _rhs;
      flag_z = (_cmp == 0);
      flag_n = (_cmp < 0);
      flag_c = ((uint32_t)_lhs < (uint32_t)_rhs);
    }
  if (!flag_z && (flag_n==flag_v)) goto cscloop1;  /* greater than (signed) */  /* BGT.B	cscloop1 */
  {  /* MOVE.L	D7,maxsubsong */
      uint32_t _mv = (uint32_t)(d7);
      WRITE32((uintptr_t)maxsubsong, _mv);
      flag_z = ((int32_t)(_mv) == 0);
      flag_n = ((int32_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
csend:
  /* UNIMPLEMENTED: PULL */  /* PULL	all */
  return;  /* RTS */
}


/* --- patchmod --- */
static void patchmod(void) {
  /* UNIMPLEMENTED: PUSH */  /* PUSH	all */
  {  /* MOVE.L	InitFuncPtr(PC),A0 */
      uint32_t _mv = (uint32_t)(READ32((uintptr_t)InitFuncPtr));
      a0 = _mv;
      flag_z = ((int32_t)(_mv) == 0);
      flag_n = ((int32_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  a1 = (uint32_t)(a0 + 1024);  /* LEA	1024(A0),A1 */
patchloop:
  {  /* CMP.L	#$b5cb6606,(A0) */
      int32_t _lhs = (int32_t)(READ32(a0));
      int32_t _rhs = (int32_t)(0xb5cb6606);
      int32_t _cmp = _lhs - _rhs;
      flag_z = (_cmp == 0);
      flag_n = (_cmp < 0);
      flag_c = ((uint32_t)_lhs < (uint32_t)_rhs);
    }
  if (!flag_z) goto next;  /* not equal / nonzero */  /* BNE.B	next */
  {  /* CMP.L	#$21450004,4(A0) */
      int32_t _lhs = (int32_t)(READ32(a0 + 4));
      int32_t _rhs = (int32_t)(0x21450004);
      int32_t _cmp = _lhs - _rhs;
      flag_z = (_cmp == 0);
      flag_n = (_cmp < 0);
      flag_c = ((uint32_t)_lhs < (uint32_t)_rhs);
    }
  if (!flag_z) goto next;  /* not equal / nonzero */  /* BNE.B	next */
  {  /* CMP.L	#$24507200,8(A0) */
      int32_t _lhs = (int32_t)(READ32(a0 + 8));
      int32_t _rhs = (int32_t)(0x24507200);
      int32_t _cmp = _lhs - _rhs;
      flag_z = (_cmp == 0);
      flag_n = (_cmp < 0);
      flag_c = ((uint32_t)_lhs < (uint32_t)_rhs);
    }
  if (!flag_z) goto next;  /* not equal / nonzero */  /* BNE.B	next */
  {  /* CMP.L	#$1212116a,12(A0) */
      int32_t _lhs = (int32_t)(READ32(a0 + 12));
      int32_t _rhs = (int32_t)(0x1212116a);
      int32_t _cmp = _lhs - _rhs;
      flag_z = (_cmp == 0);
      flag_n = (_cmp < 0);
      flag_c = ((uint32_t)_lhs < (uint32_t)_rhs);
    }
  if (!flag_z) goto next;  /* not equal / nonzero */  /* BNE.B	next */
  {  /* CMP.L	#$0001002c,16(A0) */
      int32_t _lhs = (int32_t)(READ32(a0 + 16));
      int32_t _rhs = (int32_t)(0x0001002c);
      int32_t _cmp = _lhs - _rhs;
      flag_z = (_cmp == 0);
      flag_n = (_cmp < 0);
      flag_c = ((uint32_t)_lhs < (uint32_t)_rhs);
    }
  if (!flag_z) goto next;  /* not equal / nonzero */  /* BNE.B	next */
  {  /* CMP.L	#$116a0002,20(A0) */
      int32_t _lhs = (int32_t)(READ32(a0 + 20));
      int32_t _rhs = (int32_t)(0x116a0002);
      int32_t _cmp = _lhs - _rhs;
      flag_z = (_cmp == 0);
      flag_n = (_cmp < 0);
      flag_c = ((uint32_t)_lhs < (uint32_t)_rhs);
    }
  if (!flag_z) goto next;  /* not equal / nonzero */  /* BNE.B	next */
  a2 = (uint32_t)(uintptr_t)songendfunc;  /* LEA	songendfunc(PC),A2 */
  {  /* MOVE	jsrcom(PC),4(A0) */
      uint32_t _mv = (uint32_t)(READ32((uintptr_t)jsrcom));
      WRITE32(a0 + 4, _mv);
      flag_z = ((int32_t)(_mv) == 0);
      flag_n = ((int32_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  {  /* MOVE.L	A2,6(A0) */
      uint32_t _mv = (uint32_t)(a2);
      WRITE32(a0 + 6, _mv);
      flag_z = ((int32_t)(_mv) == 0);
      flag_n = ((int32_t)(_mv) < 0);
      flag_v = 0; flag_c = 0;
    }
  goto patched;  /* BRA.B	patched */
next:
  a0 = (uint32_t)((int32_t)a0 + (int32_t)(int16_t)(2));  /* ADDQ.L	#2,A0 */
  {  /* CMP.L	A0,A1 */
      int32_t _lhs = (int32_t)(a1);
      int32_t _rhs = (int32_t)(a0);
      int32_t _cmp = _lhs - _rhs;
      flag_z = (_cmp == 0);
      flag_n = (_cmp < 0);
      flag_c = ((uint32_t)_lhs < (uint32_t)_rhs);
    }
  if (!flag_z) goto patchloop;  /* not equal / nonzero */  /* BNE.B	patchloop */
patched:
  /* UNIMPLEMENTED: PULL */  /* PULL	all */
  return;  /* RTS */
}


/* --- jsrcom ---  (address-referenced) */
static void jsrcom(void) {
  { uintptr_t _jt=(uintptr_t)(0); if(_jt) ((void(*)(void))_jt)(); }  /* JSR	#0 */
}


/* --- songendfunc ---  (address-referenced) */

/* Patch DC.L label references with runtime addresses */
static void _ds_init(void) {
  WRITE32((uintptr_t)(_ds + 2), (uint32_t)(uintptr_t)table);
  WRITE32((uintptr_t)(_ds + 140), (uint32_t)(uintptr_t)playername);
  WRITE32((uintptr_t)(_ds + 148), (uint32_t)(uintptr_t)creator);
}


/* TRANSPILER WARNINGS:
 * Line 349: Custom chip write $dff000 — emitted as no-op
 */
/* ===== WASM Harness (appended) ===== */
#include "paula_soft.h"
#include <stdlib.h>
#include <string.h>

#ifdef __EMSCRIPTEN__
#include <emscripten.h>
#define EXPORT EMSCRIPTEN_KEEPALIVE
#else
#define EXPORT
#endif

static int g_initialized = 0;
static double g_frames_per_tick = 0.0;
static double g_accum = 0.0;
static uint8_t *g_song_buf = NULL;
static uint32_t g_tick_count = 0;
static double g_output_rate = (double)PAULA_RATE_PAL;

#define VBLANK_HZ 50.0

EXPORT int player_init(const uint8_t *module_data, uint32_t module_size) {
    paula_reset();
    g_accum = 0.0;
    g_tick_count = 0;
    g_frames_per_tick = g_output_rate / VBLANK_HZ;

    if (g_song_buf) { free(g_song_buf); g_song_buf = NULL; }

    g_song_buf = (uint8_t *)malloc(module_size);
    if (!g_song_buf) return -1;
    memcpy(g_song_buf, module_data, module_size);

    a0 = (uint32_t)(uintptr_t)g_song_buf;
    InitSound();
    InitPlayer();

    g_initialized = 1;
    return 0;
}

EXPORT int player_render(float *buf, int frames) {
    if (!g_initialized) return 0;
    float *out = buf;
    int remaining = frames;

    while (remaining > 0) {
        double until_tick = g_frames_per_tick - g_accum;
        int n = (int)until_tick;
        if (n < 1) n = 1;
        if (n > remaining) n = remaining;

        int got = paula_render(out, n);
        out += got * 2;
        remaining -= got;
        g_accum += (double)got;

        if (g_accum >= g_frames_per_tick) {
            g_accum -= g_frames_per_tick;
            Interrupt();
            g_tick_count++;
        }
    }
    return frames;
}

EXPORT void player_stop(void) {
    if (g_initialized) {
        EndPlayer();
        paula_reset();
        if (g_song_buf) { free(g_song_buf); g_song_buf = NULL; }
        g_initialized = 0;
    }
}

EXPORT void player_set_sample_rate(int rate) {
    g_output_rate = (double)rate;
    paula_set_output_rate((float)rate);
    g_frames_per_tick = g_output_rate / VBLANK_HZ;
}

EXPORT int player_is_finished(void) { return 0; }
EXPORT int player_get_subsong_count(void) { return 1; }
EXPORT void player_set_subsong(int n) { (void)n; }
EXPORT const char* player_get_title(void) { return "Jochen Hippel"; }
EXPORT double player_detect_duration(void) { return 0.0; }
EXPORT void player_set_channel_gain(int ch, float gain) {
    paula_set_channel_gain(ch, gain);
}
