#!/usr/bin/env node
import { readFileSync, writeFileSync, mkdirSync } from 'fs';
import { join, basename, extname } from 'path';
import { fileURLToPath } from 'url';
import { Command } from 'commander';
import { tokenize } from './lexer.js';
import { parse } from './parser.js';
import { resolve } from './resolver.js';
import { emit } from './emitter.js';
import { genWrapper, genCMake } from './gen-wrapper.js';
import { restructure } from './restructure.js';

const program = new Command();

program
  .name('asm68k-to-c')
  .description('Transpile Motorola 68000 Amiga music replayer ASM to portable C')
  .version('0.1.0')
  .argument('<input...>', 'Input .asm or .s files')
  .option('-o, --output-dir <dir>', 'Output directory', './output')
  .option('-n, --player-name <name>', 'Player name (default: input filename)')
  .option('--timing <pal|ntsc>', 'Paula clock', 'pal')
  .option('--no-wrapper', 'Skip Wrapper.c / CMakeLists.txt generation')
  .option('--dry-run', 'Parse and report only, no output files')
  .option('--verbose', 'Show symbol table and warnings')
  .option('--pass2', 'Enable Pass 2 restructuring (experimental)', false)
  .option('-P, --preamble <file>', 'Prepend ASM file before main source (repeatable)', (v: string, acc: string[]) => [...acc, v], [] as string[])
  .action((inputs: string[], opts) => {
    for (const inputPath of inputs) {
      // Build source: optional preamble files + main source
      const preambles = (opts.preamble as string[] | undefined) ?? [];
      const preambleSource = preambles.map(p => readFileSync(p, 'utf8')).join('\n');
      const mainSource = readFileSync(inputPath, 'utf8');
      const source = preambleSource ? preambleSource + '\n' + mainSource : mainSource;
      const name   = opts.playerName ?? basename(inputPath, extname(inputPath));
      const outDir = join(opts.outputDir, name);

      const tokens   = tokenize(source);
      const ast      = parse(tokens);
      const resolved = resolve(ast);

      if (opts.verbose) {
        console.log(`[${name}] Symbols: ${resolved.symbols.size}, Labels: ${resolved.labels.size}, Exports: ${resolved.exports.join(', ')}`);
        if (resolved.warnings.length) {
          console.warn(`[${name}] Warnings:`);
          resolved.warnings.forEach(w => console.warn('  ' + w));
        }
        console.log(`[${name}] Paula writes: ${resolved.paulaWrites.length}`);
      }

      const cOutput = emit(ast, resolved, basename(inputPath));
      const finalOutput = opts.pass2 ? restructure(cOutput) : cOutput;

      if (opts.dryRun) {
        console.log(`[${name}] Dry run complete. ${ast.length} AST nodes.`);
        continue;
      }

      mkdirSync(outDir, { recursive: true });
      writeFileSync(join(outDir, `${name}.c`), finalOutput);
      writeFileSync(join(outDir, `${name}.h`), genHeader(name, resolved.exports));

      if (opts.wrapper !== false) {
        const timing = opts.timing === 'ntsc' ? 'ntsc' : 'pal';
        const wrapper = genWrapper({ playerName: name, exports: resolved.exports, timing });
        const cmake   = genCMake({ playerName: name, playerFile: `${name}.c` });
        writeFileSync(join(outDir, `${name}_wrapper.c`), wrapper);
        writeFileSync(join(outDir, 'CMakeLists.txt'), cmake);

        // Copy paula runtime files
        const runtimeDir = join(fileURLToPath(new URL('.', import.meta.url)), '../runtime');
        writeFileSync(join(outDir, 'paula_soft.h'), readFileSync(join(runtimeDir, 'paula_soft.h')));
        writeFileSync(join(outDir, 'paula_soft.c'), readFileSync(join(runtimeDir, 'paula_soft.c')));
      }

      console.log(`[${name}] Written to ${outDir}/`);
    }
  });

function genHeader(name: string, exports: string[]): string {
  const guard = name.toUpperCase().replace(/[^A-Z0-9]/g, '_') + '_H';
  return `#pragma once
// ${name}.h — auto-generated by asm68k-to-c
#ifndef ${guard}
#define ${guard}

${exports.map(e => `void ${e}(void);`).join('\n')}

#endif /* ${guard} */
`;
}

program.parse();
