interface WrapperOpts {
  playerName: string;
  exports: string[];
  initFn?: string;
  tickFn?: string;
  timing?: 'pal' | 'ntsc';
}

export function genWrapper(opts: WrapperOpts): string {
  const { playerName, exports } = opts;
  const initFn = opts.initFn ?? exports.find(e => /init/i.test(e)) ?? exports[0] ?? 'InitPlay';
  const tickFn = opts.tickFn ?? exports.find(e => /play|music|tick/i.test(e) && !/init/i.test(e)) ?? exports[1] ?? 'PlayMusic';
  const rateConst = (opts.timing === 'ntsc') ? 'PAULA_RATE_NTSC' : 'PAULA_RATE_PAL';
  const clockFn = (opts.timing === 'ntsc') ? 'paula_set_clock(PAULA_CLOCK_NTSC);' : '';

  return `// ${playerName}_wrapper.c — Emscripten C-linkage shim
// Auto-generated by asm68k-to-c. DO NOT EDIT.
// Pattern: mirrors musicline-wasm/common/MusicLineWrapper.cpp

#include "${playerName}.h"
#include "paula_soft.h"
#include <stdint.h>
#include <string.h>

static int   s_loaded         = 0;
static int   s_finished       = 0;
static float s_tick_accum     = 0.0f;
static float s_ticks_per_sec  = 50.0f;  // CIA 50 Hz PAL
static float s_samples_per_tick = 0.0f;

void player_init(int sample_rate) {
    (void)sample_rate;
    s_ticks_per_sec    = 50.0f;
    s_samples_per_tick = (float)${rateConst} / s_ticks_per_sec;
    ${clockFn}
    paula_reset();
    s_loaded   = 0;
    s_finished = 0;
    s_tick_accum = 0.0f;
}

int player_load(const uint8_t* data, int len) {
    if (!data || len <= 0) return 0;
    /* Pass module data via the init function's a0 convention.
     * The generated replayer exposes set_module_data() or takes it via ${initFn}.
     * For now, call init with no args — replayer reads data from
     * module pointer set in a0 register file. */
    ${initFn}();
    (void)data; (void)len;
    s_loaded   = 1;
    s_finished = 0;
    s_tick_accum = 0.0f;
    return 1;
}

int player_render(float* buffer, int frames) {
    if (!s_loaded) { memset(buffer, 0, frames * 2 * sizeof(float)); return -1; }
    if (s_finished) { memset(buffer, 0, frames * 2 * sizeof(float)); return 0; }
    int written = 0;
    while (written < frames) {
        int chunk = (frames - written) < 64 ? (frames - written) : 64;
        paula_render(buffer + written * 2, chunk);
        written += chunk;
        s_tick_accum += (float)chunk;
        while (s_tick_accum >= s_samples_per_tick) {
            s_tick_accum -= s_samples_per_tick;
            ${tickFn}();
        }
    }
    return frames;
}

void player_stop(void) {
    paula_reset();
    s_loaded   = 0;
    s_finished = 1;
}

int player_is_finished(void) { return s_finished ? 1 : 0; }
int player_get_subsong_count(void) { return 1; }
void player_set_subsong(int n) { (void)n; }
const char* player_get_title(void) { return "${playerName}"; }
double player_detect_duration(void) { return 0.0; }
`;
}

interface CMakeOpts {
  playerName: string;
  playerFile: string;
}

export function genCMake(opts: CMakeOpts): string {
  const { playerName, playerFile } = opts;
  const output = playerName.charAt(0).toUpperCase() + playerName.slice(1);

  return `# CMakeLists.txt — auto-generated by asm68k-to-c
# Build: emcmake cmake .. && emmake make
cmake_minimum_required(VERSION 3.13)
project(${output} C)

set(OUTPUT_NAME "${output}")
set(OUTPUT_DIR  "\${CMAKE_SOURCE_DIR}/../../public/${playerName.toLowerCase()}")
file(MAKE_DIRECTORY \${OUTPUT_DIR})

add_executable(\${OUTPUT_NAME}
    ${playerFile}
    ${playerName}_wrapper.c
    paula_soft.c
)

target_include_directories(\${OUTPUT_NAME} PRIVATE .)

if(EMSCRIPTEN)
    set(EXPORTED_FUNCTIONS
        "_malloc" "_free"
        "_player_init" "_player_load" "_player_render" "_player_stop"
        "_player_is_finished" "_player_get_subsong_count" "_player_set_subsong"
        "_player_get_title" "_player_detect_duration"
    )
    string(JOIN "," EXPORT_STR \${EXPORTED_FUNCTIONS})
    target_link_options(\${OUTPUT_NAME} PRIVATE
        -sEXPORTED_FUNCTIONS=[\${EXPORT_STR}]
        -sEXPORTED_RUNTIME_METHODS=['ccall','cwrap','getValue','UTF8ToString']
        -sALLOW_MEMORY_GROWTH=1
        -sINITIAL_MEMORY=33554432
        -sMODULARIZE=1
        -sEXPORT_NAME="create\${OUTPUT_NAME}"
        -O2
    )
    set_target_properties(\${OUTPUT_NAME} PROPERTIES
        RUNTIME_OUTPUT_DIRECTORY "\${OUTPUT_DIR}"
        SUFFIX ".js"
    )
endif()
# Usage: cd build && emcmake cmake .. && emmake make
`;
}
