/*
 * basedir_data.h — Embedded UADE basedir files (config, score, eagleplayer.conf)
 *
 * Auto-generated by generate_registry.py — DO NOT EDIT MANUALLY.
 */
#ifndef _BASEDIR_DATA_H_
#define _BASEDIR_DATA_H_

#include <stdint.h>
#include <stddef.h>

typedef struct {
    const char     *name;    /* Filename (without path) */
    const uint8_t  *data;    /* File content */
    size_t          size;    /* Size in bytes */
} UADEBasedirFile;

extern const UADEBasedirFile uade_basedir_files[];
extern const int uade_basedir_file_count;

#endif /* _BASEDIR_DATA_H_ */
