/*
 * player_registry.h — Embedded UADE eagleplayer binaries
 *
 * Auto-generated by generate_registry.py from the players/ directory.
 * Contains all 175 eagleplayer binaries as static C arrays.
 *
 * DO NOT EDIT MANUALLY — regenerate with: python3 generate_registry.py
 */

#pragma once

#include <stdint.h>
#include <stddef.h>

typedef struct {
    const char    *name;   /* Eagleplayer name (matches filename in players/) */
    const uint8_t *data;   /* Binary data */
    size_t         size;   /* Size in bytes */
} UADEPlayer;

/* All embedded eagleplayers */
extern const UADEPlayer uade_players[];
extern const int        uade_player_count;
