/**
 * generate-cinter-presets — rip synth instruments from a folder of .cinter4 songs
 * into a committed preset file (src/generated/cinterPresets.ts) that merges into
 * FACTORY_PRESETS, so every Cinter voice is selectable in the Cinter4 editor's
 * preset dropdown without loading the song.
 *
 * Cinter parsing is pure JS (no WASM/AudioContext), so this runs in Node. The
 * generator only extracts the 12 params (the baked WAV is redundant — Cinter4Synth
 * regenerates it), matching what buildCinter4Instrument emits, minus `sample`.
 *
 * Usage:  npx tsx scripts/generate-cinter-presets.mts [songsDir]
 *         (default songsDir: ~/Desktop/cinter-songs)
 *
 * Source songs are NOT committed (they are third-party music); only the generated
 * params file is. Re-run this when the song set changes.
 */

import { readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { join, basename } from 'node:path';
import { homedir } from 'node:os';
import {
  cinter4WordsToParams,
  cinter4DetectVersion,
  cinter4ParamsToSampleName,
  type Cinter4SynthWords,
} from '../src/lib/import/formats/cinter4Params.ts';

const songsDir = process.argv[2] || join(homedir(), 'Desktop', 'cinter-songs');
const OUT = join(process.cwd(), 'src', 'generated', 'cinterPresets.ts');

interface CinterPresetGen {
  name: string;
  version: 3 | 4;
  lengthWords: number;
  replenWords: number;
  params: number[];
}

/** Decode the generated-instrument headers from a .cinter4 file (big-endian). */
function extractInstruments(bytes: Uint8Array, songBase: string): CinterPresetGen[] {
  const view = new DataView(bytes.buffer, bytes.byteOffset, bytes.byteLength);
  let off = 0;
  const readI16 = () => { const v = view.getInt16(off, false); off += 2; return v; };
  const readU16 = () => { const v = view.getUint16(off, false); off += 2; return v; };

  // Optional negative raw-instrument count, then |n| raw blocks (4 bytes each).
  const firstWord = view.getInt16(0, false);
  const nRaw = firstWord < 0 ? -firstWord : 0;
  off = firstWord < 0 ? 2 : 0;
  for (let r = 0; r < nRaw; r++) { readU16(); readU16(); } // length, replength (raw — no params)

  const nGen = readI16() + 1; // stored as count-1 (dbra)
  const out: CinterPresetGen[] = [];
  for (let i = 0; i < nGen; i++) {
    if (off + 22 > bytes.length) break; // 11 words
    const lengthWords = readU16();
    const replenWords = readU16();
    const words: Cinter4SynthWords = {
      mpitch: readI16(), mod: readI16(), bpitch: readI16(), attack: readI16(),
      dist: readI16(), decay: readI16(), mpitchdecay: readI16(),
      moddecay: readI16(), bpitchdecay: readI16(),
    };
    const version = cinter4DetectVersion(words);
    const params = cinter4WordsToParams(words, version);
    out.push({
      name: `${songBase} ${String(i + 1).padStart(2, '0')}`,
      version, lengthWords, replenWords, params,
    });
  }
  return out;
}

function fingerprint(g: CinterPresetGen): string {
  return `${g.version}:${g.lengthWords}:${g.replenWords}:${g.params.join(',')}`;
}

// ── Rip every .cinter4 in the folder, dedupe across songs ────────────────────
const files = readdirSync(songsDir).filter((f) => f.toLowerCase().endsWith('.cinter4')).sort();
if (files.length === 0) {
  console.error(`[cinter-presets] no .cinter4 files in ${songsDir}`);
  process.exit(1);
}

const seen = new Set<string>();
const presets: CinterPresetGen[] = [];
for (const file of files) {
  const songBase = basename(file, '.cinter4');
  const bytes = new Uint8Array(readFileSync(join(songsDir, file)));
  const insts = extractInstruments(bytes, songBase);
  let added = 0;
  for (const g of insts) {
    if (g.lengthWords <= 0) continue;
    const fp = fingerprint(g);
    if (seen.has(fp)) continue;
    seen.add(fp);
    presets.push(g);
    added++;
  }
  console.log(`[cinter-presets] ${file}: ${insts.length} instruments, +${added} unique`);
}

// ── Emit the generated preset file ───────────────────────────────────────────
const entries = presets.map((g) => {
  const p = g.params;
  const parameters = {
    cinter: 1, version: g.version, lengthWords: g.lengthWords, replenWords: g.replenWords,
    p0: p[0], p1: p[1], p2: p[2], p3: p[3], p4: p[4], p5: p[5],
    p6: p[6], p7: p[7], p8: p[8], p9: p[9], p10: p[10], p11: p[11],
    sampleName: cinter4ParamsToSampleName(p),
  };
  return {
    type: 'synth', name: g.name, synthType: 'Cinter4Synth',
    volume: 0, pan: 0, effects: [],
    metadata: { modPlayback: { usePeriodPlayback: true, periodMultiplier: 3546895, finetune: 0 } },
    parameters,
  };
});

const header = `/**
 * cinterPresets — AUTO-GENERATED by scripts/generate-cinter-presets.mts. DO NOT EDIT.
 *
 * Synth instruments ripped from bundled Cinter songs, merged into FACTORY_PRESETS
 * so they appear in the Cinter4 editor's preset dropdown. The baked WAV is omitted;
 * Cinter4Synth regenerates the PCM from these params.
 *
 * ${presets.length} unique presets from ${files.length} songs.
 * Regenerate: npx tsx scripts/generate-cinter-presets.mts [songsDir]
 */
import type { InstrumentPreset } from '@typedefs/instrument';

export const CINTER_PRESETS: InstrumentPreset['config'][] = ${JSON.stringify(entries, null, 2)} as InstrumentPreset['config'][];
`;

writeFileSync(OUT, header);
console.log(`[cinter-presets] wrote ${presets.length} presets -> ${OUT}`);
