/**
 * calibratedStaticMap.ts — GENERATED by tools/tms5220-audit/extractLetterCalibration.ts.
 * DO NOT EDIT. Single-frame TMS5220 parameters calibrated from A-Z letter recordings.
 * Median K1-K10, mean energy, mean pitch (voiced only), median duration, mode unvoiced.
 */
import type { TMS5220Frame } from '../engine/speech/tms5220PhonemeMap';

export const calibratedStaticMap: Record<string, TMS5220Frame> = {
  " ": {
    k: [8,8,8,8,8,8,8,4,4,4],
    energy: 1,
    pitch: 0,
    unvoiced: false,
    durationMs: 120
  },
  "/H": {
    k: [18,14,8,8,8,8,8,4,4,4],
    energy: 6,
    pitch: 0,
    unvoiced: true,
    durationMs: 80
  },
  "/X": {
    k: [18,14,8,8,8,8,8,4,4,4],
    energy: 6,
    pitch: 0,
    unvoiced: true,
    durationMs: 80
  },
  "AA": {
    k: [11,22,10,11,5,8,9,5,5,2],
    energy: 10,
    pitch: 20,
    unvoiced: false,
    durationMs: 250
  },
  "AE": {
    k: [24,19,10,8,8,7,8,4,4,4],
    energy: 12,
    pitch: 18,
    unvoiced: false,
    durationMs: 150
  },
  "AH": {
    k: [21,11,8,8,7,8,8,4,4,4],
    energy: 12,
    pitch: 16,
    unvoiced: false,
    durationMs: 130
  },
  "AO": {
    k: [19,8,7,9,7,8,8,4,4,4],
    energy: 12,
    pitch: 14,
    unvoiced: false,
    durationMs: 150
  },
  "AW": {
    k: [23,12,8,8,7,8,8,4,4,4],
    energy: 12,
    pitch: 16,
    unvoiced: false,
    durationMs: 200
  },
  "AX": {
    k: [18,14,8,8,8,8,8,4,4,4],
    energy: 10,
    pitch: 16,
    unvoiced: false,
    durationMs: 90
  },
  "AY": {
    k: [13,23,9,9,7,10,12,3,2,4],
    energy: 10,
    pitch: 18,
    unvoiced: false,
    durationMs: 325
  },
  "B*": {
    k: [1,17,10,7,7,10,10,4,2,2],
    energy: 4,
    pitch: 20,
    unvoiced: false,
    durationMs: 125
  },
  "CH": {
    k: [23,26,14,13,8,8,8,4,4,4],
    energy: 8,
    pitch: 0,
    unvoiced: true,
    durationMs: 225
  },
  "D*": {
    k: [18,22,6,10,6,8,7,3,4,3],
    energy: 8,
    pitch: 16,
    unvoiced: false,
    durationMs: 60
  },
  "DX": {
    k: [18,22,6,10,6,8,7,3,4,3],
    energy: 8,
    pitch: 16,
    unvoiced: false,
    durationMs: 40
  },
  "EH": {
    k: [15,17,6,6,8,11,9,3,2,4],
    energy: 10,
    pitch: 17,
    unvoiced: false,
    durationMs: 325
  },
  "ER": {
    k: [18,16,9,9,6,10,7,5,4,4],
    energy: 12,
    pitch: 16,
    unvoiced: false,
    durationMs: 160
  },
  "EY": {
    k: [15,12,5,7,13,11,10,4,2,4],
    energy: 10,
    pitch: 20,
    unvoiced: false,
    durationMs: 350
  },
  "F*": {
    k: [20,17,9,9,8,8,8,4,4,4],
    energy: 7,
    pitch: 0,
    unvoiced: true,
    durationMs: 175
  },
  "G*": {
    k: [16,14,6,10,7,8,8,4,4,4],
    energy: 8,
    pitch: 1,
    unvoiced: false,
    durationMs: 60
  },
  "GX": {
    k: [16,14,6,10,7,8,8,4,4,4],
    energy: 8,
    pitch: 1,
    unvoiced: false,
    durationMs: 60
  },
  "IH": {
    k: [15,25,10,7,9,7,8,3,4,3],
    energy: 12,
    pitch: 18,
    unvoiced: false,
    durationMs: 120
  },
  "IX": {
    k: [14,23,9,7,9,7,8,3,4,3],
    energy: 10,
    pitch: 18,
    unvoiced: false,
    durationMs: 90
  },
  "IY": {
    k: [18,13,2,4,8,14,12,3,2,4],
    energy: 10,
    pitch: 16,
    unvoiced: false,
    durationMs: 375
  },
  "J*": {
    k: [23,26,14,13,8,8,8,4,4,4],
    energy: 9,
    pitch: 16,
    unvoiced: false,
    durationMs: 225
  },
  "K*": {
    k: [24,27,12,10,8,8,8,4,4,4],
    energy: 7,
    pitch: 0,
    unvoiced: true,
    durationMs: 100
  },
  "KX": {
    k: [24,27,12,10,8,8,8,4,4,4],
    energy: 7,
    pitch: 0,
    unvoiced: true,
    durationMs: 100
  },
  "L*": {
    k: [8,14,11,10,1,6,11,3,4,2],
    energy: 10,
    pitch: 12,
    unvoiced: false,
    durationMs: 75
  },
  "LX": {
    k: [8,14,11,10,1,6,11,3,4,2],
    energy: 10,
    pitch: 12,
    unvoiced: false,
    durationMs: 75
  },
  "M*": {
    k: [20,10,4,14,5,10,6,5,3,5],
    energy: 9,
    pitch: 16,
    unvoiced: false,
    durationMs: 120
  },
  "N*": {
    k: [18,19,4,14,5,10,6,5,3,5],
    energy: 9,
    pitch: 16,
    unvoiced: false,
    durationMs: 100
  },
  "NX": {
    k: [16,12,4,14,5,10,6,5,3,5],
    energy: 9,
    pitch: 16,
    unvoiced: false,
    durationMs: 120
  },
  "OH": {
    k: [19,8,7,9,7,8,8,4,4,4],
    energy: 12,
    pitch: 14,
    unvoiced: false,
    durationMs: 150
  },
  "OW": {
    k: [7,19,13,8,4,5,10,4,5,4],
    energy: 10,
    pitch: 20,
    unvoiced: false,
    durationMs: 300
  },
  "OY": {
    k: [19,8,7,9,7,8,8,4,4,4],
    energy: 12,
    pitch: 14,
    unvoiced: false,
    durationMs: 200
  },
  "P*": {
    k: [19,19,10,8,8,8,8,4,4,4],
    energy: 7,
    pitch: 0,
    unvoiced: true,
    durationMs: 50
  },
  "Q*": {
    k: [8,8,8,8,8,8,8,4,4,4],
    energy: 1,
    pitch: 0,
    unvoiced: true,
    durationMs: 20
  },
  "R*": {
    k: [13,17,10,4,9,12,5,4,6,1],
    energy: 10,
    pitch: 14,
    unvoiced: false,
    durationMs: 125
  },
  "RX": {
    k: [13,17,10,4,9,12,5,4,6,1],
    energy: 10,
    pitch: 14,
    unvoiced: false,
    durationMs: 125
  },
  "S*": {
    k: [29,21,7,9,8,8,8,4,4,4],
    energy: 7,
    pitch: 0,
    unvoiced: true,
    durationMs: 250
  },
  "SH": {
    k: [12,22,13,13,10,6,9,3,5,3],
    energy: 10,
    pitch: 0,
    unvoiced: true,
    durationMs: 140
  },
  "T*": {
    k: [24,20,12,8,8,8,8,4,4,4],
    energy: 7,
    pitch: 0,
    unvoiced: true,
    durationMs: 75
  },
  "TH": {
    k: [8,24,12,8,10,5,8,2,6,2],
    energy: 5,
    pitch: 0,
    unvoiced: true,
    durationMs: 120
  },
  "UH": {
    k: [17,13,7,9,7,8,8,4,4,4],
    energy: 12,
    pitch: 14,
    unvoiced: false,
    durationMs: 120
  },
  "UW": {
    k: [8,15,9,7,6,6,8,6,5,2],
    energy: 10,
    pitch: 19,
    unvoiced: false,
    durationMs: 250
  },
  "UX": {
    k: [8,15,9,7,6,6,8,6,5,2],
    energy: 10,
    pitch: 19,
    unvoiced: false,
    durationMs: 250
  },
  "V*": {
    k: [20,17,9,9,8,8,8,4,4,4],
    energy: 8,
    pitch: 16,
    unvoiced: false,
    durationMs: 175
  },
  "W*": {
    k: [5,27,11,8,4,7,9,3,4,3],
    energy: 10,
    pitch: 18,
    unvoiced: false,
    durationMs: 150
  },
  "WH": {
    k: [5,27,11,8,4,7,9,3,4,3],
    energy: 7,
    pitch: 0,
    unvoiced: true,
    durationMs: 150
  },
  "WX": {
    k: [5,27,11,8,4,7,9,3,4,3],
    energy: 10,
    pitch: 18,
    unvoiced: false,
    durationMs: 150
  },
  "Y*": {
    k: [19,7,1,7,9,11,11,5,2,2],
    energy: 10,
    pitch: 19,
    unvoiced: false,
    durationMs: 150
  },
  "YX": {
    k: [19,7,1,7,9,11,11,5,2,2],
    energy: 10,
    pitch: 19,
    unvoiced: false,
    durationMs: 150
  },
  "Z*": {
    k: [29,21,7,9,8,8,8,4,4,4],
    energy: 9,
    pitch: 16,
    unvoiced: false,
    durationMs: 250
  },
};
