/**
 * exportPhonemeLibrary.ts — mine the authentic TMS5220 phoneme library out of
 * the Speak & Spell VSM ROMs and emit src/generated/tms5220Phonemes.ts.
 *
 * The hand-authored static table in tms5220PhonemeMap.ts is a single-frame
 * approximation; the ROM-mined library carries the real TI recordings. This
 * tool serializes that library so phoneme synthesis sounds the same with and
 * without the ROM loaded.
 *
 * Usage: npx tsx --tsconfig tsconfig.app.json tools/tms5220-audit/exportPhonemeLibrary.ts
 */
import { readFileSync, writeFileSync } from 'fs';
import { join } from 'path';
import { fileURLToPath } from 'url';
import { parseVSMDirectory } from '../../src/engine/speech/VSMROMParser';
import { buildCompletePhonemeLibrary } from '../../src/engine/speech/ROMPhonemeExtractor';
import type { TMS5220Frame } from '../../src/engine/speech/tms5220PhonemeMap';

const ROOT = join(fileURLToPath(import.meta.url), '..', '..', '..');

function emitModule(entries: Array<[string, TMS5220Frame[]]>): string {
  const lines: string[] = [];
  lines.push(`/**
 * tms5220Phonemes.ts — GENERATED by tools/tms5220-audit/exportPhonemeLibrary.ts.
 * DO NOT EDIT. Authentic TMS5220 phoneme segments mined from the Speak & Spell
 * VSM ROMs (letter recordings + spelling-word segmentation). Used as the
 * phoneme library when no ROM is loaded at runtime.
 */
import type { TMS5220Frame } from '../engine/speech/tms5220PhonemeMap';

export const AUTHENTIC_PHONEMES: Record<string, TMS5220Frame[]> = {`);
  for (const [code, frames] of entries) {
    lines.push(`  ${JSON.stringify(code)}: [`);
    for (const f of frames) {
      lines.push(
        `    { k: ${JSON.stringify(f.k)}, energy: ${f.energy}, pitch: ${f.pitch}, unvoiced: ${f.unvoiced}, durationMs: ${f.durationMs} },`,
      );
    }
    lines.push('  ],');
  }
  lines.push('};');
  lines.push('');
  return lines.join('\n');
}

const rom = Buffer.concat([
  readFileSync(join(ROOT, 'public/roms/snspell/tmc0351n2l.vsm')),
  readFileSync(join(ROOT, 'public/roms/snspell/tmc0352n2l.vsm')),
]);
const { library } = buildCompletePhonemeLibrary(parseVSMDirectory(rom));

const entries = [...library.entries()].sort(([a], [b]) => a.localeCompare(b));
const totalFrames = entries.reduce((sum, [, frames]) => sum + frames.length, 0);

const outPath = join(ROOT, 'src/generated/tms5220Phonemes.ts');
writeFileSync(outPath, emitModule(entries));
console.log(`wrote ${outPath} (${entries.length} phonemes, ${totalFrames} frames)`);