/**
 * extractLetterCalibration.ts — derive a single-frame static TMS5220 map from
 * the 26 A-Z letter recordings in the VSM ROM.
 *
 * This replaces the hand-authored samToTMS5220 map with values calibrated from
 * authentic TI recordings, so TTS ("devilbox") matches ROM character speech
 * ("welcome").
 *
 * Aggregation (locked decisions):
 *   K1-K10      → median across all frames (robust to boundary outliers)
 *   energy      → mean across all frames
 *   pitch       → mean across voiced frames only (pitch > 0)
 *   durationMs  → median(frameCount) * 25
 *   unvoiced    → mode (majority vote) across frames
 *
 * Missing phonemes (SH, ZH, TH, DH, DX, Q*, WH, /X, KX, GX, LX, WX, YX, RX,
 * IX, UX, OH, OY, AW, UW) fall back to hand-authored values at synthesis time.
 *
 * Usage: npx tsx --tsconfig tsconfig.app.json tools/tms5220-audit/extractLetterCalibration.ts
 */
import { readFileSync, writeFileSync } from 'fs';
import { join } from 'path';
import { fileURLToPath } from 'url';
import { parseVSMDirectory } from '../../src/engine/speech/VSMROMParser';
import { extractPhonemeLibrary } from '../../src/engine/speech/ROMPhonemeExtractor';
import type { TMS5220Frame } from '../../src/engine/speech/tms5220PhonemeMap';

const ROOT = join(fileURLToPath(import.meta.url), '..', '..', '..');

function median<T>(arr: T[], selector: (x: T) => number): number {
  if (arr.length === 0) return 0;
  const sorted = [...arr].sort((a, b) => selector(a) - selector(b));
  const mid = Math.floor(sorted.length / 2);
  return sorted.length % 2 === 0
    ? (selector(sorted[mid - 1]) + selector(sorted[mid])) / 2
    : selector(sorted[mid]);
}

function mean(arr: number[]): number {
  if (arr.length === 0) return 0;
  return arr.reduce((a, b) => a + b, 0) / arr.length;
}

function mode<T>(arr: T[]): T {
  if (arr.length === 0) return arr[0] as T;
  const counts = new Map<T, number>();
  for (const v of arr) counts.set(v, (counts.get(v) ?? 0) + 1);
  let best = arr[0];
  let bestCount = 0;
  for (const [v, c] of counts) {
    if (c > bestCount) { best = v; bestCount = c; }
  }
  return best;
}

function emitModule(entries: Array<[string, TMS5220Frame]>): string {
  const lines: string[] = [];
  lines.push(`/**
 * calibratedStaticMap.ts — GENERATED by tools/tms5220-audit/extractLetterCalibration.ts.
 * DO NOT EDIT. Single-frame TMS5220 parameters calibrated from A-Z letter recordings.
 * Median K1-K10, mean energy, mean pitch (voiced only), median duration, mode unvoiced.
 */
import type { TMS5220Frame } from '../engine/speech/tms5220PhonemeMap';

export const calibratedStaticMap: Record<string, TMS5220Frame> = {`);
  for (const [code, frame] of entries) {
    lines.push(`  ${JSON.stringify(code)}: {`);
    lines.push(`    k: ${JSON.stringify(frame.k)},`);
    lines.push(`    energy: ${frame.energy},`);
    lines.push(`    pitch: ${frame.pitch},`);
    lines.push(`    unvoiced: ${frame.unvoiced},`);
    lines.push(`    durationMs: ${frame.durationMs}`);
    lines.push(`  },`);
  }
  lines.push('};');
  lines.push('');
  return lines.join('\n');
}

const rom = Buffer.concat([
  readFileSync(join(ROOT, 'public/roms/snspell/tmc0351n2l.vsm')),
  readFileSync(join(ROOT, 'public/roms/snspell/tmc0352n2l.vsm')),
]);
const words = parseVSMDirectory(new Uint8Array(rom));
const letterLib = extractPhonemeLibrary(words.slice(0, 26));

const calibrated: Array<[string, TMS5220Frame]> = [];

for (const [code, frames] of letterLib) {
  if (frames.length === 0) continue;

  // K1-K10: median per coefficient
  const k: number[] = [];
  for (let i = 0; i < 10; i++) {
    k.push(Math.round(median(frames, f => f.k[i] ?? 0)));
  }

  // Energy: mean
  const energy = Math.round(mean(frames.map(f => f.energy)));

  // Pitch: mean over voiced frames only
  const voicedPitches = frames.filter(f => f.pitch > 0).map(f => f.pitch);
  const pitch = voicedPitches.length > 0
    ? Math.round(mean(voicedPitches))
    : 0;

  // Duration: median frame count * 25ms
  const durationMs = Math.round(median([frames], f => f.length) * 25);

  // Unvoiced: mode
  const unvoiced = mode(frames.map(f => f.unvoiced));

  calibrated.push([code, { k, energy, pitch, unvoiced, durationMs }]);
}

calibrated.sort(([a], [b]) => a.localeCompare(b));

const outPath = join(ROOT, 'tools/tms5220-audit/calibratedStaticMap.ts');
writeFileSync(outPath, emitModule(calibrated));
console.log(`wrote ${outPath} (${calibrated.length} phonemes calibrated from letters)`);
for (const [code, f] of calibrated) {
  console.log(`  ${code}: K=[${f.k.join(',')}], energy=${f.energy}, pitch=${f.pitch}, unvoiced=${f.unvoiced}, dur=${f.durationMs}ms`);
}
