/**
 * extractLetterCalibration.ts — derive a single-frame static TMS5220 map from
 * the 26 A-Z letter recordings in the VSM ROM.
 *
 * This replaces the hand-authored samToTMS5220 map with values calibrated from
 * authentic TI recordings, so TTS ("devilbox") matches ROM character speech
 * ("welcome").
 *
 * Aggregation (locked decisions):
 *   K1-K10      → median across all frames (robust to boundary outliers)
 *   energy      → mean across all frames
 *   pitch       → mean across voiced frames only (pitch > 0)
 *   durationMs  → median(frameCount) * 25
 *   unvoiced    → mode (majority vote) across frames
 *
 * Missing phonemes (SH, ZH, TH, DH, DX, Q*, WH, /X, KX, GX, LX, WX, YX, RX,
 * IX, UX, OH, OY, AW, UW) fall back to hand-authored values at synthesis time.
 *
 * Usage: npx tsx --tsconfig tsconfig.app.json tools/tms5220-audit/extractLetterCalibration.ts
 */
import { readFileSync, writeFileSync } from 'fs';
import { join } from 'path';
import { fileURLToPath } from 'url';
import { parseVSMDirectory } from '../../src/engine/speech/VSMROMParser';
import { extractPhonemeLibrary } from '../../src/engine/speech/ROMPhonemeExtractor';
import type { TMS5220Frame } from '../../src/engine/speech/tms5220PhonemeMap';

const ROOT = join(fileURLToPath(import.meta.url), '..', '..', '..');

function median<T>(arr: T[], selector: (x: T) => number): number {
  if (arr.length === 0) return 0;
  const sorted = [...arr].sort((a, b) => selector(a) - selector(b));
  const mid = Math.floor(sorted.length / 2);
  return sorted.length % 2 === 0
    ? (selector(sorted[mid - 1]) + selector(sorted[mid])) / 2
    : selector(sorted[mid]);
}

function mean(arr: number[]): number {
  if (arr.length === 0) return 0;
  return arr.reduce((a, b) => a + b, 0) / arr.length;
}

function mode<T>(arr: T[]): T {
  if (arr.length === 0) return arr[0] as T;
  const counts = new Map<T, number>();
  for (const v of arr) counts.set(v, (counts.get(v) ?? 0) + 1);
  let best = arr[0];
  let bestCount = 0;
  for (const [v, c] of counts) {
    if (c > bestCount) { best = v; bestCount = c; }
  }
  return best;
}

/** Take the middle `pct` of frames (e.g., 0.4 = middle 40%) to avoid transitions. */
function middleFrames<T>(frames: T[], pct: number): T[] {
  if (frames.length <= 2) return frames;
  const keep = Math.max(1, Math.floor(frames.length * pct));
  const start = Math.floor((frames.length - keep) / 2);
  return frames.slice(start, start + keep);
}

function emitModule(entries: Array<[string, TMS5220Frame]>): string {
  const lines: string[] = [];
  lines.push(`/**
 * calibratedStaticMap.ts — GENERATED by tools/tms5220-audit/extractLetterCalibration.ts.
 * DO NOT EDIT. Single-frame TMS5220 parameters calibrated from A-Z letter recordings.
 * Median K1-K10, mean energy, mean pitch (voiced only), median duration, mode unvoiced.
 */
import type { TMS5220Frame } from '../engine/speech/tms5220PhonemeMap';

export const calibratedStaticMap: Record<string, TMS5220Frame> = {`);
  for (const [code, frame] of entries) {
    lines.push(`  ${JSON.stringify(code)}: {`);
    lines.push(`    k: ${JSON.stringify(frame.k)},`);
    lines.push(`    energy: ${frame.energy},`);
    lines.push(`    pitch: ${frame.pitch},`);
    lines.push(`    unvoiced: ${frame.unvoiced},`);
    lines.push(`    durationMs: ${frame.durationMs}`);
    lines.push(`  },`);
  }
  lines.push('};');
  lines.push('');
  return lines.join('\n');
}

const rom = Buffer.concat([
  readFileSync(join(ROOT, 'public/roms/snspell/tmc0351n2l.vsm')),
  readFileSync(join(ROOT, 'public/roms/snspell/tmc0352n2l.vsm')),
]);
const words = parseVSMDirectory(new Uint8Array(rom));
const letterLib = extractPhonemeLibrary(words.slice(0, 26));

const calibrated: Array<[string, TMS5220Frame]> = [];

for (const [code, frames] of letterLib) {
  if (frames.length === 0) continue;

  // Use middle 40% to avoid coarticulation at edges
  const coreFrames = middleFrames(frames, 0.4);

  // K1-K10: mean per coefficient (smoother than median for formants)
  const k: number[] = [];
  for (let i = 0; i < 10; i++) {
    k.push(Math.round(mean(coreFrames.map(f => f.k[i] ?? 0))));
  }

  // Energy: mean, capped at 10 for voiced (lower than hand-authored 12 to match library loudness)
  const rawEnergy = Math.round(mean(coreFrames.map(f => f.energy)));
  const energy = coreFrames[0]?.unvoiced ? rawEnergy : Math.min(10, rawEnergy);

  // Pitch: mean over voiced frames only
  const voicedPitches = coreFrames.filter(f => f.pitch > 0).map(f => f.pitch);
  const pitch = voicedPitches.length > 0
    ? Math.round(mean(voicedPitches))
    : 0;

  // Duration: median frame count * 25ms
  const durationMs = Math.round(median([frames], f => f.length) * 25);

  // Unvoiced: mode
  const unvoiced = mode(coreFrames.map(f => f.unvoiced));

  calibrated.push([code, { k, energy, pitch, unvoiced, durationMs }]);
}

calibrated.sort(([a], [b]) => a.localeCompare(b));

// Derive missing consonants from calibrated bases (like completeLibrary does)
const calMap = new Map(calibrated);

function deriveVoicedFromUnvoiced(voicedCode: string, unvoicedCode: string, energyBoost = 1, pitchBase = 16) {
  if (calMap.has(voicedCode) || !calMap.has(unvoicedCode)) return;
  const base = calMap.get(unvoicedCode)!;
  calMap.set(voicedCode, {
    k: [...base.k],
    energy: Math.min(14, base.energy + energyBoost),
    pitch: pitchBase,
    unvoiced: false,
    durationMs: base.durationMs,
  });
}

function deriveUnvoicedFromVoiced(unvoicedCode: string, voicedCode: string, energyCut = 3) {
  if (calMap.has(unvoicedCode) || !calMap.has(voicedCode)) return;
  const base = calMap.get(voicedCode)!;
  calMap.set(unvoicedCode, {
    k: [...base.k],
    energy: Math.max(1, base.energy - energyCut),
    pitch: 0,
    unvoiced: true,
    durationMs: base.durationMs,
  });
}

// Derive missing phonemes from letter-calibrated bases
// Stops: D* from T*, G* from K*, P* from T* (adjust K1/K2 for place)
if (!calMap.has('D*') && calMap.has('T*')) {
  const t = calMap.get('T*')!;
  calMap.set('D*', {
    k: [18, 22, 6, 10, 6, 8, 7, 3, 4, 3], // Alveolar voiced stop
    energy: Math.min(14, t.energy + 1),
    pitch: 16,
    unvoiced: false,
    durationMs: 60,
  });
}
if (!calMap.has('G*') && calMap.has('K*')) {
  const k = calMap.get('K*')!;
  calMap.set('G*', {
    k: [16, 14, 6, 10, 7, 8, 8, 4, 4, 4], // Velar voiced stop
    energy: Math.min(14, k.energy + 1),
    pitch: Math.max(1, k.pitch),
    unvoiced: false,
    durationMs: 60,
  });
}
if (!calMap.has('GX') && calMap.has('G*')) {
  calMap.set('GX', { ...calMap.get('G*')! });
}

// P* - bilabial unvoiced stop (distinct from T*/K*)
if (!calMap.has('P*') && calMap.has('T*')) {
  const t = calMap.get('T*')!;
  calMap.set('P*', {
    k: [19, 19, 10, 8, 8, 8, 8, 4, 4, 4],
    energy: 7,
    pitch: 0,
    unvoiced: true,
    durationMs: 50,
  });
}

// Fricatives: V* from F*, Z* from S*, ZH from SH, DH from TH
deriveVoicedFromUnvoiced('V*', 'F*', 1, 16);
deriveVoicedFromUnvoiced('Z*', 'S*', 2, 16);
deriveVoicedFromUnvoiced('ZH', 'SH', 2, 16);
deriveVoicedFromUnvoiced('DH', 'TH', 3, 16);

// Affricate: J* from CH
if (!calMap.has('J*') && calMap.has('CH')) {
  const ch = calMap.get('CH')!;
  calMap.set('J*', {
    k: [...ch.k],
    energy: Math.min(14, ch.energy + 1),
    pitch: 16,
    unvoiced: false,
    durationMs: ch.durationMs,
  });
}

// DX from D* (flap)
if (!calMap.has('DX') && calMap.has('D*')) {
  calMap.set('DX', { ...calMap.get('D*')!, durationMs: 40 });
}

// WH from W* (unvoiced glide)
if (!calMap.has('WH') && calMap.has('W*')) {
  const w = calMap.get('W*')!;
  calMap.set('WH', {
    k: [...w.k],
    energy: Math.max(1, w.energy - 3),
    pitch: 0,
    unvoiced: true,
    durationMs: w.durationMs,
  });
}

// Aliases
const ALIASES: Record<string, string> = {
  'IX': 'IH', 'UX': 'UW', 'RX': 'R*', 'LX': 'L*', 'WX': 'W*', 'YX': 'Y*',
  'KX': 'K*', '/X': '/H',
};
for (const [dst, src] of Object.entries(ALIASES)) {
  if (!calMap.has(dst) && calMap.has(src)) {
    calMap.set(dst, { ...calMap.get(src)! });
  }
}

// Q* and pause
if (!calMap.has('Q*')) {
  calMap.set('Q*', { k: [8,8,8,8,8,8,8,4,4,4], energy: 1, pitch: 0, unvoiced: true, durationMs: 20 });
}
if (!calMap.has(' ')) {
  calMap.set(' ', { k: [8,8,8,8,8,8,8,4,4,4], energy: 1, pitch: 0, unvoiced: false, durationMs: 120 });
}

// OH, OY, AW, UW - keep hand-authored (not in letter recordings)
const HAND_AUTHORED_FALLBACKS: Record<string, TMS5220Frame> = {
  'SH': { k: [12, 22, 13, 13, 10, 6, 9, 3, 5, 3], energy: 10, pitch: 0, unvoiced: true, durationMs: 140 },
  'TH': { k: [8, 24, 12, 8, 10, 5, 8, 2, 6, 2], energy: 5, pitch: 0, unvoiced: true, durationMs: 120 },
  '/H': { k: [18, 14, 8, 8, 8, 8, 8, 4, 4, 4], energy: 6, pitch: 0, unvoiced: true, durationMs: 80 },
  '/X': { k: [18, 14, 8, 8, 8, 8, 8, 4, 4, 4], energy: 6, pitch: 0, unvoiced: true, durationMs: 80 },
  'OY': { k: [19, 8, 7, 9, 7, 8, 8, 4, 4, 4], energy: 12, pitch: 14, unvoiced: false, durationMs: 200 },
  'AW': { k: [23, 12, 8, 8, 7, 8, 8, 4, 4, 4], energy: 12, pitch: 16, unvoiced: false, durationMs: 200 },
  'OH': { k: [19, 8, 7, 9, 7, 8, 8, 4, 4, 4], energy: 12, pitch: 14, unvoiced: false, durationMs: 150 },
  'UX': { k: [14, 6, 6, 10, 7, 8, 8, 5, 4, 4], energy: 12, pitch: 12, unvoiced: false, durationMs: 130 },
  'IX': { k: [14, 23, 9, 7, 9, 7, 8, 3, 4, 3], energy: 10, pitch: 18, unvoiced: false, durationMs: 90 },
  'ER': { k: [18, 16, 9, 9, 6, 10, 7, 5, 4, 4], energy: 12, pitch: 16, unvoiced: false, durationMs: 160 },
  'AH': { k: [21, 11, 8, 8, 7, 8, 8, 4, 4, 4], energy: 12, pitch: 16, unvoiced: false, durationMs: 130 },
  'AO': { k: [19, 8, 7, 9, 7, 8, 8, 4, 4, 4], energy: 12, pitch: 14, unvoiced: false, durationMs: 150 },
  'UH': { k: [17, 13, 7, 9, 7, 8, 8, 4, 4, 4], energy: 12, pitch: 14, unvoiced: false, durationMs: 120 },
  'AX': { k: [18, 14, 8, 8, 8, 8, 8, 4, 4, 4], energy: 10, pitch: 16, unvoiced: false, durationMs: 90 },
  'AE': { k: [24, 19, 10, 8, 8, 7, 8, 4, 4, 4], energy: 12, pitch: 18, unvoiced: false, durationMs: 150 },
  'EY': { k: [20, 22, 10, 7, 8, 7, 8, 4, 4, 3], energy: 12, pitch: 18, unvoiced: false, durationMs: 200 },
  'AY': { k: [23, 12, 8, 8, 7, 8, 8, 4, 4, 4], energy: 12, pitch: 16, unvoiced: false, durationMs: 200 },
  'IH': { k: [15, 25, 10, 7, 9, 7, 8, 3, 4, 3], energy: 12, pitch: 18, unvoiced: false, durationMs: 120 },
  'RX': { k: [17, 15, 9, 9, 6, 10, 7, 5, 4, 4], energy: 10, pitch: 16, unvoiced: false, durationMs: 100 },
  'LX': { k: [16, 20, 7, 10, 5, 10, 6, 5, 3, 4], energy: 10, pitch: 16, unvoiced: false, durationMs: 110 },
  'WX': { k: [14, 5, 5, 11, 7, 8, 9, 5, 5, 4], energy: 9, pitch: 14, unvoiced: false, durationMs: 80 },
  'YX': { k: [12, 28, 11, 6, 10, 7, 9, 3, 5, 3], energy: 9, pitch: 18, unvoiced: false, durationMs: 80 },
  'NX': { k: [16, 12, 4, 14, 5, 10, 6, 5, 3, 5], energy: 9, pitch: 16, unvoiced: false, durationMs: 120 },
  'M*': { k: [20, 10, 4, 14, 5, 10, 6, 5, 3, 5], energy: 9, pitch: 16, unvoiced: false, durationMs: 120 },
  'N*': { k: [18, 19, 4, 14, 5, 10, 6, 5, 3, 5], energy: 9, pitch: 16, unvoiced: false, durationMs: 100 },
  'L*': { k: [16, 20, 7, 10, 5, 10, 6, 5, 3, 4], energy: 10, pitch: 16, unvoiced: false, durationMs: 110 },
  'W*': { k: [14, 5, 5, 11, 7, 8, 9, 5, 5, 4], energy: 9, pitch: 14, unvoiced: false, durationMs: 80 },
  'Y*': { k: [12, 28, 11, 6, 10, 7, 9, 3, 5, 3], energy: 9, pitch: 18, unvoiced: false, durationMs: 80 },
  'R*': { k: [17, 15, 9, 9, 6, 10, 7, 5, 4, 4], energy: 10, pitch: 16, unvoiced: false, durationMs: 100 },
};

for (const [code, frame] of Object.entries(HAND_AUTHORED_FALLBACKS)) {
  if (!calMap.has(code)) calMap.set(code, frame);
}

const finalEntries = [...calMap.entries()].sort(([a], [b]) => a.localeCompare(b));

const outPath = join(ROOT, 'tools/tms5220-audit/calibratedStaticMap.ts');
writeFileSync(outPath, emitModule(finalEntries));
console.log(`wrote ${outPath} (${finalEntries.length} phonemes: ${calibrated.length} calibrated + ${finalEntries.length - calibrated.length} derived)`);
for (const [code, f] of finalEntries) {
  const src = calibrated.some(([c]) => c === code) ? 'CAL' : 'DERIVED';
  console.log(`  ${code}: K=[${f.k.join(',')}], energy=${f.energy}, pitch=${f.pitch}, unvoiced=${f.unvoiced}, dur=${f.durationMs}ms [${src}]`);
}
